Patch 1
home-assistant/home-assistant.github.io pull request #10211
Opened 2019-08-22 20:07 UTC by oischinger

**Description:**

This PR adds documentation for the Viessmann ViCare climate component. 

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-08-22 23:29 UTC, klaasnicolaas requested changes

2019-08-22 23:29 UTC, klaasnicolaas commented on source/_components/vicare.markdown
> +    username: [VICARE_EMAIL]
```suggestion
    username: VICARE_EMAIL
```

2019-08-22 23:29 UTC, klaasnicolaas commented on source/_components/vicare.markdown
> +    password: [VICARE_PASSWORD]
```suggestion
    password: VICARE_PASSWORD
```

2019-08-22 23:29 UTC, klaasnicolaas commented on source/_components/vicare.markdown
> +### Supported services
Maybe add some more information about the services

2019-08-22 23:29 UTC, klaasnicolaas commented on source/_components/vicare.markdown
> +ha_release: 0.97
```suggestion
ha_release: 0.99
```

2019-08-23 08:53 UTC, klaasnicolaas submitted a review, later dismissed

2019-08-23 08:53 UTC, klaasnicolaas commented on source/_components/vicare.markdown
> +  default: defaults to the first heating circuit of your installation
```suggestion
  default: -1
```

The info about it can you put in the description of somewhere else

2019-08-23 08:53 UTC, klaasnicolaas commented on source/_components/vicare.markdown
> +{% configuration %}
missing also the `name` config variable

2019-09-06 20:19 UTC, MartinHjelmare requested changes

2019-09-06 20:19 UTC, MartinHjelmare commented on source/_components/vicare.markdown
> +ha_iot_class: Cloud Push
```suggestion
ha_iot_class: Cloud Polling
```

2019-09-06 20:19 UTC, MartinHjelmare commented on source/_components/vicare.markdown
> +  default: -1
We didn't add a default for the circuit.

2019-09-06 20:19 UTC, MartinHjelmare commented on source/_components/vicare.markdown
> +A note about the current temperature attribute: Viessmann devices with room temperature sensing will shown the current room temperature via `current_temperature`. All other devices will show the curr
```suggestion
A note about the current temperature attribute: Viessmann devices with room temperature sensing will show the current room temperature via `current_temperature`. All other devices will show the current supply temperature of the heating circuit.
```

2019-09-06 20:19 UTC, MartinHjelmare commented on source/_components/vicare.markdown
> +| `hold_mode` | no | New value of hold mode.
```suggestion
| `preset_mode` | no | New value of hold mode.
```

2019-09-06 20:19 UTC, MartinHjelmare commented on source/_components/vicare.markdown
> +| `entity_id` | yes | String or list of strings that point at `entity_id`'s of water heater devices to control. Else targets all.
To target all entities, use `all` keyword instead of entity_id.

2019-09-06 20:19 UTC, MartinHjelmare commented on source/_components/vicare.markdown
> +| `entity_id` | yes | String or list of strings that point at `entity_id`'s of climate devices to control. Else targets all.
To target all entities, use `all` keyword instead of entity_id.

2019-09-06 20:19 UTC, MartinHjelmare commented on source/_components/vicare.markdown
> +| `entity_id` | yes | String or list of strings that point at `entity_id`'s of climate devices to control. Else targets all.
To target all entities, use `all` keyword instead of entity_id.

2019-09-06 20:19 UTC, MartinHjelmare commented on source/_components/vicare.markdown
> +| `entity_id` | yes | String or list of strings that point at `entity_id`'s of climate devices to control. Else targets all.
To target all entities, use `all` keyword instead of entity_id.

2019-09-06 20:57 UTC, MartinHjelmare commented on source/_components/vicare.markdown
> +| `entity_id` | yes | String or list of strings that point at `entity_id`'s of water heater devices to control. Else targets all.
This is still left.

2019-09-06 21:20 UTC, MartinHjelmare submitted a review, later dismissed

2019-09-07 20:04 UTC, frenck commented
Thanks for making it perfect @oischinger! 👍 

Let's merge this in! 🎉

2019-09-07 20:04 UTC, frenck approved these changes

2019-09-07 20:04 UTC, merged