Added doods component documentation
home-assistant/home-assistant.github.io pull request #10228
Opened 2019-08-26 03:08 UTC by snowzach

**Description:**
Add support for DOODS Object Detection Service

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-08-26 08:32 UTC, klaasnicolaas requested changes

2019-08-26 08:32 UTC, klaasnicolaas commented on source/_components/doods.markdown
> +ha_release: 0.82
```suggestion
ha_release: 0.99
```

2019-08-26 08:32 UTC, klaasnicolaas commented on source/_components/doods.markdown
> +redirect_from:
Please remove the `redirect_from`

2019-08-26 08:32 UTC, klaasnicolaas commented on source/_components/doods.markdown
> +logo: home-assistant.png
The Home Assistant logo can only be used for own integrations, so please remove the line if there is no logo.

2019-08-26 08:32 UTC, klaasnicolaas commented on source/_components/doods.markdown
> +image_processing:
Only required config variables in the first example.

2019-08-28 03:05 UTC, snowzach commented on source/_components/doods.markdown
> +logo: home-assistant.png
Updated.

2019-08-28 03:06 UTC, snowzach commented on source/_components/doods.markdown
> +image_processing:
@klaasnicolaas removed optional items.

2019-08-28 08:29 UTC, klaasnicolaas commented
just remove the `redirect_from` and then we can further review your PR.

2019-08-28 08:31 UTC, klaasnicolaas commented on source/_components/doods.markdown
> +You need to have DOODS running somewhere. It's easiest to run as a docker container and deployment is described on docker hub
Would be great if you could make an add-on of this docker container so that it is easy to set up in HA.

2019-08-28 12:45 UTC, snowzach commented
> 
> 
> just remove the `redirect_from` and then we can further review your PR.

Sure, that's done.

2019-08-28 12:46 UTC, snowzach commented on source/_components/doods.markdown
> +You need to have DOODS running somewhere. It's easiest to run as a docker container and deployment is described on docker hub
Once I get the component accepted, I'll work on that.

2019-09-01 11:25 UTC, snowzach commented on source/_components/doods.markdown
> +redirect_from:
Done

2019-09-02 19:49 UTC, klaasnicolaas approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2019-09-11 20:53 UTC, MartinHjelmare commented on source/_components/doods.markdown
> +ha_release: 0.99
0.100

2019-09-11 20:54 UTC, arsaboo commented
Merging this as the parent is merged...thanks @snowzach 🎉

2019-09-11 20:55 UTC, merged

2019-09-11 20:59 UTC, MartinHjelmare commented
Can someone address the `ha_release` change needed?