Update remote_rpi_gpio.markdown
home-assistant/home-assistant.github.io pull request #10274
Opened 2019-09-02 15:33 UTC by Kdemontf

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-09-02 16:15 UTC, frenck requested changes
I've reviewed your PR @Kdemontf, and left some comments. Could you please take a look? Thanks! 👍

2019-09-02 16:15 UTC, frenck commented on source/_components/remote_rpi_gpio.markdown
> +The `rpi_gpio` integration is the base for all related GPIO platforms in Home Assistant. For the platform configurations please check their corresponding sections. The remote RPi(where the GPIO pins
This is a lot of wording.. which makes it hard to read.
Try to add some paragraphs, make links actual text links and code fence the environment examples.

2019-09-02 16:15 UTC, frenck commented on source/_components/remote_rpi_gpio.markdown
> +If you receive an error such as "gpiozero.exc.BadPinFactory: Unable to load any default pin factory!" try changing the pinfactory from "pigpio" to "mock", this adresses a known issue see: https://www
Please use code fences instead of quotes (`"`). Instead of using a full link, try to link a piece of text.

2019-09-02 20:14 UTC, Kdemontf commented
Franck, I have tried to address the issues you pointed out, thanks. This is
the first time I have used Github, so patience is appreciated if I have not
done this correctly. I seem to have saved more changes than I thought I
did.... not sure how

On Mon, 2 Sep 2019 at 12:15, Franck Nijhof <notifications@github.com> wrote:

> *@frenck* requested changes on this pull request.
>
> I've reviewed your PR @Kdemontf <https://github.com/Kdemontf>, and left
> some comments. Could you please take a look? Thanks! 👍
> ------------------------------
>
> In source/_components/remote_rpi_gpio.markdown
> <https://github.com/home-assistant/home-assistant.io/pull/10274#discussion_r320011735>
> :
>
> > @@ -10,7 +10,8 @@ ha_release: 0.94
>
>  ha_iot_class: Local Push
>
>  ---
>
>
>
> -The `rpi_gpio` integration is the base for all related GPIO platforms in Home Assistant. There is no setup needed for the integration itself, for the platforms please check their corresponding sections.
>
> +The `rpi_gpio` integration is the base for all related GPIO platforms in Home Assistant. For the platform configurations please check their corresponding sections. The remote RPi(where the GPIO pins you want to control are) and the control computer (where homeassistant is running) must be prepared to run remote_rpi_gpio. The pigpio library must be available on both computers and the pigpiod daemon running on the RPi. See details here: https://gpiozero.readthedocs.io/en/stable/remote_gpio.html. Note that for virtual environments you may need to set an environment variable when starting the environment to set the pin factory, example: Environment =  GPIOZERO_PIN_FACTORY=pigpio PIGPIO_ADDR=YOUR_RPi_IP_ADDRESS. See your operating system documentation for information on how to set this variable.
>
>
> This is a lot of wording.. which makes it hard to read.
> Try to add some paragraphs, make links actual text links and code fence
> the environment examples.
> ------------------------------
>
> In source/_components/remote_rpi_gpio.markdown
> <https://github.com/home-assistant/home-assistant.io/pull/10274#discussion_r320011972>
> :
>
> > @@ -113,3 +114,7 @@ switch:
>
>      ports:
>
>        17: Speaker Relay
>
>  ```
>
> +
>
> +### Troubleshooting
>
> +
>
> +If you receive an error such as "gpiozero.exc.BadPinFactory: Unable to load any default pin factory!" try changing the pinfactory from "pigpio" to "mock", this adresses a known issue see: https://www.raspberrypi.org/forums/viewtopic.php?p=1417922
>
> Please use code fences instead of quotes ("). Instead of using a full
> link, try to link a piece of text.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/home-assistant/home-assistant.io/pull/10274?email_source=notifications&email_token=ALZ5FOWAL3RHDGXBOPH45ALQHU3ZHA5CNFSM4IS6SSN2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCDMRMDY#pullrequestreview-282662415>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALZ5FOX732BTGOVMUHNQLP3QHU3ZHANCNFSM4IS6SSNQ>
> .
>

2019-09-03 08:57 UTC, frenck approved these changes
Thanks for updating @Kdemontf! You did fine! 🏅

2019-09-03 08:59 UTC, merged