SmartThings integration option: events
home-assistant/home-assistant.github.io pull request #10304
Opened 2019-09-07 18:59 UTC by andrewsayre

**Description:**

Documents the integration option "Raise events for push updates" and the new event type `smartthings.update` in the SmartThings.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#TBD

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-09-07 20:10 UTC, frenck commented
@andrewsayre Please don't add the `awaits-parent` label. This is used to indicate it had a review and cannot be merged yet. Since your PR hasn't had a review yet, this label is incorrect and should not be applied.

2019-09-07 20:12 UTC, frenck requested changes
Reviewed, 2 small typos.

2019-09-07 20:12 UTC, frenck commented on source/_components/smartthings.markdown
> +1. `Raise events for push updates`: This is an advanced feature which provides access to the raw data received from SmartThings during a push update. When enabled, the integraiton will raise events t
```suggestion
1. `Raise events for push updates`: This is an advanced feature which provides access to the raw data received from SmartThings during a push update. When enabled, the integration will raise events through the event bus for all push updates--not just button presses. The default is to raise events only for buttons.
```

2019-09-07 20:12 UTC, frenck commented on source/_components/smartthings.markdown
> +`data`                      | Data assocaited with the event update.
```suggestion
`data`                      | Data associated with the event update.
```

2019-09-07 23:44 UTC, andrewsayre commented on source/_components/smartthings.markdown
> +1. `Raise events for push updates`: This is an advanced feature which provides access to the raw data received from SmartThings during a push update. When enabled, the integraiton will raise events t
Fixed!

2019-09-07 23:44 UTC, andrewsayre commented on source/_components/smartthings.markdown
> +`data`                      | Data assocaited with the event update.
Fixed!

2019-09-07 23:46 UTC, andrewsayre commented
@frenck sorry about that...  I've been using that label wrong this whole time.  :joy:

2019-09-08 10:16 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2019-09-16 03:40 UTC, closed without merging