Plex add media_player server config
home-assistant/home-assistant.github.io pull request #10303
Opened 2019-09-07 04:45 UTC by jjlawren

**Description:**
Allows configuration of the Plex `media_player` platform via config in addition to the nonstandard plex.conf file. Dependent on open PR #10297.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#26458

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-09-07 08:59 UTC, DubhAd submitted a review, later dismissed
👍

2019-09-07 19:56 UTC, frenck requested changes
Hi there, @jjlawren, I've reviewed your PR and left some comments. Could you please take a look? Thanks!

2019-09-07 19:56 UTC, frenck commented on source/_components/plex.markdown
> +    use_episode_art: true
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2019-09-07 19:56 UTC, frenck commented on source/_components/plex.markdown
> +    remove_unavailable_clients: true
same as above.

2019-09-09 16:09 UTC, jjlawren commented
Updated. Can #10297 please be merged before this?

2019-09-10 20:16 UTC, frenck approved these changes
Looks good! Ready to merge 🎉

2019-09-10 20:16 UTC, merged