username-host field - clarify use of '%'
home-assistant/home-assistant.github.io pull request #10347
Opened 2019-09-12 00:36 UTC by KaiboshOz

**Description:**
Clarify that '%' is used in host field when wanting to connect *from* multiple hosts

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

2019-09-12 07:30 UTC, frenck commented
Actually, both the original & the changed version are incorrect.
`%` indicates MySQL to accept any host. Configuring multiple hosts in MySQL is also possible and works different.

2019-09-25 19:35 UTC, frenck requested changes
Actually I was trying to tell that this should be changed in general. 
Using `%` is just bad practice in general, which we should not instruct people to use IMHO.

2019-09-26 07:28 UTC, KaiboshOz commented
I was only prompted to submit the doco update after needing to connect to the database from my desktop, and spending a fair whack of time searching and ending up following a bunch of red herrings before finally landing on a suggestion to use `%` which worked and figuring that it's something that should be in the addon doc as at least some other people are likely to need to do the same thing.

Happy to close this if others disagree, or to modify the update - perhaps a warning to use `%` with caution; or @frenck if you can point me in the right direction regarding the specific formatting for the addon config - as I'm ashamed to say when it comes to database, I'm used to GUIs and interfaces and the MariaDB doc wasn't much help with marrying up the actual DB config with the addon config for me to limit it to accept specific hosts while still allowing the HA/Docker connection.

2019-10-17 15:38 UTC, frenck approved these changes

2019-10-17 15:44 UTC, merged