emulated_hue note for sleep cycle and sleep as android
home-assistant/home-assistant.github.io pull request #10368
Opened 2019-09-14 20:16 UTC by orrpan

**Description:**
Note describing how to use sleep cycle and sleep as android in emulated hue using full state view

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#26650

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-09-18 11:23 UTC, frenck requested changes
Hi there, @orrpan, I've reviewed your PR and left a comment. Could you please take a look? Thanks! 👍

2019-09-18 11:23 UTC, frenck commented on source/_components/emulated_hue.markdown
> +<a href="https://www.sleepcycle.com" target="_blank">Sleep Cycle</a> and <a href="https://sleep.urbandroid.org" target="_blank"> Sleep as Android</a>: smart alarm clock app can use emulated_hue to tu
Please use markdown in this paragraph instead of HTML.

2019-09-19 08:31 UTC, frenck commented
Looking at the result, I feel like there is an overload on notes:

![image](https://user-images.githubusercontent.com/195327/65227268-a2229300-dac8-11e9-884a-92de224b8f59.png)

Can we reduce these notes into a list? For example, in combining them in a paragraph?

2019-10-02 21:15 UTC, frenck commented
A small and friendly notification.

Are you planning on moving forward on this PR? 
I didn't see any activity recently, while there are still things to do. I hope you consider picking it up soon! 👍

2019-10-02 21:23 UTC, orrpan commented
Yes, but I’m unsure if your other comments is relevant for adding a new not. I agree that alot of notes is not the cleanest way to go, but should that not be done in another pr? (Which focuses on the docs, not a new functionality)

2019-10-03 10:18 UTC, frenck submitted a review, later dismissed

2019-10-03 10:27 UTC, frenck commented
Rebased PR to resolve merge conflicts.

2019-10-03 10:50 UTC, frenck approved these changes
Thanks for your comments @orrpan!

I agree it is something that needs to be addressed, but maybe a bit out of scope.

Thanks for your contribution! 🎉

2019-10-03 10:50 UTC, merged

2019-10-17 08:22 UTC, orrpan commented
@frenck, I see that this was merged, but the referred PR is not (see description). So this functionality does not work jet