Update pi_hole.markdown
home-assistant/home-assistant.github.io pull request #10391
Opened 2019-09-19 05:54 UTC by Kanga-Who

**Description:**
Since the changes to 0.99.0, port needs to be specified on Hass.io for the sensors to be seen. The documents do not reflect this change. The listed config did not work under Hass.io.

Current working config looks like; 

`pi_hole:
  host: 192.168.1.101:4865` - IP being the machine running Hass.io and hosting Pi-hole through Community Hass.io Add-ons

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-09-21 18:18 UTC, johnluetke commented
I think ort 4865 is only the default for Pi-hole's created as a hass.io addon. If that hold true, this documentation would be incorrect for Pi-hole's running outside of hass.io

2019-09-21 18:29 UTC, frenck commented
Correct the port only applies to the Hass.io add-on.
So, remove the specific port number.

Furthermore, there is a merge conflict.

2019-09-21 18:30 UTC, frenck requested changes
Please apply the requested change and fix the merge conflict.

2019-09-21 18:32 UTC, johnluetke commented on source/_components/pi_hole.markdown
> +  description: IP address and Port of the host where Pi-hole is running. Pi-hole uses port 4865 by default.
I'd recommend specifying here that `4865` is only the default for hass.io addons. port 80 is inferred, when the pihole is running on a raspberry pi or via the official pi-hole docker images

2019-09-22 03:21 UTC, johnluetke commented
I've also opened #10415, since there is a number of github issues coming in with the same symptoms

2019-09-25 18:07 UTC, frenck commented
Closing this PR, since the change has been handled in a other PR.

2019-09-25 18:07 UTC, closed without merging