Add a way to retrieve battery level via HTTP
home-assistant/home-assistant.github.io pull request #10437
Opened 2019-09-23 18:03 UTC by Deadolus

**Description:**
The MQTT way of receiving data only seems to work if you have configured a MQTT backend. 
Added a template sensor to get the battery level with a HTTP Owntracks backend.
This way is tested on my Hometracks system.

**Pull request in home-assistant (if applicable):** 

## Checklist:

- [x ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-09-23 18:09 UTC, frenck requested changes
Thanks for the PR @Deadolus! I've left you some comments, could you please take a look? Thanks! 👍

2019-09-23 18:09 UTC, frenck commented on source/_cookbook/track_battery_level.markdown
> +        value_template: '{{ states.device_tracker.deviceid.attributes.battery_level }}'
We should not retrieve attributes like that, please use `state_attr('device_tracker.deviceid', 'battery_level')` instead.
More information: <https://www.home-assistant.io/docs/configuration/templating/#states>

2019-09-23 18:09 UTC, frenck commented on source/_cookbook/track_battery_level.markdown
> +Replace deviceid with the set Device ID in Owntracks.
```suggestion
Replace `deviceid` with the set Device ID in Owntracks.
```

2019-09-23 18:09 UTC, frenck commented on source/_cookbook/track_battery_level.markdown
> +If you have configured Owntracks to send reports to your Homeassistant instance via HTTP you can use a template sensor.
```suggestion
If you have configured Owntracks to send reports to your Home Assistant instance via HTTP you can use a template sensor. 
```

2019-09-23 18:39 UTC, Deadolus commented
Thank you @frenck for the suggestions. 
I didn't know you're not supposed to get values the way I did. 
Thank you for teaching me something new.
I added in all your suggestions.

2019-09-25 19:31 UTC, frenck approved these changes
Thanks for adjusting @Deadolus! 👍 🎉

2019-09-25 19:31 UTC, merged