Adding airscape fan platform docs
home-assistant/home-assistant.github.io pull request #10452
Opened 2019-09-24 21:30 UTC by quielb

**Description:**
Adding documentation for the new airscape platform fan component

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#26889

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-09-25 00:00 UTC, klaasnicolaas requested changes

2019-09-25 00:00 UTC, klaasnicolaas commented on source/_components/fan.airscape.markdown
> +ha_release: 0.100
```suggestion
ha_release: "0.100"
```

2019-09-25 00:00 UTC, klaasnicolaas commented on source/_components/fan.airscape.markdown
> +    host: "192.168.10.100"
```suggestion
    host: IP_ADDRESS
```

2019-09-25 00:00 UTC, klaasnicolaas commented on source/_components/fan.airscape.markdown
> +    name: "Whole House Fan"
```suggestion
    name: NAME_FOR_ENTITY
```

2019-09-28 02:31 UTC, klaasnicolaas commented
Where is the markdown file?

2019-09-28 02:46 UTC, quielb commented
> Where is the markdown file?

For some reason it didn't get committed to my branch when I changed the file name.  Landing now

2019-09-30 06:36 UTC, closed without merging