Added documentation page for Soma
home-assistant/home-assistant.github.io pull request #10460
Opened 2019-09-26 10:52 UTC by ratsept

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#26226

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-09-26 20:02 UTC, klaasnicolaas requested changes

2019-09-26 20:02 UTC, klaasnicolaas commented on source/_components/soma.markdown
> +ha_release: 0.99
```suggestion
ha_release: "0.100"
```

2019-09-30 12:25 UTC, MartinHjelmare submitted a review, later dismissed

2019-09-30 13:12 UTC, klaasnicolaas requested changes

2019-09-30 13:12 UTC, klaasnicolaas commented on source/_components/soma.markdown
> +### Configuration
```suggestion
## Configuration
```

2019-09-30 13:12 UTC, klaasnicolaas commented on source/_components/soma.markdown
> +The Soma integration will allow users to integrate their Soma Smarthome devices into Home Assistant using the Soma Connect hub. You can build a Soma Connect yourself if you have a spare Raspberry Pi.
This is difficult to read, could you divide it into several parts?

2019-10-01 09:23 UTC, klaasnicolaas approved these changes

2019-10-01 09:24 UTC, klaasnicolaas commented
Happy Hacktoberfest! 🎉

2019-10-01 09:24 UTC, merged