CentOS boot script update
home-assistant/home-assistant.github.io pull request #10610
Opened 2019-10-05 03:11 UTC by bbrendon

Description:
Clear up some confusion. I tested the process and it works.

I'm trying to close this issue: #5656

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-10-05 16:23 UTC, fabaff requested changes

2019-10-05 16:23 UTC, fabaff commented on source/_docs/installation/centos.markdown
> +This works because the Python virtual environment was created using the SCL envionrment, thus there is no need to activate SCL.
```suggestion
This works because the Python virtual environment was created using the SCL environment, thus there is no need to activate SCL.
```

2019-10-05 16:23 UTC, fabaff commented on source/_docs/installation/centos.markdown
> +ExecStart=/opt/hass/venv/bin/hass
Can we please keep it close to the [systemd](https://www.home-assistant.io/docs/autostart/systemd/) docs?

```suggestion
ExecStart=/srv/homeassistant/bin/hass
```

2019-10-09 16:48 UTC, bbrendon reviewed
Is there something I need to do to get this done?

2019-10-10 10:02 UTC, fabaff approved these changes

2019-10-10 10:03 UTC, merged