Added documentation for Flume integration
home-assistant/home-assistant.github.io pull request #10624
Opened 2019-10-05 22:53 UTC by ChrisMandich

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-10-06 10:29 UTC, klaasnicolaas requested changes

2019-10-06 10:29 UTC, klaasnicolaas commented on source/_integrations/flume.markdown
> +ha_release: 0.99.3
```suggestion
ha_release: 0.101
```

2019-10-06 19:49 UTC, klaasnicolaas submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

Happy Hacktoberfest! 🎉

2019-11-26 21:13 UTC, frenck approved these changes

2019-11-26 21:13 UTC, merged