update control section
home-assistant/home-assistant.github.io pull request #10726
Opened 2019-10-11 22:44 UTC by Misiu

`control: hidden` works fine for groups in Lovelace

**Description:**

**Pull request in home-assistant (if applicable):** https://github.com/home-assistant/home-assistant-polymer/pull/2478

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-10-12 09:56 UTC, frenck commented
Still, I think we should not add this. it is likely we are removing the old state UI before HA 1.0.
The backend should not control or influence the UI. 

So while maybe true, I'm kinda doubting we should remove this notice.

2019-10-17 15:56 UTC, iantrich commented
This is only a feature in generated mode of Lovelace. It does nothing once you take control of customizing your UI. At the very least that should be mentioned.

2019-10-17 17:56 UTC, frenck requested changes
@Misiu Would you please update this PR with the feedback given? Thanks! 👍

2019-10-23 07:43 UTC, Misiu commented
@frenck I've added info about the generated mode. Is that ok?

> This is only a feature in generated mode of Lovelace. It does nothing once you take control of customizing your UI. At the very least that should be mentioned.

@iantrich I didn't know about that, so if I create the UI using YAML then I won't be able to hide the switch in a group? If so then this is confusing and I think it should be unified.

2019-10-23 18:14 UTC, frenck approved these changes
Thanks, @Misiu! 👍 

Happy Hacktoberfest 🎉

2019-10-23 18:14 UTC, merged