Added documentation for the Sector Alarm integration
home-assistant/home-assistant.github.io pull request #10769
Opened 2019-10-13 19:54 UTC by peroyvind

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-10-13 20:28 UTC, frenck requested changes
Hi there, @peroyvind!

Thanks for the PR! Reviewed it, and left a couple of comments. Could you please take a look? Thanks! 👍 

PS: Consider adding a logo, it really helps users with identifying the brand that integrates.

2019-10-13 20:28 UTC, frenck commented on source/_integrations/sectoralarm.markdown
> +This has currencly only been testet on norwegian installations, but it should work for other countries as well.
```suggestion
This has currently only been tested on Norwegian installations, but it should work for other countries as well.
```

2019-10-13 20:28 UTC, frenck commented on source/_integrations/sectoralarm.markdown
> +Go to [minside.sectoralarm.no/](https://minside.sectoralarm.no/) and login to find your panel id. After you login it should be a part of the URL. Example: https://minside.sectoralarm.no/#!/systems/**
```suggestion
Go to [minside.sectoralarm.no/](https://minside.sectoralarm.no/) and login to find your panel id. After you log in, it should be a part of the URL. Example: https://minside.sectoralarm.no/#!/systems/**012345678**
```

2019-10-13 21:30 UTC, peroyvind commented
> Hi there, @peroyvind!
> 
> Thanks for the PR! Reviewed it, and left a couple of comments. Could you please take a look? Thanks! 👍
> 
> PS: Consider adding a logo, it really helps users with identifying the brand that integrates.

Thanks. Fixed and logo added :)

2019-10-15 18:47 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2020-01-16 08:56 UTC, frenck approved these changes

2020-03-20 17:45 UTC, closed without merging