Snips Doc - Fix link
home-assistant/home-assistant.github.io pull request #10772
Opened 2019-10-13 23:27 UTC by xelprep

**Description:**

The original author intended to link to a specific `if` statement that strips a username from an intent. The original link destination appears to be dead.

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-10-15 18:24 UTC, frenck requested changes
Hey there @xelprep! Thanks for the PR 👍 

I've left a comment, could you please take a look? Thanks!

2019-10-15 18:24 UTC, frenck commented on source/_integrations/snips.markdown
> +Note: If your Snips action is prefixed with a username (e.g., `john:playmusic` or `john__playmusic`), the Snips integration in Home Assistant [will try and strip off the username](https://github.com/
Do we really want to link to the source code details this way?
Every time we change the code a bit, this link becomes outdated. Secondly, I think it is not a great value for the average user.

Maybe consider removing the link all together?

2019-10-17 16:30 UTC, frenck approved these changes

2019-10-17 16:30 UTC, merged

2019-10-19 00:29 UTC, xelprep commented
Good call removing the link. Sorry for the slow response, long work week!