Initial Documentation for Sinch SMS
home-assistant/home-assistant.github.io pull request #10850
Opened 2019-10-17 15:03 UTC by joelstahre

**Description:**
Documentation for SINCH SMS

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#27809

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-10-17 17:01 UTC, klaasnicolaas requested changes

2019-10-17 17:01 UTC, klaasnicolaas commented on source/_integrations/sinch_sms.markdown
> +ha_release: "0.101"
```suggestion
ha_release: 0.101
```

2019-10-17 17:45 UTC, frenck commented
Hi there @joelstahre! Thanks for your first contribution to our documentation. 🎉 

Could you please make sure the build passes and that you address the comment by @klaasnicolaas ? Thanks! 👍

2019-10-18 06:14 UTC, joelstahre commented
Something i need to make this pass ?
`netlify/home-assistant-docs/deploy-preview — Deploy preview failed.`

2019-10-19 10:04 UTC, closed without merging