Srp energy
home-assistant/home-assistant.github.io pull request #10862
Opened 2019-10-18 14:43 UTC by briglx

**Description:**
Re-Add Documentation for Srp Energy.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-10-18 15:49 UTC, klaasnicolaas requested changes

2019-10-18 15:49 UTC, klaasnicolaas commented on source/_components/sensor.srpenergy.markdown
> +---
Missing a logo of SRP

2019-10-18 16:12 UTC, briglx commented on source/_components/sensor.srpenergy.markdown
> +---
No logo for this

2019-10-18 16:16 UTC, briglx commented
@klaasnicolaas how can I fix the netlify build fail? I don't see how my file affected that.

2019-10-20 12:09 UTC, frenck commented
@briglx Your fork is heavily outdated (commits before these in your fork are from 2018). Please rebase this branch.

For more information see: <https://developers.home-assistant.io/docs/en/development_catching_up.html>

Feel free to reach out or ask for help of you need it.

2019-10-20 17:20 UTC, closed without merging