New platform Microsoft Teams
home-assistant/home-assistant.github.io pull request #10911
Opened 2019-10-20 19:34 UTC by peroyvind

**Description:**
Documentation for new platform Microsoft Teams

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#27981

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-10-21 16:46 UTC, frenck requested changes
Thanks for the PR @peroyvind!

I've reviewed it and left some comments. Could you please take a look? Thanks! 👍

2019-10-21 16:46 UTC, frenck commented on source/_integrations/msteams.markdown
> +  type: url
`url` is not a valid type, use `string` instead.

```suggestion
  type: string
```

2019-10-21 16:46 UTC, frenck commented on source/_integrations/msteams.markdown
> +description: "Instructions on how to send notification to a Microsoft Teams channel."
```suggestion
description: "Instructions on how to send a notification to a Microsoft Teams channel."
```

2019-10-21 16:46 UTC, frenck commented on source/_integrations/msteams.markdown
> +To send notification to teams you need add the Incoming Webhook app to your team channel. When the app is added you will receive a webhook url that needs to be added to your `configuration.yaml`.
```suggestion
To send a notification to teams, you need to add the Incoming Webhook app to your team channel. When the app is added, you will receive a webhook URL that needs to be added to your `configuration.yaml`.
```

2019-10-21 16:46 UTC, frenck commented on source/_integrations/msteams.markdown
> +    name: myteam
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2019-10-21 16:46 UTC, frenck commented on source/_integrations/msteams.markdown
> +  description: The webhook url created in the setup step.
```suggestion
  description: The webhook URL created in the setup step.
```

2019-10-21 16:46 UTC, frenck commented on source/_integrations/msteams.markdown
> +  image_url: http://[url to file, photo, security camera etc]
```suggestion
  image_url: URL_OF_IMAGE
```

2019-10-21 16:46 UTC, frenck commented on source/_integrations/msteams.markdown
> +logo: msteams.png
Did you add the logo somewhere? It doesn't seem to be in this PR.

2019-10-21 19:09 UTC, peroyvind commented
> Thanks for the PR @peroyvind!
> 
> I've reviewed it and left some comments. Could you please take a look? Thanks! 👍

Thanks! Updated the PR 👍

2019-10-21 19:24 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-10-23 09:13 UTC, fabaff approved these changes

2019-10-23 09:14 UTC, merged