Added Sky+HD
home-assistant/home-assistant.github.io pull request #10935
Opened 2019-10-21 21:21 UTC by GreenTurtwig

**Description:**
Support for Sky+HD.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#28074

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-10-21 23:01 UTC, klaasnicolaas requested changes

2019-10-21 23:01 UTC, klaasnicolaas commented on source/_integrations/sky_plus_hd.markdown
> +media_player:
Only required config items

2019-10-21 23:01 UTC, klaasnicolaas commented on source/_integrations/sky_plus_hd.markdown
> +    host: 192.168.0.2
```suggestion
    host: IP_ADDRESS
```

2019-10-21 23:01 UTC, klaasnicolaas commented on source/_integrations/sky_plus_hd.markdown
> +ha_release: "0.102"
```suggestion
ha_release: 0.102
```

2019-10-22 21:49 UTC, GreenTurtwig commented on source/_integrations/sky_plus_hd.markdown
> +media_player:
Done :+1:

2019-10-22 21:49 UTC, GreenTurtwig commented on source/_integrations/sky_plus_hd.markdown
> +    host: 192.168.0.2
Done :+1:

2019-10-22 21:49 UTC, GreenTurtwig commented on source/_integrations/sky_plus_hd.markdown
> +ha_release: "0.102"
Done :+1:

2019-11-17 14:39 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2020-01-10 16:53 UTC, closed without merging