Http to https redirect
home-assistant/home-assistant.github.io pull request #10951
Opened 2019-10-22 18:43 UTC by EgonMarmol

**Description:**
Http to https redirect

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-10-22 19:01 UTC, frenck requested changes

2019-10-22 19:01 UTC, frenck commented on source/_integrations/waqi.markdown
> +The `waqi` sensor platform will query [World Air Quality Index](https://aqicn.org/) service to check AQI value for a specific set of locations. The resulting indexes will be added to the Home Assista
This redirects back to the HTTP version. So while a valid link, it now causes an unneeded redirect.

2019-10-22 19:40 UTC, EgonMarmol commented on source/_integrations/waqi.markdown
> +The `waqi` sensor platform will query [World Air Quality Index](https://aqicn.org/) service to check AQI value for a specific set of locations. The resulting indexes will be added to the Home Assista
Ah, sorry about that. I'm new to Git, but has now got some assistance in correcting the mistake. :) Happy Oktoberfest, @frenck!

2019-10-23 18:16 UTC, frenck approved these changes
LGTM, Thanks @EgonMarmol! 👍 

Happy Hacktoberfest 🎉

2019-10-23 18:16 UTC, merged