Add magichome document
home-assistant/home-assistant.github.io pull request #11110
Opened 2019-11-06 02:23 UTC by ZNEGGE-SDK

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-11-06 09:54 UTC, klaasnicolaas requested changes

2019-11-06 09:54 UTC, klaasnicolaas commented on source/_integrations/magichome.markdown
> +username:
Missing `platform` and `company`

2019-11-07 08:29 UTC, ZNEGGE-SDK commented on source/_integrations/magichome.markdown
> +username:
OK ! My colleague has already made up.

2020-03-06 03:17 UTC, LIULi-VVET commented
Hello @klaasnicolaas ! Is there anything else that needs to be modified?

2020-03-06 03:52 UTC, klaasnicolaas approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged 👍
⚠️ The ha_release might need an update before merging this one in.

2020-03-06 03:55 UTC, klaasnicolaas commented
@LIULi-VVET Since the PR is a bit old and we have added more checks in the meantime, it would be nice if you updated your branch on your fork and pushed to this PR. Otherwise we cannot merge when the PR is ready in the code repo.

2020-03-06 03:56 UTC, LIULi-VVET commented
> @LIULi-VVET Since the PR is a bit old and we have added more checks in the meantime, it would be nice if you updated your branch on your fork and pushed to this PR. Otherwise we cannot merge when the PR is ready in the code repo.
OK!  Thank you very much !

2020-03-09 03:25 UTC, closed without merging