Reword and provide additional information
home-assistant/home-assistant.github.io pull request #11174
Opened 2019-11-13 15:17 UTC by Tediore

This information was outdated, especially with the addition of default_config. Hopefully these changes make it clearer for new users who are confused about the missing homeassistant: line in their default configuration (this is something that has been popping up in the forum lately).

I linked to an external source for the time zone names. Perhaps we should add this list to Home Assistant website instead (or if it already exists, my apologies: I can point it to that instead).

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-11-17 14:49 UTC, frenck requested changes

2019-11-17 14:49 UTC, frenck commented on source/getting-started/configuration.markdown
> + - Now Restart Home Assistant using the RESTART button in the Server management section on the same page. In order for "Check Config" to be visible, you must enable "Advanced Mode" on your user profi
Let's enquote "RESTART", since we seem to do that everywhere.

2019-11-17 14:49 UTC, frenck commented on source/getting-started/configuration.markdown
> +<div class='note'>
Insert an empty line after this, to be sure our Markdown engine pick up the markdown inside this HTML section.

2019-11-17 14:49 UTC, frenck commented on source/getting-started/configuration.markdown
> +  If you have watched any videos about setting up Home Assistant using configuration.yaml (particularly ones that are old), you might notice your default configuration file is much smaller than what
- configuration.yaml -> `configuration.yaml`

2019-11-17 18:11 UTC, Tediore commented
Thanks for the feedback. Are you able to make these changes? I can't edit the file for some reason.

2019-11-17 19:47 UTC, frenck commented
@Tediore I can't... you've removed the upstream fork 😟

2019-11-17 19:52 UTC, Tediore commented
Crap... it must have been when I was messing with my fork of it. Any way to push the changes through and I can quickly make another PR? If not I'll just redo it.

2019-11-18 21:55 UTC, frenck commented
@Tediore Let's find a moment on Discord and coordinate a quick fix in that case 😉

2019-12-06 01:26 UTC, Tediore commented
I made the appropriate changes (and moved the screenshots) in my fork. Should I just close this PR and open a new one?

2019-12-06 05:20 UTC, frenck commented
@Tediore Oh sure, that will work!

2019-12-06 05:27 UTC, Tediore commented
Will do, sorry for the trouble.

2019-12-06 05:27 UTC, closed without merging