Update wording and provide new screenshots
home-assistant/home-assistant.github.io pull request #11180
Opened 2019-11-14 14:42 UTC by Tediore

The onboarding page was out of date given the additions to the onboarding process. I provided some new screenshots and updated the description of the process.

I added some new screenshots to the automation page.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-11-14 14:44 UTC, Tediore commented
Alright, I think I got it right this time 🙄 😆

2019-11-14 14:53 UTC, klaasnicolaas commented
Yes it went well 👍

2019-11-14 15:10 UTC, Tediore commented
I changed the default branch in my fork to `current`. Looks like the default is `next` when you fork it, at least on my end.

2019-11-16 19:05 UTC, frenck requested changes

2019-11-16 19:05 UTC, frenck commented on source/getting-started/automation.markdown
> +In Lovelace, click Configuration in the sidebar, then click Automation. You will now see the automation screen from which you can manage all the automations in Home Assistant.
This is not Lovelace specific.

```suggestion
In Home Assistant, click Configuration in the sidebar, then click Automation. You will now see the automation screen from which you can manage all the automations in Home Assistant.
```

2019-11-16 19:05 UTC, frenck commented on source/getting-started/onboarding.markdown
> +Next, you can enter a name for your home and set your location and unit system. Click DETECT to find your location and set your time zone and unit system based on that location. If you'd rather not s
```suggestion
Next, you can enter a name for your home and set your location and unit system. Click "DETECT" to find your location and set your time zone and unit system based on that location. If you'd rather not send your location, you can set these values manually.
```

2019-11-16 19:05 UTC, frenck commented on source/getting-started/onboarding.markdown
> +Finally, click Finish. Now you're brought to the main screen of Home Assistant called Lovelace. This screen will show all of your devices. So let's get that screen filled up!
The screen is not called Lovelace. Lovelace is only a part of the full frontend.

2019-11-16 19:05 UTC, frenck commented on source/getting-started/onboarding.markdown
> +When you're done, navigate back to Lovelace and voila, your devices are ready for you to control.
We should avoid Lovelace here. It is just the dashboard or Home Assistant frontend.
Lovelace is still optional + not the whole interface is Lovelace.

2019-11-16 21:04 UTC, Tediore commented
Thanks Frenck! Sorry for the misunderstanding. I reverted my changes on the last two comments--thoughts?

2019-11-17 14:10 UTC, frenck commented
Well, we currently have both the old state's screen and Lovelace for displaying information about your system. Besides that, there is the other things our frontend provides.

Maybe just call it the "Home Assistant web interface"? It covers it all right? To be clear on the subject, I'm not quite sure myself... I'm just opening up the discussion on this.

2019-11-17 14:14 UTC, Tediore commented
Right. I changed it to Lovelace since I was editing the onboarding page and Lovelace is the default. But yes, "Home Assistant web interface" would be a good general term!

I'll change that soon.

2019-11-17 18:07 UTC, Tediore commented
Alright, how about now? 😉

2019-11-17 19:50 UTC, frenck commented
Great progress! Now the thing left, is to fix the images... Please check the build preview 😉

2019-11-17 20:02 UTC, Tediore commented
It looks ok to me. [Am I looking in the wrong spot](https://github.com/home-assistant/home-assistant.io/blob/fdf733e2a813da258ab84ec8f790a46919a94b4b/source/getting-started/onboarding.markdown)?

2019-11-17 21:23 UTC, frenck commented
Yes, you are. The GitHub preview is an approximation, however, it is not accurate.
If you click on the Netlify build, you'll go to an actual build preview of the whole website, based on this PR.
You'll then notice the broken images.

2019-11-18 04:38 UTC, Tediore commented
Ah, thank you. I added those images to my fork and they're included in this PR. Are they not showing up because the PR hasn't been merged yet? If not, how should I resolve this?

Forgive my ignorance--still learning about Github.

2019-11-18 09:16 UTC, frenck commented
The paths in this repository do not match 1-1 with the generated result.

I would recommend:

- Move the images to `/source/images/getting-started/`
- Rename the images to have filenames that do not contain spaces or capital letters and are not numbered (order might change in the future) (e.g.,  `12 - new trigger.png` -> `new-trigger.png`)
- Use image refs: `/images/getting-started/new-trigger.png`

While you are in `/image/getting-started/`, that folder contains the "old" images, it would be nice if you could clean those up as well.

2019-11-19 14:46 UTC, Tediore commented
Will do! Sorry for all the trouble with this...

2019-11-19 15:09 UTC, frenck commented
Don't worry @Tediore! You are doing fine!

2019-12-06 01:20 UTC, Tediore commented
Ok. Moved the new screenshots to the requested directory and removed the old screenshots. Just waiting on the netlify build to be ready to confirm the image paths are correct.

2019-12-06 14:02 UTC, Tediore commented
Also, I included the changes to `configuration.markdown` in this PR (from the other PR I closed).

2019-12-12 16:20 UTC, frenck approved these changes
Awesome job @Tediore! (And nicely recovered the PR as well!)  👍 

Thank you!

2019-12-12 16:21 UTC, merged