Update to clarify path declaration in lovelace config
home-assistant/home-assistant.github.io pull request #11181
Opened 2019-11-14 16:27 UTC by poldim

This was not very clear as many people were having this issue:

https://community.home-assistant.io/t/google-cast-error-unable-to-find-a-view-with-path-xxxx/138180/48

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-11-14 17:03 UTC, Villhellm commented
Does it *have* to be defined? Paths are also autogenerated if you don't define it in the view. Just open the view and look at the browser url

2019-11-16 18:59 UTC, frenck commented
@Villhellm They don't have to be defined. It is definitely helpful to do so.

2019-11-16 19:00 UTC, frenck requested changes

2019-11-16 19:00 UTC, frenck commented on source/_integrations/cast.markdown
> +Home Assistant has its own Cast application to show the Home Assistant UI on any Chromecast device.  You can use it by adding the [Cast entity row](/lovelace/entities/#cast) to your Lovelace UI, or b
```suggestion
Home Assistant has its own Cast application to show the Home Assistant UI on any Chromecast device.  You can use it by adding the [Cast entity row](/lovelace/entities/#cast) to your Lovelace UI, or by calling the `cast.show_lovelace_view` service. The service takes the path of a Lovelace view and an entity ID of a Cast device to show the view on. A `path` has to be defined in your Lovelace YAML for each view, as outlined in the [views documentation](/lovelace/views/#path).
```

2019-11-17 18:42 UTC, poldim commented
> Does it _have_ to be defined? Paths are also autogenerated if you don't define it in the view. Just open the view and look at the browser url

So if a path is not defined, can you successfully cast via the service call? 

When I didn't initially have them defined they were autogenerated as just numbers.  I tried casting to the number as the path and that generated some error.

2019-11-17 19:42 UTC, frenck approved these changes
Thanks, @poldim! Let's just add this in, as it is a general good practice as well.

2019-11-17 19:42 UTC, merged