Updated Envoy documentation to include new variables
home-assistant/home-assistant.github.io pull request #11212
Opened 2019-11-17 20:23 UTC by gtdiehl

**Description:**
Documented new optional configuration variables for the Enphase Envoy sensor

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#28837

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-11-17 21:26 UTC, frenck requested changes
Change that requires a Home Assistant release (depending on a PR in the main code base) needs to be based off and go into the `next` branch.

Please update the target branch of this PR to `next` and rebase the PR if needed.

2019-11-17 21:52 UTC, gtdiehl commented
@frenck I can change the branch I'm going to commit into from `current` to `next`, but my branch where my changes are at stays at `current`. 

Do I need to close this PR and open a new one?  As if I do change the branch alot of commits besides mine are listed as going to be commited.

2019-11-18 21:52 UTC, frenck commented
No, you don't need to create a new one. You need to change the target branch in GitHub. At that point, a lot of unrelated commits show up. You next have to rebase your PR (your commits) onto the `next` branch using the git command line.

2019-12-03 09:57 UTC, frenck commented
@gtdiehl Small and friendly notification. Are you going to pick this up?
We can't merge this way and this will block the parent PR.

2019-12-03 18:06 UTC, gtdiehl commented
@frenck Sorry, I've been busy lately.  I'll fix this today as I dont want to hold up anything.

2019-12-03 22:04 UTC, gtdiehl commented
@frenck I changed the target branch to `next`.  Again sorry for the delay.

2019-12-04 08:12 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2019-12-18 09:37 UTC, merged