Recommendation for ssh and samba add-ons
home-assistant/home-assistant.github.io pull request #11266
Opened 2019-11-23 20:05 UTC by cogneato

Made a stronger recommendation for the ssh addon and samba addon following an install of Hassio.

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-11-23 20:07 UTC, DubhAd submitted a review, later dismissed
Thanks. Given the number of folks that don't install the SSH add-on and get themselves in a pickle, I think it's important this is more strongly worded.

2019-11-23 21:48 UTC, frenck approved these changes
Tiny suggestion to improve the language

2019-11-23 21:48 UTC, frenck commented on source/hassio/installation.markdown
> +7. It is important to provide yourself proper access and the Hassio custom cli tools. Both the [Samba add-on][samba] and the [SSH add-on][ssh] should be the first add-ons a user should install before
```suggestion
7. It is important to provide yourself proper access, including the Hass.io CLI tools. Both the [Samba add-on][samba] and the [SSH add-on][ssh] should be the first add-ons you should install, before making changes to the configuration in the `/config/` folder. From the UI choose **Hass.io**, which is located in the sidebar and then the add-on store.
```

2019-11-23 21:48 UTC, frenck requested changes
Arrg wrong button, let me try again

2019-11-23 21:50 UTC, frenck commented on source/hassio/installation.markdown
> +7. It is important to provide yourself proper access and the Hassio custom cli tools. Both the [Samba add-on][samba] and the [SSH add-on][ssh] should be the first add-ons a user should install before
The only thing that is missing IMHO, is WHY one needs this.
However, still a major improvement, so 👍

2019-12-13 16:00 UTC, frenck approved these changes

2019-12-13 16:00 UTC, merged