home assistant documentation change for PR29968
home-assistant/home-assistant.github.io pull request #11499
Opened 2019-12-19 18:01 UTC by rhadamantys

Add documentation description for home assistant PR 29968 https://github.com/home-assistant/home-assistant/pull/29968 to describe window handle setup in configuration.yaml file

**Description:** Add documentation for Hoppe SecuSignal window handle and other enocean F6 10 00 devices

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<29968>

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-12-19 19:08 UTC, klaasnicolaas commented
Could you please rebase this PR to the `next` branch?

2019-12-20 08:44 UTC, rhadamantys commented
@klaasnicolaas, I merged my commit into the next branch. I hope that is what you intended me to do...

2019-12-20 10:02 UTC, klaasnicolaas commented
I think it went well because I only see your own commit 😄

2019-12-20 10:14 UTC, frenck requested changes
Hi there, @rhadamantys! 

Thanks for the PR! I've reviewed it and left a small suggestion. Could you take a look? Thanks! 👍

2019-12-20 10:14 UTC, frenck commented on source/_integrations/enocean.markdown
> +As of now the Hoppe SecuSignal window handle from Somfy has been succesfully tested. However any mechanical window handle that follows the enocean RPS telegram spec F6 10 00 (Hoppe AG) is supported.
```suggestion
As of now, the Hoppe SecuSignal window handle from Somfy has been successfully tested. However, any mechanical window handle that follows the EnOcean RPS telegram spec F6 10 00 (Hoppe AG) is supported.
```

2019-12-20 13:41 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2019-12-25 14:29 UTC, merged