Updated mention of services in top text to reflect new service names
home-assistant/home-assistant.github.io pull request #11502
Opened 2019-12-20 08:15 UTC by atxbyea

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-12-20 13:42 UTC, frenck requested changes
Left a small question, @atxbyea, could you help me answer that?

2019-12-20 13:42 UTC, frenck commented on source/_integrations/vacuum.xiaomi_miio.markdown
> +- `xiaomi_miio.vacuum_clean_zone`
Why are these prefixed by the domain and the ones already in the docs not?

2020-01-07 14:56 UTC, frenck commented
@atxbyea Ping! 😄

2020-01-10 12:17 UTC, atxbyea commented
good question @frenck I just saw that list in the top of the docs, and saw that it referenced the "old" service name, and changed it to the "new" service name, probably it could just say `clean_zone` to be in line with the rest of them ?

2020-01-12 09:33 UTC, frenck commented
@atxbyea There is no policy on that, however, I think we should be consistent on the same page at least 😉

2020-02-12 07:46 UTC, frenck commented
Closing PR since it is running stale.

2020-02-12 07:46 UTC, closed without merging