New integration: Ezviz camera
home-assistant/home-assistant.github.io pull request #11596
Opened 2020-01-01 21:45 UTC by BaQs

**Description:**
Ezviz camera platform

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-01-01 22:34 UTC, klaasnicolaas requested changes

2020-01-01 22:34 UTC, klaasnicolaas commented on source/_integrations/ezviz.markdown
> +ha_release: 0.103.0
```suggestion
ha_release: 0.104
```

2020-01-01 22:34 UTC, klaasnicolaas commented on source/_integrations/ezviz.markdown
> +    username: 'user@mail.com'
```suggestion
    username: USERNAME
```

2020-01-01 22:34 UTC, klaasnicolaas commented on source/_integrations/ezviz.markdown
> +    password: 'your_password_here'
```suggestion
    password: PASSWORD
```

2020-01-01 22:34 UTC, klaasnicolaas commented on source/_integrations/ezviz.markdown
> +        username: admin
```suggestion
        username: CAMERA_USERNAME
```

2020-01-01 22:34 UTC, klaasnicolaas commented on source/_integrations/ezviz.markdown
> +        password: ABCDEF
```suggestion
        password: CAMERA_PASSWORD
```

2020-01-01 22:34 UTC, klaasnicolaas commented on source/_integrations/ezviz.markdown
> +      D87654321:
Maybe that one cam example is more then enough?

2020-01-13 21:13 UTC, frenck commented on source/_integrations/ezviz.markdown
> +If you want a shiny lovelace card, with proper buttons, here is a snippet of a lovelace card:
```suggestion
If you want a shiny Lovelace card, with proper buttons, here is a snippet of a Lovelace card:
```

2020-03-10 14:53 UTC, frenck approved these changes
There we go! Thanks, @BaQs! 👍

2020-03-10 14:53 UTC, merged