Remove empty entity_id from light doc
home-assistant/home-assistant.github.io pull request #11602
Opened 2020-01-02 11:16 UTC by fhoekstra

**Description:**

Leaving entity_id empty to target all has been deprecated, and is now non-functional since 0.103: https://github.com/home-assistant/home-assistant/pull/29178

In this commit, I patch the light doc page (probably the most visited one). Let me know if you want me to do this for all integrations. I was not 100% sure if this change is across all integrations.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-01-02 11:28 UTC, frenck requested changes
Hi there, @fhoekstra! 

This is a change to our current documentation and does not depend on the next release of Home Assistant. Therefore this PR should be based on and targeting the `current` branch.

Please change the target and rebase your PR if needed.

Thanks! 👍

2020-01-07 14:55 UTC, frenck commented
This change is actually incorrect. Entity ID's are optional (for example an area can be provided instead).

2020-01-07 14:55 UTC, closed without merging

2020-01-15 11:29 UTC, fhoekstra commented
Thanks for your responses @frenck !
I will make a new pull request for `current` where I change the docs through a 'replace all' to reflect that for every service that has an entity_id argument, either an area or entity_id must be provided.

2020-01-15 12:39 UTC, fhoekstra commented
Made a new PR for current. Look forward to your comments on that one!
#11749 is the number