Update config to new Samsung TV integration
home-assistant/home-assistant.github.io pull request #11616
Opened 2020-01-03 12:24 UTC by escoand

**Description:**
Update description to new configuration options.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#28306

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-01-03 13:10 UTC, klaasnicolaas requested changes

2020-01-03 13:10 UTC, klaasnicolaas commented on source/_integrations/samsungtv.markdown
> +    name: My Samsung TV
In the first example we want only required config variables, please remove everything that is optional here.
You can make a more advanced example above the `supported models` part 😉

2020-01-13 14:58 UTC, frenck commented
@escoand My main concern with this PR right now, is that it has no mention of configuring/setting up the integration via the integrations panel in the frontend.

I think that should be added. Also, add the `ha_config_flow: true` to the front matter of the page, to indicate this integration has a config flow.

2020-01-16 08:49 UTC, frenck commented
Maybe I'm missing something, but you can go to the integrations panel and just add the integration manually, right?

2020-01-16 09:27 UTC, escoand commented
Correct, as I wrote in line 18:

```markdown
You can add your TV by using the web interface via [ssdp](/integrations/ssdp) discovery or manual config.
For more control over the integration you can also use an entry in the configuration files.
```

2020-01-16 09:30 UTC, frenck commented
That does not really want I meant with my original comment.

There is a manual setup (click path) for the user via integrations to set it up manually. (Click integrations -> add using the + -> etc.

The manual should be written from a perspective a user of any experience level can use it. Right now, I think we should add instructions on how to set it up via just the frontend (since that is now possible).

2020-01-16 14:20 UTC, arsaboo commented
Since the component now allows both config flow and yaml, maybe the [Ring docs](https://github.com/home-assistant/home-assistant.io/pull/11679) are a good reference.

2020-01-21 20:40 UTC, escoand commented
OK, what do you think about he new wording?

2020-01-23 09:44 UTC, frenck approved these changes
Thanks!

2020-01-23 09:44 UTC, merged