Updating vera docs to use config flow in related pr.
home-assistant/home-assistant.github.io pull request #11663
Opened 2020-01-07 17:25 UTC by vangorra

**Description:**
Changing documentation to prefer config flow instead of configuration.yml.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#30189

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-01-07 19:24 UTC, frenck requested changes

2020-01-07 19:24 UTC, frenck commented on source/_integrations/vera.markdown
> +The Vera integration is configured exclusively through the front-end. Manual setup through `configuration.yaml` is deprecated.
Let not make big warnings. Those are for the release notes and changelogs that go with the releases.

Instead, we should write the documentation for a new user getting here. What does he has to click and do to make it work?

Please write the documentation from a new user perspective.

2020-01-08 09:47 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-04-03 13:05 UTC, vangorra commented
Rebased and linked PR is merged. This should be ready to merge once build finishes.

2020-04-03 13:29 UTC, frenck approved these changes
✅

2020-04-03 13:29 UTC, merged