Update solax.markdown
home-assistant/home-assistant.github.io pull request #11696
Opened 2020-01-10 08:58 UTC by danpowell88

**Description:**

Add a note for newer inverters that have updated firmware and require a reverse proxy for accessing their api

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-01-10 09:00 UTC, danpowell88 commented
Not sure why the others commits are showing up as well???

2020-01-10 10:05 UTC, frenck requested changes
Thanks for the PR @danpowell88!

I've reviewed it and left some comments and suggestions. Could you please take a look? Thanks! 👍

2020-01-10 10:05 UTC, frenck commented on source/_integrations/solax.markdown
> +Inverter models with newer firmware (and also those using devices like PocketWifi no longer expose an API when connected to SSID, they do however continue to expose it on their own broadcasted SSID,
```suggestion

Inverter models with newer firmware and also those using devices like PocketWifi, no longer expose an API when connected to SSID. They do, however, continue to expose it on their own broadcasted SSID, to use this sensor, in this case, it is necessary to set up a reverse proxy with something like Nginx and use a raspberry pi (or similar) with two network connections (one wifi that connects to the inverters SSID).
```

2020-01-10 10:05 UTC, frenck commented on source/_integrations/solax.markdown
> +Example nginx configuration
```suggestion
Example Nginx configuration
```

2020-01-10 10:05 UTC, frenck commented on source/_integrations/solax.markdown
> +```
Code block language type missing, maybe `text`?

2020-01-11 09:00 UTC, danpowell88 commented
@frenck updated, how does that look to you?

2020-01-11 10:37 UTC, frenck requested changes

2020-01-11 10:37 UTC, frenck commented on source/_integrations/solax.markdown
> +``` text
```suggestion
```text
```

2020-01-11 10:37 UTC, frenck commented on source/_integrations/solax.markdown
> +Inverter models with newer firmware (and also those using devices like PocketWifi) no longer expose an API when connected to your wireless network, they do however continue to expose it on their own
```suggestion

Inverter models with newer firmware (and also those using devices like PocketWifi) no longer expose an API when connected to your wireless network, they do however continue to expose it on their own broadcasted SSID. To use this sensor in this case it is necessary to set up a reverse proxy with something like Nginx and use a raspberry pi (or similar) with two network connections (one being wifi that connects to the inverters SSID).

```

2020-01-12 09:24 UTC, frenck approved these changes
Thanks, @danpowell88! 👍

2020-01-12 09:24 UTC, merged