Clarify which name to put in devices
home-assistant/home-assistant.github.io pull request #11715
Opened 2020-01-12 02:38 UTC by heytcass

When setting up Automatic, I found it confusing which name to put in the `devices` section, and put the nickname in, which broke the integration. Added a note to clarify for future users.

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-01-12 08:13 UTC, frenck requested changes
Thanks for the PR @heytcass.
Left 2 small suggestions, could you take a look? 👍

2020-01-12 08:13 UTC, frenck commented on source/_integrations/automatic.markdown
> +The device name must be the name given by Automatic -ahem- *automatically*. This is typically the model year, make and model. This is *not* the nickname you have give the vehicle in the `vehicles` se
Typo, and no need to mock Automatic in our documentation.

```suggestion
The device name must be the name given by Automatic automatically. This is typically the model year, make and model. This is *not* the nickname you have to give the vehicle in the `vehicles` section of the app's settings.
```

2020-01-12 08:13 UTC, frenck commented on source/_integrations/automatic.markdown
> +<div class='note'>
Added newline to keep things nice & neat.
```suggestion

<div class='note'>
```

2020-01-13 13:38 UTC, heytcass commented
@frenck Resolved. 👍

2020-01-13 13:44 UTC, frenck approved these changes
Thanks for updating @heytcass! 👍

2020-01-13 13:48 UTC, merged