Add documentation for wiffi integration
home-assistant/home-assistant.github.io pull request #11748
Opened 2020-01-15 11:59 UTC by mampfes

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-01-15 14:56 UTC, frenck requested changes
Hi there @mampfes! 

I've reviewed your PR and left some comments, could you please take a look?

2020-01-15 14:56 UTC, frenck commented on source/_integrations/wiffi.markdown
> +description: Support for Wiffi devices from stall.biz, e.g. Weatherman, Rainyman, ...
```suggestion
description: Support for WIFFI devices from stall.biz, e.g., Weatherman, Rainyman, ...
```

2020-01-15 14:56 UTC, frenck commented on source/_integrations/wiffi.markdown
> +This integration allows you to connect your [Wiffi](https://stall.biz) devices directly to Home Assistant.
```suggestion
This integration allows you to connect your [STALL WIFFI](https://stall.biz) devices directly to Home Assistant.
```

2020-01-15 14:56 UTC, frenck commented on source/_integrations/wiffi.markdown
> +Press on **wiffi** and configure the integration:
```suggestion
Press on **WIFFI** and configure the integration:
```

2020-01-15 14:56 UTC, frenck commented on source/_integrations/wiffi.markdown
> +* Enter the server port for json telegrams sent by the wiffi device.
```suggestion
* Enter the server port for JSON telegrams sent by the WIFFI device.
```

2020-01-15 14:56 UTC, frenck commented on source/_integrations/wiffi.markdown
> +## Configure wiffi device
```suggestion
## Configure the WIFFI device
```

2020-01-15 14:56 UTC, frenck commented on source/_integrations/wiffi.markdown
> +1. Set "CCU-IP Adresse myCCUIP" to IP address of Home Assistant.
```suggestion
1. Set "CCU-IP Adresse myCCUIP" to the IP address of Home Assistant.
```

2020-01-15 14:56 UTC, frenck commented on source/_integrations/wiffi.markdown
> +2. Set port for json telegrams to configured server port using parameter "send_json".
```suggestion
2. Set port for JSON telegrams to configured server port using parameter "send_json".
```

2020-01-15 14:56 UTC, frenck commented on source/_integrations/wiffi.markdown
> +Home Assistant will open a TCP server socket on the configured port and listens for incoming telegrams from wiffi devices. Entities from new devices will be automatically added.
```suggestion
Home Assistant will open a TCP server socket on the configured port and listens for incoming telegrams from WIFFI devices. Entities from new devices will be automatically added.
```

2020-01-15 14:56 UTC, frenck commented on source/_integrations/wiffi.markdown
> +title: Wiffi
```suggestion
title: STALL WIFFI
```

2020-01-15 16:39 UTC, mampfes commented on source/_integrations/wiffi.markdown
> +title: Wiffi
Done

2020-01-15 16:40 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2020-01-20 08:54 UTC, frenck submitted a review, later dismissed

2020-05-13 11:01 UTC, merged