CDO update of zha.markdown
home-assistant/home-assistant.github.io pull request #11835
Opened 2020-01-21 14:06 UTC by Gamester17

**Description:**

Change to alphabetical order when sorting the list with supported ZHA device types, same as in Z-Wave documentation

https://www.home-assistant.io/integrations/zwave vs https://www.home-assistant.io/integrations/zha/

CDO, it's like OCD but all the letters are in the alphabetical order, AS THEY SHOULD BE!

**Pull request in home-assistant (if applicable):** Not applicable

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-01-21 14:40 UTC, frenck requested changes

2020-01-21 14:40 UTC, frenck commented on source/_integrations/zha.markdown
> +integration for Home Assistant allows you to connect many off-the-shelf Zigbee based devices to Home Assistant, using one of the available Zigbee radio modules that is compatible with [Zigpy](https:/
`zigpy` is written in lower case.

```suggestion
integration for Home Assistant allows you to connect many off-the-shelf Zigbee based devices to Home Assistant, using one of the available Zigbee radio modules that is compatible with [zigpy](https://github.com/zigpy/zigpy) (an open source Python library implementing a Zigbee stack, which in turn relies on separate libraries which can each interface a with Zigbee radio module a different manufacturer).
```

2020-01-21 14:41 UTC, frenck commented
This PR is targeting an incorrect branch. Since this is a change to the documentation that matches our current release, it should be targeted against and based of the `current` branch.

Please change the target branch and rebase your PR if needed.

2020-01-22 07:44 UTC, Gamester17 commented
@frenck I did the PR against the `next` branch instead of the `current` branch because PR #11695 which adds "Cover" to that list where sort order changed is only in the `next` branch and not the `current` branch.

2020-01-22 08:14 UTC, frenck approved these changes
Thanks, @Gamester17! 👍

2020-01-23 09:17 UTC, merged