added documentation for new bkk integration
home-assistant/home-assistant.github.io pull request #11842
Opened 2020-01-21 21:51 UTC by gabor-simon

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue: -

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-01-22 00:26 UTC, klaasnicolaas requested changes

2020-01-22 00:26 UTC, klaasnicolaas commented on source/_integrations/bkk.markdown
> +ha_release: 0.49
```suggestion
ha_release: 0.105
```

2020-01-22 00:28 UTC, klaasnicolaas requested changes

2020-01-22 00:28 UTC, klaasnicolaas commented on source/_integrations/bkk.markdown
> +  required: no
```suggestion
  required: false
```

2020-01-22 00:28 UTC, klaasnicolaas commented on source/_integrations/bkk.markdown
> +  required: no
```suggestion
  required: false
```

2020-01-22 00:28 UTC, klaasnicolaas commented on source/_integrations/bkk.markdown
> +  required: no
```suggestion
  required: false
```

2020-01-22 07:08 UTC, gabor-simon commented on source/_integrations/bkk.markdown
> +ha_release: 0.49
thanks, done!

2020-01-22 07:10 UTC, gabor-simon commented on source/_integrations/bkk.markdown
> +  required: no
Done

2020-01-22 07:10 UTC, gabor-simon commented on source/_integrations/bkk.markdown
> +  required: no
Done

2020-01-22 07:11 UTC, gabor-simon commented on source/_integrations/bkk.markdown
> +  required: no
Done

2020-01-23 09:19 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2020-04-08 17:29 UTC, frenck commented
Closing PR, since the parent PR has been closed.

2020-04-08 17:29 UTC, closed without merging