QVR Pro documentation
home-assistant/home-assistant.github.io pull request #11877
Opened 2020-01-26 03:53 UTC by oblogic7

## Proposed change

Adds documentation for new QVR Pro integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-01-26 11:13 UTC, klaasnicolaas commented
Please merge the documentation to one single file `qvrpro.markdown`.

2020-02-20 09:12 UTC, frenck commented
It is not just the renaming, but the whole page.

It seems like you are using a very very old format (over a year old at least).
Please take a look at other pages, the way we make headers and things we put into the frontmatter changed quite a bit.

Please update this page to match the rest of our documentation.

2020-02-20 15:13 UTC, oblogic7 commented
Yes, I started this integration over a year ago and the working branch was rather stale.  I believe everything should be current now.

2020-02-20 15:53 UTC, frenck requested changes

2020-02-20 15:53 UTC, frenck commented on source/_integrations/qvr_pro.markdown
> +  host: 192.168.1.102
```suggestion
  host: YOUR_HOST
```

2020-02-20 15:53 UTC, frenck commented on source/_integrations/qvr_pro.markdown
> +  username: pyqvruser
```suggestion
  username: YOUR_USERNAME
```

2020-02-20 15:53 UTC, frenck commented on source/_integrations/qvr_pro.markdown
> +  password: password
```suggestion
  password: YOUR_PASSWORD
```

2020-02-20 15:53 UTC, frenck commented on source/_integrations/qvr_pro.markdown
> +  exclude_channels: 2,5,6
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2020-02-20 15:53 UTC, frenck commented on source/_integrations/qvr_pro.markdown
> +Currently only cameras are supported by this integration.
```suggestion
Currently, only cameras are supported by this integration.
```

2020-02-20 18:45 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2020-03-04 09:16 UTC, merged