Add note to Badges regarding Panel mode
home-assistant/home-assistant.github.io pull request #11914
Opened 2020-01-29 16:46 UTC by rpitera

Clarify that badges do not show when view is in panel mode.

## Proposed change
Just a clarification that Badges are ignored in Panel Mode views.  I've never really used them before so this was new to me.

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

- [X ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-01-29 18:10 UTC, klaasnicolaas requested changes

2020-01-29 18:10 UTC, klaasnicolaas commented on source/lovelace/views.markdown
> +      description: List of entities IDs or `badge` objects to display as badges. Note: Badges do not show when view is in panel mode.
```suggestion
      description: List of entities IDs or `badge` objects to display as badges. Note that badges do not show when view is in panel mode.
```

2020-01-29 18:16 UTC, rpitera commented
Changes work for me.

2020-01-30 11:11 UTC, frenck approved these changes
Thanks, @rpitera! 👍

2020-01-30 11:12 UTC, merged