Add documentation for hvv_departures
home-assistant/home-assistant.github.io pull request #12002
Opened 2020-02-06 22:34 UTC by vigonotion

## Proposed change

I added a sensor for the HVV public transportation in Hamburg, Germany. It creates a sensor that shows the timestamp for the next departure, as well as the next (up to 20) departures in the attribute "next".
The integration is using the official api (Geofox API). You'll need credentials for the api, description on how to get them are in the pr.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [https://github.com/home-assistant/home-assistant/pull/31564](https://github.com/home-assistant/home-assistant/pull/31564)
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-20 11:06 UTC, frenck requested changes
Thanks, @vigonotion! In general, it looks good!

Did a couple of minor tweak, mainly to match the general style of our documentation.

One thing missing, is the brand images. Could you please open up a PR on our Brands repository and link it to this PR?

<https://github.com/home-assistant/brands>

Thanks!

2020-04-20 11:11 UTC, vigonotion commented
I already did the brand icons, just forgot to link them here. I updated my original PR description, and here is the link again: https://github.com/home-assistant/brands/pull/1291

2020-04-20 11:20 UTC, frenck submitted a review, later dismissed
Aah right! Awesome!

✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2020-06-14 22:24 UTC, frenck approved these changes

2020-06-14 22:24 UTC, merged