Merge Dark Sky docs
home-assistant/home-assistant.github.io pull request #12016
Opened 2020-02-08 04:12 UTC by NeLLyMerC

Attempting to merge Dark Sky documentation for simplification and clarity. If the PR is accepted, I'd like to remove /integrations/weather.darksky/ and just keep the current page (/integrations/darksky/)

## Proposed change

## Type of change

- [x ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [ x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-02-09 10:27 UTC, klaasnicolaas commented
We would prefer that you now immediately remove the old platform page and set the redirects correctly from weather.darksky to darksky.

2020-02-09 10:29 UTC, klaasnicolaas requested changes

2020-02-09 10:29 UTC, klaasnicolaas commented on source/_integrations/darksky.markdown
> +
Remove the extra whitespace

2020-02-09 10:29 UTC, klaasnicolaas commented on source/_integrations/darksky.markdown
> +
Maybe add here a header with **Weather**

2020-02-09 10:29 UTC, klaasnicolaas commented on source/_integrations/darksky.markdown
> +
Maybe add here a header with **Sensor**

2020-02-09 18:28 UTC, NeLLyMerC reviewed
Edited document based on feedback

2020-02-09 18:28 UTC, NeLLyMerC commented on source/_integrations/darksky.markdown
> +
Added, thank you for the feedback

2020-02-09 18:28 UTC, NeLLyMerC commented on source/_integrations/darksky.markdown
> +
Whitespace removed, thank you.

2020-02-09 18:49 UTC, frenck commented
These are 2 different things in Home Assistant. How would one know the difference know? Where is it explained?

2020-02-09 21:08 UTC, NeLLyMerC commented
> These are 2 different things in Home Assistant. How would one know the difference know? Where is it explained? And how would that go with updates?
> 
> I think we should keep things that are separate in our code base, separate in the documentation as well. Mainly since the documentation should reflect the codebase.

The differences are described in one of the first paragraphs on the edits I made. Each entity type is linked to a page for reference (/integration/sensors & /lovelace/weather-forecast/), so the user can see examples of the differences. There are also two separate headings with the example configuration needed to get each added to Home Assistant. I found it confusing as it is because searching “Dark Sky” in the integrations page yields two results that say the same thing. The current page of /integrations/weather.darksky is also not very descriptive of what you will gain by adding this type of integration.

2020-02-10 10:06 UTC, frenck commented
I'm assigning myself as well, I think having weather platforms both implemented as weather and sensor actually are unfriendly. I'm going to take up this discussion on that level first.

2020-02-10 13:04 UTC, NeLLyMerC commented
The idea I was going for is similar to other integrations like Canary, Bloomsky, or Arlo. One page for the integration that shows you the different entities that can be configured for it. 
Let me know how I can help

2020-02-10 19:16 UTC, frenck commented
Yes, I get that, however, in this case it are 2 different integrations/platforms. (different source).

2020-04-20 07:55 UTC, frenck commented
Not stale, thanks stable bot.

2020-06-28 05:07 UTC, closed without merging