New Integration: Ubiquiti airCube
home-assistant/home-assistant.github.io pull request #12031
Opened 2020-02-10 01:00 UTC by petroffc

## Proposed change
Documentation for new Ubiquiti airCube device tracker integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue: N/A

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-02-10 01:56 UTC, klaasnicolaas requested changes

2020-02-10 01:56 UTC, klaasnicolaas commented on source/_integrations/aircube.markdown
> +ha_release: 0.106.0
```suggestion
ha_release: 0.106
```

2020-02-10 10:04 UTC, frenck requested changes

2020-02-10 10:04 UTC, frenck commented on source/_integrations/aircube.markdown
> +Note on SSL: The verify_ssl flag must currently be set to `False` as the certificate on the device cannot easily be updated. The device runs a modified version of OpenWrt with SSH disabled. While cer
```suggestion
Note on SSL: The verify_ssl flag must currently be set to `False` as the certificate on the device cannot easily be updated. The device runs a modified version of OpenWrt with SSH disabled. While certificates can be managed in OpenWrt, Ubiquiti, in violation of the GPL, has not released the source code for the airCube.
```

Maybe convert this to an actual note?
<https://developers.home-assistant.io/docs/en/documentation_create_page.html#html>

2020-02-20 09:00 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2020-06-21 09:19 UTC, frenck commented
Closing PR as the parent PR has been closed.

2020-06-21 09:19 UTC, closed without merging