Update squeezebox.markdown
home-assistant/home-assistant.github.io pull request #12067
Opened 2020-02-12 15:01 UTC by rajlaud

reflect changes in Squeezebox add query and sync pull request (#31748)

## Proposed change

Added descriptions of new services, 'call_query', 'sync', and 'unsync'.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/home-assistant/pull/31748
- This PR fixes or closes issue:

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-02-14 07:44 UTC, frenck requested changes
Thanks for the PR @rajlaud!

Just 2 small comments. Could you please take a look? Thanks! 👍

2020-02-14 07:44 UTC, frenck commented on source/_integrations/squeezebox.markdown
> +Call a custom Squeezebox JSONRPC API. The results of the query will be stored in the 'query_result' attribute of the player.
```suggestion
Call a custom Squeezebox JSON-RPC API. The result of the query will be stored in the 'query_result' attribute of the player.
```

2020-02-14 07:44 UTC, frenck commented on source/_integrations/squeezebox.markdown
> +This service can be used to integrate a Squeezebox query into an automation. For example, in a python script, you can get a list of albums available by an artist like this:
```suggestion
This service can be used to integrate a Squeezebox query into an automation. For example, in a Python script, you can get a list of albums available by an artist like this:
```

2020-02-14 18:15 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-04-29 02:14 UTC, rajlaud commented
The underlying pull request has been approved. https://github.com/home-assistant/core/pull/31748.

2020-05-08 10:43 UTC, frenck approved these changes

2020-05-08 10:43 UTC, merged