Include Android
home-assistant/home-assistant.github.io pull request #12098
Opened 2020-02-16 13:16 UTC by kloggy

I guess the icon needs to change too but I didn't know how I would include a new image.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-02-16 15:14 UTC, klaasnicolaas commented
In this case we should then also change the icon and url

2020-02-16 16:30 UTC, klaasnicolaas requested changes

2020-02-16 16:30 UTC, klaasnicolaas commented on source/docs/index.markdown
>        <img src='/images/supported_brands/apple.png' />
I think we should change this image also, for something that presents a mobile 📱

2020-02-17 08:49 UTC, frenck commented on source/docs/index.markdown
> +    <div class='title'>Android and iOS</div>
```suggestion
    <div class='title'>Mobile Apps</div>
```

2020-02-17 08:49 UTC, frenck commented
The link of the item is also incorrect, it should go to `https://companion.home-assistant.io`

2020-02-17 09:21 UTC, kloggy commented
I agree with the comments from both @klaasnicolaas and @frenck but as a GitHub novice I am not sure if this is waiting for me to do anything.

Sorry for my ignorance...

2020-05-08 14:41 UTC, frenck approved these changes
👍

2020-05-08 14:41 UTC, merged