Work day fix
home-assistant/home-assistant.github.io pull request #12124
Opened 2020-02-19 00:51 UTC by penright

## Proposed change

I just added a note. If you look at bug report #31034 we were confused thinking that adding `holidays` to exclude meant to excluded holidays from consideration. I am not a grammar guru but I did tweak some. If I made any mistakes or it is not clear let me know.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/home-assistant/pull/31832
- This PR fixes or closes issue: 31034 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-02-19 09:07 UTC, frenck requested changes

2020-02-19 09:07 UTC, frenck commented on source/_integrations/workday.markdown
> +> **_NOTE:_**
This is not how we do notes, besides it is a huge blob of text, which makes it hard to read.

Please check our developer documentation on how to make alerts/notes, and see if you can improve on this paragraph a bit to make it more readable.

2020-02-19 09:07 UTC, frenck commented on source/_integrations/workday.markdown
> +
Unneeded additional new line.

```suggestion
```

2020-02-19 16:03 UTC, springstan commented on source/_integrations/workday.markdown
> +The keyword `holiday` is used for public holidays identified by the holiday’s module.
The module is called `holidays`
```suggestion
The keyword `holiday` is used for public holidays identified by the holidays module.
```

2020-02-20 09:10 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-03-10 14:32 UTC, merged