Updated docs for PR #32085
home-assistant/home-assistant.github.io pull request #12160
Opened 2020-02-22 14:31 UTC by jezcooke

Added name parameter for Frontier Silicon players in home-assistant/home-assistant#32085.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-02-22 16:10 UTC, frenck requested changes
This PR relies on a PR in our codebase, and thus the next release of Home Assistant.

Please adjust the target branch for this PR to the `next` branch and rebase your PR if needed.

2020-02-22 16:50 UTC, frenck requested changes
Please rebase your PR as requested in my initial request. There are now unrelated commits on your PR.

2020-02-22 17:21 UTC, jezcooke commented
@frenck Sorry, I think it should be OK now?

2020-02-23 11:46 UTC, frenck approved these changes
Yep! Thanks!

✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-02-25 00:58 UTC, merged