Update TotalConnect for config flow
home-assistant/home-assistant.github.io pull request #12171
Opened 2020-02-24 00:07 UTC by austinmroczek

## Proposed change

Adds discussion of how to add TotalConnect via the user interface.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/home-assistant/pull/32126

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-02-24 00:55 UTC, klaasnicolaas commented
Put a little bit in the file, put the configuration piece on top. This is more in line with how we like it.

2020-02-25 01:22 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-03-06 04:28 UTC, austinmroczek commented
I adjusted this PR after the review was complete because the code PR ended up having a breaking change, and I had to account for that here.  For some reason I can't resolve this conflict though.

2020-03-06 10:47 UTC, klaasnicolaas requested changes
Here and there I see some extra whitespaces, can you remove them? 😄

2020-03-06 22:54 UTC, klaasnicolaas commented
I actually meant between the sentences, what you have now adjusted was not necessary.

2020-03-07 00:29 UTC, austinmroczek commented
Per discussion with balloob we un-did the breaking change in the code.  Configuration.yaml entry is still supported, so I added it back in here.

2020-04-13 06:40 UTC, frenck requested changes
Thanks, @austinmroczek 

2 Small suggestions left. Could you take a look? Thanks! 👍

2020-04-13 06:40 UTC, frenck commented on source/_integrations/totalconnect.markdown
> +    password: !secret your_password
Please use placeholders:

```suggestion
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
```

2020-04-13 06:40 UTC, frenck commented on source/_integrations/totalconnect.markdown
> +To enable TotalConnect via `configuration.yaml` add the following lines:
Newline before starting a fenced code block:

```suggestion
To enable TotalConnect via `configuration.yaml` add the following lines:

```

2020-04-15 12:48 UTC, frenck approved these changes
Thanks for the updates @austinmroczek! 👍

2020-04-15 12:48 UTC, merged