Fix telegram bot documentation
home-assistant/home-assistant.github.io pull request #12186
Opened 2020-02-26 16:50 UTC by vigonotion

## Proposed change

"Telegram chatbot" should be called "Telegram bot", like the corresponding integration. The link to source was broken because of this, that's why I had to change the filename as well.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-02-26 17:48 UTC, klaasnicolaas requested changes
We should also change this line then: https://github.com/home-assistant/home-assistant.io/blob/next/source/_redirects#L1888

2020-02-26 19:16 UTC, klaasnicolaas requested changes

2020-02-26 19:16 UTC, klaasnicolaas commented on source/_redirects
> +/components/telegram_bot /integrations/telegram_bot
```
/integrations/telegram_chatbot /integrations/telegram_bot
```

Maybe add also this rule

2020-02-27 11:53 UTC, frenck requested changes
Please update all internal links/references on our website as well.
Redirects are fine for handling external links, but our internal links should be correct.

2020-02-28 14:00 UTC, frenck approved these changes
LGTM! ✅  thanks!

2020-02-28 14:00 UTC, merged