Convert sense binary sensors to sensors that show power in watts
home-assistant/home-assistant.github.io pull request #12184
Opened 2020-02-26 09:22 UTC by bdraco

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-02-26 09:24 UTC, bdraco commented
<img width="321" alt="Screen Shot 2020-02-25 at 11 13 08 PM" src="https://user-images.githubusercontent.com/663432/75330866-d8a5cc00-5825-11ea-8f1d-ce6ef2d88203.png">
Sample of converted sensors showing power usage

2020-02-27 11:54 UTC, frenck requested changes

2020-02-27 11:54 UTC, frenck commented on source/_integrations/sense.markdown
> +In version 0.107 and later, usage sensors are created for each of the devices detected by your Sense monitor to show their power usage in Watts.
We don't add changelogs into our documentation.

Please adjust the documentation to reflect the latest codebase state.

2020-02-28 09:32 UTC, frenck approved these changes
Thanks, @bdraco! 👍

2020-02-28 09:32 UTC, merged