Add documentation for Lyric Integration
home-assistant/home-assistant.github.io pull request #12217
Opened 2020-02-29 23:03 UTC by shellster

## Proposed change

This documentation is to support the PR linked below.  It is documentation for Honeywell Lyric devices.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

https://github.com/home-assistant/home-assistant/pull/31387

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-01 15:38 UTC, klaasnicolaas requested changes

2020-03-01 15:38 UTC, klaasnicolaas commented on source/_integrations/lyric.markdown
> +ha_release: 0.106.2
```suggestion
ha_release: 0.107
```

2020-03-01 15:38 UTC, klaasnicolaas commented on source/_integrations/lyric.markdown
> +Configuration variables:
```suggestion
```

Please remove this line

2020-03-01 15:38 UTC, klaasnicolaas commented on source/_integrations/lyric.markdown
> +### Setup Developer Account and Keys
```suggestion
### Setup Developer Account and Keys

```

2020-03-09 16:52 UTC, whattheschnell commented
Looks like node.js was having issues when you committed.  Have to re-run the Lint Markdown test or re-commit.  Shouldn't be any reason for it not to pass.

2020-03-11 11:18 UTC, klaasnicolaas approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged 👍
⚠️ The ha_release might need an update before merging this one in.

2020-04-30 10:22 UTC, frenck commented
Closing PR as the parent PR has been closed.

2020-04-30 10:22 UTC, closed without merging