Tap action page
home-assistant/home-assistant.github.io pull request #12229
Opened 2020-03-02 00:06 UTC by PurelyNicole

## Proposed change

Move actions into their own page for issue #11886.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: n/a
- This PR fixes or closes issue: #11886

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-02 09:28 UTC, frenck requested changes
Thanks, @PurelyNicole! Really nice!

Don't be scared about the amount of review comments/suggestions. They all are more of the same.

I think we can deeplink better by linking to the anchor of the type of action directly. I've added them as review suggestions, so you can accept those if you agree (saves you the effort of changing them all manually).

👍

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/button.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/button.markdown
> +  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/button.markdown
> +  description: Action taken on card double tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card double tap. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/entities.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/entities.markdown
> +  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/entities.markdown
> +  description: Action taken on card double tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card double tap. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/glance.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/glance.markdown
> +  description: Action taken on card double tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card double tap. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card double tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card double tap. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-entity.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-glance.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-glance.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/lovelace/header-footer.markdown
> +  description: Action taken on card tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap. See [action documentation](/lovelace/actions/#tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-entity.markdown
> +  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-glance.markdown
> +  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-glance.markdown
> +  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture.markdown
> +  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card tap and hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/lovelace/header-footer.markdown
> +  description: Action to take on tap-and-hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action to take on tap-and-hold. See [action documentation](/lovelace/actions/#hold-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card double tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card double tap. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card double tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card double tap. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card double tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card double tap. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-elements.markdown
> +  description: Action taken on card double tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card double tap. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-entity.markdown
> +  description: Action taken on card double tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card double tap. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture-glance.markdown
> +  description: Action taken on card double tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card double tap. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/_lovelace/picture.markdown
> +  description: Action taken on card double tap. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action taken on card double tap. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/lovelace/header-footer.markdown
> +  description: Action to take on tap-and-hold. See [action documentation](/lovelace/actions/).
```suggestion
  description: Action to take on tap-and-hold. See [action documentation](/lovelace/actions/#double-tap-action).
```

2020-03-02 09:28 UTC, frenck commented on source/lovelace/actions.markdown
> +Some Lovelace cards have support for tap actions. These actions define what will happen when you tap or hold on an object within a card.
```suggestion

Some Lovelace cards have support for tap actions. These actions define what will happen when you tap or hold on an object within a card.
```

2020-03-02 09:28 UTC, frenck commented on source/lovelace/actions.markdown
> +* {% active_link /lovelace/picture-glance/ Picture Glance %}
```suggestion
- [Entity](/lovelace/entities/)
- [Entity Button](/lovelace/entity-button/)
- [Glance](/lovelace/glance/)
- [Picture](/lovelace/picture/)
- [Picture Element](/lovelace/picture-elements/)
- [Picture Entity](/lovelace/picture-entity/)
- [Picture Glance](/lovelace/picture-glance/)
```

2020-03-02 15:32 UTC, PurelyNicole commented
Agreed, the anchor link is a better approach.

2020-03-02 15:54 UTC, frenck approved these changes
Awesome!

Thanks for doing this! 👍

2020-03-02 15:54 UTC, merged

2020-03-03 14:53 UTC, iantrich commented
@PurelyNicole this was so needed! Awesome!