Add details around configuration and options flow
home-assistant/home-assistant.github.io pull request #12239
Opened 2020-03-02 15:34 UTC by kit-klein

## Proposed change

This PR adds missing details for the Konnected.io configuration flow based setup that was released in 0.106.  

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue: #12203

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-03 16:12 UTC, frenck requested changes
Some small things provided as suggestions.

In general, I think we should avoid the terms "configuration flow" or "options flow", these are terms used internally as developers. However, users aren't familiar with those terms, nor are they listed anywhere. In general, we refer to the "UI", "web interface" or the Home Assistant (web) frontend.

2020-03-03 16:12 UTC, frenck commented on source/_integrations/konnected.markdown
> +This integration uses the [SSDP](/integrations/ssdp) integration, which must be enabled for device discovery to work. If you don't want to use ssdp you'll need to manually provide the IP and Port inf
```suggestion
This integration uses the [SSDP](/integrations/ssdp) integration, which must be enabled for device discovery to work. If you don't want to use SSDP you'll need to manually provide the IP and Port information for each Konnected Panel. The IP/Port info can be found using the Konnected mobile app.
```

2020-03-03 16:12 UTC, frenck commented on source/_integrations/konnected.markdown
> +Selecting one of these discovered panels will launch a configuration flow to guide you through a setup process to initially connect the panel and generate a configuration entry. If your panel was dis
```suggestion
Selecting one of these discovered panels will launch a configuration flow to guide you through a setup process to initially connect the panel and generate a configuration entry. If your panel was discovered via SSDP, you shouldn't need any information to complete the configuration flow - simply confirm that the information is correct. If the configuration flow prompts you for IP/Port, you'll need to enter it. IP/Port info can be found using the Konnected mobile app.
```

2020-03-03 16:12 UTC, frenck commented on source/_integrations/konnected.markdown
> +If you have an existing `configuration.yaml` completing the configuration flow will do an one time import of the settings contained in `configuration.yaml`. Once the import creates a configuration en
```suggestion
If you have an existing `configuration.yaml` completing the configuration flow will do a one time import of the settings contained in `configuration.yaml`. Once the import creates a configuration entry the Konnected section of the `configuration.yaml` is no longer used - it is recommended to remove the `konnected` section of `configuration.yaml` and after the import occurs. Any future changes to settings should occur via the options provided in the Home Assistant web interface.
```

2020-03-03 16:12 UTC, frenck commented on source/_integrations/konnected.markdown
> +Once the configuration flow is completed you'll see a Konnected.io entry in **Configuration** -> **Integrations** => **Configured**.  If you imported settings from `configuration.yaml` you are now do
```suggestion
Once the configuration flow is completed you'll see a Konnected.io entry in **Configuration** -> **Integrations** => **Configured**.  If you imported settings from `configuration.yaml` you are now done! If you are setting up a new Konnected Alarm Panel or modifying settings, you'll need to utilize the Options Flow to configure zone behavior.
```

2020-03-03 16:12 UTC, frenck commented on source/_integrations/konnected.markdown
> +**Name (optional)** The friendly name for the entities associated with the zone
```suggestion
**Name (optional)** The friendly name for the entities associated with the zone.
```

2020-03-03 16:12 UTC, frenck commented on source/_integrations/konnected.markdown
> +Options Flow starts by having you configure the general behavior of each zone. You need to specify `Disabled`, `Binary Sensor`, `Digital Sensor`, or `Switchable Output` for each zone.  After that you
```suggestion
Options Flow starts by having you configure the general behavior of each zone. You need to specify `Disabled`, `Binary Sensor`, `Digital Sensor`, or `Switchable Output` for each zone.  After that, you'll be prompted, for each zone that is not disabled, to configure details of the zones' behavior. All zones will allow entry of a Name. Additional fields depend on how you configured the general behavior of the zone.  
```

2020-03-03 16:12 UTC, frenck commented on source/_integrations/konnected.markdown
> +**Times to repeat (optional):** The number of times to repeat the pulse each time the switch is activated
```suggestion
**Name: (optional)** The friendly name for the entity associated with the zone.
**Output when on:** The state of the switch when activated.
**Pulse Duration (optional):** The duration in ms to pulse the switch once activated.
**Pause between pulses (optional):** The duration in ms to wait between pulses when activated.
**Times to repeat (optional):** The number of times to repeat the pulse each time the switch is activated.
```

2020-03-03 22:51 UTC, kit-klein commented
> Some small things provided as suggestions.
> 
> In general, I think we should avoid the terms "configuration flow" or "options flow", these are terms used internally as developers. However, users aren't familiar with those terms, nor are they listed anywhere. In general, we refer to the "UI", "web interface" or the Home Assistant (web) frontend.

Thank you for the clean up suggestions.  I'll go through and replace up some of the technical terms (configuration.yaml) as well.

2020-03-06 12:58 UTC, kit-klein commented
> Some small things provided as suggestions.
> 
> In general, I think we should avoid the terms "configuration flow" or "options flow", these are terms used internally as developers. However, users aren't familiar with those terms, nor are they listed anywhere. In general, we refer to the "UI", "web interface" or the Home Assistant (web) frontend.

@frenck The latest commit removes the technical terminology.  Let me know if you see anything else.

2020-03-06 13:16 UTC, frenck approved these changes
Nice! @kit-klein 👍

2020-03-06 13:16 UTC, merged