Add Stib-Mivb component documentation
home-assistant/home-assistant.github.io pull request #12264
Opened 2020-03-04 09:51 UTC by Emilv2

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: #home-assistant/core/pull/32412
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-04 10:38 UTC, klaasnicolaas requested changes

2020-03-04 10:38 UTC, klaasnicolaas commented on source/_integrations/stib_mivb.markdown
> +sensor:
Only required config variables in the first example

2020-03-05 15:19 UTC, klaasnicolaas approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

2020-06-23 07:12 UTC, frenck commented
Closing PR as the parent PR has been closed.

2020-06-23 07:12 UTC, closed without merging