WIP: Add remote platform docs to directv
home-assistant/home-assistant.github.io pull request #12365
Opened 2020-03-14 17:20 UTC by ctalkington

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-16 12:42 UTC, frenck requested changes
Thanks for the PR @ctalkington!

I've left some comments, could you please take a look? Thanks! 👍

2020-03-16 12:42 UTC, frenck commented on source/_integrations/directv.markdown
> +The DirecTV remote platform allows you to send remote control buttons to a DirecTV receiver. It is automatically setup when a DirecTV receiver is configured.
```suggestion
The DirecTV remote platform allows you to send remote control buttons to a DirecTV receiver. It is automatically set up when a DirecTV receiver is configured.
```

2020-03-16 12:42 UTC, frenck commented on source/_integrations/directv.markdown
> +- power
I would suggest making those code blocks, as they are all values that can be used.

i.e.:
```suggestion
- `power`
```

2020-03-17 14:07 UTC, frenck commented
Looks good! Awaiting for it to get out of WIP :)

2020-04-02 22:45 UTC, frenck commented
@ctalkington What is the status of this docs PR? Since the parent PR has been merged...

2020-04-02 22:49 UTC, ctalkington commented
@frenck sorry juggling a bit here between platforms.

2020-04-02 22:53 UTC, frenck commented
Check thanks! 👍

2020-04-02 22:54 UTC, frenck approved these changes

2020-04-02 22:54 UTC, merged