Document HEOS group joining/unjoining
home-assistant/home-assistant.github.io pull request #12373
Opened 2020-03-14 22:19 UTC by klada

## Proposed change

Documents the joining and unjoining of HEOS groups (new feature)

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
https://github.com/home-assistant/core/pull/32568
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-16 12:39 UTC, frenck requested changes
Thanks for the PR @klada!

I've left some comments, could you please take a look? Thanks! 👍

2020-03-16 12:39 UTC, frenck commented on source/_integrations/heos.markdown
> +```json
Service calls should be formated in YAML.

2020-03-16 12:39 UTC, frenck commented on source/_integrations/heos.markdown
> +| `leader`               | The HEOS group leader. [Required]
Add a column to indicate if an attribute is required or not. Please see other parts of our documentation for an example.

2020-03-16 12:39 UTC, frenck commented on source/_integrations/heos.markdown
> +  "entity_id": "media_player.heos_player1",
Should be YAML.

2020-03-16 12:39 UTC, frenck commented on source/_integrations/heos.markdown
> +| `entity_id`            | Removes all grouping from this media player. [Required]
Same as above, add a column for requirements of attributes.

2020-03-16 17:39 UTC, klada commented
@frenck Thanks for the input, it makes sense to bring the docs in line with the rest of the codebase. Right now I simply followed the current style in the HEOS docs. I think I have 3 options:

a) Use your suggested documentation style for my changes only
b) Update the entire HEOS documentation to the new documentation style, including my changes
c) Come up with a new PR (against the "current" branch?) first to address the style issues with the existing docs.

Which way do you want me to go?

2020-03-16 19:17 UTC, frenck commented
I think fixing the current docs, rebasing this PR and update it to match would be the best option.

JSON input, for example, isn't used anymore and already afffects current users.

2020-06-22 20:31 UTC, frenck submitted a review, later dismissed
Rebased the PR onto the latest `next` branch, converted JSON -> YAML and fixed the tables. 🎉 

✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-11-29 13:04 UTC, frenck commented
Replaced by #20428

2021-11-29 13:04 UTC, closed without merging