Added example for extracting sensor data from email body using regex.
home-assistant/home-assistant.github.io pull request #12374
Opened 2020-03-14 22:36 UTC by scstraus

## Proposed change

This is a good working example of how to turn an email body into useful sensors which I think would save a lot of people time in building the same. I believe this is the second most common use case for this component other than the first example I gave.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.
- [X] Added an example to existing documentation

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-16 12:36 UTC, frenck requested changes
Thanks for the PR @scstraus!

I left some small comments/suggestions. Could you take a look? Thanks! 👍

2020-03-16 12:36 UTC, frenck commented on source/_integrations/imap_email_content.markdown
> +{% raw %}
Raw is not needed here.

2020-03-16 12:36 UTC, frenck commented on source/_integrations/imap_email_content.markdown
> +This example shows how to extract numbers or other formatted data from an email to change the value of a template sensor to a value extracted from the email. In this example, we will be extracting en
```suggestion
This example shows how to extract numbers or other formatted data from an email to change the value of a template sensor to a value extracted from the email. In this example, we will be extracting energy use, cost, and billed amount from an email (from Georgia Power) and putting it into sensor values using a template sensor that runs against our IMAP email sensor already set up. A sample of the body of the email used is below:
```

2020-03-16 12:36 UTC, frenck commented on source/_integrations/imap_email_content.markdown
> +By making small changes to the regular expressions defined above, a similar structure can parse other types of data out of the body of other emails.
```suggestion
By making small changes to the regular expressions defined above, a similar structure can parse other types of data out of the body of other emails.
```

2020-03-16 12:50 UTC, scstraus commented
All changes accepted. Was too busy double checking syntax and forgot to check grammar ;-).

2020-03-16 13:11 UTC, frenck commented
One comment is unresolved + the build is still failing.
Please make sure you address all of that, thanks! 👍

2020-03-17 10:01 UTC, scstraus commented
Okay think I got the last one, sorry.

2020-03-17 23:29 UTC, klaasnicolaas commented
Fixed the build errors for you 😄

2020-03-17 23:30 UTC, klaasnicolaas approved these changes

2020-03-18 09:35 UTC, frenck approved these changes
Yep! Thanks guys! 👍

2020-03-18 09:35 UTC, merged

2020-03-19 20:52 UTC, scstraus reviewed
Thanks guys, I suppose it's obvious by now that I am hopeless when it comes to github.. But I know how hard these examples were to come by so I wanted to make sure they were preserved for others.