Add fill and line color docs
home-assistant/home-assistant.github.io pull request #12380
Opened 2020-03-15 17:41 UTC by timmo001

## Proposed change

Adds docs for #5224

## Type of change

- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).

## Additional information

- Link to parent pull request in the codebase: home-assistant/frontend/pull/5224

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-16 12:21 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-03-16 18:44 UTC, frenck requested changes

2020-03-16 18:44 UTC, frenck commented on source/_lovelace/sensor.markdown
> +graph:
?
```suggestion
graph_color:
```

2020-03-16 18:52 UTC, timmo001 commented on source/_lovelace/sensor.markdown
> +graph:
Thanks @frenck ! :1st_place_medal:

2020-03-16 19:13 UTC, frenck approved these changes

2020-03-21 11:16 UTC, timmo001 commented
Attached PR closed

2020-03-21 11:16 UTC, closed without merging