Add AirVisual Node/Pro docs
home-assistant/home-assistant.github.io pull request #12382
Opened 2020-03-15 19:42 UTC by bachya

## Proposed change

This PR adds docs for the forthcoming support of AirVisual Node/Pro units.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/32815
- This PR fixes or closes issue: N/A

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-16 12:18 UTC, frenck requested changes

2020-03-16 12:18 UTC, frenck commented on source/_integrations/airvisual.markdown
> +Note that an API key-based entry can be mixed with one or more Node/Pro-baesd entries
```suggestion
Note that an API key-based entry can be mixed with one or more Node/Pro-based entries
```

2020-03-16 12:18 UTC, frenck commented on source/_integrations/airvisual.markdown
> +    # Or, to use an AirVisual Node/Pro:
Maybe just add 2 example blocks instead of adding it in as a code comment. It makes it more distinctive and easier to copy and paste.

2020-03-16 19:14 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-04-20 02:09 UTC, bachya commented
Per [ADR-0010](https://github.com/home-assistant/architecture/blob/master/adr/0010-integration-configuration.md), 7a9b32773f8d1c15bd54f97e2eb0d74438f6f841 removes `configuration.yaml` docs for this new functionality.

2020-04-23 22:13 UTC, bachya commented
@frenck Apologies: 7a9b327 re-triggered the need for a review, so I can't merge this.

2020-04-23 22:35 UTC, frenck commented
Don't worry about it if this happens we pick it up, as the label/project board it moved to the parent-merged category 😉

2020-04-23 22:36 UTC, frenck approved these changes

2020-04-23 22:36 UTC, merged