add KEF services, see https://github.com/home-assistant/core/pull/31967
home-assistant/home-assistant.github.io pull request #12417
Opened 2020-03-17 23:17 UTC by basnijholt

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/31967

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-18 10:33 UTC, frenck requested changes
Thanks for the PR @basnijholt!

Some small suggestions, could you please take a look? Thanks! 👍

2020-03-18 10:33 UTC, frenck commented on source/_integrations/kef.markdown
> +## Advanced - configure DSP settings and services
```suggestion
## Services
```

2020-03-18 10:33 UTC, frenck commented on source/_integrations/kef.markdown
> +| bass_extension         | Yes      | "Bass extension" selector ("Less", "Standard", or "Extra") |
```suggestion
| Service data attribute | Optional | Description |
| ---------------------- | -------- | ----------- |
| entity_id              | No       | The entity_id of the KEF speaker. |
| desk_mode              | Yes      | "Desk mode" (`true` or `false`) |
| wall_mode              | Yes      | "Wall mode" (`true` or `false`) |
| phase_correction       | Yes      | "Phase correction" (`true` or `false`) |
| high_pass              | Yes      | "High-pass mode" (`true` or `false`) |
| sub_polarity           | Yes      | "Sub polarity" (`-` or `+`) |
| bass_extension         | Yes      | "Bass extension" selector (`Less`, `Standard`, or `Extra`) |
```

2020-03-18 10:33 UTC, frenck commented on source/_integrations/kef.markdown
> +### Service `update_dsp`
```suggestion
### Service `kef.update_dsp`
```

2020-03-18 10:33 UTC, frenck commented on source/_integrations/kef.markdown
> +### Service `set_mode`
```suggestion
### Service `kef.set_mode`
```

2020-03-18 10:33 UTC, frenck commented on source/_integrations/kef.markdown
> +### Service `set_desk_db`
```suggestion
### Service `kef.set_desk_db`
```

2020-03-18 10:33 UTC, frenck commented on source/_integrations/kef.markdown
> +### Service `set_wall_db`
```suggestion
### Service `kef.set_wall_db`
```

2020-03-18 10:33 UTC, frenck commented on source/_integrations/kef.markdown
> +### Service `set_treble_db`
```suggestion
### Service `kef.set_treble_db`
```

2020-03-18 10:33 UTC, frenck commented on source/_integrations/kef.markdown
> +### Service `set_high_hz`
```suggestion
### Service `kef.set_high_hz`
```

2020-03-18 10:33 UTC, frenck commented on source/_integrations/kef.markdown
> +### Service `set_low_hz`
```suggestion
### Service `kef.set_low_hz`
```

2020-03-18 10:33 UTC, frenck commented on source/_integrations/kef.markdown
> +### Service `set_sub_db`
```suggestion
### Service `kef.set_sub_db`
```

2020-03-18 10:36 UTC, basnijholt commented
Thanks @frenck, I've committed your changes!

2020-03-18 10:38 UTC, frenck requested changes
Well, that was fast @basnijholt! 👍

2020-03-18 10:38 UTC, frenck submitted a review, later dismissed
Wrong button, wanted to approve it.

2020-03-30 23:04 UTC, frenck approved these changes

2020-03-30 23:04 UTC, merged