Add Netatmo webhook event examples
home-assistant/home-assistant.github.io pull request #12494
Opened 2020-03-23 15:21 UTC by cgtobi

## Proposed change

Add example automations to illustrate the usage of the netatmo events.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-23 15:47 UTC, klaasnicolaas requested changes

2020-03-23 15:47 UTC, klaasnicolaas commented on source/_integrations/netatmo.markdown
> +
The second example needs `{% raw %}` / `{% endraw %}` tags

2020-03-23 15:51 UTC, frenck commented on source/_integrations/netatmo.markdown
> +```
```suggestion
Example:

{% raw %}

```yaml
# Example automation
- alias: Motion at home
  description: 'Motion detected at home'
  trigger:
  - event_type: netatmo_event
    platform: event
    event_data:
      type: movement
  action:
  - data_template:
      message: >
        {{ trigger.event.data["data"]["message"] }}  
        at {{ trigger.event.data["data"]["home_name"] }}
      title: Netatmo event
    service: persistent_notification.create
```

{% raw %}

```

2020-03-24 12:02 UTC, frenck approved these changes
Thanks, @cgtobi 👍

2020-03-24 12:02 UTC, merged