Add ShowOnMap flag to show each/hide entity on map
home-assistant/home-assistant.github.io pull request #12541
Opened 2020-03-29 17:29 UTC by FlavorFx

## Proposed change

In Tankerkoenig the display of the sensors on the map can be switched on or off.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/33400
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-03-29 19:17 UTC, guillempages requested changes

2020-03-29 19:17 UTC, guillempages commented on source/_integrations/tankerkoenig.markdown
> +  show_on_map: false
```suggestion
```
The "minimum configuration" does not require the optional flag "show_on_map"

2020-03-29 19:17 UTC, guillempages commented on source/_integrations/tankerkoenig.markdown
> +  required: false
If it is not required, you are missing the "default" value
```suggestion
  default: True
  required: false
```

2020-03-30 11:13 UTC, frenck requested changes
Thanks for the PR @FlavorFx!

I've left a couple of comments and suggestions, could you please take a look? thanks! 👍

2020-03-30 11:13 UTC, frenck commented on source/_integrations/tankerkoenig.markdown
> +  default: True
```suggestion
  default: true
```

2020-03-30 11:13 UTC, frenck commented on source/_integrations/tankerkoenig.markdown
> +  default: true
default is specified twice.
```suggestion
```

2020-03-30 11:13 UTC, frenck commented on source/_integrations/tankerkoenig.markdown
> +  show_on_map: true
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

```suggestion
```

2020-03-30 18:55 UTC, guillempages approved these changes
Looks good to me

2020-03-31 17:11 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-04-03 13:28 UTC, merged