Add config flow to Synology DSM
home-assistant/home-assistant.github.io pull request #12597
Opened 2020-03-31 23:05 UTC by Quentame

## Proposed change

Follows parrent PR home-assistant/core#32704

And so following breaking changes "Integration has been rename from `synologydsm` to `synology_dsm`" from parent PR home-assistant/core#32704

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#32704
- Link to parent pull request in the Brands repository: home-assistant/brands/pull/876
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-01 10:10 UTC, frenck requested changes
A redirect from the old page needs to be added to the redirects file.

2020-04-01 10:10 UTC, frenck commented on source/_integrations/synology_dsm.markdown
> +## Setup the integration
```suggestion
## Configuration
```

2020-04-01 10:10 UTC, frenck commented on source/_integrations/synology_dsm.markdown
> +There is two ways to integrate Synology DSM in Home Assistant.
```suggestion
There are two ways to integrate Synology DSM in Home Assistant.
```

2020-04-01 10:10 UTC, frenck commented on source/_integrations/synology_dsm.markdown
> +Due to the nature of the Synology DSM API it is required to grant the user admin rights. This is related to the fact that utilization information is stored in the core module.
```suggestion
Due to the nature of the Synology DSM API, it is required to grant the user admin rights. This is related to the fact that utilization information is stored in the core module.
```

2020-04-01 10:10 UTC, frenck commented on source/_integrations/synology_dsm.markdown
> +When creating the user it is possible to deny access to all locations and applications. By doing this the user will not be able to login to the web interface or view any of the files on the Synology
```suggestion
When creating the user, it is possible to deny access to all locations and applications. By doing this, the user will not be able to login to the web interface or view any of the files on the Synology NAS. It is still able to read the utilization and storage information using the API.
```

2020-04-01 10:10 UTC, frenck commented on source/_integrations/synology_dsm.markdown
> +Using two-factor authentication is not supported. Please use a strong randomly generated password.
```suggestion
Using two-factor authentication is not supported. Please use a strong, randomly generated password.
```

2020-04-01 10:10 UTC, frenck commented on source/_integrations/synology_dsm.markdown
> +ha_domain: synology_dsm
```suggestion
ha_domain: synologydsm
```

2020-04-03 16:07 UTC, Quentame commented
Redirect seems to work well (tested on the netlify/home-assistant-docs/deploy-preview build)

2020-04-06 11:58 UTC, frenck approved these changes

2020-04-06 11:58 UTC, merged