Added refresh rate for picture entity
home-assistant/home-assistant.github.io pull request #12710
Opened 2020-04-06 00:31 UTC by kkellner

## Proposed change

The hui-image used in picture-entity card has a hard-coded refresh rate of 10 seconds.  To provide more flexibility in the image refresh rate a new user-configurable attribute has been added to the picture-entity card.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-06 00:33 UTC, kkellner commented
Code PR:  https://github.com/home-assistant/frontend/pull/5466

2020-04-06 08:28 UTC, frenck requested changes
Thanks for the PR @kkellner!

Left a small comment, could you please take a look?

Thanks! 👍

2020-04-06 08:28 UTC, frenck commented on source/_lovelace/picture-entity.markdown
> +  type: string
Please add the `default: ` key.

2020-04-06 10:28 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-06-20 16:55 UTC, frenck commented
Closing this PR as the parent PR has been closed.

2020-06-20 16:55 UTC, closed without merging

2024-10-15 18:45 UTC, EvanMulawski commented
Can this be reopened and reconsidered? In my opinion, there is no reason to not have this be customizable when a tenet of HA is to be customizable. If the device and the user's environment can support a live video feed, which is one of the options for this card, there is no reason it couldn't support a faster snapshot refresh rate.