Panel proxy
home-assistant/home-assistant.github.io pull request #12852
Opened 2020-04-12 06:30 UTC by doudz

## Proposed change

Add documentation for panel_proxy integration.
panel_proxy allow create reverse proxy without setting up NGINX or similar

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-12 21:02 UTC, klaasnicolaas requested changes

2020-04-12 21:02 UTC, klaasnicolaas commented on source/_redirects
> +/components/panel_proxy /integrations/panel_proxy
For a new integrations this isn't necessary

2020-04-12 21:02 UTC, klaasnicolaas commented on source/_integrations/panel_proxy.markdown
> +ha_release: 0.107
```suggestion
ha_release: 0.109
```

2020-05-17 19:16 UTC, frenck commented
Closing PR, since the parent PR has been closed.

2020-05-17 19:16 UTC, closed without merging