Add Opensprinkler integration documentation
home-assistant/home-assistant.github.io pull request #12953
Opened 2020-04-14 04:01 UTC by vinteo

## Proposed change

Add Opensprinkler integration documentation

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/34146
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-14 10:46 UTC, klaasnicolaas requested changes

2020-04-14 10:46 UTC, klaasnicolaas commented on source/_integrations/opensprinkler.markdown
> +devices:
I'm missing the `run_seconds` option.

2020-04-14 10:46 UTC, klaasnicolaas commented on source/_integrations/opensprinkler.markdown
> +      description: The port to the Opensprinkler device API. Defaults to 8080 which is the Opensprinkler default.
```suggestion
      description: The port to the Opensprinkler device API.
```

2020-04-14 10:46 UTC, klaasnicolaas commented on source/_integrations/opensprinkler.markdown
> +      required: false
Add:
```suggestion
      default: Opensprinkler
```

2020-04-14 10:46 UTC, klaasnicolaas commented on source/_integrations/opensprinkler.markdown
> +      description: The name of your Opensprinkler. Defaults to `Opensprinkler`
```suggestion
      description: The name of your Opensprinkler.
```

2020-04-14 10:49 UTC, klaasnicolaas requested changes

2020-04-14 10:49 UTC, klaasnicolaas commented on source/_integrations/opensprinkler.markdown
> +  devices:
Only required config options in the first example

2020-04-14 22:55 UTC, klaasnicolaas approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

2020-08-08 10:37 UTC, frenck commented
Closing PR as the parent PR has been closed.

2020-08-08 10:37 UTC, closed without merging