Add config flow and device registry to fritzbox integration
home-assistant/home-assistant.github.io pull request #12980
Opened 2020-04-15 12:36 UTC by escoand

## Proposed change

Add config flow and device registry to fritzbox integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/31240
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-17 09:58 UTC, klaasnicolaas requested changes

2020-04-17 09:58 UTC, klaasnicolaas commented on source/_integrations/fritzbox.markdown
> +Go to the integrations page in your configuration and click on new integration -> AVM FRITZ!Box. If you have enabled SSDP discovery, it’s likely that you just have to confirm the detected device with
```suggestion
Go to the integrations page in your configuration and click on **new integration** -> **AVM FRITZ!Box**. If you have enabled SSDP discovery, it’s likely that you just have to confirm the detected device with username and password.
```

2020-04-19 11:21 UTC, frenck requested changes

2020-04-19 11:21 UTC, frenck commented on source/_integrations/fritzbox.markdown
> +      username: admin
```suggestion
```

We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2020-04-19 13:52 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-04-20 13:08 UTC, frenck approved these changes

2020-04-20 13:08 UTC, merged