Emphasize the need for a URL
home-assistant/home-assistant.github.io pull request #13016
Opened 2020-04-16 20:18 UTC by Skorfulose

## Proposed change

Emphasize the need for a URL (as opposed to IP/hostname only) in this integration's docs.
Without the "http://" specifier you'll receive an error on config check or Home Assistant restart.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-16 20:37 UTC, frenck requested changes
Thanks for the PR @Skorfulose!

I've reviewed it and left some suggestions, could you please take a look? Thanks!

2020-04-16 20:37 UTC, frenck commented on source/_integrations/fronius.markdown
> +    resource: http://FRONIUS_URL
Please revert this, as this is a placeholder per our standards.

```suggestion
    resource: FRONIUS_URL
```

2020-04-16 20:37 UTC, frenck commented on source/_integrations/fronius.markdown
> +  description: "The URL of the Fronius device (e.g. \"http://192.0.2.0\" or \"http://fronius.local\")"
```suggestion
  description: "The URL of the Fronius device (e.g., `http://192.0.2.0` or `http://fronius.local`)"
```

2020-04-16 20:37 UTC, frenck commented on source/_integrations/fronius.markdown
> +    resource: http://192.0.2.0
```suggestion
    resource: FRONIUS_URL
```

2020-04-16 20:45 UTC, Skorfulose reviewed
Suggestions accepted 👍

2020-04-17 07:16 UTC, frenck approved these changes
Thanks, @Skorfulose 👍

2020-04-17 07:16 UTC, merged