Updating withings doc to use webhook feature
home-assistant/home-assistant.github.io pull request #13116
Opened 2020-04-21 16:19 UTC by vangorra

## Proposed change

Adding documentation for new option in withings integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/34447
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-06-19 17:44 UTC, TomBrien requested changes
Just a few small tweaks please ✏

2020-06-19 17:44 UTC, TomBrien commented on source/_integrations/withings.markdown
> +    - USER_PROFILE_NAME
Indentation looks wrong here. Could you fix please.

2020-06-19 17:44 UTC, TomBrien commented on source/_integrations/withings.markdown
> +    - If webhook is enabled
```suggestion
    - If `use_webhook` is enabled:
```

2020-06-19 17:44 UTC, TomBrien commented on source/_integrations/withings.markdown
> +    - If webhook is not enabled
```suggestion
    - If `use_webhook` is not enabled:
```

2020-06-19 17:44 UTC, TomBrien commented on source/_integrations/withings.markdown
> +    use_webhook: true  # Internet access to Home Assistant required for this option.
```suggestion
    use_webhook: true
```

Best to avoid the comment here, it is covered by the explanation below

2020-06-20 18:11 UTC, TomBrien requested changes
One last thing and then good to go I think

2020-06-20 18:11 UTC, TomBrien commented on source/_integrations/withings.markdown
> +      - USER_PROFILE_NAME
These still seem under indented by two spaces. It's in a list.
```suggestion
      profiles:
        - USER_PROFILE_NAME 
```

2020-06-20 19:24 UTC, TomBrien submitted a review, later dismissed
Looks great now. Thanks 👍

2020-06-21 20:45 UTC, klaasnicolaas requested changes

2020-06-21 20:45 UTC, klaasnicolaas commented on source/_integrations/withings.markdown
> +      use_webhook: true
```suggestion
```
In the first example, we would like to see only config variables that are required.

2020-06-22 11:49 UTC, frenck approved these changes
Thanks, @vangorra 👍

2020-06-22 11:49 UTC, merged