Add Elexa Guardian docs
home-assistant/home-assistant.github.io pull request #13150
Opened 2020-04-24 03:53 UTC by bachya

## Proposed change

This PR adds documentation for the forthcoming Elexa Guardian integration.
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/34627
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/1489
- This PR fixes or closes issue: N/A

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-24 09:16 UTC, klaasnicolaas requested changes

2020-04-24 09:16 UTC, klaasnicolaas commented on source/_integrations/guardian.markdown
> +ha_release: 0.110.0
```suggestion
ha_release: "0.110"
```

2020-04-24 09:16 UTC, klaasnicolaas commented on source/_integrations/guardian.markdown
> +`Configuration > Integrations`. If you have the `zeroconf` integration enabled, Home Assistant
```suggestion
**Configuration** -> **Integrations**. If you have the `zeroconf` integration enabled, Home Assistant
```

2020-04-24 17:00 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2020-05-27 19:32 UTC, frenck approved these changes

2020-05-27 19:32 UTC, merged