Upb
home-assistant/home-assistant.github.io pull request #13166
Opened 2020-04-25 18:10 UTC by gwww

## Proposed change

New integration for Universal Powerline Bus (UPB).

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/1502
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-25 18:33 UTC, klaasnicolaas requested changes

2020-04-25 18:33 UTC, klaasnicolaas commented on source/_integrations/upb.markdown
> +ha_release: 0.110
```suggestion
ha_release: "0.110"
```

2020-04-25 20:18 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2020-05-08 20:13 UTC, merged

2020-05-09 01:58 UTC, bdraco commented
Already merged :)