Updates for Environment Canada camera component
home-assistant/home-assistant.github.io pull request #13175
Opened 2020-04-26 18:28 UTC by michaeldavie

## Proposed change

Documents changes to `environment_canada` configuration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/34729
- This PR fixes or closes issue: https://github.com/michaeldavie/env_canada/issues/17

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-26 18:56 UTC, michaeldavie commented
Sorry, I don't understand the build error.

2020-04-26 19:09 UTC, klaasnicolaas requested changes
This should fix the build error

2020-04-26 19:09 UTC, klaasnicolaas commented on source/_integrations/environment_canada.markdown
> +  default: `rain` from April to October, `snow` from November to March
```suggestion
  default: "`rain` from April to October, `snow` from November to March"
```

2020-05-08 12:20 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-05-23 09:22 UTC, frenck commented
Closing PR, as the parent PR has been closed.

2020-05-23 09:22 UTC, closed without merging