WIP: Update Sonarr for Config Flow
home-assistant/home-assistant.github.io pull request #13178
Opened 2020-04-26 20:07 UTC by ctalkington

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-05-05 11:48 UTC, klaasnicolaas requested changes

2020-05-05 11:48 UTC, klaasnicolaas commented on source/_integrations/sonarr.markdown
> +### Configuration
```suggestion
## Configuration
```

2020-06-01 13:38 UTC, frenck approved these changes
Thanks, @ctalkington 👍

2020-06-01 13:42 UTC, merged

2020-09-08 16:24 UTC, agneevX commented
Why was most of the documentation removed? Makes no sense.

2020-09-08 16:56 UTC, frenck commented
@agneevX Because the removed documentation doesn't apply anymore. It will now be configured via the UI, YAML support has been removed from the integration and thus removed from the documentation.

2020-09-08 17:00 UTC, agneevX commented
Right but there are no details or indication of what the integration has to offer. 

Might as well make it blank.

2020-09-08 17:05 UTC, frenck commented
That wasn't there before either, only configuration has been removed. However, feel free to help out and open a PR to add it.