Adding documentation for blastbot_cloud integration
home-assistant/home-assistant.github.io pull request #13176
Opened 2020-04-26 19:38 UTC by Rodmg

Adding documentation for blastbot_cloud integration

## Proposed change

Adding documentation for blastbot_cloud integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: WIP
- Link to parent pull request in the Brands repository: TBD

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-26 20:18 UTC, klaasnicolaas requested changes

2020-04-26 20:18 UTC, klaasnicolaas commented on source/_integrations/blastbot_cloud.md
> +ha_release: TBD
```suggestion
ha_release: "0.110"
```

2020-04-26 23:20 UTC, cogneato approved these changes
:+1:

2020-07-12 13:51 UTC, frenck commented
Closing PR as the parent PR has been closed.

2020-07-12 13:51 UTC, closed without merging