Update zha.markdown to clearify zigpy-cc & zigpy-zigate as experimental
home-assistant/home-assistant.github.io pull request #13192
Opened 2020-04-27 13:14 UTC by Gamester17

## Proposed change

Update zha.markdown to clarify that zigpy-cc and zigpy-zigate are should still be considered as experimental.

This is as per zigpy README.md https://github.com/zigpy/zigpy/blob/dev/README.md

Some people might get the wrong impression that ZHA is unstable with those without a statement like this.

Also updated URL for zigpy-cc and zigpy-zigate as both those have moved to zigpy organization on GitHub.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  Not applicable.
- Link to parent pull request in the Brands repository:  Not applicable.
- This PR fixes or closes issue: Not applicable.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-27 14:06 UTC, klaasnicolaas requested changes

2020-04-27 14:06 UTC, klaasnicolaas commented on source/_integrations/zha.markdown
> +## Compatible hardware
```suggestion
## Compatible hardware

```

2020-04-28 13:23 UTC, Gamester17 commented
Suggestion applied so why is this still blocked now?

2020-05-04 12:38 UTC, Gamester17 commented
@dmulcahey OK or?

2020-05-07 10:16 UTC, Gamester17 commented
@dmulcahey @Adminiuga Note that this should preferably go in as soon as possible so many people don't wrongly get a bad initial experience of ZHA just because they tested it with an experimental dongle

2020-05-07 13:03 UTC, Adminiuga commented
Agree

2020-05-07 15:14 UTC, klaasnicolaas commented
Just wait until we are ready to review and merge your pull request. We do not judge faster if people keep asking for attention ...

2020-05-08 22:54 UTC, frenck approved these changes
Thanks, @Gamester17 👍

2020-05-08 22:55 UTC, merged