Make user configuration for unifi-os clearer.
home-assistant/home-assistant.github.io pull request #13217
Opened 2020-04-29 15:01 UTC by florisvdk

## Proposed change

Make the configuration for unifi-os clearer. (udmp and soon udm, ckg2)

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-30 14:26 UTC, fabaff requested changes
Ubiquiti is using "UniFi OS" and not "Unifi-os".

Could you please change it?

2020-04-30 14:39 UTC, frenck requested changes

2020-04-30 14:39 UTC, frenck commented on source/_integrations/unifi.markdown
> +For Unifi-os a local only user needs to be created. A user which uses the Ubiquiti cloud will not work. You can do this in the manage users section on the Unifi-os dashboard. Make sure to give it the
```suggestion
For Unifi-os a local-only user needs to be created. A user who uses the Ubiquiti cloud will not work. You can do this in the manage users section on the Unifi-os dashboard. Make sure to give it the right permissions for the functions you want to use. 
```

2020-04-30 14:39 UTC, frenck commented on source/_integrations/unifi.markdown
> +### Unifi-os
```suggestion
### UniFi OS
```

2020-05-01 13:42 UTC, frenck approved these changes
Thanks, @florisvdk! 👍

2020-05-01 13:42 UTC, merged