Adding documentation to new Jenkins integration
home-assistant/home-assistant.github.io pull request #13222
Opened 2020-04-29 18:34 UTC by Callet91

## Proposed change

This pull request adds the documentation for the new Jenkins integration. 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/34876
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-29 20:57 UTC, klaasnicolaas requested changes

2020-04-29 20:57 UTC, klaasnicolaas commented on source/_integrations/jenkins.markdown
> +ha_release: 0.109
```suggestion
ha_release: "0.110"
```

2020-04-30 13:20 UTC, klaasnicolaas approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged 👍
⚠️ The ha_release might need an update before merging this one in.

2021-06-26 12:05 UTC, frenck commented
Closing PR as the parent PR has been closed stale.

2021-06-26 12:05 UTC, closed without merging