Documentation for Natural Resources Wales river level sensor integration
home-assistant/home-assistant.github.io pull request #13223
Opened 2020-04-29 19:05 UTC by gimpje

## Proposed change

Add documentation for Natural Resources Wales river level sensor integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: todo
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/1532

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-04-29 21:20 UTC, klaasnicolaas requested changes

2020-04-29 21:20 UTC, klaasnicolaas commented on source/_integrations/natural_resources_wales.markdown
> +  description: The language to use for the sensor properties. EN or CY.
```suggestion
  description: The language to use for the sensor properties. `EN` or `CY`.
```

2020-04-29 21:20 UTC, klaasnicolaas commented on source/_integrations/natural_resources_wales.markdown
> +ha_release: 0.109
```suggestion
ha_release: "0.110"
```

2020-07-12 13:54 UTC, frenck commented
Closing PR as the parent PR has been closed.

2020-07-12 13:54 UTC, closed without merging