Add default_interface config to zeroconf
home-assistant/home-assistant.github.io pull request #13315
Opened 2020-05-06 03:44 UTC by bdraco

## Proposed change

Add default_interface config to zeroconf

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/35281
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-05-06 06:30 UTC, klaasnicolaas requested changes

2020-05-06 06:30 UTC, klaasnicolaas commented on source/_integrations/zeroconf.markdown
> +zeroconf:
```suggestion
zeroconf:
  description: 
  type: map
  keys:
```

2020-05-06 06:30 UTC, klaasnicolaas commented on source/_integrations/zeroconf.markdown
> +     required: true
```suggestion
     required: false
```

2020-05-06 14:16 UTC, bdraco commented
Thanks @klaasnicolaas !

2020-05-08 11:10 UTC, frenck approved these changes
Thanks, @bdraco! 👍

2020-05-08 11:10 UTC, merged