OpenWeatherMap config_flow documentation
home-assistant/home-assistant.github.io pull request #13318
Opened 2020-05-06 11:34 UTC by freekode

## Proposed change
Updated documentation for config_flow  in OpenWeatherMap

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#34659
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-05-06 12:11 UTC, klaasnicolaas commented on source/_integrations/openweathermap.markdown
> -ha_category:
Why are you removing the `ha_category`?

2020-05-06 12:12 UTC, klaasnicolaas requested changes

2020-05-06 12:12 UTC, klaasnicolaas commented on source/_integrations/openweathermap.markdown
>  ---
Add the option: `ha_config_flow: true`

2020-07-14 09:30 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-09-05 06:29 UTC, merged