Documentation for Acmeda Integration
home-assistant/home-assistant.github.io pull request #13331
Opened 2020-05-07 12:22 UTC by atmurray

Documentation for the proposed Rollease Acmeda Automate integration: https://github.com/home-assistant/core/pull/33384

## Proposed change
Add documentation of the proposed Rollease Acmeda integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/33384
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/1548
- This PR fixes or closes issue: 

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].
[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-05-17 09:06 UTC, klaasnicolaas requested changes

2020-05-17 09:06 UTC, klaasnicolaas commented on source/_integrations/acmeda.markdown
> +ha_release: '0.109'
```suggestion
ha_release: 0.111
```

2020-05-17 09:06 UTC, klaasnicolaas requested changes

2020-05-17 09:06 UTC, klaasnicolaas commented on source/_integrations/acmeda.markdown
> +
```suggestion
```

2020-05-18 09:10 UTC, frenck approved these changes
Thanks, @atmurray 👍

2020-05-18 09:14 UTC, merged