Update synology_srm component to use the new config flow workflow
home-assistant/home-assistant.github.io pull request #13368
Opened 2020-05-09 13:32 UTC by aerialls

## Proposed change

Update the documentation to reflect changes for the Synology SRM component.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/35412
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-05-12 07:23 UTC, frenck requested changes
Thanks for the PR @aerialls! 👍 

I've reviewed it and left some comments. Could you please take a look?

Thanks 👍

2020-05-12 07:23 UTC, frenck commented on source/_integrations/synology_srm.markdown
> +</div>
We don't keep a changelog in our documentation. Please remove this note.

2020-05-12 07:23 UTC, frenck commented on source/_integrations/synology_srm.markdown
> +The integration can be configured through the user interface at *Configuration* -> *Integrations*. Search for "Synology SRM", fill in the configuration form with your username and password, and then
I believe there is a step missing, where the user needs to click something to be able to search for "Synology SRM"...

2020-05-12 08:32 UTC, aerialls commented
Hello, thanks for the feedback! I've updated my PR with your remarks.

2020-05-22 10:19 UTC, aerialls commented
Hello @frenck. Did you have time to review my changes and also the main PR on `core`? Thanks!

2020-06-01 15:16 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-08-03 09:48 UTC, frenck commented
Closing PR as the parent PR has been closed.

2020-08-03 09:48 UTC, closed without merging