Improve JSON attributes template example
home-assistant/home-assistant.github.io pull request #13382
Opened 2020-05-10 08:09 UTC by emontnemery

## Proposed change

Improve JSON attributes template example

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2020-05-10 08:10 UTC, emontnemery commented
@deepcoder Please help to review

2020-05-13 08:13 UTC, fabaff requested changes

2020-05-13 08:13 UTC, fabaff commented on source/_integrations/sensor.mqtt.markdown
> +### Value template example - Owntracks battery level sensor
We are in the "Examples" section.

```suggestion
### Owntracks battery level sensor
```

2020-05-13 08:13 UTC, fabaff commented on source/_integrations/sensor.mqtt.markdown
> +### Value template example - Temperature and humidity sensors
```suggestion
### Temperature and humidity sensors
```

2020-05-15 17:31 UTC, frenck approved these changes
Thanks, @emontnemery 👍

2020-05-15 17:31 UTC, merged