Add config flows for bmw_connected_drive
home-assistant/home-assistant.github.io pull request #13471
Opened 2020-05-17 10:02 UTC by rikroe

## Proposed change

Add documentation for config flows implemented in home-assistant/core#35732.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#35732
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-05-19 12:36 UTC, klaasnicolaas requested changes

2020-05-19 12:36 UTC, klaasnicolaas commented on source/_integrations/bmw_connected_drive.markdown
>  ## Configuration
```suggestion
## Configuration

```

2020-05-19 12:36 UTC, klaasnicolaas commented on source/_integrations/bmw_connected_drive.markdown
> +The preferred way to enable the `bmw_connected_drive`  integration is via __Configuration > Integrations__. After connecting to your account, you can set the following settings in the integration's o
```suggestion
The preferred way to enable the `bmw_connected_drive` integration is via **Configuration** > **Integrations**. After connecting to your account, you can set the following settings in the integration's options:
```

2020-05-19 12:36 UTC, klaasnicolaas commented on source/_integrations/bmw_connected_drive.markdown
> +The following settings in your `configuration.yaml` file are considered legacy. They will be imported into __Configuration > Integrations__ and you can set the options from above. Changes to `configu
```suggestion
The following settings in your `configuration.yaml` file are considered legacy. They will be imported into **Configuration** > **Integrations** and you can set the options from above. Changes to `configuration.yaml` after the first import will be ignored. 
```

2020-05-19 12:36 UTC, klaasnicolaas commented on source/_integrations/bmw_connected_drive.markdown
> +### Legacy configuration
```suggestion
### Legacy configuration

```

2020-06-01 16:35 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-09-02 18:00 UTC, rikroe commented
Had to close the original parent PR (#35732) due to completely failing at rebasing. The new parent PR is #39585.

2020-12-20 11:20 UTC, rikroe commented
Updated docs to comply with changes requested in home-assistant/core#39585.

2020-12-29 10:50 UTC, merged