Update opengarage.markdown, add config flow
home-assistant/home-assistant.github.io pull request #13562
Opened 2020-05-23 11:53 UTC by Danielhiversen

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/36032
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-05-23 20:03 UTC, klaasnicolaas requested changes
missing the `ha_config_flow: true` on top.

2020-05-23 20:03 UTC, klaasnicolaas commented on source/_integrations/opengarage.markdown
> +To add OpenGarage to your installation, go to Configuration >> Integrations in the UI and enable the Mill integration.
```suggestion
To add OpenGarage to your installation, go to **Configuration** >> **Integrations** in the UI and enable the Mill integration.
```

2020-05-28 11:14 UTC, klaasnicolaas approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

2020-06-10 16:09 UTC, caseyjhol commented on source/_integrations/opengarage.markdown
> +To add OpenGarage to your installation, go to **Configuration** >> **Integrations** in the UI and enable the Mill integration.
Shouldn't this be OpenGarage instead of Mill?

2020-08-08 10:40 UTC, frenck commented
Closing PR as the parent PR has been closed.

2020-08-08 10:40 UTC, closed without merging