Update influxdb.markdown with measurement_attr option
home-assistant/home-assistant.github.io pull request #13561
Opened 2020-05-23 09:46 UTC by markbergsma

Documentation for the new measurement_attr option.

## Proposed change

PR home-assistant/core#36020 introduces a new config option to select InfluxDB measurement names based on State object attributes.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#36020
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-05-23 20:05 UTC, klaasnicolaas requested changes

2020-05-23 20:05 UTC, klaasnicolaas commented on source/_integrations/influxdb.markdown
> +  description: State object attribute to use as measurement name. Possible values: `unit_of_measurement` (default), `domain`, `entity_id`
```suggestion
  description: "State object attribute to use as measurement name. Possible values: `unit_of_measurement`, `domain` or `entity_id`."
```

2020-06-01 15:10 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-10-20 22:12 UTC, frenck approved these changes

2020-10-20 22:12 UTC, merged