Add additional debug steps for HEOS System error -9 errors
home-assistant/home-assistant.github.io pull request #13573
Opened 2020-05-23 21:04 UTC by rroller

## Proposed change

Add additional debug steps for those who face the "System error -9" issue.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-05-23 21:04 UTC, rroller commented
@andrewsayre I've updated the HEOS docs. PTAL.

2020-05-26 17:02 UTC, andrewsayre requested changes
Thank you for updating the docs!  I left some comments that should make this more broadly applicable!

2020-05-26 17:02 UTC, andrewsayre commented on source/_integrations/heos.markdown
> +### System error -9 (12)
These troubleshooting steps aren't specific to `system error` but are actually general troubleshooting steps for any of the errors found in the [CLI documentation](http://rn.dmglobal.com/euheos/HEOS_CLI_ProtocolSpecification.pdf).  I would rename this section to "General troubleshooting steps"

2020-05-26 17:02 UTC, andrewsayre commented on source/_integrations/heos.markdown
> +```txt
Do not include log excerpts in the documentation, it's messy and unnecessary, instead, I think it would be better to list some of the error codes from the CLI specification that users may find in their logs in a list, i.e.:

> Follow the steps below if you see errors similar to the ones below in your log files:
>
>* Internal error (11)
>* System error _number_ (12), 
>* etc...

2020-05-26 17:02 UTC, andrewsayre commented on source/_integrations/heos.markdown
> +1. Log in your HEOS account through the device. If it's an AVR, login through the on-screen display in the AVR's setup menu.
We should update this to say they should re-authenticate (log out and then log in).  I didn't include this in your case because the logs indicated you were logged out, but this is an important step that fixes a lot of issues by simply re-authenticating.

2020-08-02 20:51 UTC, closed without merging