Add set_text service to Keba EV chargers
home-assistant/home-assistant.github.io pull request #13577
Opened 2020-05-24 12:23 UTC by matlimatli

## Proposed change

Add documentation for new service that adds the possibility to display text messages on the display of Keba EV chargers. 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [https://github.com/home-assistant/core/pull/36056](https://github.com/home-assistant/core/pull/36056)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-05-24 13:14 UTC, klaasnicolaas requested changes

2020-05-24 13:14 UTC, klaasnicolaas commented on source/_integrations/keba.markdown
> +The service `keba.set_text` shows the submitted text on the display of chargers with built-in LED display. `min_time` is the minimum time in seconds the text will be shown if another message is reque
```suggestion
The service `keba.set_text` shows the submitted text on the display of chargers with built-in LED display. `min_time` is the minimum time in seconds the text will be shown if another message is requested. `max_time` is the maximum time to display the message when nothing else is requested. A maximum of 23 characters can be shown. Horizontal scroll is performed autiomatically when needed. Payload example:

```

2020-05-28 08:34 UTC, frenck requested changes

2020-05-28 08:34 UTC, frenck commented on source/_integrations/keba.markdown
> +```
We use YAML in the frontend for this nowadays.
Please convert this example to YAML.

2020-05-28 08:34 UTC, frenck commented on source/_integrations/keba.markdown
> +The optional `data` part may contain specifications of the message duration. `min_time` is the minimum time in seconds the text will be shown if another message is requested. `max_time` is the maximu
```suggestion
The use of the notify service is [described here](/integrations/notify/).

The `message` part of the event payload is shown on the display. Scrolling is performed if needed. A maximum of 23 characters can be shown.

The optional `data` part may contain specifications of the message duration. `min_time` is the minimum time in seconds the text will be shown if another message is requested. `max_time` is the maximum time to display the message when nothing else is requested. By default, the message is shown a minimum of 2 seconds and a maximum of 10 seconds.
```

2020-05-28 08:34 UTC, frenck commented on source/_integrations/keba.markdown
> +- Services: authorize, deauthorize, set energy target, set maximum allowed current, show text and manually update the states. More details can be found [here](/integrations/keba/#services).
```suggestion
- Services: authorize, deauthorize, set energy target, set the maximum allowed current, show text and manually update the states. More details can be found [here](/integrations/keba/#services).
```

2020-05-28 22:44 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-06-03 17:43 UTC, merged