Gave an example for Nabu Casa because many of the examples given else…
home-assistant/home-assistant.github.io pull request #13628
Opened 2020-05-30 21:24 UTC by scstraus

…where on github issues are wrong.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-05-31 09:36 UTC, frenck requested changes
Thanks for the PR @scstraus!

Left a small comment, could you please take a look? Thanks! 👍

2020-05-31 09:36 UTC, frenck commented on source/_integrations/withings.markdown
> +- Callback Uri: `https://your-domain-name/auth/external/callback` - Withings will check if this URL is accessible (HTTP HEAD) upon submitting the form. If you are using a recent version of home assis
```suggestion
- Callback Uri: `https://your-domain-name/auth/external/callback` - Withings will check if this URL is accessible (HTTP HEAD) upon submitting the form. If you are using the Home Assistant Cloud, this URL will look like `https://YOUR_NABU_CASA_ID.ui.nabu.casa/auth/external/callback`.
```

2020-05-31 13:56 UTC, scstraus commented on source/_integrations/withings.markdown
> +- Callback Uri: `https://your-domain-name/auth/external/callback` - Withings will check if this URL is accessible (HTTP HEAD) upon submitting the form. If you are using a recent version of home assis
I’m okay with that.

2020-06-01 10:40 UTC, frenck approved these changes
Thanks, @scstraus 👍

2020-06-01 10:40 UTC, merged

2020-06-01 20:32 UTC, scstraus reviewed
Looks good.