ONVIF device triggers and line crossed event
home-assistant/home-assistant.github.io pull request #13660
Opened 2020-06-04 01:59 UTC by hunterjm

## Proposed change

This PR adds documentation for functionality implemented in https://github.com/home-assistant/core/pull/36428 regarding device triggers and line crossed event handling.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/36428
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-06-04 08:39 UTC, klaasnicolaas requested changes

2020-06-04 08:39 UTC, klaasnicolaas commented on source/_integrations/onvif.markdown
> +  Some ONVIF events are not able to be represented as Home Assistant entities. In those cases, "onvif_event" will be fired on the Home Assistant event bus. To determine what events are being fired, y
```suggestion
  Some ONVIF events are not able to be represented as Home Assistant entities. In those cases, "onvif_event" will be fired on the Home Assistant event bus. To determine what events are being fired, you can listen for `onvif_event` in **Developer Tools** -> **Events**. If you use the Automation UI, these events will show up as Device Triggers for you to select from.
```

2020-07-14 09:17 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-07-25 09:14 UTC, frenck commented
Closing the PR as the parent PR has been closed.

2020-07-25 09:14 UTC, closed without merging