Documentation update for PR #36518
home-assistant/home-assistant.github.io pull request #13733
Opened 2020-06-12 20:16 UTC by firstof9

## Proposed change

Add attribute_templates example and configuration scheme to documents.
Related to PR#36518

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/36518
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-06-12 20:29 UTC, klaasnicolaas requested changes

2020-06-12 20:29 UTC, klaasnicolaas commented on source/_integrations/vacuum.template.markdown
> +### Add Custom Attributes
```suggestion

### Add Custom Attributes
```

2020-06-12 20:29 UTC, klaasnicolaas commented on source/_integrations/vacuum.template.markdown
> +
```suggestion
```

2020-06-23 00:25 UTC, frenck approved these changes
Thanks, @firstof9 👍

2020-06-23 00:26 UTC, merged