Update aurora_abb_powerone documentation for config flow setup
home-assistant/home-assistant.github.io pull request #13748
Opened 2020-06-13 22:02 UTC by davet2001

## Proposed change
Update documentation to support describe config flow based setup.

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/36300
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-26 09:57 UTC, frenck commented on source/_integrations/aurora_abb_powerone.markdown
> +The RS485 connection can be made using a low cost USB-RS485 converter.  It works using a 2-wire interface but an interface with a separate ground reference may be more reliable.
```suggestion
The RS485 connection can be made using a low-cost USB-RS485 converter. It works using a 2-wire interface but an interface with a separate ground reference may be more reliable.
```

2021-10-26 09:58 UTC, frenck commented on source/_integrations/aurora_abb_powerone.markdown
> +Configuration via `configuration.yaml` is now deprecated but does still work.
```suggestion
Configuration should be done via the user interface. The inverter will need to be on (i.e. in daylight) and connected correctly in order to do the first-time setup. Normally it is sufficient to select the correct serial port and leave the default address `2`.

Configuration via `configuration.yaml` is now deprecated but does still work.
```

2021-10-26 20:48 UTC, frenck requested changes

2021-10-26 20:48 UTC, frenck commented on source/_integrations/aurora_abb_powerone.markdown
> +Configuration via `configuration.yaml` is now deprecated but does still work.
We don't document deprecated features. Please remove that section.

2021-10-26 21:23 UTC, davet2001 commented on source/_integrations/aurora_abb_powerone.markdown
> +Configuration via `configuration.yaml` is now deprecated but does still work.
Done.

2021-10-26 21:32 UTC, frenck commented on source/_integrations/aurora_abb_powerone.markdown
> +Configuration should be done via the user interface. The inverter will need to be on (i.e. in daylight) and connected correctly in order to do the first-time setup. Normally it is sufficient to selec
This can be replaced by:

```
## Configuration

Configuration should be done via the user interface. The inverter will need to be on (i.e. in daylight) and connected correctly in order to do the first-time setup. Normally it is sufficient to select the correct serial port and leave the default address `2`.
```

```
{% include integrations/config_flow.md %}

The inverter will need to be on (i.e. in daylight) and connected correctly in order to do the first-time setup. Normally it is sufficient to select the correct serial port and leave the default address `2`.
```

2021-10-26 22:34 UTC, davet2001 commented on source/_integrations/aurora_abb_powerone.markdown
> +Configuration should be done via the user interface. The inverter will need to be on (i.e. in daylight) and connected correctly in order to do the first-time setup. Normally it is sufficient to selec
Awesome! I did not know this type of include was possible/available.  Thanks! Done.

2021-10-27 07:32 UTC, frenck approved these changes
Thanks, @davet2001 👍

2021-10-27 07:33 UTC, merged