Update sonarr.markdown
home-assistant/home-assistant.github.io pull request #13847
Opened 2020-06-25 14:31 UTC by jwildman16

Added information on how to configure the integration. I don't understand how to properly format the text, so additional changes may be needed.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-07-13 17:22 UTC, frenck requested changes
This will not render as you think it does:

![image](https://user-images.githubusercontent.com/195327/87333928-28b7cd80-c53e-11ea-86b1-dcf10f063b0f.png)

Could you please adjust? Please note, we are using Markdown here not normal text files.

2020-07-13 17:39 UTC, jwildman16 commented
I'm up for it, but I'd need a little guidance. It's outside of my current skill set. If you have a self-guided learning resource to recommend, I'm happy to check it out and revise my entry. Thanks.

2020-07-21 14:22 UTC, zsarnett commented on source/_integrations/sonarr.markdown
> +Go to the Configuration > Integrations page and click on the plus '+' to add a new integration. Select Sonarr. Enter your Sonarr connection information and click Submit.
We can now use a new plugin called `configuration_basic` 

Checkout the documentation for the Lovelace Weather card on how to use this plugin

Something along the lines of this
```markdown
{% configuration_basic %}

(Here you will place your variables

{% endconfiguration_basic %}
```

2020-09-05 14:21 UTC, frenck commented
This PR is running stale, closing it for now. Feel free to re-open when ready to work on it again.

2020-09-05 14:21 UTC, closed without merging