Document MQTT availability list
home-assistant/home-assistant.github.io pull request #13929
Opened 2020-07-06 15:41 UTC by emontnemery

## Proposed change

Document MQTT availability list

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/37418

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-07-06 16:06 UTC, klaasnicolaas requested changes

2020-07-06 16:06 UTC, klaasnicolaas commented on source/_integrations/camera.mqtt.markdown
> +  description: An MQTT topic subscribed to receive availability (online/offline) updates.
```suggestion
  description: An MQTT topic subscribed to receive availability (online/offline) updates.
```
This rule has a wrong indent 😉 And is in all files

2020-07-07 10:40 UTC, emontnemery commented
@klaasnicolaas I fixed the indent, but I'm not sure what's causing the build errors?

2020-07-14 01:16 UTC, balloob submitted a review, later dismissed

2020-07-14 17:47 UTC, frenck approved these changes

2020-07-14 18:33 UTC, merged