Add ozw.set_config_parameter command to documentation.
home-assistant/home-assistant.github.io pull request #13949
Opened 2020-07-08 14:54 UTC by firstof9

## Proposed change

Add set_config_parameter command to documentation.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/37523
- Link to parent pull request in the Brands repository: n/a
- This PR fixes or closes issue: n/a

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-07-08 16:19 UTC, klaasnicolaas requested changes

2020-07-08 16:19 UTC, klaasnicolaas commented on source/_integrations/ozw.markdown
> +| `node_id`              | yes      | Node id of the device to set config parameter to (integer).                                                     |
```suggestion
| `node_id`              | yes      | Node id of the device to set configuration parameter to (integer).                                                     |
```

2020-07-08 17:13 UTC, firstof9 commented
All fixed, thanks.

2020-07-14 19:06 UTC, frenck commented
Replaced by #13998, as this PR has the fork removed.

2020-07-14 19:06 UTC, closed without merging