Proxy support for rest sensor #36932
home-assistant/home-assistant.github.io pull request #13966
Opened 2020-07-10 13:22 UTC by zvldz

Proxy support for rest sensor #36932(https://github.com/home-assistant/core/pull/36932/)

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-07-10 14:47 UTC, klaasnicolaas requested changes

2020-07-10 14:47 UTC, klaasnicolaas commented on source/_integrations/rest.markdown
> +  description: The URL to the proxy server. For example: http://127.0.0.1:3128,socks5://user:password@127.0.0.1:9050
```suggestion
  description: "The URL to the proxy server. For example: http://127.0.0.1:3128,socks5://user:password@127.0.0.1:9050"
```

2020-07-14 09:55 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-10-20 20:56 UTC, frenck commented
Closing this PR as the parent PR has been closed.

2020-10-20 20:56 UTC, closed without merging