Add documentation for the Bright Sky weather entity
home-assistant/home-assistant.github.io pull request #13987
Opened 2020-07-13 01:16 UTC by mweinelt

## Proposed change

Add documentation for the bright sky weather entity.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/37800
- Link to parent pull request in the Brands repository: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-07-13 06:04 UTC, Mic92 commented on source/_integrations/weather.brightsky.markdown
> +The `brightsky` platform uses the [Bright Sky](https://darksky.net/) JSON API to query meteorological provided by the Deutsche Wetterdienst (DWD)
Wrong url?

```suggestion
The `brightsky` platform uses the [Bright Sky](https://brightsky.dev) JSON API to query meteorological provided by the Deutsche Wetterdienst (DWD)
```

2020-07-13 13:58 UTC, klaasnicolaas requested changes
Please rename the file from `weather.brightsky.markdown` to `brightsky.markdown`

2020-07-13 13:58 UTC, klaasnicolaas commented on source/_integrations/weather.brightsky.markdown
> +logo: dwd.png
Please add the logo to our [Brands repository](https://github.com/home-assistant/brands)

2020-07-13 18:04 UTC, frenck requested changes

2020-07-13 18:04 UTC, frenck commented on source/_integrations/brightsky.markdown
> +  - platform: brightsky
We no longer accept platform integrations. Furthermore, integrations that are connecting to a device or service need to have a config flow in the UI.

2021-03-29 11:01 UTC, frenck commented
Closing PR as the parent PR has been closed by the contributor.

2021-03-29 11:01 UTC, closed without merging