Add room integration
home-assistant/home-assistant.github.io pull request #14131
Opened 2020-08-01 17:56 UTC by pavoni

## Proposed change

Add documentation for the new Roon Labs media player integration,

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
https://github.com/home-assistant/core/pull/37553

- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-08-03 12:20 UTC, frenck requested changes

2020-08-03 12:20 UTC, frenck commented on source/_integrations/roon.markdown
> +</div>
Do we really need 2 note blocks? I think this can just be part of the normal text.

2020-08-09 13:17 UTC, pavoni commented
@frenck Just wanted to check I've updated this correctly (the integration is ready to merge - so hoping it will make it to 0.115)

2020-08-09 15:14 UTC, klaasnicolaas requested changes

2020-08-09 15:14 UTC, klaasnicolaas commented on source/_integrations/roon.markdown
> +1. From the Home Assistant front-end, navigate to 'Configuration' then 'Integrations'. Under 'Set up a new integration' locate 'Roon' and click 'Configure'.
```suggestion
1. From the Home Assistant front-end, navigate to **Configuration** then **Integrations**. Under **Set up a new integration** locate 'Roon' and click **Configure**.
```

2020-08-09 15:14 UTC, klaasnicolaas commented on source/_integrations/roon.markdown
> +ha_release: 0.114
```suggestion
ha_release: 0.115
```

2020-08-09 15:14 UTC, klaasnicolaas commented on source/_integrations/roon.markdown
> +2. Enter the Hostname or IP address for the Roon Core machine and click 'Submit'.
```suggestion
2. Enter the `Hostname` or `IP address` for the Roon Core machine and click **Submit**.
```

2020-08-09 15:14 UTC, klaasnicolaas commented on source/_integrations/roon.markdown
> +3. Home Assistant will then contact your Roon Core and ask to be authorized. You will need to enable this extension in the Room Application. Go to 'Settings' and then 'Extensions', there you will see
```suggestion
3. Home Assistant will then contact your Roon Core and ask to be authorized. You will need to enable this extension in the Room Application. Go to **Settings** and then **Extensions**, there you will see an entry for Home Assistant with a button next to it. Click **Enable**.
```

2020-08-09 15:30 UTC, pavoni commented
Thanks @klaasnicolaas

2020-08-09 15:39 UTC, klaasnicolaas submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged 👍
⚠️ The ha_release might need an update before merging this one in. (maybe not 😄 )

2020-08-13 11:56 UTC, frenck approved these changes

2020-08-13 11:58 UTC, merged