Add some additional help on google assistant trouble shooting
home-assistant/home-assistant.github.io pull request #14156
Opened 2020-08-04 16:43 UTC by elupus

## Proposed change

Add some additional trouble shooting information for google assistant.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-08-04 17:46 UTC, frenck requested changes

2020-08-04 17:46 UTC, frenck commented on source/_integrations/google_assistant.markdown
> +The `request_sync` service may fail with a 403 if the if the HomeGraph API is not enabled. Go to [Google API Console](https://console.cloud.google.com/apis/api/homegraph.googleapis.com/overview) and
```suggestion
The `request_sync` service may fail with a 403 if the HomeGraph API is not enabled. Go to [Google API Console](https://console.cloud.google.com/apis/api/homegraph.googleapis.com/overview) and verify that HomeGraph API is enabled for your project.
```

2020-08-04 17:46 UTC, frenck commented on source/_integrations/google_assistant.markdown
> +
```suggestion
If you receive 404 errors linked to reporting state in your log, Home Assistant is reporting state for entities that were never synced to google. Ask your Google Home to `Sync my devices` or run the service `google_assistant.request_sync`.
```

2020-08-04 17:46 UTC, frenck commented on source/_integrations/google_assistant.markdown
> +Your fullfillment url may be invalid or unreachable. Recheck the `Fulfillment URL` as specified in [Manual Setup](#manual-setup) and verify that it's publically reachable.
```suggestion
Your fulfillment URL may be invalid or unreachable. Recheck the `Fulfillment URL` as specified in [Manual Setup](#manual-setup) and verify that it's publically reachable.
```

2020-08-05 09:14 UTC, elupus commented
Christ, i'm spelling like a... Thank you for to corrections.

2020-08-05 09:35 UTC, frenck approved these changes
Thanks, @elupus 👍

2020-08-05 09:35 UTC, merged