Remove Linky integration
home-assistant/home-assistant.github.io pull request #14168
Opened 2020-08-05 17:50 UTC by Quentame

## Proposed change

Linked to parent PR : home-assistant/core#38565

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-08-05 17:51 UTC, Quentame commented
As 'current' branch just got merged into the 'next' branch, I'm not sure if my choice is good.

2020-08-06 09:37 UTC, frenck requested changes
This is not cleaning up all link references across the site.
Please clean up all blog articles linking to this page, to prevent broken links on our website.

I've actually done it, but could not push onto this branch (because that was explicitly disabled by you).

2020-08-07 11:12 UTC, Quentame commented
Cleaned all references.

First integration removal, so didn't know sorry.

My branch is on a fork, that's why.

2020-08-08 12:45 UTC, frenck commented
@Quentame A fork is normally writable for members upstream, unless specifically disabled by the owner of the fork.

2020-08-08 12:45 UTC, frenck requested changes

2020-08-08 12:45 UTC, frenck commented on source/_posts/2018-10-01-release-79.markdown
> -- Add linky sensor ([@tiste] - [#16468]) ([sensor.linky docs]) (new-platform)
Don't remove those, as they are still valid. Just remove the links to the documentation.

Same applies to all other changes.

2020-08-11 09:39 UTC, frenck approved these changes
Thanks, @Quentame 👍

2020-08-11 09:39 UTC, merged