Added a more basic example as the template ones are tough to use as s…
home-assistant/home-assistant.github.io pull request #14223
Opened 2020-08-10 19:33 UTC by scstraus

…tarting points

This is a real one from my config which I think will be easier for beginners.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-08-10 20:32 UTC, frenck requested changes
Thanks for the PR @scstraus!

Left some small comments, could you take a look? Thanks 👍

2020-08-10 20:32 UTC, frenck commented on source/_integrations/rest_command.markdown
> +This example implements 2 rest commands to add service calls the missing shuffle functionality from the iTunes integration with a REST command.
```suggestion
This example implements 2 REST commands to add service calls for the missing shuffle functionality of the iTunes integration.
```

2020-08-10 20:32 UTC, frenck commented on source/_integrations/rest_command.markdown
> +    url: "http://[YOUR_ITUNES-API_SERVER_IP]:8181/shuffle"
```suggestion
    url: "http://YOUR_ITUNES-API_SERVER_IP:8181/shuffle"
```

2020-08-10 20:32 UTC, frenck commented on source/_integrations/rest_command.markdown
> +    url: "http://[YOUR_ITUNES-API_SERVER_IP]:8181/shuffle"
```suggestion
    url: "http://YOUR_ITUNES-API_SERVER_IP:8181/shuffle"
```

2020-08-10 20:32 UTC, frenck commented on source/_integrations/rest_command.markdown
> +In this example entry, you can see some simple [templates](/docs/configuration/templating/) in use for dynamic parameters.
```suggestion
In this example, uses [templates](/docs/configuration/templating/) for dynamic parameters.
```

2020-08-11 09:08 UTC, scstraus commented
All agreed. Thanks!

2020-08-11 09:32 UTC, frenck commented
@scstraus I see you've resolved the comments, but I don't see a commit? Did you forget to push the commit?

2020-08-11 20:27 UTC, scstraus commented
Sorry, I suck at Git. Are we good?

2020-08-13 10:12 UTC, frenck approved these changes
Thanks, @scstraus 👍

2020-08-13 10:13 UTC, merged