Add documentation for new protocol flag for qvrpro
home-assistant/home-assistant.github.io pull request #14260
Opened 2020-08-16 23:39 UTC by woneill

## Proposed change

Support using https for qvrpro integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/38951

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-08-17 17:22 UTC, klaasnicolaas requested changes

2020-08-17 17:22 UTC, klaasnicolaas commented on source/_integrations/qvr_pro.markdown
> +  default: "`http`"
```suggestion
  default: "http"
```

2020-08-29 18:29 UTC, frenck commented
While the parent is merged, the parent PR conflicts with ADR-0010. A PR has been opened to revert the parent PR:

https://github.com/home-assistant/core/pull/39385

2020-08-30 12:53 UTC, frenck commented
Closing this PR as the parent PR has been reverted and need a different implementation than documented in this PR.

2020-08-30 12:53 UTC, closed without merging