Update locked_out.md
home-assistant/home-assistant.github.io pull request #14277
Opened 2020-08-20 08:37 UTC by fquinto

According this https://community.home-assistant.io/t/resetting-password-cannot-complete-the-onboarding-process-name-is-already-in-use-in-logs/152826 sometimes you need to delete core.area_registry file

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-08-21 10:59 UTC, frenck requested changes
This will actually cause more problems in that case, as removing that file will get you ending up with devices that are tied to an area that don't exist anymore.

So, this file really should not be removed.

2020-08-21 11:42 UTC, fquinto commented
Ok, maybe this information is useful and welcome in documentation.

@frenck Nice to say "Hello" to you! Good job in HA community!!

2020-08-21 13:40 UTC, frenck commented
> Ok, maybe this information is useful and welcome in documentation.

How? By telling this file should be removed? Removing that file causes issues as well.

> Nice to say "Hello" to you! Good job in HA community!!

👋

2020-08-21 16:33 UTC, fquinto commented
Sorry, maybe I explain me bad. When I say "this information", is "your" information. And finally, is good to know and write a note. Something like:

In some cases you need to consider this file: `core.area_registry` (editing?) but you need to take care because removing that file will get you ending up with devices that are tied to an area that don't exist anymore.

Finally maybe is better to not apply this PR. Up to your consideration.

2020-09-05 14:23 UTC, frenck commented
ok, checked a bit more, this file may cause issue, but that is more a bug? Removing this file suggested is absolutely a bad idea, so lets not add it to the documentation.

2020-09-05 14:23 UTC, closed without merging