Add SQLite db size example (fixes #13715)
home-assistant/home-assistant.github.io pull request #14295
Opened 2020-08-22 12:59 UTC by fabaff

## Proposed change

Add SQLite db size example.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- This PR fixes or closes issue: #13715

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-08-22 16:49 UTC, frenck requested changes

2020-08-22 16:49 UTC, frenck commented on source/_integrations/sql.markdown
> +        unit_of_measurement: 'MiB'
Code fence isn't closed.

2020-08-22 21:04 UTC, fabaff commented on source/_integrations/sql.markdown
> +        unit_of_measurement: 'MiB'
Thanks. Fixed

2020-08-23 09:23 UTC, frenck approved these changes

2020-08-23 09:23 UTC, merged