Add information on manual update of deCONZ
home-assistant/home-assistant.github.io pull request #14309
Opened 2020-08-24 21:58 UTC by darendark

The administrators of deCONZ informed me that updating manually is preferred over updating through a docker container, such as the Home Assistant addon. Updating through the Phoscon app leads to connectivity issues.

Link to message in Discord: https://discordapp.com/channels/494922323518947329/692306044495593544/747463334571278377

## Proposed change

The administrators of deCONZ informed me that updating manually is preferred over updating through a docker container, such as the Home Assistant addon. Updating through the Phoscon app leads to connectivity issues. Those who don't know any better may try to update through the add on and be left with a Zigbee network that is no longer functioning.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-08-24 22:01 UTC, darendark commented
If I would like to make further changes to the deCONZ page, is it better to split them up into sections and submit multiple pull requests, or one large one?

2020-08-25 04:12 UTC, frenck requested changes

2020-08-25 04:12 UTC, frenck commented on source/_integrations/deconz.markdown
> +If you are having issues and want to report a problem, always start with making sure that you're on the latest [deCONZ software version](https://github.com/dresden-elektronik/deconz-rest-plugin/relea
This is a bug and should be reported, not worked around in documentation.

Furthermore, manual updating is already documented in the add-on. I don't think it belongs in the integration documentation.

2020-09-05 12:27 UTC, frenck commented
Closing this PR as there is no response from the author and the given reasoning.

2020-09-05 12:27 UTC, closed without merging