Added documentation for the new met_eireann integration
home-assistant/home-assistant.github.io pull request #14347
Opened 2020-08-30 14:49 UTC by DylanGore

## Proposed change

Adds documentation for the new Met Éireann weather integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [https://github.com/home-assistant/core/pull/39429](https://github.com/home-assistant/core/pull/39429)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-08-30 17:47 UTC, klaasnicolaas requested changes

2020-08-30 17:47 UTC, klaasnicolaas commented on source/_integrations/met_eireann.markdown
> +To add a Met Éireann weather source, go to __Configuration >> Integrations__ in the UI and create a new Met Éireann entry. You can specify a custom latitude, longitude and elevation if required, if n
```suggestion
To add a Met Éireann weather source, go to **Configuration** -> **Integrations** in the UI and create a new Met Éireann entry. You can specify a custom latitude, longitude and elevation if required, if not speciefied the Home Assistant defaults will be used.
```

2021-04-25 11:18 UTC, frenck commented on source/_integrations/met_eireann.markdown
> +To add a Met Éireann weather source, go to **Configuration** -> **Integrations** in the UI and create a new Met Éireann entry. You can specify a custom latitude, longitude and elevation if required,
```suggestion
{% include integrations/config_flow.md %}
```

2021-04-25 11:18 UTC, frenck commented on source/_integrations/met_eireann.markdown
> +The data provied by Met Éireann is licensed under the Met Éireann Open Data Custom License (similar to a Creative Commons CC BY 4.0 licence). A license summary and the full license are available [her
```suggestion
The data provided by Met Éireann is licensed under the Met Éireann Open Data Custom License (similar to a Creative Commons CC BY 4.0 license). A license summary and the full license are available [here](https://data.gov.ie/dataset/met-eireann-weather-forecast-api/resource/027da6d5-d819-48d1-9b16-331dba169bd1). In short, if you distribute, broadcast or make Met Éireann data available on the public internet you must give credit to Met Éireann and display their weather warnings.
```

2021-04-25 11:18 UTC, frenck commented on source/_integrations/met_eireann.markdown
> +The `met_eireann` platform uses the [Met Éireann](https://met.ie) (The Irish Meteorological Service) Public Weather Forecast API to provide current and forecasted weather data for a given location. T
```suggestion
The Met Éireann integration uses the [Met Éireann](https://met.ie) (The Irish Meteorological Service) Public Weather Forecast API to provide current and forecasted weather data for a given location. This integration is in no way affiliated with or endorsed by Met Éireann.
```

2021-04-25 11:24 UTC, merged

2021-04-25 11:25 UTC, frenck commented
Thanks, @DylanGore 👍