Honeywell Lyric Integration
home-assistant/home-assistant.github.io pull request #14409
Opened 2020-09-05 22:17 UTC by timmo001

## Proposed change

Docs for the new integration

## Type of change

- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - ~~I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).~~ _Already exists from custom integration_

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/39695

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-09-05 22:23 UTC, timmo001 commented
Oops. Thanks bot!

2020-09-07 07:02 UTC, frenck requested changes
Thanks for the PR @timmo001!

Some small comments, could you take a look?

2020-09-07 07:02 UTC, frenck commented on source/_integrations/lyric.markdown
> +  client_secret: myconsumersecret
```suggestion
  client_id: MY_CONSUMER_KEY
  client_secret: MY_CONSUMER_SECRET
```

2020-09-07 07:02 UTC, frenck commented on source/_integrations/lyric.markdown
> +Login with your Honeywell Lyric account and agree to the terms. The Honeywell Lyric integration will then be available.
```suggestion
Log in with your Honeywell Lyric account and agree to the terms. The Honeywell Lyric integration will then be available.
```

2020-09-07 07:03 UTC, frenck commented
Oh, additionally, this might need a PR in our brands repository?

2020-09-07 20:00 UTC, timmo001 commented
> Oh, additionally, this might need a PR in our brand repository? As we should not rely on custom integration assets. So they need to be moved.

Looks like it already exists under core https://github.com/timmo001/brands/tree/master/core_integrations/honeywell

2020-09-08 07:08 UTC, frenck commented
`honeywell` is a different integration, the domain key for this integration is `lyric` right?

![image](https://user-images.githubusercontent.com/195327/92444174-caf8d800-f1b2-11ea-923a-02d78ab5f7c7.png)


Doesn't exist...

2020-09-08 12:27 UTC, timmo001 commented
> `honeywell` is a different integration, the domain key for this integration is `lyric` right?
> 
> ![image](https://user-images.githubusercontent.com/195327/92444174-caf8d800-f1b2-11ea-923a-02d78ab5f7c7.png)
> 
> 
> Doesn't exist...

Hmm strange how it shows up in the integrations in the frontend then.. 

Is it because it still has the word Honeywell in the title it still recognises it somehow?

2020-09-13 16:36 UTC, jasondefuria commented
Look at the Lyric in Custom_Components and those files can be moved over.

2021-01-31 18:55 UTC, bdraco approved these changes, later dismissed
LGTM 

https://deploy-preview-14409--home-assistant-docs.netlify.app/integrations/lyric/

Please address any additional comments that may come in after merge in a new PR.

2021-01-31 18:56 UTC, bdraco commented
Actually Frenck's review is still fresh so this will need to wait for him to take a look over.

2021-01-31 23:02 UTC, frenck commented
Fresh! Like today's salad! But I'll take a look tomorrow when cleaning things up in the morning 👍

2021-01-31 23:08 UTC, frenck commented on source/_integrations/lyric.markdown
> +   1. Callback URL: This needs to be the base URL of your Home Assistant instance + `/auth/external/callback`. For example: `http://192.168.1.123:8123/auth/external/callback`.
A small tweak, as the base URL doesn't matter anymore for OAuth 👍 

```suggestion
   1. Callback URL: This needs to be the URL of your Home Assistant instance + `/auth/external/callback`. For example: `http://192.168.1.123:8123/auth/external/callback`.
```

2021-01-31 23:09 UTC, frenck approved these changes

2021-01-31 23:11 UTC, merged