Add plugwise port configuration
home-assistant/home-assistant.github.io pull request #14488
Opened 2020-09-13 09:25 UTC by CoMPaTech

## Proposed change
Adding line indicating port number can be used for advanced users having different port numbers

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-09-13 09:29 UTC, CoMPaTech commented
Not sure why probot designates this as as current

2020-09-13 09:37 UTC, ludeeus commented
When it was opened it was missing the link to the core PR

2020-09-13 09:41 UTC, CoMPaTech commented
> When it was opened it was missing the link to the core PR

I'll open the core one first next time, apologies!

2020-09-13 11:25 UTC, bouwew approved these changes, later dismissed
More clear after rewording, tnx!

2020-09-14 06:15 UTC, frenck requested changes

2020-09-14 06:15 UTC, frenck commented on source/_integrations/plugwise.markdown
> +If you have a Smile that is connected, for example, using a (remote) port-forwarding device and has a port other than `80` (HTTP) by default: you can add the port number when configuring it manually.
```suggestion
If you have a Smile that is connected, for example, using a (remote) port-forwarding device and has a port other than `80` (HTTP) by default: you can add the port number when configuring it manually. E.g., `192.168.1.2:81`.
```

2020-09-14 09:46 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-09-17 15:05 UTC, CoMPaTech commented
Closing this as the approach changed, will merge the supported firmware versions with #14508

2020-09-17 15:05 UTC, closed without merging