server_host - more details
home-assistant/home-assistant.github.io pull request #14571
Opened 2020-09-20 00:10 UTC by bbrendon

I'm not sure how to properly display the default for multiple list items. I couldn't find any examples to work from.

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue:  https://github.com/home-assistant/home-assistant.io/issues/14531

## Checklist

- [x ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ?] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-09-23 09:34 UTC, frenck commented on source/_integrations/http.markdown
> +  description: "Only listen to incoming requests on specific IP/host. By default the `http` integration auto-detects IPv4/IPv6 and listens on all connections. Use `server_host: 0.0.0.0` if you want t
This is incorrect, the default is autodetect.

2020-09-23 09:34 UTC, frenck requested changes
Small comment and please ensure the build passes.
Thanks 👍

2020-09-25 23:35 UTC, bbrendon commented
Sorry, I'm lost as to what the issue is. Line 6 ? I thought for sure line 39 was going to be the problem.

Line 6 wasn't changed. The error ....

  Liquid Exception: (<unknown>): mapping values are not allowed in this context at line 6 column 22 in /home/runner/work/home-assistant.io/home-assistant.io/source/_integrations/http.markdown

2020-09-29 15:02 UTC, frenck commented on source/_integrations/http.markdown
> +  default: 0.0.0.0, ::
```suggestion
  default: "0.0.0.0, ::"
```

2020-09-29 15:14 UTC, frenck approved these changes
Thanks, @bbrendon 👍

2020-09-29 15:15 UTC, merged