Update document to match proposed update to component
home-assistant/home-assistant.github.io pull request #14692
Opened 2020-10-01 14:45 UTC by derekatkins

## Proposed change

This change is coinciding with a PR on the manual_mqtt component.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#40973
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-10-01 15:25 UTC, klaasnicolaas requested changes

2020-10-01 15:25 UTC, klaasnicolaas commented on source/_integrations/manual_mqtt.markdown
> +  type: JSON map
```suggestion
  type: string
```

2020-10-01 15:25 UTC, klaasnicolaas commented on source/_integrations/manual_mqtt.markdown
> +  type: JSON map
```suggestion
  type: string
```

2020-10-01 15:32 UTC, derekatkins commented on source/_integrations/manual_mqtt.markdown
> +  type: JSON map
Thanks

2020-10-01 15:33 UTC, derekatkins commented on source/_integrations/manual_mqtt.markdown
> +  type: JSON map
Thanks

2020-10-02 13:31 UTC, thanksmister approved these changes, later dismissed
Good documentation update, easy to read and understand.

2020-10-02 13:31 UTC, thanksmister commented on source/_integrations/manual_mqtt.markdown
> +title: Manual MQTT Alarm
Yes, name change desperately needed, thanks!

2020-10-02 15:36 UTC, thanksmister approved these changes
Format and description for pending look good.

2020-10-05 13:58 UTC, derekatkins commented
@klaasnicolaas I believe that I have resolved all your requested changes.  Can you please verify?
Thanks!

2020-10-09 16:05 UTC, derekatkins commented on source/_integrations/manual_mqtt.markdown
> +  type: JSON map
I committed this change.  Thanks.

2020-10-09 16:05 UTC, derekatkins commented on source/_integrations/manual_mqtt.markdown
> +  type: JSON map
I committed this change.  Thanks.

2020-10-09 16:19 UTC, thanksmister approved these changes

2021-03-04 07:57 UTC, frenck commented
Closing PR as the parent PR has been closed.

2021-03-04 07:57 UTC, closed without merging