Grammar, spelling and styling edits
home-assistant/home-assistant.github.io pull request #14741
Opened 2020-10-02 02:51 UTC by ab3lson

## Proposed change
There were a few grammatical errors that were fixed. Capitalization of `Plex` was made uniform and other small styling tweaks were made.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-10-02 11:01 UTC, frenck requested changes
Thanks for the PR, @ab3lson!

I've left some comments, could you please take a look?

Thanks! 👍

2020-10-02 11:01 UTC, frenck commented on source/_integrations/plex.markdown
> +To play `Plex` music directly to Sonos speakers, the following requirements must be met:
We don't codefence brand names

2020-10-02 11:01 UTC, frenck commented on source/_integrations/plex.markdown
> +4. [Sonos](/integrations/sonos/) integration configured
Sentences have to have a full stop. Please restore the closing punctuation.

2020-10-02 11:01 UTC, frenck commented on source/_integrations/plex.markdown
> +* The `Plex` integration supports multiple Plex servers. Additional connections can be configured under **Configuration** > **Integrations**.
```suggestion
* The Plex integration supports multiple Plex servers. Additional connections can be configured under **Configuration** > **Integrations**.
```

2020-10-02 11:01 UTC, frenck commented on source/_integrations/plex.markdown
> +* Movies must be located under the 'Movies' section in a `Plex` library to properly view the 'playing' state.
```suggestion
* Movies must be located under the 'Movies' section in a Plex library to properly view the 'playing' state.
```

2020-10-02 11:01 UTC, frenck commented on source/_integrations/plex.markdown
> +By default the `Plex` integration will create Media Player entities for all local, managed, and shared users on the Plex server. To customize which users or client types to monitor, adjust the "*Moni
```suggestion
By default, the Plex integration will create Media Player entities for all local, managed, and shared users on the Plex server. To customize which users or client types to monitor, adjust the "*Monitored users*", "*Ignore new managed/shared users*", and "*Ignore Plex Web clients*" options described under [Integration Options](#integration-options).
```

2020-10-02 11:01 UTC, frenck commented on source/_integrations/plex.markdown
> +### Automatic Configuration
```suggestion
### Configuration
```

2020-10-02 11:01 UTC, frenck commented on source/_integrations/plex.markdown
> +The `Plex` integration allows you to connect Home Assistant to a [Plex Media Server](https://plex.tv). Once configured, actively streaming [Plex Clients](https://www.plex.tv/apps-devices/) show up as
```suggestion
The Plex integration allows you to connect Home Assistant to a [Plex Media Server](https://plex.tv). Once configured, actively streaming [Plex Clients](https://www.plex.tv/apps-devices/) show up as [Media Players](/integrations/media_player/) and report playback status via a [Sensor](/integrations/sensor/) in Home Assistant. Media Players will allow you to control media playback and see the current playing item.
```

The latter media player, refers to the platform, not Plex.

2020-10-02 23:41 UTC, ab3lson commented on source/_integrations/plex.markdown
> +4. [Sonos](/integrations/sonos/) integration configured
Revised

2020-10-03 06:58 UTC, frenck approved these changes
Thanks, @ab3lson 👍 

Happy Hacktoberfest 🎉

2020-10-03 07:47 UTC, merged