Document casting Plex to Chromecast
home-assistant/home-assistant.github.io pull request #15264
Opened 2020-10-16 03:28 UTC by jjlawren

## Proposed change

Document how to cast Plex media to Chromecast devices.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/41869
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-10-16 13:44 UTC, jjlawren commented on source/_integrations/cast.markdown
> +### [Plex](https://www.home-assistant.io/integrations/plex/)
Having a link as the title seems to break the anchor link generation.
```suggestion
### Plex
```

2020-10-16 19:51 UTC, frenck requested changes

2020-10-16 19:51 UTC, frenck commented on source/_integrations/cast.markdown
> +To cast media directly from a configured Plex server, set the fields [as documented in the Plex integration](https://www.home-assistant.io/integrations/plex/#service-play_media) and prepend the `medi
```suggestion
To cast media directly from a configured Plex server, set the fields [as documented in the Plex integration](/integrations/plex/#service-play_media) and prepend the `media_content_id` with `plex://`:

```

2020-10-20 23:48 UTC, frenck approved these changes
Thanks, @jjlawren 👍

2020-10-20 23:48 UTC, merged