Update xknx to 0.15.2
home-assistant/home-assistant.github.io pull request #15301
Opened 2020-10-18 10:56 UTC by marvin-w

## Proposed change

Documentation update for underlying library change. See core PR for more details.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/42026
- Link to parent pull request in the Brands repository: -
- This PR fixes or closes issue: -

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-10-19 09:06 UTC, farmio approved these changes, later dismissed

2020-10-19 09:06 UTC, farmio commented on source/_integrations/knx.markdown
> +  description: Defines if each update of the internal state should trigger a callback within Home Assistant no matter if the payload is equal.
```suggestion
  description: Defines if telegrams with equal payload as the previously received telegram should trigger a state update within Home Assistant.
```

2020-10-19 09:06 UTC, farmio commented on source/_integrations/knx.markdown
> +  description: Specifies if state updates should ignore the internal state and always trigger the Home Assistant callback.
```suggestion
  description: Specifies if telegrams should ignore the internal state and always trigger a Home Assistant state update.
```

2020-10-19 15:24 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-11-06 21:10 UTC, farmio requested changes

2020-11-06 21:10 UTC, farmio commented on source/_integrations/knx.markdown
> +  required: true
```suggestion
  required: false
```
ignore_internal_state is optional

2020-11-06 21:10 UTC, farmio commented on source/_integrations/knx.markdown
> +  type: boolean
```suggestion
  required: false
  type: boolean
```
required key missing

2020-11-06 21:13 UTC, farmio approved these changes
👍

2020-11-06 21:26 UTC, farmio requested changes
add documentation for invert from 0.15.3

2020-11-06 21:26 UTC, farmio commented on source/_integrations/knx.markdown
> +  type: float
```suggestion
  type: float
invert:
  description: Invert the telegrams payload before processing. This is applied before `context_timeout` or `reset_after` is evaluated.
  required: false
  type: boolean
  default: False
```

2020-11-06 21:26 UTC, farmio commented on source/_integrations/knx.markdown
> +reset_after:
```suggestion
invert:
  description: Invert the telegrams payload before processing or sending. This is applied before `reset_after` is evaluated so the reset will send "1" to the bus.
  required: false
  type: boolean
  default: False
reset_after:
```

2020-11-06 21:29 UTC, farmio requested changes

2020-11-06 21:29 UTC, farmio commented on source/_integrations/knx.markdown
>    description: The time in seconds between multiple identical telegram payloads would count towards the internal counter that is used for automations. Ex. You have automations in place that trigger y
```suggestion
  default: False
context_timeout:
  description: The time in seconds between multiple identical telegram payloads would count towards the internal counter that is used for automations. Ex. You have automations in place that trigger your lights on button press and another set of lights if you click that button twice. This setting defines the time that a second button press would count toward, so if you set this 3.0 you can take up to 3 seconds in order to trigger the second button press. If set `ignore_internal_state` will be set to `True` internally. Maximum value is 10.0.
```

2020-11-06 21:33 UTC, farmio submitted a review, later dismissed
👍 now for real 🤣

2020-11-19 06:43 UTC, a005 commented
This PR should be merged for 0.118 release! It describes breaking change.

2020-11-19 06:53 UTC, frenck commented
This PR is missed when creating the 0.118 release. Changed the target branch of this PR to `current` so it ends up in the current documentation of 0.118.

2020-11-19 06:54 UTC, frenck approved these changes
Looks good! Thanks! 👍

2020-11-19 06:54 UTC, merged