Add documentation for the Twinkly integration
home-assistant/home-assistant.github.io pull request #15323
Opened 2020-10-20 04:33 UTC by dr1rrb

## Proposed change

Add documentation for the new Twinkly integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/42103
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/1954
- This PR fixes or closes issue: _none_

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-11-22 03:16 UTC, dr1rrb commented
@frenck @hunterjm If you don't any comment about the content of the doc, as the PR in core has been merged, I think this should be merged to 😊

2020-11-22 10:56 UTC, frenck commented
Please don't push or ping for those things. It will be handled and picked up automatically. Thanks 👍

2020-11-23 09:34 UTC, frenck requested changes

2020-11-23 09:34 UTC, frenck commented on source/_integrations/twinkly.markdown
> +The `twinkly` integration allows you to control [Twinkly](https://twinkly.com/) LED string from Home Assistant.
```suggestion
The Twinkly integration allows you to control [Twinkly](https://twinkly.com/) LED string from Home Assistant.
```

2020-11-23 09:34 UTC, frenck commented on source/_integrations/twinkly.markdown
> +## Setup
```suggestion
## Configuration
```

2020-11-23 09:34 UTC, frenck commented on source/_integrations/twinkly.markdown
> +You can setup this integration from the Home Assistant user interface,
We should describe here how to do that, e.g., by providing a click path and/or step by step instructions.

2020-11-23 09:35 UTC, frenck commented on source/_integrations/twinkly.markdown
> +ha_release: '0.117'
```suggestion
ha_release: 0.119
```

2020-11-23 09:35 UTC, frenck commented on source/_integrations/twinkly.markdown
> +description: Instructions on how to integrate Twinkly led string to Home Assistant.
```suggestion
description: Instructions on how to integrate Twinkly LED string to Home Assistant.
```

2020-11-23 18:13 UTC, frenck approved these changes
Thanks! 👍

2020-11-23 18:13 UTC, merged