Init commit of ColorThief component and service calls
home-assistant/home-assistant.github.io pull request #15333
Opened 2020-10-20 20:35 UTC by GenericStudent

## Proposed change

This PR links up with the new ColorThief component. It allows service call to pass in either a URL or a file path to an image file, colorthief then gives us the predominant color (RGB tuple) which we then set to the referenced light entity.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/42129
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-10-20 20:37 UTC, GenericStudent commented
Just a note, I have a Ubuntu 20 enviornment and Centos 7 environment. Neither are working using the default instructions to install ruby and build docs :( so have been unable to view the MD locally.

2020-10-25 00:39 UTC, klaasnicolaas requested changes

2020-10-25 00:39 UTC, klaasnicolaas commented on source/_integrations/color_extractor.markdown
> +logo: home-assistant.png
```suggestion
```
Please remove this line

2020-10-28 21:58 UTC, klaasnicolaas requested changes

2020-10-28 21:58 UTC, klaasnicolaas commented on source/_integrations/color_extractor.markdown
> +- alias:
```suggestion
- alias:
```

Missing a nice name 😉

2020-10-28 22:09 UTC, GenericStudent commented on source/_integrations/color_extractor.markdown
> +- alias:
Good catch 😀

2020-11-08 20:26 UTC, frenck approved these changes
Thanks, @GenericStudent 👍

2020-11-08 20:26 UTC, merged