Add docs roon services
home-assistant/home-assistant.github.io pull request #15340
Opened 2020-10-21 13:45 UTC by pavoni

## Proposed change

I've proposed a PR to add some platform services to the Roon media player, this is the matching documentation.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/42133
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-10-24 13:49 UTC, frenck requested changes
Thanks for the PR @pavoni!

I've reviewed it and left some comments. Could you take a look?

Additionally, I noticed that the `### Configuration` heading is a level 3 heading, while it should have been level 2. Maybe adjust that while you are at it?

2020-10-24 13:49 UTC, frenck commented on source/_integrations/roon.markdown
> +### Service `join`
```suggestion
## Services

### Service `roon.join`
```

2020-10-24 13:49 UTC, frenck commented on source/_integrations/roon.markdown
> +| `entity_id` | no | id of the player that will be the master of the group.
This service is registered using `async_register_entity_service`, which means the `entity_id` is optional (as a group of entities in an area can be targeted alternatively).

```suggestion
| `entity_id` | yes | ID of the player that will be the master of the group.
```

2020-10-24 13:49 UTC, frenck commented on source/_integrations/roon.markdown
> +### Service `unjoin`
```suggestion
### Service `roon.unjoin`
```

2020-10-24 13:49 UTC, frenck commented on source/_integrations/roon.markdown
> +| `entity_id` | no | id of the player that is the master of the group.
This service is registered using `async_register_entity_service`, which means the `entity_id` is optional (as a group of entities in an area can be targeted alternatively).

```suggestion
| `entity_id` | yes | ID of the player that is the master of the group.
```

2020-10-24 13:49 UTC, frenck commented on source/_integrations/roon.markdown
> +### Service `transfer`
```suggestion
### Service `roon.transfer`
```

2020-10-24 13:49 UTC, frenck commented on source/_integrations/roon.markdown
> +| `entity_id` | no | id of the source player.
This service is registered using `async_register_entity_service`, which means the `entity_id` is optional (as a group of entities in an area can be targeted alternatively).

```suggestion
| `entity_id` | yes | id of the source player.
```

2020-10-25 11:14 UTC, pavoni commented
Thanks @frenck - have updated with your suggestions.

I've added your `### Configuration` suggestion to my other PR against `current` https://github.com/home-assistant/home-assistant.io/pull/15339

I'm very happy to refactor the main body of that PR if you can let me know how you'd prefer to approach documenting the limitations of that service call for the roon player.

And thanks for taking the time - can imagine you're very busy with the combination of `hacktoberfest` and the `0.117` release.

2020-10-25 11:34 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-10-26 12:24 UTC, pavoni commented
Just fixed the conflicts with the changes to `current`

2020-10-27 21:02 UTC, frenck approved these changes

2020-10-27 21:02 UTC, merged