alarm_control_panel.alarm_trigger new delay param
home-assistant/home-assistant.github.io pull request #15399
Opened 2020-10-25 15:22 UTC by tomer-w

## Proposed change

This change document the change in home-assistant/core#41657 . We will now support delay param in alarm_control_panel.alarm_trigger service so users can have different delay for windows and doors for example.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
https://github.com/home-assistant/core/pull/41657
## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-10-25 15:47 UTC, derekatkins requested changes
I think it is useful to show an example with multiple triggers -- I used that knowledge from this exact example when I was first installing.  Can we use a template to set the delay?  Maybe something like:
```
delay: >-
  {%- if trigger == sensor.door -%}
    30
  {%- else -%}
    None
  {%- endif %}
```
(NB: there is probably a better way to template that)

2020-10-25 16:05 UTC, frenck commented
That example is way out of scope here @tomer-w.

2020-10-25 16:05 UTC, frenck requested changes
Please make sure the build passes @tomer-w

2020-10-25 16:08 UTC, derekatkins commented
@frenck Then where should such an example be put?  Or, perhaps, make two examples?
Having an example with multiple triggers, on this page, was extremely useful to me when I was starting.

2020-10-25 16:23 UTC, frenck commented
This PR and documentation is not here to learn you about templating @derekatkins.

2020-10-25 16:36 UTC, derekatkins commented
> This PR and documentation is not here to learn you about templating @derekatkins.

I already agreed with that.  I am suggesting the documentation here keep an example showing multiple entities triggering the alarm.  So perhaps adding a second example that shows adding the `delay` override.

2021-03-29 10:59 UTC, frenck commented
Closing PR as the parent PR has been closed.

2021-03-29 10:59 UTC, closed without merging