Created documentation for the connectedcars integration
home-assistant/home-assistant.github.io pull request #15401
Opened 2020-10-25 17:25 UTC by heslegrave

## Proposed change

Adding a new integration called connectedcars. This is the documentation.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [X] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/42357
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/1751 (Old link, new PR following shortly)

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-10-25 19:22 UTC, heslegrave commented
FYI @esbenr

2020-10-25 20:41 UTC, frenck requested changes
Thanks for the PR @heslegrave!

I've reviewed it, and left some comments. Could you take a look? Thanks 👍

2020-10-25 20:41 UTC, frenck commented on source/_integrations/connectedcars.markdown
> +Thanks to [niklascp](https://pypi.org/user/niklascp/) for creating the PyPi lib so I did not have to..
Giving credit is nice, but we should do it at the end of the page.

Furthermore, don't write it from your perspective, instead, use a third-person view.

2020-10-25 20:41 UTC, frenck commented on source/_integrations/connectedcars.markdown
> +The `connectedcars` integration uses the [ConnectedCars.io](https://connectedcars.io/) web service as a source for car data.
```suggestion
The ConnectedCars.io integration uses the [ConnectedCars.io](https://connectedcars.io/) web service as a source for car data.
```

2020-10-25 20:41 UTC, frenck commented on source/_integrations/connectedcars.markdown
> +You have to get an ConnectedCars.io account and have a connection device installed in the car. In Denmark this is free-of-charge (at moment of writing) on Volkswagen cars [MinVolkswagen](https://site
```suggestion
You have to get a ConnectedCars.io account and have a connection device installed in the car. In Denmark, this is free-of-charge (at the moment of writing) on Volkswagen cars [MinVolkswagen](https://site.volkswagen.dk/minvolkswagen/).
```

2020-10-25 20:41 UTC, frenck commented on source/_integrations/connectedcars.markdown
> +Simply put you `username`, `password` and `namespace`.
Avoid the use of `simply`. While it might be simple for you, it might be difficult for (and thus possibly perceived condescending by) others.

2020-10-25 20:41 UTC, frenck commented on source/_integrations/connectedcars.markdown
> +The `namespace` can be found if you login to [ConnectedCars.io GraphQL](https://api.connectedcars.io/graphql/graphiql/#) - look to the upper right corner after login.
```suggestion
The `namespace` can be found if you log in to [ConnectedCars.io GraphQL](https://api.connectedcars.io/graphql/graphiql/#) - look to the upper right corner after login.
```

2020-10-25 20:41 UTC, frenck commented on source/_integrations/connectedcars.markdown
> +Vin is still not used, the integration adds the cars entities by itself.
```suggestion
Vin is still not used, the integration adds the car entities by itself.
```

2020-10-25 20:41 UTC, frenck commented on source/_integrations/connectedcars.markdown
> +</div>
We don't inform you about the future additions in our documentation. Please remove that part.

2020-11-07 11:24 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-06-17 10:24 UTC, frenck commented
Closing PR as the parent PR has been closed.

2021-06-17 10:24 UTC, closed without merging