Update ruckus_unleashed.markdown
home-assistant/home-assistant.github.io pull request #15476
Opened 2020-10-29 21:53 UTC by pathia

Added the requirement to add the ip address of the master AP.
It was not mentioned in the documentation and took me some time to tackle. I just don't want other to make the same mistake.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-11-07 00:33 UTC, frenck requested changes

2020-11-07 00:33 UTC, frenck commented on source/_integrations/ruckus_unleashed.markdown
> +Remember to configure the IP address of your master access point. See Access Points on the management web interface. And perhaps consider to set a preferred master (Admin & Services>System>System Inf
Why is this part of the after fact/troubleshooting and not part of the configuration instructions?

2020-11-10 20:30 UTC, pathia commented
Added the requirement to add the IP address of the master AP. Now in the proposed section.

2020-11-10 20:32 UTC, frenck commented on source/_integrations/ruckus_unleashed.markdown
> +It is required to configure the IP address of your **master access point**. See the section Access Points on the management web interface. And perhaps consider to set a preferred master (Admin & Serv
```suggestion

It is required to configure the IP address of your **master access point**. See the section Access Points on the management web interface. And perhaps consider to set a preferred master (Admin & Services>System>System Info>Preferred master).
```

2020-11-10 20:32 UTC, frenck approved these changes
Thanks, @pathia 👍

2020-11-10 20:35 UTC, merged