Update influxdb.markdown
home-assistant/home-assistant.github.io pull request #15487
Opened 2020-10-30 11:28 UTC by foxy82

Added how to query influxdb as the way sensors are stored isn't obvious.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-10-30 11:36 UTC, klaasnicolaas requested changes

2020-10-30 11:36 UTC, klaasnicolaas commented on source/_integrations/influxdb.markdown
> +## Querying your data in Infux
Infux? 🤣

2020-10-30 11:37 UTC, foxy82 commented on source/_integrations/influxdb.markdown
> +## Querying your data in Infux
👍 thanks - fixed

2020-11-06 23:47 UTC, frenck commented on source/_integrations/influxdb.markdown
> +### Everythign else
```suggestion
### Everything else
```

2020-11-07 00:27 UTC, frenck approved these changes
Thanks, @foxy82 👍

2020-11-07 00:28 UTC, merged