Update weather.markdown
home-assistant/home-assistant.github.io pull request #15494
Opened 2020-10-30 18:57 UTC by jcgoette

Fix broken link.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-10-31 19:57 UTC, frenck requested changes

2020-10-31 19:57 UTC, frenck commented on source/_integrations/weather.markdown
> +The `weather` platform only knows the below listed conditions. The reason for this is that for these conditions is an icon from [Material Design Icons](https://materialdesignicons.com/) available and
So uh, why is the link to this code even in our documentation?

2020-10-31 22:12 UTC, jcgoette reviewed
Completely removed link.

2020-11-01 02:38 UTC, klaasnicolaas approved these changes

2020-11-06 20:57 UTC, frenck approved these changes
Thanks, @jcgoette 👍

2020-11-06 20:57 UTC, merged