Add reboot and shutdown service to synology_dsm
home-assistant/home-assistant.github.io pull request #15511
Opened 2020-11-01 22:03 UTC by mib1185

## Proposed change

This PR make use of new features in [python-synology lib v1.0.0](https://github.com/ProtoThis/python-synology/releases/tag/1.0.0) and add services to reboot and shutdown a DSM.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#42697
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-11-02 13:15 UTC, frenck requested changes
There are unrelated commits in this PR.
Please be sure to start with a clean branch when opening a PR for a new feature. You can git rebase this PR/branch to clean it up.

2020-11-02 23:46 UTC, mib1185 commented
> There are unrelated commits in this PR.
> Please be sure to start with a clean branch when opening a PR for a new feature. You can git rebase this PR/branch to clean it up.

Hi @frenck should I branch from `current` or from `next` ?

2020-11-03 02:25 UTC, klaasnicolaas commented
I see changes that you also apply in this pull request: https://github.com/home-assistant/home-assistant.io/pull/15413/files

For new features / integrations you create a branch that descends from the `next` branch. Because your current `next` branch is related to your other pull request and you made a copy of it for `synology-dsm_add-services` in this pull request, your commits have been mixed up.

2020-11-03 20:36 UTC, mib1185 commented
will rebase as soon #15413 is merged.

2020-11-06 20:32 UTC, frenck requested changes

2020-11-06 20:32 UTC, frenck commented on source/_integrations/synology_dsm.markdown
> +- `synology_dsm.reboot`: Reboot the by `serial` specified DSM. If only one DSM is configured, `serial` is not requiered.
```suggestion
### Service `synology_dsm.reboot`

Reboot the by `serial` specified DSM. If only one DSM is configured, `serial` is not required.
```

2020-11-06 20:32 UTC, frenck commented on source/_integrations/synology_dsm.markdown
> +- `synology_dsm.shutdown`: Shutdown the by `serial` specified DSM. If only one DSM is configured, `serial` is not requiered.
```suggestion
### Service `synology_dsm.shutdown`

Shutdown the by `serial` specified DSM. If only one DSM is configured, `serial` is not required.
```

2020-11-06 20:51 UTC, frenck requested changes

2020-11-06 20:51 UTC, frenck commented on source/_integrations/synology_dsm.markdown
> +## Services `synology_dsm.reboot`
```suggestion
## Services

## Service `synology_dsm.reboot`
```

2020-11-06 20:51 UTC, frenck commented on source/_integrations/synology_dsm.markdown
> +## Services `synology_dsm.shutdown`
```suggestion
## Service `synology_dsm.shutdown`
```

2020-11-06 21:00 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2020-11-11 18:08 UTC, merged

2020-11-11 18:12 UTC, Quentame requested changes
requiered --> required

2020-11-11 18:12 UTC, Quentame commented on source/_integrations/synology_dsm.markdown
> +Reboot the by `serial` specified DSM. If only one DSM is configured, `serial` is not requiered.
```suggestion
Reboot the specified NAS by `serial`. If only one DSM is configured, `serial` is optional.
```

2020-11-11 18:12 UTC, Quentame commented on source/_integrations/synology_dsm.markdown
> +Shutdown the by `serial` specified DSM. If only one DSM is configured, `serial` is not requiered.
```suggestion
Shutdown the specified NAS by `serial`. If only one DSM is configured, `serial` is optional.
```

2020-11-11 18:14 UTC, Quentame commented
Adding a fix

2020-11-11 18:17 UTC, Quentame commented
Fix typo PR #15615