Add Interlogix Ultrasync Alarm System Integration
home-assistant/home-assistant.github.io pull request #15588
Opened 2020-11-09 18:56 UTC by caronc

## Proposed change
Added documentation for new integration: Interlogix UltraSync Hub

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  [core/42549](https://github.com/home-assistant/core/pull/42549)
- Link to parent pull request in the Brands repository: [brands/1994](https://github.com/home-assistant/brands/pull/1994)
- This PR fixes or closes issue: n/a

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-11-09 18:58 UTC, caronc commented
I originally had [this ticket here](https://github.com/home-assistant/home-assistant.io/pull/15482) which closed for some reason when i pushed up my change upon recomendation of @frenck .  I'm not sure if i lose out on the OctoberFest thing; that's not a problem really, but i definitely don't want my code to get missed or closed off :slightly_smiling_face:

2020-11-09 19:01 UTC, frenck commented
Ouch! What happened there 😓  The right labels are on the previous PR, so it should count correctly towards Hacktoberfest 😉

2020-11-09 19:04 UTC, caronc commented
Thanks for such a quick reply; i went ahead and updated the brand and core PR to point to this one instead if that's easier.  You can leave the other one closed.

2022-02-18 18:17 UTC, frenck requested changes

2022-02-18 18:17 UTC, frenck commented on source/_integrations/ultrasync.markdown
> +The `ultrasync` platform will allow you to monitor and control your Interlogix and/or ComNav NX-595E UltraSync Hub from within Home Assistant and setup automation.
```suggestion
The Interlogix UltraSync Hub integration will allow you to monitor and control your Interlogix or ComNav NX-595E UltraSync Hub from within Home Assistant.
```

2022-02-18 18:17 UTC, frenck commented on source/_integrations/ultrasync.markdown
> +Go to the integrations page in your configuration and click on new integration -> UltraSync.
We have a nice little include for this, that handles this all 🤘 

```suggestion
{% include integrations/config_flow.md %}
```

2022-02-18 18:17 UTC, frenck commented on source/_integrations/ultrasync.markdown
> +**Note**: You can only be logged into the ZeroWire/UltraSync hub with the same user once; a subsequent login with the same user logs out the other. Since Home Assistant (HA) actively polls and mainta
```suggestion
**Note**: You can only be logged into the ZeroWire/UltraSync hub with the same user once; a subsequent login with the same user logs out the other. Since Home Assistant (HA) actively polls and maintains a login session to this Hub, it can prevent you from being able to log in at the same time elsewhere (via its website). It is strongly recommended that you create a second user account on your Hub dedicated to just HA.
```

2022-02-18 18:17 UTC, frenck commented on source/_integrations/ultrasync.markdown
> +This component will create these sensors in the format of `{ultrasync_hubname}_{sensor}`;  The below example assumes you accept the default name of `UltraSync` (which is still represented in lowercas
It sounds like you are trying to describe the resulting entity IDs, however, those are not guaranteed.

Instead, you could just describe the type of sensors created (without using entity IDs).

2022-02-18 18:17 UTC, frenck commented on source/_integrations/ultrasync.markdown
> +There are several states each sensor can be at, but usually they will be one of the following: `Unknown`, `Ready`, `Not Ready`, `Armed Stay`, and `Armed Away`.  The `Unknown` state is assigned to sen
```suggestion
There are several states each sensor can be at, but usually, they will be one of the following: `Unknown`, `Ready`, `Not Ready`, `Armed Stay`, and `Armed Away`.  The `Unknown` state is assigned to sensors that are not reporting; they usually sit in the spots of the areas you're not monitoring.
```

2022-02-18 18:17 UTC, frenck commented on source/_integrations/ultrasync.markdown
> +There are several states each sensor can be at, but usually they will be one of the following: `Unknown`, `Ready`, `Not Ready`, `Armed Stay`, and `Armed Away`.  The `Unknown` state is assigned to sen
Additionally, those are states as shown in the UI, they are not the actual state.

2022-02-18 18:17 UTC, frenck commented on source/_integrations/ultrasync.markdown
> +When an Zone or Sensor changes it's state an event usable for automation is triggered on the Home Assistant Bus.
I like this section, it helps users. However, have you considered adding support for device automations? That would make this all available via the UI (without needing the know the actual events and other technical details).

2022-02-18 18:17 UTC, frenck commented on source/_integrations/ultrasync.markdown
> +When an Zone or Sensor changes it's state an event usable for automation is triggered on the Home Assistant Bus.
```suggestion
When a Zone or Sensor changes its state an event usable for automation is triggered on the Home Assistant bus.
```

2022-02-18 18:17 UTC, frenck commented on source/_integrations/ultrasync.markdown
> +Example automation to send a message via [Apprise](https://www.home-assistant.io/integrations/apprise/) on a sensor change in your home:
```suggestion
Example automation to send a message via [Apprise](/integrations/apprise/) on a sensor change in your home:
```

2022-02-18 18:17 UTC, frenck commented on source/_integrations/ultrasync.markdown
> +- `disarm`: Disarm the alarm
Shouldn't this be implementing the standard services of the `alarm_control_panel`?

2022-05-16 11:15 UTC, frenck commented
Closing PR as the parent PR has been closed.

2022-05-16 11:15 UTC, closed without merging