Add iAlarm integration
home-assistant/home-assistant.github.io pull request #15718
Opened 2020-11-22 14:00 UTC by RyuzakiKK

## Proposed change

Previous iAlarm integration has been removed because it used webscraping https://github.com/home-assistant/core/pull/43010 and https://github.com/home-assistant/home-assistant.io/pull/15584

Now pyialarm library has been updated to the version 1.0 that uses the iAlarm API instead https://github.com/RyuzakiKK/pyialarm/blob/master/pyialarm/pyialarm.py

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/43525
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-11-22 22:25 UTC, frenck requested changes

2020-11-22 22:25 UTC, frenck commented on source/_integrations/ialarm.markdown
> +  - platform: ialarm
We no longer accept YAML configuration for integrations that connect to devices or services.

Instead, a configuration flow via the UI should be used.

For more information about this decision see:

- ADR-0007: <https://github.com/home-assistant/architecture/blob/master/adr/0007-integration-config-yaml-structure.md#decision>
- ADR-0010: <https://github.com/home-assistant/architecture/blob/master/adr/0010-integration-configuration.md#decision>

To get started on the integration configuration, see our developer documentation:

<https://developers.home-assistant.io/docs/config_entries_config_flow_handler>

2020-12-29 22:05 UTC, RyuzakiKK commented on source/_integrations/ialarm.markdown
> +ha_quality_scale: silver
Not 100% sure about this one yet.

2021-04-11 11:27 UTC, RyuzakiKK commented on source/_integrations/ialarm.markdown
> +ha_quality_scale: silver
Removed for now.

2021-04-12 11:43 UTC, frenck commented on source/_integrations/ialarm.markdown
> +This platform supports the following services: `alarm_arm_away`, `alarm_arm_home` and `alarm_disarm`.
```suggestion
The iAlarm integration provides connectivity with the [Antifurto365](https://www.antifurtocasa365.it/) iAlarm alarm systems and has also been confirmed to work with the alarm system brands Meian and Emooluxr.

This platform supports the following services:

- `alarm_control_panel.alarm_arm_away`
- `alarm_control_panel.alarm_arm_home`
- `alarm_control_panel.alarm_disarm`
```

2021-04-12 12:19 UTC, frenck approved these changes
Thanks, @RyuzakiKK 👍

2021-04-12 12:19 UTC, merged