Update no-url-available.markdown to include subdomain hint
home-assistant/home-assistant.github.io pull request #15742
Opened 2020-11-24 12:15 UTC by samuelalexmclean

## Proposed change
Add a bullet for the www vs naked domain trap. Even if you click into the address bar, Chrome hides the www until you make a second click to move your cursor somewhere within the selected address.

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-11-24 12:17 UTC, samuelalexmclean commented
@frenck has state on this - Franck, I understand if you think this is a corner case and don't want it in the docs, but I thought I would propose the addition just in case.

2020-11-24 15:02 UTC, frenck requested changes
Thanks! Got a small suggestion for improving it, what do you think?

2020-11-24 15:02 UTC, frenck commented on source/more-info/no-url-available.markdown
> +  bar and pressing enter.
```suggestion
- Ensure that the URL you provide matches the true address your browser uses to
  reach the instance. Many popular browsers will hide the www subdomain; if you
  try to configure `http://foo.bar`, but you're actually at `http://www.foo.bar`,
  OAuth will fail and you will receive this error. You can always check the
  actual domain by pasting `javascript:alert(document.location)` in your address
  bar and pressing enter.
```

2020-11-25 07:10 UTC, samuelalexmclean commented
> Thanks! Got a small suggestion for improving it, what do you think?

Looks much better, thanks! Applied.

2020-11-25 10:16 UTC, frenck approved these changes
Thanks 👍

2020-11-25 10:16 UTC, merged