Update zha.markdown with Zigbee device limits information
home-assistant/home-assistant.github.io pull request #15790
Opened 2020-11-30 15:43 UTC by Hedda

## Proposed change

Update zha.markdown with Zigbee device limits information based on Zigbee2MQTT FAQ https://www.zigbee2mqtt.io/information/FAQ.html#i-read-that-zigbee2mqtt-has-a-limit-of-20-devices-is-this-true

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: NA
- Link to parent pull request in the Brands repository: NA
- This PR fixes or closes issue: NA

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-11-30 17:36 UTC, frenck requested changes

2020-11-30 17:36 UTC, frenck commented on source/_integrations/zha.markdown
> +You use routers to increase the number of of Zigbee devices that can be used in a network. The total number of Zigbee devices that you have on a Zigbee network depends on a few things, nut you should
```suggestion
You use routers to increase the number of Zigbee devices that can be used in a network. The total number of Zigbee devices that you have on a Zigbee network depends on a few things, but you should know that Zigbee coordinator hardware and firmware only plays a larger role in Zigbee networks with a lot of devices. More important is how many directly connected devices ("direct children") versus how many routers are connected to your Zigbee coordinator. Zigpy library which ZHA uses has an upper limit is 32 direct children but if your Zigbee coordinator hardware is powerful enough then you can still have hundreds of Zigbee devices connected through routers.  
```

2020-11-30 17:36 UTC, frenck commented on source/_integrations/zha.markdown
> +Even the lest powerful Zigbee coordinator hardware supported by Zigpy is CC2530/2531 and its default firmware only support 20 devices connected directly to the coordinator. However, by having routers
```suggestion
Even the least powerful Zigbee coordinator hardware supported by Zigpy is CC2530/2531 and its default firmware, only supports 20 devices connected directly to the coordinator. However, by having routers in your Zigbee network the mesh network size can be extended. You can assume that most, if not all mains/AC-powered devices, e.g., wall-plugs and always powered-on lightbulbs in your Zigbee network, can serve as a router. You can even use CC2530/CC2531 with router firmware, as additional routers (which in their turn have a limit of 21 devices).
```

2020-11-30 17:36 UTC, frenck commented on source/_integrations/zha.markdown
> +An example is using the defaultCC2531 coordinator firmware + two CC2531 routers your device limit will be:
```suggestion
An example using the default CC2531 coordinator firmware + two CC2531 routers; Your device limit will be:
```

2020-12-02 08:13 UTC, Hedda commented
Thanks for the review!

2020-12-02 08:16 UTC, frenck approved these changes
Thanks! 👍

2020-12-02 08:16 UTC, merged