Reorg automation docs and add a using blueprints section
home-assistant/home-assistant.github.io pull request #15811
Opened 2020-12-03 16:49 UTC by balloob

## Proposed change

Reorganize automation documentation and add a section about using blueprints.

Note, this is not about creating blueprints.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-12-03 17:04 UTC, zsarnett commented on source/_docs/automation.markdown
> +If you are just starting out, we strongly suggest you start with blueprint automations. These are ready made automations by the community that you only need to configure.
```suggestion
If you are just starting, we strongly suggest you start with blueprint automations. These are ready-made automations by the community that you only need to configure.
```

2020-12-03 17:05 UTC, zsarnett commented on source/_docs/automation/basics.markdown
> +We can break up this automation in the following three parts:
```suggestion
We can break up this automation into the following three parts:
```

2020-12-03 17:05 UTC, zsarnett commented on source/_docs/automation/basics.markdown
> +Actions are all about calling services. To explore the available services open the **Developer Tools** -> **Services**. Services allow to change anything. For example turn on a light, run a script or
```suggestion
Actions are all about calling services. To explore the available services open the **Developer Tools** -> **Services**. Services allow changing anything. For example turn on a light, run a script or enable a scene. Each service has a domain and a name. For example the service `light.turn_on` is capable of turning on any light in your system. Services can be passed parameters to for example tell which device to turn on or what color to use.
```

2020-12-03 17:06 UTC, zsarnett commented on source/_docs/automation/basics.markdown
> +Now that you've got a sneak peak of what is possible, it's time to get your feet wet and create your first automation.
```suggestion
Now that you've got a sneak peek of what is possible, it's time to get your feet wet and create your first automation.
```

2020-12-03 17:07 UTC, zsarnett commented on source/_docs/automation/modes.markdown
> +Sometimes an automation is doing an action on a device that does not support multiple simultaneous actions. In such cases a queue can be used. In that case the automation will be executed once it's c
```suggestion
Sometimes an automation is doing an action on a device that does not support multiple simultaneous actions. In such cases, a queue can be used. In that case, the automation will be executed once it's current invocation and queue are done.
```

2020-12-03 17:18 UTC, frenck requested changes

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation.markdown
> +If you are just starting out, we strongly suggest you start with blueprint automations. These are ready made automations by the community that you only need to configure.
```suggestion
If you are just starting out, we strongly suggest you start with blueprint automations. These are ready-made automations by the community that you only need to configure.
```

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation.markdown
>  description: "Steps to help you get automation setup in Home Assistant."
What I mis on this page:

What is automation?!

(we didn't tell that before either thought).

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation/services.markdown
> +
This part of the documentation now feels very out of place.

I think it needs at least a couple of lines to indicate what is on this page.

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation/services.markdown
> +### `automation.turn_on`
```suggestion
## Service `automation.turn_on`
```

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation/services.markdown
> +### `automation.turn_off`
```suggestion
## Service `automation.turn_off`
```

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation/services.markdown
> +### `automation.toggle`
```suggestion
## Service `automation.toggle`
```

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation/services.markdown
> +### `automation.reload`
```suggestion
## Service `automation.reload`
```

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation/services.markdown
> +### `automation.trigger`
```suggestion
## Service `automation.trigger`
```

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +Done! If you want to revisit the configuration values, you can find it by going to **Configuration** and then **Automations**
```suggestion
Done! If you want to revisit the configuration values, you can find it by going to **Configuration** and then **Automations**.
```

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation/yaml.markdown
> +The UI will write your automations to `automations.yaml`. This file is managed by the UI and should not be editted manually.
```suggestion
The UI will write your automations to `automations.yaml`. This file is managed by the UI and should not be edited manually.
```

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation/yaml.markdown
> +
```suggestion
It is also possible to write your automations directly inside `configuration.yaml` or other YAML files. You can do this by adding a labeled `automation` block to your `configuration.yaml`:

```

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation/yaml.markdown
> +# Labelled automation block
```suggestion
# Labeled automation block
```

2020-12-03 17:18 UTC, frenck commented on source/_docs/automation/yaml.markdown
> +You can add as manny labelled `automation` blocks as you want.
```suggestion
You can add as many labeled `automation` blocks as you want.
```

2020-12-04 09:25 UTC, frenck approved these changes
Nice! 👍

2020-12-04 09:26 UTC, merged