Update meteo_france documentation
home-assistant/home-assistant.github.io pull request #15894
Opened 2020-12-13 18:26 UTC by mbo18

## Proposed change

Update documentation following this PR: https://github.com/home-assistant/core/pull/44150

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: Linked PR: https://github.com/home-assistant/core/pull/44150
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-12-13 22:40 UTC, oncleben31 requested changes

2020-12-13 22:40 UTC, oncleben31 commented on source/_integrations/meteo_france.markdown
> +|`original_condition`|The current original weather condition|No|
Can you move it to respect alphabetical order.

2020-12-14 08:26 UTC, fabaff approved these changes
Thanks

2020-12-14 08:26 UTC, merged

2020-12-15 09:58 UTC, frenck commented
@fabaff This PR should not have been merged!