Removed dead link
home-assistant/home-assistant.github.io pull request #15895
Opened 2020-12-13 19:01 UTC by kimvonmullen

The link does not work anymore.

## Proposed change

The link is dead, thus I would suggest to remove it. 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-12-13 21:43 UTC, TomBrien commented
Looks like the original link was badly formatted

2020-12-13 21:48 UTC, TomBrien requested changes

2020-12-13 21:48 UTC, TomBrien commented on source/hassio/installation.markdown
> +      - [Intel NUC][intel-nuc]
```suggestion
       - [Guide: Flashing Odroid-N2 using OTG-USB][otg-usb]
     - [Intel NUC][intel-nuc]
```

2020-12-13 21:48 UTC, TomBrien commented on source/hassio/installation.markdown
> +      - [Intel NUC][intel-nuc]
Let's keep the link and change the very last line to:
```markdown
../flashing_n2_otg
```

2020-12-15 10:23 UTC, frenck commented
The link has been fixed.

2020-12-15 10:23 UTC, closed without merging