Remove avri documentation
home-assistant/home-assistant.github.io pull request #15993
Opened 2020-12-23 12:11 UTC by timvancann

## Proposed change

This removes the documentation for the deprecated component Avri 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-12-23 12:43 UTC, frenck requested changes
This removal is incomplete. Please make sure all links to this page are cleaned up as well.

2020-12-23 17:07 UTC, w1ll1am23 commented
@frenck seems like this could result in confusion for users if the documentation is completely removed? Should something be left behind in order for users who stumble across old forum posts or something to indicate it was removed in release X?

I don't think this has been done previously, but seems like it could help people out.

2020-12-24 01:32 UTC, frenck commented
If you have a suggestion for that, sure. But let's keep it out of this PR, as it is out of scope for current running things.

2020-12-26 13:55 UTC, frenck requested changes

2020-12-26 13:55 UTC, frenck commented on source/_posts/2020-03-18-release-107.markdown
> -- Add Avri waste collection sensor ([@timvancann] - [#31134]) ([avri docs]) (new-integration)
These lines should not have been removed, as they are still true. Only the link to the documentation should have been removed.

(this applies to all other occurrences as well).

2020-12-27 08:32 UTC, MartinHjelmare commented
Please update the brands repo too.

2020-12-28 20:09 UTC, frenck commented
Added a brands PR to clean it up

2020-12-29 14:56 UTC, frenck approved these changes
Thanks! 👍

2020-12-29 14:56 UTC, merged