Asuswrt config entries
home-assistant/home-assistant.github.io pull request #16012
Opened 2020-12-25 18:14 UTC by ollo69

## Proposed change

AsusWRT documentation update to add ConfgFlow and related options. 
The associated PR in the codebase use a dedicated branch and will require multiple commit before merging in dev branch. 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [#43948](https://github.com/home-assistant/core/pull/43948) 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2020-12-26 13:49 UTC, frenck requested changes

2020-12-26 13:49 UTC, frenck commented on source/_integrations/asuswrt.markdown
> +_YAML configuration is still around for people that prefer YAML, but it's deprecated, and you should not use it anymore._
YAML configuration should be removed from documentation when the configuration flow is introduced.

2020-12-28 16:21 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-01-02 01:08 UTC, MartinHjelmare commented
Parent PR is merged into a side branch (non default). More core PRs are expected to come with this docs PR linked.

2021-02-12 10:07 UTC, MartinHjelmare commented
@ollo69 please let us know the status of the parent PRs when all are ready. Ie when the big PR from the separate side branch is merged into core dev branch, ping us here so we know when to merge this.

2021-02-12 11:08 UTC, ollo69 commented
Just to understand, the PR to merge the branch `asuswrt-config-entries` in `dev` must be created by me? Sorry but I'm not expert in this process.

2021-02-12 11:11 UTC, MartinHjelmare commented
Yes, that's correct. 👍

2021-02-13 18:18 UTC, MartinHjelmare commented
Parent PR was merged.

2021-02-13 18:19 UTC, MartinHjelmare approved these changes

2021-02-13 19:27 UTC, frenck approved these changes

2021-02-13 19:27 UTC, merged