Update locked_out.md
home-assistant/home-assistant.github.io pull request #16037
Opened 2020-12-29 13:13 UTC by kenguest

I forgot my password, while still logged in, found out how to reset it by creating another account... 
I've updated relevant parts of this document to detail the process I followed, and to also explicitly note how to reset another user's password and how to delete a user.

Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

2020-12-29 13:17 UTC, frenck requested changes

2020-12-29 13:17 UTC, frenck commented on source/_docs/locked_out.md
> +#### To reset a user's password, as an administrator
What is unclear right now, is is this paragraph needed if I did the auth reset listed above?

Maybe adding an additional introduction in this paragraph helps? Also, if listing steps, please use a type of list to make clear it is a step-by-step instruction that is given.

2020-12-29 22:36 UTC, kenguest reviewed
hi @frenck - that's done now. please let me know if there's anything else I need to tweak. :-)

2020-12-29 22:36 UTC, kenguest commented on source/_docs/locked_out.md
> +#### To reset a user's password, as an administrator
You're absolutely correct - what I added is to do with actions done through the UI. I'll explicitly state that later.

2021-01-25 14:18 UTC, frenck commented on source/_docs/locked_out.md
> +#### To reset a user's password, as an administrator via the web interface
```suggestion
#### To reset a user's password, as an administrator via the web interface

```

2021-01-25 14:18 UTC, frenck commented on source/_docs/locked_out.md
> +#### To delete a user, as an administrator via the web interface
```suggestion
#### To delete a user, as an administrator via the web interface

```

2021-01-25 14:18 UTC, homeassistant commented
Hi @kenguest, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#16037).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-01-25 14:18 UTC, homeassistant commented
Hi @kenguest, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#16037).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-01-25 14:19 UTC, frenck approved these changes
Thanks, @kenguest 👍

2021-01-25 14:40 UTC, merged