Add ecobee set humidifier mode
home-assistant/home-assistant.github.io pull request #16139
Opened 2021-01-10 01:34 UTC by treylok

## Proposed change

Document ability to set the humidifier mode of an ecobee thermostat with a humidifier attached.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/45003
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-01-10 21:28 UTC, frenck requested changes
This PR needs to be targeting the `next` branch, as it relies on a code change in the Home Assistant code base (and thus a next release).

Please change the target of this PR to the `next` branch and git rebase the PR if needed.

Thanks 👍

2021-01-25 14:49 UTC, frenck commented
There are unrelated commits in this PR, you still need to rebase it onto the `next` branch @treylok 👍

2021-01-25 16:52 UTC, treylok commented
Sorry, not sure what I did.  Hopefully this is correct.

2021-01-25 16:56 UTC, frenck requested changes
Yeah, that did the trick @treylok 👍 

2 small suggestions and the docs are ready to go 👍

2021-01-25 16:56 UTC, frenck commented on source/_integrations/ecobee.markdown
> +| `entity_id`            | no       | ecobee thermostat on which to set the humidifier mode |
Entity ID is optional, as this service is registered with `async_register_entity_service`.

```suggestion
| `entity_id`            | yes      | ecobee thermostat on which to set the humidifier mode |
```

2021-01-25 16:56 UTC, frenck commented on source/_integrations/ecobee.markdown
> +| `humidifier_modes` | This is only shown if a humidifier is controlled by ecobee and displays the valid humidifier modes: `auto` / `off` / `manual`
```suggestion
| `humidifier_modes` | This is only shown if a humidifier is controlled by ecobee and displays the valid humidifier modes: `auto` / `off` / `manual`.
```

2021-01-25 17:46 UTC, frenck approved these changes, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-04-12 21:45 UTC, MartinHjelmare requested changes

2021-04-12 21:45 UTC, MartinHjelmare commented on source/_integrations/ecobee.markdown
> +| `humidifier_modes` | This is only shown if a humidifier is controlled by ecobee and displays the valid humidifier modes: `auto` / `off` / `manual`.
We changed the parent PR to add a humidifier platform instead.

2021-04-12 21:45 UTC, MartinHjelmare commented
Let's just update the `ha_category` and `ha_platforms` front matter.

2021-04-13 06:29 UTC, MartinHjelmare commented on source/_integrations/ecobee.markdown
> +- `ecobee.set_humidifier_mode`
We didn't add this custom service.

2021-04-13 12:18 UTC, treylok commented on source/_integrations/ecobee.markdown
> +- `ecobee.set_humidifier_mode`
Sorry I missed that one, removing now.

2021-04-13 12:25 UTC, MartinHjelmare approved these changes
Thanks!

2021-04-13 12:43 UTC, frenck approved these changes

2021-04-13 12:43 UTC, merged