Trying to address https://github.com/home-assistant/home-assistant.io…
home-assistant/home-assistant.github.io pull request #16152
Opened 2021-01-11 05:39 UTC by nickrout

…/issues/15721

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-01-11 11:39 UTC, frenck requested changes

2021-01-11 11:39 UTC, frenck commented on source/_docs/installation.markdown
> +The only installation methods that allow you to use Home Assistant Add-ons is using the [Home Assistant OS](/hassio/installation/)|[A supported platform](/hassio/installation/) image or a [Home Assis
The supported installation images linked are also all Home Assistant OS, thus you are listing a duplicate?

2021-01-12 03:45 UTC, nickrout commented
Better now?

2021-01-12 07:44 UTC, frenck commented
@nickrout I don't see any changes? Forgot to push up your changes?

2021-01-25 14:20 UTC, frenck commented
@nickrout ?

2021-02-03 19:50 UTC, nickrout commented
Sorry work has been busy. Long weekend this weekend, I'll have some time
hopefully.

On Tue, 26 Jan 2021, 03:21 Franck Nijhof, <notifications@github.com> wrote:

> @nickrout <https://github.com/nickrout> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/home-assistant/home-assistant.io/pull/16152#issuecomment-766848460>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABG6PX26VT3Q6PZWOVMHJ23S3V45RANCNFSM4V5B2PYA>
> .
>

2021-02-22 15:24 UTC, frenck commented
The installation pages have been fully re-designed. The change in this PR no longer applies.

2021-02-22 15:24 UTC, closed without merging