Add documentation for AEMET OpenData integration
home-assistant/home-assistant.github.io pull request #16173
Opened 2021-01-13 07:53 UTC by Noltari

## Proposed change
Add documentation for AEMET OpenData integration: https://github.com/home-assistant/core/pull/45074

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/45074
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-02-13 20:57 UTC, MartinHjelmare commented on source/_integrations/aemet.markdown
> +ha_release: 2021.2
```suggestion
ha_release: 2021.3
```

2021-02-13 20:57 UTC, MartinHjelmare commented on source/_integrations/aemet.markdown
> +| Mode                 | Forecast mode, `daily` for daily forecast up to 6 days or `hourly` for an hourly forecast up to 3 days. |
```suggestion
```

2021-02-13 20:57 UTC, MartinHjelmare commented on source/_integrations/aemet.markdown
> +The integration creates weather entity and also sensors for all available conditions.
```suggestion
The integration creates one weather entity per forecast mode and also sensors for all available conditions. There are two forecast modes, `daily` for daily forecast up to 6 days or `hourly` for an hourly forecast up to 3 days.
```

2021-02-13 20:57 UTC, MartinHjelmare commented on source/_integrations/aemet.markdown
> +For each condition `sensor` entity will be created with id:
```suggestion
For each condition a `sensor` entity will be created with id: 
```

2021-02-13 22:06 UTC, MartinHjelmare approved these changes, later dismissed
:+1:

2021-02-13 23:35 UTC, frenck requested changes
Thanks for the PR @Noltari!

A couple of small comments and suggestions, could you please take a look? Thanks! 👍

2021-02-13 23:35 UTC, frenck commented on source/_integrations/aemet.markdown
> +| Longitude            | Longitude for weather forecast and sensor
Use `%{ config_basic %}` for this instead.

2021-02-13 23:35 UTC, frenck commented on source/_integrations/aemet.markdown
> +The `aemet` weather platform uses [AEMET OpenData](https://opendata.aemet.es/) as a source for current meteorological data for your location. AEMET stands for `Agencia Estatal de Meteorología`, which
```suggestion
The AEMET weather platform uses [AEMET OpenData](https://opendata.aemet.es/) as a source for current meteorological data for your location. AEMET stands for "Agencia Estatal de Meteorología", which is the Spanish Meteorological Agency.
```

2021-02-13 23:35 UTC, frenck commented on source/_integrations/aemet.markdown
> +The AEMET OpenData service is completely free, but is limited to the Spanish territory.
```suggestion
You need an API key, which is free but requires a [registration](https://opendata.aemet.es/centrodedescargas/altaUsuario).
The AEMET OpenData service is completely free but is limited to the Spanish territory.
```

2021-02-13 23:35 UTC, frenck commented on source/_integrations/aemet.markdown
> +All conditions:
The `entity_id` is not guaranteed, we should therefore not list it as such.

```suggestion
For each condition, the following sensors are created:
```

2021-02-13 23:35 UTC, frenck commented on source/_integrations/aemet.markdown
> +| `condition`           | Current weather condition code.      |
Let's use normal names for the conditions.

2021-02-14 10:43 UTC, frenck commented on source/_integrations/aemet.markdown
> +| longitude | Longitude for weather forecast and sensor |
```suggestion
{% configuration_basic %}
API Key:
  description: "API Key from the website"
Name:
  description: "Name of the integration"
Latitude:
  description: "Latitude for weather forecast and sensor"
Longitude:
  description: "Longitude for weather forecast and sensor".
{% configuration_basic %}
```

2021-02-14 12:28 UTC, frenck approved these changes
Thanks @Noltari!

2021-02-14 12:28 UTC, merged