Add explanation of Accuweather API rate limit
home-assistant/home-assistant.github.io pull request #16198
Opened 2021-01-16 18:59 UTC by tels7ar

The accuweather api is extremely rate-limited for the free level.  Add an explanation so people aren't caught by surprise.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-01-16 18:59 UTC, homeassistant commented
Hi @tels7ar, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#16198).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-01-16 19:01 UTC, frenck requested changes
Small comment, other than that 👍

2021-01-16 19:01 UTC, frenck commented on source/_integrations/accuweather.markdown
> +</div>
Please combine it with the warning that is already there. We don't have to add a new warning box for this.

2021-01-25 14:20 UTC, homeassistant commented
Hi @tels7ar, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#16198).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-01-25 14:44 UTC, frenck approved these changes
Tweaked it myself. Thanks for the addition @tels7ar 👍

2021-01-25 14:45 UTC, merged