Document `buttons` action support for `entities` card
home-assistant/home-assistant.github.io pull request #16214
Opened 2021-01-17 19:36 UTC by spacegaier

## Proposed change
The `buttons` type in an `entities` card already support the same action handler logic as a `button`  row, but it was not mentioned here.

Also tried to align the full-stop logic. Only use it if the description actually has multiple sentences.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-01-18 13:56 UTC, frenck requested changes
There is a merge conflict.

2021-01-18 13:56 UTC, frenck commented on source/_lovelace/entities.markdown
> +  description: Button to turn on/off all entities
ideally, every line with more than 3 words, so end with a full stop.

Both documentation guides by Microsoft's & Google agree on that. So I would rather add it every, where, than remove it.

2021-01-21 18:50 UTC, spacegaier commented
> 
> 
> There is a merge conflict.

GitHub does not allow me to tackle the merge conflict since there are pending requested changes.

2021-01-23 13:30 UTC, frenck approved these changes

2021-01-23 13:30 UTC, merged