Add total energy, preheater and RMOT sensors to comfoconnect example
home-assistant/home-assistant.github.io pull request #16244
Opened 2021-01-20 23:35 UTC by chmielowiec

## Proposed change

Add all sensors to example configuration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/45373
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-01-21 09:10 UTC, michaelarnauts requested changes

2021-01-21 09:10 UTC, michaelarnauts commented on source/_integrations/comfoconnect.markdown
> +      - preheater_power_usage
Something minor, but could you add the new items in order (alphabetically) to the list? This makes it easier to look at the list to know what sensors are available.

2021-01-21 09:13 UTC, frenck requested changes
Agree, please sort the list 👍

2021-01-21 12:09 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-01-21 18:21 UTC, michaelarnauts approved these changes

2021-01-27 13:17 UTC, cgarwood approved these changes

2021-01-27 13:17 UTC, merged