Update tado.markdown
home-assistant/home-assistant.github.io pull request #16287
Opened 2021-01-23 19:55 UTC by north3221

Adding new service tado.set_climate_temperature_offset for pr: https://github.com/home-assistant/core/pull/45014

Also added an example for it

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-01-23 21:00 UTC, frenck requested changes

2021-01-23 21:00 UTC, frenck commented on source/_integrations/tado.markdown
> +| `entity_id`            | no       | String, Name of entity e.g., `climate.heating`                         |
It is registered using `async_register_entity_service`, so entity_id became optional.

```suggestion
| `entity_id`            | yes      | String, Name of entity, e.g., `climate.heating`                       |
```

2021-01-23 21:00 UTC, frenck commented on source/_integrations/tado.markdown
> +        {{ (states('sensor.tado_temperature')|float - states('sensor.temp_sensor_room')|float) > 0.5 }}
Can we make the template less long but using multi-line templates? So it comes readable for the user.

2021-01-23 21:01 UTC, frenck commented
Oh! And this needs to go into the `next` branch, as it relies on a next release.
Please change the target branch and git rebase if needed.

2021-01-24 00:54 UTC, north3221 commented
> Oh! And this needs to go into the `next` branch, as it relies on a next release.
> Please change the target branch and git rebase if needed.

Yeah that was an accident cause I didn't know what I was doing. I've changed it but cant figure out how to rebase...

2021-01-24 11:41 UTC, north3221 commented
Unless I am mistaken you cant rebase on github, so I'll close this PR and raise it again properly

2021-01-25 14:30 UTC, closed without merging