Update tado.markdown
home-assistant/home-assistant.github.io pull request #16297
Opened 2021-01-24 18:40 UTC by samnewman86

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-01-24 18:40 UTC, homeassistant commented
Hi @samnewman86, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#16297).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-01-24 18:45 UTC, samnewman86 commented
The documentation docs dont seem to provide a standard for deprecation?

2021-01-25 11:37 UTC, frenck requested changes
There are unrelate commits in your PR. Please clean it up so only the contents (your commits) are in this PR as a change.

2021-01-25 16:40 UTC, samnewman86 commented
> There are unrelate commits in your PR. Please clean it up so only the contents (your commits) are in this PR as a change.

Sorry, no idea how to do that

2021-01-25 16:51 UTC, frenck commented
You'll need to run a git rebase to put it on top of the next branch.

Could you also update the PR description to have a link to the upstream code PR that deprecates it in the code base?

Thanks 👍

2021-01-26 19:53 UTC, klaasnicolaas requested changes
This will fix the build error

2021-01-26 19:53 UTC, klaasnicolaas commented on source/_integrations/tado.markdown
> +Previously it was necessary to add your tado username and password to your `configuration.yaml` file, this is no longer necessary and should be removed.
```suggestion
Previously it was necessary to add your Tado username and password to your `configuration.yaml` file, this is no longer necessary and should be removed.
```

2021-01-26 21:23 UTC, samnewman86 reviewed
Thanks

2021-03-29 11:07 UTC, frenck commented on source/_integrations/tado.markdown
> +Previously it was necessary to add your Tado username and password to your `configuration.yaml` file, this is no longer necessary and should be removed.
This should not be documented. We document the current state of things; this specific log belong in the release notes.

2021-03-29 11:08 UTC, frenck commented
Closing this PR, as the added documentation should not be in our docs. Nevertheless, thanks for willing to contribute 👍

2021-03-29 11:08 UTC, closed without merging