Add 'set_switch_override' text.
home-assistant/home-assistant.github.io pull request #16314
Opened 2021-01-26 13:17 UTC by GeoffAtHome

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- [Link to parent pull request in the codebase: ](https://github.com/home-assistant/core/pull/45558)

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.

- [x ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-01-26 13:23 UTC, frenck requested changes

2021-01-26 13:23 UTC, frenck commented on source/_integrations/geniushub.markdown
> +type: string
This should not be formatted like this.

2021-01-26 14:30 UTC, GeoffAtHome commented on source/_integrations/geniushub.markdown
> +type: string
VS code is removing the leading/excess white space. I need to see how I can fix this.

2021-01-26 14:30 UTC, GeoffAtHome commented on source/_integrations/geniushub.markdown
> +type: string
Changed VS code setting.

2021-01-26 14:30 UTC, GeoffAtHome commented on source/_integrations/geniushub.markdown
> +type: string
OK.

2021-01-26 14:40 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-01-26 14:41 UTC, frenck requested changes
Oh, not approved. There is still an issue. The PR is targeting the `current` branch. However, since this documentation on a code change, it depends on a next release of Home Assistant.

Thus, this PR should be targeting the `next` branch. Please change the target branch of this PR and run a git rebase if needed.

2021-01-26 14:47 UTC, GeoffAtHome commented
Rebase still to be done.

2021-01-26 14:52 UTC, GeoffAtHome commented
Rebase to next done.

2021-01-26 14:56 UTC, GeoffAtHome commented
I think I have changed to  `home-assistant:next `.  If this is wrong I need assistance here as I am unsure what needs to be done.

2021-01-26 15:13 UTC, frenck commented
Yes, the target is adjusted, but your upstream is based on current, thus there are unrelated commits in your PR.

2021-01-26 18:10 UTC, GeoffAtHome commented
I ran:
```
git fetch upstream next  
git rebase upstream/next
git push origin --force-with-lease
git push origin --force
```

Do I need to do anything else?

2021-01-26 19:57 UTC, klaasnicolaas commented
Thought the rebase was resolved but still seeing unrelated commits in the pull request.

2021-01-26 20:49 UTC, frenck commented
@GeoffAtHome 

```bash
git rebase upstream/next YOUR_BRANCH~2
git log
git push --force
```

The git log is there for you to check if everything looks good now.

2021-01-27 12:42 UTC, GeoffAtHome commented
I tried:
git rebase upstream/next branch
git log

The log has so many entries I did not know what was good or not.

I delete the fork and tried again.
I think this is right now. The change is only add one line.

2021-01-27 12:45 UTC, GeoffAtHome commented
I am not sure why I now have an unknown repository.
GeoffAtHome wants to merge 4 commits into **home-assistant:next** from **unknown repository**

It may be simpler to delete this PR and start again. Let me know what you think.

2021-01-27 13:34 UTC, frenck commented
You deleted the fork, and therefore the reference of this PR.
This can only be fixed by creating a new PR, therefore, closing this one.

2021-01-27 13:34 UTC, closed without merging