Updated iCloud to support 2FA
home-assistant/home-assistant.github.io pull request #16375
Opened 2021-02-01 14:42 UTC by nzapponi

## Proposed change

Updated iCloud to support 2FA

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/45818

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-02-03 12:50 UTC, Quentame requested changes
There is some changes to make line 33 & 34

https://github.com/home-assistant/home-assistant.io/pull/16375/files#diff-5c201e0d7dd08874952681bc48ecbe9cd834dd6eb94fa290a1d2e5d1447d2687R32-R35

2021-02-03 18:13 UTC, Quentame approved these changes, later dismissed

2021-02-04 22:09 UTC, Quentame commented
I did not merge because I'm not sure of some English construction, otherwise I'm good.

2021-02-05 11:52 UTC, Quentame commented
As https://github.com/home-assistant/core/pull/45818 was merged with a fix https://github.com/home-assistant/core/releases/tag/2021.2.1 , this PR should now target `current` branch

2021-02-05 11:54 UTC, Quentame approved these changes

2021-02-05 11:55 UTC, frenck approved these changes

2021-02-05 11:55 UTC, merged