Remove nuimo
home-assistant/home-assistant.github.io pull request #16370
Opened 2021-01-31 20:50 UTC by rngtng

## Proposed change
Remove Nuimo Controller Documentation

As of https://github.com/home-assistant/core/pull/45600 Nuimo controller integration is deleted.

## Type of change
Deletion of existing documentation

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/45600
- Link to parent pull request in the Brands repository: -
- This PR fixes or closes issue: -

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-02-01 15:58 UTC, frenck requested changes
Please remove all references to the page as well, and add a redirect to the redirect file (more removed integrations can be found in there) to handle people still landing on this page.

2021-02-01 20:35 UTC, rngtng commented
@frenck done

2021-02-02 12:35 UTC, frenck requested changes

2021-02-02 12:35 UTC, frenck commented on source/_posts/2019-09-18-release-99.markdown
> +We also had some great drinks in the evenings with companies that integrate with Home Assistant. In this picture [Konnected.io](/integrations/konnected) and Senic
```suggestion
We also had some great drinks in the evenings with companies that integrate with Home Assistant. In this picture [Konnected.io](/integrations/konnected) and Senic.
```

2021-02-02 12:35 UTC, frenck commented on source/_posts/2017-05-06-zigbee-opencv-dlib.markdown
> +- Clean up requirements ([@andrey-git] - [#7391]) (nuimo_controller docs) ([sensor.dht docs]) ([sensor.thinkingcleaner docs]) ([switch.thinkingcleaner docs])
```suggestion
- Clean up requirements ([@andrey-git] - [#7391]) ([sensor.dht docs]) ([sensor.thinkingcleaner docs]) ([switch.thinkingcleaner docs])
```

2021-02-02 13:15 UTC, frenck approved these changes
Thanks, @rngtng 👍

2021-02-02 13:15 UTC, merged