Add config flow to philips_js
home-assistant/home-assistant.github.io pull request #16392
Opened 2021-02-02 22:01 UTC by elupus

## Proposed change

Adjust documentation for config flow change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/45784

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-02-11 20:49 UTC, frenck requested changes

2021-02-11 20:49 UTC, frenck commented on source/_integrations/philips_js.markdown
> +Alternatively a deprecated way to add your TV to your installationis via `configuration.yaml` file:
When an integration moves to a configuration flow, YAML configuration should be deprecated and thus removed from the documentation.

2021-02-12 01:30 UTC, elupus commented
I will update the documentation more linked to https://github.com/home-assistant/core/pull/46422 since it adds several new features and known issues.

2021-02-12 01:33 UTC, frenck commented
That is a different PR and needs its own docs PR, as there is no guarantee that PR is merged before the beta cut off. Please adjust this PR first.

2021-02-12 01:35 UTC, elupus commented
I've already done so. It just ends up rather sparse on info.

2021-02-12 01:37 UTC, frenck commented
LOL, I missed that, sorry (its getting late here, I need to get some sleep).

2021-02-12 08:27 UTC, frenck approved these changes
Thanks, @elupus 👍

2021-02-12 08:27 UTC, merged