Add Rituals Perfume Genie integration documentation
home-assistant/home-assistant.github.io pull request #16460
Opened 2021-02-08 18:47 UTC by milanmeu

## Proposed change

Add documentation for the Rituals Perfume Genie integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [core PR 46218](https://github.com/home-assistant/core/pull/46218)
- Link to parent pull request in the Brands repository: [brands PR 2243](https://github.com/home-assistant/brands/pull/2243)
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-02-11 21:53 UTC, frenck commented on source/_integrations/rituals_perfume_genie.markdown
> +The `Rituals Perfume Genie` integration allows you to control and monitor your Rituals perfume diffusers connected to your Rituals account. The integration is compatible with the first and second `2.
```suggestion
The Rituals Perfume Genie integration allows you to control and monitor your Rituals perfume diffusers connected to your Rituals account. The integration is compatible with the first and second `2.0` version.
```

2021-02-11 21:53 UTC, frenck commented on source/_integrations/rituals_perfume_genie.markdown
> +* Enter your Rituals credentials and click **SUBMIT**.
```suggestion
To add the Rituals Perfume Genie integration to your installation:

- Go to the Integrations menu: **Configuration** >> **Integrations** in the UI.
- Click the button with the `+` sign at the bottom right of the screen.
- Select **Rituals Perfume Genie** from the list of integrations.
- Enter your Rituals credentials and click **SUBMIT**.
```

2021-02-11 21:54 UTC, frenck approved these changes, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2021-02-20 21:56 UTC, bdraco commented on source/_integrations/rituals_perfume_genie.markdown
> +- Enter your Rituals credentials and click **SUBMIT**.
```suggestion
{% include integrations/config_flow.md %}
```

Will need to be rebased as well

2021-02-22 13:35 UTC, frenck requested changes
@milanmeu Seems like your rebase resulted in a merge? Please git rebase just your commits in order to get rid of all the unrelated commits in this PR.

2021-02-22 15:55 UTC, milanmeu commented
I fixed the rebase. My commits doubled so I had to squash them.

2021-02-22 16:05 UTC, frenck commented on source/_integrations/rituals_perfume_genie.markdown
> +The Rituals Perfume Genie integration allows you to control and monitor your Rituals perfume diffusers connected to your Rituals account. The integration is compatible with the first and second `2.0`
```suggestion
The Rituals Perfume Genie integration allows you to control and monitor your Rituals perfume diffusers connected to your Rituals account. The integration is compatible with the first and second `2.0` versions.
```

2021-02-22 16:06 UTC, frenck approved these changes
Thanks, @milanmeu 👍

2021-02-22 16:15 UTC, merged