Add Xiaomi Miio Plug config flow
home-assistant/home-assistant.github.io pull request #16539
Opened 2021-02-13 10:22 UTC by starkillerOG

## Proposed change

Add config flow to xiaomi miio plug platform.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/46179
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-02-15 12:47 UTC, frenck requested changes

2021-02-15 12:47 UTC, frenck commented on source/_integrations/xiaomi_miio.markdown
> +### Configuration flow setup
```suggestion
### Configuration
```

2021-02-15 12:47 UTC, frenck commented on source/_integrations/xiaomi_miio.markdown
> +To add a plug to your installation, click Configuration in the sidebar, then click Integrations and then click the + icon in the lower right and find xiaomi_miio. Select the option “Connect to a othe
```suggestion
To add a plug to your installation, click Configuration in the sidebar, then click Integrations and then click the + icon in the lower right and find xiaomi_miio. Select the option “Connect to an other Xiaomi Miio device” and click submit. You will then be presented with a form in which you will need to fill in the “IP address” and 32 characters “token”. Optionally, you can specify a different name for the plug. After you click submit, you will have the opportunity to select the area that your devices are located.
```

2021-02-15 17:29 UTC, frenck approved these changes, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-02-17 09:14 UTC, starkillerOG commented
@frenck Sorry, I corrected some steps of the config flow that were removed.
I just realized it now.
Could you review again?

2021-02-22 13:38 UTC, frenck approved these changes
For now, let's keep the configuration like this. When all is migrated to a config flow, we should look into centralizing the configuration part in a single chapter.

2021-02-22 13:39 UTC, merged