Hive UI Docs update
home-assistant/home-assistant.github.io pull request #16568
Opened 2021-02-14 13:12 UTC by KJonline

## Proposed change

Update Hive documentation to support hive being setup via the UI.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-02-22 14:52 UTC, frenck requested changes

2021-02-22 14:52 UTC, frenck commented on source/_integrations/hive.markdown
> +### Configuration via YAML
When an integration moves to the UI, the YAML configuration is deprecated and should thus be removed from the documentation.

2021-02-22 14:52 UTC, frenck commented on source/_integrations/hive.markdown
> +If you have 2 factor authentication setup on your Hive account, a following dialog will be presented asking for  your code.
This can all be replaced by a single:

`{% include integrations/config_flow.md %}`

2021-02-22 14:52 UTC, frenck commented on source/_integrations/hive.markdown
> +This `hive` integration uses the same username and password you use on the [Hive website](https://my.hivehome.com) to configure it within Home Assistant. Once configured Home Assisatnt will detect an
It is generally wise to start with an introduction. If one gets to this page, the first thing they read about this integration is something about a Hive username/password. But what is Hive?

```suggestion
This Hive integration uses the same username and password you use on the [Hive website](https://my.hivehome.com) to configure it within Home Assistant. Once configured Home Assistant will detect and add all Hive devices, including support for multi-zone heating.
```

2021-02-22 19:54 UTC, KJonline commented
Hi @frenck I have rebased the branch from the next branch but the rebase doesn't seem to be getting rid of the tainted commits. I have also looked at creating a new branch and doing a new PR that also shows the tainted commits also. not sure what to do from here.

2021-02-22 20:08 UTC, KJonline commented
It seems to have resolved itself.

2021-03-04 10:50 UTC, frenck requested changes

2021-03-04 10:50 UTC, frenck commented on source/_integrations/hive.markdown
> +_YAML configurations are no longer supported, exisitng configurations will be imported and can then be removed._
This note is not needed, that will be added to the release notes.

```suggestion
```

2021-03-04 20:44 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-03-15 14:35 UTC, merged