Update operating_system.md
home-assistant/home-assistant.github.io pull request #16805
Opened 2021-03-02 11:05 UTC by lahhrs

Added a installtime (15-20). If you are new an don't know what happens "a few minutes" you will think about 3 to 5 minutes and you may exit because you think it dosen't work.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-03-02 11:05 UTC, homeassistant commented
Hi @lahhrs, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#16805).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-03-02 11:08 UTC, frenck requested changes

2021-03-02 11:08 UTC, frenck commented on source/_includes/installation/operating_system.md
> +4. Within 15-20 minutes you will be able to reach Home Assistant on <a href="http://homeassistant.local:8123" target="_blank">homeassistant.local:8123</a>. If you are running an older Windows version
This is incorrect. There is no installation time to bring up the interface. A soft landing is build into the image flashed, that shows installation progress and some additional guidance while waiting.

2021-03-16 15:09 UTC, frenck commented
The only change in this PR is incorrect. Going to close it.

2021-03-16 15:09 UTC, closed without merging