Quick howto to flash Hue devices via OTA folder.
home-assistant/home-assistant.github.io pull request #16975
Opened 2021-03-12 23:17 UTC by systemcrash

Quick howto to flash Hue devices via OTA folder. Clarify that other OEMs are possible, and people can throw out their Hue bridges. 

I followed the "edit" link on the doc webpage, so I assume the current branch of `current` is OK. 

## Proposed change

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-03-15 13:16 UTC, frenck requested changes
Please make sure the documentation build passes and the YAML comply with our YAML style guide: 

<https://developers.home-assistant.io/docs/documenting/yaml-style-guide>

Thanks! 👍

2021-03-15 14:15 UTC, systemcrash commented
> Please make sure the documentation build passes and the YAML comply with our YAML style guide:
> 
> https://developers.home-assistant.io/docs/documenting/yaml-style-guide
> 
> Thanks! 👍

Sure -  are you referring to the script that must be run? If it is in YAML format, then it is compliant. A copy-paste into Dev-Services works fine - that is where the text was tested. It is not a config change. 

Or was there something else that is being rejected? I also don't understand the lint warning about language: `191:1-203:4  warning  Missing code language flag  fenced-code-flag  remark-lint`

2021-03-15 14:24 UTC, systemcrash commented
Ah, well, I wasn't sure whether those scripts are yaml - but I've tagged the code-block as yaml to keep the linter happy.

2021-03-15 15:04 UTC, frenck commented
>  If it is in YAML format, then it is compliant. A copy-paste into Dev-Services works fine - that is where the text was tested. It is not a config change.

Its not about it validates YAML, it how we want YAML to be styled across our documentation. Please read the supplied link to our developer documentation. The current YAML example does not match our style guide.

2021-03-16 16:17 UTC, systemcrash commented
ping

2021-03-16 16:42 UTC, frenck commented
pong, but really, please don't.

2021-04-04 17:01 UTC, frenck approved these changes
Thanks, @systemcrash 👍

2021-04-04 17:01 UTC, merged