Xiaomi Miio: add EU gateway support
home-assistant/home-assistant.github.io pull request #17022
Opened 2021-03-16 08:44 UTC by starkillerOG

## Proposed change

Add EU gateway support documentation

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/47955
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-04-15 22:01 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-06-14 22:07 UTC, frenck commented
We should update these docs to clean up all the token retrieval stuff.

2021-06-15 14:20 UTC, starkillerOG commented
@frenck I cleaned up the docs a bit, could you have a look?

2021-06-27 18:12 UTC, frenck requested changes

2021-06-27 18:12 UTC, frenck commented on source/_integrations/xiaomi_miio.markdown
> +However when setting up a device manually the token can be retrieved in one of the following ways.
```suggestion
## Retrieving the Access Token

Not recommended, please specify the cloud credentials during the config flow for easier setup.
However, when setting up a device manually the token can be retrieved in one of the following ways.
```

2021-06-27 18:12 UTC, frenck commented on source/_integrations/xiaomi_miio.markdown
> +Alternate method to get all yours devices tokens in one run. Please follow this [instruction](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor).
We should get rid of this list. Maybe we can add links to e.g., the cloud token extractor? And thinks like that?

2021-06-28 12:45 UTC, frenck approved these changes

2021-06-28 12:45 UTC, merged