System Bridge Integration
home-assistant/home-assistant.github.io pull request #17077
Opened 2021-03-20 16:40 UTC by timmo001

## Proposed change

Adds documentation for initial System Bridge integration.

## Type of change

- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/48156
- Link to parent pull request in the Brands repository: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-04-04 16:58 UTC, frenck requested changes

2021-04-04 16:58 UTC, frenck commented on source/_integrations/system_bridge.markdown
> +[![Open your Home Assistant instance and show your service developer tools with a specific service selected.](https://my.home-assistant.io/badges/developer_call_service.svg)](https://my.home-assistan
```suggestion
{% my developer_call_service service="system_bridge.open" title="Open your Home Assistant instance and show your service developer tools with a specific service selected." %}
```

2021-04-04 16:58 UTC, frenck commented on source/_integrations/system_bridge.markdown
> +  path: 'C:\image.jpg'
```suggestion
service: system_bridge.open
data:
  bridge: "device"
  path: "C:\image.jpg"
```

2021-04-04 16:58 UTC, frenck commented on source/_integrations/system_bridge.markdown
> +  path: 'https://home-assistant.io'
```suggestion
service: system_bridge.open
data:
  bridge: "device"
  path: "https://home-assistant.io"
```

2021-04-04 16:58 UTC, frenck commented on source/_integrations/system_bridge.markdown
> +  path: 'steam://rungameid/814380'
```suggestion
service: system_bridge.open
data:
  bridge: "device"
  path: "steam://rungameid/814380"
```

2021-04-04 16:58 UTC, frenck commented on source/_integrations/system_bridge.markdown
> +[![Open your Home Assistant instance and show your service developer tools with a specific service selected.](https://my.home-assistant.io/badges/developer_call_service.svg)](https://my.home-assistan
```suggestion
{% my developer_call_service service="system_bridge.send_command" title="Open your Home Assistant instance and show your service developer tools with a specific service selected." %}
```

2021-04-04 16:58 UTC, frenck commented on source/_integrations/system_bridge.markdown
> +### Send Command
```suggestion
### Service `system_bridge.send_command`
```

2021-04-04 16:58 UTC, frenck commented on source/_integrations/system_bridge.markdown
> +### Open Path/URL
```suggestion
### Service `system_bridge.open`
```

2021-05-05 23:35 UTC, MartinHjelmare commented on source/_integrations/system_bridge.markdown
> +  - sensor
```suggestion
  - binary_sensor
  - sensor
```

2021-05-05 23:35 UTC, MartinHjelmare commented on source/_integrations/system_bridge.markdown
> +ha_release: 2021.4
```suggestion
ha_release: 2021.6
```

2021-05-06 07:55 UTC, frenck approved these changes
Thanks, @timmo001 👍

2021-05-06 07:56 UTC, merged