Improve Docker and Kubernetes support for KNX
home-assistant/home-assistant.github.io pull request #17095
Opened 2021-03-22 15:36 UTC by plomosits

## Proposed change

Document new config parameter for pull request https://github.com/home-assistant/core/pull/48065

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/48065
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-03-22 16:02 UTC, farmio requested changes
This is targeted against the wrong branch. `next` would be right imho.

2021-03-22 16:02 UTC, farmio commented on source/_integrations/knx.markdown
> +  default: true
default is `false`

2021-03-22 16:06 UTC, plomosits commented on source/_integrations/knx.markdown
> +  default: true
You are right.

2021-03-22 16:09 UTC, frenck requested changes
There are unrelated commits in this PR, due to the change of target branch. Please git rebase.

2021-03-22 17:57 UTC, frenck commented
Seems like you performed a merge instead of a rebase, as there are now more unrelated commits. Please make sure you perform a rebase.

2021-03-22 21:24 UTC, farmio commented
Hey! 
When you're stuck in a rebase/merge dilemma here (which happens to me more often than I'd like to admit) you could probably just do
```shell
# update upstream
git fetch upstream
# discard all changes, clear the branch, set it to the target
git reset --hard upstream/next
# apply your first commit
git cherry-pick e077e98
# apply the second too
git cherry-pick a963d75
# push it
git push --force
```
good luck!

2021-03-22 21:37 UTC, farmio approved these changes

2021-03-29 08:16 UTC, frenck approved these changes

2021-03-29 08:17 UTC, frenck commented
Thanks, @plomosits 👍

2021-03-29 08:17 UTC, merged