Update binary sensor names
home-assistant/home-assistant.github.io pull request #17107
Opened 2021-03-23 20:43 UTC by Scott1009

Change the name of the binary sensor suffix from 'is_watering' to 'watering'.  'Status' sensor is now 'my_controller_status'

## Proposed change

Updating the names of generated sensors.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

No additional information, naked pull request.

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-03-23 20:43 UTC, homeassistant commented
Hi @Scott1009, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#17107).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-03-29 11:41 UTC, frenck requested changes

2021-03-29 11:41 UTC, frenck commented on source/_integrations/hydrawise.markdown
> +    my_controller_status:
This seems incorrect. According to the code it validates a list of binary sensors here:

<https://github.com/home-assistant/core/blob/6023105c6a3b69ffb2338c494246802c086aaee4/homeassistant/components/hydrawise/binary_sensor.py#L17>

While the list itself is here:

```py
BINARY_SENSORS = ["is_watering", "status"]
```

<https://github.com/home-assistant/core/blob/6023105c6a3b69ffb2338c494246802c086aaee4/homeassistant/components/hydrawise/__init__.py#L57>

2021-04-02 20:05 UTC, Scott1009 commented
I did not have the most up-to-date version of HASS installed, so this is a mistake.  I apologize for wasting your time.

2021-04-02 20:05 UTC, closed without merging

2021-04-04 09:07 UTC, frenck commented
Don't worry! Things happen 👍