clarify how to reboot roomba to generate auto-discovery
home-assistant/home-assistant.github.io pull request #17111
Opened 2021-03-23 23:47 UTC by scyto

## Proposed change

Without this key piece of info most people will never experience DHCP auto discovery of their roomba.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/47696
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-03-23 23:49 UTC, scyto commented
Should I also add a note that we would like more name / mac address combinations - or just wait until folks log their roomba didn't auto discover via dhcp?

2021-03-24 23:50 UTC, frenck requested changes

2021-03-24 23:50 UTC, frenck commented on source/_integrations/roomba.markdown
> +This platform has been tested and is confirmed to be working with the iRobot Roomba s9+, Roomba 980, Roomba 960, Roomba 890, and Braava jet m6 models, but should also work fine with any Wi-Fi enabled
```suggestion
This integration has been tested and confirmed to be working with the iRobot Roomba s9+, Roomba 980, Roomba 960, Roomba 890, and Braava jet m6 models, but should also work fine with any Wi-Fi enabled Roomba or Braava like the 690. For auto-discovery, you will need to initiate a Roomba reboot. For example, by holding the clean button for up to 20 seconds on an i7 or 980. [More information about rebooting your robot](https://homesupport.irobot.com/app/answers/detail/a_id/9087/~/rebooting-or-resetting-your-robot).
```

2021-03-25 08:03 UTC, frenck approved these changes
I think this is fine to merge into the current documentation at this point.

Thanks for the PRs @scyto 👍

2021-03-25 08:03 UTC, merged