Update philips_js.markdown
home-assistant/home-assistant.github.io pull request #17158
Opened 2021-03-28 11:11 UTC by snis

Minor clarifications

## Proposed change

Some minor clarifications, I know thaat this integration is undergoing heavy development.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-03-28 11:11 UTC, homeassistant commented
Hi @snis, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#17158).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-03-29 07:11 UTC, frenck requested changes

2021-03-29 07:11 UTC, frenck commented on source/_integrations/philips_js.markdown
> +If your TV respond to http://<ip.of.tv>:1925/system then you are good to go. In the response you should also be able to see which version of the API ("api_version":{"Major":6...) you should use in th
```suggestion
If your TV responds to `http://IP_ADDRESS_OF_TV:1925/system` then this integration can be used. In the response, you should also be able to see the version of the API the TV uses (`"api_version":{"Major":6...`).
```

2021-03-29 07:11 UTC, frenck commented on source/_integrations/philips_js.markdown
> +Also note that version 6 of the API needs to be authenticated by a PIN code displayed on your TV.
```suggestion
Also, note that version 6 of the API needs to be authenticated by a PIN code displayed on your TV.
```

2021-03-29 11:26 UTC, frenck approved these changes
Thanks, @snis 👍

2021-03-29 11:26 UTC, merged