Update mqtt.markdown
home-assistant/home-assistant.github.io pull request #17227
Opened 2021-04-01 15:01 UTC by zraken

When I followed the instructions it made it seem like I can configure host/port with GUI and then add the TLS options via configuration file and that did not work. When there is any GUI configuration the mqtt configuration in the yaml file is ignored. This is not obvious, hopefully the proposed addition to help documentation will be useful.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-04-01 15:01 UTC, homeassistant commented
Hi @zraken, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#17227).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-04-01 15:07 UTC, frenck requested changes

2021-04-01 15:07 UTC, frenck commented on source/_integrations/mqtt.markdown
> +Manual configuration is required when conencting to a broker over TLS.
```suggestion

Manual configuration is required when connecting to a broker over TLS.
```

2021-04-01 15:07 UTC, frenck commented on source/_integrations/mqtt.markdown
> +# Example configuration.yaml entry for connecting over TLS without host name verification
```suggestion
# Example configuration.yaml entry
```

2021-04-01 15:07 UTC, frenck commented on source/_integrations/mqtt.markdown
> +  username: MQTT_USERNAME
```suggestion
  certificate: "PATH_TO_CA.crt"
  broker: "IP_ADDRESS_BROKER"
  port: 8883
  username: "MQTT_USERNAME"
```

2021-04-01 15:07 UTC, frenck commented on source/_integrations/mqtt.markdown
> +  tls_insecure: true
We should never recommend or display a copy and paste example that disables certificate verification.

```suggestion
```

2021-04-01 15:07 UTC, frenck commented on source/_integrations/mqtt.markdown
> +
```suggestion
```

2021-04-01 15:10 UTC, zraken reviewed
Accepted suggested changes.

2021-04-04 20:15 UTC, frenck approved these changes
Thanks, @zraken 👍

2021-04-04 20:15 UTC, merged