Homepilot
home-assistant/home-assistant.github.io pull request #17248
Opened 2021-04-03 08:28 UTC by Nico0302

## Proposed change

This pull request adds the documentation for a new integration supporting [Rademacher HomePilot](https://www.rademacher.de/smart-home/produkte/homepilot) devices.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/2244
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-04-03 08:28 UTC, homeassistant commented
Hi @Nico0302, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#17248).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-04-04 10:35 UTC, frenck requested changes

2021-04-04 10:35 UTC, frenck commented on source/_integrations/homepilot.markdown
> +- Click on **SUBMIT** to complete the setup.
```suggestion
{% include integrations/config_flow.md %}
```

2021-04-04 10:35 UTC, frenck commented on source/_integrations/homepilot.markdown
> +The [pyhomepilot library](https://github.com/Nico0302/pyhomepilot) is used for communicating.
The underlying does not add anything for the end-user and should not be part of the user documentation.

```suggestion
```

2021-04-04 17:32 UTC, frenck commented
```
Could not locate the included file 'integrations/config_flow.md' in any of ["/opt/build/repo/source/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /opt/build/repo/source/_integrations/homepilot.markdown
```

This indicates your base branch is out of date. Please perform a git rebase on the latest master to be up to date with upstream next.

2021-10-22 11:10 UTC, frenck commented
Closing PR as the parent PR has been closed.

2021-10-22 11:10 UTC, closed without merging