Added address info for modbus.binary_sensor
home-assistant/home-assistant.github.io pull request #17340
Opened 2021-04-08 12:17 UTC by dontbug

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-04-08 12:17 UTC, homeassistant commented
Hi @dontbug, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#17340).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-04-08 12:49 UTC, dontbug commented
> Hi @dontbug,
> 
> It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant/home-assistant.io#17340).
> 
> Once you do that we will be able to review and accept this pull request.
> 
> Thanks!

done

2021-04-08 12:49 UTC, frenck requested changes

2021-04-08 12:49 UTC, frenck commented on source/_integrations/modbus.markdown
> +      required: false
This seems to be required?

```py

BINARY_SENSOR_SCHEMA = BASE_COMPONENT_SCHEMA.extend(
    {
        vol.Required(CONF_ADDRESS): cv.positive_int,
        vol.Optional(CONF_DEVICE_CLASS): BINARY_SENSOR_DEVICE_CLASSES_SCHEMA,
        vol.Optional(CONF_INPUT_TYPE, default=CALL_TYPE_COIL): vol.In(
            [CALL_TYPE_COIL, CALL_TYPE_DISCRETE]
        ),
    }
)
```

2021-04-08 13:01 UTC, dontbug commented on source/_integrations/modbus.markdown
> +      required: false
yes. Thanks )). sorry

2021-04-15 10:16 UTC, frenck approved these changes
Thanks, @dontbug 👍

2021-04-15 10:16 UTC, merged