Added Mutesync
home-assistant/home-assistant.github.io pull request #17593
Opened 2021-04-25 20:36 UTC by currentoor

## Proposed change

Added docs for new Mutesync integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-04-25 23:43 UTC, klaasnicolaas requested changes, later dismissed

2021-04-25 23:43 UTC, klaasnicolaas commented on source/_integrations/mutesync.markdown
> +integration will be available.
```suggestion
{% include integrations/config_flow.md %}
```

2021-04-27 00:15 UTC, balloob commented on source/_integrations/mutesync.markdown
> +ha_release: 0.79 # TODO which one?
```suggestion
ha_release: 2021.5
```

2021-04-27 00:16 UTC, balloob commented on source/_integrations/mutesync.markdown
> +  - Binary Sensor
```suggestion
  - Presence Detection
```

2021-04-27 00:16 UTC, balloob commented on source/_integrations/mutesync.markdown
> +ha_ssdp: true
```suggestion
```

2021-04-27 14:59 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-04-27 20:46 UTC, merged