Update shelly.markdown
home-assistant/home-assistant.github.io pull request #17626
Opened 2021-04-28 09:27 UTC by ronschaeffer

It is not obvious that devices such as the Shelly Button1 use events rather than entities to track button presses. This is a clarification as well as a description of how to find event data.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-04-28 10:09 UTC, frenck requested changes
Just wondering, why don't we point to device automation? Those are created to abstract this all away, right?

2021-04-28 10:09 UTC, frenck commented on source/_integrations/shelly.markdown
> +You can subscribe to the `shelly.click` event type in [Developer Tools/Events](https://www.home-assistant.io/docs/tools/dev-tools/) in order to examine the event data JSON for the correct parameters
```suggestion
You can subscribe to the `shelly.click` event type in [Developer Tools/Events](/docs/tools/dev-tools/) in order to examine the event data JSON for the correct parameters to use in your automations. For example, `shelly.click` returns event data JSON similar to the following when you press the Shelly Button1.
```

2021-04-28 11:32 UTC, ronschaeffer commented
Good point. Is there a preferred way to show automations created with the UI in these docs? If I put in just the YAML, I think it could be confusing. The device automation uses the device ID e09c64a22553484d804353ef97a6fcd6 for my Shelly Button1, which is not at all obvious.

2021-05-20 13:49 UTC, frenck commented on source/_integrations/shelly.markdown
> +You can also create automations using YAML, for example:
```suggestion
### Automations

The simplest way to create automations is to use the Home Assistant automation editor. For example, to set an automation triggered by a double press of a particular Shelly Button1:

1. In the Triggers section of the automation, set Trigger Type to `Device`.
2. In the Device dropdown menu. find the Shelly Button1.
3. In the Trigger dropdown menu, select `Button double clicked`.
4. Set any conditions and actions to complete your automation.

You can also create automations using YAML, for example:

```

2021-05-20 14:01 UTC, frenck approved these changes
Nice, @ronschaeffer! 👍 

Well done!

../Frenck

2021-05-20 14:01 UTC, merged