Add description of verify for modbus switch.
home-assistant/home-assistant.github.io pull request #17709
Opened 2021-05-06 06:22 UTC by janiversen

## Proposed change

Describe the change to "verify:" in "switch:".

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
https://github.com/home-assistant/core/pull/50117
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-05-06 13:56 UTC, frenck requested changes

2021-05-06 13:56 UTC, frenck commented on source/_integrations/modbus.markdown
> +      description: read from modbus device to verify switch. If used without attributes it used the toogle register configuration. If omitted no verify is done, but the state of the switch is set wit
```suggestion
      description: read from modbus device to verify switch. If used without attributes it used the toggle register configuration. If omitted no verify is done, but the state of the switch is set with each toggle.
```

2021-05-06 14:18 UTC, janiversen commented on source/_integrations/modbus.markdown
> +      description: read from modbus device to verify switch. If used without attributes it used the toogle register configuration. If omitted no verify is done, but the state of the switch is set wit
Thanks for correcting my english 👍

2021-05-06 16:10 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-05-06 20:21 UTC, janiversen commented
@frenck am I correct in assuming “next” is always the next release for now 2021.6 and never patch releases ?
If I am correct how is the it managed in the time where we prepare a new release...eg. I submit a PR for next 1/5 but it is for 2021.6 and not 2021.5.

I apologize for being curious, but the more I understand the better I can help.

2021-05-06 20:22 UTC, janiversen commented
Ups pressed the wrong button.

2021-05-07 20:14 UTC, MartinHjelmare commented on source/_integrations/modbus.markdown
> +      description: read from modbus device to verify switch. If used without attributes it used the toggle register configuration. If omitted no verify is done, but the state of the switch is set wit
```suggestion
      description: Read from modbus device to verify switch. If used without attributes it uses the toggle register configuration. If omitted no verification is done, but the state of the switch is set with each toggle.
```

2021-05-09 00:35 UTC, frenck approved these changes

2021-05-09 00:36 UTC, frenck commented
> @frenck am I correct in assuming “next” is always the next release for now 2021.6 and never patch releases ?

`next` = for the next major release (2021.6 at the time of writing).
`current` = for the current release (2021.5.x at the time of writing).

2021-05-09 19:08 UTC, merged