Encourage users to configure a prometheus metric namespace
home-assistant/home-assistant.github.io pull request #17722
Opened 2021-05-06 12:03 UTC by knyar

## Proposed change

Default empty namespace makes it harder to distinguish Home Assistant metrics from other metrics reported to the same Prometheus server.

Setting up a non-empty namespace as the default will break metric continuity for most users, which will be very disruptive. However, encouraging users to configure a non-empty namespace will make experience better for new users.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-05-06 12:04 UTC, knyar commented
cc  @mweinelt

2021-05-06 12:08 UTC, mweinelt commented
Agreed, the only thing I have configured for prometheus is the namespace, as it keeps things easily findable and prevents unneccesary cluttering of the prometheus search view.

2021-05-06 12:09 UTC, mweinelt approved these changes

2021-05-09 19:42 UTC, frenck requested changes

2021-05-09 19:42 UTC, frenck commented on source/_integrations/prometheus.markdown
> +  namespace: hass
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample.

I this should have a sane default, I suggest we adjust the integration for this (although that will be quite a breaking change).

Alternatively, a more extensive example can be defined below.

2021-05-10 11:19 UTC, knyar commented
> I this should have a sane default, I suggest we adjust the integration for this (although that will be quite a breaking change).

Sounds good! This was actually what @mweinelt originally proposed in https://github.com/home-assistant/architecture/issues/391#issuecomment-657249045.

I will prepare a separate PR to introduce a default namespace (or combine it with https://github.com/home-assistant/core/pull/50156 that has a few other naming changes).

2021-05-10 11:19 UTC, closed without merging

2021-05-10 12:02 UTC, frenck commented
I really think a separate example might be better, consider the breaking nature

2021-05-10 21:32 UTC, knyar commented
We already have a [full example](https://www.home-assistant.io/integrations/prometheus/#full-example) documented that covers `namespace`, but I think most users close the page before reaching that.