Geocaching
home-assistant/home-assistant.github.io pull request #17756
Opened 2021-05-08 19:42 UTC by Sholofly

## Proposed change

Adds documentation for the new Geocaching integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [X] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [#50284](https://github.com/home-assistant/core/pull/50284)
- Link to parent pull request in the Brands repository: [#2555](https://github.com/home-assistant/brands/pull/2555)
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-05-09 09:43 UTC, frenck requested changes
There are unrelated commits in this PR. Probably caused by basing this PR from the `current` branch (instead of the `next`). Please perform a `git rebase` onto the `next` branch to clean this up.

2021-05-09 11:58 UTC, Sholofly commented
@frenck Check! Thanks for your help!

2021-05-09 12:20 UTC, klaasnicolaas requested changes

2021-05-09 12:20 UTC, klaasnicolaas commented on source/_integrations/geocaching.markdown
> +
```suggestion
{% include integrations/config_flow.md %}
```

2021-05-09 13:44 UTC, frenck requested changes

2021-05-09 13:44 UTC, frenck commented on source/_integrations/geocaching.markdown
> +## Sensors
Adding a bit of body:

```suggestion
Geocaching is a real-world, outdoor adventure that is happening all the time, all around the world. To play, participants use the Geocaching app and/or a GPS device to navigate to cleverly hidden containers called geocaches.

The Geocaching integration in Home Assistant pulls data from your [Geocaching.com](https://www.geocaching.com/) account.

{% include integrations/config_flow.md %}

## Sensors
```

2021-05-09 14:41 UTC, Sholofly commented
@frenck & @klaasnicolaas, thanks!

2021-05-09 14:53 UTC, frenck commented
Rebased onto the upstream `next` to fix the build issue.

2021-05-09 14:53 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2021-05-09 20:29 UTC, frenck approved these changes

2022-05-12 10:14 UTC, frenck commented
@Sholofly It seems like the source branch for this PR is missing, thus this PR cannot be adjusted anymore. 

Can you restore the source branch?

2022-05-12 21:59 UTC, Sholofly commented
I've created a new PR (#22728 ) because I accidentally removed the original fork and wasn't able to restore it.

2022-05-12 21:59 UTC, closed without merging