Update QNAP integration
home-assistant/home-assistant.github.io pull request #17780
Opened 2021-05-10 16:33 UTC by Cyr-ius

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [#50302](https://github.com/home-assistant/core/pull/50302)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-07-15 20:45 UTC, minke890 approved these changes

2021-07-16 07:16 UTC, frenck requested changes

2021-07-16 07:16 UTC, frenck commented on source/_integrations/qnap.markdown
>  This `qnap` sensor allows getting various statistics from your [QNAP NAS](https://www.qnap.com/en-us/).
```suggestion
The QNAP integration allows getting various statistics from your [QNAP NAS](https://www.qnap.com/en-us/).
```

2021-07-16 07:16 UTC, frenck commented on source/_integrations/qnap.markdown
>  ha_domain: qnap
- Missing `ha_config_flow`.

Does it have discovery now as well? In that case, that needs to be added as well.

2021-07-16 07:16 UTC, frenck commented on source/_integrations/qnap.markdown
> +- networks uplink : bandwidth, status
```suggestion
Sensors:

- System: status, system temperature
- CPU: usage, temperature
- Memory: usage, free, used, total
- Volume: usage, used
- Folders: usage, used
- Drives: smart status, usage
- Network: bandwidth, status
```

2021-07-16 07:16 UTC, frenck commented on source/_integrations/qnap.markdown
>  ### SSL and Self-signed certificates
This section needs adjustment as well, as it references to YAML configuration that has been removed.

2022-03-14 18:40 UTC, frenck commented
Closing PR as the parent PR has been closed.

2022-03-14 18:40 UTC, closed without merging