Update honeywell documentation
home-assistant/home-assistant.github.io pull request #17814
Opened 2021-05-12 23:50 UTC by rdfurman

## Proposed change

I have converted the Honeywell Total Connect Comfort (US) climate platform into a full integration with climate and sensor devices. This is because the Honeywell TCC (US) system actually supports additional sensors (like outdoor sensors). This PR is to update the documentation on home-assistant.io to reflect the changes I made to the integration (separate PR to follow).

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: <TODO>

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-05-12 23:50 UTC, homeassistant commented
Hi @rdfurman, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#17814).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-05-13 00:11 UTC, rdfurman commented
Added link to integration change PR.

2021-05-15 01:43 UTC, rdfurman commented
The new look:
![image](https://user-images.githubusercontent.com/2547448/118344660-9c26c480-b4ec-11eb-8e8a-5704516683c8.png)

2021-05-17 08:03 UTC, frenck requested changes

2021-05-17 08:03 UTC, frenck commented on source/_integrations/honeywell.markdown
> +The `honeywell` integration integrates Home Assistant with _US-based_ [Honeywell Total Connect Comfort (TCC)](https://mytotalconnectcomfort.com/portal/) climate systems.
```suggestion
The Honeywell integration integrates Home Assistant with _US-based_ [Honeywell Total Connect Comfort (TCC)](https://mytotalconnectcomfort.com/portal/) climate systems.
```

2021-05-17 08:03 UTC, frenck commented on source/_integrations/honeywell.markdown
> +## Configuration
This whole section, including all configuration variables can be removed as integration using the configuration flow, should deprecated YAML support.

2021-05-17 08:04 UTC, frenck commented on source/_integrations/honeywell.markdown
> +  - Sensor
```suggestion
```

2021-05-17 08:04 UTC, frenck commented on source/_integrations/honeywell.markdown
> +  - sensor
```suggestion
```

2021-05-17 14:04 UTC, rdfurman commented
![new-honeywell-docs](https://user-images.githubusercontent.com/2547448/118501917-706f2e80-b6e6-11eb-872c-57a77ef314c3.png)

2021-05-17 14:14 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-07-19 19:47 UTC, merged