Rework modbus documentation.
home-assistant/home-assistant.github.io pull request #17874
Opened 2021-05-18 14:30 UTC by janiversen

## Proposed change

The modbus documentation had become a bit "clouded" and information was not logically grouped. This PR tries to make a more logical view of how the configuration works, as well as making it easier to use the index.

It is based on next instead of current, due to the pending changes (2021.6) which are on next.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

I am not a native English speaker so suggestions to correct the wording will be accepted immediately.

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-05-18 15:25 UTC, janiversen commented
It tells me line 8 is wrong, but I did not touch the first lines at all, I am confused.

2021-05-19 08:26 UTC, janiversen commented
@frenck Can I politely ask for advice...the build tell I have an error in line#8 column 284. But the commit does not touch line 8 (first line touched is 21, and that looks ok to me). Can you give a hint where/how to search for the problem ?

thanks in advance.

2021-05-19 22:19 UTC, klaasnicolaas requested changes

2021-05-19 22:19 UTC, klaasnicolaas commented on source/_integrations/modbus.markdown
> +  description: Time to delay sending messages in seconds after connecting. Some modbus devices need a delay of typically 1-2 seconds after established connection to prepare the communication. If a de
```suggestion
  description: "Time to delay sending messages in seconds after connecting. Some modbus devices need a delay of typically 1-2 seconds after established connection to prepare the communication. If a device does not response to messagees after connect, this parameter might help. Remark: the delay is solely between connect and the first message."
```

2021-05-19 22:25 UTC, klaasnicolaas requested changes, later dismissed

2021-05-19 22:25 UTC, klaasnicolaas commented on source/_integrations/modbus.markdown
> +`rtuovertcp` Modbus messages with a wrapper TCP/IP simulating a serial lines.
```suggestion
  description: Type of communication. Possible values are `tcp` Modbus messages with modbus TCP frame on TCP/IP, `udp` Modbus messages with modbus TCP frame on UDP, `rtuovertcp` Modbus messages with a wrapper TCP/IP simulating a serial lines.
```

2021-05-20 17:29 UTC, janiversen commented
How super to see the site in a PR. This PR is ready from my side.

2021-05-22 12:17 UTC, janiversen commented
Do I miss to do something (it is no good idea, that I approve my own work) ? Code is coming in 2021.6 so I hope this doc. will as well.

2021-05-25 10:24 UTC, frenck requested changes

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +[Modbus](http://www.modbus.org/) is a serial communication protocol to control PLCs (Programmable Logic Controller) and RTUs (Remote Terminal Unit). The integration adhere strictly to the [protocol s
```suggestion
[Modbus](http://www.modbus.org/) is a serial communication protocol to control PLCs (Programmable Logic Controller) and RTUs (Remote Terminal Unit). The integration adheres strictly to the [protocol specification](https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf).
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +Modbus supports all devices adhering to the modbus standard. The communication between the device(s) can be serial (rs-485), TCP, or UDP connections. The modbus integration allows multiple communicat
```suggestion
Modbus supports all devices adhering to the Modbus standard. The communication between the device(s) can be serial (rs-485), TCP, or UDP connections. The Modbus integration allows multiple communications e.g. serial combined with TCP or different TCP connected devices.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +# Configuring modbus
```suggestion
# Configuring Modbus
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +First you define how to communicate with your modbus devices and after that you define the information being exchanged. The modbus integration allows you to use multiple connections.
```suggestion
First, you define how to communicate with your Modbus devices and after that you define the information being exchanged. The Modbus integration allows you to use multiple connections.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +## Configuring modbus common parameters
```suggestion
## Configuring Modbus common parameters
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +  description: Determines if the device connection is closed when an error occurs, default is true. Some serial-rs485 adapters delivers garble when opened, this leads to a disconnect and a new connec
```suggestion
  description: Determines if the device connection is closed when an error occurs, default is true. Some serial-rs485 adapters deliver garble when opened, this leads to a disconnect and a new connect, which can continue. If in a running communication the debug log contains a message from pymodbus, with the text "cleaning....", then try this parameter.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +  description: "Time to delay sending messages in seconds after connecting. Some modbus devices need a delay of typically 1-2 seconds after established connection to prepare the communication. If a d
```suggestion
  description: "Time to delay sending messages in seconds after connecting. Some Modbus devices need a delay of typically 1-2 seconds after established connection to prepare the communication. If a device does not respond to messages after connecting, this parameter might help. Remark: the delay is solely between connect and the first message."
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +  description: Timeout while wating for response in seconds. Remark timout less than 5 seconds will be automatically adjusted to 5 seconds.
```suggestion
  description: Timeout while waiting for a response in seconds. Remark: a timeout of fewer than 5 seconds will be automatically adjusted to 5 seconds.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +  description: Type of communication. Possible values are `tcp` Modbus messages with modbus TCP frame on TCP/IP, `udp` Modbus messages with modbus TCP frame on UDP, `rtuovertcp` Modbus messages with
```suggestion
  description: Type of communication. Possible values are `tcp` Modbus messages with Modbus TCP frame on TCP/IP, `udp` Modbus messages with Modbus TCP frame on UDP, `rtuovertcp` Modbus messages with a wrapper TCP/IP simulating a serial line.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +  description: The IP address of your Modbus device, e.g., 192.168.1.1.
```suggestion
  description: The IP address of your Modbus device, e.g., `192.168.1.1`.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +Remark `name:`is required for multiple connection, because it needs to be unique.
```suggestion
Remark: `name:`is required for multiple connections, because it needs to be unique.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +The modbus integration provides two generic services in addition to the platform specific services.
```suggestion
The Modbus integration provides two generic services in addition to the platform-specific services.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +# configure modbus platforms
```suggestion
# configure Modbus platforms
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +Modbus platform entities are configured within the modbus configuration.
```suggestion
Modbus platform entities are configured within the Modbus configuration.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +    name: hub1
```suggestion
    name: "hub1"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +    name: hub1
```suggestion
    name: "hub1"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +    name: hub2
```suggestion
    name: "hub2"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +  - name: hub1
```suggestion
  - name: "hub1"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
>    - name: hub1
```suggestion
  - name: "hub1"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +The modbus binary sensor allows you to gather data from coils which as per standard have state ON/OFF.
```suggestion
The Modbus binary sensor allows you to gather data from coils which as per standard have state ON/OFF.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +To use your modbus binary sensors in your installation, add the following to your `configuration.yaml` file, in addition to the [common parameters](#configuring- platform-common-parameters):
```suggestion
To use your Modbus binary sensors in your installation, add the following to your `configuration.yaml` file, in addition to the [common parameters](#configuring- platform-common-parameters):
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      - name: binary_sensor1
```suggestion
      - name: "binary_sensor1"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      - name: binary_ensor2
```suggestion
      - name: "binary_ensor2"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +        device_class: "door"
```suggestion
        device_class: door
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +The modbus climate platform allows to monitor your termostat as well as set a target temperature.
```suggestion
The Modbus climate platform allows you to monitor your thermostat as well as set a target temperature.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
>        - name: Watlow F4T
```suggestion
      - name: "Watlow F4T"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +To use modbus covers in your installation, add the following to your `configuration.yaml` file, in addition to the [common parameters](#configuring- platform-common-parameters):
```suggestion
To use Modbus covers in your installation, add the following to your `configuration.yaml` file, in addition to the [common parameters](#configuring- platform-common-parameters):
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +        device_class: "door"
```suggestion
        device_class: door
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      - name: Door2
```suggestion
      - name: "Door2"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +  description: The array contains a list of all your modbus covers.
```suggestion
  description: The array contains a list of all your Modbus covers.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      - name: Fan1
```suggestion
      - name: "Fan1"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      - name: Fan2
```suggestion
      - name: "Fan2"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      - name: Register1
```suggestion
      - name: "Register1"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      description: Coil number or register
```suggestion
      description: Coil number or register.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      description: type of adddress (holding/coil)
```suggestion
      description: Type of address (holding/coil).
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      description: Read from modbus device to verify fan. If used without attributes it uses the toggle register configuration. If omitted no verification is done, but the state of the fan is set wit
```suggestion
      description: Read from Modbus device to verify fan. If used without attributes it uses the toggle register configuration. If omitted no verification is done, but the state of the fan is set with each toggle.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +          description: address to read from.
```suggestion
          description: Address to read from. 
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +          description: type of adddress (holding/coil/discrete/input)
```suggestion
          description: Type of adddress (holding/coil/discrete/input).
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +          description: value when fan is on.
```suggestion
          description: Value when the fan is on.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +          description: value when fan is off.
```suggestion
          description: Value when the fan is off.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      - name: light1
```suggestion
      - name: "light1"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      - name: light2
```suggestion
      - name: "light2"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      - name: Register1
```suggestion
      - name: "Register1"
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      description: Coil number or register
```suggestion
      description: Coil number or register.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      description: type of adddress (holding/coil)
```suggestion
      description: Type of address (holding/coil).
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +          description: address to read from.
```suggestion
          description: Address to read from. 
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +          description: type of adddress (holding/coil/discrete/input)
```suggestion
          description: Type of address (holding/coil/discrete/input).
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      description: Value to write to turn on the fan.
```suggestion
      description: Value to write to turn on the light.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      description: Value to write to turn off the fan.
```suggestion
      description: Value to write to turn off the light.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +      description: Read from modbus device to verify fan. If used without attributes it uses the toggle register configuration. If omitted no verification is done, but the state of the fan is set wit
```suggestion
      description: Read from Modbus device to verify the light. If used without attributes it uses the toggle register configuration. If omitted no verification is done, but the state of the light is set with each toggle.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +          description: value when fan is on.
```suggestion
          description: Value when the light is on.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +          description: value when fan is off.
```suggestion
          description: Value when the light is off.
```

2021-05-25 10:24 UTC, frenck commented on source/_integrations/modbus.markdown
> +To use your modbus sensors in your installation, add the following to your `configuration.yaml` file, in addition to the [common parameters](#configuring- platform-common-parameters):
```suggestion
To use your Modbus sensors in your installation, add the following to your `configuration.yaml` file, in addition to the [common parameters](#configuring- platform-common-parameters):
```

2021-05-25 15:08 UTC, frenck commented on source/_integrations/modbus.markdown
> +  description: Timeout while waiting for a response in seconds. Remark: a timeout of fewer than 5 seconds will be automatically adjusted to 5 seconds.
```suggestion
  description: "Timeout while waiting for a response in seconds. Remark: a timeout of fewer than 5 seconds will be automatically adjusted to 5 seconds."
```

2021-05-25 15:17 UTC, frenck approved these changes

2021-05-25 15:18 UTC, merged