Add Nobø Ecohub integration
home-assistant/home-assistant.github.io pull request #17915
Opened 2021-05-20 18:47 UTC by oyvindwe

## Proposed change

Documentation for new climate integration: Nobø Ecohub

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: Logo already in Brands repository for HACS component
- This PR fixes or closes issue: -

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-05-20 20:17 UTC, oyvindwe commented
As far as I can tell, this PR is correctly rebased.

2021-05-25 11:45 UTC, frenck requested changes

2021-05-25 11:45 UTC, frenck commented on source/_integrations/nobo_hub.markdown
> +The possible operation modes are as following:
```suggestion
The possible operation modes are as follows:

```

2021-05-25 11:45 UTC, frenck commented on source/_integrations/nobo_hub.markdown
> +  (according to calendar setup)
```suggestion
- "Auto" - In this mode, the zone is in the normal setting and preset shows which state the zone is in right now
  (according to calendar setup).
```

2021-05-25 11:45 UTC, frenck commented on source/_integrations/nobo_hub.markdown
> +  or "Comfort")
```suggestion
- "Heat" - In this mode the zone in the override setting and in the state selected by preset ("Away", "Eco"
  or "Comfort").
```

2021-05-25 11:45 UTC, frenck commented on source/_integrations/nobo_hub.markdown
> +  turns the heater(s) in the zone completely off (more info below)
```suggestion
- "Off" - In this optional mode the zone is in the normal setting and will configure it to use a week profile that
  turns the heater(s) in the zone completely off (more info below).
```

2021-05-25 11:45 UTC, frenck commented on source/_integrations/nobo_hub.markdown
> +  "completely off" profile
```suggestion

- Changing preset to "Away", "Eco", or "Comfort" will automatically change operation to "Heat".
- Changing preset to none will automatically change operation to "Auto" and update preset.
- Changing operation to "Auto" will automatically update preset.
- Changing operation to "Heat" will set preset to "Comfort".
- Changing operation to "Off" will change operation to "Auto" and change the week profile to the predefined
  "completely off" profile.
```

2021-05-25 11:45 UTC, frenck commented on source/_integrations/nobo_hub.markdown
> +
```suggestion

```

2021-05-25 11:45 UTC, frenck commented on source/_integrations/nobo_hub.markdown
> +IP address of the hub.
```suggestion
IP address of the hub.

{% include integration/config_flow.md %}

## Operation modes
```

2021-05-25 11:45 UTC, frenck commented on source/_integrations/nobo_hub.markdown
> +you can configure the system to switch a zone to this week profile to be able to turn the heater(s) off.
```suggestion
Nobø heaters can normally not be set to override "off". This is not a limitation in the integration, but a
safety mechanism in the Nobø system (maybe they don't want you to accidentally turn off all your heaters and get
frozen pipes). However, it is possible to create a week profile that makes the heaters stay off all the time. And then
you can configure the system to switch a zone to this week's profile to be able to turn the heater(s) off.
```

2021-05-25 11:45 UTC, frenck commented on source/_integrations/nobo_hub.markdown
> +profile for your each of your zones, you can use this module to turn off (and on) your heaters. The week profiles
```suggestion
profile for each of your zones, you can use this module to turn off (and on) your heaters. The week profiles
```

2021-05-25 11:46 UTC, frenck commented
Please note: You need to open a PR at the brands repository to move the brand images from a custom integration to a core integration.

2021-05-25 12:32 UTC, oyvindwe commented
Thanks for the review! 

> Please note: You need to open a PR at the brands repository to move the brand images from a custom integration to a core integration.

Thank you - I didn't know that, as the logo appeared automatically in my dev environment. Should I move or copy the logo?

2021-05-25 12:33 UTC, frenck commented on source/_integrations/nobo_hub.markdown
> +## There is no override in Nobø Ecohub for "completely off", but there is a workaround
```suggestion
  "completely off" profile.

## There is no override in Nobø Ecohub for "completely off", but there is a workaround
```

2021-05-25 12:34 UTC, frenck commented
The brand images should be moved.

2021-05-25 12:34 UTC, frenck approved these changes, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2021-05-25 12:37 UTC, frenck approved these changes, later dismissed

2021-05-25 15:17 UTC, oyvindwe commented
Thank you for the review!

> ⚠️ The `ha_release` might need an update before merging this one in.

I guess we don't know that until the parent PR is merged?

2021-05-25 15:40 UTC, frenck commented
> I guess we don't know that until the parent PR is merged?

Correct.

2022-09-03 08:15 UTC, MartinHjelmare commented on source/_integrations/nobo_hub.markdown
> +ha_release: 2021.6
```suggestion
ha_release: 2022.10
```

2022-09-03 08:15 UTC, MartinHjelmare commented on source/_integrations/nobo_hub.markdown
> +- '@echoromeo'
We didn't add echoromeo as codeowner in the integration I believe.

2022-09-03 08:15 UTC, MartinHjelmare commented on source/_integrations/nobo_hub.markdown
> +Nobø heaters does not support preset "Off". This is not a limitation in the integration, but a safety mechanism in the
```suggestion
Nobø heaters do not support preset "Off". This is not a limitation in the integration, but a safety mechanism in the
```

2022-09-03 08:17 UTC, MartinHjelmare commented
Try rebasing on latest `next` branch to make the build pass.

2022-09-03 13:48 UTC, oyvindwe commented
> Try rebasing on latest `next` branch to make the build pass.

Done.

2022-09-03 16:08 UTC, MartinHjelmare approved these changes, later dismissed
Thanks!

2022-09-06 18:31 UTC, frenck commented on source/_integrations/nobo_hub.markdown
> +ha_release: 2021.6
```suggestion
ha_release: 2021.10
```

2022-09-06 18:32 UTC, frenck approved these changes
Thanks, @oyvindwe 👍

2022-09-06 18:33 UTC, merged