Add documentation about services for Mazda integration
home-assistant/home-assistant.github.io pull request #17946
Opened 2021-05-24 01:43 UTC by bdr99

## Proposed change

Add documentation about newly added services for the Mazda integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: TBD
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-05-24 12:26 UTC, emontnemery commented
Please document input parameters for the services.

2021-05-25 04:42 UTC, bdr99 commented
@emontnemery Added documentation for input parameters.

2021-05-25 07:55 UTC, frenck requested changes

2021-05-25 07:55 UTC, frenck commented on source/_integrations/mazda.markdown
> +| Parameter | YAML ID | Description |
Please take a look at other documented services on the format/title of the headers.

2021-05-25 07:55 UTC, frenck commented on source/_integrations/mazda.markdown
> +Starts the vehicle engine. The vehicle engine can only be remotely started 2 consecutive times. To reset this counter, the vehicle must be driven.
The service name is missing (applies to all services).

Please check other services documentation for a reference.

2021-05-25 13:52 UTC, bdr99 commented
@frenck OK, I updated it to follow the standard format that other integrations are using. I'm a little surprised that this standard format doesn't include the friendly names for the services and their parameters. I would think it would make more sense to document those, since the friendly names are what is displayed to the user. For example, "Start Engine" instead of `start_engine` since the former is what the user actually sees in the UI. They would only see `start_engine` if they switch to YAML mode.

2021-05-25 13:57 UTC, frenck commented on source/_integrations/mazda.markdown
> +### Service `start_engine`
```suggestion
### Service `mazda.start_engine`
```

2021-05-25 13:57 UTC, frenck commented on source/_integrations/mazda.markdown
> +### Service `stop_engine`
```suggestion
### Service `mazda.stop_engine`
```

2021-05-25 13:57 UTC, frenck commented on source/_integrations/mazda.markdown
> +### Service `start_charging`
```suggestion
### Service `mazda.start_charging`
```

2021-05-25 13:57 UTC, frenck commented on source/_integrations/mazda.markdown
> +### Service `stop_charging`
```suggestion
### Service `mazda.stop_charging`
```

2021-05-25 13:57 UTC, frenck commented on source/_integrations/mazda.markdown
> +### Service `send_poi`
```suggestion
### Service `mazda.send_poi`
```

2021-05-25 13:57 UTC, frenck commented on source/_integrations/mazda.markdown
> +### Service `turn_on_hazard_lights`
```suggestion
### Service `mazda.turn_on_hazard_lights`
```

2021-05-25 13:57 UTC, frenck commented on source/_integrations/mazda.markdown
> +### Service `turn_off_hazard_lights`
```suggestion
### Service `mazda.turn_off_hazard_lights`
```

2021-05-25 13:59 UTC, frenck commented
> OK, I updated it to follow the standard format that other integrations are using. I'm a little surprised that this standard format doesn't include the friendly names for the services and their parameters. 

We agree. Recently the service description format in the core repository has been changed and currently is updated completely. This allows us to generate (a more user-friendly) and even more standardized approach for the near future. Right now, we stick to what we have.

2021-05-25 14:03 UTC, bdr99 commented
@frenck Added the "mazda" prefix like you suggested.
> 
> 
> > OK, I updated it to follow the standard format that other integrations are using. I'm a little surprised that this standard format doesn't include the friendly names for the services and their parameters.
> 
> We agree. Recently the service description format in the core repository has been changed and currently is updated completely. This allows us to generate (a more user-friendly) and even more standardized approach for the near future. Right now, we stick to what we have.

Great! Glad to hear that changes are in the works.

2021-05-25 14:11 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-05-26 14:36 UTC, merged