Document optional MQTT cover options
home-assistant/home-assistant.github.io pull request #17971
Opened 2021-05-25 20:29 UTC by thecode

## Proposed change

Make all payloads optional to allow cover that can be just open (e.g. gates that self close after some time)

Example entry for `configuration.yaml`:

```yaml
cover:
  - platform: mqtt
    payload_open: "on"
    payload_close: 
    payload_stop: "on"
```

or, via auto discovery:

```json
{
  "cover": [
    {
      "platform": "mqtt",
      "payload_open": "on",
      "payload_close": null,
      "payload_stop": "on"
    }
  ]
}
```

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/50579
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-05-25 22:43 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-05-26 05:07 UTC, maxcanna requested changes
There's a small typo in the example

2021-05-26 05:07 UTC, maxcanna commented on source/_integrations/cover.mqtt.markdown
> +    payload_stop: "on
You missed a quote here 🙂

2021-05-26 06:07 UTC, frenck commented on source/_integrations/cover.mqtt.markdown
> +    payload_stop: "on
```suggestion
    payload_stop: "on"
```

2021-05-26 07:07 UTC, frenck approved these changes

2021-05-26 10:52 UTC, merged