Correct MQTT fan breaking changes info
home-assistant/home-assistant.github.io pull request #18142
Opened 2021-06-09 19:52 UTC by emontnemery

## Proposed change

Correct MQTT fan breaking changes info

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-06-09 19:52 UTC, emontnemery commented
@jbouwh Please review

2021-06-09 22:13 UTC, jbouwh requested changes
Please list the  `speeds` config option and add the speed payload specific config options to the list of options to be removed.

2021-06-09 22:13 UTC, jbouwh commented on source/_posts/2021-04-07-release-20214.markdown
>  - `speed_list`
The MQTT fan configuration option for `speed_list` attribute is `speeds`.
Further the following configuration options won't be needed anymore:
- `payload_off_speed`
- `payload_low_speed`
- `payload_medium_speed`
- `payload_high_speed`

The rest LGTM

2021-06-10 06:52 UTC, jbouwh approved these changes
LGTM

2021-06-10 10:54 UTC, jbouwh approved these changes

2021-06-10 11:11 UTC, frenck approved these changes

2021-06-10 11:11 UTC, merged