Document trigger condition
home-assistant/home-assistant.github.io pull request #18160
Opened 2021-06-11 13:04 UTC by emontnemery

## Proposed change

Document trigger condition

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/51710

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-06-11 13:05 UTC, emontnemery commented
Should we include complete automation examples, in addition to just examples of the trigger condition?

2021-06-11 21:19 UTC, frenck requested changes

2021-06-11 21:19 UTC, frenck commented on source/_docs/scripts/conditions.markdown
> +  id: event_trigger
```suggestion
condition:
  condition: trigger
  id: event_trigger
```

2021-06-11 21:19 UTC, frenck commented on source/_docs/scripts/conditions.markdown
> +  id: "0"
```suggestion
condition:
  condition: trigger
  id: "0"
```

2021-06-11 21:19 UTC, frenck commented on source/_docs/scripts/conditions.markdown
> +  id: 0
```suggestion
condition:
  condition: trigger
  id: 0
```

2021-06-11 21:19 UTC, frenck commented on source/_docs/scripts/conditions.markdown
> +It is possible to give a list of triggers:
```suggestion

It is possible to give a list of triggers:

```

2021-06-11 21:19 UTC, frenck commented on source/_docs/scripts/conditions.markdown
> +    - event_2_trigger
```suggestion
condition:
  condition: trigger
  id:
    - event_1_trigger
    - event_2_trigger
```

2021-06-12 09:48 UTC, frenck approved these changes

2021-06-12 09:48 UTC, merged