Update buienradar.markdown
home-assistant/home-assistant.github.io pull request #18220
Opened 2021-06-17 11:32 UTC by denniswham

The wind gust sensor gives values in km/h, not m/s. Haven't tested, but my guess is that all speed sensors are in km/h

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-06-17 11:32 UTC, homeassistant commented
Hi @denniswham, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#18220).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-06-17 18:21 UTC, frenck requested changes

2021-06-17 18:21 UTC, frenck commented on source/_integrations/buienradar.markdown
> +- **Wind gust**: "The wind speed of wind gusts ([km/h](https://en.wikipedia.org/wiki/M/s))."
The link to Wikipedia is now incorrect, could you please adjust that too?

Thanks! 👍

2021-06-18 09:51 UTC, frenck approved these changes
Thanks, @denniswham 👍

2021-06-18 09:52 UTC, denniswham commented
Good spot @frenck. Updated the link.

2021-06-18 09:57 UTC, merged