Update acmeda.markdown
home-assistant/home-assistant.github.io pull request #18360
Opened 2021-07-01 05:22 UTC by tallcuss

Discuss different hub versions and reference v2 integration

## Proposed change
This document describes the Automate Pulse version 1 Hub Integration. My changes point out there are two versions of the hub, each with its own integration: v1 written by atmurray and v2 written by sillyfrog

## Type of change
- [ X] Spelling, grammar or other readability improvements (`current` branch).
- [ X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist
- [ X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-07-01 05:22 UTC, homeassistant commented
Hi @tallcuss, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#18360).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-07-01 05:53 UTC, frenck requested changes

2021-07-01 05:53 UTC, frenck commented on source/_integrations/acmeda.markdown
> +The remainder of this description applies to both hub integrations.
We don't support custom components, thus should not be part of our documentation.
We generally list the supported devices instead.

```suggestion
### Supported devices

- Automate Pulse Hub v1

```

2021-07-02 05:45 UTC, frenck approved these changes

2021-07-02 05:45 UTC, merged