Automation Debugging
home-assistant/home-assistant.github.io pull request #18400
Opened 2021-07-05 21:36 UTC by knudsvik

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-07-05 21:36 UTC, homeassistant commented
Hi @rolfikr1, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#18400).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-07-06 07:14 UTC, frenck commented
There are unrelated commits in this PR. Please perform a git rebase onto the latest upstream current branch, to clean those up:

Thanks!

2021-07-06 07:14 UTC, frenck requested changes
Setting PR state correctly

2021-08-24 11:22 UTC, frenck requested changes
Looks good @elbowdonkey 👍 

All that is left is a couple of small comments and a merge conflict that needs to be resolved.

2021-08-24 11:22 UTC, frenck commented on source/_docs/automation/troubleshooting.markdown
> +### Debugging your automation
This is the page title already, so we don't need another heading.

```suggestion
```

2021-08-24 11:22 UTC, frenck commented on source/_docs/automation/troubleshooting.markdown
> +Automation debugging was added in the 2021.4 release. When an automation is run, all steps are recorded and a trace is made. From the UI choose **Configuration** which is located in the sidebar, then
We don't keep a changelog in the documentation, so mentioning the version isn't needed.

```suggestion
When an automation is run, all steps are recorded and a trace is made. From the UI choose **Configuration** which is located in the sidebar, then click on **Automation** to go to the automation editor or click this button directly: {% my automation badge %}
```

2021-08-24 11:22 UTC, frenck commented on source/_docs/automation/troubleshooting.markdown
> +Click on the clock icon next to an automation to enter the debugging screen. Alternatively click on **Show trace** directly from a Logbook automation entry.
```suggestion
Click on the clock icon next to an automation to enter the debugging screen. Alternatively, click on **Show trace** directly from a Logbook automation entry.
```

2021-08-24 11:22 UTC, frenck commented on source/_docs/automation/troubleshooting.markdown
> +The debugging screen is split in four features, the first being the Step Details which provides all details for each step of the automation. The second feature is the Trace Timeline which the screens
```suggestion
The debugging screen is split into four features, the first being the Step Details which provides all details for each step of the automation. The second feature is the Trace Timeline which the screenshot above shows and where the automation can be followed on a timeline. The next is Related logbook entries, as the name says a logbook for all the entries related to the specific trace. The last two features are Automation Config and optionally Blueprint Config for the automation YAML code.
```

2021-08-25 07:29 UTC, frenck approved these changes
Thanks, @knudsvik 👍

2021-08-25 07:29 UTC, merged