Update subaru integration documentation
home-assistant/home-assistant.github.io pull request #18538
Opened 2021-07-18 03:15 UTC by G-Two

## Proposed change

- Add documentation for new lock platform
- Minor edits for clarity

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/52852

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-07-19 09:24 UTC, frenck requested changes
Thanks, @G-Two 👍 

Left some really small comments.

2021-07-19 09:24 UTC, frenck commented on source/_integrations/subaru.markdown
> +### Sensor
```suggestion
## Sensors
```

2021-07-19 09:24 UTC, frenck commented on source/_integrations/subaru.markdown
> +### Lock
```suggestion
## Lock
```

2021-07-19 09:24 UTC, frenck commented on source/_integrations/subaru.markdown
> +This integration retrieves vehicle information and actuates remote services provided by [Subaru STARLINK](https://www.subaru.com/engineering/starlink/safety-security.html) (currently only available i
```suggestion
This integration retrieves vehicle information and actuates remote services provided by [Subaru STARLINK](https://www.subaru.com/engineering/starlink/safety-security.html) (currently only available in USA and Canada).
```

2021-07-19 09:24 UTC, frenck commented on source/_integrations/subaru.markdown
> +Subaru has deployed two generations of telematics, Gen 1 and Gen 2. The latter offers more vehicle sensor information and additional remote capabilities. Use the table below to determine your vehicle
```suggestion
Subaru has deployed two generations of telematics, Gen 1 and Gen 2. The latter offers more vehicle sensor information and additional remote capabilities. Use the table below to determine your vehicle's telematics generation and capabilities.
```

2021-07-20 09:17 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2022-03-20 09:43 UTC, bdraco commented on source/_integrations/subaru.markdown
> +Available sensors will vary by model, year, and subscription type. The integration will add all supported sensors for your vehicle. Sensor data is usually only updated when the vehicle is turned off,
```suggestion
Available sensors will vary by model, year, and subscription type. The integration will add all supported sensors for your vehicle. Sensor data is usually only updated when the vehicle is turned off unless the [polling option](#options) is enabled.
```

2022-03-20 09:44 UTC, bdraco approved these changes

2022-03-20 12:13 UTC, frenck approved these changes

2022-03-20 12:13 UTC, merged