Add documentation on new template functions for devices
home-assistant/home-assistant.github.io pull request #18540
Opened 2021-07-18 05:54 UTC by raman325

## Proposed change
In the linked PR we add some new template functions that allow templates access to the DeviceRegistry. While implementing this, I found the `device_entities` function/filter that was also undocumented so I added some notes on that as well.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/53131
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-07-19 09:43 UTC, frenck requested changes

2021-07-19 09:43 UTC, frenck commented on source/_docs/configuration/templating.markdown
> +{{ state_attr('deadbeefdeadbeefdeadbeefdeadbeef', 'manufacturer') }}  # Sony
state_attr? 😉

2021-07-19 17:12 UTC, raman325 commented on source/_docs/configuration/templating.markdown
> +{{ state_attr('deadbeefdeadbeefdeadbeefdeadbeef', 'manufacturer') }}  # Sony
doh

2021-07-19 17:23 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-07-28 06:44 UTC, frenck approved these changes
Thanks, @raman325 👍

2021-07-28 06:45 UTC, merged