Update Tuya Integration markdown file.
home-assistant/home-assistant.github.io pull request #18621
Opened 2021-07-26 12:24 UTC by zlinoliver

## Proposed change

Tuya Smart always strive to provide the best development experience possible and keep updating our Home Assistant integration capabilities. Since the old version of Tuya Home Assistant integration supports limited categories and control commands, now we bring you our new integration with extended support for more categories and commands.

Our new integration is built on Tuya’s standard [Open APIs](https://developer.tuya.com/en/docs/cloud) and tackles the limits of categories and accessible control commands. We deliver more development-friendly features including virtual device debugging, official authorization, and technical supports, which will help you efficiently work on development with the Tuya ecosystem.

The existing [Tuya Integration](https://www.home-assistant.io/integrations/tuya/) is no longer maintained by Tuya officially, and will be deprecated. The estimated deprecation date is 2021.12.31. The new integration will be officially maintained by the Tuya Developer Team, for more information of the migration, please check this documentation [How to Migrate the Tuya Home Assistant Integration from the Old Version](https://developer.tuya.com/en/docs/iot/migrate-from-an-older-version?id=Kamee9wtbd00b)

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-07-26 12:34 UTC, frenck requested changes
This is the current documentation for the current Tuya integration in the `tuya` domain. This PR does not match the current release.

I'm not sure what you are trying to achieve with this PR?

2021-07-26 12:34 UTC, frenck commented on source/_integrations/tuya.markdown
> +  - Security&Sensors
These are not valid categories

2021-07-26 12:35 UTC, frenck commented on source/_integrations/tuya.markdown
> +<style>
Don't use inline HTML in our documentation.

2021-07-27 03:05 UTC, zlinoliver commented
> This is the current documentation for the current Tuya integration in the `tuya` domain. This PR does not match the current release.
> 
> I'm not sure what you are trying to achieve with this PR?

Hi @frenck , this documentation PR is for the new Tuya integration, it's related to this PR: https://github.com/home-assistant/core/pull/53510. Should we use a new tuya v2 branch for the PR?

2021-09-29 07:40 UTC, zlinoliver commented
We create a new PR for the tuya v2 integration release, please help to review this instead: https://github.com/home-assistant/home-assistant.io/pull/19519

2021-09-29 07:40 UTC, closed without merging