Duckdns now requires the suffix
home-assistant/home-assistant.github.io pull request #18680
Opened 2021-08-01 01:23 UTC by jflecool2

Update to indicate the duckdns plugins now need the domain suffix (.duckdns.org)
As me and [this redditor](https://www.reddit.com/r/homeassistant/comments/o45je5/duckdns_fails_after_update/) figured out.
Otherwise regex refuse the config change.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-08-01 01:23 UTC, homeassistant commented
Hi @jflecool2, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#18680).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-08-02 10:54 UTC, frenck requested changes

2021-08-02 10:54 UTC, frenck commented on source/_integrations/duckdns.markdown
> +    description: Your duckdns subdomain (with the `.duckdns.org` suffix).
The link to reddit is about the add-on, this documentation is about the integration.
Are you sure you aren't mixing things up?

Could you point me to upstream documentation that shows this being needed for the integration as well?

2021-08-02 13:13 UTC, jflecool2 commented
I mixed up the Duckdns addon and Duckdns integration. Good catch frenck. And sorry!

2021-08-02 13:13 UTC, closed without merging