Update switcher_kis.markdown
home-assistant/home-assistant.github.io pull request #18818
Opened 2021-08-07 06:27 UTC by ohadbenita

@thecode FYI.

## Proposed change

Add clarification to the Switcher documentation.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
As in my case I was unable to control my device due to an old firmware, I find it may serve others in the same condition as I am.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-08-07 08:26 UTC, thecode approved these changes, later dismissed

2021-08-09 13:04 UTC, frenck requested changes

2021-08-09 13:04 UTC, frenck commented on source/_integrations/switcher_kis.markdown
> +If you completed the config flow but still unable to control the device, please make sure your device's firmware is up-to-date.
config flow is not a user-facing term.

```suggestion
If you completed the integration setup but are still unable to control the device, please make sure your device's firmware is up-to-date.
```

2021-08-09 13:50 UTC, frenck approved these changes
Thanks! 👍

2021-08-09 13:50 UTC, merged