Update modes.markdown
home-assistant/home-assistant.github.io pull request #18834
Opened 2021-08-07 22:18 UTC by johnw230873

When trying to set up an process of allowing the lights to decrease while the bottom was pressed I interrupted the  single mode incorrectly and thoughts triggers for the Automation could still alter the behavior of the running instance of the automation if in single. This suggestion is to help any other user that might think the same.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-08-07 22:18 UTC, homeassistant commented
Hi @johnw230873, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#18834).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-08-09 11:51 UTC, frenck requested changes

2021-08-09 11:51 UTC, frenck commented on source/_docs/automation/modes.markdown
> +When choosing the correct mode take into consideration that top level triggers only trigger once for any single instance of an automation. If your automation has until loops that rely on Trigger IDs
```suggestion
When choosing the correct mode take into consideration that top-level triggers only trigger once for any single instance of an automation. If your automation has until loops that rely on Trigger IDs consider using the restart mode. In this example, if we set the mode to single the release trigger will not stop the light from decreasing as the automation will be in the repeat loop.
```

2021-08-09 11:51 UTC, frenck commented on source/_docs/automation/modes.markdown
> +```yaml
Please adjust to being more compact / more to the point / without optional values / empty defaults.

Also, make sure it complies with our YAML Style Guide: <https://developers.home-assistant.io/docs/documenting/yaml-style-guide>

2021-10-15 12:01 UTC, closed without merging