Update the detecting lost connections
home-assistant/home-assistant.github.io pull request #18847
Opened 2021-08-08 16:42 UTC by Pinky007

Update the detecting lost connections with the new template form and marked deprecated lines of old example (which are still working with raising errors and warnings)

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-08-08 16:42 UTC, homeassistant commented
Hi @Pinky007, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#18847).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-08-09 11:40 UTC, frenck requested changes

2021-08-09 11:40 UTC, frenck commented on source/_integrations/homematic.markdown
> +     Using old template sensor:
Lets just remove the old stuff instead of keeping it around.

2021-08-09 11:40 UTC, frenck commented on source/_integrations/homematic.markdown
> +          {{ as_timestamp(now()) - as_timestamp(states.sensor.outlet_washmachine_voltage.last_changed) < 600 }}
Never access states via the `states` object directly.

See also:

![image](https://user-images.githubusercontent.com/195327/128700635-6a4cc0fc-21bc-41d0-b69e-f9739537d525.png)

https://www.home-assistant.io/docs/configuration/templating/#states

2021-10-15 12:00 UTC, closed without merging