Update zha.markdown with note about changing Zigbee channel
home-assistant/home-assistant.github.io pull request #18865
Opened 2021-08-09 14:30 UTC by Hedda

## Proposed change

Update zha.markdown with a note about how changing Zigbee channel will require the user to re-pair devices in ZHA.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: NA
- Link to parent pull request in the Brands repository: NA
- This PR fixes or closes issue: NA

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-08-10 11:54 UTC, martin3000 approved these changes, later dismissed

2021-10-08 20:40 UTC, Hedda commented
Not stale.

2021-10-09 01:44 UTC, Adminiuga commented
The information in this PR is incorrect.  Zha does not change the channel after the network was formed. It only tells what channel to prefer for network formation for "out of the box" radios which don't have any network.

2021-10-18 13:00 UTC, Hedda commented
> The information in this PR is incorrect. Zha does not change the channel after the network was formed. It only tells what channel to prefer for network formation for "out of the box" radios which don't have any network.

So would you prefer changing that to something like this instead:

_**Zigbee network channel is set to prefer channel 15 by default by ZHA but you can change this via YAML, however note that changing prefered Zigbee network channel changes requires repairing all already devices paired to ZHA if you want them to try use that new channel instead.**_

2021-10-22 10:56 UTC, frenck requested changes

2021-10-22 10:56 UTC, frenck commented on source/_integrations/zha.markdown
> +Zigbee network channel changes 15 will be used by default by ZHA but the Zigbee network channel can be changed via YAML, however note that changing Zigbee network channel changes requires repairing a
```suggestion
ZHA prefers to use Zigbee channel 15 by default. You can change this using YAML configuration, however, note that changing the channel requires repairing all devices.
```

2021-10-22 10:56 UTC, frenck commented on source/_integrations/zha.markdown
> +Tip: Reference this for channel selection [Zigbee and WiFi coexistence (using non-overlapping frequency-bands)](https://support.metageek.com/hc/en-us/articles/203845040-ZigBee-and-WiFi-Coexistence).
I don't think this is an improvement, and quite an unneeded change. Please revert it.

2021-10-22 11:06 UTC, martin3000 commented on source/_integrations/zha.markdown
> +Zigbee network channel changes 15 will be used by default by ZHA but the Zigbee network channel can be changed via YAML, however note that changing Zigbee network channel changes requires repairing a
"repairing all already devices" ? what is this?

2021-10-22 15:43 UTC, Adminiuga commented on source/_integrations/zha.markdown
> +Zigbee network channel changes 15 will be used by default by ZHA but the Zigbee network channel can be changed via YAML, however note that changing Zigbee network channel changes requires repairing a
Because currently it requires killing the current network and forming a new one. But here's the challenge: re-forming the network is radio specific and now we run into the same issue when this is now not ZHA integration specific, but radio specific and shouldn't really belong to ZHA integration documentation. 

Right now channel configuration is taken into consideration only for new sticks. if ZHA was configured at least once and already formed the network on the stick, then channel configuration is ignored.

2021-10-22 15:47 UTC, frenck commented on source/_integrations/zha.markdown
> +Zigbee network channel changes 15 will be used by default by ZHA but the Zigbee network channel can be changed via YAML, however note that changing Zigbee network channel changes requires repairing a
So, shall we just close this instead?

2021-10-22 15:55 UTC, martin3000 commented
One day I recognized that my zigbee was on a bad channel. So I wanted to change the channel. I read the chapter  "DEFINING ZIGBEE CHANNEL TO USE", implemented it in my configuration.yaml and it did not work. And I wondered why. So it is necessary to mention that defining a channel only works when you start the first time. Maybe this note should also go into the installation instructions. Because if you use a zigbee channel with a frequency the nearby hospital uses for its devices, you are lost.

2021-10-22 15:58 UTC, Adminiuga commented on source/_integrations/zha.markdown
> +ZHA prefers to use Zigbee channel 15 by default. You can change this using YAML configuration, however, note that changing the channel requires repairing all devices.
```suggestion
ZHA prefers to use Zigbee channel 15 by default. You can change this using YAML configuration, but this only works
if there's no existing network. To change the channel for an existing channel, radio has to be factory reset and a new network to be formed. This requires re-pairing of all the devices.
```

2021-10-22 16:03 UTC, frenck commented on source/_integrations/zha.markdown
> +Tip: Reference this for channel selection [Zigbee and WiFi coexistence (using non-overlapping frequency-bands)](https://support.metageek.com/hc/en-us/articles/203845040-ZigBee-and-WiFi-Coexistence).
```suggestion
This is a good reference for channel selection [Zigbee and Wifi Coexistance](https://support.metageek.com/hc/en-us/articles/203845040-ZigBee-and-WiFi-Coexistence)
```

2021-10-22 16:06 UTC, frenck submitted a review, later dismissed

2021-10-22 16:09 UTC, Adminiuga commented on source/_integrations/zha.markdown
> +if there's no existing network. To change the channel for an existing channel, radio has to be factory reset and a new network to be formed. This requires re-pairing of all the devices.
Doh
```suggestion
if there's no existing network. To change the channel for an existing network, radio has to be factory reset and a new network to be formed. This requires re-pairing of all the devices.
```

2021-10-22 16:19 UTC, frenck approved these changes

2021-10-22 16:19 UTC, merged