Update template.markdown
home-assistant/home-assistant.github.io pull request #18889
Opened 2021-08-11 11:00 UTC by nibbles-

## Proposed change

Added a short description on the template sensor example for the issue with sensors not being available

## Type of change

- [] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-08-11 11:00 UTC, homeassistant commented
Hi @nibbles-, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#18889).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-08-11 12:29 UTC, frenck requested changes

2021-08-11 12:29 UTC, frenck commented on source/_integrations/template.markdown
> +A way to solve this is to make the template sensor have an Unknown or Unavailable state instead.
That is, however, not what the example does.

2021-08-11 13:03 UTC, nibbles- commented on source/_integrations/template.markdown
> +A way to solve this is to make the template sensor have an Unknown or Unavailable state instead.
Ah. Right. It will get the previous value and only Unavailable during startup.
Will change the wording

2021-08-11 13:56 UTC, frenck commented on source/_integrations/template.markdown
> +To make the sensor always Unavailable if any of the included sensors fails change `states('sensor.average_temperature')`to `'Unavailable'`instead
This makes it really unclear IMHO. I think the example should be simple, and this adds unneeded complexity.

2021-10-22 21:46 UTC, frenck requested changes

2021-10-22 21:46 UTC, frenck commented on source/_integrations/template.markdown
> +          {% if (kitchen and bedroom) != None %}
I think we should simplify the example with one sensor, and use `is_number` additionally.

2021-10-22 21:46 UTC, frenck commented on source/_integrations/template.markdown
> +The `| float` part in the above example is a [filter](https://jinja.palletsprojects.com/en/latest/templates/#filters) that converts the state to a float.
Actually, defaulting to 0.0 is being removed (and already deprecated since Home Assistant 2021.10)

2021-10-23 05:31 UTC, closed without merging