Add regex_findall
home-assistant/home-assistant.github.io pull request #19214
Opened 2021-09-05 08:54 UTC by koying

Depends on https://github.com/home-assistant/core/pull/54584

## Proposed change

Add `regex_findall` documentation

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/54584
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-09-05 13:49 UTC, Adminiuga approved these changes, later dismissed
Lgtm

2021-09-22 17:23 UTC, frenck submitted a review, later dismissed
Thanks, @koying 👍

2021-09-22 17:31 UTC, klaasnicolaas approved these changes, later dismissed

2021-09-22 17:35 UTC, ludeeus requested changes

2021-09-22 17:35 UTC, ludeeus commented on source/_docs/configuration/templating.markdown
> +- Filter `string|regex_findall_index(find='', index=0, ignorecase=False)` will do the same as `regex_findall` and return the match at index.
```suggestion
- Filter `value | regex_findall(find='', ignorecase=False)` will find all regex matches of the find expression in `value` and return the array of matches.
- Filter `value | regex_findall_index(find='', index=0, ignorecase=False)` will do the same as `regex_findall` and return the match at index.
```
1) It does not have to be a string,  `{{ 123  | regex_findall(find='', ignorecase=False) }}` is valid as well
2) Filter should have spacing around them <https://developers.home-assistant.io/docs/documenting/yaml-style-guide#filters>

2021-09-22 17:43 UTC, frenck approved these changes

2021-09-22 17:43 UTC, ludeeus approved these changes

2021-09-22 17:45 UTC, merged