Initial commit for EnaSolar Integration
home-assistant/home-assistant.github.io pull request #19212
Opened 2021-09-04 22:20 UTC by geustace

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/54859
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/2759
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-12-15 20:10 UTC, geustace commented
This PR seems to have stalled, is there something I need to do before it can be merged?

2021-12-15 20:44 UTC, klaasnicolaas requested changes
When this PR is merged depends on the progress in the codebase 😉

2021-12-15 20:44 UTC, klaasnicolaas commented on CODEOWNERS
> +source/_integrations/enasolar.markdown @geustace
No adjustments are necessary here as it is synced with the codebase.

2021-12-15 20:44 UTC, klaasnicolaas commented on source/_integrations/enasolar.markdown
> +ha_release: '0.1.0'
```suggestion
ha_release: 2022.2
```

2021-12-15 20:44 UTC, klaasnicolaas commented on source/_integrations/enasolar.markdown
> +Fill in the connection form. Note: Naming the inverter isn't particularly helpful unless you have more than one. select NEXT. If the connection succeeded the next form will have been pre-filled with
```suggestion
{% include integrations/config_flow.md %}
```

2022-02-03 19:41 UTC, geustace commented
Moved documentation into the custom component docs folder.

2022-02-03 19:41 UTC, closed without merging