Update nest.markdown
home-assistant/home-assistant.github.io pull request #19246
Opened 2021-09-07 12:03 UTC by PatrickScheidl

Information provided from Google on 07.09.2021
The new Google Nest Devices "Camera" and "Doorbell (Battery)" arent supported for third party applications.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-09-07 12:03 UTC, homeassistant commented
Hi @PatrickScheidl, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#19246).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-09-07 14:25 UTC, allenporter commented
Hi,

Thanks for this update.

There is a section `Overview: Supported Devices` which talks about what devices are supported.  Can you improve that section instead?

2021-09-07 14:27 UTC, allenporter commented
For connecting the dots, related issue tracking support: https://github.com/home-assistant/core/issues/55302

2021-09-08 06:51 UTC, PatrickScheidl commented
> Hi,
> 
> Thanks for this update.
> 
> There is a section `Overview: Supported Devices` which talks about what devices are supported. Can you improve that section instead?
Sure, how do i do that?

2021-09-08 14:39 UTC, allenporter commented
> > Hi,
> > Thanks for this update.
> > There is a section `Overview: Supported Devices` which talks about what devices are supported. Can you improve that section instead?
> > Sure, how do i do that?

There is already a section in this document which says which devices are supported.  I would recommend you add another bullet point to the section on which camera devices are supported, e.g. around line 56. You could add another bullet that says the battery doorbell is not supported.

2021-09-12 08:26 UTC, ludeeus requested changes

2021-09-12 08:26 UTC, ludeeus commented on source/_integrations/nest.markdown
> +Currently the New Nest Cams and the New Nest Doorbell (battery) arent supported for third party applications.
This should be added under the `- Display, Camera, and Doorbell Devices` bullet point in the  `Overview: Supported Devices` section

2021-10-26 14:13 UTC, frenck commented
Since there was no response at all, I'm declaring this PR stale and closing it.
Feel free to re-open this PR when you feel like that is the appropriate thing to do.

2021-10-26 14:13 UTC, closed without merging