Add documentation for ws66i core integration
home-assistant/home-assistant.github.io pull request #19294
Opened 2021-09-11 06:54 UTC by ssaenger

## Proposed change

This is the documentation for the ws66i core integration soon to be added. I tried viewing it locally, but it would not show up in the integrations page...

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/56094
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/2809
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-12-05 04:20 UTC, ssaenger commented
Comment to keep PR from going stale.

2022-03-06 18:56 UTC, ssaenger commented
@frenck Is it appropriate to contact the vendor of the amplifier and ask for a discount code to be displayed on the documentation page?

2022-03-07 11:05 UTC, frenck commented
@ssaenger I would say: No.

2022-05-09 12:52 UTC, frenck requested changes

2022-05-09 12:52 UTC, frenck commented on source/_integrations/ws66i.markdown
> +ha_release: 2022.5
```suggestion
ha_release: 2022.6
```

2022-05-09 12:52 UTC, frenck commented on source/_integrations/ws66i.markdown
> +The `ws66i` platform allows you to control the [Soundavo Whole-Home Audio Amplifier](https://www.soundavo.com/products/ws-66i) via the local network. This amplifier is an upgrade of the amplifier sol
```suggestion
The Soundavo WS66i 6-Zone Amplifier integration allows you to control the [Soundavo Whole-Home Audio Amplifier](https://www.soundavo.com/products/ws-66i) via the local network. This amplifier is an upgrade of the amplifier sold by [Monoprice](https://www.monoprice.com/product?p_id=10761) that adds 2 built-in wireless streamers and an Ethernet port for control over LAN.
```

2022-05-09 12:52 UTC, frenck commented on source/_integrations/ws66i.markdown
> +Take a snapshot of one or more zones' states. This service, and the following one are useful if you want to play a doorbell or notification sound and resume playback afterward.
We have scenes that provide this functionality in Home Assistant, why does this integration provide its own logic for this?

2022-05-09 12:52 UTC, frenck commented on source/_integrations/ws66i.markdown
> +### Service `ws66i.restore`
Same as above, scenes provide this functionality in Home Assistant, why does this add duplicate logic to Home Assistant?

2022-05-12 03:39 UTC, ssaenger commented
@frenck Done. Custom services were removed in https://github.com/home-assistant/core/pull/71717

2022-05-23 10:35 UTC, frenck approved these changes
Thanks, @ssaenger 👍

2022-05-23 10:35 UTC, merged