Update docs for core #55540
home-assistant/home-assistant.github.io pull request #19339
Opened 2021-09-13 20:17 UTC by StevenLooman

## Proposed change

Remove `local_ip` configuration option as this is no longer supported.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/55540
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-09-13 20:20 UTC, StevenLooman commented
Change of plans.

2021-09-13 20:26 UTC, MartinHjelmare commented
It's ok to remove the option from the docs also if we deprecate the option.

2021-09-19 12:05 UTC, StevenLooman commented
Uncertain why the three top items haven't been executed by the automated build. Perhaps these are only executed after the require review has been done?

2021-09-19 18:38 UTC, bdraco commented on source/_integrations/upnp.markdown
>  ```
```suggestion
```
```

2021-09-19 18:39 UTC, bdraco commented
Looks like the CI failed.  I did an same suggestion empty commit to trigger a retry

2021-09-19 19:23 UTC, klaasnicolaas requested changes, later dismissed

2021-09-19 19:23 UTC, klaasnicolaas commented on source/_integrations/upnp.markdown
> -```
This should be put back (```)

2021-09-22 17:14 UTC, frenck approved these changes
Thanks, @StevenLooman 👍

2021-09-22 17:15 UTC, merged

2021-09-22 20:08 UTC, StevenLooman commented
Thank you @frenck!