Adding amaberelectric documentation
home-assistant/home-assistant.github.io pull request #19396
Opened 2021-09-20 10:13 UTC by madpilot

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/56448
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-09-27 18:14 UTC, frenck requested changes
The installation instructions for Home Assistant are missing on this page. I would suggest (`{% include integrations/config_flow.md %}`.

Additionally, I would recommend putting up the prerequisites (API key) and installation instructions directly after the introduction and move additional documentation below that.

2021-09-27 18:14 UTC, frenck commented on source/_integrations/amberelectric.markdown
> +  - Sensor
Energy?

2021-09-27 18:14 UTC, frenck commented on source/_integrations/amberelectric.markdown
> +[Amber](https://www.amber.com.au/) is an Australian electricity retailer that provides access to wholesale electricity prices. Customers monitor the wholesale price and shift their energy usage to ch
```suggestion
[Amber](https://www.amber.com.au/) is an Australian electricity retailer that provides access to wholesale electricity prices. Customers monitor the wholesale price and shift their energy usage to cheaper, greener times. This saves them money and supports the shift to a more renewably-powered Australia.

Using this integration, customers can go a step further - setting up devices to automatically shift energy usage to cheaper and greener times, based on real-time electricity prices and forecasts.
```

2021-09-27 23:00 UTC, madpilot commented on source/_integrations/amberelectric.markdown
> +[Amber](https://www.amber.com.au/) is an Australian electricity retailer that provides access to wholesale electricity prices. Customers monitor the wholesale price and shift their energy usage to ch
Good feedback - paragraph is now split

2021-09-28 07:20 UTC, frenck approved these changes
Thanks, @madpilot 👍

2021-09-28 07:20 UTC, merged