Update sidebar.markdown
home-assistant/home-assistant.github.io pull request #19394
Opened 2021-09-20 07:39 UTC by cat-inGlasses

The sentence of placing card in sidebar view ws not fully understandable, and contained word "arrow" repeating

## Proposed change

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-09-20 07:39 UTC, homeassistant commented
Hi @cat-inGlasses, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#19394).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-09-22 16:14 UTC, frenck requested changes

2021-09-22 16:14 UTC, frenck commented on source/_lovelace/sidebar.markdown
> +You can set if a card should be placed in the main (left) column or in another column (right) of the sidebar, by pressing the right or left arrow in the bar underneath the card.
It now suggests there is a third column right of the sidebar, which is incorrect.

2021-10-22 21:40 UTC, frenck commented
Since there was no response at all, I'm declaring this PR stale and closing it.
Feel free to re-open this PR when you feel like that is the appropriate thing to do.

2021-10-22 21:40 UTC, closed without merging