Added info about Long term statistics
home-assistant/home-assistant.github.io pull request #19469
Opened 2021-09-25 13:39 UTC by johanf85

## Proposed change

Added some info to the State class description. State class has to be set to `measurement` or `total_increasing` I read on [https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics.](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics.) 

I am not sure if I am right here. But I think I got my template sensors working with setting `State_class: measurement`. 

I think a lot of users would like to know how to add their sensors to long term statistics, so some extra info on this page, by adding this line,  I would consider helpful . 

Also the question, it says only current possible value is `measurement`. Still the case for a template sensor or does this need updating as well?

## Type of change

*   [ ] Spelling, grammar or other readability improvements (`current` branch).
*   [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
*   [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
    *   [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
*   [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
*   [ ] Removed stale or deprecated documentation.

## Additional information

*   Link to parent pull request in the codebase:
*   Link to parent pull request in the Brands repository:
*   This PR fixes or closes issue:

## Checklist

*   [x] This PR uses the correct branch, based on one of the following:
    *   I made a change to the existing documentation and used the `current` branch.
    *   I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
*   [x] The documentation follows the Home Assistant documentation [standards](https://developers.home-assistant.io/docs/documenting/standards).

2021-09-27 09:59 UTC, emontnemery requested changes

2021-09-27 09:59 UTC, emontnemery commented on source/_integrations/template.markdown
> +      description: "Defines the state class of the sensor, if any. Necessary to be set to 'measurement' to include in long term statistics. Only possible value currently is `measurement`. Set this if
```suggestion
      description: "Defines the [state_class](https://developers.home-assistant.io/docs/core/entity/sensor#available-state-classes) of the sensor, if any. Please refer to [state class documentation](https://developers.home-assistant.io/docs/core/entity/sensor#available-state-classes) for which state class, if any, to choose and how it impacts long term statistics."
```

2021-09-27 09:59 UTC, emontnemery commented on source/_integrations/template.markdown
> +      description: "Defines the state class of the sensor, if any. Necessary to be set to 'measurement' to include in long term statistics. Only possible value currently is `measurement`. Set this if
This will get old, maybe we can link to sensor documentation instead.

2021-11-15 14:38 UTC, frenck commented
Closing this PR. It is running stale, has merge conflicts and unresolved comments without a response from the PR author. Feel free to re-open when ready to work on it again.

2021-11-15 14:38 UTC, closed without merging