Update environment_canada for config flow
home-assistant/home-assistant.github.io pull request #19564
Opened 2021-10-02 14:13 UTC by michaeldavie

## Proposed change
Update `environment_canada` to support config flow.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/56908
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-04 10:31 UTC, frenck commented on source/_integrations/environment_canada.markdown
> +  - weather
Note: That seems majorly breaking... 😟

2021-10-04 10:32 UTC, frenck requested changes

2021-10-04 10:32 UTC, frenck commented on source/_integrations/environment_canada.markdown
> +title: Environment Canada Weather
This must match the name in the integration manifest, which now, it doesn't.

2021-10-04 10:32 UTC, frenck commented on source/_integrations/environment_canada.markdown
> +ha_quality_scale: gold
This does not match the integration manifest.

2021-10-04 10:32 UTC, frenck commented on source/_integrations/environment_canada.markdown
> +The `environment_canada` integration provides meteorological data for Canadian locations from [Environment and Climate Change Canada](https://weather.gc.ca/index_e.html).
```suggestion
The Environment Canada integration provides meteorological data for Canadian locations from [Environment and Climate Change Canada](https://weather.gc.ca/index_e.html).
```

2021-10-06 02:30 UTC, michaeldavie commented on source/_integrations/environment_canada.markdown
> +  - weather
Unbroken

2021-10-06 02:30 UTC, michaeldavie commented on source/_integrations/environment_canada.markdown
> +  - weather
This change has been removed

2021-10-06 02:32 UTC, michaeldavie commented
I've updated this PR to reflect the new PR in `core` and to address the requested changes.

2021-10-11 15:51 UTC, frenck requested changes

2021-10-11 15:51 UTC, frenck commented on source/_integrations/environment_canada.markdown
> +The configuration snippet below adds a useful [template sensors](https://www.home-assistant.io/integrations/template/) showing the current "feels like" temperature among air temperature, humidex, and
```suggestion
The configuration snippet below adds a useful [template sensors](/integrations/template/) showing the current "feels like" temperature among air temperature, humidex, and wind chill.
```

2021-10-11 15:51 UTC, frenck commented on source/_integrations/environment_canada.markdown
> +  - platform: template
We should use the new format for this template instead of the old platform format.

See the `template` integration documentation for more information

2021-10-22 09:54 UTC, frenck commented
@michaeldavie Friendly notification, as this might have slipped your mind :)

2021-10-23 02:28 UTC, michaeldavie commented
Thanks, I updated the template according to the new documentation. Please let me know if any other changes are needed.

2021-10-23 09:38 UTC, frenck commented on source/_integrations/environment_canada.markdown
> +  - platform: template
Re-opening this comment.

The sensor templates are moved from being a platform configuration to a integration level configuration. The last change you made, actually broke the template.

Could you take a look?

2021-10-23 14:34 UTC, michaeldavie commented on source/_integrations/environment_canada.markdown
> +  - platform: template
Sorry, I see the problem. I've tested the latest version locally and it's working as designed.

2021-10-23 18:23 UTC, frenck approved these changes
Thanks, @michaeldavie 👍

2021-10-23 18:23 UTC, merged