Update iotawatt.markdown for using the new high accuracy sensors
home-assistant/home-assistant.github.io pull request #19570
Opened 2021-10-03 05:03 UTC by jyavenard

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-04 10:46 UTC, frenck requested changes
I feel like this PR has pending code changes?
Could you point me to the upstream PR?

2021-10-04 10:48 UTC, jyavenard commented
https://github.com/home-assistant/core/pull/55512

this got merged a month ago.

2021-10-04 11:15 UTC, frenck commented
Was that part of 2021.9?

2021-10-04 13:41 UTC, jyavenard commented
> Was that part of 2021.9?

Nope.

2021-10-04 14:57 UTC, frenck commented
In that case, this PR is targeting an incorrect branch, as the `current` branch is the current stable release, which is 2021.9.

Please change the target branch to `next` and perform a git rebase if needed.

2021-10-05 01:09 UTC, jyavenard commented
hmmm this isn't what I wanted it to do :(

2021-10-05 01:11 UTC, jyavenard commented
that's better.

2021-10-06 08:47 UTC, frenck commented on source/_integrations/iotawatt.markdown
> +Starting with Home Assistant 2021.10 you can use the accumulated energy sensors directly with the energy management application.
We don't keep a changelog in our docs. The docs always reflect the current state.

```suggestion
You can use the accumulated energy sensors directly with the Home Assistant energy dashboard.
```

2021-10-06 08:47 UTC, frenck commented on source/_integrations/iotawatt.markdown
> +The iotawatt team recommends that the inputs for solar reads positive which can be achieved by either changing the orientation of the CT sensor or in the IoTaWatt's input settings, check `Reverse`
```suggestion
#### Using a solar net system

The IoTaWatt team recommends that the inputs for solar reads positive which can be achieved by either changing the orientation of the CT sensor or in the IoTaWatt's input settings, check `Reverse`.
```

2021-10-06 08:51 UTC, frenck approved these changes
Thanks, @jyavenard 👍

2021-10-06 08:51 UTC, merged