Fix broken link in TP-Link Kasa Smart
home-assistant/home-assistant.github.io pull request #19586
Opened 2021-10-03 21:48 UTC by scheric

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-03 21:52 UTC, rytilahti requested changes
Thanks for the PR! Looks like that link unfortunately does not exist anymore, but considering that the app is not only available on Android, it'd be better to have something hosted by the vendor instead of a play store link here.

2021-10-03 23:11 UTC, rytilahti commented on source/_integrations/tplink.markdown
> +The `tplink` integration allows you to control your [TP-Link Smart Home Devices](https://www.tp-link.com/kasa-smart/) such as smart plugs, smart wall switches and smart bulbs.
```suggestion
The `tplink` integration allows you to control your [TP-Link Smart Home Devices](https://www.tp-link.com/kasa-smart/) such as plugs, power strips, wall switches, LED strips and bulbs.
```

2021-10-04 08:30 UTC, scheric commented on source/_integrations/tplink.markdown
> +The `tplink` integration allows you to control your [TP-Link Smart Home Devices](https://www.tp-link.com/kasa-smart/) such as smart plugs, smart wall switches and smart bulbs.
Yep, I forgot that one. Thanks

2021-10-04 12:18 UTC, rytilahti approved these changes

2021-10-04 12:18 UTC, merged