Update config for scenes
home-assistant/home-assistant.github.io pull request #19605
Opened 2021-10-05 06:37 UTC by mishmanners

## Proposed change

The previous scene config was confusing, since everything was written in one line. Changed to make it more readable and understandable.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
- I made a change to the existing documentation and used the `current` branch.
- I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards](
[standards]: https://developers.home-assistant.io/docs/documenting/standards).

2021-10-05 06:38 UTC, homeassistant commented
Hi @mishmanners, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#19605).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-10-05 06:47 UTC, frenck requested changes

2021-10-05 06:47 UTC, frenck commented on source/_docs/scene.markdown
> +- entities
Let's incorporate those in the configuration schema below.

2021-10-05 06:47 UTC, frenck commented on source/_docs/scene.markdown
> +  description: Add a friendly name for your scene here
No need to write "here" in all of these, please revert that.

2021-10-05 06:47 UTC, frenck commented on source/_docs/scene.markdown
> +  description: Add which smart objects you want to control here, and their desired state.
We don't call it smart objects. Please change it back to entities.

2021-10-07 05:46 UTC, mishmanners commented
Yeah this is awesome! Thank you, incorporated now and resubmitted (I think). Thanks @frenck :smile:

2021-10-07 05:47 UTC, mishmanners commented on source/_docs/scene.markdown
> +  description: Add which smart objects you want to control here, and their desired state.
Ahhh cool. Thanks for keeping me up to date on naming conventions.

2021-10-07 05:49 UTC, mishmanners commented on source/_docs/scene.markdown
> +  description: Add a friendly name for your scene here
noted.

2021-10-07 05:49 UTC, mishmanners commented on source/_docs/scene.markdown
> +- entities
👍

2021-10-08 04:05 UTC, mishmanners reviewed
All looking good now. Changes made.

2021-10-11 11:12 UTC, frenck commented on source/_docs/scene.markdown
> +- entities
Unresolved this comment, as the requested changes are not applied.

Instead of adding this paragraph, please adjust the configurations section below to reflect these requirements.

2021-10-18 21:48 UTC, mishmanners commented
@frenck let me know if there's anything else I need to do to help get this merged.

2021-10-26 05:29 UTC, mishmanners reviewed
Oops, forgot to click, "submit review". Thanks, still new to all this!

2021-10-26 05:31 UTC, mishmanners commented
So when I look at it, all the changes had already been made... not sure what else I need to do.

2021-10-26 05:32 UTC, mishmanners reviewed
This should be fine yeah @frenck? Let me know if not. Again, sorry, this learning all this :smile:

2021-10-26 05:36 UTC, mishmanners commented on source/_docs/scene.markdown
> +- entities
Okay I think that's what I did now. Please let me know if this is good.

2021-10-26 10:49 UTC, frenck commented
Rebased the PR to deal with an CI issue.

2021-10-26 11:04 UTC, frenck approved these changes
Thanks, @mishmanners 👍

2021-10-26 11:04 UTC, merged