Add push_weather_data Service to Rainmachine
home-assistant/home-assistant.github.io pull request #19600
Opened 2021-10-04 23:17 UTC by shbatm

## Proposed change

Add service to Rainmachine to push weather data from Home Assistant to Rainmachine. This will allow users to send Home Assistant data to the Rain Machine Device to manage the amount of watering required, for example, weather from a local weather station feeding into Home Assistant.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/57051
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-05 19:15 UTC, bachya commented on source/_integrations/rainmachine.markdown
> +Local Weather Push service should be enabled from Settings > Weather > Developer tab for RainMachine to consider the values being sent. Units must be sent in metric; no conversions are performed by t
I would recommend putting these separate thoughts as bullets:

```suggestion
Some key notes:

* Local Weather Push service should be enabled from Settings > Weather > Developer tab for RainMachine to consider the values being sent.
* Units must be sent in metric; no conversions are performed by the integration.
* Note: RAIN and QPF values shouldn't be send as cumulative values; instead, they should reflect the measured/forecasted values for each hour or day. The RainMachine Mixer will sum all RAIN or QPF values in the current day to have the day total RAIN or QPF.
```

2021-10-06 01:15 UTC, bachya approved these changes
Great!

2021-10-08 23:03 UTC, bachya requested changes

2021-10-08 23:03 UTC, bachya commented on source/_integrations/rainmachine.markdown
> +| `condition`            | no       | Current weather condition code (WNUM)                                                                                 |
This was one that I needed to look up (since I didn't know what it was and couldn't deduce it from the name). Found this: https://blog.synopticlabs.org/blog/2016/09/26/weather-condition-codes.html – is this the same thing? If so, what would you think about linking this as a resource?

2021-10-09 00:35 UTC, shbatm commented on source/_integrations/rainmachine.markdown
> +| `condition`            | no       | Current weather condition code (WNUM)                                                                                 |
I think it's actually this: https://github.com/sprinkler/rainmachine-developer-resources/blob/d47e1ad59dee59e34094ad41636ae289275eb973/sdk-parsers/RMDataFramework/rmWeatherData.py#L13

But I've honestly not messed with it much.

2021-10-09 01:05 UTC, bachya commented on source/_integrations/rainmachine.markdown
> +| `condition`            | no       | Current weather condition code (WNUM)                                                                                 |
Ah, okay. Worth putting a reference in these docs or no?

2021-10-09 11:20 UTC, shbatm commented on source/_integrations/rainmachine.markdown
> +| `condition`            | no       | Current weather condition code (WNUM)                                                                                 |
Added a reference. I can't tell if it actually does anything however, so I don't know if it is actually still the correct reference. It seems to accept any string or integer. The Push data seems to have some variances to the custom parsers so YMMV. If they publish more details or someone sorts out that it's looking for something else, we can adjust the reference down the road.

2021-10-09 16:15 UTC, bachya commented
@shbatm Looks good, but let's wait for https://github.com/home-assistant/home-assistant.io/pull/19622 to be merged and rebase off of `next`. I'll keep you posted.

2021-10-11 15:11 UTC, bachya commented
@shbatm https://github.com/home-assistant/home-assistant.io/pull/19622 is merged, FYI.

2021-10-12 10:34 UTC, shbatm commented on source/_integrations/rainmachine.markdown
> +- Services that require a device ID as a target:
This is linting from the home-assistant.io devcontainer. Let me know if you want me to exclude.

2021-10-12 13:40 UTC, bachya commented on source/_integrations/rainmachine.markdown
> +- Services that require a device ID as a target:
That's fine.

2021-10-12 13:40 UTC, bachya submitted a review, later dismissed
Thanks!

2021-10-22 09:55 UTC, frenck commented on source/_integrations/rainmachine.markdown
> +Local Weather Push service should be enabled from Settings > Weather > Developer tab for RainMachine to consider the values being sent. Units must be sent in metric; no conversions are performed by t
```suggestion
Push Weather Data from Home Assistant to the RainMachine device.

Local Weather Push service should be enabled from Settings > Weather > Developer tab for RainMachine to consider the values being sent. Units must be sent in metric; no conversions are performed by the integration. Note: RAIN and QPF values shouldn't be sent as cumulative values but the measured/forecasted values for each hour or day. The RainMachine Mixer will sum all RAIN or QPF values in the current day to have the day total RAIN or QPF.
```

2021-10-22 09:55 UTC, frenck commented on source/_integrations/rainmachine.markdown
> +See details of RainMachine API Here: https://rainmachine.docs.apiary.io/#reference/weather-services/parserdata/post
```suggestion
See details of RainMachine API here: 
<https://rainmachine.docs.apiary.io/#reference/weather-services/parserdata/post>
```

2021-10-22 09:55 UTC, frenck approved these changes
Thanks, @shbatm 👍

2021-10-22 09:59 UTC, merged