update Brother integration examples with new template sensor format
home-assistant/home-assistant.github.io pull request #19656
Opened 2021-10-07 19:08 UTC by cturra

## Proposed change
template sensor configurations were changed in 2021.4 and the Brother printer integration documents still reference the legacy format.  just a quick update to correct that.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: N/A
- Link to parent pull request in the Brands repository: N/A
- This PR fixes or closes issue: N/A

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-07 19:08 UTC, homeassistant commented
Hi @cturra, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#19656).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-10-09 10:53 UTC, bieniu commented on source/_integrations/brother.markdown
> +        {{ is_state('sensor.<DEVICE_NAME>_status', 'paper jam') }}
I'm not sure if we should use `<DEVICE_NAME>` here, user may have changed entity_id. IMO it's better to use `sensor.hl_l2340d_status` as an example.

2021-10-09 21:19 UTC, cturra commented on source/_integrations/brother.markdown
> +        {{ is_state('sensor.<DEVICE_NAME>_status', 'paper jam') }}
agreed.

2021-10-11 10:27 UTC, frenck requested changes

2021-10-11 10:27 UTC, frenck commented on source/_integrations/brother.markdown
> +        {{ is_state('sensor.hl_l2340d_status', 'paper jam') }}
I would not recommend setting the `unique_id` in the example. For different reasons:

- It is optional.
- The suggested IDs I would not recommend (use of UUIDs is generally safer).

```suggestion
template:
  - binary_sensor:
    - name: 'Laser Printer Out Of Paper'
      state: >
        {{ is_state('sensor.hl_l2340d_status', 'no paper') }}

  - binary_sensor:
    - name: 'Later Printer Paper Jam'
      state: >
        {{ is_state('sensor.hl_l2340d_status', 'paper jam') }}
```

2021-10-11 14:56 UTC, frenck approved these changes
Thanks, @cturra 👍 

Happy Hacktoberfest 🎉 

../Frenck

2021-10-11 14:56 UTC, merged