Replace Synology DSM services with buttons
home-assistant/home-assistant.github.io pull request #19677
Opened 2021-10-08 21:09 UTC by mib1185

## Proposed change

The services `reboot` and `shutdown` are deprecated and will be removed in future release. Please use the new button entities.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core/pull/57352
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-01-07 11:59 UTC, frenck commented
not stale bot... thanks :)

2022-01-25 09:20 UTC, mib1185 commented
TBH i do not have any clue about this CI jobs 🙈 

This is the only error I see in the respective log

https://app.netlify.com/sites/home-assistant-docs/deploys/61ef1a5b5f85290008285977
```
[...]
10:35:44 PM: JSON::ParserError: 783: unexpected token at '<html><body>You are being <a href="https://community.home-assistant.io/l/top?period=all">redirected</a>.</body></html>'
10:35:44 PM: /opt/build/repo/Rakefile:225:in `block in <top (required)>'
/opt/build/cache/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/build/cache/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'
/opt/build/cache/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => blueprint_exchange_data
[...]
```

2022-01-25 09:52 UTC, frenck commented
Rebased the PR to deal with the CI issues

2022-01-25 10:02 UTC, frenck requested changes

2022-01-25 10:02 UTC, frenck commented on source/_integrations/synology_dsm.markdown
> +
We don't keep a log of deprecations in our documentation.
Please remove this note and the deprecated services from the documentation instead.

2022-01-25 12:16 UTC, mib1185 commented on source/_integrations/synology_dsm.markdown
> +
yeah, makes absolutely sense 👍

2022-01-25 13:05 UTC, frenck approved these changes
Thanks, @mib1185 👍

2022-01-25 13:05 UTC, merged