Spell check dict update
home-assistant/home-assistant.github.io pull request #19730
Opened 2021-10-12 07:43 UTC by stefanroelofs

## Proposed change
Update the `cSpell.json` file with often used keywords.
This file is used by the `Code Spell Checker` extension in VS Code.
This extension is recommended to install because it is listed in `extensions.json`.

Is this usefull to commit?

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-12 08:40 UTC, frenck requested changes
Make the first comment, then realized the capitalization of words has been removed. Please restore that and make sure it is correct for new additions as well.

2021-10-12 08:40 UTC, frenck commented on .vscode/cSpell.json
> +    "btle",
`BTLE` is an abbreviation and should be capitalized

2021-10-12 08:49 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "btle",
I actually deliberately lowercased the list since the spellchecker is case insensitive.
But I'll fix it. 
Thanks

2021-10-12 09:54 UTC, stefanroelofs commented
Alright, I've added capitalisation back to the list.
This change is mostly cosmetic, since the spell checker is case-insensitive.
Also most keywords are used with various (camel-case) capitalisation throughout the code.
Thanks.

2021-10-14 07:15 UTC, frenck requested changes

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "homeassistant",
Dit is niet de juiste schrijfwijze voor "Home Assistant"
```suggestion
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "hassos",
Duplicaat met erboven
```suggestion
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "homekit",
```suggestion
    "HomeKit",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "ignorecase",
Ignore case are two words

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "ifttt",
```suggestion
    "IFTTT",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "codeowners",
These are two words

```suggestion
    "codeowners",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "commandline",
Command Line is two words (and also additional complicated to spellcheck like this, as it has to be written hyphenated in some cases: Command-Line)

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "duckdns",
The correct style of writing according to their website is: `Duck DNS`

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "eventstream",
```suggestion
    "EventStream",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "everspring",
```suggestion
    "Everspring",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "gpslogger",
```suggestion
    "GPSLogger",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "landingpage",
These are two words

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "lutron",
```suggestion
    "Lutron",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "meteobridge",
```suggestion
    "Meteobridge",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "Nabu",
```suggestion
    "Nabu Casa",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "nijhof",
```suggestion
    "Nijhof",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "nmap",
```suggestion
    "Nmap",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "openzwave",
```suggestion
    "OpenZWave",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "owntracks",
```suggestion
    "OwnTracks",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "powerwall",
```suggestion
    "Powerwall",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "pushbullet",
```suggestion
    "Pushbullet",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "schoutsen",
```suggestion
    "Schoutsen",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "smartthings",
```suggestion
    "SmartThings",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "tradfri",
```suggestion
    "TRÅDFRI",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "tuya",
```suggestion
    "Tuya",
```

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "worldclock",
These are two words

2021-10-14 07:15 UTC, frenck commented on .vscode/cSpell.json
> +    "ZWave"
Incorrect spelling 
```suggestion
    "Z-Wave"
```

2021-10-14 08:31 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "tradfri",
The word tradfri is used 294 times in the documentation. The md file is called: tradfri.markdown. I'd suggest leaving it in the spell checker, and add the string TRÅDFRI

2021-10-14 08:35 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "ZWave"
The word zwave is used 1653 times in documentation. Services are prefixed with zwave_. I'd suggest leaving it in, and add the  Z-Wave string.

2021-10-14 08:37 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "worldclock",
`webhook` is the name of the platform. 'Web hook' as 2 words is no problem for the spell checker. I'd suggest leaving it in.

2021-10-14 08:38 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "worldclock",
(same goed for WLED and worldclock, these are the names for sensors / platforms)

2021-10-14 08:41 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "ignorecase",
`ignorecase` is used only 6 times in the documentation, as a parameter for the match() and search() functions. I will remove this string.

2021-10-14 08:43 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "homeassistant",
`homeassistant` is used over a 1000 times in the documentation. For example the `homeassistant.turn_on` service call. I'd suggest leaving it in.

2021-10-14 08:48 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "codeowners",
`codeowners` is used in the metadata for every markdown file. In `ha_codeowners:` I'd suggest leaving this in.

2021-10-14 08:51 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "commandline",
I agree. Also this string is hardly used in the documentation. I'll remove the keyword.

2021-10-14 08:54 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "duckdns",
`duckdns` is the name of the HA platform, and is used a lot in the documentation. I'd suggest leaving it in. 
(the separate words duck and dns are no problem for the spell checker)

2021-10-14 08:56 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "eventstream",
`eventstream` is used more in lowercase than with a kapital. Like in: `mqtt_eventstream:` . I'd suggest leaving it in lowercase. 
( the spell checker disregards kapitalisation anyways)

2021-10-14 09:03 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "landingpage",
`landingpage` is used a lot in code. (as the name of a layout). I'd suggest leaving it in.
Same goes for `keepalive' as a parameter in yaml configurations.

2021-10-14 09:08 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "Nabu",
The list of keywords actually can not handle spaces. Only single words are accepted. That's why i've added `Nabu`. 
`Casa` is already a valid word for the spell checker.

2021-10-14 09:09 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "nijhof",
Of course! :)

2021-10-14 09:16 UTC, stefanroelofs commented
Thanks for your suggestinos.
I've finished with all of them. Can you review my comments? Thanks.

2021-10-14 09:17 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "ZWave"
Actually, Z-Wave is not a problem for the spell checker, so there is no need to add this keyword.

2021-10-14 09:29 UTC, frenck commented on .vscode/cSpell.json
> +    "ZWave"
> Services are prefixed with zwave_. I'd suggest leaving it in, and add the Z-Wave string

Services are code and should be code fenced to prevent the spellchecker to interfere.
This is incorrect spelling and should be removed from the dictionary.

2021-10-14 09:29 UTC, frenck commented on .vscode/cSpell.json
> +    "worldclock",
platform names should be code fenced, not whitelisted in the spellchecker

2021-10-14 09:30 UTC, frenck commented on .vscode/cSpell.json
> +    "tradfri",
The filename doesn't matter for a spell checker.
Its is a brand/product name, which should be written correctly.

2021-10-14 09:30 UTC, frenck commented on .vscode/cSpell.json
> +    "ignorecase",
Those are code occurrances. If they trigger the spellchecker it has been displayed wrong in the documentation to begin with. Please remove this occurance.

2021-10-14 09:30 UTC, frenck commented on .vscode/cSpell.json
> +    "codeowners",
That is frontmatter and should not trigger the spellchecker.

2021-10-14 09:31 UTC, frenck commented on .vscode/cSpell.json
> +    "duckdns",
platform names must be fenced, not exempted in the spellchecker. We need to fix those occurrences. Please spell it correctly here or remove it from this file.

2021-10-14 09:32 UTC, frenck commented on .vscode/cSpell.json
> +    "homeassistant",
Those should be codefenced, not silenced in the spellchecker. Please remove it from this file.

2021-10-14 09:32 UTC, frenck commented on .vscode/cSpell.json
> +    "landingpage",
code must not trigger the spellchecker. If it does, it is wrongly used/displayed in the documentation that needs fixing, not silencing. 

Please remove this occurance.

2021-10-14 09:40 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "ZWave"
Well, the spell checker that we use (https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) is specifically ment to be used on source code. The spell checker is used by writers / maintainers of the documentation and website. Not by users of Home Assistant.

So code fencing has no effect on the spell checker. The only option you have is prefixing lines with `// cSpell:disable` but that is not workable in my opinion.

`zwave` is correct spelling if you are writing yaml files, not?
But if you're sure I will remove the keyword.

2021-10-14 10:59 UTC, frenck commented on .vscode/cSpell.json
> +    "ZWave"
codefenced text/blocks are not spellchecked...

2021-10-20 08:22 UTC, stefanroelofs commented on .vscode/cSpell.json
> +    "ZWave"
Hi,

Are you sure about the fact that codefenced text is not spellchecked?
You mean code blocks that are between 3 backticks?

In my instance of VS Code the complete .md file is spellchecked:
![image](https://user-images.githubusercontent.com/37924749/138055122-7504d747-0e44-4c08-b7d1-c1159fd9ca62.png)

Maybe there is a setting for this, but I cannot find it.


Also in the dictionaries that the spell checker uses ([for example](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/software-terms/src/software-terms.txt)) there are lots of code keywords that are not correct English. Like I said, the spell checker is ment to be used on source code.

But if you think y're right, I will resolve the requested changes. No problem. 
Thanks!

2021-10-21 08:11 UTC, stefanroelofs commented
I've implemented your suggestions to the list.
Thanks!

2021-10-22 10:32 UTC, frenck approved these changes
Thanks, @stefanroelofs 👍 

Happy Hacktoberfest 🎉 

../Frenck

2021-10-22 10:32 UTC, merged