Document config of individual energy sensor device
home-assistant/home-assistant.github.io pull request #19765
Opened 2021-10-14 07:52 UTC by EetuRasilainen

Document manual configuration of energy sensor for individual devices

As talked about on discord #energy channel

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-14 08:07 UTC, frenck requested changes

2021-10-14 08:07 UTC, frenck commented on source/_docs/energy/individual-devices.markdown
> +Energy usage of individual devices should be set up by the device's integration automatically. However, if you do need to enable this for a manually configured energy sensor (such as a [template sens
Aren't those documented in the integration documentation already?

2021-10-14 08:07 UTC, frenck commented on source/_docs/energy/individual-devices.markdown
> +* The sensor needs to have it's `state_class` set to `total_increasing`
This is incomplete, as it is not limited to this.

2021-10-14 10:03 UTC, EetuRasilainen commented on source/_docs/energy/individual-devices.markdown
> +Energy usage of individual devices should be set up by the device's integration automatically. However, if you do need to enable this for a manually configured energy sensor (such as a [template sens
Not really. If you are [searching for bugs](https://github.com/home-assistant/home-assistant.io/issues?utf8=%E2%9C%93&q=%22%2Fdocs%2Fenergy%2Findividual-devices%2F%22&in=body) for this particular page (`individual-devices.markdown`) you can see that people expect that documentation right at this page. The integrations just mention the attribute `state_class`, but not that it's directly related to energy monitoring for individual devices using the energy dashboard.

2021-10-14 10:07 UTC, EetuRasilainen commented on source/_docs/energy/individual-devices.markdown
> +* The sensor needs to have it's `state_class` set to `total_increasing`
Hmm, okay. The "docs" (a.k.a. pinned messages) at the #ernergy discord channel mention exactly these two things as requirements. And for my custom MQTT sensors that was all that was required. What exactly is missing here? I have been looking everywhere to find more information about this, but it does not seem to be documented anywhere - that's why I started this litte documentation effort :smiley:

2021-10-14 10:51 UTC, frenck commented on source/_docs/energy/individual-devices.markdown
> +Energy usage of individual devices should be set up by the device's integration automatically. However, if you do need to enable this for a manually configured energy sensor (such as a [template sens
Well, this page provides generic content on the fact it can monitor individual devices. There is nothing technical on this page and we should keep it that way.

I think it is fine to refer to the integrations that could provide such information. I think the integration integration should be part of the list in that case as well.

2021-10-14 10:53 UTC, frenck commented on source/_docs/energy/individual-devices.markdown
> +* The sensor needs to have it's `state_class` set to `total_increasing`
There are more permutations, for example, it could use a different state class as well, for example `total`. Those are two really different state classes and you have to pick the right one or else you will end up with incorrect stats or warnings.

As for the unit of measurement, it is normalized to `kWh`, but you can provide other units as well, like `Wh`.

Nevertheless, this page provides generic information. These details do not belong on this page.

2021-10-14 12:05 UTC, Mariusthvdb commented on source/_docs/energy/individual-devices.markdown
> +* The sensor needs to have it's `state_class` set to `total_increasing`
fyi, have a look at https://developers.home-assistant.io/docs/core/entity/sensor/#how-to-choose-state_class-and-last_reset

2021-11-15 14:09 UTC, frenck commented
Closing this PR, as I truly believe this is being added in an inappropriate location.

2021-11-15 14:09 UTC, closed without merging