Add description for Sleep Timer services of Yamaha MusicCast
home-assistant/home-assistant.github.io pull request #19817
Opened 2021-10-17 15:23 UTC by micha91

## Proposed change

In this PR we add the documentation of the sleep timer related services, introduced in the referenced PR.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/57910
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-17 15:49 UTC, frenck requested changes

2021-10-17 15:49 UTC, frenck commented on source/_integrations/yamaha_musiccast.markdown
> +Some MusicCast devices support sleep timers. Sleep timers can be used to turn of the device after a given amount of minutes.
```suggestion
Some MusicCast devices support sleep timers. Sleep timers can be used to turn off the device after a given amount of minutes. 
```

2021-10-17 15:49 UTC, frenck commented on source/_integrations/yamaha_musiccast.markdown
> +  entity_id: media_player.wohnzimmer_zone2
```suggestion
  entity_id: media_player.living_room_zone2
```

2021-10-17 15:49 UTC, frenck commented on source/_integrations/yamaha_musiccast.markdown
> +  entity_id: media_player.wohnzimmer_zone2
```suggestion
  entity_id: media_player.living_room_zone2
```

2021-10-17 16:52 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-12-07 17:04 UTC, micha91 commented
will be available as select entity, see [here](https://github.com/home-assistant/core/pull/60645)

2021-12-07 17:04 UTC, closed without merging