updating utility_meter example to use new template format
home-assistant/home-assistant.github.io pull request #19826
Opened 2021-10-17 22:08 UTC by cturra

## Proposed change
updating `utility_meter` example to use new template format introduced in 2021.4. i also took the opportunity to demonstrate setting the appropriate `device_class` .

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: N/A
- Link to parent pull request in the Brands repository: N/A
- This PR fixes or closes issue: N/A

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-18 08:00 UTC, dgomes commented
Thank you for your contribution!

I would also advise to change the `float` filter in accordance to https://www.home-assistant.io/docs/configuration/templating/#numeric-functions-and-filters

2021-10-18 20:49 UTC, dgomes commented
OK.... my comment was towards address a common situation in which `peak` or `offpeak` values are unavailable and the cast to float results in `0` and not `unavailable`

2021-10-19 04:00 UTC, cturra commented
thanks for the feedback @dgomes and i apologize for not getting this right away. hopefully my last commit gets closer to what you're looking for. :metal:

2021-10-19 08:18 UTC, dgomes submitted a review, later dismissed

2021-10-21 17:03 UTC, cturra commented
anything outstanding on this pr to get it across the line? happy to help if there are any action items required for me.

2021-10-22 10:33 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +we use a [float filter](https://www.home-assistant.io/docs/configuration/templating/#numeric-functions-and-filters) to
```suggestion
we use a [float filter](/docs/configuration/templating/#numeric-functions-and-filters) to
```

2021-10-22 10:35 UTC, frenck requested changes

2021-10-22 10:35 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +        {% set offpeak = float(states('sensor.daily_energy_offpeak'), default='Invalid Number') %}
This is not correct usage of the float default.

The float default can provide an alternative float value in case the value can't be parsed as a float, and is not means to provide an alternative string.

The state of this sensor should be returning an int or float value, otherwise, it should become unknown.

If you want to check if a value is numeric, you can use the `is_number` template method.

2021-10-22 16:20 UTC, cturra commented on source/_integrations/utility_meter.markdown
> +        {% set offpeak = float(states('sensor.daily_energy_offpeak'), default='Invalid Number') %}
thanks for this feedback @frenck and that makes a lot of sense to me. i want to take a step back here though -- i feel like we're making this example too complicated for a newer user. the intent of my change was to simply update to the new template format. if you both see value in continuing down this path, i'm happy to help, but i'm not convinced it's the best. sorry for being difficult, but this has been on my mind for a bit. /cc: @dgomes

2021-10-22 17:22 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +        {% set offpeak = float(states('sensor.daily_energy_offpeak'), default='Invalid Number') %}
Well, the fact is, the current example is wrong, so we can't merge it in this state.

2021-10-22 17:32 UTC, cturra commented on source/_integrations/utility_meter.markdown
> +        {% set offpeak = float(states('sensor.daily_energy_offpeak'), default='Invalid Number') %}
absolutely! no argument there and sorry if i miscommunication my intentions, but that was not what i meant. i was proposing we backed up to the original proposal of simply updating the template format. to clean the slate, i'm happy to close off this pr and propose a new one.. or leave it.

2021-10-22 17:52 UTC, dgomes commented
The current example is actually very bad and the cause of some issue reports where one of the source sensors is unavailable causing havoc in the energy panel. Even-though complex I think it is necessary to document it officially, can't we default to "unavailable" @frenck ?

2021-10-22 18:19 UTC, frenck commented
> can't we default to "unavailable" @frenck ?

Unavailable is a state where the devices are unreachable, which is something that should not be set from here IMHO.

I think the best approach is to check if the current value is a number else, return no value.

2021-10-22 18:27 UTC, cturra commented
... or, should we come up with a different example that still demonstrates something related to the utility-meter integration and is more new  user friendly?

2021-10-22 19:27 UTC, dgomes commented
defaulting to 0 is bad (it will cause havoc with statistics) 

I only see as an option adding `unavailable` to the template (not state = unavailable)

2021-10-25 20:25 UTC, cturra commented
thanks for your patience with my response here gents. i've refactored the example to confirm `peak` and  `offpeak` values are numeric. if that's true, then i add the values, if not, i return the string: `Invalid Number`

2021-10-26 06:44 UTC, cturra commented on source/_integrations/utility_meter.markdown
> +        {% set offpeak = float(states('sensor.daily_energy_offpeak'), default='Invalid Number') %}
i've refactored the example to use the `is_number()` function in my [last commit](https://github.com/home-assistant/home-assistant.io/pull/19826/commits/3a00e2bd0818f7bd5e20c4e944bd7c974c75a313).

2021-10-26 07:32 UTC, frenck requested changes

2021-10-26 07:32 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
"Invalid Number" is not a valid state for a sensor with a kWh unit of measurement.

```suggestion
```

2021-10-26 07:32 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
```suggestion
```

2021-10-26 16:25 UTC, cturra commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
setting to `unknown` instead, which i believe is consistent with what home assistant does today. if i've got that wrong, please let me know.

2021-10-26 16:26 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
Yes, that is wrong, `unknown` is a result of the state engine getting `None` value.

2021-10-26 16:43 UTC, cturra commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
alright. i think it's time for me to bow-out of this pull request. i'm trying to help, but clearly, playing wack-a-mole isn't going to get this done. sorry for not being able to get this across the line.

2021-10-26 16:48 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
? I have the exact suggestion that was needed, instead, you ignored it and did something else and are now bow-out because playing "wack-a-mole"?

Interesting.

Thanks for trying though.

../Frenck

2021-10-26 16:50 UTC, cturra commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
maybe i misread - were you suggesting i set the value to `None` instead?

2021-10-26 16:50 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
Nowhere. None isn't a value.

Hence the removal of the else:

![image](https://user-images.githubusercontent.com/195327/138924817-6977737a-e1bf-47d1-8588-02a96bf39ae0.png)


It returns nothing, thus None.

2021-10-26 16:54 UTC, cturra commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
i misunderstood the review (github interface). my bad - update incoming that matches.

2021-10-26 16:55 UTC, cturra commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
oh. i think i found it!

> I think the best approach is to check if the current value is a number else, return no value.

would this be acceptable then? 

```
      state: >
        {% if is_number(states('sensor.daily_energy_offpeak')) and is_number(states('sensor.daily_energy_peak')) %}
          {{ (states('sensor.daily_energy_offpeak') + states('sensor.daily_energy_peak')) | float }}
        {% endif %}
```

2021-10-26 16:59 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
Yes, I think that would return None. As it is processed as a native type. I'm going to test that out. Hold on.

2021-10-26 17:04 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
I guess we are both wrong. It will now return an empty string 😢 

So what happens, is that the result of a Jinja2 template is always a string. That string is evaluated by Python, to find a type of the value that is returned. An empty string, is a... string :(

So is "unknown", however, that is a result of the state engine when there is no state (None).

So, apparently, the trick is to return `None` explicitly. When that is evaluated by Python, it recognizes it, and will actually be a `None` type value.

```suggestion
        {% else %}
          None
```

In some way, thanks! Because this was a refresh course for me even (even though I wrote part of this handling 😟 )

2021-10-26 17:22 UTC, cturra commented on source/_integrations/utility_meter.markdown
> +          Invalid Number
thanks for sharing that - it'll definitely be useful to understand for me also.

i think because of all the back-and-forth, github is grumpy with these comments being against an outdated commit, so i cannot approve the change through the ui. will follow up with a commit on my end to reflect this suggestion.

2021-10-26 17:25 UTC, frenck submitted a review, later dismissed
Nice 👍

2021-10-26 17:25 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +        {% set offpeak = float(states('sensor.daily_energy_offpeak'), default='Invalid Number') %}
👍  Nice!

2021-10-26 17:33 UTC, frenck commented
Rebased to PR onto the latest `current` branch to deal with the build error.

2021-10-26 17:40 UTC, frenck approved these changes

2021-10-26 17:40 UTC, merged