Improve documentation for history-graph #19893
home-assistant/home-assistant.github.io pull request #19895
Opened 2021-10-21 20:00 UTC by koskila

## Proposed change

#19893 shows documentation for history-graph might be lacking. This change makes it more clear how to customize how history-graph (and many other cards) figure out how to display different entities.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: #19893 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-21 20:00 UTC, homeassistant commented
Hi @koskila, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#19895).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-10-22 08:46 UTC, frenck requested changes

2021-10-22 08:46 UTC, frenck commented on source/_lovelace/history-graph.markdown
> +Changing the units used to generate the graphs requires changing the entities' unit_of_measurement property, as it can't be overridden on the history-graph card. For more details, see [Customizing En
This is, unfortunately, no longer true. State classes are also considered nowadays.
Additionally, we really don't want to recommend customizing devices, as we consider it bad practice.

2021-10-22 08:46 UTC, frenck commented on source/_lovelace/history-graph.markdown
> +```yaml
Add a small description before the example to explain what it does / why it is here.

2021-10-22 08:46 UTC, frenck commented on source/_lovelace/history-graph.markdown
> +title: 'Temperatures in the last 48 hours'
```suggestion
title: "Temperatures in the last 48 hours"
```

2021-10-22 08:46 UTC, frenck commented on source/_lovelace/history-graph.markdown
> +    name: Lounge
```suggestion
    name: "Lounge"
```

2021-10-22 08:46 UTC, frenck commented on source/_lovelace/history-graph.markdown
> +    name: Attic
```suggestion
    name: "Attic"
```

2021-10-22 18:38 UTC, koskila commented on source/_lovelace/history-graph.markdown
> +Changing the units used to generate the graphs requires changing the entities' unit_of_measurement property, as it can't be overridden on the history-graph card. For more details, see [Customizing En
Thanks for your comments! Good to be learning more, thought I was up-to-speed here but I clearly wasn't!

I can see why customizing entities would be seen as bad practice - what's the best alternative, if one needs to change the unit of measurement for an entity they haven't explicitly created themselves?

2021-10-22 18:42 UTC, frenck commented on source/_lovelace/history-graph.markdown
> +Changing the units used to generate the graphs requires changing the entities' unit_of_measurement property, as it can't be overridden on the history-graph card. For more details, see [Customizing En
In those cases, I would say it is a bug and should be reported so it can be fixed (instead of worked around).

2021-10-22 18:54 UTC, koskila commented on source/_lovelace/history-graph.markdown
> +Changing the units used to generate the graphs requires changing the entities' unit_of_measurement property, as it can't be overridden on the history-graph card. For more details, see [Customizing En
Fair enough - thanks!

2021-10-22 19:25 UTC, koskila commented on source/_lovelace/history-graph.markdown
> +```yaml
Done 👍

2021-10-22 19:44 UTC, frenck approved these changes
Thanks, @koskila 👍 

Happy Hacktoberfest 🎉 

../Frenck

2021-10-22 19:44 UTC, merged