Fix value template for detecting lost connections
home-assistant/home-assistant.github.io pull request #19941
Opened 2021-10-24 10:05 UTC by selmaohneh

The current sample did not work. The sensor stayed unavailable, the template editor showed errors. Here is a working version.

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-24 10:05 UTC, homeassistant commented
Hi @selmaohneh, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#19941).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-10-24 15:42 UTC, frenck requested changes

2021-10-24 15:42 UTC, frenck commented on source/_integrations/homematic.markdown
> +          {{(as_timestamp(now())-as_timestamp(states.sensor.office_voltage.last_changed)) < 600}}
We should never access `states.X` directly, this is bad practice and something we highly discourage. If that is needed, we should at least have the proper checks in the template, to prevent accessing a non-existing entity state object.

Also, you've adjusted the example to no longer match our styling guide. Could you please add back the spacing?

2021-10-27 06:57 UTC, selmaohneh commented
Thanks for the review!

Just to prove my point:

![image](https://user-images.githubusercontent.com/29881939/139014610-969832cc-ba82-4017-a68b-09ea00985052.png)

Accessing `last_changed` seems to be only possible via `states.X`. The templating documentation does this as an example, as well:

![image](https://user-images.githubusercontent.com/29881939/139014771-2a661740-a7fc-4a62-aecd-5d94b51773d3.png)

So is last_changed some kind of special attribute? I guess so since it as not listed as other attributes but on the right side in the developer tools:

![image](https://user-images.githubusercontent.com/29881939/139015129-608ee4ef-d162-47b0-b695-5138ac1d4b03.png)

I want to understand that - adding the needed checks would just fix the symptoms.  I think allowing `state_attr` to work with `last_changed` would be the prefered fix.

Thoughts @frenck ?

2021-10-27 07:29 UTC, frenck commented
My thoughts are in my previous review, we should not access the states object directly.

2022-01-04 14:19 UTC, frenck requested changes

2022-01-04 14:19 UTC, frenck commented on source/_integrations/homematic.markdown
> +          {{(as_timestamp(now())-as_timestamp(states.sensor.office_voltage.last_changed)) < 600}}
This suggestion will do:

```suggestion
          {{ (now() - states.sensor.office_voltage.last_changed).seconds < 600 }}
```

2022-01-11 16:05 UTC, closed without merging