Update orangepi_gpio.markdown
home-assistant/home-assistant.github.io pull request #19956
Opened 2021-10-25 09:41 UTC by drizzle1

## Proposed change

updated for pi4 and pi4B boards

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 

https://github.com/home-assistant/core/pull/58392

- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-25 10:04 UTC, frenck requested changes
This PR is based on the branch (`current`), while it targets `next`.
Please rebase to clean it up.

2021-10-25 12:07 UTC, pascallj requested changes

2021-10-25 12:07 UTC, pascallj commented on source/_integrations/orangepi_gpio.markdown
> +| RK3399 (PI4, PI4B) | 21/28 |
```suggestion
| RK3399 (PI4, PI4B) | 28/28 |
```
[We have verified all pins work](https://github.com/rm-hull/OPi.GPIO/pull/57), so this should now be changed.

2021-10-26 07:33 UTC, frenck commented
@drizzle1 You have now changed the target, but you'll need to perform a git rebase as well.

2021-10-26 11:33 UTC, closed without merging