Refereshed links
home-assistant/home-assistant.github.io pull request #19950
Opened 2021-10-24 18:41 UTC by EgonMarmol

Updated a handful of old links on the Securing page.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-24 19:08 UTC, frenck commented on source/_docs/configuration/securing.markdown
> +Other options are to use TLS/SSL via the add-ons [Duck DNS integrating Let's Encrypt](/integrations/duckdns/) or [Let’s Encrypt](https://community.home-assistant.io/t/installing-tls-ssl-using-lets-en
That is actually a community guide and should be removed.

2021-10-24 19:09 UTC, frenck requested changes
See comment above

2021-10-24 21:05 UTC, EgonMarmol commented on source/_docs/configuration/securing.markdown
> +Other options are to use TLS/SSL via the add-ons [Duck DNS integrating Let's Encrypt](/integrations/duckdns/) or [Let’s Encrypt](https://community.home-assistant.io/t/installing-tls-ssl-using-lets-en
@frenck Thanks for the heads up. The original link redirected to the community URL. Do you want me to remove the reference to Let's Encrypt entirely, or change it to something else like this blog post: https://www.home-assistant.io/blog/2017/09/27/effortless-encryption-with-lets-encrypt-and-duckdns/

2021-10-25 06:52 UTC, frenck commented on source/_docs/configuration/securing.markdown
> +Other options are to use TLS/SSL via the add-ons [Duck DNS integrating Let's Encrypt](/integrations/duckdns/) or [Let’s Encrypt](https://community.home-assistant.io/t/installing-tls-ssl-using-lets-en
That blog post is heavily outdated as well. Let's remove it.

2021-10-25 09:49 UTC, EgonMarmol commented on source/_docs/configuration/securing.markdown
> +Other options are to use TLS/SSL via the add-ons [Duck DNS integrating Let's Encrypt](/integrations/duckdns/) or [Let’s Encrypt](https://community.home-assistant.io/t/installing-tls-ssl-using-lets-en
@frenck Thanks for clarifying. I will fix.

2021-10-25 09:54 UTC, EgonMarmol commented on source/_docs/configuration/securing.markdown
> +Other options are to use TLS/SSL via the add-ons [Duck DNS integrating Let's Encrypt](/integrations/duckdns/) or [Let’s Encrypt](https://community.home-assistant.io/t/installing-tls-ssl-using-lets-en
@frenck The changes have now been applied.

2021-10-25 10:03 UTC, frenck approved these changes
Thanks, @EgonMarmol 👍

2021-10-25 10:03 UTC, merged