Fix markdownlint / spelling  issues #3
home-assistant/home-assistant.github.io pull request #19961
Opened 2021-10-25 13:12 UTC by stefanroelofs

## Proposed change

Fix several issues related to markdownlint and spelling.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-25 14:29 UTC, frenck requested changes

2021-10-25 14:29 UTC, frenck commented on source/_integrations/buienradar.markdown
> +- **Rain n days ahead**: "The forecasted amount of rain in [mm](https://en.wikipedia.org/wiki/Millimeter) n days ahead; the average of minimum_rain_1d and maximum_rain_1d."
You can't just spell correct this. These are actual keys.
Do you have a PR that adjusts this in our codebase?

2021-10-25 14:29 UTC, frenck commented on source/_integrations/buienradar.markdown
> +- **Wind azimuth n days ahead**: Where the wind is coming from in degrees, with true north at 0° and progressing clockwise for n days ahead. (derived from wind_direction_1d)
same as above

2021-10-25 14:29 UTC, frenck commented on source/_integrations/buienradar.markdown
> +- **Wind speed n days ahead**: "The expected wind speed in [m/s](https://en.wikipedia.org/wiki/M/s) n days ahead (derived from wind force_1d)."
same as above

2021-10-25 14:29 UTC, frenck commented on source/_integrations/cisco_webex_teams.markdown
> +* then copying the room ID from the URL.
This is a list of item 2. This should be indented to make it appear it is part of that.

2021-10-25 14:29 UTC, frenck commented on source/_integrations/cisco_webex_teams.markdown
> +**Note: you must add the bot email (in the format `mybot@webex.bot`) as a participant to the room specified above.**
Let use actual notes as per developer documentation.

2021-10-25 15:01 UTC, stefanroelofs commented on source/_integrations/buienradar.markdown
> +- **Rain n days ahead**: "The forecasted amount of rain in [mm](https://en.wikipedia.org/wiki/Millimeter) n days ahead; the average of minimum_rain_1d and maximum_rain_1d."
In my configuration the entity ids are acually like this:
![image](https://user-images.githubusercontent.com/37924749/138719612-2593507a-e042-4995-b2af-9a0368ae4346.png)
These are the default entity ids, so I assumed the documentation was wrong in this case.

2021-10-25 15:02 UTC, stefanroelofs commented on source/_integrations/buienradar.markdown
> +- **Wind azimuth n days ahead**: Where the wind is coming from in degrees, with true north at 0° and progressing clockwise for n days ahead. (derived from wind_direction_1d)
Actual default configuration:
![image](https://user-images.githubusercontent.com/37924749/138720358-2b5c73e0-2d6f-4359-a528-bed4a75666ac.png)

2021-10-25 15:02 UTC, stefanroelofs commented on source/_integrations/buienradar.markdown
> +- **Wind speed n days ahead**: "The expected wind speed in [m/s](https://en.wikipedia.org/wiki/M/s) n days ahead (derived from wind force_1d)."
Same as above:
![image](https://user-images.githubusercontent.com/37924749/138720545-86d606cf-1d88-46a0-b070-9601970cd65a.png)

2021-10-25 15:11 UTC, stefanroelofs commented on source/_integrations/cisco_webex_teams.markdown
> +* then copying the room ID from the URL.
You are very right, fixed it.

2021-10-25 15:18 UTC, stefanroelofs commented on source/_integrations/cisco_webex_teams.markdown
> +**Note: you must add the bot email (in the format `mybot@webex.bot`) as a participant to the room specified above.**
Good idea, fixed it.

2021-10-25 21:06 UTC, frenck commented on source/_integrations/buienradar.markdown
> +- **Rain n days ahead**: "The forecasted amount of rain in [mm](https://en.wikipedia.org/wiki/Millimeter) n days ahead; the average of minimum_rain_1d and maximum_rain_1d."
Right, that is the key that is used internally nowadays I guess.

Maybe we should instead just refer to the human-readable name as is used on this page already.

The problem with entity IDs is, is that they aren't guaranteed either.

2021-10-26 09:20 UTC, stefanroelofs commented on source/_integrations/buienradar.markdown
> +- **Rain n days ahead**: "The forecasted amount of rain in [mm](https://en.wikipedia.org/wiki/Millimeter) n days ahead; the average of minimum_rain_1d and maximum_rain_1d."
Done 👍

2021-10-27 08:19 UTC, stefanroelofs commented
The buienradar.markdown file probably needs another review
(see commit: https://github.com/home-assistant/home-assistant.io/pull/19961/commits/17c97ca231263baa66ce7d1b0e9ccdd18470a8cc)
But otherwise this is ready to be merged.
Thanks!

2021-10-27 08:38 UTC, frenck commented on source/_integrations/buienradar.markdown
> +| Entity                                | Description |
Don't use tables, they are really problematic on mobile devices.
This change wasn't really needed.

2021-10-27 09:08 UTC, frenck approved these changes
Thanks, @stefanroelofs 👍

2021-10-27 09:08 UTC, merged