edimax update template sensor example
home-assistant/home-assistant.github.io pull request #19970
Opened 2021-10-25 19:17 UTC by SNoof85

## Proposed change
Update template sensor example

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-26 10:19 UTC, frenck requested changes

2021-10-26 10:19 UTC, frenck commented on source/_integrations/edimax.markdown
> +      state: "{{ state_attr('switch.edimax_smart_plug',  'current_power_w') | replace('None', 0) }}"
Double-space in the middle.

`None` is weird, that is not a valid state?

2021-10-26 10:19 UTC, frenck commented on source/_integrations/edimax.markdown
> +    - name: edimax_current_power
Please use normal names

2021-10-26 18:55 UTC, SNoof85 commented on source/_integrations/edimax.markdown
> +      state: "{{ state_attr('switch.edimax_smart_plug',  'current_power_w') | replace('None', 0) }}"
I don't know the integration, I just adapt what was already done. But as far as I can understand this I guess `|float(default=0)` would be better. What do you think ?

2021-10-26 19:29 UTC, frenck commented on source/_integrations/edimax.markdown
> +      state: "{{ state_attr('switch.edimax_smart_plug',  'current_power_w') | replace('None', 0) }}"
I dunno, I think if it is truly a possible `None`-type value, it would be:

`{{ state_attr('switch.edimax_smart_plug', 'current_power_w') | default(0, true) }}`

2021-10-26 20:20 UTC, SNoof85 commented on source/_integrations/edimax.markdown
> +      state: "{{ state_attr('switch.edimax_smart_plug',  'current_power_w') | replace('None', 0) }}"
https://github.com/home-assistant/core/blob/7024a5d7d95d27e6a818aa09ee08e2d07965c334/homeassistant/components/edimax/switch.py#L41
Could be None then ?

No ?

2021-10-26 20:21 UTC, SNoof85 commented on source/_integrations/edimax.markdown
> +      state: "{{ state_attr('switch.edimax_smart_plug',  'current_power_w') | replace('None', 0) }}"
https://github.com/home-assistant/core/blob/7024a5d7d95d27e6a818aa09ee08e2d07965c334/homeassistant/components/edimax/switch.py#L92
Looks like it can be None.

`|float(default=0)` on `None` is not correct ?

2021-10-26 20:34 UTC, frenck commented on source/_integrations/edimax.markdown
> +      state: "{{ state_attr('switch.edimax_smart_plug',  'current_power_w') | replace('None', 0) }}"
That would work as well. But attributes are type native, so we get back a number of None. So instead of casting it, we can just default for None values.

2021-10-27 10:32 UTC, SNoof85 commented on source/_integrations/edimax.markdown
> +      state: "{{ state_attr('switch.edimax_smart_plug',  'current_power_w') | replace('None', 0) }}"
OK, as the attributes looks to be `None` possible, let's do like you proposed then ;)

2021-10-27 12:01 UTC, frenck approved these changes
Thanks, @SNoof85 👍

2021-10-27 12:01 UTC, merged