Abb Powerone document new energy sensor
home-assistant/home-assistant.github.io pull request #19983
Opened 2021-10-26 11:47 UTC by davet2001

## Proposed change

Add the extra energy metering sensor to the documentation.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/58454
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-26 14:00 UTC, frenck requested changes

2021-10-26 14:00 UTC, frenck commented on source/_integrations/aurora_abb_powerone.markdown
> +Configuration via `configuration.yaml` is now deprecated but does still work.
We don't document deprecations, we remove them from the documentation.

2021-10-26 18:28 UTC, davet2001 commented on source/_integrations/aurora_abb_powerone.markdown
> +Configuration via `configuration.yaml` is now deprecated but does still work.
Done

2021-10-26 18:28 UTC, davet2001 commented
Comments addressed, but #13748 should be merged first.

2021-11-08 12:42 UTC, davet2001 commented
I think that since the parent has been [cherry picked](https://github.com/home-assistant/core/pull/58454#event-5560649970) into 2021.11.x, this needs to be merged (need to remove the `next` label).
(The [live documentation](https://www.home-assistant.io/integrations/aurora_abb_powerone/) only refers to 2 sensors but there are now 3).

2021-11-09 11:08 UTC, frenck approved these changes
Thanks, @davet2001 👍

2021-11-09 11:08 UTC, merged