Refactor blueprints docs
home-assistant/home-assistant.github.io pull request #20012
Opened 2021-10-27 12:21 UTC by axilleas

## Proposed change

Add section about updating blueprints

- Before: https://www.home-assistant.io/docs/automation/using_blueprints/
- After: https://deploy-preview-20012--home-assistant-docs.netlify.app/docs/automation/using_blueprints/

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-27 12:26 UTC, frenck requested changes

2021-10-27 12:26 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +If you have automations based on a previous bleuprint revision, do not delete the already existing blueprint, because the automations based on it will stop working.
```suggestion
If you have automations based on a previous blueprint revision, do not delete the already existing blueprint, because the automations based on it will stop working.
```

2021-10-27 12:26 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +## Updating blueprints
This is not updating...

2021-10-27 19:53 UTC, axilleas commented on source/_docs/automation/using_blueprints.markdown
> +## Updating blueprints
@frenck fair enough. I can add the manual version that you need to edit the YAML file directly, would that be acceptable? I don't know in that case though what happens with the existing automations relying on the blueprint, do they keep working?

2021-10-29 10:34 UTC, axilleas commented on source/_docs/automation/using_blueprints.markdown
> +## Updating blueprints
I added manual instructions!

2021-10-29 10:39 UTC, axilleas commented
@frenck I ended up refactoring the page to be more straightforward to new users. Let me know what you think.

2021-10-29 11:06 UTC, frenck requested changes

2021-10-29 11:06 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +Blueprints created by the community may go through multiple revisions. Sometimes a user creates a blueprint,
I think we should be clear on the fact there is no updating mechanism.

2021-10-29 11:06 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +The Home Assistant Community forums have a specific tag for blueprints. This tag is used to collect all blueprints.
We don't have a tag for it, but a forum.

2021-10-29 11:06 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> -Quick links:
Why remove the quick links?

2021-10-29 11:06 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +- The Home Assistant forum
Link it again?

2021-10-29 11:06 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> -## Blueprint Automations
Why is this whole section gone?

2021-10-29 11:06 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +- The Home Assistant forum
I like the previous working better. It was more readable/story telling instead of a list.

2021-10-29 11:06 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +1. [Find a blueprint][blueprint-forums] you want to import.
This feels like a bullet point list instead of a tutorial story. I'm not sure if that is actually better.

2021-10-29 11:06 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +</div>
Do we have to add a big warning box here?

2021-10-29 11:06 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +## Creating an automation based on a blueprint
The fact this is now here, makes the whole section above weird.
It disconnects blueprints from automations. While it is true, that is not the mindset of a new user/reader. I think this is a good example of the difference between documenting from a experienced user perspective versus a new user.

2021-10-29 13:20 UTC, axilleas commented on source/_docs/automation/using_blueprints.markdown
> +1. [Find a blueprint][blueprint-forums] you want to import.
I don't agree :slightly_smiling_face: 

It helps the user to complete a task (import the blueprint), and it takes them through specific steps that need to be followed in that order.

I'm wondering though, was it the whole list that threw you off, or just the first item?

2021-10-29 13:22 UTC, axilleas commented on source/_docs/automation/using_blueprints.markdown
> +- The Home Assistant forum
Added a link and reverted back to a single sentence. Google has a nice tutorial on lists https://developers.google.com/tech-writing/one/lists-and-tables?hl=en

2021-10-29 13:25 UTC, axilleas commented on source/_docs/automation/using_blueprints.markdown
> +</div>
Yeah, I can either make it a note or drop it completely.

Made it a note.

2021-10-29 13:25 UTC, axilleas commented on source/_docs/automation/using_blueprints.markdown
> +## Creating an automation based on a blueprint
I was trying to create a path for the user to follow. First they find the blueprint, then they add it, and lastly they create the automation based on it.

I think I know what you mean though. We can add more words in the opening paragraph and make this clear that blueprints are primarily used for automations.

2021-10-29 13:25 UTC, axilleas commented on source/_docs/automation/using_blueprints.markdown
> -## Blueprint Automations
I actually renamed it to  `## Creating an automation based on a blueprint`.

2021-10-29 13:25 UTC, axilleas commented on source/_docs/automation/using_blueprints.markdown
> -Quick links:
This was duplicate in the following section on finding blueprints :thinking:

2021-10-29 13:25 UTC, axilleas commented on source/_docs/automation/using_blueprints.markdown
> +The Home Assistant Community forums have a specific tag for blueprints. This tag is used to collect all blueprints.
This sentence was there before, so I didn't pay much attention. I corrected this to be category instead of tag.

2021-10-29 13:26 UTC, axilleas commented on source/_docs/automation/using_blueprints.markdown
> +Blueprints created by the community may go through multiple revisions. Sometimes a user creates a blueprint,
I added some more wording and changed the heading to `Keeping blueprints up to date`.

2022-01-06 23:00 UTC, closed without merging