Add condition in example
home-assistant/home-assistant.github.io pull request #20037
Opened 2021-10-28 19:59 UTC by js94x

## Proposed change
Add condition to example automation, to show users how filtering between multiple feeds is possible.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-28 19:59 UTC, homeassistant commented
Hi @js94x, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#20037).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-10-28 20:05 UTC, frenck requested changes

2021-10-28 20:05 UTC, frenck commented on source/_integrations/feedreader.markdown
> +      - "{{ trigger.event.data.feed_url  == 'https://hasspodcast.io/feed/podcast' }}"
In our documentation, templates should not be used if a non-template alternative is available.

See also our YAML style guide: <https://developers.home-assistant.io/docs/documenting/yaml-style-guide#templates>

2021-10-28 20:22 UTC, js94x commented on source/_integrations/feedreader.markdown
> +      - "{{ trigger.event.data.feed_url  == 'https://hasspodcast.io/feed/podcast' }}"
Can you pls give me a short hint which condition type can I use instead of the shorthand template method? I don't know which is more capable than mine.

2021-10-28 20:27 UTC, js94x commented on source/_integrations/feedreader.markdown
> +      - "{{ trigger.event.data.feed_url  == 'https://hasspodcast.io/feed/podcast' }}"
If multiple URLs are configured in the integration, this is afaik the only way to separate them. I think this information is very useful, if somebody has more then one URL configured

2022-01-04 12:23 UTC, frenck commented on source/_integrations/feedreader.markdown
> +      - "{{ trigger.event.data.feed_url  == 'https://hasspodcast.io/feed/podcast' }}"
Sorry for the late reply, this one slipped my queue somewhere :(

Don't use the shorthand style in this case.

2022-01-04 12:23 UTC, frenck commented
Not stale, thanks bot :)

2022-02-22 02:01 UTC, frenck commented on source/_integrations/feedreader.markdown
> +      - "{{ trigger.event.data.feed_url  == 'https://hasspodcast.io/feed/podcast' }}"
```suggestion
      event_type: feedreader
      event_data:
        feed_url: "https://hasspodcast.io/feed/podcast"
```

2022-02-22 02:10 UTC, frenck approved these changes
Thanks, @js94x 👍

2022-02-22 02:10 UTC, merged