Document binary sensors for Shelly inputs
home-assistant/home-assistant.github.io pull request #20047
Opened 2021-10-29 07:58 UTC by raducotescu

* this commit fixes https://github.com/home-assistant/core/issues/57660

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
- This PR fixes or closes issue: https://github.com/home-assistant/core/issues/57660

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-29 07:58 UTC, homeassistant commented
Hi @raducotescu, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#20047).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-10-29 10:00 UTC, frenck requested changes

2021-10-29 10:00 UTC, frenck commented on source/_integrations/shelly.markdown
> +Depending on how a device's button type is configured, the integration will create binary sensors corresponding to those inputs. Starting with version 2021.10.4 of Home Assistant, these binary sensor
We don't keep a changelog in our documentation. Instead, we document only the latest state.

That said, 2021.10.4 is a patch release, which should not contain breaking changes. If it does, it is more likely a bug that should be reported.

2021-10-29 11:37 UTC, thecode commented on source/_integrations/shelly.markdown
> +Depending on how a device's button type is configured, the integration will create binary sensors corresponding to those inputs. Starting with version 2021.10.4 of Home Assistant, these binary sensor
That comment is wrong. Binary sensors were never created when button type is `momentary` or `momentary_on_release`.

2021-10-29 11:40 UTC, thecode commented on source/_integrations/shelly.markdown
> +For generation 2 hardware it's possible to select if a device's input is connected to a button or a switch. Binary sensors are created only if the input mode is set to `switch`. When the input is of
```suggestion

## Binary input sensors (generation 2)
For generation 2 hardware it's possible to select if a device's input is connected to a button or a switch. Binary sensors are created only if the input mode is set to `switch`. When the input is of type `button` you need to use events for your automations.
```

2021-10-29 11:45 UTC, thecode commented on source/_integrations/shelly.markdown
> +Depending on how a device's button type is configured, the integration will create binary sensors corresponding to those inputs. Starting with version 2021.10.4 of Home Assistant, these binary sensor
```suggestion
## Binary input sensors (generation 1)
Depending on how a device's button type is configured, the integration will create binary sensors corresponding to those inputs. binary sensors are not created when the button type is `momentary` or `momentary_on_release`, for these types you need to use events for your automations.
```

2021-11-18 06:51 UTC, chemelli74 commented
@raducotescu are you going to review the comments so we can proceed with this ?

Simone

2021-12-31 18:05 UTC, thecode commented
@frenck I committed my suggestions trying to finish this, please review and I will make changes if needed, Thanks

2021-12-31 18:05 UTC, thecode submitted a review, later dismissed

2022-01-03 10:33 UTC, raducotescu commented
@thecode, thanks for following up and sorry for not acting earlier. I had the impression that you had already pushed your suggestion.

@frenck, thanks for letting me know about the wording. The truth is that 2021.10.4 introduced a behaviour change that @thecode helped me debug. I'm not sure how I ended in the state that I reported, but starting with 2021.10.4 the integration removed some entities it used to have before.

2022-01-03 10:38 UTC, frenck commented on source/_integrations/shelly.markdown
> +For generation 2 hardware it's possible to select if a device's input is connected to a button or a switch. Binary sensors are created only if the input mode is set to `switch`. When the input is of
```suggestion
## Binary input sensors

### Binary input sensors (generation 1)

Depending on how a device's button type is configured, the integration will create binary sensors corresponding to those inputs. binary sensors are not created when the button type is `momentary` or `momentary_on_release`, for these types you need to use events for your automations.

### Binary input sensors (generation 2)

For generation 2 hardware it's possible to select if a device's input is connected to a button or a switch. Binary sensors are created only if the input mode is set to `switch`. When the input is of type `button` you need to use events for your automations.
```

2022-01-03 10:52 UTC, frenck approved these changes
Thanks, @raducotescu 👍

2022-01-03 10:53 UTC, merged