Update homematic templates examples
home-assistant/home-assistant.github.io pull request #20053
Opened 2021-10-29 12:08 UTC by SNoof85

## Proposed change
Update homematic templates examples

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-29 12:08 UTC, SNoof85 commented
This one was tricky, I'm not sure of what i've done.

2021-10-29 12:11 UTC, SNoof85 commented on source/_integrations/homematic.markdown
> +        {{ as_timestamp(now()) - as_timestamp(state_attr('sensor.office_voltage', 'last_changed'), 601) < 600 }}
I think on the first `as_timestamp` no default is needed because `now()` must be existing (or should we default to `now()` once again ?
The second one needs a default, wich i've set to put the binary_sensor to `off` immediately. But it could cause several `homematic.reconnect` service call...
🤷‍♂️

2021-10-29 12:13 UTC, frenck requested changes

2021-10-29 12:13 UTC, frenck commented on source/_integrations/homematic.markdown
> +- sensor
Incorrect yaml, indentation is off as well.

2021-10-29 12:13 UTC, frenck commented on source/_integrations/homematic.markdown
> +        {{ as_timestamp(now()) - as_timestamp(state_attr('sensor.office_voltage', 'last_changed'), 601) < 600 }}
the first as_timestamp isn't needed at all.

2021-10-29 12:13 UTC, frenck commented on source/_integrations/homematic.markdown
> +     template
Incorrect yaml and indentation

2021-10-29 12:17 UTC, SNoof85 commented on source/_integrations/homematic.markdown
> +- sensor
Oh, what is going on with my eyes 👀

2021-10-29 12:20 UTC, SNoof85 commented on source/_integrations/homematic.markdown
> +        {{ as_timestamp(now()) - as_timestamp(state_attr('sensor.office_voltage', 'last_changed'), 601) < 600 }}
Changed

2021-10-29 12:26 UTC, SNoof85 commented
Hope all fixed :)

2021-10-29 12:32 UTC, SNoof85 commented on source/_integrations/homematic.markdown
> +        {{ as_timestamp(now()) - as_timestamp(state_attr('sensor.office_voltage', 'last_changed'), 601) < 600 }}
I removed the 1st `as_timestamp` but tested it on my templating tool it doesn't work : 
`now() - 601` gives a TypeError
`now()` is `datetime `and `601` is `int`

2021-10-30 14:54 UTC, frenck approved these changes
Thanks, @SNoof85 👍 

Happy Hacktoberfest 🎉 

../Frenck

2021-10-30 14:54 UTC, merged