Add section on keeping blueprints up to date
home-assistant/home-assistant.github.io pull request #20065
Opened 2021-10-29 18:40 UTC by axilleas

## Proposed change

Add section on keeping blueprints up to date.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-10-29 18:41 UTC, axilleas commented
@frenck :wave: so this is a stripped down version of https://github.com/home-assistant/home-assistant.io/pull/20012, where I added only the blueprints update section. Cheers!

2022-01-04 12:24 UTC, frenck commented
Not stale bot, thanks, awaiting our review and handling

2022-02-18 19:02 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +1. Navigate to the blueprints directory (`/blueprints/automation/`).
```suggestion
1. Navigate to the blueprints directory (`/config/blueprints/automation/`).
```

2022-02-18 19:02 UTC, frenck commented on source/_docs/automation/using_blueprints.markdown
> +   similar to how you find [`configuration.yaml`](/docs/configuration/#editing-configurationyaml).
```suggestion
   The location of this directory depends on the installation method and it's
   similar to how you find [`configuration.yaml`](/docs/configuration/#editing-configurationyaml).
```

2022-02-18 19:06 UTC, frenck requested changes
Looks good! 2 Tiny comments.

I do wonder, should it list something about the new Blueprint that might be incompatible with the previous version? And so it might need that you need to adjust them accordingly?

2022-02-19 12:13 UTC, frenck approved these changes
Thanks, @axilleas 👍

2022-02-19 12:14 UTC, merged