Mqtt add object
home-assistant/home-assistant.github.io pull request #20070
Opened 2021-10-30 04:03 UTC by Smeagolworms4

## Proposed change

Add documentation of object_id in relation with with PR: https://github.com/home-assistant/core/pull/58728

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/58728
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-11-02 14:50 UTC, emontnemery commented
Each MQTT entity's documentation should be updated with the new configuration parameter, not just the discovery starting page.

2021-11-02 14:50 UTC, emontnemery requested changes
Each MQTT entity's documentation should be updated with the new configuration parameter, not just the discovery starting page.

2021-11-05 22:32 UTC, jbouwh requested changes

2021-11-05 22:32 UTC, jbouwh commented on source/_docs/mqtt/discovery.markdown
> +- Configuration topic: `homeassistant/sensor/devive1/config`
Spelling device

2021-11-05 22:32 UTC, jbouwh commented on source/_docs/mqtt/discovery.markdown
> + }
Same here

2021-11-08 12:49 UTC, closed without merging