SolarEdge energy dashboard configuration example
home-assistant/home-assistant.github.io pull request #20118
Opened 2021-11-02 10:58 UTC by purcell-lab

## Proposed change

This change documents the sensors to be utilised for the SolarEdge integration to populate the Energy Dashboard, which is natively supported as of core-2021.11.

This addresses a common question as to how to configure the Energy Dashboard with this integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR documents the changes in issue: https://github.com/home-assistant/core/issues/58735#event-5545327262

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-11-02 11:01 UTC, purcell-lab commented
Should be proposed for `next` branch but I couldn't work out how to point against that branch.

2021-11-02 11:38 UTC, frenck requested changes

2021-11-02 11:38 UTC, frenck commented on source/_integrations/solaredge.markdown
> +As of Home Assistant 2021.11 the SolarEdge intergration can natively populate the [Energy Dashboard](https://www.home-assistant.io/docs/energy/) without additional setup.
We don't keep changelogs in our documentation.

2021-11-02 11:38 UTC, frenck commented on source/_integrations/solaredge.markdown
> +To monitor your solar system you can utilise `sensor.solaredge_lifetime_energy` for solar production:
This is automatically detected, do we need to mention it?

2021-11-02 11:38 UTC, frenck commented on source/_integrations/solaredge.markdown
> +![Screenshot 2021-11-02 21 25 31](https://user-images.githubusercontent.com/79175134/139829667-cfe116f1-c3a7-4c53-8278-6c1d5e7f42d0.png)
External screenshot, we cannot use that.

2021-11-29 13:30 UTC, frenck commented
This PR is running stale, closing it for now. Feel free to re-open when ready to work on it again.

2021-11-29 13:30 UTC, closed without merging