Add Troubleshooting for known issue to ffmpeg_noise
home-assistant/home-assistant.github.io pull request #20446
Opened 2021-11-25 15:33 UTC by koenhendriks

## Proposed change

There is a known issue which can be fixed rather easily. This PR adds troubleshooting for this issue to the documentation of the integration. It keeps the same format for troubleshooting as other integrations have in the documentation.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

Related issues:
- https://github.com/home-assistant/core/issues/56421
- https://github.com/home-assistant/core/issues/49183
- https://github.com/home-assistant/core/issues/7081
- https://github.com/home-assistant/core/issues/42204
- https://github.com/home-assistant-libs/ha-ffmpeg/issues/32

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.

- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-11-25 15:33 UTC, homeassistant commented
Hi @koenhendriks, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#20446).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-11-29 12:42 UTC, frenck requested changes

2021-11-29 12:42 UTC, frenck commented on source/_integrations/ffmpeg_noise.markdown
> +
We should not link to issues. If the issue has content that is important, it should be added to the documentation directly.

```suggestion
If the noise sensor becomes unresponsive, make sure you have `extra_arguments: -nostats` in the configuration.  
```

2021-12-08 07:52 UTC, koenhendriks commented
@frenck I've updated as requested. Could you take another look?

2021-12-08 07:54 UTC, frenck approved these changes
Thanks, @koenhendriks 👍

2021-12-08 07:54 UTC, merged