add advice to delete data via recorder services
home-assistant/home-assistant.github.io pull request #20445
Opened 2021-11-25 12:39 UTC by copykatze

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-11-25 12:39 UTC, homeassistant commented
Hi @copykatze, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#20445).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-11-25 13:36 UTC, frenck requested changes

2021-11-25 13:36 UTC, frenck commented on source/_docs/backend/database.markdown
> +Deleting data directly from the database might lead to a corrupted database, since the database isn't meant to be consumed like that:
Let's remove the manual deletion part.

2021-11-25 13:50 UTC, homeassistant commented
Hi @copykatze, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#20445).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-11-25 13:51 UTC, copykatze reviewed
removed the manual deletion part

2021-11-29 08:42 UTC, frenck requested changes

2021-11-29 08:42 UTC, frenck commented on source/_docs/backend/database.markdown
> +If you don't want to keep certain entities, you can delete them permanently by using the services provided by the recorder: https://www.home-assistant.io/integrations/recorder/#service-purge_entities
```suggestion
If you don't want to keep certain entities, you can delete them permanently by using the [services provided by the recorder](/integrations/recorder/#service-purge_entities).
```

2021-11-29 17:32 UTC, homeassistant commented
Hi @copykatze, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#20445).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-11-29 17:47 UTC, frenck approved these changes
Thanks, @copykatze 👍

2021-11-29 17:47 UTC, merged