Add integration for Lektrico
home-assistant/home-assistant.github.io pull request #20450
Opened 2021-11-25 17:55 UTC by mtarjoianu

## Proposed change

Added integration for Lektrico Charging Station

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/2963
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-01-17 08:56 UTC, frenck requested changes

2023-01-17 08:56 UTC, frenck commented on source/_integrations/lektrico.markdown
> +This `lektrico` integrates your [Lektrico Charging Station](https://lektri.co/en/product/ev-charging-station-lektri-co-svik-7-4kw-ac/) into your Home Assistant and allows you to monitor it.
```suggestion
The Lektrico Charging Station integration integrates your [Lektrico Charging Station](https://lektri.co/en/product/ev-charging-station-lektri-co-svik-7-4kw-ac/) into your Home Assistant and allows you to monitor it.
```

2023-01-17 08:56 UTC, frenck commented on source/_integrations/lektrico.markdown
> +For this you can use some network scanners.
```suggestion

The Lektrico Charging Station device will be added as a sensor in Home Assistant.

## Prerequisite

Before adding the integration, you must know the device's IP.

{% include integrations/config_flow.md %}

```

2023-01-17 08:56 UTC, frenck commented
Additionally, there is a merge conflict as well, could you take a look?

2023-01-18 11:15 UTC, mtarjoianu commented
> Additionally, there is a merge conflict as well, could you take a look?

I solved the confict, thank you.

2023-01-18 20:40 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2023-11-23 09:13 UTC, frenck commented
Closing PR as the parent PR has been closed.

2023-11-23 09:13 UTC, closed without merging