Need libpython3.9-dev to build ciso8601
home-assistant/home-assistant.github.io pull request #20604
Opened 2021-12-07 09:51 UTC by punnerud

Fixes #20603

2021-12-07 09:51 UTC, homeassistant commented
Hi @punnerud, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#20604).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-12-07 10:37 UTC, frenck requested changes

2021-12-07 10:37 UTC, frenck commented on source/_includes/installation/core.md
> +sudo apt-get install -y python3 python3-dev python3-venv python3-pip libpython3.9-dev libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzd
`python3-dev` already depends on `libpython3.9-dev`, see:

<https://packages.debian.org/bullseye/python3-dev>

The `libturbojpeg0-dev` change is unclear to me, as far as I'm aware we don't need to compile anything against it, so the non-dev version should be enough.

2022-01-05 23:14 UTC, frenck commented
No response from PR author, going to close this stale for now.

2022-01-05 23:14 UTC, closed without merging