Updating and simplifying nest integration documentation structure
home-assistant/home-assistant.github.io pull request #20656
Opened 2021-12-11 20:57 UTC by allenporter

## Proposed change

Updating nest integration instructions.  The primary goals are:
- Reduce the overall amount of words describing the state of support of various devices.
- Give an overview of the supported devices in a table, since the number of devices and various capabilities has grown significantly in the last year. In particular, its hard for users to understand various states of streams, events supported, and which can actually capture media in response to events. This mirrors an existing google documentation table, but explains device/API capabilities in terms of home assistant features.
- Clarify differences between RTSP and WebRTC stream support
- Also call out Nest Hub Max known limitations since this is a common community forum issue. (I'm in contact with the nest API tech lead)
- Re-order Climate and Camera so that the camera related features flow together better (Camera, then Device Triggers, then Media Source)
- Other whitespace fixes

Follow up documentation improvements planned:
[ ] Restructure / move troubleshooting lower in the page e.g. collapsing logging
[ ] Move event automation example to use new media source API
[ ] Example for capturing an mp4 clip

## Type of change

- [X] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-12-13 22:12 UTC, frenck requested changes

2021-12-13 22:12 UTC, frenck commented on source/_integrations/nest.markdown
> +Cameras and Doorbells use [Automation and Device Triggers](#automation-and-device-triggers) for events and a [Media Source](#media-source) for capturing media iamges on supported devices. Other devic
```suggestion
Cameras and Doorbells use [Automation and Device Triggers](#automation-and-device-triggers) for events and a [Media Source](#media-source) for capturing media images on supported devices. Other device types like Smoke and CO Alarms or Security systems are not currently supported by the SDM API.
```

2021-12-13 22:12 UTC, frenck commented on source/_integrations/nest.markdown
> +</div>
```suggestion
<div class='note'>

The Nest Smart Device Management (SDM) API **requires a US$5 fee**.

</div>
```

2021-12-13 22:12 UTC, frenck commented on source/_integrations/nest.markdown
> +  * **WebRTC**: These devices support direct browser to camera communication, and a super low latency stream. Live image previews and the `camera` services like stream recording are *not supported*.
```suggestion
- **RTSP**: These devices have an HLS stream served by the Home Assistant Core. These cameras support server-side `camera` services like stream recording or image preview. See [Low Latency HLS](/integrations/stream#ll-hls) as a great option to enable to reduce stream latency.
- **WebRTC**: These devices support direct browser to camera communication and a super low latency stream. Live image previews and the `camera` services like stream recording are *not supported*.
```

2021-12-14 02:28 UTC, allenporter commented
Thank you for the fast review. I looked again locally and the commits look good, thanks.

2021-12-14 19:12 UTC, frenck approved these changes
Thanks, @allenporter 👍

2021-12-14 19:12 UTC, merged