Update HMIP-DLD documentation in homematic
home-assistant/home-assistant.github.io pull request #20671
Opened 2021-12-12 15:33 UTC by ProfDrYoMan

2021.12.0 fixed a bug. Now the lock sensor status is available. No need for an extra program on the CCU.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-12-12 15:33 UTC, homeassistant commented
Hi @ProfDrYoMan, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#20671).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-01-05 23:19 UTC, frenck requested changes

2022-01-05 23:19 UTC, frenck commented on source/_integrations/homematic.markdown
> +create a program on CCU, which updates the variable with every change of the lock level to `true` for locked and `false` for unlocked.
We don't keep a changelog in our documentation. So, I guess this whole section can now be removed?

```suggestion
```

2022-01-16 17:02 UTC, frenck approved these changes
Thanks, @ProfDrYoMan 👍

2022-01-16 17:02 UTC, merged