update documentation to match the latest updates
home-assistant/home-assistant.github.io pull request #20713
Opened 2021-12-15 21:37 UTC by kimfrellsen

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-12-15 22:48 UTC, kimfrellsen commented
This is documentation to PR https://github.com/home-assistant/core/pull/61970

2021-12-17 13:22 UTC, MartinHjelmare commented on source/_integrations/fortios.markdown
> +ha_quality_scale: silver
Changing the quality scale requires updating the manifest.json in the core integration first.

2021-12-19 12:10 UTC, frenck requested changes
Please make sure the CI/builds pass

2021-12-28 11:11 UTC, kimfrellsen commented on source/_integrations/fortios.markdown
> +ha_quality_scale: silver
Thanks. I have removed the quality_scale. It is not of importance to me.
I do not understand the Netlify errors. They are pointing towards the "ha_iot_class: Local Polling" line and complaining of headers. I have tried to encapsulate them in " without any luck.

2021-12-28 11:14 UTC, MartinHjelmare commented on source/_integrations/fortios.markdown
> +The latest update to the integration use this API: ```<host>:<port>/api/v2/monitor/user/device/query``` which is only available in FortiOS 6.4.3 and later. So minimum supported version is on FortiOS
```suggestion
The integration uses this API: ```<host>:<port>/api/v2/monitor/user/device/query``` which is only available in FortiOS 6.4.3 and later. So minimum supported version is on FortiOS 6.4.3.
```

2021-12-28 11:14 UTC, MartinHjelmare commented on source/_integrations/fortios.markdown
> +  description: Hostname or IP address of the FortiGate. Optionally portname can be added like this "10.10.10.10:443". Remember qoutes if portnumber is added.
```suggestion
  description: Hostname or IP address of the FortiGate. Optionally port name can be added like this "10.10.10.10:443". Remember quotes if port number is added.
```

2021-12-28 11:14 UTC, MartinHjelmare commented on source/_integrations/fortios.markdown
> +  description: See: [Generate an API token for FortiOS](https://docs.fortinet.com/document/forticonverter/6.2.0/online-help/866905/connect-fortigate-device-via-api-token) for how to create an API tok
```suggestion
  description: See: [Generate an API token for FortiOS](https://docs.fortinet.com/document/forticonverter/6.2.0/online-help/866905/connect-fortigate-device-via-api-token) for how to create an API token. This integration only needs read access to a FortiGate, so configure the API user to only to have limited and read-only access.
```

2022-01-23 19:17 UTC, frenck commented
Rebased the PR to deal with the CI issues

2022-01-23 19:37 UTC, frenck commented on source/_integrations/fortios.markdown
> +ha_release: "0.97"
```suggestion
title: FortiOS
description: Instructions on how to use Fortinet FortiOS to track devices in Home Assistant.
ha_category: Presence Detection
ha_iot_class: Local Polling
ha_release: 0.97
```

2022-01-23 19:37 UTC, frenck commented on source/_integrations/fortios.markdown
> +The integration has been verified on FortiGate appliances and FortiGate VM running FortiOS v. 6.4.x (up to 6.4.8) and 7.0.x (up to 7.0.4).
```suggestion
The integration relies on the [fortiosapi](https://pypi.org/project/fortiosapi/). It has been verified on FortiGate appliances and FortiGate VM running FortiOS v. 6.4.x (up to 6.4.8) and 7.0.x (up to 7.0.4).  
```

2022-01-23 19:37 UTC, frenck commented on source/_integrations/fortios.markdown
> +The integration uses this API: ```<host>:<port>/api/v2/monitor/user/device/query``` which is only available in FortiOS 6.4.3 and later. So minimum supported version is on FortiOS 6.4.3.
This is an implementation detail. Not relevant for the average end-user.
```suggestion
The minimum version supported is FortiOS 6.4.3.
```

2022-01-23 19:37 UTC, frenck commented on source/_integrations/fortios.markdown
> +This example uses the FortiOS integration as device tracker, with API token and does not verify the SSL certificate.
```suggestion
### Example Configuration:

This example uses the FortiOS integration as a device tracker, with an API token and does not verify the SSL certificate.

```

2022-01-23 19:37 UTC, frenck commented on source/_integrations/fortios.markdown
> +  default: false
```suggestion
  default: false
```

2022-01-23 19:38 UTC, frenck commented on source/_integrations/fortios.markdown
> +ha_category: Presence Detection
```suggestion
ha_category: 
 - Presence Detection
```

2022-01-23 19:43 UTC, frenck approved these changes
Thanks, @kimfrellsen 👍

2022-01-23 19:43 UTC, merged