Create area.markdown
home-assistant/home-assistant.github.io pull request #20743
Opened 2021-12-18 07:24 UTC by Beta-Computer

Create Documentation for the area card.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ x ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ x ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ x ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-12-18 07:24 UTC, homeassistant commented
Hi @Beta-Computer, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#20743).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-12-18 07:27 UTC, Beta-Computer commented
Should I add more information about fans, lights, and motion sensors?

2021-12-20 07:07 UTC, mikedahlgren commented
> Should I add more information about fans, lights, and motion sensors?

An example on how to use it with a camera feed would be very appreciated.

2021-12-21 11:14 UTC, frenck requested changes

2021-12-21 11:14 UTC, frenck commented on source/_lovelace/area.markdown
> +To add the Humidifier card to your user interface, click the Lovelace menu (three dots at the top right of the screen) and then **Edit Dashboard**. Click the "Add Card" button in the bottom right cor
```suggestion
To add the Area card to your user interface, click the Lovelace menu (three dots at the top right of the screen) and then **Edit Dashboard**. Click the "Add Card" button in the bottom right corner and select **Area** from the card picker. All options for this card can be configured via the user interface.
```

2021-12-21 11:14 UTC, frenck commented on source/_lovelace/area.markdown
> +  <img src='https://www.home-assistant.io/images/blog/2021-12/area-card.png' alt='Screenshot of the Area card'>
```suggestion
  <img src='/images/blog/2021-12/area-card.png' alt='Screenshot of the Area card'>
```

2021-12-22 13:41 UTC, frenck commented
@Beta-Computer Can you please make sure the build passes? Thanks 👍

2021-12-22 19:47 UTC, Beta-Computer commented
Sorry should be all good now

2021-12-22 20:04 UTC, frenck approved these changes
Thanks, @Beta-Computer 👍

2021-12-22 20:04 UTC, merged