Documentation update for Signal Messenger integration for adding URL attachment support
home-assistant/home-assistant.github.io pull request #20762
Opened 2021-12-19 15:10 UTC by burnsie-la

Added documentation for a new feature I am proposing to this integration - https://github.com/home-assistant/core/pull/62311

## Proposed change
I am proposing a feature to the Signal Integration to allow sending of attachments in Signal messages from a URL.  This is the documentation update for this feature.

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: 
https://github.com/home-assistant/core/pull/62311

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-01-08 18:04 UTC, ianByrne requested changes

2022-01-08 18:04 UTC, ianByrne commented on source/_integrations/signal_messenger.markdown
> +      urls:
```suggestion
            verifyUrls: false
            urls:
```

2022-01-08 18:04 UTC, ianByrne commented on source/_integrations/signal_messenger.markdown
> +
```suggestion

Note there is a 50mb size limit for attachments retrieved via URLs.

```

2022-01-08 18:11 UTC, ianByrne requested changes

2022-01-08 18:11 UTC, ianByrne commented on source/_integrations/signal_messenger.markdown
> +            urls:
```suggestion
      verifySsl: False
      urls:
```

2022-01-08 18:11 UTC, ianByrne commented on source/_integrations/signal_messenger.markdown
> +Note there is a 50mb size limit for attachments retrieved via URLs. You can set `verifyUrls` to `False` to ignore SSL errors (default `True`)
```suggestion
Note there is a 50mb size limit for attachments retrieved via URLs. You can set `verifySsl` to `False` to ignore SSL errors (default `True`)
```

2022-01-10 11:12 UTC, frenck requested changes

2022-01-10 11:12 UTC, frenck commented on source/_integrations/signal_messenger.markdown
> +      verifySsl: False
`verifySsl` isn't following our standards; it should be:

```suggestion
      verify_ssl: false
```

Additionally, I'm confused why Home Assistant needs to verify SSL, to begin with?

2022-01-16 16:36 UTC, ianByrne requested changes

2022-01-16 16:36 UTC, ianByrne commented on source/_integrations/signal_messenger.markdown
> +Note there is a 50mb size limit for attachments retrieved via URLs. You can set `verifySsl` to `False` to ignore SSL errors (default `True`)
```suggestion
To attach files from outside of HomeAssistant, the URLs must be added to the [allowlist_external_urls](https://www.home-assistant.io/docs/configuration/basic/#allowlist_external_urls) list.

Note there is a 50mb size limit for attachments retrieved via URLs. You can also set `verify_ssl` to `False` to ignore SSL errors (default `True`)
```

2022-01-19 14:35 UTC, frenck commented on source/_integrations/signal_messenger.markdown
> +To attach files from outside of HomeAssistant, the URLs must be added to the [allowlist_external_urls](https://www.home-assistant.io/docs/configuration/basic/#allowlist_external_urls) list.
```suggestion
To attach files from outside of HomeAssistant, the URLs must be added to the [allowlist_external_urls](/docs/configuration/basic/#allowlist_external_urls) list.
```

2022-01-19 14:35 UTC, frenck commented on source/_integrations/signal_messenger.markdown
> +Note there is a 50mb size limit for attachments retrieved via URLs. You can also set `verify_ssl` to `False` to ignore SSL errors (default `True`)
```suggestion
Note there is a 50MB size limit for attachments retrieved via URLs. You can also set `verify_ssl` to `false` to ignore SSL errors (default `true`).
```

2022-01-19 14:36 UTC, frenck commented on source/_integrations/signal_messenger.markdown
> +To attach files from outside of HomeAssistant, the URLs must be added to the [allowlist_external_urls](/docs/configuration/basic/#allowlist_external_urls) list.
```suggestion
To attach files from outside of HomeAssistant, the URLs must be added to the [`allowlist_external_urls`](/docs/configuration/basic/#allowlist_external_urls) list.
```

2022-01-19 17:49 UTC, frenck approved these changes

2022-01-19 17:50 UTC, merged