Add Overkiz documentation for new integration
home-assistant/home-assistant.github.io pull request #20841
Opened 2021-12-23 18:08 UTC by iMicknl

## Proposed change
Adds the first version of the Overkiz documentation, for the sensor entity.

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: #62640
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist
- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2021-12-24 00:25 UTC, bdraco requested changes
The `somfy` changes should probably be in a separate PR after this is merged since this PR is really about `overkiz` and not `somfy`

2021-12-24 20:30 UTC, bdraco approved these changes

2021-12-24 20:30 UTC, bdraco commented
@iMicknl For the rest of these, please do one docs PR to match up with the core PR so they are easier to keep track of.  Thanks 👍

2021-12-24 20:30 UTC, merged

2021-12-27 09:59 UTC, frenck reviewed
@iMicknl Please address these review comments in a new PR.

Thanks 👍

2021-12-27 09:59 UTC, frenck commented on source/_integrations/overkiz.markdown
> +ha_release: 2022.1.0
This version is incorrect. It should tag the major version and above all 2022.1 won't be released.

Please open a PR to correct this to 2022.2

2021-12-27 09:59 UTC, frenck commented on source/_integrations/overkiz.markdown
> +The Overkiz has a limit of 10 actions that can be executed in parallel. Currently this can only be solved by adding a time-out in between your executions, where you need to take the execution time in
This sounds like a bug to me, and something that should not be solved in the documentation.

We should not have to burden the end-user with these kinds of things.

2021-12-27 09:59 UTC, frenck commented on source/_integrations/overkiz.markdown
> +The Overkiz (by Somfy) integration platform is used by many different vendors, like Somfy, Hitachi and Atlantic. This integration will allow users to integrate their devices into Home Assistant using
- `like Somfy, Hitachi and Atlantic` -> `like Somfy, Hitachi, and Atlantic`

2021-12-27 09:59 UTC, frenck commented on source/_integrations/overkiz.markdown
> +During peak hours, it could happen that the Overkiz platform is unable to execute your command. The integration will try to retry this command, however this is not guaranteed to succeed.
- Space after `succeed. `
- Missing comma after `however`: `this command, however, this is`

2021-12-27 09:59 UTC, frenck commented on source/_integrations/overkiz.markdown
> +Even though most Overkiz hubs supports adding Z-Wave, Hue and Sonos devices, this isn't supported in the Overkiz integration. All these platforms have native integrations in Home Assistant which are
- `supports` -> `support`
- `Z-Wave, Hue and Sonos devices` -> `Z-Wave, Hue, and Sonos devices`
- `feature rich` -> feature-rich`

2021-12-27 09:59 UTC, frenck commented on source/_integrations/overkiz.markdown
> +This integration communicates via the cloud based Overkiz API, since Overkiz doesn't expose a local API on their hubs. If you are only using Somfy IO compatible devices, you could purchase a Velux KL
- `cloud based` -> `cloud-based`
- Misplaced `to`, remove it: `Velux KLF200 hub and use to` -> `Velux KLF200 hub and use`

2021-12-27 18:26 UTC, bdraco commented on source/_integrations/overkiz.markdown
> +The Overkiz has a limit of 10 actions that can be executed in parallel. Currently this can only be solved by adding a time-out in between your executions, where you need to take the execution time in
@iMicknl AFAICT this is a limitation on Somfy's side with no clear solution. Feel free to reach out on discord to discuss ideas to work around this implementation flaw.