Add set_guest_wifi_password description
home-assistant/home-assistant.github.io pull request #20915
Opened 2021-12-28 18:45 UTC by sti0

Update docs for PR https://github.com/home-assistant/core/pull/62892

## Proposed change

- Add documentation for new service `set_guest_wifi_password` (https://github.com/home-assistant/core/pull/62892)

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/62892
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-01-04 12:34 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2022-01-18 21:36 UTC, mib1185 requested changes

2022-01-18 21:36 UTC, mib1185 commented on source/_integrations/fritz.markdown
> +| `length`               | yes      | Length of the new password. The password will be auto-generated, if no password is set.                        |
```suggestion
| `length`               | yes      | Length of the auto-generated password. (_default 12_)                        |
```

2022-01-18 21:36 UTC, mib1185 commented on source/_integrations/fritz.markdown
> +If no additional parameter is set, the password will be auto-generated with a length of 12 characters.
```suggestion
If no password is given, it will be auto-generated.
```

2022-01-18 21:41 UTC, mib1185 approved these changes

2022-02-14 13:40 UTC, frenck approved these changes

2022-02-14 13:40 UTC, merged