add vartastorage.markdown
home-assistant/home-assistant.github.io pull request #21112
Opened 2022-01-09 13:51 UTC by Vip0r

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [X] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
https://github.com/home-assistant/core/pull/63736
- Link to parent pull request in the Brands repository: 
https://github.com/home-assistant/brands/pull/3049

- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-01-10 09:42 UTC, frenck requested changes

2022-01-10 09:42 UTC, frenck commented on source/_integrations/vartastorage.markdown
> +[VARTA Storage](https://www.varta-storage-portal.com) allows you to integrate your Battery device into HomeAssistant.
```suggestion
[VARTA Storage](https://www.varta-storage-portal.com) allows you to integrate your Battery device into Home Assistant.
```

2022-01-10 09:42 UTC, frenck commented on source/_integrations/vartastorage.markdown
> +The Port ist pre-defined with 502 (Standard Modbus Port). The integration is using this [PyPI Package](https://github.com/vip0r/vartastorage)
```suggestion
The integration will create sensor entities for the different values of the device like the State of Charge, Charge Power, Power Grid Consumption, and many more.

# Prerequisites

To set up this integration, it is required that your battery device is connected to your network.
```

2022-01-15 13:17 UTC, Vip0r commented
Updated the filename of this integration-doc as recommended within the PR for the integration

2022-01-17 17:34 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2024-03-20 08:21 UTC, frenck commented
Closing PR as the linked parent PR has been closed.

2024-03-20 08:21 UTC, closed without merging