Info on Hassio installation
home-assistant/home-assistant.github.io pull request #21114
Opened 2022-01-09 16:08 UTC by s1gmund80

Just to avoid users to spend time to try install setcap on hassio before discovering it is not needed at all

## Proposed change

As a user I spent time to try to allow home assistant to launch a web server on port 80, since I was assuming I was on linux. But I spent some time trying to enable setcap on the shell just to follow the guide. Only before trying harder I configured everything to test if the current installation was already able to serve on port 80, so... better specify it on the guide

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-01-09 16:08 UTC, homeassistant commented
Hi @s1gmund80, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#21114).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-01-10 12:17 UTC, frenck requested changes

2022-01-10 12:17 UTC, frenck commented on source/_integrations/emulated_hue.markdown
> +Nothing special to do on Hassio, the server is already enabled to serve on port 80
The documentation should be adjusted to handle the Home Assistant OS, Supervised & Container installations by default (as those are the most used installation types).

Additionally, `Hassio` isn't a term used anymore (for a long time already). It is ambiguous.

2022-01-10 12:17 UTC, frenck commented on source/_integrations/emulated_hue.markdown
> +Once configured on HomeAssistant, you can add new devices from Alexa App, choosing Philips Hue from the famous devices list.
```suggestion
Once configured on Home Assistant, you can add new devices from Alexa App, choosing Philips Hue from the famous devices list.
```

2022-03-12 11:00 UTC, frenck commented
Since there was no response at all, I'm declaring this PR stale and closing it.
Feel free to re-open this PR when you feel like that is the appropriate thing to do.

2022-03-12 11:00 UTC, closed without merging