Fix formatting in note
home-assistant/home-assistant.github.io pull request #21140
Opened 2022-01-11 00:29 UTC by ScottG489

Markdown syntax was not rendering correctly in this note div. This fixes the formatting of the link and a code segment to be properly formatted.

I'm not entirely certain why it was not rendering properly, but I'm guessing it has something to do with Markdown being inside of an HTML element.

## Proposed change

The commit message contains all the necessary details.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

The improper formatting as it exists now can be observed in the "note" block here:
https://www.home-assistant.io/integrations/shell_command/#execution

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-01-11 00:29 UTC, homeassistant commented
Hi @ScottG489, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#21140).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-01-11 00:49 UTC, frenck requested changes

2022-01-11 00:49 UTC, frenck commented on source/_integrations/shell_command.markdown
>  </div>
This is not the correct fix. Please revert the change and add a new line after the opening div and before the closing div instead.

The new line will allow the parser to switch context between Markdown and HTML.

2022-01-11 01:13 UTC, homeassistant commented
Hi @ScottG489, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#21140).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-01-14 08:50 UTC, frenck approved these changes
Thanks, @ScottG489 👍

2022-01-14 08:50 UTC, merged