add media play url support to roku
home-assistant/home-assistant.github.io pull request #21185
Opened 2022-01-14 04:35 UTC by ctalkington

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/64021
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-01-14 18:47 UTC, lvcabral requested changes

2022-01-14 18:47 UTC, lvcabral commented on source/_integrations/roku.markdown
> +| `extra.format` | no | A media format. Should be one of `mp4` (supports mov and m4v), `wma`, `mp3`, `hls`, `ism` (smooth streaming), `dash` (MPEG-DASH), `mkv`, `mka`, `mks` | `mp4`
Please add the support for HLS, as Roku can handle it. The best use case is to be able to use the HA service `camera.play_stream` just like the **Google Cast** integration supports. The `media_type` provided by HA when using `play_stream` is `media_type == FORMAT_CONTENT_TYPE[HLS_PROVIDER]`

2022-01-15 03:12 UTC, ctalkington commented on source/_integrations/roku.markdown
> +| `extra.format` | no | A media format. Should be one of `mp4` (supports mov and m4v), `wma`, `mp3`, `hls`, `ism` (smooth streaming), `dash` (MPEG-DASH), `mkv`, `mka`, `mks` | `mp4`
let's work on that here https://github.com/home-assistant/core/pull/64153

2022-01-16 17:00 UTC, frenck approved these changes

2022-01-16 17:00 UTC, merged

2022-01-16 21:51 UTC, ctalkington commented
thanks @frenck