Add page for PECO integration
home-assistant/home-assistant.github.io pull request #21392
Opened 2022-01-29 18:40 UTC by IceBotYT

## Proposed change

I am adding a page that documents how to use the PECO integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/3124

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-01-30 13:30 UTC, mrand commented
nws_alerts documentation page is included in this pull request.  Does this new integration provide nws_alerts, or is that just left over from the previous effort?

2022-01-30 13:38 UTC, IceBotYT commented
That’s just leftovers. Do you want me to revert it?

2022-01-30 14:37 UTC, mrand commented
If it's unrelated, I don't think this PR can be committed until it's removed.

2022-01-30 14:38 UTC, IceBotYT commented
Alright I’ll revert it and push. One moment

2022-01-30 14:58 UTC, IceBotYT commented
I have reverted the NWS Alerts page

2022-03-22 08:35 UTC, frenck requested changes

2022-03-22 08:35 UTC, frenck commented on source/_integrations/peco.markdown
> +The PECO Outage Counter integration allows you to get the current count of power outages for the county, and total for the operating region too.
```suggestion
The PECO Outage Counter integration allows you to get the current count of power outages for the county, and the total for the operating region too.
```

2022-03-22 08:35 UTC, frenck commented on source/_integrations/peco.markdown
> +
- Can we add something like links to the sources too?
- Maybe extend the story a little. For example, what this integration can do/is useful for.
- A comment for the countries this applies to might be helpful. I'm pretty sure the counties in my country, aren't covered 😉

2022-03-22 08:35 UTC, frenck commented on source/_integrations/peco.markdown
> +</div>
- Does this have to be a big info box?
- `TOTAL` isn't code and should not be code fenced.
- "TOTAL" is capitalized, which seems kinda shouty/unfriendly. Can we adjust that?

2022-03-22 08:35 UTC, frenck commented on source/_integrations/peco.markdown
> +ha_release: "2022.2.0"
```suggestion
ha_release: 2022.4
```

2022-03-27 14:29 UTC, frenck commented on source/_integrations/peco.markdown
> +<div class='note warning'>
Just a note will do 😉 

```suggestion
<div class='note'>
```

2022-03-27 14:29 UTC, frenck requested changes

2022-03-27 14:29 UTC, frenck commented on source/_integrations/peco.markdown
> +- `sensor.<county>_percent_customers_out`
Entity IDs are not guaranteed and, above all, can be changed. Instead, just describe the sensors instead.

2022-03-28 08:30 UTC, frenck approved these changes
Thanks, @IceBotYT 👍

2022-03-28 08:30 UTC, merged