Add config flow to fibaro
home-assistant/home-assistant.github.io pull request #21394
Opened 2022-01-29 20:54 UTC by rappenze

## Proposed change

A separate PR in core add's config flow suuport for the fibaro integration. This is the related change for the documentation. It replaces the configuraiton section with the standard config flow documentation by using the related include.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/65203
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-01-31 10:34 UTC, frenck requested changes

2022-01-31 10:34 UTC, frenck commented on source/_integrations/fibaro.markdown
>  ## Configuration
Please remove this heading, as it is inserted by the config flow include.

2022-01-31 17:55 UTC, frenck approved these changes
Thanks for the update @rappenze 👍 

✅ Approved. Can be merged as soon as the parent PR gets merged.

2022-03-26 19:50 UTC, bdraco approved these changes

2022-03-26 19:50 UTC, merged