Add name to example configuration.yaml
home-assistant/home-assistant.github.io pull request #21428
Opened 2022-02-01 16:40 UTC by MickMorley

name is required for the apprise platform to populate in the UI

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-02-01 16:40 UTC, homeassistant commented
Hi @MickMorley, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#21428).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-02-01 18:50 UTC, frenck requested changes
According to the code, it is optional:

<https://github.com/home-assistant/core/blob/aef6f49eff1fa9da9bf34460d5ab24d1e708f04c/homeassistant/components/notify/__init__.py#L35>

So, either this documentation change is incorrect, or its a bug in the code that needs to be fixed.

Either way, merging this makes the code & documentation out of sync.

2022-02-01 18:50 UTC, frenck requested changes
According to the code, it is optional:

<https://github.com/home-assistant/core/blob/aef6f49eff1fa9da9bf34460d5ab24d1e708f04c/homeassistant/components/notify/__init__.py#L35>

So, either this documentation change is incorrect, or its a bug in the code that needs to be fixed.

Either way, merging this makes the code & documentation out of sync.

2022-02-18 23:48 UTC, frenck reviewed
Closing this PR, as the name is actually optional.
If you do think we need an example that clarifies the use of the name option then please, open up a PR to add a separate example for that usage.

2022-02-18 23:48 UTC, closed without merging