Update nanoleaf.markdown
home-assistant/home-assistant.github.io pull request #21421
Opened 2022-01-31 17:59 UTC by ldvc86

included effect of transition on brightness, is no brightness is set.
As discussed with @milanmeu on https://github.com/home-assistant/core/issues/65078

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-01-31 17:59 UTC, homeassistant commented
Hi @ldvc86, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#21421).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-02-01 08:01 UTC, frenck requested changes

2022-02-01 08:01 UTC, frenck commented on source/_integrations/nanoleaf.markdown
> +When using transition in service calls (such as light.turn_on), transition is only applied to brightness and does not apply to color. When a service call has a transition set but no brightness is inc
```suggestion
# Transition and brightness

When using a transition in service calls (such as `light.turn_on`), the transition is only applied to brightness and does not apply to color. When a service call has a transition set but no brightness is included, the light will automatically transition to 100% brightness.
```

2022-02-01 08:01 UTC, frenck commented on source/_integrations/nanoleaf.markdown
> +When using transition in service calls (such as light.turn_on), transition is only applied to brightness and does not apply to color. When a service call has a transition set but no brightness is inc
Additionally, let move this section below the config flow section; as this is, of course, only a concern if one has set it up 😉

2022-02-01 11:06 UTC, milanmeu approved these changes
LGTM :+1: 
Thanks @ldvc86

2022-02-01 14:41 UTC, frenck approved these changes
Thanks! 👍

2022-02-01 14:41 UTC, merged