Update procedure on HAOS installation on x86_64
home-assistant/home-assistant.github.io pull request #21554
Opened 2022-02-08 18:57 UTC by c0ffeeca7

## Proposed change

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-02-16 13:50 UTC, agners commented on source/_includes/installation/operating_system.md
> +### Configure the BIOS on your x86-64 hardware
```suggestion
### Configure the BIOS on your x86-64 Hardware
```

2022-02-16 13:50 UTC, agners approved these changes, later dismissed

2022-02-16 13:58 UTC, frenck requested changes

2022-02-16 13:58 UTC, frenck commented on source/_includes/installation/operating_system.md
> +### Configure the BIOS on your x86-64 Hardware
```suggestion
### Configure the BIOS on your x86-64 hardware
```

2022-02-16 13:58 UTC, frenck commented on source/_includes/installation/operating_system.md
> +As a next step, we need to write the HA Operating System image to the target boot medium. The HAOS has no integrated installer. This means, the Operating System is not copied automatically to the int
```suggestion
As a next step, we need to write the Home Assistant Operating System image to the target boot medium. The HAOS has no integrated installer. This means the Operating System is not copied automatically to the internal disk.
```

2022-02-16 13:58 UTC, frenck commented on source/_includes/installation/operating_system.md
> +- Alternatively, an external medium can be used to boot HAOS such as an USB SDD (not recommended).
```suggestion
- The "boot medium" is the medium your x86-64 hardware will boot from when it is running Home Assistant.
- Typically, an internal medium is used for the x86-64 hardware. Examples of internal media are S-ATA hard disk, S-ATA SSD, M.2 SSD, or a non-removable eMMC.
- Alternatively, an external medium can be used to boot HAOS such as a USB SDD (not recommended).
```

2022-02-16 13:58 UTC, frenck commented on source/_includes/installation/operating_system.md
> +2. Copying a live operating system (e.g. Ubuntu) onto a USB device. Then, insert this USB device to your x86-64 hardware and start the Ubuntu.
```suggestion
To install the HAOS internally on your x86-64 hardware, there are 2 methods:

1. Copying the HAOS disk image from your Desktop computer onto your boot medium (e.g. by using a USB to S-ATA adapter). This is not an option for a non-removable eMMC on your x86-64 hardware, of course.
To use this method, follow the steps described in the procedure below: [Write the image to your boot media](#write-the-image-to-your-boot-media).
2. Copying a live operating system (e.g. Ubuntu) onto a USB device. Then, insert this USB device into your x86-64 hardware and start the Ubuntu.
```

2022-02-16 13:58 UTC, frenck commented on source/_includes/installation/operating_system.md
> +1. If you used your Desktop system to write the HAOS your boot media, install the boot media ({{site.installation.types[page.installation_type].installation_media}}) in the generic-x86-64 system.
```suggestion
1. If you used your desktop system to write the HAOS your boot media, install the boot media ({{site.installation.types[page.installation_type].installation_media}}) in the generic-x86-64 system.
```

2022-02-16 13:58 UTC, frenck commented on source/_includes/installation/operating_system.md
> +- If you used a live operating system (e.g. Ubuntu), shutdown the live operating system and make sure to remove the USB flash drive you used for the live system.
```suggestion
- If you used a live operating system (e.g. Ubuntu), shut down the live operating system and make sure to remove the USB flash drive you used for the live system.
```

2022-02-17 14:10 UTC, frenck approved these changes
Thanks, @c0ffeeca7 👍

2022-02-17 14:10 UTC, merged