Add documentation for new Rabbit Air integration
home-assistant/home-assistant.github.io pull request #21560
Opened 2022-02-09 01:01 UTC by al-s

## Proposed change

Add documentation for the new RabbitAir integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/66130
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/3150
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-02-09 01:01 UTC, homeassistant commented
Hi @al-s, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#21560).

Once you do that we will be able to review and accept this pull request.

Thanks!

2024-01-08 11:43 UTC, frenck commented on source/_integrations/rabbitair.markdown
> +ha_release: 2022.3
```suggestion
ha_release: 2024.2
```

2024-01-08 11:47 UTC, frenck requested changes, later dismissed

2024-01-08 11:47 UTC, frenck commented on source/_integrations/rabbitair.markdown
> +The fan platform of this integration allows you to turn on/off the unit, select the preset mode or set the speed manually.
```suggestion
The Rabbit Air integration lets you control your air purifier over the local network. The following device models are currently supported:

- MinusA2 (2-nd generation)
- A3

The fan platform of this integration allows you to turn the unit on/off, select the preset mode, or set the speed manually.
```

2024-01-08 11:47 UTC, frenck commented on source/_integrations/rabbitair.markdown
> +## Retrieving the Access Token
```suggestion
## Pre-requisites
```

2024-01-08 11:47 UTC, frenck commented on source/_integrations/rabbitair.markdown
> +4. On this page, quickly tap on "Serial Number" several times until you see two more lines that were previously hidden. The first is the device ID, and the second is the access token.
```suggestion
1. Open the Rabbit Air mobile app. You will see a list of devices connected to your account.
2. Tap the list item, and the device control page will open.
3. On the device page, select the **Edit** button. You will see a page with the device location and name settings.
4. On this page, quickly tap **Serial Number** several times until you see two more previously hidden lines. The first is the device ID, and the second is the access token.
```

2024-01-08 11:47 UTC, frenck commented on source/_integrations/rabbitair.markdown
> +Then you can use `abcdef1234_123456789012345678.local` as the "Host" and `0123456789ABCDEF0123456789ABCDEF` as the "Access Token".
```suggestion
Then you can use `abcdef1234_123456789012345678.local` as the **Host** and `0123456789ABCDEF0123456789ABCDEF` as the **Access Token**.
```

2024-01-10 09:20 UTC, c0ffeeca7 commented on source/_integrations/rabbitair.markdown
> +## Pre-requisites
```suggestion
## Prerequisites
```

2024-01-10 09:21 UTC, c0ffeeca7 approved these changes
Thank you, @al-s :+1:

2024-01-10 09:22 UTC, merged