Add some details to wiz docu
home-assistant/home-assistant.github.io pull request #21628
Opened 2022-02-13 16:40 UTC by sbidy

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/44779
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-02-14 13:37 UTC, frenck requested changes

2022-02-14 13:37 UTC, frenck commented on source/_integrations/wiz.markdown
> +More details can be found in the [official Docker documentation](https://docs.docker.com/network/host/).
This section can be removed, we do not support running it without host networking.

```suggestion
```

2022-02-14 13:37 UTC, frenck commented on source/_integrations/wiz.markdown
> +4. Enable the switch **Allow local communication**
Should this be listed as prerequisites above the config flow instructions?

2022-02-14 13:37 UTC, frenck commented on source/_integrations/wiz.markdown
> +If you have further questions, please have a look into the [WiZ Support Page](https://www.wizconnected.com/en/consumer/support/).
```suggestion
To connect a WiZ device to your Wi-Fi network, please follow the instructions in the [WiZ app](https://www.wizconnected.com/en/consumer/app/) (available for iOS and Android).
If you have further questions, please have a look at the [WiZ Support Page](https://www.wizconnected.com/en/consumer/support/).
```

2022-02-14 13:37 UTC, frenck commented on source/_integrations/wiz.markdown
> +The integration needs to communicated locally with the WiZ device. This setting **Allow local communication** can be disabled or enabled in WiZ app.
```suggestion
The integration needs to communicate locally with the WiZ device. This setting **Allow local communication** can be disabled or enabled in WiZ app.
```

2022-02-14 13:37 UTC, frenck commented on source/_integrations/wiz.markdown
> +4. Enable the switch **Allow local communication**
```suggestion
1. Open the WiZ app on your phone.
2. Click on the settings menu in the upper-left corner.
3. Scroll down to the security settings.
4. Enable the switch **Allow local communication**.
```

2022-02-14 14:38 UTC, sbidy commented on source/_integrations/wiz.markdown
> +4. Enable the switch **Allow local communication**
The connection part should be above. Because this step is necessary if you plug in a device the first time.

2022-02-19 20:06 UTC, frenck approved these changes, later dismissed
Thanks, @sbidy 👍

2022-02-19 20:14 UTC, frenck approved these changes

2022-02-19 20:14 UTC, merged