Add inverted option
home-assistant/home-assistant.github.io pull request #21774
Opened 2022-02-24 11:31 UTC by the-real-wizhack

Add configuration for using inverted option in configuration.yaml

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-02-24 11:31 UTC, homeassistant commented
Hi @the-real-wizhack, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#21774).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-03-27 14:06 UTC, frenck requested changes

2022-03-27 14:06 UTC, frenck commented on source/_integrations/rflink.markdown
> +This configuration uses `0a0a0a` to control the inverted shutter (send UP to close and Down to open) and listen commands sent by `0f1f2f` remote control.
````suggestion
### Invert cover

Devices can be configure to work in inverted mode by adding option in `configuration.yaml`:

```yaml
# Example configuration.yaml entry for inverted RTS cover
cover:
  - platform: rflink
    devices:
      # Rfloader created remote control which is used by Home Assistant
      RTS_0a0a0a_1:
        name: "Blind office"
        aliases: 
          - rts_0f1f2f_01 # ID of the remote control (Somfy smove in this case)
        type: inverted
 ```

This configuration uses `0a0a0a` to control the inverted shutter (send UP to close and Down to open) and listen commands sent by `0f1f2f` remote control.

````

2022-03-27 14:09 UTC, frenck approved these changes
Thanks, @the-real-wizhack 👍

2022-03-27 14:09 UTC, merged