Add JVC Projector Integration
home-assistant/home-assistant.github.io pull request #21835
Opened 2022-02-27 23:27 UTC by iloveicedgreentea

## Proposed change
This adds the documentation for my JVC Projectors integration. 

https://github.com/home-assistant/core/compare/dev...iloveicedgreentea:jvc_projector?expand=1

PR to the HA repo pending until this is made.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

 https://github.com/home-assistant/core/compare/dev...iloveicedgreentea:jvc_projector?expand=1

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-02-27 23:39 UTC, iloveicedgreentea commented
> It seems that this PR is targeted against an incorrect branch. Documentation updates which apply to our current stable release should target the `current` branch. Please change the target branch of this PR to `current` and rebase if needed. If this is documentation for a new feature, please add a link to that PR in your description. (message by DocsTargetBranch)

PR is here, added to description: https://github.com/home-assistant/core/pull/67358

2022-02-28 00:32 UTC, klaasnicolaas requested changes

2022-02-28 00:32 UTC, klaasnicolaas commented on source/_integrations/jvc_projectors.markdown
> +{% endconfiguration_basic %}
{% include integrations/config_flow.md %}

2022-02-28 00:32 UTC, klaasnicolaas commented on source/_integrations/jvc_projectors.markdown
> +{% raw %}
```suggestion
```

2022-02-28 00:32 UTC, klaasnicolaas commented on source/_integrations/jvc_projectors.markdown
> +{% endraw %}
```suggestion
```

2022-02-28 00:32 UTC, klaasnicolaas commented on source/_integrations/jvc_projectors.markdown
> +[jvc projectors]: /integrations/jvc_projectors
```suggestion
```

2022-02-28 00:32 UTC, klaasnicolaas commented on source/_integrations/jvc_projectors.markdown
> +The `jvc_projectors` platform allows you to control [JVC Projectors](https://www.us.jvc.com/projectors/) from Home Assistant. It is likely that your device is supported by the [jvc_projectors] platfo
```suggestion
The `jvc_projectors` integration allows you to control [JVC Projectors](https://www.us.jvc.com/projectors/) with Home Assistant.
```

2022-05-30 09:11 UTC, frenck commented
Closing PR as the parent PR has been closed.

2022-05-30 09:11 UTC, closed without merging