Document Mazda button entities
home-assistant/home-assistant.github.io pull request #21894
Opened 2022-03-04 05:51 UTC by bdr99

## Proposed change

Add documentation for Mazda button entities.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-03-09 03:49 UTC, bdraco commented on source/_integrations/mazda.markdown
> +- Turn on hazard lights (lights will flash briefly and then then turn off)
```suggestion
- Turn on hazard lights (lights will flash briefly and then turn off)
```

2022-03-09 03:49 UTC, bdraco commented on source/_integrations/mazda.markdown
> +- Refresh vehicle status (only refreshes electric vehicle related information)
```suggestion
- Refresh vehicle status (only refreshes electric vehicle-related information)
```

2022-03-10 18:58 UTC, bdr99 commented
@bdraco Addressed your comments.

2022-03-10 19:42 UTC, klaasnicolaas requested changes

2022-03-10 19:42 UTC, klaasnicolaas commented on source/_integrations/mazda.markdown
> +Button entities are available to perform the following actions:
```suggestion
Button entities are available to perform the following actions:

```

2022-03-10 19:42 UTC, klaasnicolaas commented on source/_integrations/mazda.markdown
> +Additionally, the following button entity is available for electric vehicles:
```suggestion
Additionally, the following button entity is available for electric vehicles:

```

2022-03-10 19:50 UTC, klaasnicolaas approved these changes
✅ LGTM

2022-03-12 02:09 UTC, bdraco approved these changes

2022-03-12 02:09 UTC, merged