Updated documentation on DTE bridge
home-assistant/home-assistant.github.io pull request #21933
Opened 2022-03-07 16:11 UTC by jcmendez

This integration is still useful for some people with v1 bridges and those who have prevented v2 bridges from further updates from DTE, but the majority of new users will go into a rabbit hole by trying this integration, failing, then trying to troubleshoot.  Better to have this out front.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-03-07 16:11 UTC, homeassistant commented
Hi @jcmendez, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#21933).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-03-09 09:35 UTC, frenck requested changes

2022-03-09 09:35 UTC, frenck commented on source/_integrations/dte_energy_bridge.markdown
> +you get any response.  If your firmware is not supported, see [this tread](https://github.com/home-assistant/core/issues/20170#issuecomment-478752765) for workarounds using MQTT
- Adjusted to use notes from our style guide.
- Tweaked wording a bit
- Removed reference to external issues with workarounds, as that is not related to this integration.

```suggestion
<div class='note'>

The firmware of the DTE v2 bridges that started shipping circa mid-2020 will not work with this integration.

You can check if your firmware is still supported by trying accessing `http://{ip_address}:8888/zigbee/se/instantaneousdemand`, and see if
you get a response.

</div>
```

2022-03-11 12:07 UTC, frenck approved these changes
Thanks, @jcmendez 👍

2022-03-11 12:07 UTC, merged