Update decora_wifi setup instructions
home-assistant/home-assistant.github.io pull request #22005
Opened 2022-03-13 01:52 UTC by connorwagner

## Proposed change

This PR updates the decora_wifi integration to be configurable via the UI
and adds explicit support for Leviton Decora fan controllers.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/68070
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-03-13 07:09 UTC, frenck requested changes
Please make sure to add the `ha_config_flow` frontmatter configuration parameter as well.

2022-03-13 07:09 UTC, frenck commented on source/_integrations/decora_wifi.markdown
> +To enable the integration, configure it via the "Add Integration" workflow in the configuration section of the Home Assistant web UI.
Use/include our snippet instead:

`{% include integrations/config_flow.md %}`

2022-03-13 15:43 UTC, connorwagner commented on source/_integrations/decora_wifi.markdown
> +To enable the integration, configure it via the "Add Integration" workflow in the configuration section of the Home Assistant web UI.
Updated, thanks!

2022-06-28 13:55 UTC, frenck commented
Closing PR as the parent PR has been closed.

2022-06-28 13:55 UTC, closed without merging