Add config flow for Utility Meter
home-assistant/home-assistant.github.io pull request #22180
Opened 2022-03-28 18:49 UTC by frenck

## Proposed change

Updates documentation for the configuration flow that is added to the Utility Meter

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/68457
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-03-28 20:57 UTC, dgomes approved these changes, later dismissed
👍

2022-03-28 21:37 UTC, frenck commented on source/_integrations/utility_meter.markdown
> +Alternatlively, this integration can be configured and set up manually via YAML
```suggestion
Alternatively, this integration can be configured and set up manually via YAML
```

2022-03-29 12:49 UTC, emontnemery commented on source/_integrations/utility_meter.markdown
> +    the offsetting of these beginnings.
We should mention config flows only supports an offset counted in days, and that yaml gives more freedom.
We should also mention that if the combination of "meter reset cycle" and "meter reset offset" is too limiting, yaml supports CRON patterns.

2022-04-04 10:40 UTC, emontnemery requested changes

2022-04-04 10:40 UTC, emontnemery commented on source/_integrations/utility_meter.markdown
> +    finegranded offset, consider using the YAML configuration below, which
```suggestion
    fine-grained offset, consider using the YAML configuration below, which
```

2022-04-04 10:40 UTC, emontnemery commented on source/_integrations/utility_meter.markdown
> +    tariff is needed.
```suggestion
    A list of supported tariffs, leave empty if only a single tariff is needed.
```

2022-04-04 11:22 UTC, merged