Improve Chromecast on different subnet docs
home-assistant/home-assistant.github.io pull request #22187
Opened 2022-03-29 18:50 UTC by slovdahl

## Proposed change

Add information about the shortcomings identified in https://github.com/home-assistant/core/issues/27174.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes https://github.com/home-assistant/core/issues/66974

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-03-29 19:07 UTC, emontnemery reviewed
Can you confirm the address translation is to make the mDNS based discovery work, or to make TCP-based communication with the chromecasts work?

2022-04-01 08:41 UTC, emontnemery requested changes

2022-04-01 08:41 UTC, emontnemery commented on source/_integrations/cast.markdown
> +If it is not possible, it's necessary to either enable mDNS forwarding between the subnets or to configure a list of known hosts. In addition to that, source NAT may need to be enabled to make reques
```suggestion
If it is not possible to have Home Assistant and the cast devices on the same subnet, it's necessary to either enable mDNS forwarding between the subnets or to configure a list of known hosts.

In addition to the problem with mDNS discovery across subnets, some Cast devices have been reported to block TCP based traffic not originating from their own subnet, if this is the case source NAT needs to be enabled to make TCP based traffic from Home Assistant to the Chromecast appear as originating from the same subnet.

Setups with cast devices on a different subnet than Home Assistant are strongly advised against and not supported.
```

2022-04-01 08:41 UTC, emontnemery commented on source/_integrations/cast.markdown
>  Automatic discovery in setups with cast devices on a different subnet than Home Assistant is not recommended and not supported.
```suggestion
```

2022-04-01 08:42 UTC, emontnemery commented
Rephrased assuming source NAT is required to make TCP based requests work.
@slovdahl Can you please help confirm this is the case?

2022-04-01 08:43 UTC, emontnemery commented
I'm setting this PR to draft until we have a confirmation from @slovdahl

2022-04-02 17:26 UTC, slovdahl commented
Sorry for the delay.

> Rephrased assuming source NAT is required to make TCP based requests work.
@slovdahl Can you please help confirm this is the case?

Yes, that was the intention at least. mDNS discovery has always worked fine for me, but I've had some problems with getting e.g. the playing/paused state synchronized in a timely manner to HA, and initially it seemed like enabling source NAT improved the situation. But in the end, I'm still having the same kind of problems, so it's probably something else.

2022-04-02 17:27 UTC, slovdahl commented on source/_integrations/cast.markdown
> +If it is not possible, it's necessary to either enable mDNS forwarding between the subnets or to configure a list of known hosts. In addition to that, source NAT may need to be enabled to make reques
Thanks, good suggestion 👍

2022-04-15 11:02 UTC, emontnemery commented
> initially it seemed like enabling source NAT improved the situation. But in the end, I'm still having the same kind of problems, so it's probably something else

Should we close the PR then if you're not sure enabling source NAT makes any difference?

2022-04-15 17:33 UTC, slovdahl commented
No strong opinion either way as far as I'm concerned. It _did_ seem to do the trick for @nayfield according to #66974 though.

2022-06-22 05:06 UTC, closed without merging