Menu/resume
home-assistant/home-assistant.github.io pull request #22195
Opened 2022-03-30 11:56 UTC by QbaF

As divided for three types described separatelly, I propose that small menu/resume.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-03-31 13:01 UTC, frenck requested changes

2022-03-31 13:01 UTC, frenck commented on source/dashboards/header-footer.markdown
> +- [graph] /dashboards/header-footer/#graph-header--footer
- These are on this page? Show in the sidebar?
- This doesn't work?

2022-03-31 17:03 UTC, QbaF commented on source/dashboards/header-footer.markdown
> +- [graph] /dashboards/header-footer/#graph-header--footer
Are on this page. They are just 3 types of header/footer.

2022-03-31 18:04 UTC, frenck commented on source/dashboards/header-footer.markdown
> +- [graph] /dashboards/header-footer/#graph-header--footer
Ok, so I'm confused on why this is added in that case?

(besides the fact, it doesn't work..)

2022-04-01 09:02 UTC, QbaF commented on source/dashboards/header-footer.markdown
> +- [graph] /dashboards/header-footer/#graph-header--footer
Ok. When I was looking in the documentation for info about footers/headers I found it firstly not clear (mainly why configuration variable `type` has only `picture` argument). Just for a few seconds but I thought that some users could find it useful when supplemented with a short menu at the beginning. And I thought that I can somehow help that great community with that small contribution when proposing some changes. 

You can use it, correct it or point me out what or how I should correct, it or throw it away.  I will not feel offended, I promise;) Maybe completely fresh to GitHub, as I am, shouldn't try to cooperate with changes proposals as maybe it brings more troubles than goods.

This was the answer to why I added those links on the page.

Why these links don't work - I have no idea. I wrote it based on other parts of the code while checking links on the page. Conclusion could be as above.

2022-05-16 09:55 UTC, frenck commented
Going to close this PR and friendly decline its contents. Besides the case is not clear to me, it also isn't working either.

2022-05-16 09:55 UTC, closed without merging