Describe how to use custom polling intervals
home-assistant/home-assistant.github.io pull request #22351
Opened 2022-04-11 18:56 UTC by oischinger

## Proposed change
Many users complain that the `scan_interval` option was dropped.
We should at least provide them with a code snippet for manual scheduling

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #67052 #65806

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-04-12 10:55 UTC, frenck requested changes

2022-04-12 10:55 UTC, frenck commented on source/_integrations/vicare.markdown
> +### Customizing the poll interval
This is not specific to vicare. Instead, this should be generally documented (and not as an exception for an integration).

2022-04-26 10:50 UTC, frenck requested changes

2022-04-26 10:50 UTC, frenck commented on source/_docs/configuration/platform_options.markdown
> +### Platforms set up via the UI
This is not a platform option and thus should not be documented here as such.

2022-05-24 17:12 UTC, oischinger commented
I don't know where and how to do this properly

2022-05-24 17:12 UTC, closed without merging