Adjust Slack documentation for config flow
home-assistant/home-assistant.github.io pull request #22353
Opened 2022-04-11 19:04 UTC by tkdrob

## Proposed change

Adjust Slack documentation for config flow

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/69880
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-04-12 23:40 UTC, bachya submitted a review, later dismissed

2022-04-13 06:50 UTC, frenck requested changes

2022-04-13 06:50 UTC, frenck commented on source/_integrations/slack.markdown
> +{% include integrations/config_flow.md %}
The order is incorrect I think. Let's make a prerequisites chapter first, with the instructions on how to obtain the needed keys first, then add the config flow include after that.

2022-05-16 09:16 UTC, frenck approved these changes

2022-05-16 09:16 UTC, merged