workday sensor example added to documentation
home-assistant/home-assistant.github.io pull request #22366
Opened 2022-04-12 17:20 UTC by kenshub

## Proposed change
Add example with 2 workday sensors

## Type of change
- [x ] Adjusted missing or incorrect information in the current documentation (`current` branch).

## Additional information
People in this thread thought they were limited to 1 workday sensor.
https://community.home-assistant.io/t/create-2-different-calendars-for-different-automations-to-work-or-not/283634/13

2022-04-12 17:20 UTC, homeassistant commented
Hi @kenshub, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#22366).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-04-12 17:39 UTC, frenck requested changes

2022-04-12 17:39 UTC, frenck commented on source/_integrations/workday.markdown
> +    name: workday-default
Enquote strings please, and let's use a descriptive name. This applies to all string in this YAML example. For more information see:

<https://developers.home-assistant.io/docs/documenting/yaml-style-guide>

Also, using descriptive names, makes it more readable and less needed to explain what it is in the above text preceding this example.

2022-04-12 17:39 UTC, frenck commented on source/_integrations/workday.markdown
> +This example has two workday sensors. The default mon-fri workday and a 2nd `schoolday-name` sensor for tue-thu.
Let's avoid abbreviating the weekdays

2022-05-23 17:05 UTC, frenck commented
Since there was no response at all, I'm declaring this PR stale and closing it.
Feel free to re-open this PR when you feel like that is the appropriate thing to do.

2022-05-23 17:05 UTC, closed without merging