Update seventeentrack config
home-assistant/home-assistant.github.io pull request #22428
Opened 2022-04-19 01:55 UTC by McSwindler

Updating the seventeentrack docs to confirm with the new V1 API configuration

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-04-19 01:55 UTC, homeassistant commented
Hi @McSwindler, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#22428).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-05-02 01:18 UTC, rjmidau requested changes
* Update documentation to reflect that the Integration now uses Config Flow instead of YAML
* Explicitly mention that you must create a Developer-type account, not a Buyer or Seller account (which get Permission Denied errors when trying to access api.17track.net). It isn't possible to convert an existing account between types.
* It's not possible to get to the Settings page directly from the URL mentioned in this document. You must click on 'Go to dashboard', then the Settings page (https://api.17track.net/en/admin/settings) is linked off the Dashboard (https://api.17track.net/en/admin/dashboard).

2022-05-09 16:33 UTC, McSwindler commented
@rjmidau Hopefully I have addressed all of your comments :)

2022-05-09 16:34 UTC, frenck requested changes

2022-05-09 16:34 UTC, frenck commented on source/_integrations/seventeentrack.markdown
> +1. Register for an account: https://user.17track.net/en/register
Please don't use bare URLs.

2022-05-09 16:34 UTC, frenck commented on source/_integrations/seventeentrack.markdown
> +3. Select "Developer Account"
```suggestion
3. Select "Developer Account".
```

2022-05-09 16:34 UTC, frenck commented on source/_integrations/seventeentrack.markdown
> +6. Open the settings page: https://api.17track.net/en/admin/settings
Please don't use bare URLs.

2022-05-09 16:34 UTC, frenck commented on source/_integrations/seventeentrack.markdown
> +7. API Token will be displayed under the Security tab
```suggestion
7. API Token will be displayed under the Security tab.
```

2022-05-09 16:34 UTC, frenck commented on source/_integrations/seventeentrack.markdown
> +{% include integrations/config_flow.md %}
Did you forget to update the frontmatter to indicate config flow support?

2022-05-09 17:28 UTC, frenck commented on source/_integrations/seventeentrack.markdown
> +The `seventeentrack` sensor platform allows users to get package data tied to their [17track.net](https://api.17track.net/en) account. The platform creates both summary sensors, which show the number
Just noticed this one, as this is an integration now :)

```suggestion
The 17TRACK integration allows users to get package data tied to their [17track.net](https://api.17track.net/en) account. The platform creates both summary sensors, which show the number of packages in a current state (e.g., "In Transit"), as well as individual sensors for each package within the account.
```

2022-05-11 09:43 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2023-10-06 09:30 UTC, frenck commented
Closing PR as the parent PR has been closed.

2023-10-06 09:30 UTC, closed without merging