Add trigger and condition to configuration vars
home-assistant/home-assistant.github.io pull request #22467
Opened 2022-04-22 08:52 UTC by TheFes

Whoops, forgot two important ones

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-04-22 09:06 UTC, frenck requested changes

2022-04-22 09:06 UTC, frenck commented on source/_docs/automation/yaml.markdown
> +  description: The trigger(s) which will start the automation. Multiple triggers can be added and the automation will start when any of these triggers changes from `false` to `true`.
Triggers are not conditional (e.g., can be event based too); so its not about being true or false.

```suggestion
  description: The trigger(s) which will start the automation. Multiple triggers can be added and the automation will start when any of these triggers trigger.
```

2022-04-22 09:06 UTC, frenck commented on source/_docs/automation/yaml.markdown
> +      description: An id which can be used in the automatin to determine which trigger caused the automation to start
```suggestion
      description: An ID that can be used in the automation to determine which trigger caused the automation to start.
```

2022-04-22 09:06 UTC, frenck commented on source/_docs/automation/yaml.markdown
> +      description: Variables which will be available in the conditions and action sequence.
```suggestion
      description: Variables that will be available in the conditions and action sequence.
```

2022-04-22 09:06 UTC, frenck commented on source/_docs/automation/yaml.markdown
> +  description: Conditions which have to be `true` to start the automation. By default all conditions listed have to be `true`, you can use [logical conditions](https://www.home-assistant.io/docs/scri
```suggestion
  description: Conditions that have to be `true` to start the automation. By default all conditions listed have to be `true`, you can use [logical conditions](/docs/scripts/conditions/#logical-conditions) to change this default behavior.
```

2022-04-22 11:04 UTC, TheFes commented
@frenck I think I messed something up, It seems there is a review requesting changes pending, but I don't see it anymore.

2022-04-23 14:06 UTC, klaasnicolaas approved these changes
✅ LGTM but let @frenck make the final review 👀 
BTW the open change request is because of the first round of changes tot Frenck has suggested 😉

2022-04-23 20:43 UTC, TheFes commented
@klaasnicolaas Thanks! I accepted all of them, but then messed something up and committed a version without the new part in it.
I did a new commit after that, with the `trigger` and  `condition` part in it, including the proposed changes by @frenck 

But if it is just the final review now, then it's probably fine. :)

2022-04-26 10:21 UTC, frenck approved these changes
Thanks, @TheFes 👍

2022-04-26 10:21 UTC, merged