21029
home-assistant/home-assistant.github.io pull request #22484
Opened 2022-04-23 00:54 UTC by dannytsang

## Proposed change
Added missing customization example to the Nmap integration documentation. I used a typical home network address and the default scan options when you add the Nmap integration.

I have also added links to what I believe is the official Nmap documentation online if people want more details.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #21029

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-04-23 13:41 UTC, klaasnicolaas requested changes, later dismissed

2022-04-23 13:41 UTC, klaasnicolaas commented on source/_integrations/nmap_tracker.markdown
> +  * **--host-timeout 5s** sets the maximum time a device has to respond to a scan before it gives up on waiting.
Please use the `{% configuration_basic %}` / `{% endconfiguration_basic %}` format

2022-05-09 09:31 UTC, frenck commented on source/_integrations/nmap_tracker.markdown
> +  description: A comma separated list of IP address to not scan. The above example will skip `192.168.1.50`.
```suggestion
  description: A comma-separated list of IP addresses not to scan. The above example will skip `192.168.1.50`.
```

2022-05-17 08:14 UTC, frenck approved these changes
Thanks, @dannytsang 👍

2022-05-17 08:15 UTC, merged