Added Documentation for Multilevel Switch
home-assistant/home-assistant.github.io pull request #22488
Opened 2022-04-23 06:29 UTC by reubenbijl

Added feature in ZwaveJS 9
https://github.com/home-assistant/core/pull/68830#pullrequestreview-950921456

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-04-23 06:39 UTC, raman325 commented on source/_integrations/zwave_js.markdown
> +#### MultilevelSwitch Notification Command Class
```suggestion
#### MultilevelSwitch Command Class
```

2022-04-23 06:39 UTC, raman325 commented on source/_integrations/zwave_js.markdown
> +##### Stop Level Change
```suggestion
```

##### Stop Level Change
```

2022-04-23 06:41 UTC, raman325 commented on source/_integrations/zwave_js.markdown
> +##### Stop Level Change
Remove the slash, it was the only way to make this a commitable suggestion

2022-04-23 06:52 UTC, raman325 commented on source/_integrations/zwave_js.markdown
> +\```
```suggestion
```
```

2022-04-23 06:53 UTC, raman325 requested changes
please remove the backslash I added and then this should be good to go

2022-04-23 06:54 UTC, raman325 approved these changes, later dismissed
Fixed and approved, thanks!

2022-04-23 07:23 UTC, reubenbijl reviewed
Thanks, sorry, I read it correctly, and then accidentally accepted the whole commit.

2022-04-27 07:13 UTC, MartinHjelmare approved these changes
Thanks!

2022-04-27 07:14 UTC, merged