Remove broken links
home-assistant/home-assistant.github.io pull request #22615
Opened 2022-05-03 13:20 UTC by wrt54g

## Proposed change

I removed 2 more broken links in the Help page.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-04 12:22 UTC, fabaff requested changes

2022-05-04 12:22 UTC, fabaff commented on source/help/index.markdown
> -- [Home Assistant workshop](https://github.com/home-assistant/home-assistant-assets/tree/master/german/2017-clt-workshop) at [CLT 2017](https://chemnitzer.linux-tage.de/2017/de/) - March 2017
That link would be: https://github.com/home-assistant-ecosystem/workshops/tree/main/2017-clt-workshop

2022-05-04 12:22 UTC, fabaff commented on source/help/index.markdown
> -- [Home Assistant - Erweiterungen (Platforms/Components)](https://github.com/home-assistant/home-assistant-assets/tree/master/german/2016-puzzle) at [Puzzle ITC](https://www.puzzle.ch/de/) - December
That link would be: https://github.com/home-assistant-ecosystem/workshops/tree/main/2016-puzzle

2022-05-04 12:22 UTC, fabaff commented on source/help/index.markdown
> -- [10 open source software tools for developing IoT applications](https://www.cbronline.com/news/internet-of-things/10-open-source-software-tools-developing-iot-applications/) - March 2017
We could use archive.org: http://web.archive.org/web/20200926222601/https://www.cbronline.com/news/internet-of-things/10-open-source-software-tools-developing-iot-applications/

I guess that we can remove that link as the section about Home Assistant is very short.

2022-05-04 17:41 UTC, wrt54g commented
@fabaff I fixed them now.

2022-05-06 16:08 UTC, fabaff requested changes

2022-05-06 16:08 UTC, fabaff commented on source/help/index.markdown
> +- - [Home Assistant workshop](https://github.com/home-assistant-ecosystem/workshops/tree/main/2017-clt-workshop) at [CLT 2017](https://chemnitzer.linux-tage.de/2017/de/) - March 2017
`-` instead of `- -`.

see https://deploy-preview-22615--home-assistant-docs.netlify.app/help/

2022-05-29 12:05 UTC, fabaff commented
Superseded by #22904

2022-05-29 12:05 UTC, closed without merging