Update sample .yaml to give noobs (like me) an easier starting point
home-assistant/home-assistant.github.io pull request #22629
Opened 2022-05-04 18:47 UTC by GitHubGoody

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-04 18:47 UTC, homeassistant commented
Hi @GitHubGoody, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#22629).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-05-04 23:26 UTC, frenck requested changes

2022-05-04 23:26 UTC, frenck commented on source/_integrations/systemmonitor.markdown
> +- sensor:
This line is actually incorrect now.

2022-05-04 23:26 UTC, frenck commented on source/_integrations/systemmonitor.markdown
> +      - type: disk_use
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2022-05-09 20:51 UTC, GitHubGoody reviewed
Made changes as requested by frenck

2022-05-11 09:44 UTC, frenck commented on source/_integrations/systemmonitor.markdown
> +        # specify arg:
Commented out code, please remove that.

2022-05-11 15:46 UTC, GitHubGoody reviewed
Removed commented out code

2022-06-28 13:58 UTC, frenck approved these changes
Thanks, @GitHubGoody 👍

2022-06-28 13:58 UTC, merged