Add documentation for installation on older BIOS's which don't detect…
home-assistant/home-assistant.github.io pull request #22628
Opened 2022-05-04 12:19 UTC by tsvi

… the EFI entry correctly

Fixes home-assistant/operating-system#1760

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-23 13:25 UTC, agners requested changes
It makes sense to add this as some systems indeed require it to be able to boot HAOS :+1:

2022-05-23 13:25 UTC, agners commented on source/_includes/installation/operating_system.md
> +  efibootmgr --create --disk /dev/sda --part 1 --label "HAOS" --loader \EFI\BOOT\bootx64.efi
I'd prefer adding a newline here so it looks nicer in the docs, e.g.

```
efibootmgr --create --disk /dev/sda --part 1 --label "HAOS" \
    --loader \EFI\BOOT\bootx64.efi
```

Also, can you replace `sda` with a placeholder and note that it should point to the drive where Home Assistant OS has been installed to, typically `sda` or `nvme0n1` if a NVMe SSD is used.

2022-05-23 19:05 UTC, agners approved these changes, later dismissed

2022-06-20 21:15 UTC, frenck commented on source/_includes/installation/operating_system.md
> +<div class="note">
```suggestion
<div class="note">

```

2022-06-21 06:38 UTC, frenck approved these changes
Thanks, @tsvi 👍

2022-06-21 06:39 UTC, merged