Clarification on ferry type and origin of data
home-assistant/home-assistant.github.io pull request #22627
Opened 2022-05-04 11:52 UTC by tubalainen

Clarification that Trafikverket only provides road ferry services and the English translation of Trafikverket "The Swedish Transport Administration".

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-04 13:46 UTC, frenck requested changes
This PR is targeting the `rc` branch, which should not be used. Either target `current` for existing documentation or `next` for new documentation.

Thanks! 👍

2022-05-04 13:46 UTC, frenck commented on source/_integrations/trafikverket_ferry.markdown
> +title: Trafikverket Road Ferry
This title is synced with the integration manifest. The manifest needs to be adjusted for this.

2022-05-04 15:17 UTC, tubalainen commented
> This PR is targeting the `rc` branch, which should not be used. Either target `current` for existing documentation or `next` for new documentation.
> 
> Thanks! 👍

My inexperience shows - sorry. Is there an easy way just to "move it" to `new` or do I have to close it an make the changes to `new`?

2022-05-05 06:01 UTC, closed without merging

2022-05-05 06:01 UTC, tubalainen commented
Made a booboo.

2022-05-05 06:01 UTC, tubalainen commented
Made a booboo

2022-05-05 08:00 UTC, frenck commented
> My inexperience shows - sorry. Is there an easy way just to "move it" to new or do I have to close it an make the changes to new?

Since 2022.5 was released, you could have just hit the edit button (near the title) and select `current` instead of `rc` as the target branch.