Add Sonos favorites notes
home-assistant/home-assistant.github.io pull request #22642
Opened 2022-05-05 14:17 UTC by jjlawren

## Proposed change

Adds a description and example usage of the new Sonos favorites sensor added in https://github.com/home-assistant/core/pull/70235.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-09 10:30 UTC, frenck requested changes

2022-05-09 10:30 UTC, frenck commented on source/_integrations/sonos.markdown
> +The Sonos favorites sensor (`sensor.sonos_favorites`) is disabled by default. It can be found and enabled from the entities associated with the Sonos integration on your [Integrations](https://my.hom
```suggestion
The Sonos favorites sensor (`sensor.sonos_favorites`) is disabled by default. It can be found and enabled from the entities associated with the Sonos integration on your {% my integrations %} page.
```

2022-05-09 10:30 UTC, frenck commented on source/_integrations/sonos.markdown
> +The favorites sensor provides the names and `media_content_id` values for each of the favorites saved to My Sonos in the native Sonos app. This replaces the legacy `source_list` attribute previously
I don't think we need to mention the legacy part (it will have no meaning after a few releases).

2022-05-09 19:08 UTC, jjlawren commented on source/_integrations/sonos.markdown
> +The favorites sensor provides the names and `media_content_id` values for each of the favorites saved to My Sonos in the native Sonos app. This replaces the legacy `source_list` attribute previously
Fair. I feel the rest of this still has value. Do you agree?

2022-05-09 21:16 UTC, frenck commented on source/_integrations/sonos.markdown
> +The favorites sensor provides the names and `media_content_id` values for each of the favorites saved to My Sonos in the native Sonos app. This replaces the legacy `source_list` attribute previously
Yeah agreed, it is just the deprecation/history lesson that feels a bit unneeded.

2022-05-10 06:50 UTC, frenck approved these changes
Thanks, @jjlawren 👍

2022-05-10 06:50 UTC, merged