Update markdown Trafikverket Train
home-assistant/home-assistant.github.io pull request #22657
Opened 2022-05-06 18:15 UTC by gjohansson-ST

## Proposed change

Update markdown for Trafikverket Train to provide better text.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-08 14:31 UTC, davet2001 requested changes

2022-05-08 14:31 UTC, davet2001 commented on source/_integrations/trafikverket_train.markdown
> +Next departure is calculated from actual, estimated and planned to provide most accurate information about departure.
Add 'the' after 'provide'.

2022-05-14 10:16 UTC, davet2001 submitted a review, later dismissed
LGTM 👍

2022-05-15 19:59 UTC, frenck commented on source/_integrations/trafikverket_train.markdown
> +- Delayed time
```suggestion
- Delayed time.
```

2022-05-15 19:59 UTC, frenck commented on source/_integrations/trafikverket_train.markdown
> +Next departure is calculated from actual, estimated and planned to provide the most accurate information about departure.
```suggestion
Next departure is calculated from actual, estimated, and planned to provide the most accurate information about departure.
```

2022-05-15 20:04 UTC, frenck approved these changes
Thanks,  @gjohansson-ST 👍

2022-05-15 20:04 UTC, merged