Fix the anchor links (and some others) in RSS
home-assistant/home-assistant.github.io pull request #22662
Opened 2022-05-06 23:11 UTC by RosemaryOrchard

I noticed in the RSS feed that the anchor links take me to `https://www.home-assistant.io/#new-automation--script-features` (for example), ideally these would be absolute URLs rather than full, which ought to fix the issue.

## Proposed change
Swap the `full_urls` filter for `absolute_url`, this is what the [jekyll-feed plugin](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml) does.

## Type of change
- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
N/A

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].
^(Yes, but not applicable I think?)

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-06 23:11 UTC, homeassistant commented
Hi @RosemaryOrchard, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#22662).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-05-09 09:41 UTC, frenck requested changes
This doesn't work as it seems? The CI fails. Could you take a look?

2022-05-09 22:23 UTC, RosemaryOrchard commented
> This doesn't work as it seems? The CI fails. Could you take a look?

Yes, I've been trying to do so but was on the wrong machine this weekend, I'll try again now!

2022-08-22 16:02 UTC, frenck commented
I've take a small moment to look at this, but I don't see how to solve this. Tied working with expand_urls, absolute_urls, full_urls and combinations of those, neither seems to expand anchors. Kinda makes sense, though, as anchors should not navigate away from your current panel/application.

2022-09-16 18:34 UTC, frenck commented
Since this one is running stale, I'll go ahead and close it.

2022-09-16 18:34 UTC, closed without merging