Adds docs for UP Chime support
home-assistant/home-assistant.github.io pull request #22754
Opened 2022-05-14 22:28 UTC by AngellusMortis

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/71874
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-15 19:55 UTC, frenck requested changes

2022-05-15 19:55 UTC, frenck commented on source/_integrations/unifiprotect.markdown
> +* **Device Configuration** - Smart chimes will get a volume slider adjust the loudness of the chime as well as sensor the last time the chime rang.
```suggestion
* **Device Configuration** - Smart chimes will get a volume slider to adjust the loudness of the chime as well as a sensor for the last time the chime rang.
```

2022-05-15 19:55 UTC, frenck commented on source/_integrations/unifiprotect.markdown
> +| `doorbells`            | No       | A [target selector](https://www.home-assistant.io/docs/blueprint/selectors/#target-selector) for any number of doorbells you want to pair to the chime. |
Please don't use full URLs; additionally: I'm also not sure how the target selector is relevant to mention or link in this case?

2022-05-20 20:22 UTC, bdraco commented on source/_integrations/unifiprotect.markdown
> +* **Button** - A button to trigger the chime manually for each smart chime device. Also a disabled by default button is added that will let you reboot your smart chime device.
```suggestion
* **Button** - A button to trigger the chime manually for each smart chime device. Also, a disabled by default button is added to let you reboot your smart chime device.
```

2022-05-20 20:22 UTC, bdraco commented on source/_integrations/unifiprotect.markdown
> +* **Device Configuration** - Smart chimes will get a volume slider to adjust the loudness of the chime as well as a sensor for the last time the chime rang.
```suggestion
* **Device Configuration** - Smart chimes will get a volume slider to adjust the chime's loudness and a sensor for the last time the chime rang.
```

2022-05-21 05:31 UTC, bdraco approved these changes

2022-05-23 10:35 UTC, frenck approved these changes

2022-05-23 10:36 UTC, merged