Add Netgear speed test info
home-assistant/home-assistant.github.io pull request #22819
Opened 2022-05-19 21:06 UTC by starkillerOG

## Proposed change

Add Netgear speed test info

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/72215
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-20 16:14 UTC, fabaff submitted a review, later dismissed

2022-05-20 16:14 UTC, fabaff commented on source/_integrations/netgear.markdown
> +The `Average Ping`, `Downlink Bandwidth` and `Uplink Bandwidth` can be tracked by perfoming a speedtest every 30 minutes.
```suggestion
The `Average Ping`, `Downlink Bandwidth` and `Uplink Bandwidth` can be tracked by performing a speedtest every 30 minutes.
```

2022-05-23 09:28 UTC, frenck requested changes

2022-05-23 09:28 UTC, frenck commented on source/_integrations/netgear.markdown
> +The `Average Ping`, `Downlink Bandwidth` and `Uplink Bandwidth` can be tracked by performing a speedtest every 30 minutes.
Those terms are not code and should not be code fenced for that reason.

2022-05-23 09:43 UTC, starkillerOG commented on source/_integrations/netgear.markdown
> +The `Average Ping`, `Downlink Bandwidth` and `Uplink Bandwidth` can be tracked by performing a speedtest every 30 minutes.
I changed it, thanks

2022-05-23 10:02 UTC, frenck commented on source/_integrations/netgear.markdown
> +The speed test intervall is chosen to be 30 minutes to not put unnesesarry load on the network.
```suggestion
The "Average Ping", "Downlink Bandwidth" and "Uplink Bandwidth" can be tracked by performing a speed test every 30 minutes.
If these sensor entities are enabled they will first show as Unknown since the first speed test does only happen 30 minutes after the integration loads, previous results will be restored on subsequent restarts.
The speed test interval is chosen to be 30 minutes to not put unnecessary load on the network.
```

2022-05-23 10:02 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2022-05-25 06:45 UTC, merged