Add number platform docs to Slack
home-assistant/home-assistant.github.io pull request #22842
Opened 2022-05-22 01:46 UTC by tkdrob

## Proposed change

Add number platform docs to Slack

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/72291
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-22 09:49 UTC, frenck requested changes

2022-05-22 09:49 UTC, frenck commented on source/_integrations/slack.markdown
> +- **Do Not Disturb**: Set Do Not Disturb period. This starts immediately when set and decreases until depleted.
Number entities are not allowed to decrease automatically (they are not countdown timers).

2022-07-20 15:00 UTC, veleek commented on source/_integrations/slack.markdown
> +- **Do Not Disturb Period**: Set Do Not Disturb period. This starts immediately when set.
This should indicate the unit of time.  Is it minutes, seconds, etc?

2022-12-08 20:58 UTC, tkdrob commented
I'm not so sure we need this with the current state of the parent.

2023-11-29 22:55 UTC, frenck commented
Closing PR as the parent PR has been closed.

2023-11-29 22:55 UTC, closed without merging