Add this variable to trigger-based templates
home-assistant/home-assistant.github.io pull request #22879
Opened 2022-05-24 19:29 UTC by akloeckner

## Proposed change

Document `this` for trigger-entities.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/72437
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-06-27 06:49 UTC, emontnemery requested changes, later dismissed

2022-06-27 06:49 UTC, emontnemery commented on source/_integrations/template.markdown
> -State-based template entities have the special template variable `this` available in their templates and actions. The `this` variable aids [self-referencing](#self-referencing) of an entity's state a
We should not remove this section because it's a subsection of "State-based template binary sensors, buttons, numbers, selects and sensors"

2022-06-27 13:40 UTC, akloeckner commented on source/_integrations/template.markdown
> -State-based template entities have the special template variable `this` available in their templates and actions. The `this` variable aids [self-referencing](#self-referencing) of an entity's state a
Or should we promote the inserted section to a second-level section, because it is valid for both (trigger and state based) entities now?

Edit: I have committed this change, in case you approve. I like it better to have the information in one place only. But I'll put it in two places, if you prefer.

2022-06-28 07:58 UTC, frenck approved these changes
Thanks, @akloeckner 👍

2022-06-28 07:59 UTC, merged

2022-06-28 08:00 UTC, emontnemery reviewed
Thanks, @akloeckner 👍