Update tasmota.markdown
home-assistant/home-assistant.github.io pull request #22891
Opened 2022-05-26 06:10 UTC by maxberger

Add hint on how to enable color settings on certain RGBCCT devices.

## Proposed change
Add documentation for RGBCCT lights. This was suggested here: https://community.home-assistant.io/t/tasmota-colour-light-support-via-mqtt/316773/4
and worked for me.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-26 06:11 UTC, homeassistant commented
Hi @maxberger, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#22891).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-05-30 10:58 UTC, emontnemery commented
When using the Tasmota integration (`setoption19 0`) , lights with colour support should always be correctly detected, and if they aren't that's a bug.

@maxberger I think the linked community topic may be talking about using the MQTT integration (`setoption19 1`) instead of the Tasmota integration (`setoption19 0`)?

2022-05-30 10:59 UTC, emontnemery requested changes
Please give more background to why this change is needed.

2022-05-30 11:11 UTC, maxberger commented
> When using the Tasmota integration (`setoption19 0`) , lights with colour support should always be correctly detected, and if they aren't that's a bug.
> 
> @maxberger I think the linked community topic may be talking about using the MQTT integration (`setoption19 1`) instead of the Tasmota integration (`setoption19 0`)?

My setoption19 is off, as instructed in this doc. The device shows up with 106 set to off, but does not allow me to change colors. After I used setoption106, the color support started working correctly.

If you rather want to treat this as a bug: Let me know what information you would need.

Current (working) state:
```12:02:42.872 CMD: setoption106
12:02:42.878 MQT: stat/tasmota_40C83D/RESULT = {"SetOption106":"ON"}
12:02:48.983 CMD: setoption19
12:02:48.989 MQT: stat/tasmota_40C83D/RESULT = {"SetOption19":"OFF"}
```

Device is a Teckin SB53, Tasmota is 11.1.0

2022-05-30 12:24 UTC, emontnemery commented
@maxberger OK, thanks for confirming!

Can you share how you've configured the various light related setoptions, the state of each setoption mentioned here would be helpful: https://tasmota.github.io/docs/Lights/#light

Also, how many PWM channels does your light have?

2022-05-30 19:36 UTC, maxberger commented
> Can you share how you've configured the various light related setoptions, the state of each setoption mentioned here would be helpful: https://tasmota.github.io/docs/Lights/#light

I listed all of them below; since I reset the device everything except for the setoption106 should be default value. 

> Also, how many PWM channels does your light have?
I am not 100% sure, I have been using this template which shows 5 channels: https://templates.blakadder.com/teckin_SB53.html
I can control R,G,B, Color Temperature, and Brightness.

Let me know if you need anything else!

```
20:27:13.863 CMD: SETOPTION99
20:27:13.869 MQT: stat/tasmota_40C83D/RESULT = {"SetOption99":"OFF"}
20:27:51.932 CMD: SetOption68
20:27:51.937 MQT: stat/tasmota_40C83D/RESULT = {"SetOption68":"OFF"}
20:28:23.834 CMD: SetOption105
20:28:23.840 MQT: stat/tasmota_40C83D/RESULT = {"SetOption105":"OFF"}
20:28:32.297 CMD: SetOption37
20:28:32.302 MQT: stat/tasmota_40C83D/RESULT = {"SetOption37":0}
20:28:42.967 CMD: SetOption20
20:28:42.973 MQT: stat/tasmota_40C83D/RESULT = {"SetOption20":"OFF"}
20:28:49.328 CMD: SetOption92
20:28:49.334 MQT: stat/tasmota_40C83D/RESULT = {"SetOption92":"OFF"}
20:28:56.681 CMD: SetOption106
20:28:56.687 MQT: stat/tasmota_40C83D/RESULT = {"SetOption106":"ON"}
20:28:59.135 CMD: SetOption107
20:28:59.141 MQT: stat/tasmota_40C83D/RESULT = {"SetOption107":"OFF"}
20:29:18.012 CMD: SetOption31
20:29:18.018 MQT: stat/tasmota_40C83D/RESULT = {"SetOption31":"OFF"}
```

2022-05-31 07:16 UTC, emontnemery commented
@maxberger Thanks for sharing the settings! Most lights which support RGB + CT have 5 groups of LEDs - red, green, blue, warm white, cold white, where each group is PWM controlled.

When such a light is in color mode, the Red + Green + Blue channels are enabled and the 2 white channels are disabled, and when it's in white mode only the cold and warm white channels are enabled.

Lights which support RGB + White only have 4 groups of LEDs - red, green, blue, white (cold, warm or in-between).
The purpose of `SetOption106 1` is to fake adjustable color temperature for RGBW lights by mixing in some color together with the white channel.

In your case, I suspect either your light only has 4 groups of LEDs, i.e. only 1 white channel, or the template you are using is wrong meaning one of the white groups is on another GPIO than what's configured by the template.

Can you explain in some more detail how your light behaves in Home Assistant and in the Tasmota UI with and without `SetOption106 1`?

2022-08-06 08:03 UTC, closed without merging