Update octoprint.markdown
home-assistant/home-assistant.github.io pull request #22925
Opened 2022-05-30 20:49 UTC by IGastel

added note to allow pop-up for connection to home assistant.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-05-30 20:49 UTC, homeassistant commented
Hi @IGastel, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#22925).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-05-31 13:37 UTC, frenck requested changes

2022-05-31 13:37 UTC, frenck commented on source/_integrations/octoprint.markdown
> +The Octoprint integration will attempt to register itself via the [application keys plugin](https://docs.octoprint.org/en/master/bundledplugins/appkeys.html). After submitting the configuration UI in
I think this makes more sense as part of the first sentence (which would incorporate it more into the existing text, instead of putting an in-line note at the end).

2022-06-08 10:52 UTC, IGastel commented on source/_integrations/octoprint.markdown
> +The Octoprint integration will attempt to register itself via the [application keys plugin](https://docs.octoprint.org/en/master/bundledplugins/appkeys.html). After submitting the configuration UI in
agree. thi sis my first time using github. so bear with me. i am still learning how to do this.

2022-06-09 13:39 UTC, frenck commented on source/_integrations/octoprint.markdown
> +For the integration to work, please check that the plugin Discovery is enabled. note: make sure to enable pop-ups in the settings -> printer notifications menu.
```suggestion
For the integration to work, please check that in Octoprint, the plugin Discovery is enabled and in the settings -> printer notifications menu pop-ups are enabled.
```

2022-06-09 13:46 UTC, frenck approved these changes
Thanks, @IGastel 👍

2022-06-09 13:46 UTC, merged