Update stale google calendar OAuth instructions
home-assistant/home-assistant.github.io pull request #22980
Opened 2022-06-04 04:55 UTC by allenporter

## Proposed change

Update incorrect google calender oauth instructions based on discussion #70241

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-06-29 11:14 UTC, frenck requested changes
@allenporter There is a merge conflict, could you take a look? 👍

2022-07-05 11:57 UTC, dannytsang commented
@allenporter looks good. Very minor comments and it covers https://github.com/home-assistant/home-assistant.io/pull/23270 as well. Thank you for updating it.

2022-07-09 16:03 UTC, frenck commented on source/_integrations/google.markdown
> +If you have an error with your credentails you can delete them in the [Application Credentials](/integrations/application_credentials/) user interface.
```suggestion
If you have an error with your credentials you can delete them in the [Application Credentials](/integrations/application_credentials/) user interface.
```

2022-07-09 16:03 UTC, frenck commented on source/_integrations/google.markdown
> +1.  You will then be automatically taken to the *Scopes* page. You do not need to add any scopes here so click **Save and Continue** to move to the *Test users* page. You will need to add the Gmail a
```suggestion
1.  You will then be automatically taken to the *Scopes* page. You do not need to add any scopes here so click **Save and Continue** to move to the *Test users* page. You will need to add the Gmail address you will be using with this integration as a test user before you will be allowed to use the API. Once you have added your email address under *Test users* click **Save and Continue** which will take you to the *Summary* page. (you do not need to do anything here).
```

2022-07-09 16:12 UTC, frenck approved these changes
Thanks, @allenporter 👍

2022-07-09 16:12 UTC, merged

2022-07-09 18:50 UTC, rhino53150 commented
"Generate Client ID and Client Secret" instructions are not correct. I just stepped through the process twice and step 11 states "You will then be automatically taken to the Scopes page. You do not need to add any scopes here so click Save and Continue to move to the Test users page." There is an "Optional Info" page after the "Scopes" page and then "Summary"


![2022-07-09 13_49_59-Window](https://user-images.githubusercontent.com/70902965/178119101-a1112964-44c0-4ae2-aca9-d9c4bde70104.png)

2022-07-09 18:53 UTC, allenporter commented
Can you send an edit with what makes sense to you?

2022-07-09 21:52 UTC, rhino53150 commented
> Can you send an edit with what makes sense to you?

11. You will then be automatically taken to the Scopes page. You do not need to add any scopes here so click Save and Continue to move to the Optional info page. You do not need to add anything to the Optional info page so click Save and Continue which will take you to the Summary page. Click Back to Dashboard.

2022-07-10 02:24 UTC, allenporter commented
> > Can you send an edit with what makes sense to you?
> 
> 11. You will then be automatically taken to the Scopes page. You do not need to add any scopes here so click Save and Continue to move to the Optional info page. You do not need to add anything to the Optional info page so click Save and Continue which will take you to the Summary page. Click Back to Dashboard.

I meant send an actual edit PR e.g. https://community.home-assistant.io/t/editing-the-documentation-and-creating-a-pull-request-on-github/9573

Thank you for your contributions!