document verify_ssl for IMAP/SMTP (#22901)
home-assistant/home-assistant.github.io pull request #22995
Opened 2022-06-05 04:34 UTC by Djelibeybi

## Type of change

Add documentation for new LIFX functionality: HEV cleaning cycle support.

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/73060
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-06-09 03:08 UTC, micolous requested changes
Generally looks good, the automation examples are helpful. :)

Unfortunately, I can't press "approve" here because otherwise GitHub won't mark my comments as "requested changes"...

2022-06-09 03:08 UTC, micolous commented on source/_integrations/lifx.markdown
> +Home Assistant will indicate whehther a LIFX Clean cycle is active via an extra state attribute for LIFX Clean bulbs and
`s/whehther/whether/` (spelling error)

2022-06-09 03:08 UTC, micolous commented on source/_integrations/lifx.markdown
> +Home Assistant will indicate whehther a LIFX Clean cycle is active via an extra state attribute for LIFX Clean bulbs and
> via an extra state attribute for LIFX Clean bulbs

Can you describe the extra state attribute here?

Also, this should be broken up into two sentences or paragraphs, because there are two distinct concepts described here (retrieving HEV state and setting HEV state).

2022-06-09 03:08 UTC, micolous commented on source/_integrations/lifx.markdown
> +For example, here's how to start a 1-hour HEV cycle from an automation:
Use [active voice](https://developers.google.com/tech-writing/one/active-voice):

```
For example, to start a 1 hour HEV cycle from an automation:

To stop a HEV cycle from an automation:
```

2022-06-09 03:08 UTC, micolous commented on source/_integrations/lifx.markdown
> +| `duration` | Duration (in seconds) for the cleaning cycle. Will use the default of 7200 seconds (2 hours) if not specified.
Use [active voice](https://developers.google.com/tech-writing/one/active-voice):

```
Duration (in seconds) of the HEV cycle. Defaults to 2 hours (7200 seconds).
```

2022-06-21 05:58 UTC, micolous approved these changes
Looks good, thanks!

2022-06-22 22:51 UTC, frenck commented
Closing this PR as the parent PR has been closed.

2022-06-22 22:51 UTC, closed without merging

2022-06-22 22:52 UTC, Djelibeybi commented
> Closing this PR as the parent PR has been closed.

Thanks. Sorry I didn't think to do it myself.

2022-06-22 22:53 UTC, frenck commented
> Thanks. Sorry I didn't think to do it myself.

Don't worry about it 👍