Adjust filtering to make includes stronger than excludes
home-assistant/home-assistant.github.io pull request #23223
Opened 2022-06-28 01:27 UTC by bdraco

## Proposed change

Adjust entity filters to make includes stronger than excludes

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/74080
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-06-28 08:11 UTC, emontnemery requested changes, later dismissed

2022-06-28 08:11 UTC, emontnemery commented on source/_includes/common-tasks/filters.md
> +1. No includes or excludes - all entities
Please be more explicit, maybe:
```suggestion
1. No includes or excludes - all entities included
```

2022-06-28 08:11 UTC, emontnemery commented on source/_includes/common-tasks/filters.md
> +      - If entity is included, accept
Let's consistently use the words "include" and "exclude" and not mix it up with "accept" and "reject.

2022-06-28 08:11 UTC, emontnemery commented on source/_includes/common-tasks/filters.md
> +      - If entity included and excluded, the entity exclude is ignored
This is very unclear, please rephrase it.

2022-06-28 08:11 UTC, emontnemery commented on source/_includes/common-tasks/filters.md
> +      - If entity is included, accept
Let's try to be more explicit, this refers to the entity being named directly, as opposed to being included via a domain or glob?

2022-06-28 08:11 UTC, emontnemery commented on source/_includes/common-tasks/filters.md
> +      - If entity is excluded, reject
If this is an ordered list, rewrite to:
> - Otherwise, if entity ...

2022-06-28 08:11 UTC, emontnemery commented on source/_includes/common-tasks/filters.md
>     - Neither include or exclude specifies domains or glob patterns
What if *both* include and exclude has domains and globs?

2022-06-28 14:47 UTC, bdraco commented on source/_includes/common-tasks/filters.md
> +5. Domain and/or glob excludes and no domain and/or glob includes:
```suggestion
5. Domain and/or glob excludes:
```

2022-06-28 14:48 UTC, bdraco commented on source/_includes/common-tasks/filters.md
> +4. Domain and/or glob includes:
```suggestion
4. Domain and/or glob includes (may also have excludes):
```

2022-06-28 14:48 UTC, bdraco commented on source/_includes/common-tasks/filters.md
> +5. Domain and/or glob excludes:
```suggestion
5. Domain and/or glob excludes (no domain and/or glob includes):
```

2022-06-29 09:59 UTC, frenck approved these changes
Thanks, @bdraco 👍

2022-06-29 09:59 UTC, merged