Document `int` and `boolean` template filters
home-assistant/home-assistant.github.io pull request #23221
Opened 2022-06-27 19:14 UTC by pyos

## Proposed change

Documentation for home-assistant/core#74068. I've also added `int` despite it being a built-in Jinja filter since `float` is also mentioned and this seems fair.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#74068

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-06-28 08:30 UTC, emontnemery requested changes

2022-06-28 08:30 UTC, emontnemery commented on source/_docs/configuration/templating.markdown
> +- `boolean(value, default)` function converts the value to either `true` or `false`. The following values are considered to be `true`: `true` (a `bool`), `"true"` (a string, case-insensitive), `"yes"
Please break up these lines (it won't show in the rendered html, but makes editing and reviewing simpler).

Let's rephrase to make it clear these are all case-insensitive strings, maybe:
> either of the strings `"true"`, `"yes"`, `"on"`, `"enable"`, `"1"` (case-insensitive)

Let's be more explicit about what returns `False`, instead of just this:
> Their opposites are `false`: `false`, `"false"`, `"no"`, `"off"`, `"disable"`, `"0"`, `0`, and `0.0`.

2022-06-28 17:21 UTC, pyos commented on source/_docs/configuration/templating.markdown
> +- `boolean(value, default)` function converts the value to either `true` or `false`. The following values are considered to be `true`: `true` (a `bool`), `"true"` (a string, case-insensitive), `"yes"
I tried to reword this, hopefully the new text makes it more clear that these values and *only* these values are `false`? I've also mentioned the intended use of parsing binary_sensor states.

2022-06-29 10:30 UTC, emontnemery approved these changes
Thanks, @pyos 👍

2022-06-29 10:33 UTC, merged