Update doorbird.markdown
home-assistant/home-assistant.github.io pull request #23602
Opened 2022-08-01 12:17 UTC by rosscullen

## Proposed change

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

Additional tweaks to make easier to understand. Automation examples. Addition of Doorbird Web Portal use for easier configuration.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-08-02 07:18 UTC, frenck requested changes
Please avoid the use of bare URLs, additionally, please make sure the build passes. Thanks! 👍 

../Frenck

2022-08-02 07:18 UTC, frenck commented on source/_integrations/doorbird.markdown
> +Once events have been registered on the DoorBird device, they must be attached to a schedule using the official DoorBird app on Android or iOS or the web portal at https://webadmin.doorbird.com. Curr
Please do not use bare URLs.

2022-08-02 07:18 UTC, frenck commented on source/_integrations/doorbird.markdown
> +It is recommended to set up a new & dedicated account on your Doorbird App/web portal for use with Home Assistant. The instructions in this documentation refer specifically to the Doorbird IOS/Androi
Please do not use bare URLs

2022-08-02 12:24 UTC, rosscullen reviewed
Minor changes to doorbird Spelling (DoorBird)

2022-08-04 12:19 UTC, rosscullen reviewed
minor spelling changes to docs

2022-08-29 01:43 UTC, bdraco commented on source/_integrations/doorbird.markdown
> +Note: Remember to complete the schedule assignment steps above for each event type that you registered. If you are configuring HTTP Call(s) schedules for registered RFID tags, please note you will ha
```suggestion
Note: Remember to complete the schedule assignment steps above for each event type you registered. If you are configuring HTTP Call(s) schedules for registered RFID tags, please note that you will have to enable/configure the schedule for each RFID tag.
```

2022-08-29 01:43 UTC, bdraco commented on source/_integrations/doorbird.markdown
> +Once events have been registered on the DoorBird device, they must be attached to a schedule using the official DoorBird app on Android or iOS or the [DoorBird - WebAdmin](https://webadmin.doorbird.c
```suggestion
Once events have been registered on the DoorBird device, they must be attached to a schedule using the official DoorBird app on Android or iOS or the [DoorBird - WebAdmin](https://webadmin.doorbird.com) portal. Currently, there are schedules available for doorbell, motion, relay, and RFID events (on supported DoorBird devices). Essentially, you can enable an HTTP(S) call from your DoorBird device to the Home Assistant DoorBird API by configuring an action/event (by enabling a schedule).
```

2022-08-29 01:44 UTC, bdraco commented on source/_integrations/doorbird.markdown
> +The URLs on the event will be based on the configuration used to connect to your DoorBird device. Ability to connect from outside your network will depend on your configuration.
```suggestion
The URLs on the event will be based on the configuration used to connect to your DoorBird device. The ability to connect from outside your network will depend on your configuration.
```

2022-08-29 01:44 UTC, bdraco commented on source/_integrations/doorbird.markdown
> +Each event will include live image and video URLs for the DoorBird device that triggered the event. These URLs can be found on the event data and can be useful in automation actions. For example, you
```suggestion
Each event will include live image and video URLs for the DoorBird device that triggered the event. These URLs can be found on the event data and are helpful in automation actions. For example, you could use `html5_viewer_url` on a notification to be linked directly to the live view of the device that triggered the automation.
```

2022-08-29 01:45 UTC, bdraco commented on source/_integrations/doorbird.markdown
> +It is recommended to set up a new & dedicated account on your DoorBird App/web portal for use with Home Assistant. The instructions in this documentation refer specifically to the DoorBird IOS/Androi
```suggestion
It is recommended to set up a new & dedicated account on your DoorBird App/web portal for use with Home Assistant. The instructions in this document refer specifically to the DoorBird IOS/Android app. Still, most actions can also be performed using the web-based [DoorBird - WebAdmin](https://webadmin.doorbird.com) portal and logging in on your DoorBird admin account.
```

2022-08-29 01:47 UTC, bdraco requested changes
Looks good.

Please see small comments above.

2022-08-29 17:55 UTC, frenck commented
@rosscullen You 👍 and resolved all the above review comments by bdraco; however, it seems like you have not pushed any changes onto this PR. Did something go wrong?

../Frenck

2022-10-19 19:32 UTC, frenck approved these changes
I've taken the liberty to apply the changes to the PR (so this PR can move forward).

Thanks @rosscullen 👍 

../Frenck

2022-10-19 19:50 UTC, merged