Documentation for a new integration for air-Q devices (air quality sensors)
home-assistant/home-assistant.github.io pull request #23809
Opened 2022-08-18 17:35 UTC by Sibgatulin

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/76999
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/3597
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-08-18 17:54 UTC, klaasnicolaas commented
Please rebase your branch to the `next` branch, because currently there are unrelated commits from the `current` branch in your PR.

2022-08-19 13:38 UTC, Sibgatulin commented
Thanks for the quick review @klaasnicolaas! Sorry, my bad. 
Since this PR effectively contributes a single commit, I cherry-picked it on top of `next`, and force-pushed. I hope it does the trick.

2022-10-26 08:40 UTC, ChristianHeimke submitted a review, later dismissed

2022-11-09 10:39 UTC, frenck commented on source/_integrations/airq.markdown
> +ha_release: '2022.09'
```suggestion
ha_release: '2022.12'
```

2022-11-09 10:41 UTC, frenck requested changes

2022-11-09 10:41 UTC, frenck commented on source/_integrations/airq.markdown
> +This platform allows to integrate the sensors, provided by your [Air-Q](https://www.air-q.com/) device, into Home Assistant.
```suggestion
This integration allows integrating the sensors, provided by your [Air-Q](https://www.air-q.com/) device, into Home Assistant.
```

2022-11-09 10:41 UTC, frenck commented on source/_integrations/airq.markdown
> +For this integration to communicate with the device, both must be connected to the same WiFi network.
```suggestion
During the configuration, the user is prompted for the IP address of the device or the first 5 characters of the serial number, as well as the device password.

For this integration to communicate with the device, both must be connected to the same Wi-Fi network.
```

2022-11-09 10:41 UTC, frenck commented on source/_integrations/airq.markdown
> +[^voc]: Volatile organic compounds
These don't work for our website/documentation.

2022-11-09 12:51 UTC, Sibgatulin commented
Thanks for the review, @frenck. I fixed the issues (+ extended the sensor list, as it grew during the parent PR development)

2022-11-09 13:05 UTC, frenck approved these changes
Thanks, @Sibgatulin 👍

2022-11-09 13:05 UTC, merged

2022-11-09 14:02 UTC, Sibgatulin commented
Thanks for the prompt merge! :rocket: