Update docs for updated config flow
home-assistant/home-assistant.github.io pull request #23831
Opened 2022-08-21 04:23 UTC by ocalvo

## Proposed change

- Updated documentation to reflect new config flow.
- Added more samples

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/76733
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-08-22 18:04 UTC, MartinHjelmare commented
Please solve the merge.

2022-08-22 18:25 UTC, ocalvo commented
> Please solve the merge.

Done

2022-08-23 07:01 UTC, MartinHjelmare commented on source/_integrations/sms.markdown
>  ## Notes about the operation system
```suggestion
## Notes about the operating system
```

2022-08-23 07:05 UTC, MartinHjelmare approved these changes
Thanks!

2022-08-23 07:10 UTC, MartinHjelmare requested changes

2022-08-23 07:10 UTC, MartinHjelmare commented on source/_integrations/sms.markdown
> +      message: "{{ message }}"
Templates need to be inside `{% raw %}` tags.

2022-08-23 07:10 UTC, MartinHjelmare commented on source/_integrations/sms.markdown
> +```yaml
```suggestion

{% raw %}

```yaml
```

2022-08-23 07:10 UTC, MartinHjelmare commented on source/_integrations/sms.markdown
```suggestion

{% endraw %}

```

2022-08-23 07:10 UTC, MartinHjelmare commented on source/_integrations/sms.markdown
> +```yaml
```suggestion

{% raw %}

```yaml
```

2022-08-23 07:10 UTC, MartinHjelmare commented on source/_integrations/sms.markdown
```suggestion

{% endraw %}

```

2022-08-23 07:15 UTC, MartinHjelmare approved these changes

2022-08-23 07:15 UTC, merged

2022-08-23 08:36 UTC, frenck reviewed
Please address the comments in a new PR, thanks! @ocalvo

2022-08-23 08:36 UTC, frenck commented on source/_integrations/sms.markdown
> +      target: states(sensor.user1_phone_number)
This seems a bug? It looks like a template but isn't?

2022-08-23 08:36 UTC, frenck commented on source/_integrations/sms.markdown
> +      message: 'From: {{trigger.event.data.phone}}
Please use double quotes (as per our YAML styling guidelines)

2022-08-23 08:36 UTC, frenck commented on source/_integrations/sms.markdown
> +## Notes about the operating system
I think it is time to remove this note entirely

2022-08-23 08:36 UTC, frenck commented on source/_integrations/sms.markdown
> +      example: The light is on!
These are strings and should be enquoted to show the best practices (as per our YAML style guidelines)

2022-08-23 08:36 UTC, frenck commented on source/_integrations/sms.markdown
> +- id: 'forward_sms'
Please remove the listing and the unique ID, they are optional and by foot and pasting they quickly can lead to duplicate issues.

2022-08-23 08:36 UTC, frenck commented on source/_integrations/sms.markdown
> +  description: ''
Empty field, remove it

2022-08-23 08:36 UTC, frenck commented on source/_integrations/sms.markdown
> +  alias: Forward SMS
This is een string and thus needs to be enquoted

2022-08-23 08:36 UTC, frenck commented on source/_integrations/sms.markdown
> +  condition: []
Empty conditions, please remove it

2022-08-23 08:36 UTC, frenck commented on source/_integrations/sms.markdown
> +#### Putting it all together in `automations.yaml`
They don't have to be in automations .yaml, let's remove that from the tittle.

2022-08-23 08:36 UTC, frenck commented on source/_integrations/sms.markdown
> +      state: !secret user1_phone_number
Please avoid the use of secrets in examples.

2022-08-23 15:51 UTC, ocalvo commented
> Please address the comments in a new PR, thanks! @ocalvo

@frenck 
https://github.com/home-assistant/home-assistant.io/pull/23864