Add keymitt ble documentation
home-assistant/home-assistant.github.io pull request #23839
Opened 2022-08-21 22:07 UTC by spycle

## Proposed change
Documentation for new MicroBot Push integration (keymitt_ble)

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/76575
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/3585
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-08-22 15:02 UTC, frenck commented on source/_integrations/keymitt_ble.markdown
> +ha_release: ???
```suggestion
ha_release: 2022.8
```

2022-08-22 15:06 UTC, frenck requested changes

2022-08-22 15:06 UTC, frenck commented on source/_integrations/keymitt_ble.markdown
> +In order to use this integration, it is required to have working Bluetooth set up on the device running Home Assistant. A Naran/Keymitt hub is not required.
```suggestion
In order to use this integration, it is required to have working [Bluetooth](/integrations/blueooth) set up on the device running Home Assistant. A Naran/Keymitt hub is not required.
```

2022-08-22 15:06 UTC, frenck commented on source/_integrations/keymitt_ble.markdown
> +The device will need to be in pairing mode before adding to Home Assistant. To reset the MicroBot Push, turn it off then back on and immediately hold the push button while the LED is red. After appro
```suggestion
The device will need to be in pairing mode before adding to Home Assistant. To reset the MicroBot Push, turn it off, then back on, and immediately hold the push button while the LED is red. After approximately 5 seconds, the LED will flash rapidly, at which point release the button. The LED will blink blue if the pairing mode has been successfully activated.
```

2022-08-22 15:06 UTC, frenck commented on source/_integrations/keymitt_ble.markdown
> +If you have multiple devices, you will need to know the BTLE MAC address of your device to tell them apart.
```suggestion
If you have multiple devices, you will need to know the BTLE MAC address of your device to tell them apart.
```

2022-08-22 15:06 UTC, frenck commented on source/_integrations/keymitt_ble.markdown
> +Please note, devices cannot remain paired to the MicroBot app for this integration to function. They will be paired to Home Assistant exclusively.
```suggestion
Please note, that devices cannot remain paired to the MicroBot app for this integration to function. They will be paired to Home Assistant exclusively.
```

2022-08-22 15:06 UTC, frenck commented on source/_integrations/keymitt_ble.markdown
> +Please note: The push arm will extend or retract (dependant on the mode set) after the service call is invoked. The mode and depth will be demomstrated but not the duration. The setting is however st
```suggestion
Please note: The push arm will extend or retract (dependant on the mode set) after the service call is invoked. The mode and depth will be demonstrated, but not the duration. The setting is, however, stored and can be confirmed by manually operating the device.
```

2022-08-22 15:06 UTC, frenck commented on source/_integrations/keymitt_ble.markdown
> +| `entity_id`            | yes      | Entity ID of the MicroBot Push to calibrate.                                                  |
Isn't this an entity service? (Thus `entity_id` isn't required, one could target areas, devices or everything alternatively).

2022-09-07 15:50 UTC, bdraco commented on source/_integrations/keymitt_ble.markdown
> +ha_release: 2022.8
```suggestion
ha_release: "2022.10"
```

2022-09-26 15:36 UTC, frenck approved these changes

2022-09-26 15:37 UTC, merged