List Silabs and TI adapters above ConBee/RaspBee
home-assistant/home-assistant.github.io pull request #23895
Opened 2022-08-26 13:51 UTC by Hedda

## Proposed change

Change listing of Silicon Labs and Texas Instruments Zigbee adapters to the top of the Known working Zigbee radio modules so that they are listed before deCONZ (ConBee/RaspBee) Zigbee adapters, reasons being that both Silabs and TI adapters have many more available options on the market as well as being better supported in ZHA/zigpy than deCONZ (ConBee/RaspBee) Zigbee adapters.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-08-26 13:53 UTC, frenck requested changes
Lets just sort the list alphabetically.

2022-08-26 18:22 UTC, Hedda commented
> Lets just sort the list alphabetically.

That would make it even worse from the suggested compatibility point-of-view since Digi XBee is the least / poorest supported radio by ZHA/zigpy developers today.

It is my belief that many new ZHA end-users will just buy the first adapter that is listed at the very top, so it would be better to have Silicon Labs listed at the top since the upcoming Home Assistant SkyConnect USB Stick (and Home Assistant Yellow) will be based on Silicon Labs radios.

2022-08-26 18:33 UTC, frenck commented
It is a list of "Known working Zigbee radio modules".
The order should not matter. We should not make it a search game, lets's please sort the list alphabetically.

2022-08-26 18:43 UTC, puddly commented
The technical reasons for why some some adapters are better-supported than others don't belong in user documentation but this PR is correctly ordering them.  I don't want to encourage people to buy anything but TI, SiLabs, or a Conbee (in that order) and expect a smooth experience with ZHA.

Perhaps we can instead split this into two sections: "Recommended Adapters" and a less-prominent "Other Supported Adapters" (or something similar)?

2022-08-26 18:52 UTC, frenck commented
Yeah that is fine, but ordering all of these per recommendation will lead to discussions always. Making a first section on recommended adapters and a second one with "others" sounds perfectly fine. It also clearly communicates the recommendation (which currently is implicit)

2022-08-27 08:49 UTC, Hedda commented
> Perhaps we can instead split this into two sections: "Recommended Adapters" and a less-prominent "Other Supported Adapters" (or something similar)?

That is by the way almost exactly what Zigbee2MQTT official documentation does, as they have compatible adapters sorted in seperate lists for ”Recommended”, ”Not recommended”, and ”Experimental” while under those still grouping the adapters per chip radio type that they are based on, see -> https://www.zigbee2mqtt.io/guide/adapters/

2022-09-27 07:47 UTC, Hedda commented
OK I have now changed the PR as feedback, splitting lists if ZHA-supported adapters into two segments for which adapters/modules are recommended and which are not recommended for new purchase/buyers, which is a little more similar to how Zigbee2MQTT list their supported adapters -> https://www.zigbee2mqtt.io/information/supported_adapters.html

2022-10-10 13:46 UTC, Hedda commented
Closing in favor of https://github.com/home-assistant/home-assistant.io/pull/24493

2022-12-05 09:36 UTC, Hedda commented
Updated: Split ZHA Recommended Adapters from Other Supported Adapters into two sections, as per feedback from @puddly.

> The technical reasons for why some some adapters are better-supported than others don't belong in user documentation but this PR is correctly ordering them. I don't want to encourage people to buy anything but TI, SiLabs, or a Conbee (in that order) and expect a smooth experience with ZHA.
> 
> Perhaps we can instead split this into two sections: "Recommended Adapters" and a less-prominent "Other Supported Adapters" (or something similar)?

With this the "**_Recommended Zigbee radio adapters and modules_**" section with modern/newer hardware from Silicon Labs, Texas Instruments, and Dresden Elektronik, then an "**_Other support but not recommended Zigbee radio adapters or modules_**" section with legacy/older   hardware from Silicon Labs, Texas Instruments, and Dresden Elektronik, as well as Digi XBee and ZiGate.

2022-12-05 09:44 UTC, Hedda commented
Oh, removed clarifying explanations on why some are recommended and others are not as not quite sure if that is a too long text?

### Recommended Zigbee radio adapters and modules

These adapters/modules listed below are currently recommended because they use powerful radio chips, can handle a large Zigbee network, use later firmware still maintained by their manufacturer, and are well-supported in this Zigbee implementation.

### Other support but not recommended Zigbee radio adapters or modules

These other radio adapters/modules listed below are also supported but generally not recommended for a new purchase because reasons like they by today's standards have either obsolete/underpowered chips, can not handle a large Zigbee network, use older firmware no longer maintained by their manufacturer, or just currently do not have many developers + testers that keep actively developing the support for them with this Zigbee implementation.

2023-01-16 17:58 UTC, frenck commented on source/_integrations/zha.markdown
> +### Other support but not recommended Zigbee radio adapters or modules
```suggestion
### Other supported but not recommended Zigbee radio adapters or modules
```

2023-01-16 17:58 UTC, frenck commented on source/_integrations/zha.markdown
> +
```suggestion

```

2023-01-16 18:05 UTC, frenck approved these changes
Thanks, @Hedda 👍 

../Frenck

2023-01-16 18:05 UTC, merged