adding example for old foscam and similar no-brand
home-assistant/home-assistant.github.io pull request #23917
Opened 2022-08-28 00:22 UTC by yarix

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-08-28 00:22 UTC, homeassistant commented
Hi @yarix, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#23917).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-08-28 09:23 UTC, klaasnicolaas requested changes

2022-08-28 09:23 UTC, klaasnicolaas commented on source/_integrations/mjpeg.markdown
> +  - MJPEG URL: `http://192.168.1.13:8080/videostream.cgi` (add ?resultion=32 for 640x480 or ?resultion=32 for 320x240)
```suggestion
  - MJPEG URL: `http://IP:PORT/videostream.cgi` (add ?resultion=32 for 640x480 or ?resultion=32 for 320x240)
```

2022-08-28 09:23 UTC, klaasnicolaas commented on source/_integrations/mjpeg.markdown
> +  - Still Image URL: `http://192.168.1.13:8080/snapshot.cgi`
```suggestion
  - Still Image URL: `http://IP:PORT/snapshot.cgi`
```

2022-09-06 16:46 UTC, klaasnicolaas approved these changes
Thnx for the PR! 🎖️

2022-09-06 16:46 UTC, merged