Fix details block in Bravia TV
home-assistant/home-assistant.github.io pull request #23966
Opened 2022-08-31 23:54 UTC by Drafteed

## Proposed change

https://rc.home-assistant.io/integrations/braviatv/

It looks like the details block doesn't support code blocks.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-08-31 23:57 UTC, Drafteed commented
Please patch RC.

2022-09-02 11:42 UTC, klaasnicolaas commented
What exactly is the purpose of this PR? I see a long list of options in the current documentation and you don't link to a pull request in the core integration?

2022-09-02 11:46 UTC, Drafteed commented
@klaasnicolaas This is a bug fix introduced in my previous PR https://github.com/home-assistant/home-assistant.io/pull/23889.
At the moment it is only merged into `next`, not `current`.

2022-09-02 12:18 UTC, klaasnicolaas commented
Thank you for explaining. I had to dig a bit to check if your core PR was in the release (it wasn't in the list), but should be fine and your docs PR is now tagged for the release 😉

2022-09-02 12:23 UTC, klaasnicolaas commented
![image](https://user-images.githubusercontent.com/20448157/188141525-3eef5348-78f7-4e40-b172-9b3118b4b025.png)

Maybe it's better not to make this in a list form but just string with commas?

2022-09-02 13:40 UTC, Drafteed commented
> but should be fine and your docs PR is now tagged for the release 😉

Thank you! 👍

> Maybe it's better not to make this in a list form but just string with commas?

I thought about it, but it seemed to me that the list is more convenient and readable. Although one line is also good.

<img src="https://user-images.githubusercontent.com/11841379/188157887-23a1beee-f378-42b2-b28f-d867351d1447.png" width="500">

<img src="https://user-images.githubusercontent.com/11841379/188157980-defbe6d8-c29a-4b95-a942-945c55c72538.png" width="500">

2022-09-02 14:19 UTC, bieniu submitted a review, later dismissed

2022-09-06 18:34 UTC, frenck requested changes

2022-09-06 18:34 UTC, frenck commented on source/_integrations/braviatv.markdown
>  {% details "Some commonly used commands" %}
The change needed here, is adding a new-line before and after the liquid syntax (`{% ... %}`, allowing the parser to switch context between liquid and Markdown.

2022-09-06 18:43 UTC, frenck requested changes

2022-09-06 18:43 UTC, frenck commented on source/_integrations/braviatv.markdown
>  Up, Down, Left, Right, Confirm, Return, Home, Exit, Rewind, Forward, ActionMenu, SyncMenu, Num0, Num1, Num2, Num3, Num4, Num5, Num6, Num7, Num8, Num9
Please restore the previous list. A alphabetically list is easier to scan than single line with tons of options.

2022-09-06 18:58 UTC, frenck approved these changes
Thanks, @Drafteed 👍

2022-09-06 18:59 UTC, merged