Doc fix: Remove outdated information
home-assistant/home-assistant.github.io pull request #24014
Opened 2022-09-05 21:37 UTC by AlfredJKwack

## Proposed change
This resolves a small documentation issue. The documentation referred to another page for further information though that page itself no longer had anything relevant. It also led the user into more complex patterns than necessary (ie. the notion of the singular `automation:` as opposed to the prvailing labelled automatoins).

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-09-05 21:37 UTC, homeassistant commented
Hi @AlfredJKwack, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#24014).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-09-08 22:03 UTC, frenck requested changes

2022-09-08 22:03 UTC, frenck commented on source/_integrations/workday.markdown
> +automation workday_heating:
This is not a generic approach. Yes, that works, but it is using an advanced configuration method most people should not need.

Lets revert this change.

2022-09-08 22:03 UTC, frenck commented on source/_integrations/workday.markdown
>  </div>
This warning is indeed incorrect, and highly depending on your setup. Let just remove it to avoid confusion.

2022-09-11 12:33 UTC, AlfredJKwack commented
Well now I'm the one who's definitly confused.

2022-09-12 21:31 UTC, klaasnicolaas approved these changes

2022-09-13 12:05 UTC, frenck approved these changes
Thanks, @AlfredJKwack 👍

2022-09-13 12:05 UTC, merged