Update daikin.markdown
home-assistant/home-assistant.github.io pull request #24062
Opened 2022-09-09 06:23 UTC by emufan

## Proposed change

Clarify/correct the description of the source of two entities. According to https://github.com/home-assistant/core/issues/72545

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/core/issues/72545

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-09-09 06:24 UTC, cremor commented on source/_integrations/daikin.markdown
> +- The 'Today's total energy consumption' and 'Estimated power consumption' sensor is updated every time 100 Wh are consumed by all different operating modes summed together. This values are the value
Typo in "onle".

2022-09-09 07:25 UTC, emufan commented on source/_integrations/daikin.markdown
> +- The 'Today's total energy consumption' and 'Estimated power consumption' sensor is updated every time 100 Wh are consumed by all different operating modes summed together. This values are the value
Fixed.

2022-09-09 14:51 UTC, mlemainque requested changes

2022-09-09 14:51 UTC, mlemainque commented on source/_integrations/daikin.markdown
> +- The 'Today's total energy consumption' and 'Estimated power consumption' sensor is updated every time 100 Wh are consumed by all different operating modes summed together. This values are the value
Typo in "This", should be "These"

2022-09-09 16:14 UTC, emufan commented on source/_integrations/daikin.markdown
> +- The 'Today's total energy consumption' and 'Estimated power consumption' sensor is updated every time 100 Wh are consumed by all different operating modes summed together. This values are the value
Fixed.

2022-09-09 18:02 UTC, mlemainque approved these changes

2022-09-15 13:52 UTC, frenck approved these changes
Thanks, @emufan 👍

2022-09-15 13:52 UTC, merged