Added Whirlpool/Maytag Washer/Dryer
home-assistant/home-assistant.github.io pull request #24107
Opened 2022-09-12 11:49 UTC by mkmer

## Proposed change

Addition of Whirlpool/Maytag laundry machines to the integration. Washers and Dryers will now create 2 sensors each - one for machine state and one for cycle time remaining.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/77336
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-09-16 18:22 UTC, frenck requested changes

2022-09-16 18:22 UTC, frenck commented on source/_integrations/whirlpool.markdown
> +description: Instructions on how to integrate Whirlpool/Maytag appliances with Home Assistant.
Shouldn't Maytag be added as a supported brand instead?

2022-09-16 18:22 UTC, frenck commented on source/_integrations/whirlpool.markdown
> +The `whirlpool` sensor platform integrates Whirlpool/Maytag Washer and Dryer systems into Home Assitant, allowing views of the machine state and time remaining as sensors for each device.
Looks like something went wrong here with the headers....

2022-09-16 18:28 UTC, mkmer commented on source/_integrations/whirlpool.markdown
> +description: Instructions on how to integrate Whirlpool/Maytag appliances with Home Assistant.
Probably - amateur mistake :)

2022-09-19 14:05 UTC, mkmer commented on source/_integrations/whirlpool.markdown
> +description: Instructions on how to integrate Whirlpool/Maytag appliances with Home Assistant.
Looking this over a bit, I'm not sure "supported brands" is right.  In this case, whirlpool and maytag appliances are all connected to a single user account - the integration pulls all appliances into HA (well for now laundry and climate, but soon ovens and microwaves).
For now, I've removed Maytag from the update, but feedback one how to proceed is appreciated.

2022-09-19 14:07 UTC, frenck commented on source/_integrations/whirlpool.markdown
> +description: Instructions on how to integrate Whirlpool/Maytag appliances with Home Assistant.
> Looking this over a bit, I'm not sure "supported brands" is right. In this case, whirlpool and maytag appliances are all connected to a single user account - the integration pulls all appliances into HA (well for now laundry and climate, but soon ovens and microwaves).

This is exactly what it is for. If the user has a Maytag device, it can still find the integration.

2022-09-19 14:15 UTC, mkmer commented on source/_integrations/whirlpool.markdown
> +description: Instructions on how to integrate Whirlpool/Maytag appliances with Home Assistant.
So if the user has 2 Whirlpool appliances and 1 Maytag on a user account, there will only be on integration loaded and all 3 appliances would show up with different device/entity groups. 
Still correct?  (sorry for my limited understanding on this)

2022-09-19 14:32 UTC, frenck commented on source/_integrations/whirlpool.markdown
> +description: Instructions on how to integrate Whirlpool/Maytag appliances with Home Assistant.
Supported brands are only for findability.

2023-01-17 13:52 UTC, frenck approved these changes

2023-01-17 13:52 UTC, merged