Update zha.markdown ZHA quirks handling
home-assistant/home-assistant.github.io pull request #24118
Opened 2022-09-13 08:21 UTC by Hedda

## Proposed change

Update zha.markdown ZHA quirks handling.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-11-20 07:09 UTC, Hedda commented
Not stale

2022-11-20 16:50 UTC, frenck commented
Are you planning on moving it forward then?

../Frenck

2023-01-09 08:29 UTC, Hedda commented
> Are you planning on moving it forward then?
> 
> ../Frenck

How can and should I move it forward? Is not the missing review the only blocker? Is not reviewers required to move it forward?

2023-01-16 18:38 UTC, frenck requested changes

2023-01-16 18:38 UTC, frenck commented on source/_integrations/zha.markdown
> +Home Assistant's ZHA integration already supports most standard device types out-of-the-box as long as they follow the official Zigbee specifications, but for devices that manufacturers have not prop
```suggestion
Home Assistant's ZHA integration already supports most standard device types out-of-the-box as long as they follow the official Zigbee specifications, but for devices that manufacturers have not properly not fully Zigbee compatible, the ZHA integration has implemented a library called "[ZHA Device Handlers (also known as "zha-quirk")](https://github.com/zigpy/zha-device-handlers)" that handle and resolve compliance issues via custom conversion/translation of Zigbee parameters (clusters and attributes) for specific devices which do not conform with the Zigbee standards.
```

2023-01-16 18:38 UTC, frenck commented on source/_integrations/zha.markdown
> +The few devices that will for example not join/pair properly or while joined/paired do not present all attributes in the ZHA integration likely deviate from the Zigbee specifications set by the [CSA
```suggestion
The few devices that will, for example, not join/pair properly or, while joined/paired, do not present all attributes in the ZHA integration likely deviate from the Zigbee specifications set by the [CSA (Connectivity Standards Alliance)](https://csa-iot.org/all-solutions/zigbee/). These devices may therefore require the creation of a bug report by a device owner, supplying debug logs. The device owner may need to actively assist in troubleshooting by providing the information developers need to create custom ZHA Device Handlers.
```

2023-01-16 18:38 UTC, frenck commented on source/_integrations/zha.markdown
> +Such a custom "ZHA Device Handler" are Python script that internally is also referred to as a "quirk" because they fix or workaround "quirks" in devices, like deviations from the standard specificati
This whole chapter is repeating all the above, in different wording, and can thus be removed without losing information.

```suggestion
```

2023-01-16 18:38 UTC, frenck commented on source/_integrations/zha.markdown
> +For reference, the ZHA integration's custom quirks implementations for zigpy implemented as ZHA Device Handlers for Home Assistant are a similar concept to that of other Zigbee gateway/hub implementa
Non of this is relevant to an end-user.

```suggestion
```

2023-02-03 17:17 UTC, frenck approved these changes
Thanks, @Hedda 👍 

../Frenck

2023-02-03 17:17 UTC, merged