Add documentation for initial nibe implementation
home-assistant/home-assistant.github.io pull request #24141
Opened 2022-09-16 13:16 UTC by elupus

## Proposed change

Add documentation for nibe heat pump integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/78542
- Link to parent pull request in the Brands repository: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-09-26 15:26 UTC, frenck requested changes

2022-09-26 15:26 UTC, frenck commented on source/_integrations/nibe_heatpump.markdown
> +The `nibe_heatpump` integration allows you to control and monitor [Nibe Heat Pumps](https://www.nibe.eu/en-eu/products/heat-pumps) in Home Assistant.
```suggestion
The Nibe Heat Pump integration allows you to control and monitor [Nibe Heat Pumps](https://www.nibe.eu/en-eu/products/heat-pumps) in Home Assistant.
```

2022-09-26 15:26 UTC, frenck commented on source/_integrations/nibe_heatpump.markdown
> +- Serial Modbus for Nibe Modbus 40 (not yet implemented)
I would suggest changing this to only list what is supported.

2022-09-26 15:26 UTC, frenck commented on source/_integrations/nibe_heatpump.markdown
> +The heat pump exposes a RS485 interface for communication with extensions. This can be used to speak to the pump by emulating the Nibe MODBUS40 accessory.
```suggestion
The heat pump exposes an RS485 interface for communication with extensions. This can be used to speak to the pump by emulating the Nibe MODBUS40 accessory.
```

2022-09-26 15:26 UTC, frenck commented on source/_integrations/nibe_heatpump.markdown
> +Since the pump will go into an error state if the accessory is not responding, a dedicated hardware running a gateway software is the preferable choice.
```suggestion
Since the pump will go into an error state if the accessory is not responding, dedicated hardware running a gateway software is the preferable choice.
```

2022-09-26 15:26 UTC, frenck commented on source/_integrations/nibe_heatpump.markdown
> +This can be built using a Raspberry Pi with a RS485 hat, a Arduino with RS485 support or an ESP32 with RS485 converters.
```suggestion
This can be built using a Raspberry Pi with an RS485 hat, an Arduino with RS485 support or an ESP32 with RS485 converters.
```

2022-09-26 15:52 UTC, elupus commented on source/_integrations/nibe_heatpump.markdown
> +To communicate with the pump there are a few different connection methods available depending on hardware.
```suggestion
To communicate with the pump there are a few different connection methods available depending on hardware. At the moment the following methods are supported.
```

2022-09-26 15:53 UTC, elupus commented on source/_integrations/nibe_heatpump.markdown
> +- Serial Modbus for Nibe Modbus 40 (not yet implemented)
```suggestion
```

2022-09-26 16:07 UTC, elupus commented on source/_integrations/nibe_heatpump.markdown
> +  - water_heater
These two are yet to be reviewed/merged. I will remove these from this pull should they not make the release.

2022-09-30 10:48 UTC, elupus commented on source/_integrations/nibe_heatpump.markdown
> +  - water_heater
```suggestion
```

2022-10-03 11:56 UTC, frenck commented on source/_integrations/nibe_heatpump.markdown
> +ha_release: 2022.10
```suggestion
ha_release: '2022.10'
```

2022-10-03 11:59 UTC, frenck approved these changes
Thanks for updating @elupus 👍

2022-10-03 11:59 UTC, merged