Habuild patch 1
home-assistant/home-assistant.github.io pull request #24223
Opened 2022-09-23 04:44 UTC by habuild

## Proposed change

Added example Markdown and variable notification and related image.
- [X] Added example and image to the current documentation (`current` branch).

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-09-26 12:39 UTC, frenck requested changes

2022-09-26 12:39 UTC, frenck commented on source/_integrations/persistent_notification.markdown
> +![persistant_notification_msgCapture](https://user-images.githubusercontent.com/36288425/191888076-0895e15a-2cc2-4e31-9755-c758135b108e.PNG)
Images should be included in the repository.

2022-09-26 12:39 UTC, frenck commented on source/_integrations/persistent_notification.markdown
> +### Example Markdown variable notification
What is this example adding? As in, I'm not sure what you are trying to show?
Please update the PR description to elaborate / motivate the change.

2022-09-26 12:39 UTC, frenck commented on source/_integrations/persistent_notification.markdown
> +  message: >-
The example title says this is a Markdown example, but it contains mainly HTML. Please remove the HTML.

2022-09-26 12:39 UTC, frenck commented on source/_integrations/persistent_notification.markdown
> +  notification_id: os-agent            ## <<< this can be whatever 12343232
```suggestion
  notification_id: os-agent
```

2022-09-26 12:39 UTC, frenck commented on source/_integrations/persistent_notification.markdown
> +  title: "There is an update in Os-Agent!"
Why is the OS Agent used in this example? Is there a specific reason?

2022-09-26 15:22 UTC, habuild commented on source/_integrations/persistent_notification.markdown
> +  message: >-
https://daringfireball.net/projects/markdown/syntax#p

That is the link from the page we are discussing.
I couldn't get a lot of the markdown to work. Whereas the html would. The rest is my ignorance I should have listed it as a html example. I could do both, although not sure html is allowed(or promoted).

Try this in dev tools, I am not great at markdown, this doesn't seem to me correct though.
```
service: persistent_notification.create
data:
  notification_id: frenck
  message: >-
    Agent "{{ states('sensor.os_agent_version_github') }}" is
    >available

    ----------

    1.  Bird
    2.  McHale
    3.  Parish

    1.  Bird

    2.  McHale

    3.  Parish


    * Bird

    *  Magic
    *  Bird

    * Magic

    ---------

    <ul>
    <li>Bird</li>
    <li>Magic</li>
    </ul>

    ***    

    * * *

    - - -

    ------------------------------------


    [Latest](https://github.com/home-assistant/os-agent/releases/latest)\n


    **wget https://github.com/home-assistant/os-agent/releases/download/** "{{
    states('sensor.os_agent_version_github') }}"/os-agent_"{{
    states('sensor.os_agent_version_github') }}"_linux_aarch64.deb\n
    sudo dpkg \n -i os-agent_"{{ states('sensor.os_agent_version_github')
    }}"_linux_aarch64.deb
  title:  Hi Frenck tyvm


```

2022-09-26 15:32 UTC, habuild commented on source/_integrations/persistent_notification.markdown
> +  title: "There is an update in Os-Agent!"
No specific reason other than, that is what I was making for myself at the time, when I was following the docs.

2022-09-27 03:42 UTC, habuild commented on source/_integrations/persistent_notification.markdown
> +![persistant_notification_msgCapture](https://user-images.githubusercontent.com/36288425/191888076-0895e15a-2cc2-4e31-9755-c758135b108e.PNG)
noted. moved.

2022-09-27 03:43 UTC, habuild commented on source/_integrations/persistent_notification.markdown
> +### Example Markdown variable notification
updated proposed changes

2022-09-29 09:39 UTC, closed without merging