New function/test/filter is_nominal for templating
home-assistant/home-assistant.github.io pull request #24360
Opened 2022-10-03 22:06 UTC by ehendrix23

Add new function/test/filter is_nominal to check if entity is known and does not have state unknown or unavailable.

## Proposed change

Adding new templating function is_nominal for checking if an entity is known and not unavailable.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/79550
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-10-25 11:45 UTC, ThomDietrich commented on source/_docs/configuration/templating.markdown
> +{% if ['sensor.train_departure_time', 'sensor.train_arrival_time']|is_nominal() %}
```suggestion
{% if ['sensor.train_departure_time', 'sensor.train_arrival_time'] | is_nominal() %}
```

2022-11-02 22:54 UTC, ThomDietrich commented on source/_docs/configuration/templating.markdown
> +- `is_nominal('sensor.my_sensor')` will test if the given entity exist and is not unknown or unavailable. A list of entities can be provided instead of a string. Can be used as a filter. `nominal` is
After the short discussion in the core PR: Would it make sense to explicitly mention that for a list of entities an OR logic is applied!? Cheers

2022-11-03 21:37 UTC, ThomDietrich commented
Lgtm

2022-11-03 21:38 UTC, ThomDietrich submitted a review, later dismissed
Lgtm

2023-03-14 09:20 UTC, frenck requested changes

2023-03-14 09:20 UTC, frenck commented on source/_docs/configuration/templating.markdown
> +{% if sensor.train_departure_time is has_value %}
what is `sensor.trains_departure_time`? as in, where does this variable come from?

2023-03-14 13:59 UTC, ehendrix23 commented on source/_docs/configuration/templating.markdown
> +{% if sensor.train_departure_time is has_value %}
Sorry, missed states. there. Fixed.

2023-03-14 14:32 UTC, frenck requested changes

2023-03-14 14:32 UTC, frenck commented on source/_docs/configuration/templating.markdown
> +{% if states.sensor.train_departure_time is has_value %}
`states` should not be used in this context, as per our own documentation:

![image](https://user-images.githubusercontent.com/195327/225034110-220a29ae-4d35-4395-9ebc-c94572e1854a.png)

2023-03-28 15:04 UTC, frenck approved these changes
Thanks, @ehendrix23 👍 

../Frenck

2023-03-28 15:05 UTC, merged