Update to new py-sucks library that is being used
home-assistant/home-assistant.github.io pull request #24375
Opened 2022-10-04 21:00 UTC by dmares01

This still points to the old documentation for the original _sucks_ library that has been archived. No developers are currently supporting original _sucks_ library and it is significantly out of date. The py-sucks library isn't seeing much active development but at least is not archived

## Proposed change
Updating the documentation for the py-sucks vs sucks library that the ecovacs component used to use

## Type of change
Documentation Update

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
N/A

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-10-04 21:51 UTC, mib1185 requested changes
Hi @dmares01
Many thanks for pointing this out 👍
Only one small comment from my side

2022-10-04 21:51 UTC, mib1185 commented on source/_integrations/ecovacs.markdown
> +Note: For some countries, you will need to set `continent` to `ww` (meaning worldwide.) There is unfortunately no way to know the correct settings other than guessing and checking. See the [py-sucks
```suggestion
Note: For some countries, you will need to set `continent` to `ww` (meaning worldwide.) There is unfortunately no way to know the correct settings other than guessing and checking. See the [py-sucks library protocol documentation](https://github.com/mib1185/py-sucks/blob/master/protocol.md) for more information about what has been figured out about the Ecovacs servers.
```
Please keep the full path

2022-10-25 03:24 UTC, dmares01 commented
@mib1185 I committed those changes! Thank you for pointing it out

2022-10-25 06:58 UTC, mib1185 approved these changes

2022-10-25 06:59 UTC, merged