Note SoyeaLink support in Huawei LTE docs
home-assistant/home-assistant.github.io pull request #24450
Opened 2022-10-08 07:43 UTC by scop

## Proposed change

The Huawei LTE integration works out of the box with at least some SoyeaLink devices, note that in the docs.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-10-08 08:07 UTC, homeassistant commented
It seems that this PR is targeted against an incorrect branch since it has a parent PR on one of our codebases. Documentation that needs to be updated for an upcoming release should target the `next` branch. Please change the target branch of this PR to `next` and rebase if needed.

2022-10-08 08:08 UTC, scop commented
https://github.com/home-assistant/core/pull/79853 is related/similary, but not a blocking parent in the sense that this one should be rebased on `next`.

2022-10-10 15:17 UTC, frenck requested changes

2022-10-10 15:17 UTC, frenck commented on source/_integrations/huawei_lte.markdown
> +and [SoyeaLink](https://www.soyea-tech.com/) LTE devices.
Shouldn't this be added as a supported brand instead?

2022-11-06 09:39 UTC, closed without merging