Add instructions to get the flap_id
home-assistant/home-assistant.github.io pull request #24475
Opened 2022-10-09 17:07 UTC by Heisenberg2980

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-10-09 17:40 UTC, klaasnicolaas requested changes, later dismissed
Tables quickly become difficult to read, especially on a mobile view. I think you better put this information as a separate chapter above the services.

![image](https://user-images.githubusercontent.com/20448157/194771382-bba4271a-f816-42d0-a420-b0e48968d5ff.png)

2022-10-10 12:56 UTC, frenck requested changes

2022-10-10 12:56 UTC, frenck commented on source/_integrations/surepetcare.markdown
> +`flap_id` can be found following this instructions: Log into [surepetcare.io](https://surepetcare.io/), open the side bar, click your flap and the flap_id will be at the end of the URL (i.e. https://
```suggestion
The `flap_id` can be found following these instructions:

- Log into [surepetcare.io](https://surepetcare.io/).
- Open the sidebar and click your flap.
- The `flap_id` will be at the end of the URL (i.e., `https://surepetcare.io/control/device/FLAP-ID`)
```

2022-10-10 14:24 UTC, frenck approved these changes
Thanks, @Heisenberg2980 👍

2022-10-10 14:24 UTC, merged