Adding NVM information
home-assistant/home-assistant.github.io pull request #24474
Opened 2022-10-09 16:29 UTC by raidboy

Adding proposed text to document new NVM backup/restore and migration of Z-Wave controller. Community forum articles have varying information, for example the wrong information that one needs to manually run conversion. So it would be good for the official documentation to start documenting the correct steps. I verified the steps migrating from ZST10-700 to ZST10(-500)

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-10-09 18:19 UTC, MartinHjelmare requested changes

2022-10-09 18:19 UTC, MartinHjelmare commented on source/_integrations/zwave_js.markdown
> +Z-Wave supports backup and restore of Z-Wave controller "Non Volatile Memory" (NVM) via "Control Panel" -> "Advanced Actions". Backup will save an NVM file into "Store" -> "backups" -> "nvm", where i
Looks like you're describing functionality of Z-Wave JS UI. The integration doesn't yet support any NVM features, so we shouldn't document that here yet.

2022-10-10 12:49 UTC, frenck commented
Thanks for being willing to contribute @raidboy, but Martin is right, this is not functionality in Home Assistant. Most people (as we recommend) don't use Z-Wave JS UI by the Core add-on.
This documentation will be highly confusing for those users.

Therefore, going to friendly decline this PR.

../Frenck

2022-10-10 12:49 UTC, closed without merging

2022-10-10 14:26 UTC, raidboy commented
@frenck i am happy to find a place and propose this text to the z-wave js ui documentation instead, but i am confused about your statement of recommending to not using "z-wave js UI by the core add-on". Could you please explain.

Aka: i have HAOS running on RPI4, and in the web UI, on the left, there is "Z-Wave JS". When i click on that, i think the HA web server connects to the "Z-Wave JS UI" which i then see on the right. And that is where all the NVM functionality is.

a) is that understanding correct ?
b) what of that is not recommended ? 

I get that user who do not use HAOS may not have this integrating link on the web, but to perform any of the advanced functions of Z-Wave JS that are not mapped via API into HA directly,  they would still need to use that Z-Wave JS UI directly, right ?

2022-10-10 14:30 UTC, frenck commented
> Aka: i have HAOS running on RPI4, and in the web UI, on the left, there is "Z-Wave JS". When i click on that, i think the HA web server connects to the "Z-Wave JS UI" which i then see on the right. And that is where all the NVM functionality is.

That is a third-party add-on from the community add-on store. That is not the add-on that the Home Assistant Project recommends. The recommended add-on is provided by the Core add-on repository and automatically installed and set up when setting up the Z-Wave JS integration.

2022-10-10 15:03 UTC, raidboy commented
@frenck  Still confused:

I remember how ZWave JS was not the official integration last year when i installed it, and all the documentation was very explicit to mention that. But not, it seems that the previous "official" zwave integration was demoted to legacy, and Z-Wave JS is the current official, reommended integration:

https://www.home-assistant.io/integrations/zwave_js/

This integration allows you to control a Z-Wave network via the [Z-Wave JS](https://zwave-js.github.io/node-zwave-js/#/) driver. This is our recommended Z-Wave integration for Home Assistant. If you’re migrating from the legacy zwave, see [our migration instructions](https://www.home-assistant.io/integrations/zwave_js/#migrating-from-previous-z-wave-implementations).

In fact, it seems to be the only available integration in current HAOS, its the only z-wave integration i see in the list. 

Back in 2021, in HAOS, i could see two lists of integrations, official ones and community. I can not see this distinction anymore.

2022-10-10 15:05 UTC, frenck commented
> I remember how ZWave JS was not the official integration last year when i installed it

It always has been, as a matter of fact, the community version of the add-on was created after the core version.

In any case, this PR described functionality not part of Home Assistant and declined for that reason right now.

2022-10-10 15:13 UTC, raidboy commented
Just to be  able tto compare: How would i install the "core version" vs. the "community version" ? And if there are two different versions, why is that not mentioned at all in the official home assistant documentation ? Sorry, i am still confused, because i do not see two versions. And the official home assistnt documentation seems to be referring to the version which AFAIK always has that Z-Wave JS UI.  I may be wrong, but i would like to understand.

2022-10-10 15:23 UTC, frenck commented
>  And if there are two different versions, why is that not mentioned at all in the official home assistant documentation ?

It is mentioned. Many are even put into the FAQ the answer your questions as well: <https://www.home-assistant.io/integrations/zwave_js#frequently-asked-questions>