Add additional known working iBeacon devices (#24284)
home-assistant/home-assistant.github.io pull request #24551
Opened 2022-10-13 22:08 UTC by Djelibeybi

## Proposed change

Adds a section that lists the available sensor entities for the LIFX integration, i.e. the HEV cycle status sensor, infrared brightness sensor and proposed wifi signal strength (RSSI) sensor. 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/79973
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-10-14 08:13 UTC, frenck commented on source/_integrations/lifx.markdown
> +| WiFi signal strength (RSSI)   | All        | No
```suggestion
| Wi-Fi signal strength (RSSI)   | All        | No
```

2022-10-14 08:13 UTC, frenck approved these changes, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2022-10-24 13:39 UTC, bdraco requested changes
Please resolve conflicts

2022-10-26 14:14 UTC, bdraco requested changes
It looks like there are unrelated changes in this PR

2022-10-26 20:20 UTC, Djelibeybi commented
It's the same content, I just rearranged things a bit to make the theme section a little easier to read.

2022-10-26 20:59 UTC, bdraco commented on source/_integrations/lifx.markdown
> +Home Assistant provides a collection of predefined themes for LIFX multizone lights, each of which is designed to mimic the theme of the same name from the LIFX smartphone app.
```suggestion
Home Assistant provides a collection of predefined themes for LIFX multizone lights, each designed to mimic the theme of the same name from the LIFX smartphone app.
```

2022-10-26 20:59 UTC, bdraco approved these changes

2022-10-26 22:06 UTC, merged