add docs for formula_one integration
home-assistant/home-assistant.github.io pull request #24564
Opened 2022-10-14 13:01 UTC by y34hbuddy

## Proposed change

New core integration: formula_one

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [X] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: TBD
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/3786
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-10-14 13:17 UTC, frenck requested changes

2022-10-14 13:17 UTC, frenck commented on source/_integrations/formula_one.markdown
> +The `formula_one` integration offers integration with the [Ergast](http://ergast.com/mrd/) Formula 1 API to provide details about the current season's Drivers Championship, Constructors Championship,
```suggestion
The Formula 1 integration offers integration with the [Ergast](http://ergast.com/mrd/) Formula 1 API to provide details about the current season's Drivers Championship, Constructors Championship, and Race schedule.
```

2022-10-14 13:17 UTC, frenck commented on source/_integrations/formula_one.markdown
> +- `f1_next_race`: a sensor representing the next Race of the season
What are these codes in those code blocks? Entity IDs? Or?

2022-10-14 13:21 UTC, y34hbuddy commented on source/_integrations/formula_one.markdown
> +- `f1_next_race`: a sensor representing the next Race of the season
Indeed - these are sensor.* entity IDs. Is there a more-preferred way of documenting these?

2022-10-14 13:23 UTC, frenck commented on source/_integrations/formula_one.markdown
> +- `f1_next_race`: a sensor representing the next Race of the season
Aah ok, it wasn't really clear those where entity IDs (as those start with e.g., `sensor.`). Anyways, it is not preferred to write entity IDs, as those are not guaranteed to be assigned.

Instead, just describe them in human language.

2022-10-14 13:30 UTC, y34hbuddy commented on source/_integrations/formula_one.markdown
> +- `f1_next_race`: a sensor representing the next Race of the season
Understood - will do!

2022-10-14 14:28 UTC, hmmbob commented on source/_integrations/formula_one.markdown
> +The Formula 1 integration offers integration with the [Ergast](http://ergast.com/mrd/) Formula 1 API to provide details about the current season's Drivers Championship, Constructors Championship, and
```suggestion
The Formula 1 integration offers integration with the [Ergast](https://ergast.com/mrd/) Formula 1 API to provide details about the current season's Drivers Championship, Constructors Championship, and Race schedule.
```

2022-10-16 14:06 UTC, y34hbuddy commented
Apologies for re-requesting review... that was meant for another PR  :)

2022-10-18 13:12 UTC, frenck requested changes

2022-10-18 13:12 UTC, frenck commented on source/_integrations/formula_one.markdown
> +### Available Resources
```suggestion
## Available resources
```

2022-10-18 13:12 UTC, frenck commented on source/_integrations/formula_one.markdown
> +- A sensor representing the next Race of the season
```suggestion
The list of currently available resources:

- Sensors representing each position in the Drivers Championship
- Sensors representing each driver in the Drivers Championship
- Sensors representing each position in the Constructors Championship
- Sensors representing each constructor in the Constructors Championship
- Sensors representing each race of the season
- Sensor representing the next race of the season
```

2024-05-27 07:46 UTC, frenck commented
Closing PR as the parent PR has been closed.

2024-05-27 07:46 UTC, closed without merging