Camera annotations
home-assistant/home-assistant.github.io pull request #24588
Opened 2022-10-16 19:51 UTC by eddiewebb

## Proposed change

This adds the instructions for camera `annotation` from [/core#80429 home-assistant/core/#80429](https://github.com/home-assistant/core/pull/80429)

PR from core/#80429 adds ability to pass arbitrary template ( title, timestamp, etc) to be place on image.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.
- [x] I was instructed to open corresponding docs change for pending Core PR [core/#80429
=](https://github.com/home-assistant/core/pull/80429)

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/80429
- Link to parent pull request in the Brands repository:  NA
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-10-17 14:11 UTC, frenck requested changes
This PR contains unrelated commits/changes. It seems like it was made from the wrong base branch. Please git rebase your changes/commits on the latest upstream `next` branch to clean it up.

Thanks! 👍 

../Frenck

2022-10-17 23:37 UTC, eddiewebb commented
doh, thanks @frenck  

I pushed change against `next`, single line now :) 

I'll un-assign myself if these pending tests pass.

2022-10-18 13:05 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2022-10-28 11:39 UTC, frenck commented
Closing PR as the parent PR has been closed.

2022-10-28 11:39 UTC, closed without merging