Add new abbreviations
home-assistant/home-assistant.github.io pull request #24723
Opened 2022-10-28 13:39 UTC by bieniu

## Proposed change

Update MQTT `update` platform documentation.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/81131
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-10-28 14:57 UTC, jbouwh reviewed
A few comments

2022-10-28 14:57 UTC, jbouwh commented on source/_integrations/update.mqtt.markdown
> +  description: Summary of the release notes or changelog. This is not suitable for long changelogs but merely suitable for a short excerpt update description of max 255 characters.
```suggestion
  description: Summary of the release notes or changelog. This is suitable a brief update description of max 255 characters.
```

2022-10-28 14:57 UTC, jbouwh commented on source/_integrations/update.mqtt.markdown
> +  description: The MQTT topic subscribed to receive state updates. The state update may be either JSON or a simple string with `installed_version` value. When a JSON payload is detected, the state va
```suggestion
  description: The MQTT topic subscribed to receive state updates. The state update may be either JSON or a simple string with `installed_version` value. When a JSON payload is detected, the state value of the JSON payload should supply the `installed_version` and can optional supply:  `latest_version`, `title`, `release_summary`, `release_url` or an `entity_picture` URL.
```

2022-10-28 14:57 UTC, jbouwh commented on source/_integrations/update.mqtt.markdown
> +  description: Title of the software. This helps to differentiate between the device or entity name versus the title of the software installed.
```suggestion
  description: Title of the software, or firmware update. This helps to differentiate between the device or entity name versus the title of the software installed.
```

2022-10-28 14:57 UTC, jbouwh commented on source/_integrations/update.mqtt.markdown
> +  description: "Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract the installed version value. Alternatively `value_template` can be used to r
```suggestion
  description: "Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract the `installed_version` state value or to render to a valid JSON payload on from the payload received on `state_topic`."
```

2022-10-28 15:02 UTC, jbouwh requested changes
`latest_version_topic` is not required anymore.

2022-10-28 16:58 UTC, jbouwh submitted a review, later dismissed
Looks good to me!

2022-10-28 16:59 UTC, jbouwh commented
@bieniu You need to fix the errors before we can merge

2022-10-28 21:07 UTC, bieniu commented
Any hint what's wrong with line 162?

2022-10-29 12:38 UTC, jbouwh approved these changes, later dismissed
Looks good to me!
Thnx @bieniu !

2022-10-31 09:42 UTC, frenck approved these changes
Thanks, @bieniu 👍

2022-10-31 09:42 UTC, merged