Add config flow to `pushbullet`
home-assistant/home-assistant.github.io pull request #24773
Opened 2022-11-01 13:22 UTC by engrbm87

## Proposed change

Add config flow to `pushbullet`.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/74240
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-11-02 15:13 UTC, MartinHjelmare commented on source/_integrations/pushbullet.markdown
> +### Sensors
```suggestion
## Sensors
```

2022-11-03 11:35 UTC, frenck commented on source/_integrations/pushbullet.markdown
>  ### Setup
```suggestion
## Prerequisites
```

2022-11-03 11:37 UTC, frenck requested changes

2022-11-03 11:37 UTC, frenck commented on source/_integrations/pushbullet.markdown
> +- `Type`: The type of the push.
This is not code and should thus not be code fenced.

```suggestion
- Application name: The application sending the push.
- Body: The notification message body.
- Notification ID: The ID of the notification.
- Tag: The notification tag (if the application sending supports it).
- Package name: The name of the sender’s package.
- Receiver Email: The email of the push’s target.
- Sender Email: The email of the sender.
- Sender device ID: The ID of the sender’s device.
- Title: The title of the push.
- Type: The type of the push.
```

2022-11-03 11:37 UTC, frenck commented on source/_integrations/pushbullet.markdown
> +`Body` and `Title` are enabled by default. The rest can be enabled from the UI.
```suggestion
"Body" and "Title" are enabled by default. The rest can be enabled from the UI.
```

2022-11-03 11:37 UTC, frenck commented on source/_integrations/pushbullet.markdown
>  The `pushbullet` notification platform sends messages to [Pushbullet](https://www.pushbullet.com/), a free service to send information between your phones, browsers, and friends. The free tier is [li
```suggestion
The Pushbullet notification platform sends messages to [Pushbullet](https://www.pushbullet.com/), a free service to send information between your phones, browsers, and friends. The free tier is [limited](https://docs.pushbullet.com/#push-limit) to 500 pushes per month.
```

2022-11-03 11:44 UTC, frenck approved these changes
Thanks, @engrbm87 👍

2022-11-03 11:44 UTC, merged