Added sensors descriptions to Oral-B integration
home-assistant/home-assistant.github.io pull request #24824
Opened 2022-11-05 01:18 UTC by dannytsang

## Proposed change
Added a list of sensors and descriptions for Oral-B integration. I don't have pressure working on my toothbrush so I have not added it to this change.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #24803

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-11-05 13:42 UTC, klaasnicolaas requested changes, later dismissed

2022-11-05 13:42 UTC, klaasnicolaas commented on source/_integrations/oralb.markdown
> -
There should be a blank line 😉

2022-11-05 15:22 UTC, dannytsang commented on source/_integrations/oralb.markdown
> -
Re-added the line in the latest push.

2022-11-09 11:05 UTC, frenck approved these changes
Thanks, @dannytsang 👍

2022-11-09 11:05 UTC, merged