Fix hvac mode keys
home-assistant/home-assistant.github.io pull request #24866
Opened 2022-11-08 21:55 UTC by avishorp

The keys used in the configuration under modbus -> climate -> hvac_mode_register have changed.

## Proposed change

Change the names of the keys used for the configuration of climate mode in Modbus integration. The existing keys use the word "off" which gets parsed as a boolean False instead of a string.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-11-09 10:07 UTC, janiversen requested changes

2022-11-09 10:07 UTC, janiversen commented on source/_integrations/modbus.markdown
> +            state_dry: 4
I think state_off is missing ?

2022-11-09 10:30 UTC, frenck requested changes
This PR is targeting the wrong branch. It targets the `current` branch, but it depends on a change in the Home Assistant codebase that is depending a future release of Home Assistant. This PR should thus target the `next` branch.

Please adjust the target branch and git rebase if needed.

2022-11-09 10:30 UTC, frenck commented on source/_integrations/modbus.markdown
> +            state_dry: 4
This is a breaking change. I've left a comment on the parent PR to avoid this.

2022-11-15 21:21 UTC, frenck commented on source/_integrations/modbus.markdown
> +            state_dry: 4
Nevermind, was explained in the parent PR.

2022-11-16 12:22 UTC, frenck commented on source/_integrations/modbus.markdown
> +            state_dry: 4
```suggestion
            state_dry: 4
            state_off: 5
```

2022-11-16 12:51 UTC, janiversen submitted a review, later dismissed
LGTM. apart from the wrong branch, please rebase.

2022-11-16 20:08 UTC, frenck commented
Changed base.

2022-11-16 20:08 UTC, frenck approved these changes
Thanks, @avishorp 👍

2022-11-16 20:08 UTC, merged