Vallox switch platform
home-assistant/home-assistant.github.io pull request #24963
Opened 2022-11-16 12:47 UTC by yozik04

## Proposed change

Added description about new **switch** platform.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/75857
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-11-16 13:14 UTC, frenck requested changes

2022-11-16 13:14 UTC, frenck commented on source/_integrations/vallox.markdown
> +The **switch** platform allows to lock heat recovery bypass.
```suggestion
The **sensor** platform exposes a number of relevant metrics like fan speed, various air temperatures, and humidity.

The **switch** platform allows locking heat recovery bypass.
```

2022-11-16 13:36 UTC, yozik04 commented
Thank you @frenck

2022-11-16 13:39 UTC, yozik04 commented
@frenck I do not see how to get rid of "Changes requested". I have applied these.

2022-11-16 14:56 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2022-11-18 08:46 UTC, yozik04 commented
@frenck Maybe you can do the final review of the parent PR: https://github.com/home-assistant/core/pull/75857
It sits there for quite a long time already.

2022-11-18 09:17 UTC, merged