Add `date` platform docs
home-assistant/home-assistant.github.io pull request #24986
Opened 2022-11-18 03:14 UTC by raman325

## Proposed change
Adds docs for the new date platform.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/81948
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-11-18 16:04 UTC, frenck requested changes

2022-11-18 16:04 UTC, frenck commented on source/_integrations/date.markdown
> +Date entities are created automatically by integrations that support them.
```suggestion
Date entities cannot be implemented manually, but can be provided by other integrations. If you are looking for a way to create a similar entity, please take a look at the [Date/Time helper](/integrations/input_datetime).
```

2022-11-18 16:15 UTC, frenck approved these changes, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2022-12-07 10:51 UTC, spacegaier commented on source/_integrations/date.markdown
> +Date entities cannot be implemented manually, but can be provided by other integrations. If you are looking for a way to create a similar entity, please take a look at the [Date/Time helper](/integra
```suggestion
Date entities cannot be created manually, but can be provided by other integrations. If you are looking for a way to create a similar entity, please take a look at the [Date/Time helper](/integrations/input_datetime).
```

I think the meaning here is that users cannot manually create those entities and have to use helpers instead. Then I'd say "create" is clearer here.

2023-04-30 18:35 UTC, frenck commented on source/_integrations/date.markdown
> +ha_release: '2022.12'
```suggestion
ha_release: '2023.6'
```

2023-04-30 18:35 UTC, frenck approved these changes

2023-04-30 18:45 UTC, merged