Add `text` platform docs
home-assistant/home-assistant.github.io pull request #24989
Opened 2022-11-18 04:53 UTC by raman325

## Proposed change

Adds docs for the new text platform.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/79454
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-11-18 16:00 UTC, frenck requested changes

2022-11-18 16:00 UTC, frenck commented on source/_integrations/text.markdown
> +Text entities are created automatically by integrations that support them.
This makes it a little more clear that you can't just spawn these manually, while also providing an alternative that can be used manually.

```suggestion
Text entities cannot be implemented manually, but can be provided by other integrations. If you are looking for a way to create a text entity, please take a look at the [Text helper](/integrations/input_text).
```

2022-11-18 16:09 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2022-11-24 19:02 UTC, frenck requested changes
Not sure why I missed this earlier 🙈 

../Frenck

2022-11-24 19:02 UTC, frenck commented on source/_integrations/text.markdown
> +### Service `siren.turn_on`
```suggestion
### Service `text.set_value`
```

2022-11-24 19:02 UTC, frenck commented on source/_integrations/text.markdown
> +Turn the siren on.
```suggestion
Set the textual value of the text entity.
```

2022-11-24 19:27 UTC, raman325 commented
> Not sure why I missed this earlier 🙈
> 
> ../Frenck

doh me too

2022-11-24 19:29 UTC, frenck approved these changes
Thanks, @raman325 👍

2022-11-24 19:32 UTC, merged