Adding vallox number platform documentation
home-assistant/home-assistant.github.io pull request #24993
Opened 2022-11-18 08:40 UTC by yozik04

## Proposed change

Adding documentation about number platform.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

I am not sure if I should notify about service deprecation in the documentation or just remove the whole block.

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/75858
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-11-18 08:51 UTC, frenck requested changes

2022-11-18 08:51 UTC, frenck commented on source/_integrations/vallox.markdown
> +### Service `vallox.set_profile_fan_speed_away` (deprecated)
Please remove deprecated services from the documentation.

2022-11-18 09:00 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2022-11-18 09:25 UTC, frenck submitted a review, later dismissed

2022-11-22 09:59 UTC, yozik04 commented
I am sorry @frenck. But main PR review showed that I need to move some number platform entities to fan platform. Fan platform related PR will deprecate mentioned services. Not current one.

2022-11-22 11:48 UTC, MartinHjelmare approved these changes

2022-11-23 18:31 UTC, frenck approved these changes
Thanks, @yozik04 👍

2022-11-23 18:31 UTC, merged