Document proposed alt_text properties.
home-assistant/home-assistant.github.io pull request #24990
Opened 2022-11-18 06:45 UTC by progman32

## Proposed change

Added `alt_text` property support to cards which feature images. Please see https://github.com/home-assistant/frontend/pull/14405

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/frontend/pull/14405
- Link to parent pull request in the Brands repository:  n/a
- This PR fixes or closes issue: fixes #14178 in frontend

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-11-18 11:37 UTC, frenck requested changes, later dismissed
There are unrelated commit in this PR, probably caused by this PR being branched from the `current` branch.

Please git rebase your commit onto the `next` branch to clean this PR up.

Thanks 👍 

../Frenck

2022-11-18 20:08 UTC, progman32 commented
Shoot, yes, silly of me. Fixing.

2022-11-30 14:27 UTC, steverep requested changes

2022-11-30 14:27 UTC, steverep commented on source/dashboards/header-footer.markdown
> -{% endconfiguration %}
Need to add this line back.  Probably why the checks are failing

2022-11-30 14:27 UTC, steverep commented on source/_dashboards/picture-entity.markdown
> +alt_text:
Let's get rid of this and create the alt text per my comment on the frontend PR.

2022-11-30 14:27 UTC, steverep commented on source/_dashboards/picture.markdown
> +  description: "Image alternate text. This is useful for users of assistive technology."
```suggestion
  description: "Alternative text for the image. This is useful for users of assistive technology."
```

2022-11-30 14:27 UTC, steverep commented on source/dashboards/header-footer.markdown
> +  description: "Image alternate text. This is useful for users of assistive technology."
```suggestion
  description: "Alternative text for the image. This is useful for users of assistive technology."
```

2022-12-23 19:33 UTC, progman32 commented on source/dashboards/header-footer.markdown
> -{% endconfiguration %}
That was.... silly of me :/

2022-12-24 06:26 UTC, steverep commented on source/dashboards/header-footer.markdown
> +alt_text:
Can we move this above the actions?  Makes more sense right after the image source.

2022-12-30 04:34 UTC, steverep approved these changes

2022-12-31 17:23 UTC, merged