Add note regarding expiration of Tuya IoT Platform trial period.
home-assistant/home-assistant.github.io pull request #25035
Opened 2022-11-24 03:06 UTC by creeve4

2022-11-24 07:39 UTC, frenck requested changes
I've noticed you've removed the PR template in this PR. Please restore it and fill it out.

Thanks! 👍 

../Frenck

2022-11-24 07:39 UTC, frenck commented on source/_integrations/tuya.markdown
> +**Note**: this account may have a trial period, which expires by default after 6 months and must be manually renewed. Once expired, all devices will be revoked and unavailable in Home Assistant. Rene
That isn't a prerequisite, this fits more into the troubleshooting section below.

2022-11-24 16:02 UTC, creeve4 commented
> I've noticed you've removed the PR template in this PR. Please restore it and fill it out.
> 
> Thanks! 👍
> 
> ../Frenck

My mistake. Where can I find the template (without creating a new PR)?

2023-01-17 12:15 UTC, frenck commented
> Where can I find the template (without creating a new PR)?

Just open up a new PR (without creating a new PR, just get into the dialog), and copy paste the template shown.

2023-03-17 12:05 UTC, frenck commented
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

2023-03-17 12:05 UTC, closed without merging