Add documentation about the HomeWizard identify feature
home-assistant/home-assistant.github.io pull request #25030
Opened 2022-11-23 12:53 UTC by DCSBL

## Proposed change

Add documentation about the HomeWizard identify feature, lets the device do 🚨 for a moment.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/82375
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-11-23 13:37 UTC, frenck requested changes
Tiny tweak, as "Indentify" isn't code.

2022-11-23 13:37 UTC, frenck commented on source/_integrations/homewizard.markdown
> +The `Identify` button can be pressed to let the status light blink for a few seconds.
```suggestion
The identify button can be pressed to let the status light blink for a few seconds.
```

2022-11-23 13:40 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2022-11-23 16:49 UTC, balloob commented on source/_integrations/homewizard.markdown
> + </div>
Notes are kinda big and annoying. Let’s just make it a single line. 
```suggestion
The identify button can be pressed to let the status light blink for a few seconds. This feature is not supported by all devices.
```

2022-11-23 16:49 UTC, balloob submitted a review, later dismissed

2022-11-23 18:05 UTC, DCSBL commented on source/_integrations/homewizard.markdown
> + </div>
Sure 👍. But I still think we should tell which devices are supported to prevent users spamming support and/or the forum with "when/where is this available?" This is also enforced by `python-homewizard-energy`, so support is only added through a PR in core.

```suggestion
The identify button can be pressed to let the status light blink for a few seconds.
This feature is currently only available for the Wifi Energy Socket with firmware version `3.01` or later.
```

2022-11-23 18:06 UTC, frenck approved these changes, later dismissed

2022-11-28 07:54 UTC, frenck approved these changes

2022-11-28 07:54 UTC, merged