Add required scope in Slack docs
home-assistant/home-assistant.github.io pull request #25195
Opened 2022-12-08 11:29 UTC by tkdrob

## Proposed change

Add required scope in Slack docs

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes # https://github.com/home-assistant/core/issues/83523

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-12-08 14:32 UTC, bachya commented on source/_integrations/slack.markdown
> +3. In the Scopes section, add the `chat:write` and `dnd:read` scopes, `Send messages as user`. If you get a `missing_scope` error when trying to send a message, check these permissions.
```suggestion
3. In the Scopes section, add the `chat:write` and `dnd:read` scopes and select `Send messages as user`. Many errors can occur if these options are not set correctly.
```

2022-12-08 16:42 UTC, frenck commented
I don't think this PR fixed the reported issue. Documenting it is good, but the integration should handle this better. For example, it could stop retry-ing and raise an re-auth or maybe raise an repairs issue.

2022-12-08 16:43 UTC, frenck requested changes
Setting review status of this PR correctly.

2022-12-08 18:40 UTC, tkdrob commented
> I don't think this PR fixed the reported issue. Documenting it is good, but the integration should handle this better. For example, it could stop retry-ing and raise an re-auth or maybe raise an repairs issue.

Let me be clear that this is not currently doing any OAuth 2 schemes like what Google/Nest has. The solution should just be for the user to add the scope in their app. Maybe I'm missing something?

2022-12-12 11:43 UTC, frenck commented
> Let me be clear that this is not currently doing any OAuth 2 schemes like what Google/Nest has.

Understood 👍 
Thanks for clarifying!

../Frenck

2022-12-12 11:43 UTC, frenck approved these changes

2022-12-12 11:43 UTC, merged