add ecobee ventilator documentation
home-assistant/home-assistant.github.io pull request #25215
Opened 2022-12-09 16:17 UTC by marcolivierarsenault

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/83645
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-12-12 11:04 UTC, frenck requested changes

2022-12-12 11:04 UTC, frenck commented on source/_integrations/ecobee.markdown
> +The ecobee thermostat supports the addition of an accessory. If you have a air exchanger (ventilator, hrv or erv) you can control it via the Ventilator entity.
```suggestion
The ecobee thermostat supports the addition of an accessory. If you have an air exchanger (ventilator, HRV, or ERV), you can control it via the Fan entity.
```

2022-12-12 11:04 UTC, frenck commented on source/_integrations/ecobee.markdown
> +The _state_ is the state of the ventilator. (on or off). It tells you if the ventilator is currently running.
```suggestion
The _state_ is the state of the fan. (on or off). It tells you if the ventilator is currently running.
```

2022-12-12 11:04 UTC, frenck commented on source/_integrations/ecobee.markdown
> +The _state_ is the state of the ventilator. (on or off). It tells you if the ventilator is currently running.
Don't get me wrong, this feels a bit obvious. Should we drop this line?

2022-12-12 11:04 UTC, frenck commented on source/_integrations/ecobee.markdown
> +4. After authorizing the app with ecobee, return to Home Assistant and click **Submit**. If the authorization was successful, a configuration entry will be created and your thermostats, ventilators a
We call them fans in Home Assistant.

```suggestion
4. After authorizing the app with ecobee, return to Home Assistant and click **Submit**. If the authorization was successful, a configuration entry will be created and your thermostats, fans, and sensors will be available in Home Assistant.
```

2022-12-12 11:04 UTC, frenck commented on source/_integrations/ecobee.markdown
> +| `is_on` | Current status of the ventilator. The possible values are True or False.
`is_on` is not an attribute of an fan entity, but an property of the implementation of an fan entity. 

```suggestion
```

2022-12-12 11:04 UTC, frenck commented on source/_integrations/ecobee.markdown
> +| `ventilator_min_on_time_home` | The minimum amount of time (in minutes) that the ventilator will run per hour, when you are home. This is determined by the minimum ventilator runtime setting which
```suggestion
| `ventilator_min_on_time_home` | The minimum amount of time (in minutes) that the ventilator will run per hour when you are home. This is determined by the minimum ventilator runtime setting, which can be changed in the ecobee app or on the thermostat itself.
```

2022-12-12 11:04 UTC, frenck commented on source/_integrations/ecobee.markdown
> +| `ventilator_min_on_time_away` | The minimum amount of time (in minutes) that the ventilator will run per hour, when you are away. This is determined by the minimum ventilator runtime setting which
```suggestion
| `ventilator_min_on_time_away` | The minimum amount of time (in minutes) that the ventilator will run per hour when you are away. This is determined by the minimum ventilator runtime setting, which can be changed in the ecobee app or on the thermostat itself.
```

2022-12-12 11:04 UTC, frenck commented on source/_integrations/ecobee.markdown
> +### Service `ecobee.set_ventilator_min_on_time_home`
Should this be a `number` entity instead?

2022-12-12 11:04 UTC, frenck commented on source/_integrations/ecobee.markdown
> +### Service `ecobee.set_ventilator_min_on_time_away`
Shouldn't this be a `number` entity instead?

2022-12-12 14:12 UTC, marcolivierarsenault commented on source/_integrations/ecobee.markdown
> +4. After authorizing the app with ecobee, return to Home Assistant and click **Submit**. If the authorization was successful, a configuration entry will be created and your thermostats, ventilators a
@frenck Through the doc, I tried to separate fan from ventilator. 
I know Home assistant entity is a fan. But given the Ecobee device has:
- a Fan (for the furnace) which is included in the climate entity
- a Ventilator, (implemented from a fan entity) 

I think it makes the doc more clear to use ventilator. 

That being said, I have no strong feeling if you prefer to move to `fan`

2022-12-12 18:07 UTC, marcolivierarsenault commented on source/_integrations/ecobee.markdown
> +### Service `ecobee.set_ventilator_min_on_time_home`
done

2022-12-12 18:07 UTC, marcolivierarsenault commented on source/_integrations/ecobee.markdown
> +### Service `ecobee.set_ventilator_min_on_time_away`
done

2022-12-12 18:09 UTC, marcolivierarsenault commented
@frenck applied your comments except the fan/ventilator comments.

Let me know what you think

2023-02-20 09:47 UTC, frenck approved these changes
Thanks, @marcolivierarsenault 👍 

../Frenck

2023-02-20 09:48 UTC, merged