Add a callout to update RuuviTag firmware
home-assistant/home-assistant.github.io pull request #25331
Opened 2022-12-17 20:46 UTC by conallob

## Proposed change

Add a callout to update to the latest firmware (complete with link), if RuuviTags are not being discovered

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-12-19 11:29 UTC, frenck requested changes

2022-12-19 11:29 UTC, frenck commented on source/_integrations/ruuvitag_ble.markdown
> +**Callout:** If RuuviTags are not discovered, [update to the latest firmware](https://ruuvi.com/software-update/)
```suggestion
If your RuuviTags are not discovered, please make sure to update them to [the latest firmware](https://ruuvi.com/software-update/).
```

2022-12-19 13:06 UTC, conallob commented
Accepted the additional commit.

2022-12-27 20:00 UTC, frenck approved these changes
Thanks, @conallob 👍

2022-12-27 20:01 UTC, merged