adding new parameters as per PR on the code
home-assistant/home-assistant.github.io pull request #25403
Opened 2022-12-24 14:41 UTC by wasperen

## Proposed change

These changes describe how the additional parameters (unlocked through https://github.com/wasperen/hass-core/commit/d7825c31b4fb97d55964f488da2f9615867943ba) can be used.

Also made it clear that `client_id` is actually called "Client key" on the current version of the Mastadon UI.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/wasperen/hass-core/commit/d7825c31b4fb97d55964f488da2f9615867943ba

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-23 19:21 UTC, c0ffeeca7 requested changes

2023-03-23 19:21 UTC, c0ffeeca7 commented on source/_integrations/mastodon.markdown
> +integration currently only support sending notifications, so the API only has to be able to `write` to the
```suggestion
integration currently only supports sending notifications, so the API only has to be able to `write` to the
```

2023-03-23 19:21 UTC, c0ffeeca7 commented on source/_integrations/mastodon.markdown
> +Client key.
```suggestion
**Client key**.
```

2023-03-23 19:21 UTC, c0ffeeca7 commented on source/_integrations/mastodon.markdown
> +
Do you think you could maybe also specify what to put for **Application website** and **Redirect URI** on the Mastodon end of things? If nothing is required there, maybe just say that it's fine to leave those fields empty. I tried following your steps and felt uncertain there.

2023-03-27 16:43 UTC, frenck requested changes
Hi there @wasperen 👋 

Thanks for the PR; however, it seems like the PR is targeting an incorrect branch. Currently, it is targeting the `current` branch, however, it depends on a code change in the Core repository, which will be released in a future (next) version of Home Assistant. Therefore, this PR should target the `next` branch.

Please change the target to `next` and git rebase your changes if needed.

Thanks 👍 

../Frenck

2023-03-27 16:43 UTC, frenck commented on source/_integrations/mastodon.markdown
> +public but not appear on the public timeline; ‘public’ - post will be public (the default)"
```suggestion
  description: "determines the scope of how the Toot is going to be sent. Can be any of: `direct` - post will be 
visible only to mentioned users; `private` - post will be visible only to followers; `unlisted` - post will be 
public but not appear on the public timeline; ‘public’ - post will be public (the default)"
```

2023-09-26 08:03 UTC, frenck commented
Closing PR as the parent PR has been closed.

2023-09-26 08:03 UTC, closed without merging