Add new JVC Projector integration
home-assistant/home-assistant.github.io pull request #25470
Opened 2022-12-30 19:46 UTC by SteveEasley

## Proposed change

Adds documentation for new JVC Projector integration .

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/84748
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/3980
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2022-12-30 23:56 UTC, Kane610 requested changes
Looks good!

2022-12-30 23:56 UTC, Kane610 commented on source/_integrations/jvc_projector.markdown
> +ha_release: '2023.1'
```suggestion
ha_release: '2023.2'
```
Too late for that :)

2022-12-31 08:49 UTC, Kane610 approved these changes, later dismissed

2023-01-02 13:13 UTC, frenck approved these changes, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2023-02-07 13:26 UTC, SteveEasley commented
@frenck This integration is done for this release. I will add the additional mentioned features in the next release when I will have more time.

2023-05-05 18:53 UTC, elupus reviewed
Looks good, not sure what frenck meant with the ha_release changes .

2023-05-06 21:37 UTC, frenck commented on source/_integrations/jvc_projector.markdown
> +ha_release: '2023.2'
```suggestion
ha_release: '2023.6'
```

2023-05-06 21:38 UTC, frenck commented
> Looks good, not sure what frenck meant with the ha_release changes .

I've just added the change. The `ha_release` version in the frontmatter of the integration page indicates the version of Home Assistant this integration was introduced. It needs to match the version of when the parent PR was merged.

../Frenck

2023-05-06 21:45 UTC, frenck approved these changes

2023-05-06 21:45 UTC, merged