Added docs for evse_wifi integration
home-assistant/home-assistant.github.io pull request #25646
Opened 2023-01-08 17:03 UTC by JFK344

## Proposed change

Added the documentation for the new evse_wifi integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #
https://github.com/home-assistant/core/pull/85438
## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-01-10 11:42 UTC, frenck requested changes

2023-01-10 11:42 UTC, frenck commented on source/_integrations/evse_wifi.markdown
> +  - number
Initial additions / PRs to Home Assistant (including the actual integration), may only contain a single platform at the time. The initial documentation PR this cannot contain multiple platforms either.

2023-01-10 11:42 UTC, frenck commented on source/_integrations/evse_wifi.markdown
> +ha_release: 0.38
Unlikely 😉

2023-01-10 11:42 UTC, frenck commented on source/_integrations/evse_wifi.markdown
> +description: Instructions on how to integrate a WiFi-equipped Simple EVSE Charging station with Home Assistant
```suggestion
description: Instructions on how to integrate a Wi-Fi-equipped Simple EVSE Charging station with Home Assistant
```

2023-01-10 11:42 UTC, frenck commented on source/_integrations/evse_wifi.markdown
> +To enable this sensor in your installation, search for "Evse-Wifi" in the Integrations and add it via the Configuration-Flow
```suggestion
{% include integrations/config-flow.md %}
```

2023-01-10 11:42 UTC, frenck commented on source/_integrations/evse_wifi.markdown
> +- Charge Current
Please limit this PR to a single platform.

2023-01-13 08:16 UTC, frenck requested changes

2023-01-13 08:16 UTC, frenck commented on source/_integrations/evse_wifi.markdown
> +To enable this sensor in your installation, search for "Evse-Wifi" in the Integrations and add it via the Configuration-Flow
```suggestion
```

2023-01-13 08:24 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2023-01-13 08:25 UTC, JFK344 commented
Yes 🥳  thank you 👍 now lets see how the acutal integration 😅

2023-06-26 16:39 UTC, frenck commented
Closing PR as the parent PR has been closed.

2023-06-26 16:39 UTC, closed without merging