Document jammed, locking and unlocking for MQTT lock
home-assistant/home-assistant.github.io pull request #25728
Opened 2023-01-12 20:29 UTC by Nardol

## Proposed change

Document `state_jammed`, `state_locking` and `state_unlocking` in the MQTT lock documentation

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#85779
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-01-12 22:27 UTC, jbouwh commented on source/_integrations/lock.mqtt.markdown
> +
```suggestion

```suggestion
A MQTT lock can also report the intermediate states `unlocking`, `locking` and a state when the lock is `jammed`.

```

2023-01-12 22:41 UTC, jbouwh commented
Please update also the abbreviations on the MQTT integration page.

2023-01-14 17:16 UTC, jbouwh commented on source/_integrations/mqtt.markdown
> +    'stat_jammed':         'state_jammed',
```suggestion
```

2023-01-14 17:20 UTC, jbouwh requested changes
One leftover of `jammed` state.

2023-01-14 17:48 UTC, Nardol commented
> One leftover of `jammed` state.

Did I forget another than this I commit at last?
I hop I won't forget abbreviations for next PR.

2023-01-14 18:10 UTC, jbouwh approved these changes
Looks good!

2023-01-16 07:44 UTC, merged