Add docs for Dremel 3D Printer
home-assistant/home-assistant.github.io pull request #25775
Opened 2023-01-15 22:40 UTC by tkdrob

## Proposed change

Add docs for Dremel 3D Printer

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/85969
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-01-16 07:47 UTC, frenck commented on source/_integrations/dremel_3d_printer.markdown
> +
```suggestion
```

2023-01-16 07:48 UTC, frenck requested changes

2023-01-16 07:48 UTC, frenck commented on source/_integrations/dremel_3d_printer.markdown
> +The [Dremel 3D Printer](https://www.dremel.com/gn/en/digilab) can be added by knowing its Host IP address.
This is more of a prerequisite instead of an introduction.

2023-06-01 10:36 UTC, frenck requested changes
The PR for our brands repository is missing.

Could you create one @tkdrob and link it to this PR?

<https://github.com/home-assistant/brands>

Thanks already! 👍 

../Frenck

2023-06-01 12:19 UTC, tkdrob commented
> The PR for our brands repository is missing.
> 
> Could you create one @tkdrob and link it to this PR?
> 
> https://github.com/home-assistant/brands
> 
> Thanks already! 👍
> 
> ../Frenck

Don't we already have a brand logo for Dremel? We should have one already.

Update: Guess I just need to move the logo out of custom components then.

2023-06-01 14:53 UTC, frenck commented on source/_integrations/dremel_3d_printer.markdown
> +ha_release: 2023.6
```suggestion
ha_release: 2023.7
```

2023-06-01 14:56 UTC, frenck approved these changes
Thanks, @tkdrob!

../Frenck

2023-06-01 14:58 UTC, merged