Add doc for new `contains` jinja filter and test
home-assistant/home-assistant.github.io pull request #25890
Opened 2023-01-22 17:35 UTC by Vaarlion

## Proposed change

Add some doc for the new jinja test and filter `contains` proposed in https://github.com/home-assistant/core/pull/86390

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/86390
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-01-22 18:43 UTC, frenck requested changes
This PR is targeting an incorrect branch. As it has a parent PR in the core codebase, it depends on a next release of Home Assistant and thus needs to go into the `next` branch.

Please change the target PR of this PR to the `next` branch and git rebase your changes onto the upstream `next` branch to ensure your PR is clean without unintended PRs coming along.

../Frenck

2023-01-22 19:49 UTC, Vaarlion commented
My apologist for the time lost having to tell me what i should have known.
This is now rebased and changed.

2023-01-22 19:59 UTC, frenck requested changes

2023-01-22 19:59 UTC, frenck commented on source/_docs/configuration/templating.markdown
> +The `contains` test and filter allow you to do the exact opposite and test for a list containing an element. This is particularly usefully in `select` or `selectattr` filter, as well as to check a if
```suggestion
Jinja provides by default a [`in` operator](https://jinja.palletsprojects.com/en/latest/templates/#other-operators) how return `True` when one element is `in` a provided list.
The `contains` test and filter allow you to do the exact opposite and test for a list containing an element. This is particularly useful in `select` or `selectattr` filter, as well as to check if a device has a specific attribute, a `supported_color_modes`, a specific light effect.
```

2023-01-22 19:59 UTC, frenck commented on source/_docs/configuration/templating.markdown
> +- `{{ state_attr('light.dining_room', 'effect_list') | contains('rainbow') }}` will return `true` if the light have a `rainbow` effect
```suggestion
- `{{ state_attr('light.dining_room', 'effect_list') | contains('rainbow') }}` will return `true` if the light has a `rainbow` effect.
```

2023-01-22 19:59 UTC, frenck commented on source/_docs/configuration/templating.markdown
> +  This more complex example use the `contains` filter to match the current month with a list. In this case it's used to generate a list of light theme to give to the `Input select: Set options` servi
```suggestion
  This more complex example uses the `contains` filter to match the current month with a list. In this case, it's used to generate a list of light theme to give to the `Input select: Set options` service.
```

2023-01-23 05:06 UTC, Vaarlion commented on source/_docs/configuration/templating.markdown
> +  This more complex example use the `contains` filter to match the current month with a list. In this case it's used to generate a list of light theme to give to the `Input select: Set options` servi
Fixed thank

2023-01-23 05:07 UTC, Vaarlion commented on source/_docs/configuration/templating.markdown
> +- `{{ state_attr('light.dining_room', 'effect_list') | contains('rainbow') }}` will return `true` if the light have a `rainbow` effect
Fixed thank

2023-01-23 05:07 UTC, Vaarlion commented on source/_docs/configuration/templating.markdown
> +The `contains` test and filter allow you to do the exact opposite and test for a list containing an element. This is particularly usefully in `select` or `selectattr` filter, as well as to check a if
Fixed thank

2023-01-25 10:51 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2023-01-25 10:51 UTC, merged