Add page for myUplink
home-assistant/home-assistant.github.io pull request #25920
Opened 2023-01-24 15:05 UTC by pajzo

## Proposed change

Documentation for a new integration: myUplink

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/86522
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-10-08 17:55 UTC, frenck requested changes
Some tiny tweaks, otherwise it looks great 👍 

../Frenck

2023-10-08 17:55 UTC, frenck commented on source/_integrations/myuplink.markdown
> +Depending on the type of devices in your system there will be added one or more sensor entities to Home Assistant. Currently there is support for generic and temperature sensors.
```suggestion
Depending on the type of devices in your system, one or more sensor entities to Home Assistant. Currently, there is support for generic and temperature sensors.
```

2023-10-08 17:55 UTC, frenck commented on source/_integrations/myuplink.markdown
> +The myUplink integration allows users to get information about their devices supporting myUplink using the [official cloud API](https://dev.myuplink.com).
We write pages for the reader, not a group of people.

```suggestion
The myUplink integration lets you get information about the devices supporting myUplink using the [official cloud API](https://dev.myuplink.com).
```

2023-10-08 17:55 UTC, frenck commented on source/_integrations/myuplink.markdown
> +2. Go to [Applications](https://dev.myuplink.com/apps), register a new App:
```suggestion
2. Go to [**Applications**](https://dev.myuplink.com/apps), register a new App:
```

2023-10-08 17:55 UTC, frenck commented on source/_integrations/myuplink.markdown
> +- Redirect URI: `https://my.home-assistant.io/redirect/oauth`
```suggestion
- **Application ID**: Home Assistant (or whatever name makes sense to you)
- **OAuth Flow**: Authorization Code Grant Flow
- **Redirect URI**: `https://my.home-assistant.io/redirect/oauth`
```

2023-10-08 17:55 UTC, frenck commented on source/_integrations/myuplink.markdown
> +The integration configuration will ask for the *Client ID* and *Client Secret* created above. See [Application Credentials](/integrations/application_credentials) for more details.
```suggestion
The integration configuration will require the **Client ID** and **Client Secret** created above. See [Application Credentials](/integrations/application_credentials) for more details.
```

2023-10-09 09:30 UTC, frenck approved these changes, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2024-01-12 11:22 UTC, MartinHjelmare requested changes

2024-01-12 11:22 UTC, MartinHjelmare commented on source/_integrations/myuplink.markdown
> +ha_release: '2023.2'
```suggestion
ha_release: '2024.2'
```

2024-01-12 11:22 UTC, MartinHjelmare commented on source/_integrations/myuplink.markdown
> +Depending on the type of devices in your system, one or more sensor entities to Home Assistant. Currently, there is support for generic and temperature sensors.
```suggestion
Depending on the type of devices in your system, one or more sensor entities will be created in Home Assistant. Currently, there is support for generic and temperature sensors.
```

2024-01-12 11:22 UTC, MartinHjelmare commented on source/_integrations/myuplink.markdown
> +Depending on the type of devices in your system, one or more sensor entities to Home Assistant. Currently, there is support for generic and temperature sensors.
Generic sensors sounds weird. Maybe just don't mention what sensors are supported as that will change over time and it's hard to keep the documentation updated to cover it exactly?

2024-01-12 11:22 UTC, MartinHjelmare commented on source/_integrations/myuplink.markdown
> +2. Go to [**Applications**](https://dev.myuplink.com/apps), register a new App:
```suggestion
2. Go to [**Applications**](https://dev.myuplink.com/apps), and register a new App:
```

2024-01-16 09:20 UTC, MartinHjelmare approved these changes
Thanks!

2024-01-16 09:20 UTC, merged