Added documentation for the rpi_pfio platform.
home-assistant/home-assistant.github.io pull request #2597
Opened 2017-05-08 13:31 UTC by basschipper

**Description:**
Support for the PiFace Digital I/O module (Raspberry Pi add on board)
This is basically a port of the rpi_gpio component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#7494

2017-05-08 16:33 UTC, Landrash requested changes
Looks really good and only needed change is to update the release number before release.

If a better link is available I would recommend linking to the maker of the product instead of Element 14.

2017-05-08 16:33 UTC, Landrash commented on source/_components/binary_sensor.rpi_pfio.markdown
> +ha_release: 0.44.3
.45 will be the next release.

2017-05-08 16:33 UTC, Landrash commented on source/_components/binary_sensor.rpi_pfio.markdown
> +The `rpi_pfio` binary sensor platform allows you to read sensor values of the [PiFace Digital I/O](https://www.element14.com/community/docs/DOC-69001) .
Could the link be pointed to the manufacture instead of Element 14?

2017-05-08 19:16 UTC, basschipper commented on source/_components/binary_sensor.rpi_pfio.markdown
> +The `rpi_pfio` binary sensor platform allows you to read sensor values of the [PiFace Digital I/O](https://www.element14.com/community/docs/DOC-69001) .
Element14 seems to be the manufacturer of the PiFace.

2017-05-08 19:16 UTC, Landrash approved these changes
Good to go and can be merged when parent PR is merged.

2017-05-08 19:19 UTC, Landrash commented on source/_components/binary_sensor.rpi_pfio.markdown
> +The `rpi_pfio` binary sensor platform allows you to read sensor values of the [PiFace Digital I/O](https://www.element14.com/community/docs/DOC-69001) .
Oh. Well then my bad :)

2017-05-10 05:36 UTC, merged

2020-04-17 18:05 UTC, roland1970 commented
Hello Bas ,Is it possible to add more then 1 piface?
I mean to add the address-rule so that we can use more pifaces.
Or can you tell me what I must change make that possible .

2020-04-17 19:30 UTC, klaasnicolaas commented
Pleas don't comment on old pull requests. You can create an issue here instead: https://github.com/home-assistant/core/issues/new/choose