Add RGB, RGBW and RGBWW capability to template.light
home-assistant/home-assistant.github.io pull request #25994
Opened 2023-01-28 15:44 UTC by Vaarlion

## Proposed change

This clean old mention of the white control that no-longer work since https://github.com/home-assistant/core/pull/76923 and add the new documentation for it's replacement, RGB, RGBW and RGBWW control.

It also replace the still working but deprecated `color` keyword for the new and more accurate `hs` keyword.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [X] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/76923
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-09-30 15:48 UTC, YuriiMaiboroda requested changes
Need to remove duplicate of `required: false` for `set_rgbww`.

2023-09-30 15:48 UTC, YuriiMaiboroda commented on source/_integrations/light.template.markdown
>          required: false
`required: false` is duplicated

2023-09-30 16:41 UTC, Vaarlion commented on source/_integrations/light.template.markdown
>          required: false
Good catch :)

2023-09-30 17:12 UTC, YuriiMaiboroda approved these changes
LGTM

2023-11-02 22:11 UTC, Vaarlion commented
rebased one last time, i no longer working on this.
It's been to long.

2023-11-23 08:13 UTC, c0ffeeca7 commented on source/_integrations/light.template.markdown
> +        description: Defines a template to get the hs color of the light. Must render a tuple (hue, saturation)
```suggestion
        description: Defines a template to get the HS color of the light. Must render a tuple (hue, saturation).
```

2023-11-23 08:13 UTC, c0ffeeca7 commented on source/_integrations/light.template.markdown
> +        description: Defines a template to get the rgb color of the light. Must render a tuple or a list (red, green, blue)
```suggestion
        description: Defines a template to get the RGB color of the light. Must render a tuple or a list (red, green, blue).
```

2023-11-23 08:13 UTC, c0ffeeca7 commented on source/_integrations/light.template.markdown
> +        description: Defines a template to get the rgbw color of the light. Must render a tuple or a list (red, green, blue, white)
```suggestion
        description: Defines a template to get the RGBW color of the light. Must render a tuple or a list (red, green, blue, white).
```

2023-11-23 08:13 UTC, c0ffeeca7 commented on source/_integrations/light.template.markdown
> +        description: Defines a template to get the rgbww color of the light. Must render a tuple or a list (red, green, blue, cold white, warm white)
```suggestion
        description: Defines a template to get the RGBWW color of the light. Must render a tuple or a list (red, green, blue, cold white, warm white).
```

2023-11-23 08:13 UTC, c0ffeeca7 commented on source/_integrations/light.template.markdown
> +        description: "Defines an action to run when the light is given a rgb color command. Available variables: `rgb` as a tuple, `r`, `g` and `b`"
```suggestion
        description: "Defines an action to run when the light is given an RGB color command. Available variables: `rgb` as a tuple, `r`, `g` and `b`."
```

2023-11-23 08:13 UTC, c0ffeeca7 commented on source/_integrations/light.template.markdown
> +        description: "Defines an action to run when the light is given a rgbw color command. Available variables: `rgbw` as a tuple, `rgb` as a tuple, `r`, `g`, `b` and `w`"
```suggestion
        description: "Defines an action to run when the light is given an RGBW color command. Available variables: `rgbw` as a tuple, `rgb` as a tuple, `r`, `g`, `b` and `w`."
```

2023-11-23 08:13 UTC, c0ffeeca7 commented on source/_integrations/light.template.markdown
> +        description: "Defines an action to run when the light is given a rgbww color command. Available variables: `rgbww` as a tuple, `rgb` as a tuple, `r`, `g`, `b`, `cw` and `ww`"
```suggestion
        description: "Defines an action to run when the light is given an RGBWW color command. Available variables: `rgbww` as a tuple, `rgb` as a tuple, `r`, `g`, `b`, `cw` and `ww`."
```

2023-11-23 08:13 UTC, c0ffeeca7 commented on source/_integrations/light.template.markdown
> +Brightness will be passed as a named parameter `brightness` to either of `turn_on`, `color_temp`, `effect`, `hs_color`, `rgb_color`, `rgbw_color` or `rgbww_color` scripts if the corresponding paramet
```suggestion
Brightness will be passed as a named parameter `brightness` to either of `turn_on`, `color_temp`, `effect`, `hs_color`, `rgb_color`, `rgbw_color` or `rgbww_color` scripts if the corresponding parameter is also in the call. In this case, the brightness script (`set_level`) will not be called.
```

2023-11-23 08:13 UTC, c0ffeeca7 commented on source/_integrations/light.template.markdown
> +### Make a Global light entity for a multi segments WLED light
```suggestion
### Make a global light entity for a multi-segment WLED light
```

2023-11-23 08:14 UTC, c0ffeeca7 approved these changes, later dismissed
Thank you, @Vaarlion :+1:

2023-11-23 08:59 UTC, c0ffeeca7 approved these changes

2023-11-23 09:00 UTC, merged