Feat/add onetracker docs
home-assistant/home-assistant.github.io pull request #26009
Opened 2023-01-29 22:36 UTC by packruler

## Proposed change

Add docs for OneTracker integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/86921
- Link to parent pull request in the Brands repository:  https://github.com/home-assistant/brands/pull/4088

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-01-30 08:44 UTC, frenck requested changes

2023-01-30 08:44 UTC, frenck commented on source/_integrations/onetracker.markdown
> +The `OneTracker` platform allows one to track deliveries by [OneTracker](https://onetracker.app), a service that supports 490+ couriers worldwide. To use the tracking API functionality, the Essential
```suggestion
The OneTracker integration allows one to track deliveries by [OneTracker](https://onetracker.app), a service that supports 490+ couriers worldwide. To use the tracking API functionality, the Essentials plan is required. This plan includes 100 shipments per month. There are various paid-for tiers after that.
```

2023-01-30 08:44 UTC, frenck commented on source/_integrations/onetracker.markdown
> +  type: string
Configuration basic doesn't use these fields.

```suggestion
```

2023-01-30 08:44 UTC, frenck commented on source/_integrations/onetracker.markdown
> +  type: string
```suggestion
```

2023-01-30 08:44 UTC, frenck commented on source/_integrations/onetracker.markdown
> +## Setup
```suggestion
## Prerequisites
```

2023-01-30 08:44 UTC, frenck commented on source/_integrations/onetracker.markdown
> +or [iOS](https://itunes.apple.com/us/app/onetracker-package-tracking/id1409295535) application.
Considering this is needed before setting up this integration, I suggest on moving this chapter above the config flow section.

2023-01-30 16:55 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2023-01-30 17:07 UTC, packruler commented
> ✅ Approved. Can be merged as soon as the parent PR gets merged. ⚠️ The `ha_release` might need an update before merging this one in.

Is there a proper placeholder version?

2023-01-30 17:34 UTC, frenck commented
> Is there a proper placeholder version?

No. This is fine. We'll check when the upstream PR is ready.

2023-03-07 17:49 UTC, packruler commented
https://github.com/home-assistant/core/pull/86921#issuecomment-1458583523

2023-03-07 17:49 UTC, closed without merging