Add documentation for entity and device filters
home-assistant/home-assistant.github.io pull request #26145
Opened 2023-02-06 16:11 UTC by piitaya

## Proposed change

Add documentation for new `filter` option for `entity` and `device` selectors. Support for multiple device_classes has been added too.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/87536 https://github.com/home-assistant/frontend/pull/15302
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-02-06 16:16 UTC, piitaya commented on source/_docs/blueprint/selectors.markdown
> +  type: map
Seems that `[map, list]` is not allowed so I set `map`.

2023-03-04 14:18 UTC, frenck requested changes
Couple of small corrections to match our style guides:

<https://developers.home-assistant.io/docs/documenting/yaml-style-guide#properties-that-accept-a-mapping-or-a-list-of-mappings>

2023-03-04 14:18 UTC, frenck commented on source/_docs/blueprint/selectors.markdown
> +    model: RWL021
```suggestion
    - integration: deconz
      manufacturer: Philips
      model: RWL021
```

2023-03-04 14:18 UTC, frenck commented on source/_docs/blueprint/selectors.markdown
> +    device_class: motion
```suggestion
    - integration: zha
      domain: binary_sensor
      device_class: motion
```

2023-03-09 11:42 UTC, frenck approved these changes
Thanks, @piitaya 👍 

../Frenck

2023-03-09 11:43 UTC, merged