Radio migration procedure in ZHA docs
home-assistant/home-assistant.github.io pull request #26236
Opened 2023-02-13 13:29 UTC by Hedda

Radio migration procedure in ZHA docs.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-02-13 13:40 UTC, frenck requested changes
There is a CI failure. Additionally, I think we should first handle the other open PR you have left, before opening new ones.

Thanks 👍 

../Frenck

2023-02-13 14:07 UTC, Hedda commented
> There is a CI failure.

That has been fixed.

> Additionally, I think we should first handle the other open PR you have left, before opening new ones.

Can we please agree to disagree on that? Existing PRs literally take years primarily due to a lack of reviews, see example https://github.com/home-assistant/home-assistant.io/pull/18864

I do not think that we should refrain from opening new separate pull requests for different sections/segments of the documentation when at least one of the reasons why there are many open pull requests is that it goes several months between each review. 

My feedback to you on that is that I believe the existing integrations documentation still has as many holes as it does because you make it way too hard to contribute documentation.

2023-02-14 07:40 UTC, frenck commented
> Can we please agree to disagree on that? 
Sure, you may disagree. Yet, I want to have the old ones handled the old ones first.

2023-02-14 08:28 UTC, Hedda commented
> > Can we please agree to disagree on that?
> 
> Sure, you may disagree. Yet, I want to have the old ones handled first.

Then please consider having more people review documentation pull requests and increasing the time between re-reviews after changes. 

You are now telling people not to open any new pull requests for separate unrelated segments due to the fact that reviewers are not revising or processing the existing pull requests. 

Again, see https://github.com/home-assistant/home-assistant.io/pull/18864 which took 6-months to get even get an initial first review and that initial review can not even be considered a proper review as it was just a short comment to rewrite of the entire PR, then it took another 6-months(!) to get the second review, and so on. 

My only other open pull request also took more than 2-months before got a first review to https://github.com/home-assistant/home-assistant.io/pull/24494

Yes, I realize that the text is not short in those two specific pull requests, but seriously, do you really think that taking this long time between reviews in those two specific pull requests is where the process needs to change rather than telling people not to open any new pull requests for separate and totally unrelated topic segments in the ZHA integration documenation?

It is not like there has been an overwhelming amount of pull requests coming in for the ZHA integration documentation, and looking at your more recent analytics statistics and community forum activity on the usage of this ZHA integration I believe that it should be clear to most that the ZHA integration documentation is need of being both improved as well as being expanded.

2023-02-14 08:38 UTC, frenck commented
Could you please calm down?

All I ask was for readable documentation, which imho is the bare minimum.  Yes, we do limit people in the amount of open PRs at times, simply to prevent many PRs lingering around. As for the other PRs some have recently updated and need a new review pass, another you have updated just hours ago and didn't process the review comment.

It ain't that difficult, we process hundreds of PRs every month, yet, you simply seems to ignore or refusing to process any comments. I rarely have this level of a (unneeded imho), battle. That is fine, but they won't get merged (which is a unfortunate, as more docs are great).

I have recently merged a PR for you adding lots of great text after just some small comments. So, you actually can do it.

That said, all of this if fairly off topic for this pr contents and thus will ask to stop this discussion on this PR.

Thanks.

../Frenck

2023-03-13 10:38 UTC, frenck commented
@Hedda Your other PRs have been merged, feel free to push this one forward when you're ready.

../Frenck

2023-03-24 07:54 UTC, Hedda commented
> feel free to push this one forward when you're ready.

Thanks. This is ready now. Please review it when you have time.

2023-06-19 06:23 UTC, Hedda commented
@frenck Bump?

2023-07-07 09:37 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +To easily migrate from a Zigbee Coordinator radio adapter to another Zigbee Coordinator adapter you can use the config flow for radio migration that is built into the Zigbee Home Automation (ZHA) int
```suggestion
Follow this guide if you have a Zigbee Home Assistant (ZHA) network running and want to migrate from one Zigbee coordinator radio adapter to another Zigbee coordinator radio adapter.
```

2023-07-07 09:40 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +### Zigbee Coordinator adapter migration inside ZHA
```suggestion
## Migrating to a new Zigbee coordinator adapter inside ZHA
```

2023-07-07 14:09 UTC, c0ffeeca7 requested changes
Some suggestions for style tweaks

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +Prerequisites:
```suggestion
### Prerequisites

```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +- Your old Zigbee Coordinator radio adapter used in the ZHA integration need to be of radio type ezsp (Silicon Labs EmberZnet), znp (Texas Instruments Z-Stack ZNP), or deCONZ (ConBee/RaspBee from dre
```suggestion
- Your old Zigbee Coordinator radio adapter is used in the ZHA integration (not in deCONZ or MQTT)
- It is of radio type ezsp (Silicon Labs EmberZnet), znp (Texas Instruments Z-Stack ZNP), or deCONZ (ConBee/RaspBee from dresden elektronik).
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - If your old Zigbee Coordinator is a deCONZ (ConBee/RaspBee) radio adapter then you also need to make sure that is already running [firmware 0x26700700 (from 2021-08-18)](https://github.com/dresde
```suggestion
  - If your old Zigbee coordinator is a deCONZ (ConBee/RaspBee) radio adapter, make sure it is running [firmware 0x26700700 (from 2021-08-18)](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Firmware-Changelog) or later.
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +
```suggestion
### To migrate to a new Zigbee coordinator radio inside ZHA

```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +The radio migration flow can be found in the Home Assistant's UI under "Settings" -> "Devices & Services", select "CONFIGURE" on the Zigbee Home Assistant (ZHA) integration.
```suggestion
1. Go to **{% my integrations title="Settings > Devices & Services" %}** and select the ZHA integration. Then select **Configure**.
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +
```suggestion
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +1. Inside the ZHA integration, under "Network Settings", select "MIGRATE RADIO".
```suggestion
1. Under **Network settings**, select **Migrate radio**.
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +2. "Reconfigure ZHA" will start, informing that ZHA will start and asking if you want to continue, select "SUBMIT".
```suggestion
1. Reconfiguration of ZHA will start. Select **Submit**.
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +3. Under "Migrate or re-configure" select "Migrate to a new radio".
```suggestion
1. Under **Migrate or re-configure**, select **Migrate to a new radio**.
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +4. "Migrate to a new radio" will inform you that an automatic backup will be performed and that your old Zigbee Coordinator radio will be then reset before the backup is automatically restored, selec
```suggestion
1. **Migrate to a new radio** will inform you that an automatic backup will be performed and that your old Zigbee coordinator radio will then be reset before the backup is automatically restored.
- Select **Submit**.
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +5. "Unplug your old radio" will inform you that your old Zigbee Coordinator radio has been reset and you can now plug in your new Zigbee Coordinator radio adapter, (to avoid interference it is recomm
```suggestion
1. **Unplug your old radio** will inform you that your old Zigbee coordinator radio has been reset and that you can now plug in your new Zigbee coordinator radio adapter.
  - To avoid interference, use a USB extension cable. 
  - Use a USB 2.0 port or a powered USB 2.0 hub and keep the Zigbee stick away from USB 3.0 devices. 
  - You may now also choose to either unplug your old Zigbee coordinator radio adapter or keep your old radio plugged in.
  - If that radio was a combined Z-Wave and Zigbee radio, like the HUSBZB-1 adapter, then only the Zigbee radio part of it was reset. Confirm that the Zigbee Coordinator radio adapter is properly connected and select **Submit**.
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +6.  You now need to start the backup restore process. If your new Zigbee Coordinator radio adapter was automatically discovered by the Zigbee Home Automation (ZHA) integration then select "CONFIGURE"
```suggestion
1.  You now need to start the backup restore process. 
  - If your new Zigbee Coordinator radio adapter was automatically discovered by the Zigbee Home Automation (ZHA) integration, then select **Configure**.  
  - If not, then you might first have to restart the radio migration flow. Under "*Network Settings**, select **Migrate radio** > **Reconfigure ZHA** > **Migrate to a new radio**.
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +7. Among the options for "Network Formation" select "Restore and automatic backup".
```suggestion
1. Under **Network Formation**, select **Restore and automatic backup**.
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +8. Choose the latest automatic backup under "Restore Automation Backup" and select "SUBMIT".
```suggestion
1. Under **Restore Automation Backup**, choose the latest automatic backup and select **Submit**.
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +9. Overwrite Radio IEEE Address. Tick the box for "Permanently replace the radio IEEE address" and select "SUBMIT". This may take some time as overwriting the IEEE address may take a while so simply
```suggestion
1. Under **Overwrite Radio IEEE Address**, select the **Permanently replace the radio IEEE address** and select **Submit**. Overwriting the IEEE address may take a while. Wait. 
  - Your old Zigbee Coordinator radio and your new stick will now have the same Zigbee IEEE address (unique MAC address for the Zigbee device). 
  - Selecting this option is required for the migration process to complete successfully. 
  - From this point onwards, you should not operate the old stick in the same area unless you change the Zigbee IEEE address on it. 
  - If you do not migrate the Zigbee IEEE address from your old Zigbee Coordinator radio, then you will have to re-join/re-pair many of your devices in order to keep them working. 
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +10. Final message of "Success!" should pop up with information that all options were successfully saved. Select "FINISH" to confirm.
```suggestion
1. Finally, a **Success!** message should pop up with information that all options were successfully saved. 
 - Select **Finish** to confirm. 
```

2023-07-07 14:09 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +The migration process is complete, however, be aware that you now need to be a little patient you will not be able to control all your existing Zigbee devices until they rejoined the Zigbee network a
```suggestion
The migration process is complete. However, be aware that you will not be able to control all your existing Zigbee devices until they rejoined the Zigbee network again. Normally, they will rejoin within a couple of hours. You can accelerate the rejoin process by power-cycling your Zigbee devices.
```

2023-07-07 14:11 UTC, c0ffeeca7 commented
Thank you for adding this, @Hedda. 
I think it is good to have this procedure also here on the ZHA page, rather than just having it on the SkyConnect website.

2023-07-09 07:03 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +### To migrate to a new Zigbee coordinator radio inside ZHA
```suggestion
```

2023-07-09 07:03 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +
```suggestion
### To migrate to a new Zigbee coordinator radio inside ZHA

```

2023-07-09 07:07 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +
```suggestion
### To migrate to a new Zigbee coordinator radio inside ZHA

2023-07-09 07:08 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +### To migrate to a new Zigbee coordinator radio inside ZHA
```suggestion


### To migrate to a new Zigbee coordinator radio inside ZHA

```

2023-07-09 07:11 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +### To migrate to a new Zigbee coordinator radio inside ZHA
```suggestion
```

2023-07-09 07:20 UTC, c0ffeeca7 reviewed
Fix indent issue I introduced in previous review comment

2023-07-09 07:20 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +- Select **Submit**.
```suggestion
  - Select **Submit**.
```

2023-07-09 07:20 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - To avoid interference, use a USB extension cable.
```suggestion
    - To avoid interference, use a USB extension cable. 
```

2023-07-09 07:20 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - Use a USB 2.0 port or a powered USB 2.0 hub and keep the Zigbee stick away from USB 3.0 devices.
```suggestion
    - Use a USB 2.0 port or a powered USB 2.0 hub and keep the Zigbee stick away from USB 3.0 devices. 
```

2023-07-09 07:20 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - You may now also choose to either unplug your old Zigbee coordinator radio adapter or keep your old radio plugged in.
```suggestion
    - You may now also choose to either unplug your old Zigbee coordinator radio adapter or keep your old radio plugged in.
```

2023-07-09 07:20 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - If that radio was a combined Z-Wave and Zigbee radio, like the HUSBZB-1 adapter, then only the Zigbee radio part of it was reset. Confirm that the Zigbee Coordinator radio adapter is properly con
```suggestion
    - If that radio was a combined Z-Wave and Zigbee radio, like the HUSBZB-1 adapter, then only the Zigbee radio part of it was reset. Confirm that the Zigbee Coordinator radio adapter is properly connected and select **Submit**.
```

2023-07-09 07:20 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - If your new Zigbee Coordinator radio adapter was automatically discovered by the Zigbee Home Automation (ZHA) integration, then select **Configure**.
```suggestion
    - If your new Zigbee Coordinator radio adapter was automatically discovered by the Zigbee Home Automation (ZHA) integration, then select **Configure**.  
```

2023-07-09 07:20 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - If not, then you might first have to restart the radio migration flow. Under "*Network Settings**, select **Migrate radio** > **Reconfigure ZHA** > **Migrate to a new radio**.
```suggestion
    - If not, then you might first have to restart the radio migration flow. Under "*Network Settings**, select **Migrate radio** > **Reconfigure ZHA** > **Migrate to a new radio**.
```

2023-07-09 07:23 UTC, c0ffeeca7 requested changes

2023-07-09 07:23 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - Select **Submit**.
```suggestion
    - Select **Submit**.
```

2023-07-09 07:23 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - Your old Zigbee Coordinator radio and your new stick will now have the same Zigbee IEEE address (unique MAC address for the Zigbee device).
```suggestion
    - Your old Zigbee Coordinator radio and your new stick will now have the same Zigbee IEEE address (unique MAC address for the Zigbee device). 
```

2023-07-09 07:23 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - Selecting this option is required for the migration process to complete successfully.
```suggestion
    - Selecting this option is required for the migration process to complete successfully. 
```

2023-07-09 07:23 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - From this point onwards, you should not operate the old stick in the same area unless you change the Zigbee IEEE address on it.
```suggestion
    - From this point onwards, you should not operate the old stick in the same area unless you change the Zigbee IEEE address on it. 
```

2023-07-09 07:23 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +  - If you do not migrate the Zigbee IEEE address from your old Zigbee Coordinator radio, then you will have to re-join/re-pair many of your devices in order to keep them working.
```suggestion
    - If you do not migrate the Zigbee IEEE address from your old Zigbee Coordinator radio, then you will have to re-join/re-pair many of your devices in order to keep them working. 
```

2023-07-09 07:23 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> + - Select **Finish** to confirm.
```suggestion
  - Select **Finish** to confirm. 
```

2023-07-09 07:29 UTC, c0ffeeca7 commented on source/_integrations/zha.markdown
> +    - If not, then you might first have to restart the radio migration flow. Under "*Network Settings**, select **Migrate radio** > **Reconfigure ZHA** > **Migrate to a new radio**.
```suggestion
    - If not, then you might first have to restart the radio migration flow. Under **Network Settings**, select **Migrate radio** > **Reconfigure ZHA** > **Migrate to a new radio**.
```

2023-07-11 14:43 UTC, puddly requested changes

2023-07-11 14:43 UTC, puddly commented on source/_integrations/zha.markdown
> +1. Under **Network Formation**, select **Restore and automatic backup**.
```suggestion
1. Under **Network Formation**, select **Restore an automatic backup**.
```

2023-07-11 14:43 UTC, puddly commented on source/_integrations/zha.markdown
> +    - If your new Zigbee Coordinator radio adapter was automatically discovered by the Zigbee Home Automation (ZHA) integration, then select **Configure**.
`Configure` only shows up during discovery. In the migration flow the serial ports will be listed as they are during ZHA setup:

```suggestion
    - Select your new Zigbee radio from the list of serial ports and select **Next**.
```

2023-07-11 14:43 UTC, puddly commented on source/_integrations/zha.markdown
> +    - If not, then you might first have to restart the radio migration flow. Under **Network Settings**, select **Migrate radio** > **Reconfigure ZHA** > **Migrate to a new radio**.
Migration won't work if the current radio is unresponsive. You can use the re-configure flow to do this instead:

```suggestion
    - If your new radio does not appear or you need to reboot after plugging in new hardware, you can resume the migration after a reboot: under **Network Settings**, select **Re-configure the current radio** and choose your new radio.
```

2023-07-11 14:43 UTC, puddly commented on source/_integrations/zha.markdown
> +1. Under **Overwrite Radio IEEE Address**, select the **Permanently replace the radio IEEE address** and select **Submit**. Overwriting the IEEE address may take a while. Wait.
This screen won't appear for certain types of coordinators, or for new EZSP coordinators with firmware supporting the token interface:

```suggestion
1. If your radio requires overwriting the IEEE address, you will see a screen titled **Overwrite Radio IEEE Address**. Check the **Permanently replace the radio IEEE address** box and click **Submit**. Overwriting the IEEE address may take a while.
```

2023-07-11 14:43 UTC, puddly commented on source/_integrations/zha.markdown
> +The migration process is complete. However, be aware that you will not be able to control all your existing Zigbee devices until they rejoined the Zigbee network again. Normally, they will rejoin wit
Devices don't need to re-join the network during a coordinator swap, from their perspective the coordinator just reboots:

```suggestion
The migration process is complete. However, be aware that you will not be able to control your existing Zigbee devices until the new coordinator fully joins the network. This process can take a few minutes. If some existing devices do not function after some time, try power-cycling them to allow them to re-join the network.
```

2023-07-13 09:35 UTC, c0ffeeca7 approved these changes
Thank you for your review, @puddly :pray:

2023-07-13 09:36 UTC, c0ffeeca7 approved these changes

2023-07-13 11:47 UTC, c0ffeeca7 commented
Let me fix the PR run

2023-07-13 11:48 UTC, c0ffeeca7 requested changes
Let me fix the CI failure

2023-07-13 12:01 UTC, c0ffeeca7 approved these changes

2023-07-13 18:01 UTC, puddly approved these changes

2023-07-23 09:36 UTC, frenck approved these changes

2023-07-23 09:36 UTC, merged