Add Reolink siren documentation
home-assistant/home-assistant.github.io pull request #26282
Opened 2023-02-17 07:53 UTC by starkillerOG

## Proposed change

Add Reolink siren documentation

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/88217
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-02-18 09:43 UTC, frenck requested changes

2023-02-18 09:43 UTC, frenck commented on source/_integrations/reolink.markdown
> +The siren turn on supports duration (no turn off needed) and volume options.
Some rewording suggestions:

```suggestion
If the camera supports a siren, a siren entity will be created.
When using the siren turn-on service, the siren will continue to sound until the siren turn-off service is called.

In some camera models, there is a delay of up to 5 seconds between the turn-off command and the sound stopping. The siren turn-on service supports setting a volume and a duration (no turn-off service call is needed in that case).
```

2023-02-18 09:43 UTC, frenck commented on source/_integrations/reolink.markdown
> +- The siren turn off command does not work on the Reolink NVR, you need to power cycle the NVR/camera to stop the siren. Reolink is aware of this firmware bug and is working on a solution.
```suggestion
- The siren turn-off service does not work on the Reolink NVR, you need to power cycle the NVR/camera to stop the siren. Reolink is aware of this firmware bug and is working on a solution.
```

2023-02-19 10:09 UTC, starkillerOG commented
@frenck thanks for the improvements!

2023-03-05 20:23 UTC, frenck approved these changes
Thanks, @starkillerOG 👍 

../Frenck

2023-03-05 20:24 UTC, merged