Adding Config Flow to Obihai
home-assistant/home-assistant.github.io pull request #26354
Opened 2023-02-23 22:36 UTC by ejpenney

## Proposed change

Adding config_flow to the Obihai integration, deprecate YAML configuration.  Also Adding a service, obihai.reboot which can be used to restart the Obihai from Home Assistant.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/88627
- Link to parent pull request in the Brands repository: N/A
- This PR fixes or closes issue: fixes: N/A

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-02-24 19:41 UTC, ejpenney commented
Ended up re-creating the PR because I wanted a more descriptive branch name.  Gonna have 3 docs PRs related to this feature, and who knows how long they'll take to get through, so this way I can keep better track.

2023-02-27 16:38 UTC, ejpenney commented
@dshokouhi, the code was merged. Could I pester you for a +1 here?

Edit: Not sure why asking the codeowner for a review is abuse?  Is there a different process?

2023-02-27 16:50 UTC, dshokouhi commented
@ejpenney  I do not usually review PRs in this repo and I think for Config Flow PRs there may need to be a flag at the top to indicate a config flow is added

`ha_config_flow: true`

I am also not sure if the docs should continue to mention the YAML configuration since its being deprecated.

2023-02-27 17:23 UTC, ejpenney commented
I don't think it's still mentioning the YAML config?  We still describe the three required input fields, but it's not in the context of YAML anymore.

2023-03-04 14:19 UTC, frenck requested changes

2023-03-04 14:19 UTC, frenck commented on source/_integrations/obihai.markdown
>    required: true
Configuration basic only has a `description` property on each of its items.
All others are not used or viable for use and should be removed.

2023-03-04 21:05 UTC, frenck reviewed
Thanks, @ejpenney 👍

../Frenck

2023-03-04 21:05 UTC, frenck approved these changes

2023-03-04 21:05 UTC, merged