Intellifire sleep timer
home-assistant/home-assistant.github.io pull request #26360
Opened 2023-02-24 15:19 UTC by jeeftor

## Proposed change

Adding documentation change for sleep timer in intellifire 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/88709
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-09 12:13 UTC, frenck requested changes

2023-03-09 12:13 UTC, frenck commented on source/_integrations/intellifire.markdown
> +- **Sleep timer:** `0` will disable the sleep timer. Valid values are `1-180` minutes.
That is a big contradicting?

0 will disable, but isn't a valid value?

> Valid values are `1-180` minutes.

2023-07-05 12:50 UTC, jeeftor commented on source/_integrations/intellifire.markdown
> +- **Sleep timer:** `0` will disable the sleep timer. Valid values are `1-180` minutes.
You are very right. I've updated the text

2023-12-27 09:38 UTC, closed without merging

2023-12-27 09:38 UTC, frenck commented
Closing PR as the parent PR has been closed.