Add `active_children_template` in universal
home-assistant/home-assistant.github.io pull request #26377
Opened 2023-02-27 01:33 UTC by Drafteed

## Proposed change

Docs related to core PR: https://github.com/home-assistant/core/pull/88816
I also slightly formatted the example sections.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/88816
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-09 12:10 UTC, frenck approved these changes, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2023-06-28 08:50 UTC, emontnemery requested changes
The name of the new parameter, `active_children_template` suggests plural, but the documentation suggests singular, i.e. a single active child:
> Template must return the `entity_id` of the child that will be selected as active

Which one is it?

2023-07-23 12:07 UTC, frenck commented on source/_integrations/universal.markdown
> +Using `active_child_template` will allow you to specify an active entity if the default behavior is not suitable for your task. Template must return the `entity_id` of the child that will be selected
```suggestion
Using `active_child_template` will allow you to specify an active entity if the default behavior is unsuitable for your task. The template must return the `entity_id` of the child that will be selected as active or `None` to return the default behavior.
```

2023-07-23 12:07 UTC, frenck commented on source/_integrations/universal.markdown
> +  description: "A [template](/docs/configuration/templating/) that will allow to select (override) active child. Must return the `entity_id` of the child that will be selected as active, or `None` to
```suggestion
  description: "A [template](/docs/configuration/templating/) that will allow to select (override) active child. Must return the `entity_id` of the child selected as active, or `None` to use the default behavior."
```

2023-07-23 12:15 UTC, frenck approved these changes
Thanks, @Drafteed 👍 

../Frenck

2023-07-23 12:15 UTC, merged