HELTUN partnership announcement blog post
home-assistant/home-assistant.github.io pull request #26415
Opened 2023-03-01 18:10 UTC by b-uwe

## Proposed change

Announce the HELTUN partnership in a blog post

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- This announcement follows
  - https://github.com/home-assistant/home-assistant.io/pull/26411, which again follows
  - https://github.com/home-assistant/core/pull/88892

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-01 18:37 UTC, frenck commented
Marking this as a draft for a bit, as it currently holds a date in the future.

2023-03-02 21:09 UTC, b-uwe commented
Putting it back to ready for review

2023-03-03 11:00 UTC, frenck requested changes

2023-03-03 11:00 UTC, frenck commented on source/_posts/2023-03-03-heltun-partner.markdown
> +HELTUN's thermostats, switches and switch panels integrate to Home Assistant via Z-Wave (Z-Wave stick required) completely locally so that devices react instantly to your commands which allows for th
```suggestion
HELTUN's thermostats, switches, and switch panels integrate with Home Assistant via Z-Wave (Z-Wave stick required) completely locally so that devices react instantly to your commands which allows for the best user experience with Home Assistant.
```

2023-03-03 11:00 UTC, frenck commented on source/_posts/2023-03-03-heltun-partner.markdown
> +HELTUN is an Armenian-US high tech hardware company focusing on Z-Wave based smart home and building automation solutions. The company's focus is to redefine energy management with smart programmable
```suggestion
HELTUN is an Armenian-US high-tech hardware company focusing on Z-Wave-based smart home and building automation solutions. The company's focus is to redefine energy management with smart programmable thermostats and switches, aiming to utilize the most advanced features and functionality on the market. 
```

2023-03-03 12:03 UTC, frenck approved these changes
Looks good to me, thanks @b-uwe 👍 

../Frenck

2023-03-03 12:45 UTC, merged