Add Room Support Documentation & Cleanup
home-assistant/home-assistant.github.io pull request #26491
Opened 2023-03-08 06:56 UTC by funkybunch

## Proposed change

Adding documentation for a new room targeting service in the SharkIQ integration. (will edit with PR link after it is created)
Also, some general housekeeping & cleanup. 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-09 09:22 UTC, frenck requested changes, later dismissed
Please split the cleanup from adding new documentation into separate PRs. Those are not directly related.

../Frenck

2023-03-10 18:19 UTC, funkybunch commented
Moved cleanup content into https://github.com/home-assistant/home-assistant.io/pull/26548

2024-04-22 14:58 UTC, c0ffeeca7 commented on source/_integrations/sharkiq.markdown
> +If you want to use the area selector in service's the UI, you need to format the area's name exactly as they appear in the vacuum's `Rooms` attribute.  You may also check the attribute using Home Ass
```suggestion
If you want to use the area selector in the service's UI, you need to format the area names exactly as they appear in the vacuum's `Rooms` attribute.  You may also check the attribute using Home Assistant's [Developer Tools](https://www.home-assistant.io/docs/tools/dev-tools/).
```

2024-04-22 14:58 UTC, c0ffeeca7 approved these changes, later dismissed
Thank you, @funkybunch :+1:

2024-04-22 15:00 UTC, c0ffeeca7 commented
A merge conflict emerged. Please resolve the conflict.

2024-04-23 14:18 UTC, c0ffeeca7 approved these changes

2024-04-23 14:18 UTC, merged