Clarify behaviour of counter restore option
home-assistant/home-assistant.github.io pull request #26513
Opened 2023-03-09 13:19 UTC by EKCJ

## Proposed change

When configuring a counter in `configuration.yaml`, the `restore` option  applies to `maximum`, `minimum`, `initial` and `step`, as well as the value. This makes sense as it avoids programmatic changes being lost, but is not intuitive - see https://github.com/home-assistant/core/issues/32469#

Clarification to avoid further confusion as it doesn't seem like any changes to the behaviour are being worked on.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes https://github.com/home-assistant/core/issues/32469#

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-09 17:38 UTC, frenck requested changes

2023-03-09 17:38 UTC, frenck commented on source/_integrations/counter.markdown
> +      description: Try to restore the last known value when Home Assistant starts. If this is true, future changes to `maximum`, `minimum`, `initial` and `step` can only be made using the `counter.co
To be honest, that sounds like a bug?

Have you raised an issue to verify this wasn't a bug but by design?

2023-05-08 18:17 UTC, EKCJ commented
As far as I know this behaviour is unchanged, and I appreciate that your to do list is probably extremely long @frenck . Would it make sense to make the documentation changes for now, and change it back as and when the behaviour is fixed? Unfortunately I don't have the skills to fix the issue myself.

2023-05-08 18:24 UTC, frenck commented
@EKCJ The task is planned for the upcoming release (2023.6). We are going to remove the configuration services.

2023-05-08 18:40 UTC, EKCJ commented
Fantastic, thanks.

2023-05-08 18:40 UTC, closed without merging

2023-05-08 18:51 UTC, rutiruti commented
О
--Model: rockchip,
Serial number: 011283A7CC74FCC4,
Version: 33.9-prod
Отправлено из Mail.ru для Android понедельник, 08 мая 2023г., 21:25 +03:00 от Franck Nijhof  ***@***.*** :

>@EKCJ The task is planned for the upcoming release (2023.6). We are going to remove the configuration services.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  . io/pull/26513/c1538838984 @ github . com>