Add Roborock integration
home-assistant/home-assistant.github.io pull request #26520
Opened 2023-03-09 18:38 UTC by Lash-L

## Proposed change

This is a conversion of the popular hacs integration: https://github.com/humbertogontijo/homeassistant-roborock. It aims to allow users to be able to use the Roborock app and the home assistant integration, rather than having to use the Xiaomi app.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/89456
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-09 21:24 UTC, frenck requested changes
Since a Roborock can also be controlled fully locally using the Xiaomi  integration, it might be nice to add some more information in the introduction text.

2023-03-09 21:24 UTC, frenck commented on source/_integrations/roborock.markdown
> +The `roborock` integration allows you to control your Roborock](https://us.roborock.com/pages/robot-vacuum-cleaner) vacuum.
```suggestion
The Roborock integration allows you to control your Roborock](https://us.roborock.com/pages/robot-vacuum-cleaner) vacuum.
```

2023-03-09 21:34 UTC, Lash-L commented
> Since a Roborock can also be controlled fully locally using the Xiaomi integration, it might be nice to add some more information in the introduction text.

Agreed. I will try to go through and add some more info later tonight. Thank you! I plan to try to figure out local control down the line, but it is not in the hacs integration, so it will be a bit before I get to it as I figured it made more sense to add all of those features first.

2023-03-09 22:59 UTC, Lash-L commented
> Since a Roborock can also be controlled fully locally using the Xiaomi integration, it might be nice to add some more information in the introduction text.

Added a bit more information. More than happy to add more if needed

2023-03-10 00:37 UTC, rytilahti reviewed
I think it's great to get more complete support for roborock's into homeassistant, thanks @Lash-L! Added a couple of suggestions on the wording (with my roborock-using xiaomi_miio maintainer hat on) not having tested the PR itself.

2023-03-10 00:37 UTC, rytilahti commented on source/_integrations/roborock.markdown
> +description: Instructions on how to integrate your Roborock vacuum with home assistant
```suggestion
description: Instructions on how to integrate Roborock vacuums into Home Assistant
```
I'm not sure where/if this string is used, but this should likely be in plural form?

2023-03-10 00:37 UTC, rytilahti commented on source/_integrations/roborock.markdown
> +The Roborock integration allows you to control your Roborock](https://us.roborock.com/pages/robot-vacuum-cleaner) vacuum while syncing everything from the Roborock app. The [Xiaomi Miio](https://www.
```suggestion
The Roborock integration allows you to control your Roborock](https://us.roborock.com/pages/robot-vacuum-cleaner) vacuum while keeping using the Roborock app. In contrast to [Xiaomi Miio](https://www.home-assistant.io/integrations/xiaomi_miio/) integration, this integration provides more complete support but requires cloud access and device configuration using the Roborock app.
```
Just a suggestion to reword this a bit, but I think it makes sense to clearly point out the strengths & weaknesses compared to the existing integration.

2023-03-10 00:59 UTC, Lash-L commented
> I think it's great to get more complete support for roborock's into homeassistant, thanks @Lash-L! Added a couple of suggestions on the wording (with my roborock-using xiaomi_miio maintainer hat on) not having tested the PR itself.

Thank you! I agreed with your suggestions and I went ahead and made them.

Thank you for your feedback and thank you for all of your work on the Xiaomi miio integration!

(And if your roborock-using xiaomii_miio maintainer self ever want to contribute anything on this project, you are more than welcome!)

2023-03-10 07:33 UTC, frenck commented on source/_integrations/roborock.markdown
> +The Roborock integration allows you to control your [Roborock](https://us.roborock.com/pages/robot-vacuum-cleaner) vacuum while continuing to use the Roborock app. In contrast to [Xiaomi Miio](https:
```suggestion
The Roborock integration allows you to control your [Roborock](https://us.roborock.com/pages/robot-vacuum-cleaner) vacuum while continuing to use the Roborock app.

In contrast to [Xiaomi Miio](/integrations/xiaomi_miio/) integration, this integration provides more complete support but requires cloud access and device configuration using the Roborock app.
```

2023-03-10 07:34 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2023-03-10 12:40 UTC, Lash-L commented
Appreciate you @frenck! Thanks

2023-04-22 16:52 UTC, frenck commented on source/_integrations/roborock.markdown
> +Once you login with your Roborock account, the integration will automatically discover your Roborock devices, and get the needed information to communicate locally with them. Make sure your Home Assi
```suggestion
In contrast to [Xiaomi Miio](/integrations/xiaomi_miio/) integration, this integration provides more complete support but requires cloud access to set up and device configuration using the Roborock app.

Once you log in with your Roborock account, the integration will automatically discover your Roborock devices and get the needed information to communicate locally with them. Please ensure your Home Assistant instance can communicate with the local IP of your device. We recommend setting a static IP for your Roborock Vacuum to help prevent future issues.
```

2023-04-22 16:53 UTC, frenck approved these changes
Thanks, @Lash-L 👍 

../Frenck

2023-04-22 17:08 UTC, Lash-L commented
Thanks frenck!

2023-04-22 17:17 UTC, merged