doc: virt-install in presence of USB dongle
home-assistant/home-assistant.github.io pull request #26642
Opened 2023-03-17 08:50 UTC by vlavorini

## Proposed change

Adding instructions to append the USB dongle to the Virtual Machine

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-17 09:24 UTC, frenck requested changes
The CI is failing, please make sure is passes.

2023-03-17 11:50 UTC, mrand commented
Would it be appropriate to include a small warning that USB device numbers can change when using a different USB port, or sometimes even the same USB port with number of USB devices plugged in?   This catches a number of Linux users.

2023-03-20 10:43 UTC, frenck commented on source/_includes/installation/operating_system.md
> +    you can recognize the Sonoff dongle at Bus 003 Device 003. So the command to install the VM will become:
```suggestion
    You can recognize the Sonoff dongle at `Bus 003 Device 003`. So the command to install the VM will become:
```

2023-03-20 10:52 UTC, vlavorini commented
Ok for me

2023-03-20 10:53 UTC, frenck approved these changes
Thanks, @vlavorini 👍 

../Frenck

2023-03-20 10:53 UTC, merged