Add Yellow to Getting started section
home-assistant/home-assistant.github.io pull request #26676
Opened 2023-03-21 10:01 UTC by c0ffeeca7

## Proposed change

Add Home Assistant Yellow as an option in the Getting started section.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-23 21:19 UTC, mrand commented on source/installation/yellow.html
> +                        <p>For installation instructions, checkout the <a
```suggestion
                        <p>For installation instructions, check out the <a
```

2023-03-24 02:52 UTC, c0ffeeca7 commented on source/installation/yellow.html
> +                        <p>For installation instructions, checkout the <a
Thank you for the catch, @mrand !

2023-03-26 12:11 UTC, frenck requested changes

2023-03-26 12:11 UTC, frenck commented on source/installation/yellow.html
> +                            Visit the <a href="https://www.home-assistant.io/yellow">Home Assistant Yellow product page</p>
```suggestion
                            Visit the <a href="/yellow">Home Assistant Yellow product page</p>
```

2023-03-26 12:11 UTC, frenck commented on source/installation/yellow.html
> +                                href="https://www.home-assistant.io/yellow">Home Assistant Yellow documentation</a></p>
```suggestion
                                href="/yellow">Home Assistant Yellow documentation</a></p>
```

2023-03-26 14:15 UTC, frenck approved these changes
Thanks, @c0ffeeca7 👍 

../Frenck

2023-03-26 14:15 UTC, merged