Blog for Android 2023.3
home-assistant/home-assistant.github.io pull request #26703
Opened 2023-03-23 20:02 UTC by jpelgrom

## Proposed change

Adds a blog post for the upcoming Android 2023.3 release. Specific date TBD but should be this month.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-23 20:08 UTC, balloob commented on source/_posts/2023-03-25-android-20233.markdown
> +controls. 🎉
```suggestion
It's finally here, one of the most common feature requests for the Home Assistant
Android Companion app: you can now configure multiple Home Assistant servers. The app can send sensor
updates to all servers and easily mix and match widgets, tiles and
controls for different servers 🎉
```

2023-03-23 20:08 UTC, balloob commented on source/_posts/2023-03-25-android-20233.markdown
> +devices, which allows you to quickly connect your computer to Home Assistant.
```suggestion
Plus, a preview of the Home Assistant app is now available on the Amazon Appstore on Windows 11, which allows you to quickly connect your computer to Home Assistant.
```

2023-03-24 14:37 UTC, jpelgrom commented
@frenck Could you help with a header/social image in the 'usual style' for the core releases? It appears you have the template. The app doesn't really have integrations to show, but I was thinking maybe a Windows logo and servers sheet could work.
[assets.zip](https://github.com/home-assistant/home-assistant.io/files/11063312/assets.zip)

2023-03-27 10:07 UTC, frenck requested changes

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +app can send sensor updates to all servers and easily mix and match widgets, tiles
```suggestion
app can send sensor updates to all servers and easily mix and match widgets, tiles,
```

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +for features in the latest Home Assistant releases, so let's dig in to the update!
```suggestion
for features in the latest Home Assistant releases, so let's dig into the update!
```

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +hassle. Switching apps, creating bookmarks, using different profiles. Let alone
```suggestion
hassle. Switching apps, creating bookmarks, and using different profiles. Let alone
```

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +This issue now belongs to the past, as there's a new option in [Settings] >
```suggestion
This issue now belongs to the past, as there's a new option in **{% my config title="Settings" %}** >
```

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +Companion app to configure  a second server, and another one after that, and another...
```suggestion
**Companion app** to configure a second server, and another one after that, and another...
```

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +expect like lots of sensors for your device and support for push notifications.
```suggestion
expect, like lots of sensors for your device and support for push notifications.
```

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +That's not all - you can use all servers _outside_ the app as well, mixing and
```suggestion
That's not all - you can also use all servers _outside_ the app, mixing and
```

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +via the Amazon Appstore. While there are already great options to integrate your
```suggestion
The Home Assistant Android Companion app is now available via the Amazon Appstore
on [supported Windows 11 devices]. While there are already great options to integrate your
```

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +computer out there from the community, the Companion app makes it easy to start
```suggestion
computer from the community out there, the Companion app makes it easy to start
```

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +TODO: link to Microsoft Store
TODO

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +The Home Assistant app has been available for a bit over a year now on Wear OS
```suggestion
The Home Assistant app has been available for over a year now on Wear OS
```

2023-03-27 10:07 UTC, frenck commented on source/_posts/2023-03-25-android-20233.markdown
> +watches, and continues to improve. Earlier this year initial support for Assist was
```suggestion
watches and continues to improve. Earlier this year, initial support for Assist was
```

2023-03-27 10:18 UTC, frenck commented
> @frenck Could you help with a header/social image in the 'usual style' for the core releases?

Sure! Here you go:

![Home Assistant - Blog - Android 2023 3](https://user-images.githubusercontent.com/195327/227914033-f3b664d7-0ed7-448d-8b70-197fd73771a2.png)

If you want a different one, or need changes, feel free to reach out (here or on Discord).

2023-03-27 16:16 UTC, jpelgrom commented
Thanks for the comments. Image looks better than expected, no changes needed!

2023-03-29 17:33 UTC, jpelgrom commented on source/_posts/2023-03-25-android-20233.markdown
> +TODO: link to Microsoft Store
Removed as it doesn't look like deeplinks are available

2023-03-30 22:16 UTC, dshokouhi commented
Update is now live in the play store :)

2023-03-30 23:20 UTC, dshokouhi approved these changes, later dismissed
Looks good to me! Great stuff this release!!!!

2023-03-31 00:29 UTC, balloob approved these changes

2023-03-31 00:34 UTC, merged