Add character_encoding doc to REST and Scrape
home-assistant/home-assistant.github.io pull request #26730
Opened 2023-03-26 11:44 UTC by olivierouellet

## Proposed change

Add documentation for a new configuration variable character_encoding.
Related to PR [#90254](https://github.com/home-assistant/core/pull/90254)

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [#90254](https://github.com/home-assistant/core/pull/90254)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-26 12:04 UTC, frenck approved these changes, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2023-03-26 19:22 UTC, gjohansson-ST requested changes
Adjust to match core PR

2023-03-26 19:22 UTC, gjohansson-ST commented on source/_integrations/rest.markdown
> +character_encoding:
```suggestion
encoding:
```

2023-03-26 19:22 UTC, gjohansson-ST commented on source/_integrations/scrape.markdown
> +character_encoding:
```suggestion
encoding:
```

2023-03-28 11:05 UTC, gjohansson-ST approved these changes

2023-03-28 11:09 UTC, frenck requested changes
Thanks, @olivierouellet 👍 

../Frenck

2023-03-28 11:09 UTC, frenck approved these changes
Now with the right button! (Darn UI changes :P)

2023-03-28 11:10 UTC, merged