Remove frontier_silicon from discovery integration
home-assistant/home-assistant.github.io pull request #26753
Opened 2023-03-28 06:38 UTC by wlcrs

## Proposed change

Discovery of Frontier Silicon devices moved from `discovery` plugin to its own config flow.

Additionally, upon reviewing the code I noticed that a few other integrations were already migrated, but did not update the documentation.
I thus also remove following services:
- bose_soundtouch due to https://github.com/home-assistant/core/commit/273e9b287f482f5d1f0718ebf09a56c49c66513d
- lg_smart_device due to https://github.com/home-assistant/core/commit/5fa3b90b2ca309cab3ee03d2a27bf6aaa4dc5a68
- sabnzbd due to https://github.com/home-assistant/core/commit/3f5027834b2334eaf5eaab7884376b3cfb089a63

cfr. https://github.com/home-assistant/core/blob/dev/homeassistant/components/discovery/__init__.py#L60-L66

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/89496
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-03-28 09:48 UTC, frenck requested changes
This PR is linked to a core PR, and should only make changes that are directly related to the linked core PR.

Another improvement should be done in its own/separate PR.

../Frenck

2023-03-28 09:48 UTC, frenck commented on source/_integrations/discovery.markdown
> - * [SABnzbd downloader](/integrations/sabnzbd)
Unrelates changes, please move those out of this PR

2023-03-28 09:59 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2023-03-29 08:02 UTC, bdraco approved these changes

2023-03-29 08:02 UTC, merged