Documenting additional Supla channels
home-assistant/home-assistant.github.io pull request #26850
Opened 2023-04-03 14:43 UTC by alh84001

## Proposed change

This update is reflecting changes made in https://github.com/home-assistant/core/pull/90723 - support for DIMMER and RGBLIGHTING channels.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/90723
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-04-03 19:26 UTC, klaasnicolaas requested changes

2023-04-03 19:26 UTC, klaasnicolaas commented on source/_integrations/supla.markdown
> +Currently supported channel types are:
```suggestion
Currently supported channel types are:

```

2023-04-03 19:51 UTC, klaasnicolaas approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

2024-03-20 08:20 UTC, frenck commented
Closing PR as the linked parent PR has been closed.

2024-03-20 08:20 UTC, closed without merging