Romy
home-assistant/home-assistant.github.io pull request #26948
Opened 2023-04-11 11:58 UTC by xeniter

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/91194 
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/4293  
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-04-11 12:17 UTC, klaasnicolaas requested changes
See also the errors that textlint returns

2023-04-11 12:17 UTC, klaasnicolaas commented on source/_integrations/romy.markdown
> +  required: true
```suggestion
  required: true
  default: 8080
```

2023-04-11 12:17 UTC, klaasnicolaas commented on source/_integrations/romy.markdown
> +  - host: 12345678
This seems to be incorrect YAML config

2023-04-12 07:57 UTC, xeniter commented on source/_integrations/romy.markdown
> +  - host: 12345678
ups, was not aware that it didn't work at all anymore and is not wanted anymore
removed description now completly

https://github.com/home-assistant/architecture/blob/master/adr/0010-integration-configuration.md#decision
[homeassistant.components.vacuum] The romy platform for the vacuum integration does not support platform setup. Please remove it from your config.

2023-05-29 14:19 UTC, frenck commented
Closing PR as the parent Core PR has been closed.

../Frenck

2023-05-29 14:19 UTC, closed without merging