Add service `vacuum_reset_consumable` for xiaomi_miio
home-assistant/home-assistant.github.io pull request #27020
Opened 2023-04-16 02:11 UTC by zry98

## Proposed change

Add service call `vacuum_reset_consumable` to reset consumable status (e.g., main brush work time) of Xiaomi vacuum cleaners, no longer need to use MiHome app to do that.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/91483
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-04-16 08:30 UTC, azogue commented
@zry98, it looks like one unrelated commit to source/_integrations/zwave_js.markdown got mixed in this PR when redirecting to 'next' instead of 'current', please clean the branch 👍

2023-04-16 08:42 UTC, zry98 commented
> @zry98, it looks like one unrelated commit to source/_integrations/zwave_js.markdown got mixed in this PR when redirecting to 'next' instead of 'current', please clean the branch 👍

I think I've messed up the branch, I shouldn't have used the `current` branch for docs of new features, right?

2023-04-16 12:09 UTC, frenck requested changes
It seems like your branch was based on `current` and not the `next` branch. Please git rebase your changes onto the next branch to clean it up.

../Frenck

2023-04-16 12:09 UTC, frenck commented on source/_integrations/xiaomi_miio.markdown
> +### Service `xiaomi_miio.vacuum_reset_consumable`
As per comment on the linked Core PR. These should become buttons, not services.

2023-04-16 12:09 UTC, frenck commented on source/_integrations/zwave_js.markdown
> +## Z-Wave terminology
Unrelated

2023-04-17 16:00 UTC, zry98 commented
Messed up branches, closing it to open a new one with `next` branch.

2023-04-17 16:00 UTC, closed without merging