Add "state x days ago" query
home-assistant/home-assistant.github.io pull request #27028
Opened 2023-04-16 19:23 UTC by Marquo1

I think a sensor showing a state 1 day ago is potentially a common use case and should be in the docs to promote its use.

I did not write the query, it comes from: https://community.home-assistant.io/t/sensor-state-24-h-ago/524994/13?u=marquo 
Since I lack knowledge and don't want to ruin it, I copied it without changing the formatting. Please adjust if needed.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-04-17 08:01 UTC, frenck requested changes

2023-04-17 08:01 UTC, frenck commented on source/_integrations/sql.markdown
> +If you want to extract the state of entity from a day, hour or minute ago, the query is:
```suggestion
If you want to extract the state of an entity from a day, hour, or minute ago, the query is:

```

2023-04-17 08:01 UTC, frenck commented on source/_integrations/sql.markdown
> +ORDER BY last_updated_ts DESC LIMIT 1;
Can we format the SQL query just like all other queries on this page? It will help with readability.

2023-04-17 08:01 UTC, frenck commented on source/_integrations/sql.markdown
> +Replace  `-1 day` with the target offset, e.g. `-1 hour`.
```suggestion

Replace `-1 day` with the target offset, for example, `-1 hour`.
```

2023-04-17 11:25 UTC, Marquo1 commented on source/_integrations/sql.markdown
> +ORDER BY last_updated_ts DESC LIMIT 1;
I lack knowledge about query structure to make correct indentations myself

2023-05-01 10:35 UTC, Marquo1 commented on source/_integrations/sql.markdown
> +ORDER BY last_updated_ts DESC LIMIT 1;
Done

2023-05-01 11:30 UTC, gjohansson-ST requested changes

2023-05-01 11:30 UTC, gjohansson-ST commented on source/_integrations/sql.markdown
> +  state
```suggestion
  states.state
```

2023-05-01 11:30 UTC, gjohansson-ST commented on source/_integrations/sql.markdown
> +LIMIT 1;
```suggestion
LIMIT
  1;
```

2023-05-01 19:47 UTC, gjohansson-ST approved these changes

2023-05-29 14:37 UTC, frenck approved these changes
Thanks, @Marquo1 👍 

../Frenck

2023-05-29 14:37 UTC, merged