remove latest-release-notes from indexation
home-assistant/home-assistant.github.io pull request #27038
Opened 2023-04-17 14:40 UTC by bemble

## Proposed change

Right now, `/latest-release-notes/` is a simple HTML page that redirect to the latest release note. This page is included in the sitemap and Google indexation bot goes through this page. We recently had an indexation issue, where the selected `/latest-release-notes/` as canical URL instead of the right one (the link is in the "Recent Posts" section given page): 
<img width="928" alt="Capture d’écran 2023-04-17 à 16 22 19" src="https://user-images.githubusercontent.com/397503/232515000-c69862b7-83ea-4e66-bb19-8ba51e78ac9a.png">

Usage of `/latest-release-notes/` should be avoided:
- on the `index.html`, release note link points directly to the latest core blog post
- the link in different blog post has been changed to the corresponding link
- the redirection is now done by netlify in the `_redirect` (status `302`)
- `/latest-release-notes/` is not in the `sitemap.xml` anymore

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-04-17 15:22 UTC, frenck requested changes

2023-04-17 15:22 UTC, frenck commented on source/_posts/2020-02-19-community-highlights.markdown
> +Today we are releasing the first beta of Home Assistant Core 0.106. It is packed with awesome features. For a sneak peek of what is coming, check the [beta release notes](https://rc.home-assistant.io
There is no point in linking to the beta website anymore, let's just point it at the current stable one

```suggestion
Today we are releasing the first beta of Home Assistant Core 0.106. It is packed with awesome features. For a sneak peek of what is coming, check the [beta release notes](/blog/2020/02/26/release-106/).
```

2023-04-17 15:22 UTC, frenck commented on source/_posts/2020-03-15-community-highlights.markdown
> +[beta, sneak peak?](https://rc.home-assistant.io/blog/2020/03/18/release-107/)).
```suggestion
[beta, sneak peak?](/blog/2020/03/18/release-107/)).
```

2023-04-17 15:22 UTC, frenck commented on source/index.html
> +        <span class="release-date">{{ site.date_released | date: "%B %e, %Y" }}</span>
Unrelated change?

2023-04-17 15:22 UTC, frenck commented on source/index.html
> +      <a class="material-card highlight-blog-post" href="/blog/2016/01/19/perfect-home-automation/">
Everything below here in this file seems to be unrelated?

2023-04-17 17:40 UTC, bemble commented on source/index.html
> +        <span class="release-date">{{ site.date_released | date: "%B %e, %Y" }}</span>
It's an automated code reformat on save, but nothing related to this PR directly yes.

2023-04-17 17:40 UTC, bemble commented on source/index.html
> +      <a class="material-card highlight-blog-post" href="/blog/2016/01/19/perfect-home-automation/">
Same as above.

2023-04-22 20:31 UTC, frenck commented on source/index.html
> +        <span class="release-date">{{ site.date_released | date: "%B %e, %Y" }}</span>
Those have caused issues on this website. Please revert this unrelated change.

2023-04-22 20:32 UTC, frenck requested changes
Please rever the unrelated changes.

2023-04-24 17:18 UTC, frenck approved these changes
Thanks, @bemble 👍 

../Frenck

2023-04-24 17:19 UTC, merged