Z-Wave controllers on Yellow: Add additional modules to list
home-assistant/home-assistant.github.io pull request #27037
Opened 2023-04-17 12:55 UTC by c0ffeeca7

## Proposed change

Procedure on how to setup a -Z-Wave module on Yellow:
- Tested setup with additional modules
- added modules to procedure

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-04-17 13:16 UTC, AlCalzone requested changes

2023-04-17 13:16 UTC, AlCalzone commented on source/_docs/z-wave/controllers.markdown
>  1. Make sure the Aeotec Z-Pi 7 is properly seated on the Home Assistant Yellow.
```suggestion
1. Make sure the module is properly seated on the Home Assistant Yellow. 
```

2023-04-17 13:16 UTC, AlCalzone commented on source/_docs/z-wave/controllers.markdown
>     ![Aeotex Z-Pi 7 on Home Assistant Yellow](/images/docs/z-wave/zpi-7-yellow.jpg).
```suggestion
   ![Aeotec Z-Pi 7 on Home Assistant Yellow](/images/docs/z-wave/zpi-7-yellow.jpg).
```

2023-04-17 13:23 UTC, c0ffeeca7 commented
Thank you for the catch, @AlCalzone!

2023-04-17 13:30 UTC, AlCalzone approved these changes

2023-04-18 17:52 UTC, MartinHjelmare approved these changes

2023-04-18 17:55 UTC, merged