Update freebox.markdown
home-assistant/home-assistant.github.io pull request #27194
Opened 2023-04-28 16:56 UTC by nachonam

Add entries for Freebox sensors and alarm panel

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/92196
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-07-04 06:51 UTC, frenck requested changes

2023-07-04 06:51 UTC, frenck commented on source/_integrations/freebox.markdown
> +* [Binary sensors](#binary)
A parent PR may not contain multiple platforms in a single PR.

2023-07-04 06:51 UTC, frenck commented on source/_integrations/freebox.markdown
> +*
Stale bullet point?

2023-09-27 14:15 UTC, Quentame submitted a review, later dismissed

2023-09-27 14:18 UTC, Quentame approved these changes

2023-09-27 15:11 UTC, frenck approved these changes

2023-09-27 15:11 UTC, merged