Add Enocean 1BS/D5-00-01 "WindowSensor" Device
home-assistant/home-assistant.github.io pull request #27190
Opened 2023-04-28 11:13 UTC by philippaul23

Added code to "sensor.py" to support an additional EEP.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-05-08 12:48 UTC, c0ffeeca7 requested changes

2023-05-08 12:48 UTC, c0ffeeca7 commented on source/_integrations/enocean.markdown
> +The window sensor is tested with the NodON SDO-2-1-05 reed sensor which uses 1BS telegrams with EEP D5-00-01
``` suggestion
The window sensor is tested with the NodON SDO-2-1-05 reed sensor, which uses 1BS telegrams with EEP D5-00-01.
```

2023-05-08 12:49 UTC, c0ffeeca7 commented on source/_integrations/enocean.markdown
> +The window sensor is tested with the NodON SDO-2-1-05 reed sensor which uses 1BS telegrams with EEP D5-00-01
One tiny tweak. Looks good otherwise.

2023-09-26 08:03 UTC, closed without merging

2023-09-26 08:03 UTC, frenck commented
Closing PR as the parent PR has been closed.