Bot permission granting in Discord integration doc
home-assistant/home-assistant.github.io pull request #27230
Opened 2023-05-02 14:08 UTC by anthonymag

## Proposed change
Explaining in the Discord integration documentation how to adjust the bot's permissions during the initial configuration.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
Hello, and thanks for considering this PR! During my setting up of the Discord integration, I was having trouble getting messages to appear in my Discord and only later discovered it was because the bot lacked permissions. This step is not currently documented which hopefully I can solve.

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-05-03 17:09 UTC, dannytsang commented
I don't seem to have an issue with this. My bot app is set to 0 and I am still getting posts in Discord. Anyone else confirm this?

2023-05-04 06:54 UTC, dannytsang requested changes

2023-05-04 06:54 UTC, dannytsang commented on source/_integrations/discord.markdown
> +</p>
Please change to Markdown image syntax instead of HTML.

2023-05-04 14:19 UTC, anthonymag commented on source/_integrations/discord.markdown
> +</p>
Thanks, done and went ahead and updated the other images as well.

2023-05-04 14:21 UTC, anthonymag commented
> I don't seem to have an issue with this. My bot app is set to 0 and I am still getting posts in Discord. Anyone else confirm this?

That is odd; I can say that changing this one step finally got it working for me whereas before I was having nothing post to my channels.

2023-05-06 00:47 UTC, dannytsang commented
Changes look good.

@frenck could you advise what to do in this case where there's a difference in setup (see above) please.

2023-05-11 07:06 UTC, frenck commented
> Changes look good.
> 
> @frenck could you advise what to do in this case where there's a difference in setup (see above) please.

It really depends on what permissions you want your bot the have on the server. I think this makes sense in a way, as it helps with giving it whatever permission they prefer.

I don't see a direct blocker to not merge this in 👍 

../Frenck

2023-05-11 07:17 UTC, dannytsang approved these changes
Thanks @anthonymag

2023-05-11 07:17 UTC, merged