Slow pwm
home-assistant/home-assistant.github.io pull request #27380
Opened 2023-05-12 15:48 UTC by antonverburg

## Proposed change
Add documentation for new integration 'slow_pwm' 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: will follow
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/4371
- This PR fixes or closes issue: fixes #

## Checklist
- [ x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-05-15 19:23 UTC, c0ffeeca7 requested changes
Thank you, @antonverburg :+1: 
just a few minor typos.

2023-05-15 19:23 UTC, c0ffeeca7 commented on source/_integrations/slow_pwm.markdown
> +The switches will be controlled by Pulse-Width-Manipulation (PWM, See https://en.wikipedia.org/wiki/Pulse-width_modulation).
```suggestion
The switches will be controlled by pulse width modulation (PWM, see https://en.wikipedia.org/wiki/Pulse-width_modulation). 
```
I realize that Wikipedia spells it differently. I went for the spelling used by [Marriam Webster](https://www.merriam-webster.com/dictionary/pulse%20width%20modulation), which I find to be a reliable resource.

2023-05-15 19:23 UTC, c0ffeeca7 commented on source/_integrations/slow_pwm.markdown
> +This enables the usage of digital switches in modulated modes. This is typically useful in slow systems like floorheater or boiler heater controller systems. The [PID controller](/integrations/pid_co
```suggestion
This enables the usage of digital switches in modulated modes. This is typically useful in slow systems like floor heater or boiler heater controller systems. The [PID controller](/integrations/pid_controller) and the [PID thermostat](/integrations/pid_thermostat)  can use this number as regulated output. 
```

2023-05-15 19:23 UTC, c0ffeeca7 commented on source/_integrations/slow_pwm.markdown
> +  description: One or more output switches. When multiple outputs are selected, the range of 0..100% will be shared over the multiple switches. For example, with 2 switches at 50% output only the fir
```suggestion
  description: One or more output switches. When multiple outputs are selected, the range of 0..100% will be shared over the multiple switches. For example, with 2 switches at 50% output, only the first switch will be on full time, at 75% the first switch will be on 100% of the time, and the second 50%.
```

2023-05-15 19:23 UTC, c0ffeeca7 commented on source/_integrations/slow_pwm.markdown
> +  description: Shortest possible time a switch should be on- or off. This parameter is typically useful in slow switching applications like the wax-valve of domestic heater systems.
```suggestion
  description: Shortest possible time a switch should be on or off. This parameter is typically useful in slow-switching applications like the wax valve of domestic heater systems.
```
The hyphenation here reflects my personal preference. I'm not sure there is an exact rule, see [Merriam Webster](https://www.merriam-webster.com/words-at-play/spelling-using-compound-words-guide)

2023-05-15 19:23 UTC, c0ffeeca7 commented on source/_integrations/slow_pwm.markdown
> +  default: {'minutes':30}
```suggestion
  default: "{'minutes': 30}"
```
I'm not 100% sure, but this might fix the pipeline run.

2023-05-15 19:23 UTC, c0ffeeca7 commented on source/_integrations/slow_pwm.markdown
> +description: Convert one or multiple switches to a numeric input using slow Pulse-Width-Modulation
```suggestion
description: Convert one or multiple switches to a numeric input using slow pulse width modulation
```

2023-05-16 11:37 UTC, c0ffeeca7 commented on source/_integrations/slow_pwm.markdown
> +  description: One or more output switches. When multiple outputs are selected, the range of 0..100% will be shared over the multiple switches. For example, with 2 switches at 50% output, only the fi
```suggestion
  description: >
    `entity_id`'s for switches, must be toggle devices. When multiple outputs are selected, the range of 0..100% will be shared over the multiple switches. For example, with 2 switches at 50% output only the first switch will be on full time, at 75% the first switch will be on 100% of the time, and the second 50%.
```
Not sure if I managed to paste this correctly. But I think there was a formatting issue. I believe it should look like this
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/038fbb90-865d-4e1e-ae6c-2f18d0f251ad)

2023-05-16 11:37 UTC, c0ffeeca7 commented on source/_integrations/slow_pwm.markdown
> +  type: multiple strings
```suggestion
  type: string
```
My VS Code tells me _multiple strings_ is not a supported type. Did you mean _string_, maybe?

2023-05-16 11:37 UTC, c0ffeeca7 commented on source/_integrations/slow_pwm.markdown
> +  type: time_period
```suggestion
  type: time
```
My VS Code tells me _time_period_ is not a supported type. Did you mean _time_, maybe?

2023-05-17 06:33 UTC, antonverburg commented on source/_integrations/slow_pwm.markdown
> +  type: time_period
Time is not correct, it should be a time_period. I think the time_period does exist, but in this sentence I should indeed not use a time_period, as the formatting of a time period is 'hh:mm:ss', I use the formatting '{minutes: NN}' to be compatible with the config_flow formatting. In my code I use the cv-check 'cv.time_period_dict', in the python code it is converted to a timeperiod. Can you give both a try in VS Code (I use a simple plain text editor)?

2023-05-17 06:52 UTC, frenck requested changes

2023-05-17 06:52 UTC, frenck commented on source/_integrations/slow_pwm.markdown
> +  - platform: slow_pwm
This is old-style platform configuration, which is no longer allowed to be introduced. See ADR-0007: <https://github.com/home-assistant/architecture/blob/master/adr/0007-integration-config-yaml-structure.md>

2023-05-17 06:52 UTC, frenck commented on source/_integrations/slow_pwm.markdown
> +    name: Floorheater living room
Doesn't match our YAML style guide: <https://developers.home-assistant.io/docs/documenting/yaml-style-guide>

2023-05-17 06:52 UTC, frenck commented on source/_integrations/slow_pwm.markdown
> +The `slow_pwm` platform is a `number`. It can be used to control one or multiple digital switches in an analog control algorithm.
We don't allow the creation of new platform integrations anymore.

Suggested: The SlowPWM integration can be used to control...

2023-05-17 06:52 UTC, frenck commented on source/_integrations/slow_pwm.markdown
> +## Configuration
This header is already provided by the include below, did you test this before opening the PR?

2023-05-17 06:52 UTC, frenck commented on source/_integrations/slow_pwm.markdown
> +```yaml
This YAML example doesn't match our YAML style guides, please make sure the styling matches.

2023-05-17 06:53 UTC, frenck commented on source/_integrations/slow_pwm.markdown
> +  type: multiple strings
There is no such things as multiple strings indeed. This should be a `list`.

2023-06-01 17:50 UTC, frenck commented
Closing PR as the parent PR has been closed.

2023-06-01 17:50 UTC, closed without merging