Add formatting note for Reusable Templates Formatting
home-assistant/home-assistant.github.io pull request #27401
Opened 2023-05-14 20:30 UTC by SirGoodenough

## Proposed change

This was pointed out to me on Discord, and I offered to extend the documentation to include the information.

QUOTE:
TheFes — 05/12/2023 1:05 PM
Important to know:

    The result of an imported macro is always a string
    If you don't add a hyphen to all your opening and closing tags (so use {%-, -%}, {{- and -}}) you're result will include unintended whitespace.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

https://discord.com/channels/330944238910963714/672223497736421388/1106643448943095938

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-05-15 05:41 UTC, c0ffeeca7 requested changes

2023-05-15 05:41 UTC, c0ffeeca7 commented on source/_docs/configuration/templating.markdown
> +1. The value returned is always a string.  If you want a number or a boolean you need to use ```|int()```, ```|float(),``` or ```|bool``` filters.
```suggestion
1. The value returned is always a string.  If you want a number or a boolean, you need to use ```|int()```, ```|float(),``` or, ```|bool``` filters.
```

2023-05-15 05:41 UTC, c0ffeeca7 commented on source/_docs/configuration/templating.markdown
> +1. If you don't add a hyphen to all your opening and closing tags (so use `{%-`, `-%}`, `{{-`, and `-}}`) you're result will include unintended whitespace.
```suggestion
1. If you don't add a hyphen to all your opening and closing tags (so use `{%-`, `-%}`, `{{-`, and `-}}`), your result will include unintended whitespace.
```

2023-05-15 06:23 UTC, frenck commented
Hoe if this different from any other template? 🤷‍♂️

2023-05-27 02:04 UTC, SirGoodenough commented on source/_docs/configuration/templating.markdown
> +1. The value returned is always a string.  If you want a number or a boolean you need to use ```|int()```, ```|float(),``` or ```|bool``` filters.
agree

2023-05-27 02:04 UTC, SirGoodenough commented on source/_docs/configuration/templating.markdown
> +1. If you don't add a hyphen to all your opening and closing tags (so use `{%-`, `-%}`, `{{-`, and `-}}`) you're result will include unintended whitespace.
agree

2023-05-29 15:31 UTC, frenck commented on source/_docs/configuration/templating.markdown
> +1. If you don't add a hyphen to all your opening and closing tags (so use `{%-`, `-%}`, `{{-`, and `-}}`) you're result will include unintended whitespace.
This is not specific to re-using templates, but general information on the Jinja2 syntax that is put here. But putting it here, it seems like this is something specific to the marco's, which it is not.

../Frenck

2023-06-15 16:15 UTC, SirGoodenough commented on source/_docs/configuration/templating.markdown
> +1. If you don't add a hyphen to all your opening and closing tags (so use `{%-`, `-%}`, `{{-`, and `-}}`) you're result will include unintended whitespace.
It's specific in this use case because the casual operator may be expecting say a boolean returned or a number or a list, and that's not what they will be getting.  Only returns a string.  I used these words as that was what someone on the HA Discord helped me with.  So if not these exact words, some reminder that it returns a string would be very helpful to the prople that need the docs to use the feature.

2023-08-17 23:15 UTC, closed without merging