Kodi keypress device triggers
home-assistant/home-assistant.github.io pull request #27475
Opened 2023-05-21 14:06 UTC by starkillerOG

## Proposed change

Add documetation for Kodi keypress device triggers, see PR: https://github.com/home-assistant/core/pull/93321

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/93321
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-05-25 09:11 UTC, emontnemery requested changes
This needs to be updated to reflect the changes in the parent PR

2023-05-25 09:44 UTC, starkillerOG commented
@emontnemery I made the changes needed.
However the checks fail with:
`Liquid Exception: Liquid syntax error (line 422): Expected end_of_string but found comparison in "{{trigger.event.data.data.key == "volume_up"}}" in /opt/build/repo/source/_integrations/kodi.markdown`
Do you know how to resolve that?

2023-05-30 06:46 UTC, frenck commented on source/_integrations/kodi.markdown
> +A example of a automation to turn up/down the volume of a receiver using the event:
```suggestion
A example of a automation to turn up/down the volume of a receiver using the event:

{% raw %}

```

2023-05-30 06:47 UTC, frenck commented on source/_integrations/kodi.markdown
> +```
````suggestion
```

{% endraw %}
````

2023-05-30 07:29 UTC, frenck commented on source/_integrations/kodi.markdown
> +key presses of keyboards/remotes can be overwritten in Kodi and configured to send a event to Home Assistant, which can then be used in automations to for instance turn up/down the volume of a TV/rec
```suggestion

key presses of keyboards/remotes can be overwritten in Kodi and configured to send an event to Home Assistant, which can then be used in automations to, for instance, turn up/down the volume of a TV/receiver.
```

2023-05-30 07:29 UTC, frenck commented on source/_integrations/kodi.markdown
> +A example of the Kodi keymap configuration using XML which will overwrite the volume_up/volume_down buttons and instead send a event to HomeAssistant:
```suggestion
An example of the Kodi keymap configuration using XML, which will overwrite the volume_up/volume_down buttons and instead send an event to HomeAssistant:

```

2023-05-30 07:29 UTC, frenck commented on source/_integrations/kodi.markdown
> +For the example abbove, when the volume up key is pressed, a event in Home Assistant will be fired that looks like:
```suggestion

The `"KodiLivingroom"` can be set to any value and will be present in the event data as the `"sender"`
The `"OnKeyPress"` is needed to identify the event in Home Assistant, do not change this.
The `{"key":"volume_up"}` can contain any JSON which will be present in the event data under the `"data"` key, normally this is used to identify which key was pressed.

For possible keyboard key names, see: https://kodi.wiki/view/List_of_keynames
For other actions, see: https://kodi.wiki/view/Keymap#Keynames

For the example above, when the volume up key is pressed, an event in Home Assistant will be fired that looks like this:
```

2023-05-30 07:48 UTC, frenck approved these changes
Thanks, @starkillerOG 👍 

../Frenck

2023-05-30 07:48 UTC, merged

2023-05-30 08:38 UTC, starkillerOG commented
@frenck thank you very much for fixing the CLI and the tweaks!
Could not figure it out.

2023-05-30 08:39 UTC, frenck commented
No problem at all 👍