add bangolufsen documentation
home-assistant/home-assistant.github.io pull request #27507
Opened 2023-05-24 14:27 UTC by mj23000

## Proposed change
Add documentation for the bangolufsen integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/93462
- Link to parent pull request in the Brands repository: already added https://github.com/home-assistant/brands/pull/3877 https://github.com/home-assistant/brands/pull/3879
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-07-04 09:56 UTC, klaasnicolaas requested changes

2023-07-04 09:56 UTC, klaasnicolaas commented on source/_integrations/bangolufsen.markdown
> +ha_release: 2023.6.0
```suggestion
ha_release: 2023.8
```

2023-08-09 07:48 UTC, edenhaus requested changes
Please create a new PR in the brand's repo, where you copy the images from `custom_integrations` to `core_integrations`.

2023-08-16 09:44 UTC, mj23000 commented
> Please create a new PR in the brand's repo, where you copy the images from `custom_integrations` to `core_integrations`.
I have now done this.
https://github.com/home-assistant/brands/pull/4605

2023-12-20 10:24 UTC, jpbede commented
Closing this as it was based of the wrong branch so it has tagged a lot of people.
Please open a new PR based on `next`

2023-12-20 10:24 UTC, closed without merging