Piper: show how to use Piper TTS with media player in automation
home-assistant/home-assistant.github.io pull request #27523
Opened 2023-05-25 15:46 UTC by c0ffeeca7

## Proposed change

Piper: show how to use Piper TTS with media player in automation
- Add procedure on how Piper can be used for local text-to-speech processing with a media player
- Addresses the issue mentioned in https://github.com/home-assistant/addons/issues/3034

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-06-06 06:36 UTC, frenck requested changes

2023-06-06 06:36 UTC, frenck commented on source/voice_control/using_tts_in_automation.markdown
> +        media_content_id: media-source://tts/tts.piper?message=Your+coffee+is+ready%21+Enjoy.
Indentation got lost here, rendering this YAML invalid.

2023-06-08 08:55 UTC, frenck requested changes

2023-06-08 08:55 UTC, frenck commented on source/voice_control/using_tts_in_automation.markdown
> +          media_content_id: media-source://tts/tts.piper?message=Your+coffee+is+ready%21+Enjoy.
```suggestion
      media_content_id: media-source://tts/tts.piper?message=Your+coffee+is+ready%21+Enjoy.
      media_content_type: provider
    metadata:
      title: Your coffee is ready! Enjoy.
      thumbnail: https://brands.home-assistant.io/_/tts/logo.png
      media_class: app
      children_media_class: null
      navigateIds:
          - {}
          - media_content_type: app
            media_content_id: media-source://tts
          - media_content_type: provider
            media_content_id: media-source://tts/tts.piper?message=Your+coffee+is+ready%21+Enjoy.
```

2023-06-08 08:55 UTC, frenck commented on source/voice_control/using_tts_in_automation.markdown
> +    entity_id: media_player.m5stack_atom_echo_a61920
```suggestion
      entity_id: media_player.m5stack_atom_echo_a61920
```

2023-06-08 09:06 UTC, c0ffeeca7 commented
Thank you for your help, @frenck

2023-06-08 09:27 UTC, frenck approved these changes

2023-06-08 09:27 UTC, merged