Voice control create separate section in docs
home-assistant/home-assistant.github.io pull request #27586
Opened 2023-05-30 11:51 UTC by c0ffeeca7

## Proposed change

Voice control: create separate section in docs
- Move voice control related sections from Docs page to its own proper page

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-05-31 12:49 UTC, balloob commented on source/_includes/asides/docs_navigation.html
>            <li>{% active_link /projects/worlds-most-private-voice-assistant/ Tutorial: World's most private voice assistant %}</li>
why not move these over?

2023-05-31 12:49 UTC, balloob commented on source/_includes/asides/docs_navigation.html
> -          <li>{% active_link /docs/assist/android/ Assist for Android %}</li>
If you change URLs, you need to update the `redirect` file to make sure all old URLs keep working.

2023-05-31 12:50 UTC, balloob commented on source/_includes/asides/docs_navigation.html
> +        <b>{% active_link /voice/ Assist %}</b>
We need to be consistent in our naming. If top-level is called "Voice Control", should it be called "Voice Control" here too ?

2023-05-31 12:51 UTC, balloob commented on source/voice/index.markdown
> -Assist is our feature to allow you to control Home Assistant using natural language. It is built on top of an open voice foundation and powered by knowledge provided by our community. You can use the
Since we link to this page from "Voice Control", people might come here when looking for Alexa/Google, so in that case, let's link them to HA Cloud.

2023-05-31 13:51 UTC, c0ffeeca7 reviewed
find replace errors

2023-05-31 13:51 UTC, c0ffeeca7 commented on source/_integrations/conversation.markdown
> +By default, a collection of [community contributed sentences](https://github.com/home-assistant/intents/) are supported in a growing [list of languages](https://developers.home-assistant.io/docs/voic
```suggestion
By default, a collection of [community contributed sentences](https://github.com/home-assistant/intents/) are supported in a growing [list of languages](https://developers.home-assistant.io/docs/voice/intent-recognition/supported-languages).
```

2023-05-31 13:51 UTC, c0ffeeca7 commented on source/_integrations/conversation.markdown
> +You can add your own [sentence templates](https://developers.home-assistant.io/docs/voice_control/intent-recognition/template-sentence-syntax) to teach Home Assistant about new sentences. These sente
```suggestion
You can add your own [sentence templates](https://developers.home-assistant.io/docs/voice/intent-recognition/template-sentence-syntax) to teach Home Assistant about new sentences. These sentences can work with the [built-in intents](https://developers.home-assistant.io/docs/intent_builtin/) or trigger a custom action by defining custom {% term intents %} with the [intent script integration](/integrations/intent_script/).
```

2023-05-31 13:51 UTC, c0ffeeca7 commented on source/_integrations/conversation.markdown
> +To get started, create a `custom_sentences/<language>` directory in your Home Assistant `config` directory where `<language>` is the [language code](https://developers.home-assistant.io/docs/voice_co
```suggestion
To get started, create a `custom_sentences/<language>` directory in your Home Assistant `config` directory where `<language>` is the [language code](https://developers.home-assistant.io/docs/voice/intent-recognition/supported-languages) of your language, such as `en` for English. These YAML files are automatically merged, and may contain intents, lists, or expansion rules.
```

2023-05-31 13:51 UTC, c0ffeeca7 commented on source/_posts/2023-03-01-release-20233.markdown
> +Read more about [contributing sentences in our documentation](https://developers.home-assistant.io/docs/voice_control/intent-recognition/contributing).
```suggestion
Read more about [contributing sentences in our documentation](https://developers.home-assistant.io/docs/voice/intent-recognition/contributing).
```

2023-05-31 13:51 UTC, c0ffeeca7 commented on source/voice_control/builtin_sentences.markdown
> +Home Assistant comes with built-in sentences [contributed by the community](https://github.com/home-assistant/intents/) for [dozens of languages](https://developers.home-assistant.io/docs/voice_contr
```suggestion
Home Assistant comes with built-in sentences [contributed by the community](https://github.com/home-assistant/intents/) for [dozens of languages](https://developers.home-assistant.io/docs/voice/intent-recognition/supported-languages).
```

2023-05-31 13:51 UTC, c0ffeeca7 commented on source/voice_control/index.markdown
> +[List of supported languages.](https://developers.home-assistant.io/docs/voice_control/intent-recognition/supported-languages)
```suggestion
[List of supported languages.](https://developers.home-assistant.io/docs/voice/intent-recognition/supported-languages)
```

2023-05-31 13:51 UTC, c0ffeeca7 commented on source/voice_control/index.markdown
> +Did Assist not understand your sentence? [Contribute them.](https://developers.home-assistant.io/docs/voice_control/intent-recognition/)
```suggestion
Did Assist not understand your sentence? [Contribute them.](https://developers.home-assistant.io/docs/voice/intent-recognition/)
```

2023-05-31 13:51 UTC, c0ffeeca7 commented on source/_posts/2023-01-26-year-of-the-voice-chapter-1.markdown
> +We will continue collecting home automation sentences for all languages ([anyone can help!](https://developers.home-assistant.io/docs/voice_control/intent-recognition/)). Updates will be included wit
```suggestion
We will continue collecting home automation sentences for all languages ([anyone can help!](https://developers.home-assistant.io/docs/voice/intent-recognition/)). Updates will be included with every major release of Home Assistant.
```

2023-05-31 14:43 UTC, c0ffeeca7 commented
thank you, @balloob!

2023-05-31 15:02 UTC, balloob commented on source/_redirects
> +/docs/assist/ /docs/voice_control/
All pages need to be listed here. People might have linked to the tutorial etc, Those links are now broken and need to remain working.

2023-05-31 15:06 UTC, balloob commented on source/voice_control/index.markdown
> +You want to use Home Assistant with [Google Assistant](https://www.nabucasa.com/config/google_assistant/) or [Alexa](https://www.nabucasa.com/config/amazon_alexa/)? Get started with [Home Assistant C
```suggestion
Want to use Home Assistant with Google Assistant or Amazon Alexa? Get started with [Home Assistant Cloud](https://www.nabucasa.com/config/). 
```

2023-06-01 10:31 UTC, frenck requested changes
A wild merge conflict appeared out of nowhere 🙈 

../Frenck

2023-06-01 11:08 UTC, frenck approved these changes
Thanks, @c0ffeeca7 👍 

../Frenck

2023-06-01 11:08 UTC, merged