Add Reolink troubleshooting step
home-assistant/home-assistant.github.io pull request #27751
Opened 2023-06-11 14:24 UTC by starkillerOG

## Proposed change

Add Reolink troubleshooting step

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-06-11 14:25 UTC, starkillerOG commented
Reported in https://github.com/home-assistant/core/issues/91493#issuecomment-1585608924

2023-06-12 07:23 UTC, c0ffeeca7 requested changes

2023-06-12 07:23 UTC, c0ffeeca7 commented on source/_integrations/reolink.markdown
> +- Do not set a a static IP in the Reolink device itself, but leave the **Connection Type** on **DHCP** under **Settings** -> **Network** -> **Network Information** -> **Set Up**. If you set is to **s
```suggestion
- Do not set a static IP in the Reolink device itself, but leave the **Connection Type** on **DHCP** under **Settings** > **Network** > **Network Information** > **Set Up**. If you set it to **static** on the Reolink device itself, this is known to cause incorrect DHCP requests on the network. The incorrect DHCP request causes Home Assistant to use the wrong IP address for the camera, resulting in connection issues. The issue originates from the Reolink firmware, which keeps sending DCHP requests even when you set a static IP address in the Reolink device.
```

2023-06-12 07:28 UTC, c0ffeeca7 approved these changes
Thank you, @starkillerOG :+1:

2023-06-12 07:28 UTC, merged