Add new section for PhilipsTV sensors
home-assistant/home-assistant.github.io pull request #27867
Opened 2023-06-18 19:03 UTC by Floyer007

## Proposed change

A new feature within the PhilipsTV integration requires some little explanation or at least the listing of those new functionality.
This PR will add those new featured sensors and update the header order for readability.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/94691

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - ~~I made a change to the existing documentation and used the `current` branch.~~
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-06-19 18:03 UTC, frenck requested changes, later dismissed

2023-06-19 18:03 UTC, frenck commented on source/_integrations/philips_js.markdown
> +  - binary_sensor
PRs to the Core codebase may not contain multiple platforms in a single PR, therefore, this PR can also not contain multiple platforms being added in a single PR.

2023-06-20 18:50 UTC, Floyer007 commented on source/_integrations/philips_js.markdown
> +  - binary_sensor
Sure. Sorry about that. Understood the system now.

I changed both PRs to support binary_sensor only.
A new one will follow for sensor

2023-11-23 06:03 UTC, c0ffeeca7 commented on source/_integrations/philips_js.markdown
> +  - Binary Sensor
```suggestion
  - Binary sensor
```
We're now doing sentence-style capitalization on the categories, too

2023-11-23 06:03 UTC, c0ffeeca7 commented on source/_integrations/philips_js.markdown
> +## Binary Sensor
```suggestion
## Binary sensor
```

2023-11-23 06:03 UTC, c0ffeeca7 commented on source/_integrations/philips_js.markdown
> +For those TV'S this integration supports two entities:
```suggestion
Some newer OS versions support live TV recording functions via the API.
For those TVs, this integration supports two entities:
```

2023-11-23 06:04 UTC, c0ffeeca7 approved these changes
Thank you, @Floyer007 :+1:

2023-11-23 06:11 UTC, merged