Add more information about slow bluetooth connections
home-assistant/home-assistant.github.io pull request #27869
Opened 2023-06-18 21:33 UTC by bdraco

## Proposed change

Add more information about slow bluetooth connections and what to do to resolve the performance issues.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-06-18 21:34 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +The connection time and performance varies greatly based on the bluetooth adapter. Below adapters are listed from best performing to worst performing:
```suggestion
The connection time and performance varies greatly based on the Bluetooth adapter. Below adapters are listed from best performing to worst performing:
```

2023-06-18 21:35 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- USB High performance adapter with passive scanning
```suggestion
- [USB High performance](#known-working-high-performance-adapters) adapter with passive scanning
```

2023-06-18 21:35 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- USB High performance adapter with active scanning
```suggestion
- [USB High performance](#known-working-high-performance-adapters) adapter with active scanning
```

2023-06-18 21:36 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- [USB High performance adapter](#known-working-high-performance-adapters) with passive scanning
```suggestion
- [USB High performance adapter](#known-working-high-performance-adapters) with [passive scanning](#passive-scanning)
```

2023-06-18 21:36 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- Onboard high performance adapter with passive scanning
```suggestion
- Onboard high performance adapter with [passive scanning](#passive-scanning)
```

2023-06-18 21:36 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- Known working adapters with passive scanning
```suggestion
- Known working adapters with [passive scanning](#passive-scanning)
```

2023-06-18 21:37 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- Known working adapters with active scanning
```suggestion
- [Known working adapters](#known-working-adapters) with [passive scanning](#passive-scanning)
- [Known working adapters[(#known-working-adapters) with active scanning
```

2023-06-18 21:37 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- Onboard high performance adapter with active scanning
```suggestion
- [Onboard high performance adapter](#cypress-based-adapters) with [passive scanning](#passive-scanning)
- [Onboard high performance adapter](#cypress-based-adapters) with active scanning
```

2023-06-18 21:38 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- Bluetooth proxies running ESPHome 2023.6.0 or later with active scanning
```suggestion
- [Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with passive scanning
- [USB High performance adapter](#known-working-high-performance-adapters) with [passive scanning](#passive-scanning)
- [Bluetooth proxies](#remote-adapters-bluetooth-proxies)  running ESPHome 2023.6.0 or later with active scanning
```

2023-06-18 21:39 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +Known working adapters list adapter that do not meet high performance requirements, but will generally work. These adapters vary widely in performance, and may take as long as thirty seconds or more
```suggestion
Known working adapters list adapters that do not meet high-performance requirements but will generally work. These adapters vary widely in performance and may take as long as thirty seconds or more to establish a connection.
```

2023-06-18 21:40 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +The connection time and performance vary greatly based on the Bluetooth adapter. The below adapters are listed from best performing to worst performing:
```suggestion
The connection time and performance vary greatly based on the Bluetooth adapter. The below adapters are listed from best-performing to worst-performing:
```

2023-06-18 21:40 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- [Known working adapters[(#known-working-adapters) with active scanning
```suggestion
- [Known working adapters](#known-working-adapters) with active scanning
```

2023-06-18 21:41 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +The connection time and performance vary greatly based on the Bluetooth adapter. The below adapters are listed from best-performing to worst-performing:
```suggestion
The connection time and performance vary greatly based on the Bluetooth adapter and interference. The below adapters are listed from best-performing to worst-performing:
```

2023-06-18 21:41 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- [Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [passive scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-variables)
```suggestion
- [Ethernet-connected Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [passive scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-variables)
```

2023-06-18 21:41 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- [Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [active scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-variables)
```suggestion
- [Ethernet-connected Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [active scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-variables)
```

2023-06-18 21:42 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +- [USB High performance adapter](#known-working-high-performance-adapters) with active scanning
```suggestion
- [Ethernet-connected Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [passive scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-variables)
- [USB High performance adapter](#known-working-high-performance-adapters) with [passive scanning](#passive-scanning)
- [WiFi-connected Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [passive scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-variables)
- [Ethernet-connected Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [active scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-variables)
- [USB High performance adapter](#known-working-high-performance-adapters) with active scanning
- [WiFi-connected Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [active scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-variables)
```

2023-06-19 07:25 UTC, c0ffeeca7 requested changes

2023-06-19 07:25 UTC, c0ffeeca7 commented on source/_integrations/bluetooth.markdown
> +- [WiFi-connected Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [passive scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-v
```suggestion
- [Wi-Fi-connected Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [passive scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-variables)
```

2023-06-19 07:25 UTC, c0ffeeca7 commented on source/_integrations/bluetooth.markdown
> +- [WiFi-connected Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [active scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-va
```suggestion
- [Wi-Fi-connected Bluetooth proxies](#remote-adapters-bluetooth-proxies) running ESPHome 2023.6.0 or later with [active scanning](https://esphome.io/components/esp32_ble_tracker.html#configuration-variables)
```

2023-06-19 14:38 UTC, bdraco commented
changes LGTM

2023-06-19 22:17 UTC, bdraco commented on source/_integrations/bluetooth.markdown
> +Known working adapters list adapters that do not meet high-performance requirements but will generally work. These adapters vary widely in performance and may take as long as thirty seconds or more t
```suggestion
Known working adapters list adapters that do not meet high-performance requirements but will generally work. These adapters vary widely in performance and may take as long as thirty seconds or more to establish a connection. These adapters may also miss advertisements such as button presses or temperature updates.
```

2023-06-20 06:56 UTC, frenck approved these changes
Thanks, @bdraco 👍

../Frenck

2023-06-20 15:38 UTC, c0ffeeca7 approved these changes

2023-06-20 15:38 UTC, c0ffeeca7 commented on source/_integrations/bluetooth.markdown
> +### Improving connection times
The title "Improving connection times" and the PR message suggest that there are instructions on how to improve connection times. 
So the measure to take is to use a different device, one that is higher up in the list?

2023-06-20 15:39 UTC, merged

2023-06-20 16:33 UTC, bdraco commented
thanks!