Add tutorial on daily summary by assist
home-assistant/home-assistant.github.io pull request #28364
Opened 2023-07-28 13:40 UTC by c0ffeeca7

## Proposed change

Add tutorial on daily summary by assist
- Move procedure on creating a voice assistant to separate section
  - this allows referencing it in other procedures
- reference blueprint on daily summary by allenporter
- remove OpenAI procedure from World's most private voice assistant task and add a reference instead

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-08-03 19:20 UTC, synesthesiam requested changes

2023-08-03 19:20 UTC, synesthesiam commented on source/voice_control/assist_create_open_ai_personality.markdown
> +   - Once you installed the OpenAI Conversation integration, go to {% my integrations title="**Settings** > **Devices & Services**" %} and in OpenAI Conversation integration, the select **Configure**
"the select" -> "then select"

2023-08-04 06:37 UTC, c0ffeeca7 commented on source/voice_control/assist_create_open_ai_personality.markdown
> +   - Once you installed the OpenAI Conversation integration, go to {% my integrations title="**Settings** > **Devices & Services**" %} and in OpenAI Conversation integration, the select **Configure**
```suggestion
   - Once you installed the OpenAI Conversation integration, go to {% my integrations title="**Settings** > **Devices & Services**" %}. In the OpenAI Conversation integration, select **Configure**.
```

2023-08-04 06:37 UTC, c0ffeeca7 commented on source/voice_control/assist_create_open_ai_personality.markdown
> +   - Once you installed the OpenAI Conversation integration, go to {% my integrations title="**Settings** > **Devices & Services**" %} and in OpenAI Conversation integration, the select **Configure**
Thank you for the catch, @synesthesiam

2023-08-07 16:08 UTC, synesthesiam approved these changes

2023-08-08 06:31 UTC, merged