add write_registers to climate target temperature
home-assistant/home-assistant.github.io pull request #28376
Opened 2023-07-30 09:13 UTC by brunoenten

## Proposed change

In the climate integration, add the possibility to use write_registers not only for hvac_mode like before, but also for target temperature, using separate config attribute.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/97475
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-07-30 10:16 UTC, janiversen approved these changes, later dismissed
LGTM.

2023-07-31 09:25 UTC, janiversen submitted a review, later dismissed

2023-08-28 14:41 UTC, frenck requested changes
👋  Hi @brunoenten,

There is a merge conflict with this PR. Could you please take a look?

Thanks! 👍 

../Frenck

2023-08-28 15:13 UTC, janiversen commented
@brunoenten be aware the documentation have been rewritten, so your changes now goes into different lines.

2023-09-20 13:39 UTC, janiversen approved these changes, later dismissed
LGTM, Thanks

2023-09-21 09:05 UTC, frenck commented on source/_integrations/modbus.markdown
> +      description: if true use write_registers for target temperature
```suggestion
      description: "If `true` use `write_registers` for target temperature."
```

2023-09-21 09:21 UTC, frenck approved these changes
Thanks, @brunoenten 👍 

../Frenck

2023-09-21 09:21 UTC, merged