Add media player docs to System Bridge
home-assistant/home-assistant.github.io pull request #28384
Opened 2023-07-31 11:33 UTC by timmo001

## Proposed change

For https://github.com/home-assistant/core/pull/97532

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/97532

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-09-10 16:25 UTC, joostlek requested changes, later dismissed

2023-09-10 16:25 UTC, joostlek commented on source/_integrations/system_bridge.markdown
> +## Media Player
```suggestion
## Media player
```

2023-10-06 13:09 UTC, frenck submitted a review, later dismissed
Thanks, @timmo001 👍 

../Frenck

2023-10-06 13:10 UTC, frenck approved these changes
Thanks, @timmo001 👍 

../Frenck

2023-10-06 13:14 UTC, merged