Add airtouch5 documentation
home-assistant/home-assistant.github.io pull request #28523
Opened 2023-08-09 22:45 UTC by danzel

## Proposed change

Add documentation for the airtouch5 integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: TODO
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/4594
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-11-15 09:08 UTC, edenhaus requested changes, later dismissed

2023-11-15 09:08 UTC, edenhaus commented on source/_integrations/airtouch5.markdown
> +Each zone has binary sensors to show if the battery is low or spill is active.
```suggestion
```

They will not be added with the linked PR. Please create a separate docs PR for them

2023-11-15 09:08 UTC, edenhaus commented on source/_integrations/airtouch5.markdown
> +  - cover
```suggestion
  - climate
```

2023-11-15 09:08 UTC, edenhaus commented on source/_integrations/airtouch5.markdown
> +ha_release: 2023.9
```suggestion
ha_release: 2023.12
```

2024-01-29 07:43 UTC, c0ffeeca7 commented on source/_integrations/airtouch5.markdown
> +The AirTouch 5 integration allows you to control Ducted Air Conditioning Systems that are using the [AirTouch 5](https://www.airtouch.net.au/smart-air-conditioning/airtouch-5/) Controller.
```suggestion
The AirTouch 5 integration allows you to control ducted air conditioning systems that are using the [AirTouch 5](https://www.airtouch.net.au/smart-air-conditioning/airtouch-5/) controller.
```
Tiny tweak. Applied sentence-style capitalization as this is not a proper noun, but a generic term. Based on Microsoft Style Guide on [capitalization](https://learn.microsoft.com/en-us/style-guide/capitalization).

2024-01-29 07:44 UTC, c0ffeeca7 approved these changes
Thank you, @danzel :+1:

2024-01-29 07:48 UTC, merged