Update Apprise example to include name
home-assistant/home-assistant.github.io pull request #28580
Opened 2023-08-14 17:37 UTC by mjforan

## Proposed change
Minor update to documentation, clarifies use of Apprise notification service

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
The Apprise integration is meant to be called as a service. To register this service, the configuration needs to have the "name" parameter configured. Copying the examples as-is will not currently work because they are calling the `notify.apprise` service, which was not registered because the "name" parameter was not used. I added this parameter so the example will work.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-08-23 07:44 UTC, c0ffeeca7 requested changes
Tiny tweak. I think this way of writing it would make it clear that the name can be defined by the user.

2023-08-23 07:44 UTC, c0ffeeca7 commented on source/_integrations/apprise.markdown
> +  - name: apprise
```suggestion
  - name: NOTIFIER_NAME
```
I think this would make it clearer that the name can be user-defined.

2023-08-23 07:44 UTC, c0ffeeca7 commented on source/_integrations/apprise.markdown
> +  - name: apprise
```suggestion
  - name: NOTIFIER_NAME
```

2023-08-23 07:44 UTC, c0ffeeca7 commented on source/_integrations/apprise.markdown
> +  - name: apprise
```suggestion
  - name: NOTIFIER_NAME
```

2023-08-23 12:34 UTC, mjforan reviewed
Good idea. I made a commit with these changes and also modified the name in the service call.

2023-08-23 12:36 UTC, mjforan commented
One thing I wasn't sure of is if the name field should be listed as "required". Technically HA will accept a config without the name, but then the service won't be accessible by the user.

2023-08-24 12:10 UTC, mjforan reviewed
Addressed in separate commit

2023-09-11 06:29 UTC, c0ffeeca7 approved these changes
Thank you, @mjforan :+1:

2023-09-11 06:29 UTC, merged