Add duotecno climate platform
home-assistant/home-assistant.github.io pull request #28734
Opened 2023-08-30 12:59 UTC by Cereal2nd

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-09-07 12:42 UTC, joostlek requested changes, later dismissed

2023-09-07 12:42 UTC, joostlek commented on source/_integrations/duotecno.markdown
> +    - [Switch](#switch)
Why are you creating references to paragraphs that don't exist?

2023-09-26 09:53 UTC, frenck commented on source/_integrations/duotecno.markdown
> +
```suggestion
- Climate
- Cover
- Light
- Switch
```

2023-09-26 09:54 UTC, frenck submitted a review, later dismissed
Thanks, @Cereal2nd 👍 

../Frenck

2023-09-26 10:51 UTC, frenck approved these changes

2023-09-26 10:52 UTC, merged