Update ESPHome entity ID description
home-assistant/home-assistant.github.io pull request #28755
Opened 2023-08-31 20:49 UTC by jesserockz

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-08-31 20:50 UTC, kbx81 approved these changes

2023-08-31 22:02 UTC, bdraco requested changes, later dismissed
The docs do agree with the code

https://github.com/home-assistant/core/blob/5e03954e6940827a04b407980adce1bcfad922b6/homeassistant/components/esphome/entity.py#L160

2023-11-01 21:08 UTC, bdraco commented
We still need to fix this

2023-11-24 05:52 UTC, jesserockz commented
PR to be made to correct code comments but this is fine to go in.

2023-11-24 09:18 UTC, c0ffeeca7 approved these changes
Thank you, @jesserockz :+1:

2023-11-24 09:19 UTC, merged

2023-11-24 12:54 UTC, bdraco commented
Thanks @jesserockz