Add documentation for the new Husqvarna Automower integration
home-assistant/home-assistant.github.io pull request #28817
Opened 2023-09-06 22:26 UTC by Thomas55555

## Proposed change

Add documentation for the new Husqvarna Automower integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/99776
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-09-07 05:32 UTC, pascalwinters commented on source/_integrations/husqvarna_automower.markdown
> +4. Enter the following from the Husqvrana developer tab:
Type in `Husqvrana`

2023-09-07 05:33 UTC, pascalwinters commented on source/_integrations/husqvarna_automower.markdown
> +    ![Creat new Application](https://github.com/Thomas55555/home-assistant.io/assets/59625598/97abbbac-a089-4d9a-be3d-3a3f9c50442c)
Typo in `Creat`

2023-09-07 21:40 UTC, joostlek commented on source/_integrations/husqvarna_automower.markdown
> +    ![Creat new Application](https://github.com/Thomas55555/home-assistant.io/assets/59625598/97abbbac-a089-4d9a-be3d-3a3f9c50442c)
```suggestion
    ![Create new Application](https://github.com/Thomas55555/home-assistant.io/assets/59625598/97abbbac-a089-4d9a-be3d-3a3f9c50442c)
```

2023-09-07 21:40 UTC, joostlek commented on source/_integrations/husqvarna_automower.markdown
> +    ![Creat new Application](https://github.com/Thomas55555/home-assistant.io/assets/59625598/97abbbac-a089-4d9a-be3d-3a3f9c50442c)
Please don't use your own assets in the docs :)

2023-09-19 02:07 UTC, djpremier requested changes

2023-09-19 02:07 UTC, djpremier commented on source/_integrations/husqvarna_automower.markdown
> +4. Enter the following from the Husqvrana developer tab:
```suggestion
4. Enter the following from the Husqvarna developer tab:
```

2024-01-28 17:46 UTC, frenck commented
Closing PR as the parent PR has been closed.

2024-02-20 14:36 UTC, MartinHjelmare requested changes
Have you made sure to invalidate the example application credentials shown in the image

2024-02-20 14:36 UTC, MartinHjelmare commented on source/_integrations/husqvarna_automower.markdown
> +1. Go to the [Husqvarna Developers Portal](https://developer.husqvarnagroup.cloud) and sign in with your Husqvarna account. Authorize *Developer Portal* to access Husqvarna account when prompted.
```suggestion
1. Go to the [Husqvarna Developer Portal](https://developer.husqvarnagroup.cloud) and sign in with your Husqvarna account. Authorize *Developer Portal* to access Husqvarna account when prompted.
```

2024-02-20 16:12 UTC, Thomas55555 commented
> Have you made sure to invalidate the example application credentials shown in the image

Thanks for the hint. Yes, it's invalidated.

2024-02-21 08:53 UTC, MartinHjelmare approved these changes
Thanks!

2024-02-21 08:54 UTC, merged