Update mqtt.markdown
home-assistant/home-assistant.github.io pull request #28824
Opened 2023-09-07 14:29 UTC by martin3000

Beginners could think is for configuring the broker itself. Clarified wording.

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-09-07 20:02 UTC, jbouwh requested changes

2023-09-07 20:02 UTC, jbouwh commented on source/_integrations/mqtt.markdown
> +## Configuration of the connection to the broker
I rather prefer not to update the headers if this is not strictly needed as with it also the page anchors change.
To specific this header it seems clear enough to me in it current form.

2023-09-07 20:02 UTC, jbouwh commented on source/_integrations/mqtt.markdown
> +### Advanced configuration of the connection to the broker
Same here. You could suggest a change the paragraph text though.

2023-09-07 20:18 UTC, martin3000 commented
In the whole text, it is not clearly differentiated between the MQTT client integration and the broker. For most users this should be very confusing.

2023-09-07 22:45 UTC, jbouwh commented
> In the whole text, it is not clearly differentiated between the MQTT client integration and the broker. For most users this should be very confusing.

I do not agree on this. The documentation is clear that the MQTT integration requires to choose a broker and tells about the alternatives. It is clear the documentation is not about setting up the broker you choose MQTT broker.

2023-10-07 10:10 UTC, frenck commented
I think I'm with @jbouwh on this one, and therefore going to close this PR.

Nevetheless, thanks for being willing to contribute 👍 

../Frenck

2023-10-07 10:10 UTC, closed without merging