Add docs for new type check template functions
home-assistant/home-assistant.github.io pull request #29008
Opened 2023-09-24 22:14 UTC by raman325

## Proposed change
Documents the following additional functions/filters/tests for templates: https://github.com/home-assistant/core/pull/100807

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/100807
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-09-27 12:08 UTC, emontnemery requested changes

2023-09-27 12:08 UTC, emontnemery commented on source/_docs/configuration/templating.markdown
> +In addition to strings and numbers, Python (and Jinja) support lists, sets, and dictionaries. To help you with testing these types, the following are available as functions, filters, and tests:
support -> supports
```suggestion
In addition to strings and numbers, Python (and Jinja) supports lists, sets, and dictionaries. To help you with testing these types, the following are available as functions, filters, and tests:
```

2023-09-27 12:08 UTC, emontnemery commented on source/_docs/configuration/templating.markdown
> +- `is_list(x)` will return whether `x` is a `list` or not (e.g. [1, 2]).
Please rewrite the example ("e.g. [1, 2]") is an example of a list, not of how `is_list` behaves.
Also, please explain how it works when used as a filter or test too.
Same comment for the other `is_xxx`` .

It's mentioned in the core PR, Jinja has a built in function called "mapping", can we mention it here too? Does that also allow use as a function, filter or test?

2023-10-25 11:56 UTC, frenck commented on source/_docs/configuration/templating.markdown
> +Note that, as of Home Assistant 2023.10.0, Jinja has built in tests for `boolean` (`True`/`False`), `callable` (any function), `float` (a number with a decimal), `integer` (a number without a decimal
```suggestion
Note that, in Home Assistant, Jinja has built-in tests for `boolean` (`True`/`False`), `callable` (any function), `float` (a number with a decimal), `integer` (a number without a decimal), `iterable` (a value that can be iterated over such as a `list`, `set`, `string`, or generator), `mapping` (mainly `dict` but also supports other dictionary like types), `number` (`float` or `int`), `sequence` (a value that can be iterated over and indexed such as `list` and `string`), and `string`.
```

2023-10-25 11:56 UTC, frenck commented on source/_docs/configuration/templating.markdown
> +While Jinja natively supports the conversion of an iterable to a `list`, it does not support conversion to `tuple` or `set`. To help you with using these types, you can use the following functions:
```suggestion
While Jinja natively supports the conversion of an iterable to a `list`, it does not support conversion to a `tuple` or `set`. To help you with using these types, you can use the following functions:
```

2023-10-25 11:56 UTC, frenck commented on source/_docs/configuration/templating.markdown
> +Note that, as of Home Assistant 2023.10.0, to convert a value to a `list`, a `string`, an `int`, or a `float`, Jinja has built in functions with names that correspond to each type.
```suggestion
Note that, in Home Assistant, to convert a value to a `list`, a `string`, an `int`, or a `float`, Jinja has built-in functions with names that correspond to each type.
```

2023-10-25 12:10 UTC, frenck approved these changes
Thanks, @raman325 👍 

../Frenck

2023-10-25 12:10 UTC, merged