chore: updated list of supported products.
home-assistant/home-assistant.github.io pull request #29063
Opened 2023-09-29 06:27 UTC by riokuu

## Proposed change

Update of documentation supplementing missing devices and functionalities. 

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-10-06 06:45 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +- Door state(open, close, unknown)
```suggestion
## BleBox controllers

### rollerGate

#### This integration adds the Blebox device as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position
- Stop

### gateBox

#### This integration adds the Blebox device as a cover entity to Home Assistant

#### Key supported features

- Open (Trigger primary output)
- Close (Trigger primary output)
- Stop (Trigger secondary output)
- Gate state (open, close, unknown)

#### Additional features

- "stop" requires setting your device's secondary trigger as stop (via website or phone app).

### gateBox Pro

#### This integration adds the Blebox device as a cover entity to Home Assistant

#### Key supported features

- Open (Trigger primary output)
- Close (Trigger primary output)
- Stop (Trigger secondary output)
- Gate state (open, close, unknown)

#### Additional features

- "stop" requires setting your device's secondary trigger as stop(via website or phone app).

### doorBox

#### This integration adds the Blebox device as a cover entity to Home Assistant

#### Key supported features

- Open
- Door state (open, close, unknown)

### saunaBox

#### This integration adds the Blebox device as a climate entity to Home Assistant

#### Key supported features

- On
- Off
- Setting target temperature
- Read current temperature

### thermoBox

#### This integration adds the Blebox device as a climate entity to Home Assistant

#### Key supported features

- On
- Off
- Set target temperature
- Read current temperature

#### Additional features

- Changing operation mode(cooling/heating) requires direct access to device or from wBox app

### shutterBox

#### This integration adds the Blebox device as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position
- Tilt regulation

### shutterBoxDC

#### This integration adds the Blebox device as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position
- Tilt regulation

### shutterBox DIN

#### This integration adds the Blebox device as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position
- Tilt regulation

### switchBox

#### This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Energy consumption measurement

### switchBox DIN

#### This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Energy consumption measurement

### switchBoxD

#### This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Energy consumption measurement

### switchBoxD DIN

#### This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Energy consumption measurement

### switchBoxDC

#### This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### switchBox LIGHT

#### This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### switchBoxT PRO

#### This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### dimmerBox

#### This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Brightness

### wLightBox

#### This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

#### Additional features

- Changing color mode available from direct device access or wBox app. Device needs to be reloaded from Home Assistant.

### wLightBox PRO

#### This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

#### Additional features

- Changing color mode available from direct device access or wBox app. Device needs to be reloaded from Home Assistant.

### wLightBoxS

#### This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness

### wLightBoxS PRO

#### This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness

### pixelBox

#### This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

### tempSensor

#### This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of temperature

### tempSensorAC

#### This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of temperature for all probes

### tempSensor PRO

#### This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of temperature for all probes

### humiditySensor

#### This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of humidity
- Periodic read of temperature

### wind&RainSensor

#### This integration adds the Blebox device as a sensor & binary sensor entity to Home Assistant

#### Key supported features

- Periodic read of current wind speed
- Periodic read of state of rain detection

### rainSensor

#### This integration adds the Blebox device as a binary sensor entity to Home Assistant

#### Key supported features

- Periodic read of state of rain detection

### airSensor

#### This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of:
  - pm1
  - pm2.5
  - pm10

### windSensor PRO

#### This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of current wind speed

------

## "BleBox inside" controllers

### Simon 54 GO SHUTTER

#### This integration adds the Simon 54 GO device ("blebox inside")  as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position
- Tilt regulation

### Simon 54 GO SWITCH

#### This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### Simon 54 GO SWITCH D

#### This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### Simon 54 GO LED 230V (dimmer)

#### This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Brightness

### Simon 54 GO LED MONO

#### This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

### Simon 54 GO RGBW

#### This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

### Simon 55 GO SHUTTER

#### This integration adds the Simon 55 GO device ("blebox inside") as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position
- Tilt regulation

### Simon 55 GO SWITCH

#### This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### Simon 55 GO SWITCH D

#### This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Brightness

### Simon 55 GO LED 230V (dimmer)

#### This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Brightness

### Simon 55 GO LED M [...]

2023-10-06 06:47 UTC, c0ffeeca7 requested changes
Fix markdown violation

2023-10-06 07:04 UTC, c0ffeeca7 reviewed
Change styling of introductory sentence to paragraph style.

2023-10-06 07:04 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +- Door state (open, close, unknown)
```suggestion
#### Additional features

- Changing operation mode(cooling/heating) requires direct access to device or from wBox app

### shutterBox

This integration adds the Blebox device as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position
- Tilt regulation

### shutterBoxDC

This integration adds the Blebox device as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position
- Tilt regulation

### shutterBox DIN

This integration adds the Blebox device as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position
- Tilt regulation

### switchBox

This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Energy consumption measurement

### switchBox DIN

This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Energy consumption measurement

### switchBoxD

This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Energy consumption measurement

### switchBoxD DIN

This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Energy consumption measurement

### switchBoxDC

This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### switchBox LIGHT

This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### switchBoxT PRO

This integration adds the Blebox device as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### dimmerBox

This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Brightness

### wLightBox

This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

#### Additional features

- Changing color mode available from direct device access or wBox app. Device needs to be reloaded from Home Assistant.

### wLightBox PRO

This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

#### Additional features

- Changing color mode available from direct device access or wBox app. Device needs to be reloaded from Home Assistant.

### wLightBoxS

This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness

### wLightBoxS PRO

This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness

### pixelBox

This integration adds the Blebox device as a light entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

### tempSensor

This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of temperature

### tempSensorAC

This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of temperature for all probes

### tempSensor PRO

This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of temperature for all probes

### humiditySensor

This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of humidity
- Periodic read of temperature

### wind&RainSensor

This integration adds the Blebox device as a sensor & binary sensor entity to Home Assistant

#### Key supported features

- Periodic read of current wind speed
- Periodic read of state of rain detection

### rainSensor

This integration adds the Blebox device as a binary sensor entity to Home Assistant

#### Key supported features

- Periodic read of state of rain detection

### airSensor

This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of:
  - pm1
  - pm2.5
  - pm10

### windSensor PRO

This integration adds the Blebox device as a sensor entity to Home Assistant

#### Key supported features

- Periodic read of current wind speed

------

## "BleBox inside" controllers

### Simon 54 GO SHUTTER

This integration adds the Simon 54 GO device ("blebox inside")  as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position
- Tilt regulation

### Simon 54 GO SWITCH

This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### Simon 54 GO SWITCH D

This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### Simon 54 GO LED 230V (dimmer)

This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Brightness

### Simon 54 GO LED MONO

This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

### Simon 54 GO RGBW

This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

### Simon 55 GO SHUTTER

This integration adds the Simon 55 GO device ("blebox inside") as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position
- Tilt regulation

### Simon 55 GO SWITCH

This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off

### Simon 55 GO SWITCH D

This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Brightness

### Simon 55 GO LED 230V (dimmer)

This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Brightness

### Simon 55 GO LED MONO

This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

### Simon 55 GO RGBW

This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant

#### Key supported features

- On
- Off
- Effects
- Brightness
- Color

### FAKRO FTP-V/FTU-V WiFi

This integration adds the Fakro device ("blebox inside") as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position

### FAKRO ARF/ARP WiFi

This integration adds the Fakro device ("blebox inside") as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position

### FAKRO ARZ/AMZ/VMZ WiFi

This integration adds the Fakro device ("blebox inside") as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position

### SABAJ TV K-SMRT-4 - WIFI RJ-45

This integration adds the SABAJ device ("blebox inside") as a button entity to Home Assistant

#### Key supported features

- Open
- Close
- Up
- Down
- Fav

### Wiśniowski RiCo

This integration adds the Wiśniowski device ("blebox inside") as a cover entity to Home Assistant

- Open (trigger primary output)
- Close (trigger primary output)
- Stop (trigger secondary output)
- Gate state (open, close, unknown) - only Pro version

#### Additional features

- "stop" requires setting your device's secondary trigger as stop (via website or phone app)

### Polfendo smartGateControl

This integration adds the Polfendo device ("blebox inside") as a cover entity to Home Assistant

#### Key supported features

- Open
- Close
- Position [...]

2023-10-06 07:04 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +#### This integration adds the Blebox device as a cover entity to Home Assistant
```suggestion
This integration adds the Blebox device as a cover entity to Home Assistant.

2023-10-06 07:04 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +#### This integration adds the Blebox device as a cover entity to Home Assistant
```suggestion
This integration adds the Blebox device as a cover entity to Home Assistant.
```

2023-10-06 07:04 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +#### This integration adds the Blebox device as a cover entity to Home Assistant
```suggestion
This integration adds the Blebox device as a cover entity to Home Assistant.
```

2023-10-06 07:04 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +#### This integration adds the Blebox device as a cover entity to Home Assistant
```suggestion
This integration adds the Blebox device as a cover entity to Home Assistant.
```

2023-10-06 07:04 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +#### This integration adds the Blebox device as a climate entity to Home Assistant
```suggestion
This integration adds the Blebox device as a climate entity to Home Assistant.
```

2023-10-06 07:04 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +#### This integration adds the Blebox device as a climate entity to Home Assistant
```suggestion
This integration adds the Blebox device as a climate entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 reviewed
Fix typo I introduced in previous commit

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a cover entity to Home Assistant
```suggestion
This integration adds the Blebox device as a cover entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a cover entity to Home Assistant
```suggestion
This integration adds the Blebox device as a cover entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a cover entity to Home Assistant
```suggestion
This integration adds the Blebox device as a cover entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a switch entity to Home Assistant
```suggestion
This integration adds the Blebox device as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a switch entity to Home Assistant
```suggestion
This integration adds the Blebox device as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a switch entity to Home Assistant
```suggestion
This integration adds the Blebox device as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a switch entity to Home Assistant
```suggestion
This integration adds the Blebox device as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a switch entity to Home Assistant
```suggestion
This integration adds the Blebox device as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a switch entity to Home Assistant
```suggestion
This integration adds the Blebox device as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a switch entity to Home Assistant
```suggestion
This integration adds the Blebox device as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a light entity to Home Assistant
```suggestion
This integration adds the Blebox device as a light entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a light entity to Home Assistant
```suggestion
This integration adds the Blebox device as a light entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a light entity to Home Assistant
```suggestion
This integration adds the Blebox device as a light entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a light entity to Home Assistant
```suggestion
This integration adds the Blebox device as a light entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a light entity to Home Assistant
```suggestion
This integration adds the Blebox device as a light entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a light entity to Home Assistant
```suggestion
This integration adds the Blebox device as a light entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a sensor entity to Home Assistant
```suggestion
This integration adds the Blebox device as a sensor entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a sensor entity to Home Assistant
```suggestion
This integration adds the Blebox device as a sensor entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a sensor entity to Home Assistant
```suggestion
This integration adds the Blebox device as a sensor entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a sensor entity to Home Assistant
```suggestion
This integration adds the Blebox device as a sensor entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a sensor & binary sensor entity to Home Assistant
```suggestion
This integration adds the Blebox device as a sensor & binary sensor entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a binary sensor entity to Home Assistant
```suggestion
This integration adds the Blebox device as a binary sensor entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a sensor entity to Home Assistant
```suggestion
This integration adds the Blebox device as a sensor entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Blebox device as a sensor entity to Home Assistant
```suggestion
This integration adds the Blebox device as a sensor entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 54 GO device ("blebox inside")  as a cover entity to Home Assistant
```suggestion
This integration adds the Simon 54 GO device ("blebox inside")  as a cover entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant
```suggestion
This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant
```suggestion
This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant
```suggestion
This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant
```suggestion
This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant
```suggestion
This integration adds the Simon 54 GO device ("blebox inside") as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 55 GO device ("blebox inside") as a cover entity to Home Assistant
```suggestion
This integration adds the Simon 55 GO device ("blebox inside") as a cover entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant
```suggestion
This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant
```suggestion
This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant
```suggestion
This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant
```suggestion
This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant
```suggestion
This integration adds the Simon 55 GO device ("blebox inside") as a switch entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Fakro device ("blebox inside") as a cover entity to Home Assistant
```suggestion
This integration adds the Fakro device ("blebox inside") as a cover entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Fakro device ("blebox inside") as a cover entity to Home Assistant
```suggestion
This integration adds the Fakro device ("blebox inside") as a cover entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Fakro device ("blebox inside") as a cover entity to Home Assistant
```suggestion
This integration adds the Fakro device ("blebox inside") as a cover entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the SABAJ device ("blebox inside") as a button entity to Home Assistant
```suggestion
This integration adds the SABAJ device ("blebox inside") as a button entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Wiśniowski device ("blebox inside") as a cover entity to Home Assistant
```suggestion
This integration adds the Wiśniowski device ("blebox inside") as a cover entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Polfendo device ("blebox inside") as a cover entity to Home Assistant
```suggestion
This integration adds the Polfendo device ("blebox inside") as a cover entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Plast-met device ("blebox inside") as a light entity to Home Assistant
```suggestion
This integration adds the Plast-met device ("blebox inside") as a light entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Plast-met device ("blebox inside") as a light entity to Home Assistant
```suggestion
This integration adds the Plast-met device ("blebox inside") as a light entity to Home Assistant.
```

2023-10-06 07:10 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +This integration adds the Tedee device ("blebox inside") as a cover entity to Home Assistant
```suggestion
This integration adds the Tedee device ("blebox inside") as a cover entity to Home Assistant.
```

2023-10-06 07:14 UTC, c0ffeeca7 approved these changes, later dismissed
Thank you, @riokuu :+1:

2023-10-06 07:22 UTC, c0ffeeca7 reviewed
Fix typos

2023-10-06 07:22 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +- Open (Trigger primary output)
```suggestion
- Open (trigger primary output)
```

2023-10-06 07:22 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +- Close (Trigger primary output)
```suggestion
- Close (trigger primary output)
```

2023-10-06 07:22 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +- Stop (Trigger secondary output)
```suggestion
- Stop (trigger secondary output)
```

2023-10-06 07:22 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +- Open (Trigger primary output)
```suggestion
- Open (trigger primary output)
```

2023-10-06 07:22 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +- Close (Trigger primary output)
```suggestion
- Close (trigger primary output)
```

2023-10-06 07:22 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +- Stop (Trigger secondary output)
```suggestion
- Stop (trigger secondary output)
```

2023-10-06 07:22 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +- "stop" requires setting your device's secondary trigger as stop(via website or phone app).
```suggestion
- "stop" requires setting your device's secondary trigger as stop (via website or phone app).
```

2023-10-06 07:22 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +- Changing operation mode(cooling/heating) requires direct access to device or from wBox app
```suggestion
- Changing operation mode (cooling/heating) requires direct access to device or from wBox app
```

2023-10-06 07:22 UTC, c0ffeeca7 commented on source/_integrations/blebox.markdown
> +- Door state(open, close, unknown)
```suggestion
- Door state (open, close, unknown)
```

2023-10-06 07:29 UTC, c0ffeeca7 commented
@riokuu, I noticed you changed the Product name from *BleBox device" to *Blebox device* in some cases. In the main header it is called BleBox device. Was this changed on purpose? I checked the website and found different spellings there.

2023-10-09 06:51 UTC, c0ffeeca7 approved these changes
Thank you, @riokuu :+1:

2023-10-09 06:51 UTC, merged

2023-10-09 08:30 UTC, riokuu commented
Thanks to You, @c0ffeeca7 :muscle: