Update twitch.markdown to include instructions that prevent OAuth error
home-assistant/home-assistant.github.io pull request #29166
Opened 2023-10-04 20:45 UTC by PanicRide

## Proposed change
The OAuth redirect URL must be included when configuring a Twitch developer app. This avoids an error during the new UI flow.

Related issue: https://github.com/home-assistant/core/issues/101414

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: N/A
- Link to parent pull request in the Brands repository: N/A
- This PR fixes or closes issue: fixes https://github.com/home-assistant/core/issues/101414

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-10-04 20:49 UTC, yyolk commented
Can confirm I needed to do this when upgrading from the integration from `config.yaml` configuration to the UI config flow.

2023-10-06 11:38 UTC, bergdahl commented
Yes, this is required when setting up the integration regardless if you had it upgraded or not.

2023-10-06 11:41 UTC, frenck requested changes

2023-10-06 11:41 UTC, frenck commented on source/_posts/2023-10-04-release-202310.markdown
> +{% details "Twitch" %}
This part is already merged in another PR. Please remove the release notes adjustments from this PR.

2023-10-07 10:05 UTC, frenck commented
Superseded by #29219

2023-10-07 10:05 UTC, closed without merging