Update thirteen-usd-voice-remote.markdown
home-assistant/home-assistant.github.io pull request #29378
Opened 2023-10-16 11:24 UTC by andreasjacobsen93

2023-10-16 12:18 UTC, frenck requested changes

2023-10-16 12:18 UTC, frenck commented on source/voice_control/thirteen-usd-voice-remote.markdown
> +As a first step, you need to install the openWakeWord add-on in Home Assistant. This must be installed before setting up the ATOM Echo.
In Home Assistant is implied. Let's remove that.

2023-10-16 12:18 UTC, frenck commented on source/voice_control/thirteen-usd-voice-remote.markdown
> +1. Make sure this page is opened in Chrome or a Chromium-based browser (like Microsoft Edge) on a desktop. It does not work on a tablet or phone.
Chrome is a Chromium-based browser (and should be listed as Microsoft Edge).

2023-10-24 04:48 UTC, c0ffeeca7 approved these changes
Thank you, @andreasjacobsen93 :+1:

2023-10-25 05:30 UTC, frenck approved these changes

2023-10-25 05:30 UTC, merged