Update past vulnerability credits
home-assistant/home-assistant.github.io pull request #29446
Opened 2023-10-20 11:30 UTC by pwntester

## Proposed change
Update the vulnerability credits to:
- show the names instead of the GitHub handles.
- share credits for issues independently discovered by different researchers.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-10-20 16:57 UTC, frenck requested changes

2023-10-20 16:57 UTC, frenck commented on source/security/index.markdown
> +Discovered by: _[Cure53](https://cure53.de/) (Funded by [Nabu Casa](https://www.nabucasa.com/)) and [Peter Stöckli](https://github.com/p-) ([GitHub Security Lab](https://securitylab.github.com/))_
Sorry, as reported in the reported issue as well, this was already discovered and credited to the original reported.

Please revert this change.

2023-10-20 16:57 UTC, frenck commented on source/security/index.markdown
> +Discovered by: _[Cure53](https://cure53.de/) (Funded by [Nabu Casa](https://www.nabucasa.com/)) and [Peter Stöckli](https://github.com/p-) ([GitHub Security Lab](https://securitylab.github.com/))_
Same.

2023-10-20 18:01 UTC, pwntester commented on source/security/index.markdown
> +Discovered by: _[Cure53](https://cure53.de/) (Funded by [Nabu Casa](https://www.nabucasa.com/)) and [Peter Stöckli](https://github.com/p-) ([GitHub Security Lab](https://securitylab.github.com/))_
Hey 👋🏼 my understanding from the original report was that no new advisories were required because those issues had already been reported by a different security researcher. However, I do believe it's important to acknowledge the contributions of other researchers who independently discover the same issue before a patch is made public. It just doesn't seem fair otherwise, to be honest. Sharing credits for issues found independently is a common practice in infosec. Nonetheless, we will respect your final decision in this matter.

2023-10-20 18:09 UTC, frenck commented on source/security/index.markdown
> +Discovered by: _[Cure53](https://cure53.de/) (Funded by [Nabu Casa](https://www.nabucasa.com/)) and [Peter Stöckli](https://github.com/p-) ([GitHub Security Lab](https://securitylab.github.com/))_
The report wasn't credited. Sorry.
Our security page already clarifies those reports are not eligible.

../Frenck

2023-10-23 11:05 UTC, frenck approved these changes
Thanks, @pwntester 👍 

As you are internal with GitHub, it might be a good point of feedback to have the security advisories also be able to handle real names. Right now, we've copied it from the advisories (which show usernames).

Feels a bit odd to do it differently here.

../Frenck

2023-10-23 11:05 UTC, merged