Add update documentation for System Bridge
home-assistant/home-assistant.github.io pull request #29582
Opened 2023-10-28 19:14 UTC by timmo001

## Proposed change

Add update component documentation for https://github.com/home-assistant/core/pull/102966

## Type of change

- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/102966

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-10-29 09:34 UTC, jpbede requested changes

2023-10-29 09:34 UTC, jpbede commented on source/_integrations/system_bridge.markdown
Please add `update` to the `ha_platforms` as well.

2023-10-30 09:34 UTC, jpbede approved these changes

2023-11-06 13:42 UTC, frenck approved these changes
Thanks, @timmo001 👍 

../Frenck

2023-11-06 13:42 UTC, merged