Add documentation for new Vogel's MotionMount integration
home-assistant/home-assistant.github.io pull request #29716
Opened 2023-11-06 11:46 UTC by RJPoelstra

## Proposed change

Add documentation for new integration to support Vogel's MotionMount.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-11-25 21:16 UTC, joostlek requested changes

2023-11-25 21:16 UTC, joostlek commented on source/_integrations/motionmount.md
> +ha_codeowners:
```suggestion
ha_platforms:
  - number
ha_codeowners:
```

2023-11-26 10:32 UTC, frenck commented
@RJPoelstra Please don't request reviews. Thanks! 👍 

../Frenck

2023-12-22 11:06 UTC, joostlek commented on source/_integrations/motionmount.md
> +This integration uses the Ethernet (IP) connection of your MotionMount. It's not possible connect using the RS-232 connection.
```suggestion
This integration uses the Ethernet (IP) connection of your MotionMount. It's not possible to connect using the RS-232 connection.
```

2023-12-22 11:06 UTC, joostlek commented on source/_integrations/motionmount.md
> +The `Vogel's MotionMount` integration allows you to control the position of your [TVM 7675 Pro](https://www.vogels.com/p/tvm-7675-pro-motorized-tv-wall-mount-black) Signature MotionMount.
```suggestion
The Vogel's MotionMount integration allows you to control the position of your [TVM 7675 Pro](https://www.vogels.com/p/tvm-7675-pro-motorized-tv-wall-mount-black) Signature MotionMount.
```

2023-12-22 11:09 UTC, joostlek commented on source/_integrations/motionmount.md
> +ha_release: '2023.12.0'
```suggestion
ha_release: 2024.1
```

2023-12-23 23:08 UTC, joostlek approved these changes

2023-12-23 23:08 UTC, merged