Add documentation for V2C Trydan EVSE
home-assistant/home-assistant.github.io pull request #29715
Opened 2023-11-06 09:39 UTC by dgomes

## Proposed change

A

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-11-07 20:54 UTC, joostlek requested changes, later dismissed

2023-11-07 20:54 UTC, joostlek commented on source/_integrations/v2c.markdown
> +title: Ecoforest
;)

2023-11-07 20:54 UTC, joostlek commented on source/_integrations/v2c.markdown
> +To configure the V2C integration you will need to enter the IP Address of your Trydan EVSE.
```suggestion
To configure the V2C integration you will need to enter the IP address of your Trydan EVSE.
```

2023-11-08 13:43 UTC, frenck approved these changes
Thanks, @dgomes 👍 

../Frenck

2023-11-08 13:43 UTC, merged