Correct spelling of to-do list
home-assistant/home-assistant.github.io pull request #29773
Opened 2023-11-09 16:58 UTC by frenck

## Proposed change

Make sure we are consistent with how we write to-do lists.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #29667

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-11-09 21:41 UTC, MartinHjelmare requested changes

2023-11-09 21:41 UTC, MartinHjelmare commented on source/_integrations/todo.markdown
> +Add a new to-do Item. A to-do list `target` is selected with a [Target Selector](/docs/blueprint/selectors/#target-selector) and the `data` payload supports the following fields:
```suggestion
Add a new to-do item. A to-do list `target` is selected with a [Target Selector](/docs/blueprint/selectors/#target-selector) and the `data` payload supports the following fields:
```

2023-11-09 21:41 UTC, MartinHjelmare commented on source/_integrations/todo.markdown
> +Removing a to-do Item. A to-do list `target` is selected with a [Target Selector](/docs/blueprint/selectors/#target-selector), and the `data` payload supports the following fields:
```suggestion
Removing a to-do item. A to-do list `target` is selected with a [Target Selector](/docs/blueprint/selectors/#target-selector), and the `data` payload supports the following fields:
```

2023-11-10 08:18 UTC, MartinHjelmare approved these changes

2023-11-10 08:19 UTC, MartinHjelmare commented
How will this solve the linked issue? Wasn't that case inverted compared to this change?

2023-11-10 08:23 UTC, frenck commented
The spelling was inconsistent. It is now consistent with our user interface and according to the recommendations from the Microsoft Style Guide for writing (which we follow).

2023-11-10 08:27 UTC, MartinHjelmare commented
Ok. But the case style in the frontend is not consistent between the different items in the side bar.

2023-11-10 08:30 UTC, frenck commented
![CleanShot 2023-11-10 at 09 29 26@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/a6d338ea-b1ed-4aa3-906f-744fae810128)

This item in the frontend is correct, as in, follows sentence casing. 

![CleanShot 2023-11-10 at 09 30 16@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/d15e43cd-00bf-4b1f-89ef-66376c163776)

These seem to do so as well? What am I missing?

../Frenck

2023-11-10 08:46 UTC, MartinHjelmare commented
That looks good. The screenshot in the issue still had tools in Developer tools capitalized.

2023-11-10 09:21 UTC, merged