Add Option For Kelvin Unit To Color Temperature Selector
home-assistant/home-assistant.github.io pull request #29804
Opened 2023-11-11 16:36 UTC by schelv

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-12-02 15:48 UTC, FletcherAU requested changes
Slight correction

2023-12-02 15:48 UTC, FletcherAU commented on source/_docs/blueprint/selectors.markdown
> +  description: The chosen unit for the color temperature. This can be either `kelvin` or `mired`. `mired` is the default for historic reasons.
```suggestion
  description: The chosen unit for the color temperature. This can be either `kelvin` or `mired`. `mired` is the default for historical reasons.
```
Historic is noteworth vs historical which is basically precedent in this instance.

2023-12-02 15:52 UTC, FletcherAU approved these changes

2023-12-04 05:34 UTC, c0ffeeca7 commented on source/_docs/blueprint/selectors.markdown
> +The color temperature selector allows the user to select a color temperature from a gradient using a slider.
```suggestion
The color temperature selector allows you to select a color temperature from a gradient using a slider.
```

2023-12-04 05:35 UTC, c0ffeeca7 approved these changes
Thank you, @schelv and @FletcherAU :+1:

2023-12-04 05:50 UTC, merged