Add support for lupusec smoke and water sensor
home-assistant/home-assistant.github.io pull request #29827
Opened 2023-11-13 13:45 UTC by suaveolent

## Proposed change

Updating documentation for lupus to include support for water and smoke sensor for XT2 Plus.

https://github.com/home-assistant/core/pull/103905

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-11-14 08:19 UTC, FletcherAU requested changes

2023-11-14 08:19 UTC, FletcherAU commented on source/_integrations/lupusec.markdown
> +- **Binary Sensor**: Displays the status of binary sensors. Door, window, water and smoke sensors are supported.
```suggestion
- **Binary Sensor**: Displays the status of binary sensors. Door, window, water, and smoke sensors are supported.
```
Oxford comma as per the [standards](https://developers.home-assistant.io/docs/documenting/standards/).

2023-11-14 08:58 UTC, FletcherAU approved these changes

2023-11-15 12:40 UTC, edenhaus approved these changes

2023-11-15 12:40 UTC, merged