Add logarithmic scale option to Statistics and History graph cards
home-assistant/home-assistant.github.io pull request #29874
Opened 2023-11-16 18:43 UTC by wittypluck

## Proposed change

This PR adds documentation for the new "logarithmic scale" option in the Statistics and History graph cards.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
https://github.com/home-assistant/frontend/pull/18637

- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-11-16 21:47 UTC, wittypluck commented
Hi,
I'm not sure why lint gives me the following error. 
Could somebody hepl ont his ?
Thanks,

`error  Incorrect usage of the term: “axis”, use “Axis” instead  terminology`

2023-11-17 06:07 UTC, FletcherAU requested changes
Convention appears to be `Y-axis` over `vertical axis` ie, https://github.com/home-assistant/home-assistant.io/blob/86cef97aeedd5b67242d0d1f929a20a465c36a3b/source/_dashboards/sensor.markdown?plain=1#L60

(This may also help with the linter problem though that's only a guess)

2023-11-17 06:07 UTC, FletcherAU commented on source/_dashboards/history-graph.markdown
> +  description: If true, numerical values on the vertical axis will be displayed with a logarithmic scale.
```suggestion
  description: If true, numerical values on the Y-axis will be displayed with a logarithmic scale.
```

2023-11-17 06:07 UTC, FletcherAU commented on source/_dashboards/statistics-graph.markdown
> +  description: If true, numerical values on the vertical axis will be displayed with a logarithmic scale.
```suggestion
  description: If true, numerical values on the Y-axis will be displayed with a logarithmic scale.
```

2023-11-17 07:47 UTC, FletcherAU commented
Looks like that's solved it :)

2023-11-17 07:57 UTC, wittypluck commented
Thank you for the suggestion!

2023-11-23 09:03 UTC, c0ffeeca7 approved these changes
Thank you, @wittypluck and @FletcherAU :+1:

2023-11-23 09:03 UTC, merged