Add documentation for LinknLink integration
home-assistant/home-assistant.github.io pull request #29881
Opened 2023-11-17 08:53 UTC by xuanxuan000

## Proposed change

Add documentation for LinknLink integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/4912
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-11-17 12:22 UTC, FletcherAU requested changes

2023-11-17 12:22 UTC, FletcherAU commented on source/_integrations/linknlink.markdown
> +The LinknLink integration allows you to control and monitor LinknLink universal remotes, smart plugs, power strips, switches and sensors. The following devices are supported:
```suggestion
The LinknLink integration allows you to control and monitor LinknLink universal remotes, smart plugs, power strips, switches, and sensors. The following devices are supported:
```
Serial comma as per [standards](https://developers.home-assistant.io/docs/documenting/standards/)

2023-11-17 12:22 UTC, FletcherAU commented on source/_integrations/linknlink.markdown
> +The entities have the same name as the device by default. To change the name, icon or entity id, click the entity on the frontend and click the settings icon in the upper right. You can also disable
```suggestion
There is no more need to set up platforms except for custom IR/RF switches. Once the device is configured all entities will be created automatically.

The entities have the same name as the device by default. To change the name, icon, or entity id select the entity on the frontend and click the settings icon in the upper right. You can also disable the entity there if you don't think it is useful. Don't forget to select _Update_ to save your changes when you're done.
```
Serial comma and convention is to use select over click if I recall correctly.

2023-11-17 12:22 UTC, FletcherAU commented on source/_integrations/linknlink.markdown
> +To learn IR codes, call `remote.learn_command` with the device name and command to be learned:
```suggestion
To learn IR codes call `remote.learn_command` with the device name and command to be learned:
```

2023-11-17 12:22 UTC, FletcherAU commented on source/_integrations/linknlink.markdown
> +When the LED blinks, point the remote at the LinknLink device and press the button you want to learn.
```suggestion
When the LED blinks point the remote at the LinknLink device and press the button you want to learn.
```

2023-11-17 12:22 UTC, FletcherAU commented on source/_integrations/linknlink.markdown
> +When the LED blinks for the first time, press and hold the button to sweep the frequency. Then wait for the LED to blink again and press the button a second time to capture the code.
```suggestion
When the LED blinks for the first time press and hold the button to sweep the frequency. Then wait for the LED to blink again and press the button a second time to capture the code.
```

2023-11-17 12:22 UTC, FletcherAU commented on source/_integrations/linknlink.markdown
> +_Tip:_ Click Notifications in the sidebar after calling the service and follow the instructions to make sure you are pressing the button at the right time.
```suggestion
_Tip:_ Select Notifications in the sidebar after calling the service and follow the instructions to make sure you are pressing the button at the right time.
```

2023-11-17 12:22 UTC, FletcherAU commented on source/_integrations/linknlink.markdown
> +In order to streamline the learning process, you may want to provide a list of commands to be learned sequentially:
```suggestion
In order to streamline the learning process you may want to provide a list of commands to be learned sequentially:
```

2023-11-17 12:22 UTC, FletcherAU commented on source/_integrations/linknlink.markdown
> +After calling this service, you will be prompted to press the buttons in the same order as provided. Check the notifications to stay on track and make sure you are pressing the right button at the ri
```suggestion
After calling this service you will be prompted to press the buttons in the same order as provided. Check the notifications to stay on track and make sure you are pressing the right button at the right time.
```

2023-11-17 12:22 UTC, FletcherAU commented on source/_integrations/linknlink.markdown
> +When the LED blinks for the first time, press the button you want to learn. Then wait for the LED to blink again and press the same button. By doing so, two different codes will be learned for the sa
```suggestion
When the LED blinks for the first time, press the button you want to learn. Then wait for the LED to blink again and press the same button. This wil cause two different codes will be learned for the same command and they will be sent alternately at each call.
```

2025-07-03 22:31 UTC, frenck commented
Closing PR as the parent PR has been closed.

2025-07-03 22:31 UTC, closed without merging