u-z integrations: apply sentence-style caps to categories
home-assistant/home-assistant.github.io pull request #29907
Opened 2023-11-18 17:32 UTC by c0ffeeca7

## Proposed change

u-z integrations:
- apply sentence-style caps to categories

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-11-18 21:07 UTC, ludeeus commented on source/_integrations/universal.markdown
> +A Universal Media player can combine multiple existing entities in Home Assistant into a single media player entity. This is used to create a single media player entity that can control an entire med
```suggestion
A universal media player can combine multiple existing entities in Home Assistant into a single media player entity. This is used to create a single media player entity that can control an entire media center.
```

2023-11-18 21:07 UTC, ludeeus commented on source/_integrations/universal.markdown
>  title: Universal Media Player
```suggestion
title: Universal media player
```

2023-11-18 21:07 UTC, ludeeus commented on source/_integrations/universal.markdown
>  Multiple media player entities may be controlled from a Universal Media Player. Additionally, the Universal Media Player can enable volume and power commands to be directed to other Home Assistant en
```suggestion
Multiple media player entities may be controlled from a universal media player. Additionally, the universal media player can enable volume and power commands to be directed to other Home Assistant entities. This enables the media player power and volume commands to control devices like a television, amplifier or audio receiver, for example.
```

2023-11-18 21:07 UTC, ludeeus commented on source/_integrations/uptimerobot.markdown
>  description: Instructions on how to set up Uptime Robot within Home Assistant.
```suggestion
description: Instructions on how to set up UptimeRobot within Home Assistant.
```

2023-11-18 21:07 UTC, ludeeus commented on source/_integrations/xbox.markdown
> +The Xbox media player platform will create Media player entities for each console linked to your Microsoft account. These entities will display the active app and playback controls as well as a media
```suggestion
The Xbox media player platform will create media player entities for each console linked to your Microsoft account. These entities will display the active app and playback controls as well as a media browser implementation, allowing you to launch any installed application.
```

2023-11-18 21:07 UTC, ludeeus commented on source/_integrations/xbox.markdown
>  The Xbox media source platform allows you to use the Media Browser panel to view both your own, and community, gameclips or screenshots for games that you have installed on any of your consoles. As w
```suggestion
The Xbox media source platform allows you to use the media browser panel to view both your own, and community, gameclips or screenshots for games that you have installed on any of your consoles. As with any other media source integration, you are also able to send these clips to supported media players like Chromecast.
```
"the media browser panel" could possible be a my link as well.
https://my.home-assistant.io/redirect/media_browser/

2023-11-19 04:47 UTC, c0ffeeca7 commented on source/_integrations/universal.markdown
> +A Universal Media player can combine multiple existing entities in Home Assistant into a single media player entity. This is used to create a single media player entity that can control an entire med
```suggestion
A Universal Media Player can combine multiple existing entities in Home Assistant into a single media player entity. This is used to create a single media player entity that can control an entire media center.
```
I'm not entirely sure about this one. It looks like [Universal Media Server](https://www.universalmediaserver.com/) is the name of their product. I did not find the player on their website. Maybe we can leave the caps, to align with the spelling of their product name.

2023-11-19 04:48 UTC, c0ffeeca7 commented on source/_integrations/universal.markdown
>  Multiple media player entities may be controlled from a Universal Media Player. Additionally, the Universal Media Player can enable volume and power commands to be directed to other Home Assistant en
I think it's the product name.

2023-11-19 10:22 UTC, c0ffeeca7 commented on source/_integrations/universal.markdown
>  title: Universal Media Player
I think it is the name

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/universal.markdown
> +  description: Allows override the browse media {% term entity %} to desired media player.
```suggestion
  description: Allows override the browse media entity to desired media player.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/universal.markdown
> +  description: The device class that this {% term entity %} represents. Can be `tv`, `speaker`, or `receiver`.
```suggestion
  description: The device class that this entity represents. Can be `tv`, `speaker`, or `receiver`.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/universal.markdown
> +  description: A unique identifier for this {% term entity %}. Needs to be unique within the `media_player` platform.
```suggestion
  description: A unique identifier for this entity. Needs to be unique within the `media_player` platform.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/utility_meter.markdown
> +  description: The sensor {% term entity %} providing utility readings (energy, water, gas, heating).
```suggestion
  description: The sensor entity providing utility readings (energy, water, gas, heating).
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/vacuum.mqtt.markdown
> +  description: When `availability` is configured, this controls the conditions needed to set the {% term entity %} to `available`. Valid entries are `all`, `any`, and `latest`. If set to `all`, `payl
```suggestion
  description: When `availability` is configured, this controls the conditions needed to set the entity to `available`. Valid entries are `all`, `any`, and `latest`. If set to `all`, `payload_available` must be received on all configured availability topics before the entity is marked as online. If set to `any`, `payload_available` must be received on at least one configured availability topic before the term entity is marked as online. If set to `latest`, the last `payload_available` or `payload_not_available` received on any configured availability topic controls the availability.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/vacuum.template.markdown
> +        description: Defines a template to get the `available` state of the {% term entity %}. If the template either fails to render or returns `True`, `"1"`, `"true"`, `"yes"`, `"on"`, `"enable"`,
```suggestion
        description: Defines a template to get the `available` state of the entity. If the template either fails to render or returns `True`, `"1"`, `"true"`, `"yes"`, `"on"`, `"enable"`, or a non-zero number, the entity will be `available`. If the template returns any other value, the entity will be `unavailable`. If not configured, the entity will always be `available`. Note that the string comparison not case sensitive; `"TrUe"` and `"yEs"` are allowed.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/vizio.markdown
> +  description: Nickname for your device that will be used to generate the device's {% term entity %} ID. If multiple Vizio devices are configured, the value must be unique for each entry.
```suggestion
  description: Nickname for your device that will be used to generate the device's entity ID. If multiple Vizio devices are configured, the value must be unique for each entry.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/water_heater.mqtt.markdown
> +  description: When `availability` is configured, this controls the conditions needed to set the {% term entity %} to `available`. Valid entries are `all`, `any`, and `latest`. If set to `all`, `payl
```suggestion
  description: When `availability` is configured, this controls the conditions needed to set the entity to `available`. Valid entries are `all`, `any`, and `latest`. If set to `all`, `payload_available` must be received on all configured availability topics before the entity is marked as online. If set to `any`, `payload_available` must be received on at least one configured availability topic before the entity is marked as online. If set to `latest`, the last `payload_available` or `payload_not_available` received on any configured availability topic controls the availability.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/water_heater.mqtt.markdown
> +  description: Flag which defines if the {% term entity %} should be enabled when first added.
```suggestion
  description: Flag which defines if the entity should be enabled when first added.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/water_heater.mqtt.markdown
> +  description: The [category](https://developers.home-assistant.io/docs/core/entity#generic-properties) of the {% term entity %}.
```suggestion
  description: The [category](https://developers.home-assistant.io/docs/core/entity#generic-properties) of the entity.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/water_heater.mqtt.markdown
> +  description: "[Icon](/docs/configuration/customizing-devices/#icon) for the {% term entity %}."
```suggestion
  description: "[Icon](/docs/configuration/customizing-devices/#icon) for the {% term entity %}."
```
```suggestion
  description: "[Icon](/docs/configuration/customizing-devices/#icon) for the entity."
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/watson_iot.markdown
> +      description: The list of {% term entity %} ids to be excluded from recording to Watson IoT Platform.
```suggestion
      description: The list of entity ids to be excluded from recording to Watson IoT Platform.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/weather.template.markdown
> +  description: An ID that uniquely identifies this weather {% term entity %}. Set this to a unique value to allow customization through the UI.
```suggestion
  description: An ID that uniquely identifies this weather entity. Set this to a unique value to allow customization through the UI.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/yeelight.markdown
> +          description: Adds another {% term entity %}, to control nightlight mode (for models that supports it). Currently, only `light` is supported. It will create 2 light entities, one for normal
```suggestion
          description: Adds another entity, to control nightlight mode (for models that supports it). Currently, only `light` is supported. It will create 2 light entities, one for normal light mode and second for nightlight mode. They are mutually exclusive.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/zabbix.markdown
> +      description: The list of {% term entity %} ids to be excluded from being published to Zabbix.
```suggestion
      description: The list of entity ids to be excluded from being published to Zabbix.
```

2023-11-19 11:00 UTC, c0ffeeca7 commented on source/_integrations/zabbix.markdown
> +      description: The list of {% term entity %} ids to be included in being published to Zabbix.
```suggestion
      description: The list of entity ids to be included in being published to Zabbix.
```

2023-11-19 11:23 UTC, c0ffeeca7 commented on source/_integrations/vizio.markdown
> +>>>>>>> Stashed changes
```suggestion
  description: Nickname for your device that will be used to generate the device's term entity ID. If multiple VIZIO devices are configured, the value must be unique for each entry.
```

2023-11-19 11:32 UTC, c0ffeeca7 commented on source/_integrations/universal.markdown
> +  description: Ordered list of child media players that this {% term entity %} will control.
```suggestion
  description: Ordered list of child media players that this entity will control.
```

2023-11-19 11:55 UTC, ludeeus commented on source/_integrations/universal.markdown
> +A Universal Media Player can combine multiple existing entities in Home Assistant into a single media player {% term entity %}. This is used to create a single media player {% term entity %} that can
```suggestion
A universal media player can combine multiple existing entities in Home Assistant into a single media player {% term entity %}. This is used to create a single media player {% term entity %} that can control an entire media center.
```

2023-11-19 11:55 UTC, ludeeus commented on source/_integrations/unifiprotect.markdown
> +### Local sser
```suggestion
### Local user
```

2023-11-19 11:55 UTC, ludeeus commented on source/_integrations/universal.markdown
> +The Universal Media Player will primarily imitate one of its `children`. The Universal Media Player will control the first child on the list that is active (not idle/off). The Universal Media Player
```suggestion
The universal media player will primarily imitate one of its `children`. The universal media player will control the first child on the list that is active (not idle/off). The universal media player will also inherit its state from the first active child if a `state_template` is not provided. Entities in the `children:` list must be media players, but the state template can contain any {% term entity %}.
```

2023-11-19 11:55 UTC, ludeeus commented on source/_integrations/vacuum.mqtt.markdown
> +  description: When `availability` is configured, this controls the conditions needed to set the entity to `available`. Valid entries are `all`, `any`, and `latest`. If set to `all`, `payload_availab
```suggestion
  description: When `availability` is configured, this controls the conditions needed to set the entity to `available`. Valid entries are `all`, `any`, and `latest`. If set to `all`, `payload_available` must be received on all configured availability topics before the entity is marked as online. If set to `any`, `payload_available` must be received on at least one configured availability topic before the entity is marked as online. If set to `latest`, the last `payload_available` or `payload_not_available` received on any configured availability topic controls the availability.
```

2023-11-19 11:55 UTC, ludeeus commented on source/_integrations/vizio.markdown
> +  description: Nickname for your device that will be used to generate the device's term entity ID. If multiple VIZIO devices are configured, the value must be unique for each entry.
```suggestion
  description: Nickname for your device that will be used to generate the device's entity ID. If multiple VIZIO devices are configured, the value must be unique for each entry.
```

2023-11-19 11:55 UTC, ludeeus commented on source/_integrations/wled.markdown
> +This inte{% term integration %}gration provides sensors for the following information from WLED:
```suggestion
This {% term integration %} provides sensors for the following information from WLED:
```

2023-11-19 11:55 UTC, ludeeus commented on source/_integrations/ws66i.markdown
> +The **Soundavo WS66i 6-Zone Amplifier** {% term integration %} allows you to control the [Soundavo Whole-Home Audio Amplifier](https://www.soundavo.com/products/ws-66i) via the local network. This am
```suggestion
The **Soundavo WS66i 6-Zone Amplifier** {% term integration %} allows you to control the [Soundavo Whole-Home Audio Amplifier](https://www.soundavo.com/products/ws-66i) via the local network. This amplifier is an upgrade of the amplifier sold by [Monoprice](https://www.monoprice.com/product?p_id=10761) that adds 2 built-in wireless streamers and an ethernet port for control over LAN.
```

2023-11-19 13:00 UTC, joostlek requested changes

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/ukraine_alarm.markdown
> +The **Ukraine Alarm** {% term integrations %} uses the siren.pp.ua API - public wrapper for [Ukraine Alarm](https://www.ukrainealarm.com/) web service to offer air-raid siren notifications. The {% te
```suggestion
The **Ukraine Alarm** {% term integration %} uses the siren.pp.ua API - public wrapper for [Ukraine Alarm](https://www.ukrainealarm.com/) web service to offer air-raid siren notifications. The {% term integration %} will create 6 binary sensors for your selected region in Ukraine:
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/ultraloq.markdown
> +Ultraloq Z-Wave Series smart locks work locally and integrate seamlessly with the **Z-Wave** {% term integrations %} in Home Assistant (Z-Wave stick required).
```suggestion
Ultraloq Z-Wave Series smart locks work locally and integrate seamlessly with the **Z-Wave** {% term integration %} in Home Assistant (Z-Wave stick required).
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
> +The **UniFi Protect** {% term integrations %} adds support for retrieving camera feeds and sensor data from a [UniFi Protect application](https://ui.com/camera-security) by [Ubiquiti Networks, inc.](
```suggestion
The **UniFi Protect** {% term integration %} adds support for retrieving camera feeds and sensor data from a [UniFi Protect application](https://ui.com/camera-security) by [Ubiquiti Networks, inc.](https://www.ui.com/) that is running on a UniFi OS Console.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
> +This {% term integrations %} supports all UniFi OS Consoles that can run UniFi Protect. Currently, this includes:
```suggestion
This {% term integration %} supports all UniFi OS Consoles that can run UniFi Protect. Currently, this includes:
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
> +Using Early Access versions will likely cause your UniFi Protect {% term integrations %} to break unexpectedly.
```suggestion
Using Early Access versions will likely cause your UniFi Protect {% term integration %} to break unexpectedly.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
> +each of the different {% term entity %} platforms.
I think the term is better used at "entities" above, as the term here is entity platforms

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
> +- **Media Player** - If your camera has a speaker, you will get a media player {% term entity %} that allows you to play audio to your camera's speaker. Any audio file URI that is playable by FFmpeg
```suggestion
- **Media player** - If your camera has a speaker, you will get a media player {% term entity %} that allows you to play audio to your camera's speaker. Any audio file URI that is playable by FFmpeg will be able to be played to your speaker, including via the [TTS Say Service](/integrations/tts/#service-say).
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
>  - **Device Configuration** - Floodlights will get configuration controls for the PIR Motion Sensitivity, the Auto-shutoff Duration after detected motion, and Status Light switch
```suggestion
- **Device configuration** - Floodlights will get configuration controls for the PIR motion sensitivity, the Auto-shutoff Duration after detected motion, and status light switch
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
>  - **Device Configuration** - Smart sensors will get configuration controls for the Status Light, enabling/disabling all of the main sensors, selecting the Paired Camera, and changing the Mount Type o
```suggestion
- **Device configuration** - Smart sensors will get configuration controls for the status light, enabling/disabling all of the main sensors, selecting the paired camera, and changing the mount type of the sensor.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
>  - **Disk Health**: Each disk installed in your NVR will have a disk health sensor. These are simple good/bad sensors and the order is not promised to match the order in UniFi OS. Disk model number is
```suggestion
- **Disk health**: Each disk installed in your NVR will have a disk health sensor. These are simple good/bad sensors and the order is not promised to match the order in UniFi OS. Disk model number is provided as a state attribute though to help map sensor to disk.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
>  - **Utilization and Storage Sensors**: Several other sensors are also added for uptime, hardware utilization, and distribution details of the video on disk.
```suggestion
- **Utilization and storage sensors**: Several other sensors are also added for uptime, hardware utilization, and distribution details of the video on disk.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
> +### {% term Service %} unifiprotect.set_default_doorbell_text
Wouldn't it make more sense to make Services the term?

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
> +The {% term integrations %} provides two proxy views to proxy media content from your Home Assistant instance so you can access thumbnails and video clips from within the context of Home Assistant wi
```suggestion
The {% term integration %} provides two proxy views to proxy media content from your Home Assistant instance so you can access thumbnails and video clips from within the context of Home Assistant without having to expose your UniFi Protect NVR Console. As with the media identifiers, all IDs are UniFi Protect IDs as they may not map to specific Home Assistant entities depending on how you have configured your {% term integration %}.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/unifiprotect.markdown
> +`nvr_id` can either be the UniFi Protect ID of your NVR or the config entry ID for your UniFi Protect {% term integrations %}. `camera_id` can either be the UniFi Protect ID of your camera or an enti
```suggestion
`nvr_id` can either be the UniFi Protect ID of your NVR or the config entry ID for your UniFi Protect {% term integration %}. `camera_id` can either be the UniFi Protect ID of your camera or an entity ID of any {% term entity %} provided by the UniFi Protect {% term integration %} that can be reversed to a UniFi Protect camera (i.e., an entity ID of a detected object sensor).
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/universal.markdown
> +title: Universal media player
Shouldn't this be changed in the code as well? Otherwise Frencks sync script will overwrite this again when 2023.12 drops

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/universal.markdown
>  A Universal Media Player is created in `configuration.yaml` as follows.
```suggestion
A universal media player is created in `configuration.yaml` as follows.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/vicare.markdown
> +- [Water heater](#water-heater) (Domestic Hot Water)
```suggestion
- [Water heater](#water-heater) (Domestic hot water)
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/wallbox.markdown
>  - Added Energy
Lots of potential here

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/weatherflow.markdown
> +This {% term integration %} is a local-only **WeatherFlow** {% term integration %} that reads weather data from all [WeatherFlow Tempest](https://weatherflow.com/tempest-weather-system/) compatible w
```suggestion
The **WeatherFlow** {% term integration %} is a local-only {% term integration %} that reads weather data from all [WeatherFlow Tempest](https://weatherflow.com/tempest-weather-system/) compatible weather station on the local network.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/wemo.markdown
> +Clicking the **Configure** button on the WeMo {% term integration %} will bring up some additional options that can be configured for WeMo devices.
```suggestion
Selecting the **Configure** button on the WeMo {% term integration %} will bring up some additional options that can be configured for WeMo devices.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/wilight.markdown
>  There are several services which can be used for automations and control of the Irrigation:
Services could be a term

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/ws66i.markdown
> +Enter the IP Address of the WS66i amplifier when prompted to connect to the device and hit submit. It will detect the number of connected amplifiers and present each zone as an {% term entity %}.
```suggestion
Enter the IP address of the WS66i amplifier when prompted to connect to the device and hit submit. It will detect the number of connected amplifiers and present each zone as an {% term entity %}.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/wyoming.markdown
> +The Wyoming {% term integration %} connects external voice services to Home Assistant using a [small protocol](https://github.com/rhasspy/rhasspy3/blob/master/docs/wyoming.md). This enables [Assist](
```suggestion
The **Wyoming** {% term integration %} connects external voice services to Home Assistant using a [small protocol](https://github.com/rhasspy/rhasspy3/blob/master/docs/wyoming.md). This enables [Assist](/voice_control/) to use a variety of local [speech-to-text](/integrations/stt/), [text-to-speech](/integrations/tts/), and [wake-word-detection](/integrations/wake_word/) systems, such as:
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/xiaomi_aqara.markdown
> +The ***Xiaomi Gateway (Aqara)* {% term integration %} allows you to integrate [Xiaomi](https://www.mi.com/en/) Aqara-compatible devices into Home Assistant.
```suggestion
The **Xiaomi Gateway (Aqara)** {% term integration %} allows you to integrate [Xiaomi](https://www.mi.com/en/) Aqara-compatible devices into Home Assistant.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/yalexs_ble.markdown
> +Some locks only send push updates when they have an active HomeKit pairing. If your lock is not sending push updates, ensure it's paired with a HomeKit using an iOS device or the HomeKit controller i
```suggestion
Some locks only send push updates when they have an active HomeKit pairing. If your lock is not sending push updates, ensure it's paired with a HomeKit using an iOS device or the HomeKit controller {% term integration %}. The lock cannot be paired via HomeKit Controller and the Yale Access Bluetooth {% term integration %} on the same Home Assistant instance as they will both try to access the lock simultaneously and fail.
```

2023-11-19 13:00 UTC, joostlek commented on source/_integrations/yamaha_musiccast.markdown
> +  - One number ent{% term entity %}ity each is added for bass and treble
```suggestion
  - One number {% term entity %} each is added for bass and treble
```

2023-11-19 13:06 UTC, c0ffeeca7 commented on source/_integrations/wallbox.markdown
>  - Added Energy
nice catch. Let me fix those in a bit.

2023-11-19 13:08 UTC, c0ffeeca7 commented on source/_integrations/wilight.markdown
>  There are several services which can be used for automations and control of the Irrigation:
haha, good point. true, they are. But for the most part, I didn't link those yet. I wanted to finish at some point today and go play outside.

2023-11-19 13:22 UTC, joostlek commented on source/_integrations/wilight.markdown
>  There are several services which can be used for automations and control of the Irrigation:
Fair haha

2023-11-19 13:22 UTC, joostlek commented on source/_integrations/universal.markdown
> +title: Universal media player
https://github.com/home-assistant/core/pull/104204

2023-11-19 13:42 UTC, joostlek approved these changes

2023-11-19 13:43 UTC, merged