Improve v2c documentation
home-assistant/home-assistant.github.io pull request #29975
Opened 2023-11-23 11:15 UTC by dgomes

## Proposed change

Small update to existing documentation

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-11-23 11:17 UTC, joostlek requested changes

2023-11-23 11:17 UTC, joostlek commented on source/_integrations/v2c.markdown
> +- [Binary Sensor](#binary-sensor)
```suggestion
- [Binary sensor](#binary-sensor)
```

2023-11-23 11:18 UTC, joostlek approved these changes

2023-11-24 07:20 UTC, c0ffeeca7 commented
@dgomes, this PR is not related to a parent PR but updates existing documentation. Is there a particular reason you pointed it at *next* and not the *current* branch?

2023-11-24 07:20 UTC, merged