Updated Withings app creation steps
home-assistant/home-assistant.github.io pull request #29984
Opened 2023-11-23 20:27 UTC by dannytsang

## Proposed change
New developer application creation steps on Withings' site.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #29971

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-11-23 21:39 UTC, joostlek requested changes

2023-11-23 21:39 UTC, joostlek commented on source/_integrations/withings.markdown
> +  - Registered URLs: [replace with your Home Assistant address e.g. https://my.home-assistant.io/redirect/oauth]
This is incorrect, it should always be the my.home-assistant link unless you disabled the my integration (for which there is a section below)

2023-11-24 11:48 UTC, closed without merging

2023-11-24 11:48 UTC, frenck commented
Joost is right on this one, going to close it on this end 👍 

../Frenck

2023-11-24 12:03 UTC, joostlek commented
I mean the rest of the steps are correct (and if I understand the issue correctly we still should change the docs) but only this step was incorrect