Add config flow for LG Netcast
home-assistant/home-assistant.github.io pull request #30110
Opened 2023-12-02 20:31 UTC by splinter98

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-02-01 00:00 UTC, Drafteed commented on source/_integrations/lg_netcast.markdown
> +Any other [actions](/docks/automation/action/) to power on the device can be configured.
Typo in the URL:

```suggestion
Any other [actions](/docs/automation/action/) to power on the device can be configured.
```

2024-02-04 04:07 UTC, Drafteed approved these changes

2024-05-22 13:11 UTC, c0ffeeca7 requested changes
Small style tweaks

2024-05-22 13:11 UTC, c0ffeeca7 commented on source/_integrations/lg_netcast.markdown
> +Home Assistant is able to turn on an LG Netcast TV is you specify an action, provided by an {% term integration %} like [HDMI-CEC](/integrations/hdmi_cec/) or [WakeOnLan](/integrations/wake_on_lan/).
```suggestion
Home Assistant can turn on an LG Netcast TV if you specify an action provided by an {% term integration %} like [HDMI-CEC](/integrations/hdmi_cec/) or [WakeOnLan](/integrations/wake_on_lan/).
```

2024-05-22 13:11 UTC, c0ffeeca7 commented on source/_integrations/lg_netcast.markdown
>  The example below shows how you can use the `turn_on_action` the [`wake_on_lan` integration](/integrations/wake_on_lan/).
```suggestion
The example below shows how you can use the `turn_on_action` with the [`wake_on_lan` integration](/integrations/wake_on_lan/).
```

2024-05-22 13:11 UTC, c0ffeeca7 commented on source/_integrations/lg_netcast.markdown
> +You can create an automation from the user interface, from the device create a new automation and select the **Device is requested to turn on** automation.
```suggestion
1. To create an automation, go to {% my integrations title="**Settings** > **Devices & services**" %} and open the device page. 
2. Under **Automations**, select the + icon to create an automation with that device.
3. In the dialog, select the **Device is requested to turn on** automation.

```

2024-05-22 13:13 UTC, c0ffeeca7 approved these changes
Thank you, @splinter98 :+1:

2024-05-22 13:34 UTC, merged