Update documentation for Digital Ocean - HA PR #89800
home-assistant/home-assistant.github.io pull request #30166
Opened 2023-12-05 13:59 UTC by phrfpeixoto

## Proposed change

Update the DigitalOcean Integration docs to add information about the new DNS Update service, which is being implemented on https://github.com/home-assistant/core/pull/89800

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/89800
- Link to parent pull request in the Brands repository: N/A
- This PR fixes or closes issue: N/A

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-12-05 14:17 UTC, FletcherAU requested changes
Couple of slight suggestions :)

2023-12-05 14:17 UTC, FletcherAU commented on source/_integrations/digital_ocean.markdown
> +Currently only A and CNAME records are supported. The service can be called either from the Developer-Tools UI, as well as from within integrations.
```suggestion
Currently only A and CNAME records are supported. The service can be called either from the Developer Tools UI, or from within integrations.
```
Slight suggestion

2023-12-05 14:17 UTC, FletcherAU commented on source/_integrations/digital_ocean.markdown
> +Example call within the Developer-Tools UI:
```suggestion
Example call within the Developer Tools UI:
```

2023-12-05 14:23 UTC, FletcherAU requested changes

2023-12-05 14:23 UTC, FletcherAU commented on source/_integrations/digital_ocean.markdown
> +This integration offers a service to execute {% term DNS %} record updates on any domain hosted on your [DigitalOcean Networking](https://cloud.digitalocean.com/networking/domains) section.
Looks like you've used the glossary/term template for a term that's not yet in the glossary. It would need to be added to `/source/_data/glossary.yml`

2023-12-05 16:09 UTC, phrfpeixoto commented on source/_integrations/digital_ocean.markdown
> +Example call within the Developer-Tools UI:
Done.

2023-12-05 16:10 UTC, phrfpeixoto commented on source/_integrations/digital_ocean.markdown
> +This integration offers a service to execute {% term DNS %} record updates on any domain hosted on your [DigitalOcean Networking](https://cloud.digitalocean.com/networking/domains) section.
I've added those now.

2023-12-05 16:13 UTC, FletcherAU commented on source/_data/glossary.yml
> +    DNS servers make it possible for people to input normal words into their browsers, such as homeassistant.com,
```suggestion
    DNS servers make it possible for people to input normal words into their browsers, such as home-assistant.io, 
```

2023-12-05 16:17 UTC, FletcherAU commented
Ayy there we go, checks are passing now :)

2024-07-05 15:37 UTC, frenck commented
Closing PR as the parent PR has been closed.

2024-07-05 15:37 UTC, closed without merging