Deprecate service list_events in favor of get_events
home-assistant/home-assistant.github.io pull request #30196
Opened 2023-12-07 08:37 UTC by c0ffeeca7

## Proposed change

Deprecate service list_events in favor of get_events

- The service `calendar.list_events` is deprecated in favor or `calendar.get_events`
- in 2023.12. Scheduled to be removed in 2024.6
- This PR adds a note that this service is deprecated
- The docs for `get_events` are a topic for a separate PR
- Unlike list_events, get_events supports multiple responses
- This PR belongs into current because the parent has already been deployed.
- related parent PR in core: https://github.com/home-assistant/core/pull/102481

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-12-07 10:01 UTC, frenck commented on source/_integrations/calendar.markdown
> +This service has been **deprecated**. It will be removed in a future release of Home Assistant. Please use `calendar.get_events` instead.
We should just remove the deprecated service from the documentation.

2023-12-07 13:53 UTC, mikeodr approved these changes

2023-12-07 13:55 UTC, c0ffeeca7 commented
Thank you, @mikeodr

2023-12-08 07:52 UTC, MartinHjelmare requested changes

2023-12-08 07:52 UTC, MartinHjelmare commented on source/_docs/scripts/service-calls.markdown
> +service: calendar.get_events
We should update the notify.gmail example below too as it consumes the response variable set in this example.

```yaml
service: notify.gmail_com
data:
  target: "gduser1@workspacesamples.dev"
  title: "Daily agenda for {{ now().date() }}"
  message: >-
    Your agenda for today:
    <p>
    {% for event in agenda['calendar.school'].events %}
    {{ event.start}}: {{ event.summary }}<br>
    {% endfor %}
    </p>
```

2023-12-14 09:18 UTC, MartinHjelmare approved these changes
Thanks!

2023-12-14 09:19 UTC, merged