Update Zigbee device limitation in zha.markdown
home-assistant/home-assistant.github.io pull request #30217
Opened 2023-12-08 08:23 UTC by Hedda

Update Zigbee devices limitations in zha.markdown

## Proposed change

Update device limitation in ZHA documenation, clearifying that Zigbee devices can only connect to a single Zigbee Coordinator,

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-12-13 15:59 UTC, frenck requested changes, later dismissed

2023-12-13 15:59 UTC, frenck commented on source/_integrations/zha.markdown
> +Any Zigbee device can only be connected to a single Zigbee Coordinator (i.e. only one Zigbee gateway). This is a limitation in the current (as well as previous) Zigbee protocol specifications, govern
```suggestion
Any Zigbee device can only be connected to a single Zigbee Coordinator (only one Zigbee gateway). This is a limitation in the current (as well as previous) Zigbee protocol specifications, governed by the [CSA (Connectivity Standards Alliance)](https://csa-iot.org/all-solutions/zigbee/). As such, it is a limit that applies to all Zigbee implementations, not just the ZHA implementation.
```

2024-02-02 13:04 UTC, puddly approved these changes

2024-02-02 13:05 UTC, c0ffeeca7 approved these changes
Thank you, @Hedda :+1:

2024-02-02 13:06 UTC, merged