fix container disable  jemalloc example
home-assistant/home-assistant.github.io pull request #30239
Opened 2023-12-09 16:39 UTC by TaiPhamD

1. environment tag should be a child of the service homeassistant tag
2. environment variable value is set with equal sign and not :

## Proposed change
### error
<img width="649" alt="Screenshot 2023-12-09 at 8 34 45 AM" src="https://github.com/home-assistant/home-assistant.io/assets/10516699/889bced9-79e7-4ddb-82fc-4934e93fb6ab">

### after syntax 
<img width="541" alt="Screenshot 2023-12-09 at 8 37 19 AM" src="https://github.com/home-assistant/home-assistant.io/assets/10516699/f7bfbbe2-1e6b-439b-bbaf-5577a89c08b8">

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/TaiPhamD/home-assistant.io
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-12-10 23:26 UTC, mnoorenberghe approved these changes

2023-12-11 07:52 UTC, frenck requested changes

2023-12-11 07:52 UTC, frenck commented on source/_includes/installation/container.md
> +          - DISABLE_JEMALLOC=true
Both mappings and array syntax can be used. The mapping syntax is the modern one and I suggest to stick with that.

That said, the example indeed contained an error as it mixed them up. This is the right syntax:

```suggestion
        environment:
          DISABLE_JEMALLOC: true
```

2023-12-11 08:04 UTC, frenck approved these changes
Thanks, @TaiPhamD 👍 

../Frenck

2023-12-11 08:04 UTC, merged