add config flow setup
home-assistant/home-assistant.github.io pull request #30340
Opened 2023-12-14 19:41 UTC by miaucl

## Proposed change
The integration has been updated with a config flow and the `yaml` setup will be getting deprecated.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/105648

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2023-12-21 19:39 UTC, gjohansson-ST requested changes, later dismissed

2023-12-21 19:39 UTC, gjohansson-ST commented on source/_integrations/swiss_public_transport.markdown
> +  - '@miaucl'
Missing `ha_config_flow` in the header

2023-12-21 19:39 UTC, gjohansson-ST commented on source/_integrations/swiss_public_transport.markdown
> +**DEPRECATED:** Or add the data to your `configuration.yaml` file as shown in the example:
yaml configuration should be removed

2023-12-22 05:24 UTC, c0ffeeca7 approved these changes
Nice! Thank you, @miaucl :+1:

2023-12-22 05:27 UTC, merged