Explains Riemann Integration methods
home-assistant/home-assistant.github.io pull request #30595
Opened 2024-01-01 18:43 UTC by dgomes

## Proposed change

Attempts to address #30368 by providing more information about methods and the functioning of the integration

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #30368

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-01-02 01:38 UTC, cadamini commented on source/_integrations/integration.markdown
> +Regardless of the method used the integration will be more accurate if the source updates more often. If your source is not updated, neither will the Riemann Sum sensor will, as all this integration
```suggestion
Regardless of the method used the integration will be more accurate if the source updates more often. If your source is not updated, neither will the Riemann Sum sensor, as all this integration does is calculate the next step on the event of a source update.
```

2024-01-02 01:46 UTC, dgomes commented on source/_integrations/integration.markdown
> +Regardless of the method used the integration will be more accurate if the source updates more often. If your source is not updated, neither will the Riemann Sum sensor will, as all this integration
Thank you!

2024-01-05 23:06 UTC, dannytsang requested changes

2024-01-05 23:06 UTC, dannytsang commented on source/_integrations/integration.markdown
> +Riemann Sum is a approximation of an integral by a finite sum and is therefore intrinsicaly innacurate, nonetheles, depending on the method used, values can be more or less accurate.
```suggestion
Riemann Sum is a approximation of an integral by a finite sum and is therefore intrinsically inaccurate, nonetheless, depending on the method used, values can be more or less accurate.
```

2024-01-05 23:06 UTC, dannytsang commented on source/_integrations/integration.markdown
> +The `left` method follows the [Left rule](https://en.wikipedia.org/wiki/Riemann_sum#Left_rule). The method **underestimates** the intrinsic source, but is extremely accurate at estimating rectangular
```suggestion
The `left` method follows the [Left rule](https://en.wikipedia.org/wiki/Riemann_sum#Left_rule). The method **underestimates** the intrinsic source, but is extremely accurate at estimating rectangular functions which are very stable for long periods of time and change very rapidly (e.g. such as the power function of a resistive load can jump instantly to a given value and stay at the same value for hours). If your source keeps its state for long periods of time, this method is preferable to the `trapezoidal`.
```

2024-01-05 23:17 UTC, dgomes commented on source/_integrations/integration.markdown
> +Riemann Sum is a approximation of an integral by a finite sum and is therefore intrinsicaly innacurate, nonetheles, depending on the method used, values can be more or less accurate.
tks

2024-01-06 10:40 UTC, dannytsang approved these changes

2024-01-06 10:41 UTC, dannytsang commented
Thank you @dgomes

2024-01-06 10:41 UTC, merged