Update ZHA reporting issues instructions
home-assistant/home-assistant.github.io pull request #30612
Opened 2024-01-03 10:57 UTC by Hedda

## Proposed change

Update ZHA reporting issues instructions, (which did not contain any information on where to report issues with ZHA).

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-01-03 11:06 UTC, frenck requested changes

2024-01-03 11:06 UTC, frenck commented on source/_integrations/zha.markdown
> +If you found what looks to be a bug with the underlying component for the ZHA integration, please report it to the [Issues tracker for Home Assistant Core](https://github.com/home-assistant/core/issu
This is not information integrations needs to document.

2024-01-03 11:07 UTC, frenck commented
I'm not in favor of adding this at all. We have centralized instructions on where to go for issues. Having each integration adding their own versions, makes it really hard to maintain and hard to be consistent.

2024-01-03 11:51 UTC, Hedda commented
> I'm not in favor of adding this at all. We have centralized instructions on where to go for issues.

OK, I have now removed all information that are in centralized instructions with a link to it instead.

2024-01-08 12:10 UTC, frenck approved these changes
Thanks, @Hedda 👍 

../Frenck

2024-01-08 12:10 UTC, merged