Add Matter livestream
home-assistant/home-assistant.github.io pull request #30647
Opened 2024-01-04 19:31 UTC by GuySie

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-01-04 19:42 UTC, marcelveldt approved these changes, later dismissed
One comment I have is if the event shouldn't be preregistered and linked in the article ?

2024-01-05 10:47 UTC, frenck requested changes
The filename needs adjustments too

2024-01-05 10:47 UTC, frenck commented on source/_posts/2024-01-04-matter-livestream.markdown
> +date_formatted: "January 4, 2024"
```suggestion
date: 2024-01-05 00:00:01
date_formatted: "January 5, 2024"
```

2024-01-05 10:52 UTC, frenck approved these changes
Thanks, @GuySie 👍 

../Frenck

2024-01-05 10:55 UTC, merged