Add example automation using the schedule helper
home-assistant/home-assistant.github.io pull request #30668
Opened 2024-01-05 21:52 UTC by dannytsang

## Proposed change
Per title and feedback from #30615

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #30615

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-01-08 09:35 UTC, frenck requested changes, later dismissed

2024-01-08 09:35 UTC, frenck commented on source/_integrations/schedule.markdown
> +A schedule creates an on/off (binary) sensor within the times set. Using the Thermostat schedule example above, you can turn on your thermostat:
```suggestion
### Automation example

A schedule creates an on/off (binary) sensor within the times set. Using the thermostat schedule example above, you can turn on your thermostat:
```

2024-01-08 09:35 UTC, frenck commented on source/_integrations/schedule.markdown
> +      data: {}
```suggestion
```

2024-01-10 13:07 UTC, c0ffeeca7 approved these changes
Nice! Thank you, @dannytsang :+1:

2024-01-10 13:08 UTC, merged