Add documentation for the Elvia integration
home-assistant/home-assistant.github.io pull request #30688
Opened 2024-01-06 21:39 UTC by ludeeus

## Proposed change

Documentation for https://github.com/home-assistant/core/pull/107405

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/107405
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-01-06 21:39 UTC, ludeeus commented on source/_integrations/elvia.markdown
> +ha_release: 9999.9 #placeholder version
Placeholder version, needs replacement.

2024-01-08 08:18 UTC, frenck requested changes

2024-01-08 08:18 UTC, frenck commented on source/_integrations/elvia.markdown
> +The Elvia integration will import you grid consumption.
```suggestion
The Elvia integration will import your grid consumption.
```

2024-01-08 08:18 UTC, frenck commented on source/_integrations/elvia.markdown
> +## Setup
```suggestion
## Prerequisites
```

2024-01-08 08:18 UTC, frenck commented on source/_integrations/elvia.markdown
> +6. Copy the token shown in the dialog, and paste that in the integration configuration.
```suggestion
1. Start by logging in to your [Min side](https://www.elvia.no/logg-inn/).
2. Once logged in, select your main account (Usually the one with your name on it).
3. Select the **Tilganger** tab.
4. Under the "" section, select the **Opprett token for målerverdier i API**.
5. In the dialog, select the meter(s) ([see note below about multiple meters](#multiple-meters-for-a-single-api-token)) you want to import values for, give it a name (like "Home Assistant integrasjon") and use the **Opprett** button to create your token.
6. Copy the token shown in the dialog, and paste that in the integration configuration.
```

2024-01-08 08:18 UTC, frenck commented on source/_integrations/elvia.markdown
> +The first time it runs the data for the past year will be imported.
```suggestion
The first time it runs, the data for the past year will be imported.
```

2024-01-08 08:18 UTC, frenck commented on source/_integrations/elvia.markdown
> +So if you are using the same token for multiple meters, you need to add the integration multiple times and selecting a different meter each time.
```suggestion
While you can select multiple meters when you create your token, the integration will only allow 1 meter for each configuration.
So if you are using the same token for multiple meters, you must add the integration multiple times and select a different meter each time.
```

2024-01-08 08:26 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2024-01-08 08:27 UTC, ludeeus commented
Thanks @frenck !
> The ha_release might need an update before merging this one in.

might? 😂 

As its currently 9999.9 it definitely needs an update 😄

2024-01-08 08:29 UTC, frenck commented
Yeah... there is quite a slight high probability it might maybe need an update... 😁

2024-01-31 13:48 UTC, edenhaus requested changes

2024-01-31 13:48 UTC, edenhaus commented on source/_integrations/elvia.markdown
> +ha_release: 9999.9 #placeholder version
```suggestion
ha_release: 2024.2
```

2024-01-31 13:50 UTC, edenhaus approved these changes

2024-01-31 13:51 UTC, merged