Fix Alexa smart home supported platforms again
home-assistant/home-assistant.github.io pull request #30821
Opened 2024-01-13 17:58 UTC by IceBotYT

## Proposed change

Fix the supported platforms from being another table of contents to just the supported platforms.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-01-13 22:36 UTC, jbouwh requested changes
This part is auto generated and it is on at the top at the page as well. This part should be removed instead. It does not need a header.

2024-01-13 22:42 UTC, jbouwh commented on source/_integrations/alexa.smart_home.markdown
> +  - [Operation Mode](#operation-mode)
```suggestion
```

2024-01-14 13:50 UTC, jbouwh commented
Alternative approach for this PR:
https://github.com/home-assistant/home-assistant.io/pull/30831

It completely removes the redundant table of contents.

2024-01-15 04:22 UTC, c0ffeeca7 commented
Going to close this PR as completed by #30831.

2024-01-15 04:22 UTC, closed without merging