Add write_registers support for Fan Mode
home-assistant/home-assistant.github.io pull request #30838
Opened 2024-01-14 21:51 UTC by crug80

## Proposed change

Add doc for write_registers parameter that it is a new feature of the Fan Mode modbus climate Entity

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/108053
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-01-17 10:26 UTC, janiversen requested changes

2024-01-17 10:26 UTC, janiversen commented on source/_integrations/modbus.markdown
> +        write_registers:
As requested in the code, please do not add a new parameter....make the address an int or an array.

2024-01-24 18:30 UTC, janiversen approved these changes
LGTM, thanks

2024-01-24 20:01 UTC, klaasnicolaas approved these changes
✅ Approved.

2024-01-24 20:02 UTC, merged