Add new virtual integration for opower City of Austin Utilities provider
home-assistant/home-assistant.github.io pull request #30923
Opened 2024-01-19 02:50 UTC by max2697

## Proposed change

Add new virtual integration for opower City of Austin Utilities provider
Related to PR https://github.com/home-assistant/home-assistant.io/pull/30840 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/108337
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-01-19 10:40 UTC, frenck requested changes
This PR is missing a PR upstream in our brands repository.

Please create a PR there and link it up with the parent PRs here and in Core.

2024-01-21 00:04 UTC, max2697 commented
@frenck Created new PR for brands: https://github.com/home-assistant/brands/pull/5114

2024-01-21 19:39 UTC, tronikos commented on source/_integrations/coautilities.markdown
> +ha_domain: oru_opower
update

2024-01-22 01:04 UTC, max2697 commented on source/_integrations/coautilities.markdown
> +ha_domain: oru_opower
Fixed

2024-01-22 05:57 UTC, tronikos approved these changes

2024-01-28 18:54 UTC, frenck approved these changes
Thanks, @max2697 👍 

../Frenck

2024-01-28 18:54 UTC, merged