Update backup.markdown for backup example modification
home-assistant/home-assistant.github.io pull request #30968
Opened 2024-01-21 13:05 UTC by grzesiczek1

Previous backup example when imported to automation.yaml was resulting in validation failure due to lack of ID. This updates proposes example to add ID value and structure as per default at version 2024.1.5

## Proposed change
Previous backup example when imported to automation.yaml was resulting in validation failure due to lack of ID. This update proposes example with added ID value and structure as per default at version 2024.1.5

## Type of change
- [  ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [  ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [  ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [  ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [  ] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: N/A
- Link to parent pull request in the Brands repository: N/A
- This PR fixes or closes issue: fixes N/A

## Checklist
- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [  ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-01-22 19:48 UTC, klaasnicolaas requested changes

2024-01-22 19:48 UTC, klaasnicolaas commented on source/_integrations/backup.markdown
> +ha_release: 2024.1.5
Please revert this change

2024-01-24 11:24 UTC, frenck commented on source/_integrations/backup.markdown
> +- id: '1702841556346'
ID's are not required. As a matter of fact, documenting them may result in duplicate IDs being used.

2024-01-24 11:24 UTC, frenck commented on source/_integrations/backup.markdown
> +  alias: Backup Home Assistant every night at 3 AM
You've removed the quoting required in our YAML style guidelines.

2024-01-24 11:24 UTC, frenck commented on source/_integrations/backup.markdown
> +  description: Create Backup
Description is optional and has no value for this example; adding this doesn't help.

2024-01-24 11:24 UTC, frenck commented on source/_integrations/backup.markdown
> +    at: 03:00:00
Removed quoting that shouldn't have been removed.

2024-01-24 11:24 UTC, frenck commented on source/_integrations/backup.markdown
> +  condition: []
This is the default, it doesn't add anything to the example. Please remove it.

2024-01-24 11:24 UTC, frenck commented on source/_integrations/backup.markdown
> +    data: {}
these are defaults that do not add anything to the example.

2024-01-24 11:24 UTC, frenck commented on source/_integrations/backup.markdown
> +  mode: single
This is the default as well.

2024-01-24 11:25 UTC, frenck commented
Considering the above notes (which are all unneeded or changes that are not matching our YAML style guides) and the unneeded addition of the unique ID, I'll go ahead and close up this PR.

Nevertheless, thanks for being willing to contribute!

../Frenck

2024-01-24 11:25 UTC, closed without merging