Fix secure inclusion  section. Source: AlCalzone
home-assistant/home-assistant.github.io pull request #30990
Opened 2024-01-22 13:21 UTC by c0ffeeca7

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-01-22 13:26 UTC, AlCalzone requested changes

2024-01-22 13:26 UTC, AlCalzone commented on source/_integrations/zwave_js.markdown
> +S2 security does not impose additional network traffic and provides additional benefits. For example, end devices using S2 require the hub to report whether it has received and understood their repor
```suggestion
Security S2 does not impose additional network traffic and provides additional benefits. For example, end devices using S2 require the hub to report whether it has received and understood their reports.
```
this is the "official" name

2024-01-22 13:26 UTC, AlCalzone commented on source/_integrations/zwave_js.markdown
> +By default, Z-Wave prefers S2 security, if supported. S0 is used only when absolutely necessary.
dito

2024-01-22 13:28 UTC, c0ffeeca7 commented on source/_integrations/zwave_js.markdown
> +By default, Z-Wave prefers S2 security, if supported. S0 is used only when absolutely necessary.
```suggestion
By default, Z-Wave prefers Security S2, if supported. Security S0 is used only when absolutely necessary.
```

2024-01-22 13:29 UTC, AlCalzone approved these changes

2024-01-24 08:04 UTC, frenck approved these changes
Thanks, @c0ffeeca7 👍 

../Frenck

2024-01-24 08:04 UTC, merged