Add documentation for microBees integration
home-assistant/home-assistant.github.io pull request #31021
Opened 2024-01-24 10:08 UTC by marcolettieri

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/108764  https://github.com/home-assistant/core/pull/99573
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/4645
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-02-19 14:12 UTC, joostlek commented
Please open a PR for the brands repository.

2024-02-19 14:14 UTC, joostlek requested changes, later dismissed

2024-02-19 14:14 UTC, joostlek commented on source/_integrations/microbees.markdown
> +ha_release: 0.1.0
```suggestion
ha_release: 2024.3
```

2024-02-19 14:14 UTC, joostlek commented on source/_integrations/microbees.markdown
> +  - light
```suggestion
```

2024-02-19 14:14 UTC, joostlek commented on source/_integrations/microbees.markdown
> +The `microbees` integration allows you to control your [microBees devices](https://www.microbees.com/) such as plugs, wall switches and bulbs.
```suggestion
The microbees integration allows you to control your [microBees devices](https://www.microbees.com/) such as plugs and wall switches.
```

2024-02-19 14:14 UTC, joostlek commented on source/_integrations/microbees.markdown
> +To retrieve the OAuth2 Client ID and Client Secret go to [microBees Developer Dashboard](https://developers.microbees.com/dashboard), login with your microBees account and [create a new app](https://
What's a "Label"?

2024-02-19 14:20 UTC, marcolettieri commented on source/_integrations/microbees.markdown
> +To retrieve the OAuth2 Client ID and Client Secret go to [microBees Developer Dashboard](https://developers.microbees.com/dashboard), login with your microBees account and [create a new app](https://
A label for the Oauth Client

2024-02-19 14:22 UTC, marcolettieri commented
> Please open a PR for the brands repository.

@joostlek 
Here the PR for brand, was also accepted but closed
https://github.com/home-assistant/brands/pull/4645

2024-02-19 14:22 UTC, joostlek commented
That brands PR is adding brands for a custom integration, but they should be added to the core integrations. Please open a new one and correct it

2024-02-22 13:39 UTC, klaasnicolaas requested changes
Keep this PR limited to the platforms created in your initial core PR, you can re-add all platforms you added later via a separate PR.

2024-02-22 14:57 UTC, klaasnicolaas requested changes
The sensor platform was also added in a later PR and therefore does not belong in this one.

Instead of just naming the supported platform, you could also describe what a user can do with, for example, the switch entity.

2024-02-22 14:57 UTC, klaasnicolaas commented on source/_integrations/microbees.markdown
> +
```suggestion
```

2024-02-22 14:57 UTC, klaasnicolaas commented on source/_integrations/microbees.markdown
> +
```suggestion
```

2024-02-22 14:57 UTC, klaasnicolaas commented on source/_integrations/microbees.markdown
> +
```suggestion
```

2024-02-22 15:44 UTC, klaasnicolaas requested changes
Remove also the extra blank lines

2024-02-22 15:44 UTC, klaasnicolaas commented on source/_integrations/microbees.markdown
> +
```suggestion
```

2024-02-22 15:44 UTC, klaasnicolaas commented on source/_integrations/microbees.markdown
> +
```suggestion
```

2024-02-22 15:44 UTC, klaasnicolaas commented on source/_integrations/microbees.markdown
> +
```suggestion
```

2024-02-22 16:21 UTC, klaasnicolaas approved these changes

2024-02-22 16:48 UTC, merged