Add binary sensors to TechnoVE integration
home-assistant/home-assistant.github.io pull request #31095
Opened 2024-01-27 21:00 UTC by Moustachauve

## Proposed change
This updates the documentation of the TechnoVE integration for the new binary sensors

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-01-29 10:58 UTC, gjohansson-ST requested changes
Atleast `ha_platforms` needs to be updated in the header section

2024-01-30 03:48 UTC, Moustachauve commented
`ha_platforms` has been updated.

2024-01-30 06:06 UTC, c0ffeeca7 commented on source/_integrations/technove.markdown
> +## Binary Sensors
```suggestion
## Binary sensors
```
Tiny tweak. We use sentence-style capitalization also in headings.

2024-01-30 06:07 UTC, c0ffeeca7 approved these changes
Thank you, @Moustachauve and @gjohansson-ST :+1:

2024-01-30 06:09 UTC, gjohansson-ST approved these changes

2024-01-30 06:10 UTC, merged