Update tuya.markdown with instructions for new user code functionality
home-assistant/home-assistant.github.io pull request #31212
Opened 2024-02-03 06:40 UTC by codyc1515

## Proposed change
The steps described were incomplete for me. I was not able to follow them as written. I am using the Tuya Smart app, which may be why there were different (i.e. if they were written for Smart Life).

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-02-03 06:41 UTC, codyc1515 commented
Not sure why the bot is saying that.

2024-02-04 18:56 UTC, frenck requested changes

2024-02-04 18:56 UTC, frenck commented on source/_integrations/tuya.markdown
> +Tuya Smart app. You can find it by opening the app and:
```suggestion
### Obtaining User Code for sign-in

To sign-in, you will need to get your **User Code** from the Smart Life /
Tuya Smart app. You can find it by opening the app and:
```

2024-02-04 18:56 UTC, frenck commented on source/_integrations/tuya.markdown
> +5. Enter this in Home Assistant exactly as shown (it is case-sensitive)
Removed step 5, as the user isn't there yet at this point.

```suggestion
1. On the tab bar, select **Me**.
2. Select the **⚙️ (gear)** icon in the top-right corner.
3. Tap **Account and Security**.
4. At the bottom, **User Code** will be shown; you need to when setting up this integration.
```

2024-02-04 19:28 UTC, codyc1515 commented
Thank you for the feedback. I have incoporated that now.

2024-02-04 19:30 UTC, frenck approved these changes
Thanks, @codyc1515 👍 

../Frenck

2024-02-04 19:35 UTC, merged