GeoRSS sensor
home-assistant/home-assistant.github.io pull request #3124
Opened 2017-08-02 12:48 UTC by exxamalte

**Description:**
Generic GeoRSS events service
Retrieves current events (typically incidents or alerts) in GeoRSS format, and
shows information on events filtered by distance to the HA instance's location
and grouped by category.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#8789

2017-08-04 08:16 UTC, Landrash approved these changes
Looks good and na be merged when parent PR is merged. :fire:

2017-08-18 07:27 UTC, Landrash approved these changes

2017-09-07 00:20 UTC, exxamalte commented
New code pull request https://github.com/home-assistant/home-assistant/pull/9322 due to issues with cla-bot.

2017-09-24 06:16 UTC, MartinHjelmare requested changes

2017-09-24 06:16 UTC, MartinHjelmare commented on source/_components/sensor.geo_rss_events.markdown
> +ha_version: 0.52
0.55

2017-09-24 11:06 UTC, MartinHjelmare approved these changes

2017-09-24 11:07 UTC, merged