airzone_cloud: document Air Quality binary_sensor
home-assistant/home-assistant.github.io pull request #31531
Opened 2024-02-21 15:38 UTC by Noltari

## Proposed change
Document Airzone Cloud Air Quality active binary_sensor.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/106573
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-02-21 19:09 UTC, davet2001 requested changes
Suggested improvement to capitalisation and extra clarification word.

2024-02-21 19:09 UTC, davet2001 commented on source/_integrations/airzone_cloud.markdown
> +| air_quality_active  | Indicates that the Air Quality is running.              |
```suggestion
| air_quality_active  | Indicates that the air quality control is running.              |
```

2024-02-22 07:26 UTC, davet2001 approved these changes
Looks good! Thanks @Noltari 👍

2024-03-20 09:29 UTC, c0ffeeca7 approved these changes
Thank you, @Noltari and @davet2001 :+1:

2024-03-20 09:29 UTC, merged