added cover platform to microBees Integration
home-assistant/home-assistant.github.io pull request #31568
Opened 2024-02-22 18:34 UTC by marcolettieri

## Proposed change

added cover platform to microBees Integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/111135
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-03-05 15:00 UTC, klaasnicolaas submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

2024-03-06 17:05 UTC, jpbede requested changes
Please add a note as comment in core PR (https://github.com/home-assistant/core/pull/111135#discussion_r1514033176), that the cover entity will be unknown

2024-03-06 17:19 UTC, jpbede requested changes
There was no change to the documentation. Please see my comment above

2024-03-06 17:36 UTC, jpbede requested changes, later dismissed
Please do not mark a PR as "Ready for review" if it actually is not. Please include a note in the documentation that the cover entity remains in the `unknown` state, as I described in the core PR (https://github.com/home-assistant/core/pull/111135#discussion_r1514033176), otherwise we might get a lot "why is this entity unknown" issues. After addressing my comment, you can mark this as "Ready for review".

2024-03-07 06:17 UTC, marcolettieri commented
> Please do not mark a PR as "Ready for review" if it actually is not. Please include a note in the documentation that the cover entity remains in the `unknown` state, as I described in the core PR ([home-assistant/core#111135 (comment)](https://github.com/home-assistant/core/pull/111135#discussion_r1514033176)), otherwise we might get a lot "why is this entity unknown" issues. After addressing my comment, you can mark this as "Ready for review".

we have added in note in the PR. Anyway now we will add also to comments

2024-03-25 08:02 UTC, c0ffeeca7 commented on source/_integrations/microbees.markdown
> +ha_category:  - Switch
```suggestion
ha_category: 
```

2024-03-25 08:02 UTC, c0ffeeca7 commented on source/_integrations/microbees.markdown
> +  - Cover
```suggestion
  - Switch
  - Cover
```

2024-03-25 08:03 UTC, c0ffeeca7 commented on source/_integrations/microbees.markdown
> +ha_category:  - Switch
Tweak to fix the build

2024-03-25 08:09 UTC, c0ffeeca7 commented
@marcolettieri: Please implement the comment by jpbede. I see you added a note in the PR description. But this is not visible in the documentation. You need to add this information to the file itself.

2024-03-25 08:13 UTC, c0ffeeca7 approved these changes
Thank you, @marcolettieri :+1:

2024-03-25 08:14 UTC, c0ffeeca7 commented
@jpbede, are you good with the PR?

2024-03-25 08:53 UTC, jpbede commented
Yes, this is fine now, thanks @marcolettieri 👍

2024-03-25 10:30 UTC, merged