Add button platform and improve other text.
home-assistant/home-assistant.github.io pull request #31609
Opened 2024-02-25 16:44 UTC by yozik04

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/111391
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-02-25 17:51 UTC, slovdahl approved these changes

2024-02-26 11:32 UTC, yozik04 commented
I am sorry, but PR ended up with `button` -> `date` platform change.

2024-03-01 01:31 UTC, klaasnicolaas requested changes

2024-03-01 01:31 UTC, klaasnicolaas commented on source/_integrations/vallox.markdown
> +The **date** platform allows you to set the filter change date.
Think it's better to move this part to under the configuration (config flow) include and use markdown headers.

2024-03-01 19:42 UTC, yozik04 commented
I am not sure if I got your point correctly, but this is what I have now. Previously it was more compact that I liked.

2024-03-01 20:18 UTC, klaasnicolaas commented
This is fine, it is less compact but it will appear neatly in the TOC (table of contents) and you can use a hyperlink directly to part of the docs via the markdown header.

./Klaas

2024-03-01 20:19 UTC, klaasnicolaas submitted a review, later dismissed

2024-03-04 09:03 UTC, c0ffeeca7 commented on source/_integrations/vallox.markdown
> +### Binary Sensor
```suggestion
### Binary sensor
```

2024-03-04 09:04 UTC, c0ffeeca7 approved these changes
Thank you, @yozik04 :+1:

2024-03-04 09:06 UTC, merged