Add event platform to rfxtrx docs
home-assistant/home-assistant.github.io pull request #31636
Opened 2024-02-26 20:18 UTC by elupus

## Proposed change

Add mention of event entities for rfxtrx devices.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/111526
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-03-01 01:26 UTC, klaasnicolaas requested changes

2024-03-01 01:26 UTC, klaasnicolaas commented on source/_integrations/rfxtrx.markdown
> +The RFXtrx integration will expose event entities for remotes controlling lights as well as security devices.
```suggestion
The RFXtrx integration will expose event entities for remotes controlling lights as well security devices.
```

2024-03-01 15:29 UTC, klaasnicolaas requested changes
I made a mistake, `as well as` was fine. Sorry!

2024-03-01 15:29 UTC, klaasnicolaas commented on source/_integrations/rfxtrx.markdown
> +The RFXtrx integration will expose event entities for remotes controlling lights as well security devices.
```suggestion
The RFXtrx integration will expose event entities for remotes controlling lights as well as security devices.
```

2024-03-01 15:30 UTC, klaasnicolaas approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

2024-03-20 09:12 UTC, c0ffeeca7 approved these changes
Thank you, @elupus and @klaasnicolaas :+1:

2024-03-20 09:12 UTC, merged