Update daikin.markdown
home-assistant/home-assistant.github.io pull request #31642
Opened 2024-02-27 06:47 UTC by jwillemsen

## Proposed change

There is now an official API for integrating Daikin devices through the cloud. Added a link to the Daikin Developer Portal.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-02-27 08:13 UTC, jwillemsen commented
I have reworked the daikin_residential_altherma to support the new public API, see https://github.com/jwillemsen/daikin_onecta. Not sure whether this documentation page is the correct place to mention that integration, working on getting it added to HACS

2024-03-01 01:20 UTC, klaasnicolaas requested changes

2024-03-01 01:20 UTC, klaasnicolaas commented on source/_integrations/daikin.markdown
> +  Daikin has removed their local API in newer products. They offer a Onecta cloud API for controlling Daikin devices through the cloud, see the Daikin Europe Developer Portal at https://developer.clo
```suggestion

Daikin has removed their local API in newer products. They offer a Onecta cloud API for controlling Daikin devices through the cloud, see the [Daikin Europe Developer Portal](https://developer.cloud.daikineurope.com) for more details. This affects units fitted with the BRP069C4x wifi adapter. Units listed under Supported Hardware below continue to have access to local control. Additionally the older but commonly available BRP072A42 adapter can be fitted to most if not all newer units for access to local control.

```

2024-03-01 01:24 UTC, klaasnicolaas commented
> Not sure whether this documentation page is the correct place to mention that integration.

The community forum is a suitable place for this, not the Home Assistant docs

2024-03-01 13:35 UTC, klaasnicolaas approved these changes

2024-03-01 13:36 UTC, merged