Add documentation for Overseerr
home-assistant/home-assistant.github.io pull request #31701
Opened 2024-03-01 14:10 UTC by l-holter

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [X] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-03-01 15:03 UTC, klaasnicolaas commented
Missing a link to the PR in the core repository.

./Klaas

2024-03-03 01:26 UTC, klaasnicolaas requested changes

2024-03-03 01:26 UTC, klaasnicolaas commented on source/_integrations/overseerr.markdown
> +This Overseerr integration pulls data from a given [Overseerr](https://overseerr.dev/) instance.
```suggestion
This **Overseerr** {% term integration %} pulls data from a given [Overseerr](https://overseerr.dev/) instance.
```

2024-03-03 01:26 UTC, klaasnicolaas commented on source/_integrations/overseerr.markdown
> +Your API key can be found in Settings > General > API Key in the Overseerr Web UI.
```suggestion
Your API key can be found in **Settings** > **General** > **API Key** in the Overseerr Web UI.
```

2024-03-03 01:26 UTC, klaasnicolaas commented on source/_integrations/overseerr.markdown
> +Make sure to add /api/v1 to your URL in the configuration.
```suggestion
Make sure to add `/api/v1` to your URL in the configuration.
```

2024-03-03 11:36 UTC, l-holter commented on source/_integrations/overseerr.markdown
> +Make sure to add /api/v1 to your URL in the configuration.
Thank you, I have applied the changes:)

2024-03-07 15:22 UTC, frenck commented
Closing PR as the parent PR has been closed.

2024-03-07 15:22 UTC, closed without merging