Jewish Calendar: Document Services
home-assistant/home-assistant.github.io pull request #31770
Opened 2024-03-07 02:11 UTC by SLaks

## Proposed change

Document https://github.com/home-assistant/core/pull/112431

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-03-07 08:52 UTC, tsvi requested changes
Thank you very much, looks like a great idea.
Please rename the services from `for_` to `get_`
get_gregorian_date, get_hebrew_date, get_next_holiday.

2024-03-07 08:54 UTC, tsvi commented on source/_integrations/jewish_calendar.markdown
> +All of these services return the same fields, based on which of the following `include_*` attributes you pass to the service. If you set multiple attributes to true, it will return all of thise field
```suggestion
These services return the same fields, based on the following `include_*` attributes. If you set multiple attributes to true, they will return all these fields.
```

2024-03-07 16:37 UTC, SLaks commented on source/_integrations/jewish_calendar.markdown
> +All of these services return the same fields, based on which of the following `include_*` attributes you pass to the service. If you set multiple attributes to true, it will return all of thise field
Done

2024-03-07 16:37 UTC, SLaks commented
Renamed.

Also added examples.

2024-03-08 00:40 UTC, tsvi approved these changes
Looks very promising. The use for Yahrzeits/birthdays/etc. has been requested by multiple users.

2025-03-13 21:05 UTC, closed without merging