Update sma.markdown
home-assistant/home-assistant.github.io pull request #31792
Opened 2024-03-08 13:22 UTC by littleyoda

Added note regarding unsupported devices.

## Proposed change

It should be mentioned that not all series from SMA are supported by SMA Integration. For example, the SMA Tripower X is not supported.

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ X] Adjusted missing or incorrect information in the current documentation (`current` branch).

## Additional information
- This PR fixes or closes issue: fixes #31791

## Checklist
  [X ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [X ] The documentation follows the Home Assistant documentation [standards].
(I hope so)

2024-03-08 13:24 UTC, rklomp approved these changes

2024-03-11 11:44 UTC, frenck requested changes

2024-03-11 11:44 UTC, frenck commented on source/_integrations/sma.markdown
> +The integration uses the web interface (called webconnect) of the device. Before you start, make sure you are able to connect to the solar inverter from your favorite web browser. Devices with the en
We can not recommend or list custom integrations. We don't support or recommend using them.

2024-03-11 11:44 UTC, frenck commented on source/_integrations/sma.markdown
> +For the SMA Energy Meter and SMA Sunny Home Manager please you the [Home Assistant SMA Add-On](https://github.com/kellerza/hassio-sma-em)
Same for third-party add-ons. Please remove these occurances.

2024-03-12 10:45 UTC, frenck commented on source/_integrations/sma.markdown
> +The integration uses the web interface (called webconnect) of the device. Before you start, make sure you are able to connect to the solar inverter from your favorite web browser. Devices with the en
```suggestion

## Supported Devices

Not all inverters, energy meters and batteries from SMA are supported.

The integration uses the device's web interface (called webconnect). Before you start, make sure you are able to connect to the solar inverter from your favorite web browser. Devices with the ennexos operating system (like the Tripower X series) and all Energy Meters (SMA Energy Meter and SMA Sunny Home Manager) are not supported.
```

2024-03-12 18:04 UTC, frenck approved these changes
Thanks, @littleyoda 👍 

../Frenck

2024-03-12 18:04 UTC, merged