Romy sensor
home-assistant/home-assistant.github.io pull request #31818
Opened 2024-03-10 09:57 UTC by xeniter

## Proposed change

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/112388
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-03-11 11:14 UTC, frenck requested changes

2024-03-11 11:14 UTC, frenck commented on source/_integrations/romy.markdown
> +The **Romy** {% term integrations %} will add the following sensors.
- This is not the first time this term has been introduced.
- No need to emphasize the brand name here?
- 
```suggestion
The Romy will add the following sensors.
```

2024-03-11 11:14 UTC, frenck commented on source/_integrations/romy.markdown
> +- **Total distance driven**: The total distance in m the robot has driven
```suggestion
- **Battery Level**: The battery level in percent.
- **RSSI**: Wi-Fi signal strength.
- **Dustbin Dirt Level**: The raw dustbin dirt sensor value (not every ROMY has one).
- **Total cleaning time**: How many hours the robot has spent cleaning in total.
- **Total cleaning runs**: The total number of cleaning runs.
- **Total cleaned area**: The total area in m² the robot has cleaned.
- **Total distance driven**: The total distance in m the robot has driven.
```

2024-03-20 07:58 UTC, frenck commented on source/_integrations/romy.markdown
> +The Romy will add the following sensors.
```suggestion
The ROMY will add the following sensors.
```

2024-03-20 07:58 UTC, frenck approved these changes, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2024-04-24 15:07 UTC, joostlek submitted a review, later dismissed
There's a merge conflict

2024-04-30 05:08 UTC, c0ffeeca7 approved these changes
Thank you, @xeniter :+1:

2024-04-30 05:09 UTC, merged