Add A6 family code for DS2438 1-Wire sensor
home-assistant/home-assistant.github.io pull request #31816
Opened 2024-03-10 08:51 UTC by definitio

## Proposed change

Add A6 family code for DS2438 1-Wire sensor

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/112844
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-03-10 16:05 UTC, epenet reviewed
It feels very weird to have two separate prefixes for the same device.
Are you 100% sure that this is a DS2438?
Do you have a reference to dallas indicating this?

If it's a "similar" device or a new generation, then please point out the source.

2024-03-11 10:45 UTC, epenet requested changes

2024-03-11 10:45 UTC, epenet commented on source/_integrations/onewire.markdown
> +| A6     | [DS2438](https://datasheets.maximintegrated.com/en/ds/DS2438.pdf)            | Temperature, Voltage, Current (pressure when using B1-R1-A, illuminance when using S2-R1-A, humidity when usi
```suggestion
| A6     | Secondary family code for [DS2438](https://datasheets.maximintegrated.com/en/ds/DS2438.pdf)            | Temperature, Voltage, Current (pressure when using B1-R1-A, illuminance when using S2-R1-A, humidity when using compatible Honeywell or Humirel sensor) <sup>[2](#note_2)</sup> |
```

2024-03-12 07:06 UTC, epenet approved these changes
LGTM

2024-03-12 09:55 UTC, c0ffeeca7 approved these changes
Thank you, @definitio and @epenet  :+1:

2024-03-12 09:55 UTC, merged