Add error sensor to Husqvarna Automower
home-assistant/home-assistant.github.io pull request #31856
Opened 2024-03-12 17:46 UTC by Thomas55555

## Proposed change

Add documentation for the error sensor

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-03-20 07:54 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2024-03-31 18:07 UTC, gjohansson-ST requested changes
Missing `restricted_reason`

2024-04-02 06:46 UTC, c0ffeeca7 commented on source/_integrations/husqvarna_automower.markdown
> +- Error
```suggestion
- Error. For example: *Mower tilted*, *outside geofence*.
- Restricted reason. For example: *Week schedule*, *frost*, or *daily limit*.
```

2024-04-02 06:48 UTC, c0ffeeca7 commented
> Missing `restricted_reason`

Added restricted reason to move this along before the release. Do you approve, @gjohansson-ST ?

2024-04-02 06:50 UTC, gjohansson-ST approved these changes
Thanks @Thomas55555 and @c0ffeeca7 👍

2024-04-02 06:50 UTC, merged