Twitch: Expand app creation instructions
home-assistant/home-assistant.github.io pull request #31972
Opened 2024-03-20 18:16 UTC by jonnybergdahl

## Proposed change

Added instructions for the Twitch integrations, as proposed by #31905.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #31905

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-03-20 18:19 UTC, joostlek commented on source/_integrations/twitch.markdown
> + - Enter a **Name** for your app, note that it needs to be unique all over Twitch, so it is recommended to use your Twitch handle as part of the app name.
Why do we recommend this tho

2024-03-20 19:08 UTC, jonnybergdahl commented
Because your Twitch handle works kinda like a namespace, it is unique all over Twitch.

2024-03-21 08:09 UTC, joostlek commented
But i guess saying that something should be unique should be enough right? We dont care how they call it and we have no need for a special name, soooo

2024-03-21 10:48 UTC, jonnybergdahl commented
And I don't care much for the sparse documentation you usually go for in the HA docs, often leaving newbies confused. Especially in this case where you get stuck creating the app name in Twitch without any indication that the reason is that it is not actually unique. I changed the wording. If you don't like it, I will close this PR.

2024-03-21 10:57 UTC, klaasnicolaas requested changes
Indicating that a name must be unique is sufficient, what users do with it is up to them.

2024-03-21 10:57 UTC, klaasnicolaas commented on source/_integrations/twitch.markdown
> + - Enter a **Name** for your app. Note that it needs to be unique all over Twitch. You can consider incorporating your Twitch handle into the app name as one way to ensure uniqueness.
```suggestion
- Enter a **Name** for your app. Note that it needs to be unique all over Twitch.
```

2024-03-21 13:36 UTC, jonnybergdahl commented
Compare the sparse wording on the Twitch integration with the verbose and helpful text of the Youtube integration. Documentation is supposed to be helpful for the user, and my changes add to that. 

With that said, I will not waste my time on this any more, neither will I accept your proposed change. You can merge or close this PR at your convenience, I don't care anymore.

2024-04-09 15:30 UTC, klaasnicolaas approved these changes

2024-04-09 15:30 UTC, merged