Add documentation for to-do list card
home-assistant/home-assistant.github.io pull request #31985
Opened 2024-03-21 12:59 UTC by c0ffeeca7

## Proposed change

Add documentation for to-do list card
- Add documentation for to-do list card
- add links to to-do list card docs from related integrations

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-03-21 13:53 UTC, allenporter approved these changes, later dismissed
Looks good, one small suggestion

2024-03-21 13:53 UTC, allenporter commented on source/_integrations/caldav.markdown
> +- [Bring!](https://www.getbring.com/)
Omit this one?

```suggestion
```

2024-03-21 14:30 UTC, klaasnicolaas submitted a review, later dismissed

2024-03-25 10:47 UTC, frenck requested changes

2024-03-25 10:47 UTC, frenck commented on source/_integrations/shopping_list.markdown
> +Your shopping list will be accessible from the sidebar, and you can optionally add the [Todo list card](/dashboards/todo-list/) to your dashboard. With the [conversation integration](/integrations/co
```suggestion
Your shopping list will be accessible from the sidebar, and you can optionally add the [To-do list card](/dashboards/todo-list/) to your dashboard. With the [conversation integration](/integrations/conversation/), you can add items to your shopping list using voice commands like "Add eggs to my shopping list." 
```

2024-03-25 10:47 UTC, frenck commented on source/_integrations/todo.markdown
> +- [Todo list card](/dashboards/todo-list/)
```suggestion
- [To-do list card](/dashboards/todo-list/)
```

2024-03-25 10:49 UTC, frenck approved these changes

2024-03-25 10:50 UTC, merged