Adds get_forecast_attribute service to Weather
home-assistant/home-assistant.github.io pull request #32012
Opened 2024-03-23 14:58 UTC by gjohansson-ST

## Proposed change

This adds the get_forecast_attribute service to `Weather`

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/100928
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-03-25 09:19 UTC, emontnemery requested changes
The documentation does not match the new service to my understanding

2024-03-25 09:19 UTC, emontnemery commented on source/_integrations/weather.markdown
> +with a mapping of weather services and their associated forecasts.
This is just copied from the `weather.get_forecast` service, without adjusting the language to what the new service does.

2024-03-25 09:19 UTC, emontnemery commented on source/_integrations/weather.markdown
> +| `wind_speed` | The wind speed in the unit indicated by the `wind_speed_unit` state attribute. | 24.41
Again, this is all just copied, and doesn't seem to make sense

2024-03-31 22:31 UTC, gjohansson-ST commented
Closing as parent PR has been closed.

2024-03-31 22:31 UTC, closed without merging