Add section on message validation for mysensors
home-assistant/home-assistant.github.io pull request #3218
Opened 2017-08-21 12:29 UTC by MartinHjelmare

**Description:**
Explain message validation for mysensors.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):**
https://github.com/home-assistant/home-assistant/pull/9069

2017-08-21 12:49 UTC, frenck requested changes
⚠️ Found some spelling & grammar issues in the added text.

2017-08-21 12:49 UTC, frenck commented on source/_components/mysensors.markdown
> +Messages sent to or from Home Assistant from or to a MySensors device will be validated according to the MySensors [serial API](https://www.mysensors.org/download/serial_api_20). If a message doesn't
*Grammar*:
- Missing comma after `validation`: `If a message doesn't pass validation, it will be dropped`

2017-08-21 12:49 UTC, frenck commented on source/_components/mysensors.markdown
> +The log should inform you of messages that failed validation or if a child value is missing that is required for a certain child type. Note that the log will log all possible combinations of platform
*Spelling & grammar*:
- `dosn't` -> `doesn't`
- Missing comma after `received`: `for a platform has been received, but other required value types are missing`

2017-08-21 12:55 UTC, MartinHjelmare commented
Thanks! Should be fixed now.

2017-08-21 12:56 UTC, frenck approved these changes
✅ Thanks for fixing 👍

2017-08-22 11:07 UTC, Landrash approved these changes
Can be merged after parent Pr has been merged!
Thank you :cookie:

2017-08-26 07:27 UTC, merged