Update media_player.markdown
home-assistant/home-assistant.github.io pull request #32262
Opened 2024-04-11 00:35 UTC by theberko

## Proposed change

## Type of change

- [x ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-04-11 05:20 UTC, MartinHjelmare requested changes

2024-04-11 05:20 UTC, MartinHjelmare commented on source/_integrations/media_player.markdown
> +- `receiver`: Device is an audio video receiver type device taking audio and outputting to speakers and video to some displays.
```suggestion
- `receiver`: Device is an audio/video receiver type device taking audio and outputting to speakers and video to displays.
```

2024-04-12 23:04 UTC, MartinHjelmare commented
My comment with a change suggestion hasn't been addressed.

2024-04-12 23:06 UTC, theberko commented
Oops. It's my first time editing a page and I'm not really sure how this works. Your version is definitely better than mine.

2024-04-12 23:14 UTC, MartinHjelmare commented
You should be able to commit my suggestion directly here in the GitHub web user interface by clicking the commit suggestion button under my suggestion above.

2024-04-15 10:34 UTC, MartinHjelmare approved these changes
Thanks!

2024-04-15 10:35 UTC, merged