Backup: make steps procedural, add related links
home-assistant/home-assistant.github.io pull request #32286
Opened 2024-04-12 08:29 UTC by c0ffeeca7

## Proposed change

Backup: make steps procedural, add related links
- Style change: use numbered steps to make steps procedural
- Add related topics
- Add glossary term refs
- Move manual configuration section to bottom, as it is probably less used than other information

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-04-12 09:46 UTC, ludeeus requested changes

2024-04-12 09:46 UTC, ludeeus commented on source/_integrations/backup.markdown
> +   - A Home Assistant backup is just a tar file of the `/config` directory, plus some metadata.
```suggestion
   - A Home Assistant backup is just a tar file of the [configuration directory](/docs/configuration/#editing-configurationyaml), plus some metadata.
```
`/config` only exists in the containers, not for core so we should link to the explanation here.

2024-04-12 09:46 UTC, ludeeus commented on source/_integrations/backup.markdown
> +   - The restore functionality is already built-in.
```suggestion
```
This is implied with the next step.

2024-04-12 09:46 UTC, ludeeus commented on source/_integrations/backup.markdown
> +   - The backup files are stored in a new **backups** subdirectory in the root of your configuration directory, `/config/backups/`.
```suggestion
```

While you _can_ add this yo your configuration, doing so does nothing as this integration is always loaded regardless.
https://github.com/home-assistant/core/blob/a213de3db5524b065d56f9ba7a9d7d187ec6176b/homeassistant/bootstrap.py#L171

2024-04-12 09:46 UTC, ludeeus commented on source/_integrations/backup.markdown
> +Backups created via the **Backup** integration are located in your `/config/backups` directory.
```suggestion
Backups created via the **Backup** integration are located in your a subdirectory named `backups` which are located in your [configuration directory](/docs/configuration/#editing-configurationyaml).
```

2024-04-12 10:06 UTC, ludeeus approved these changes
LGTM 👍 
But still needs @home-assistant/core to look as well.

2024-04-15 06:01 UTC, merged

2024-04-15 06:54 UTC, MartinHjelmare commented on source/_integrations/backup.markdown
> +Backups created via the **Backup** integration are located in your a subdirectory named `backups` which are located in your [configuration directory](/docs/configuration/#editing-configurationyaml).
Remove "your" in "located in your a subdirectory".

2024-04-15 07:56 UTC, c0ffeeca7 commented on source/_integrations/backup.markdown
> +Backups created via the **Backup** integration are located in your a subdirectory named `backups` which are located in your [configuration directory](/docs/configuration/#editing-configurationyaml).
Thank you! https://github.com/home-assistant/home-assistant.io/pull/32318