Update DNS IP regarding multiple IPs
home-assistant/home-assistant.github.io pull request #32308
Opened 2024-04-14 13:54 UTC by pemontto

## Proposed change
Clarify change in behaviour now we're returning the lowest IP. Related to https://github.com/home-assistant/core/pull/115218

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/115218
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-04-17 07:05 UTC, c0ffeeca7 commented
As this PR is related to a pending code change in core, please point the related docs PR needs to the `next` branch. It is currently targeting the `current` branch. 
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/13137f01-2c31-40b8-926f-873f29a7b55f)

2024-04-18 17:56 UTC, pemontto commented
@c0ffeeca7 have rebased on next and updated target branch :+1:

2024-04-19 04:30 UTC, c0ffeeca7 commented on source/_integrations/dnsip.markdown
> +2. If you specify a `hostname`, a regular DNS lookup will be performed, providing you the IP the hostname resolves to. If your hostname resolves to multiple IP addresses, the lowest IP will returned
```suggestion
2. If you specify a `hostname`, a regular DNS lookup will be performed, providing you the IP the hostname resolves to. If your hostname resolves to multiple IP addresses, the lowest IP will be returned as the state. The first 10 IPs will be returned in ascending order in the `IPs` attribute.
```

2024-04-19 04:31 UTC, c0ffeeca7 requested changes
Tiny tweak.

2024-04-21 05:43 UTC, c0ffeeca7 approved these changes, later dismissed

2024-04-23 13:30 UTC, gjohansson-ST commented on source/_integrations/dnsip.markdown
> +2. If you specify a `hostname`, a regular DNS lookup will be performed, providing you the IP the hostname resolves to. If your hostname resolves to multiple IP addresses, the lowest IP will be return
```suggestion
2. If you specify a `hostname`, a regular DNS lookup will be performed, providing you the IP the hostname resolves to. If your hostname resolves to multiple IP addresses, the lowest IP will be returned as the state. The first 10 IPs will be returned in ascending order in the `ip_addresses` attribute.
```

2024-04-23 13:31 UTC, gjohansson-ST approved these changes
Approved awaiting parent ✅

2024-05-07 09:50 UTC, merged