Add documentation for Point oauth2
home-assistant/home-assistant.github.io pull request #32971
Opened 2024-05-28 06:16 UTC by fredrike

## Proposed change

https://github.com/home-assistant/core/pull/118243 implements use of HA's internal oauth2 authentication for Point this PR documents how to configure Point.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/118243
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-05-28 13:37 UTC, c0ffeeca7 requested changes
Tiny tweaks

2024-05-28 13:37 UTC, c0ffeeca7 commented on source/_integrations/point.markdown
> +## Get Minut Point application credentials
```suggestion
## Prerequisites

Before adding the integration to Home Assistant, you need to get Minut Point application credentials.
```

2024-05-28 13:37 UTC, c0ffeeca7 commented on source/_integrations/point.markdown
> +Navigate to the [API-client | Minut](https://web.minut.com/settings/api-clients) dashboard and **Create client**:
```suggestion
1. Navigate to the [API-client | Minut](https://web.minut.com/settings/api-clients) dashboard and **Create client**:
```

2024-05-28 13:37 UTC, c0ffeeca7 commented on source/_integrations/point.markdown
> +- Get the **ClientID** and **ClientSecret** for the new client, you need them to complete the integration setup in Home Assistant.
```suggestion
  - Enter a **Name** for your client (this is just an identifier).
  - Enter `https://my.home-assistant.io/redirect/oauth` in the **Redirect URI** field.
2. Get the **ClientID** and **ClientSecret** for the new client and store them in a safe place. You need them to complete the integration setup in Home Assistant.
```

2024-05-28 13:37 UTC, c0ffeeca7 commented on source/_integrations/point.markdown
> +If you are a kickstarter backer you need to send an email to hello@minut.com to retrive **ClientID** and **ClientSecret**, don't forget to mention that the **Redirect URI** should be `https://my.home
```suggestion
If you are a Kickstarter backer, you need to send an email to hello@minut.com to retrieve the **ClientID** and **ClientSecret**. Don't forget to mention that the **Redirect URI** should be `https://my.home-assistant.io/redirect/oauth`.
```

2024-05-28 18:59 UTC, fredrike commented
Thanks for the suggestions @c0ffeeca7!

2024-05-29 04:53 UTC, c0ffeeca7 commented on source/_integrations/point.markdown
> +  - Enter `https://my.home-assistant.io/redirect/oauth` in the **Redirect URI** field.
```suggestion
    - Enter a **Name** for your client (this is just an identifier).
    - Enter `https://my.home-assistant.io/redirect/oauth` in the **Redirect URI** field.
```
Got the indents wrong in my previous comment

2024-05-29 04:58 UTC, c0ffeeca7 commented on source/_integrations/point.markdown
> +    - Enter `https://my.home-assistant.io/redirect/oauth` in the **Redirect URI** field.
```suggestion
   - Enter a **Name** for your client (this is just an identifier).
   - Enter `https://my.home-assistant.io/redirect/oauth` in the **Redirect URI** field.
```

2024-05-29 05:16 UTC, c0ffeeca7 reviewed
Missed a few last time

2024-05-29 05:16 UTC, c0ffeeca7 commented on source/_integrations/point.markdown
>  # Device types
```suggestion
## Device types
```

2024-05-29 05:16 UTC, c0ffeeca7 commented on source/_integrations/point.markdown
> +  - [Sensor](#sensor)
```suggestion
```
This section is duplicated below.

2024-05-29 05:16 UTC, c0ffeeca7 commented on source/_integrations/point.markdown
> +The Point hub enables integration with the [Minut Point](https://minut.com/). There is currently support for the following device types within Home Assistant:
```suggestion
The Point hub enables integration with the [Minut Point](https://minut.com/).
```

2024-05-29 05:16 UTC, c0ffeeca7 commented on source/_integrations/point.markdown
> +- [Device types](#device-types)
```suggestion
```

2024-05-29 05:16 UTC, c0ffeeca7 commented on source/_integrations/point.markdown
> +    - [Webhook events](#webhook-events)
```suggestion
```

2024-05-29 06:32 UTC, c0ffeeca7 approved these changes
Thank you, @fredrike :+1:

2024-09-23 11:43 UTC, merged