Documentation for ista EcoTrend integration
home-assistant/home-assistant.github.io pull request #32996
Opened 2024-05-29 11:28 UTC by tr4nt0r

## Proposed change

Add documentation for ista EcoTrend integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/118360
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/5510
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-06-03 10:07 UTC, c0ffeeca7 requested changes, later dismissed
Small tweaks

2024-06-03 10:07 UTC, c0ffeeca7 commented on source/_integrations/ista_ecotrend.markdown
> +Not all values might be available in your ista EcoTrend account. Cost estimations is an optional service and has to be booked by your property manager. The cost sensors are therefore deactivated by d
```suggestion
Not all values may be available in your ista EcoTrend account. Cost estimation is an optional service that has to be booked by your property manager. Therefore, the cost sensors are deactivated by default.
```

2024-06-03 10:07 UTC, c0ffeeca7 commented on source/_integrations/ista_ecotrend.markdown
> +Make sure to select the correct statistics in the energy dashboard. You can differentiate the statistics from the sensors by their prefix `ista_ecotrend`
```suggestion
Make sure to select the correct statistics in the energy dashboard. You can differentiate the statistics from the sensors by their prefix `ista_ecotrend`.
```

2024-06-03 10:07 UTC, c0ffeeca7 commented on source/_integrations/ista_ecotrend.markdown
> +The **ista EcoTrend** integration for Home Assistant allows you to import your monthly meter readings from the [ista EcoTrend](https://ecotrend.ista.de) service.
```suggestion
The **ista EcoTrend** {% term integration %} for Home Assistant allows you to import your monthly meter readings from the [ista EcoTrend](https://ecotrend.ista.de) service.
```

2024-06-03 10:07 UTC, c0ffeeca7 commented on source/_integrations/ista_ecotrend.markdown
> +ha_release: '2024.6'
```suggestion
ha_release: '2024.7'
```

2024-06-04 08:59 UTC, joostlek approved these changes

2024-06-04 09:00 UTC, merged