2024.11: Beta release notes
home-assistant/home-assistant.github.io pull request #35429
Opened 2024-10-28 06:03 UTC by frenck

## Proposed change

ℹ️ Work in progress for the 2024.11 beta releases notes

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

2024-10-29 13:57 UTC, mback2k commented
I am not sure if it is okay to mention additional items, please tell me if I shouldn't do this in the future:

Breaking change due to a bugfix: [Fix visualization by inverting open/closed state of patio awnings](https://github.com/home-assistant/core/pull/128079)
Potential noteworthy feature addition: [Add light support to WMS WebControl pro](https://github.com/home-assistant/core/pull/128308)

2024-10-29 16:19 UTC, klaasnicolaas requested changes

2024-10-29 16:19 UTC, klaasnicolaas commented on source/_posts/2024-11-06-release-202411.markdown
> +will get our awesome drop and drop experience!
```suggestion
will get our awesome drag and drop experience!
```

2024-10-30 13:23 UTC, bramkragten commented
> I am not sure if it is okay to mention additional items, please tell me if I shouldn't do this in the future:
> 
> Breaking change due to a bugfix: [Fix visualization by inverting open/closed state of patio awnings](https://github.com/home-assistant/core/pull/128079) Potential noteworthy feature addition: [Add light support to WMS WebControl pro](https://github.com/home-assistant/core/pull/128308)

Thanks! If they are labeled with the correct labels, they will pop up :-)

2024-10-30 17:37 UTC, merged

2024-10-30 19:01 UTC, mback2k commented
> > I am not sure if it is okay to mention additional items, please tell me if I shouldn't do this in the future:
> 
> > 
> 
> > Breaking change due to a bugfix: [Fix visualization by inverting open/closed state of patio awnings](https://github.com/home-assistant/core/pull/128079) Potential noteworthy feature addition: [Add light support to WMS WebControl pro](https://github.com/home-assistant/core/pull/128308)
> 
> 
> 
> Thanks! If they are labeled with the correct labels, they will pop up :-)

You are welcome! Doesn't seem like it with your latest changes. I guess it depends on how the processed PR marker is interpreted, based on merge or creation/numeric order.