Ads
home-assistant/home-assistant.github.io pull request #3777
Opened 2017-10-25 17:11 UTC by MrLeeh

**Description:**

Add documentation for  ADS component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

2017-11-19 16:15 UTC, frenck requested changes
@MrLeeh I've reviewed your submission and left some suggestions to improve the documentation. Could you please take a look?

2017-11-19 16:15 UTC, frenck commented on source/_components/ads.markdown
> +ha_release: 0.55
You might want to update the version number

2017-11-19 16:15 UTC, frenck commented on source/_components/ads.markdown
> +logo: home-assistant.png
Maybe add the TwinCAT or Backhoff logo?

2017-11-19 16:15 UTC, frenck commented on source/_components/ads.markdown
> +- **device** (*Required*): The AMS NetId that identifies the device.
Please use the configuration tags for listing configuration variables. For more information:
https://home-assistant.io/developers/documentation/create_page/#configuration

2017-11-19 16:15 UTC, frenck commented on source/_components/ads.markdown
> +- **adsvar**: name of the variable on the ADS device. To access global variables
Please use the configuration tags for listing configuration variables. For more information:
https://home-assistant.io/developers/documentation/create_page/#configuration

2017-11-19 16:15 UTC, frenck commented on source/_components/binary_sensor.ads.markdown
> +- **adsvar** (*Required*): The name of the variable which you want to access on
Please use the configuration tags for listing configuration variables. For more information:
https://home-assistant.io/developers/documentation/create_page/#configuration

2017-11-19 16:15 UTC, frenck commented on source/_components/light.ads.markdown
> +- **adsvar** (*Required*): The name of the boolean variable that switches the
Please use the configuration tags for listing configuration variables. For more information:
https://home-assistant.io/developers/documentation/create_page/#configuration

2017-11-19 16:15 UTC, frenck commented on source/_components/sensor.ads.markdown
> +- **adsvar** (*Required*): The name of the variable which you want to access on
Please use the configuration tags for listing configuration variables. For more information:
https://home-assistant.io/developers/documentation/create_page/#configuration

2017-11-19 16:15 UTC, frenck commented on source/_components/switch.ads.markdown
> +- **adsvar** (*Required*): The name of the variable which you want to access on
Please use the configuration tags for listing configuration variables. For more information:
https://home-assistant.io/developers/documentation/create_page/#configuration

2017-11-19 16:15 UTC, frenck commented on source/_components/binary_sensor.ads.markdown
> +is used. This parameter defines the pollint interval in milliseconds. Defaults
Typo: `pollint` -> `polling`

2017-11-19 16:15 UTC, frenck commented on source/_components/binary_sensor.ads.markdown
> +If *device notifications* are enabled the *ADS* device will push a change
Missing comma: `are enabled, the`
Missing comma: `Otherwise, the value`

2017-11-19 16:15 UTC, frenck commented on source/_components/sensor.ads.markdown
> +If *device notifications* are enabled the *ADS* device will push a change
Missing comma: `are enabled, the`
Missing comma: `Otherwise, the value`

2017-11-19 16:15 UTC, frenck commented on source/_components/sensor.ads.markdown
> +The  *factor* can be used to implement fixed decimals. E.g. set *factor* to 100
Missing comma: `E.g., set`

2017-11-19 18:35 UTC, MrLeeh commented
@frenck Thank you for your review. I updated the version number to 0.59 and fixed the typos and commas. Also I added the *components* tags to all platforms. Concerning the logo I think I might need to ask the company for permission to use their logo.

2017-11-20 08:06 UTC, frenck commented
@MrLeeh Not sure what you have done at this point.
But there are a lot of merge conflicts now and there are a lot of commits in this PR that should not be there...

Could you please take a look?

2017-11-20 09:02 UTC, MrLeeh commented
@frenck Damn, after I made the changes you suggested I realized I was on the wrong branch. So I merged it in the `ads` branch. There must have something gone wrong.

2017-11-20 09:05 UTC, MrLeeh commented
I don't know where those conflicts are coming from. Maybe I just start a new PR?

2017-11-20 15:07 UTC, closed without merging

2017-11-20 19:25 UTC, MrLeeh commented
There are still some changes in the component going on. I will wait with the PR until all details have been clarified.