Add documentation for the group alarm platform
home-assistant/home-assistant.github.io pull request #4283
Opened 2017-12-27 13:24 UTC by bonzini

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#11323

## Checklist:

  - [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`. 
  - [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-02-23 10:47 UTC, OttoWinter commented on source/_components/alarm_control_panel.group.markdown
> +    required: true
According to [the code](https://github.com/home-assistant/home-assistant/pull/11323/files#diff-e9227afef3b89ba1d9c7d8dd38984134R36) this is not required.

2018-02-23 12:20 UTC, OttoWinter commented on source/_components/alarm_control_panel.group.markdown
> +Configuration variables:
`{% configuration %}` will already create a heading for you.

2018-02-23 12:20 UTC, OttoWinter commented on source/_components/alarm_control_panel.group.markdown
> +ha_release: 0.59
Should probably be updated once a merge is imminent.

2018-02-23 12:20 UTC, OttoWinter commented on source/_cookbook/automation_alarm.markdown
> +the dashboard.  In this example, I'm using **input_boolean** for those
Link all se stuff :) `**[input_boolean](https://home-assistant.io/components/input_boolean/)**`

2018-03-23 18:02 UTC, frenck commented
Rebased the PR in order to fix the build

2018-03-23 18:54 UTC, frenck requested changes

2018-03-23 18:54 UTC, frenck commented on source/_components/alarm_control_panel.group.markdown
> +  entities:
The example shows `panels`, the configuration parameters `entities`. Which one is it? our both?

2018-03-23 18:54 UTC, frenck commented
@bonzini I've reviewed your PR and left a single question.
Could you please take a look? 👍

2018-04-06 16:38 UTC, frenck commented
@bonzini, I've upped the `ha_release` in the documentation.
Secondly, a little reminder about this PR 😉

2018-05-15 22:46 UTC, frenck commented
Parent PR has been closed, so closing this one as well.

Feel free to re-open when you are ready.

2018-05-15 22:46 UTC, closed without merging