[WIP] Generic Thermostat - Add AUTO support with heat/cool switches #11472
home-assistant/home-assistant.github.io pull request #4355
Opened 2018-01-06 17:45 UTC by ciotlosm

**Description:**
Documentation update for allowing both heater and A/C unit control and `auto` mode for `generic_thermostat`

Note: **Breaking change**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#11472

## Checklist:

  - [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`. 
  - [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-03-13 19:32 UTC, frenck requested changes
@ciotlosm Thank you for this PR.
I've found some small things, could you please take a look? 👍

2018-03-13 19:32 UTC, frenck commented on source/_components/climate.generic_thermostat.markdown
> +Note: Make sure `target_temp_low` and `target_temp_high` are far enough from each other so you don't trigger both devices at the same time or bouce between.
- Please use note boxes for this, see: https://home-assistant.io/developers/documentation/create_page/#html
- `bouce` -> `bounce`

2018-03-13 19:32 UTC, frenck commented on source/_components/climate.generic_thermostat.markdown
> +- **name** (*Required*): Name of thermostat.
- `Name of thermostat` -> `Name of the thermostat`

2018-03-13 19:32 UTC, frenck commented on source/_components/climate.generic_thermostat.markdown
> +- **min_cycle_duration** (*Optional*): Set a minimum amount of time that the switch (either **heater_control** or **ac_control**) must be in it's current state prior to being switched either off or o
- `it's` -> `its`

2018-03-18 19:34 UTC, ciotlosm commented
@frenck I messed up a rebase. I deleted all my changed by mistake instead of resetting my origin/next. I included your comments in the recreated commit.

2018-03-23 18:05 UTC, frenck approved these changes

2018-03-23 18:05 UTC, frenck commented
Looks good, @ciotlosm! 🎖 

Can be merged as soon as the parent PR gets merged.

2018-05-15 22:48 UTC, frenck commented
Closing this PR, since the parent PR has been closed as well.
Feel free to re-open when you are ready.

2018-05-15 22:48 UTC, closed without merging