Add: teleinfo sensor documentation
home-assistant/home-assistant.github.io pull request #4382
Opened 2018-01-09 15:31 UTC by nlamirault

Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#10603

## Checklist:

  - [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`. 
  - [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-02-21 14:44 UTC, c727 commented
main PR closed

2018-10-01 17:12 UTC, DubhAd submitted a review, later dismissed

2018-10-01 17:12 UTC, DubhAd commented on source/_components/sensor.teleinfo.markdown
> +      value_template: '{{ states.sensor.edf.attributes["HCHC"] }}'
These should be using `"{{ state_attr('sensor.edf','HCHC') }}"` as this format handles if the sensor isn't available, rather than throwing errors.

2018-10-01 17:12 UTC, DubhAd commented on source/_components/sensor.teleinfo.markdown
> +      value_template: '{{ states.sensor.edf.attributes["HCHP"] }}'
And here

2018-10-01 17:12 UTC, DubhAd commented on source/_components/sensor.teleinfo.markdown
> +      value_template: '{{ states.sensor.edf.attributes["HHPHC"] }}'
And here

2018-10-01 17:12 UTC, DubhAd commented on source/_components/sensor.teleinfo.markdown
> +      value_template: '{{ states.sensor.edf.attributes["IINST"] }}'
And here

2018-10-01 17:12 UTC, DubhAd commented on source/_components/sensor.teleinfo.markdown
> +      value_template: '{{ states.sensor.edf.attributes["IMAX"] }}'
And here

2018-10-01 17:12 UTC, DubhAd commented on source/_components/sensor.teleinfo.markdown
> +      value_template: '{{ states.sensor.edf.attributes["PAPP"] }}'
And here

2018-10-01 17:12 UTC, DubhAd commented on source/_components/sensor.teleinfo.markdown
> +      value_template: '{{ states.sensor.edf.attributes["PTEC"] }}'
And here

2018-10-01 17:12 UTC, DubhAd commented on source/_components/sensor.teleinfo.markdown
> +      unit_of_measurement: ''
Either don't define the unit at all, or define it, don't define it as blank.

2018-10-01 17:12 UTC, DubhAd commented on source/_components/sensor.teleinfo.markdown
> +      value_template: '{{ states.sensor.edf.attributes["ISOUSC"] }}'
And finally here

2018-10-01 17:12 UTC, DubhAd commented on source/_components/sensor.teleinfo.markdown
> +Configuration variables:
Please use a configuration block as [detailed here](https://developers.home-assistant.io/docs/en/documentation_standards.html#component-and-platform-pages).

2018-10-01 17:12 UTC, DubhAd commented on source/_components/sensor.teleinfo.markdown
> +ha_release: "0.61"
No longer correct, 0.80 I'm guessing?

2018-10-03 08:33 UTC, nlamirault commented
Any idea about this error : 

```
10:27:22 AM: failed during stage 'deploying site': Invalid filename 'components/mqtt/#logging.html'. Deployed filenames cannot contain # or ? characters
```

2018-10-03 09:00 UTC, frenck commented
@nlamirault You branch is based on an older version of the website. Please rebase your changes onto the latest `next` branch. (Please rebase, do not merge `next` into this branch).

2018-10-17 03:24 UTC, tjorim requested changes
Some things will need to be adjusted, thanks for the PR!

⚠️ The `ha_release` will need an update before merging this one in.

2018-10-17 03:24 UTC, tjorim commented on source/_components/sensor.teleinfo.markdown
> +
I think `sensor:` should be on this line.
Increase the indentation of the next lines with 2 spaces as well.

2018-10-17 03:24 UTC, tjorim commented on source/_components/sensor.teleinfo.markdown
> +{% raw %}
Since this doesn't contain Jinja2 templates we don't need the `raw`-tags.

2018-10-17 03:24 UTC, tjorim commented on source/_components/sensor.teleinfo.markdown
> +{% endraw %}
Remove endraw tag

2018-10-17 03:24 UTC, tjorim commented on source/_components/sensor.teleinfo.markdown
> +Configuration variables:
This is not needed, `{% configuration %}` will include it automatically.

2018-10-17 03:24 UTC, tjorim commented on source/_components/sensor.teleinfo.markdown
> +  required: true
Not required because of default

2018-11-11 08:26 UTC, frenck commented
Closing PR, since the parent PR has been closed as well.

2018-11-11 08:26 UTC, closed without merging