Documentation for the NADTelnet platform
home-assistant/home-assistant.github.io pull request #4436
Opened 2018-01-16 19:23 UTC by andreas-amlabs

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

  - [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`. 
  - [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-01-16 19:24 UTC, andreas-amlabs commented
Documentation matching
https://github.com/home-assistant/home-assistant/pull/11524

Which is not yet approved

2018-01-16 19:54 UTC, frenck requested changes
@andreas-amlabs Thank you for sending in the documentation, could you please take a look at my review comment? Thanks 👍

2018-01-16 19:54 UTC, frenck commented on source/_components/media_player.nadtelnet.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-01-16 20:19 UTC, andreas-amlabs commented
Gave it a go, hope it went well

2018-01-17 07:02 UTC, andreas-amlabs commented
A little help plz, what is wrong with

+sources:
 +  description: A list of mappings from sources to source name.
 +  required: false
 +  type: list
 +  keys:
 +    1:
 +      description: A valid source description

2018-01-23 21:35 UTC, andreas-amlabs commented
So keep getting "Liquid Exception: undefined method `downcase' for ["1-10"]:Array" no matter what

Trying to ask for help again, please assist

2018-01-23 21:44 UTC, frenck commented
This PR is still on my radar don't worry. I've assigned myself to look at it on a short term.

2018-03-13 19:34 UTC, frenck commented
Closing this PR, since the parent PR has been closed as well.

2018-03-13 19:34 UTC, closed without merging