Synology homemode
home-assistant/home-assistant.github.io pull request #4556
Opened 2018-01-31 15:39 UTC by philklei

**Description:**
Added description for Synology Home Mode

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-01-31 16:27 UTC, arsaboo commented
Is this PR about Synology? You have some Tahoma related PRs mixed up. Can you please clean this PR up a little.

2018-02-02 09:15 UTC, fabaff requested changes
Can't be merged. The Tahoma docs must be removed.

2018-03-13 19:51 UTC, frenck commented
I will rebase the last commit to a fresh branch.
Adding it to my todo list.

2018-03-14 12:11 UTC, frenck commented
Rebased the last 2 commits onto `next`. Ready for review now.

2018-03-23 18:59 UTC, frenck requested changes

2018-03-23 18:59 UTC, frenck commented on source/_components/switch.synology_homemode.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-03-23 19:00 UTC, frenck commented
@philklei I've reviewed your PR and left a comment. Could you please take a look? 👍

2018-04-06 17:27 UTC, frenck commented
@philklei Little heads up, still waiting for a response.

2018-05-15 22:50 UTC, frenck commented
Closing this PR, since the parent PR has been closed as well.

Feel free to re-open as soon as you are ready.

2018-05-15 22:50 UTC, closed without merging