Added climate.modbus module documentation
home-assistant/home-assistant.github.io pull request #4593
Opened 2018-02-07 04:54 UTC by Kirchoff

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

2018-02-07 16:05 UTC, dgomes commented
Can you provide more information about using this component ? E.g. What equipments works with this ? Does it require any extra hardware ?

2018-03-13 20:13 UTC, frenck requested changes
@Kirchoff Thank you for this. Left a couple of small RFC's. Could you please take a look? 👍

2018-03-13 20:13 UTC, frenck commented on source/_components/climate.modbus.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-03-13 20:13 UTC, frenck commented on source/_components/climate.modbus.markdown
> +    data_type: float
Please don't add optional configuration parameters to the examples.
We'd like to keep examples as minimal as possible.

2018-03-13 20:13 UTC, frenck commented on source/_components/climate.modbus.markdown
> +ha_release: pre 0.7
This is a new component. Please set the `ha_release` to the next release (`0.66`).

2018-03-14 03:03 UTC, Kirchoff commented
@frenck - I made the changes you requested, does everything look good? Thank you.

2018-03-14 05:17 UTC, frenck requested changes
@Kirchoff Almost good!

2018-03-14 05:17 UTC, frenck commented on source/_components/climate.modbus.markdown
> +  - **name** (*Required*): Name of the sensor.
Almost correct! You need to change/format the configuration options as well.

https://home-assistant.io/developers/documentation/create_page/#configuration

2018-03-15 20:55 UTC, frenck commented
Rebased the PR in order to fix the build.

2018-03-15 21:16 UTC, frenck submitted a review, later dismissed
Thank you @Kirchoff! 🏅 

Can be merged as soon as the parent PR gets merged.

2018-04-16 18:34 UTC, MartinHjelmare approved these changes

2018-04-16 18:34 UTC, merged