create documentation for KIWI lock component
home-assistant/home-assistant.github.io pull request #4639
Opened 2018-02-11 15:11 UTC by c7h

**Description:**

Create new documentation for the KIWI lock component

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

https://github.com/home-assistant/home-assistant/pull/12304

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-03-13 20:47 UTC, frenck requested changes
@c7h Thank you! Looks good in general, but some minor comment for you to look at. 👍

2018-03-13 20:47 UTC, frenck commented on source/_components/lock.kiwi.markdown
> +ha_release: 0.63.1
Please update this to the next major release (`0.66` at the time of writing this comment).

2018-03-13 20:47 UTC, frenck commented on source/_components/lock.kiwi.markdown
> +
Maybe add the "KIWI Opening Door" logo to this PR?

2018-03-23 19:11 UTC, frenck commented
Rebased this PR in order to fix the build.

@c7h A little reminder, could you please take a look?

2018-05-12 17:40 UTC, DubhAd commented
I note that the linked PR was closed 10 days ago, closing this too

2018-05-12 17:40 UTC, closed without merging

2018-05-16 10:29 UTC, c7h commented
will update and create new PR