New Component: Add docs for Google Maps Location Sharing
home-assistant/home-assistant.github.io pull request #4646
Opened 2018-02-12 10:45 UTC by michaelarnauts

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#12301

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-02-21 14:47 UTC, c727 submitted a review, later dismissed

2018-03-07 16:22 UTC, PRabahy commented on source/_components/device_tracker.google_maps.markdown
> +You first need to create an additional Google account, and share your location with that account. This platform will use that account to fetch the location of your device(s). You have to setup sharin
Typo. "trough" is probably supposed to be "through".

2018-03-13 21:01 UTC, frenck requested changes
@michaelarnauts Thank you for this PR. I've reviewed it and left you a comment. Could you please take a look? 👍

2018-03-13 21:01 UTC, frenck commented on source/_components/device_tracker.google_maps.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-03-23 19:14 UTC, frenck commented
Rebased the PR in order to fix the build

2018-04-02 14:19 UTC, frenck approved these changes

2018-04-02 14:20 UTC, frenck commented
Did some small updates myself.

This one can be merged in as soon as the build passes since the parent PR has been merged already.

2018-04-02 14:36 UTC, merged

2018-04-17 16:09 UTC, Skaronator commented on source/_components/device_tracker.google_maps.markdown
> +  platform: google_maps
shouldn't this be:

```
device_tracker:
  - platform: google_maps
    username: example@gmail.com
    password: password
```
(missing `-`)?