Added request_rssi configuration variable to docs
home-assistant/home-assistant.github.io pull request #4684
Opened 2018-02-16 17:32 UTC by FrederikBolding

**Description:**
Adds documentation for the configuration variable added in my pull request.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#12458

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-03-13 21:07 UTC, frenck requested changes
@FrederikBolding Thank you! I've reviewed the change and left a comment. Could you please take a look? 👍

2018-03-13 21:07 UTC, frenck commented on source/_components/device_tracker.bluetooth_tracker.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-03-14 18:05 UTC, FrederikBolding commented
Like this @frenck ?

2018-03-15 22:31 UTC, frenck commented
Rebased the PR onto `next` in order to fix the build errors.

2018-03-15 23:36 UTC, FrederikBolding commented
Thanks @frenck :smile:

2018-03-16 09:25 UTC, frenck approved these changes

2018-03-16 09:26 UTC, frenck commented
Is must thank you! Thank you for this PR 🏅 

Approved, can be merged as soon as the parent PR gets merged.

2018-03-31 21:23 UTC, merged