Xiaomi MiIO Fan: Xiaomi Air Humidifier integration
home-assistant/home-assistant.github.io pull request #4829
Opened 2018-03-04 19:49 UTC by syssi

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#12627

2018-03-23 19:51 UTC, frenck requested changes
@syssi Could you please take a look at the merge conflicts? 

And, to fix the build errors, could you please rebase against origin/next as well? 

👍

2018-03-24 00:59 UTC, syssi commented
Merge conflicts fixed.

2018-03-24 08:33 UTC, frenck approved these changes

2018-03-24 08:33 UTC, frenck commented
Thanks, @syssi! 🏅 

Can be merged as soon as the parent PR gets merged.

2018-03-24 22:05 UTC, merged