New - Palo Alto Sensor Documentation
home-assistant/home-assistant.github.io pull request #4831
Opened 2018-03-04 21:18 UTC by skalavala

I did a PR on the main branch for the `Palo Alto` sensor, this is the supporting documentation.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-03-04 22:34 UTC, skalavala commented
If someone can tell me where to upload the logo `palo_alto.png`, that would be great. I've added the logo in the documentation page, but not sure where that goes.

2018-03-15 21:12 UTC, frenck commented
@skalavala `source/images/supported_brands/`

2018-03-15 21:15 UTC, frenck requested changes
@skalavala Left some comments, could you please take a look? 👍

2018-03-15 21:15 UTC, frenck commented on source/_components/sensor.paloalto.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-03-15 21:15 UTC, frenck commented on source/_components/sensor.paloalto.markdown
> +  - platform: paloalto
Seems like the required configuration variables are missing in this example? (`ip_address`, `api_key`)

2018-03-23 19:54 UTC, frenck commented
Rebased the PR in order to fix the build issue.

@skalavala Friendly reminder, could you please take a look at the remaining requests?

2018-04-01 23:14 UTC, skalavala commented
I have closed my PR for the new Palo Alto sensor for now, and when I get to that, I will re-open this PR.

2018-04-01 23:14 UTC, closed without merging