Documentation for Epson projector support in HA
home-assistant/home-assistant.github.io pull request #5005
Opened 2018-03-24 13:19 UTC by pszafer

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13416

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-03-24 13:42 UTC, frenck requested changes

2018-03-24 13:42 UTC, frenck commented on source/_components/media_player.epson.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-03-24 13:42 UTC, frenck commented on source/_components/media_player.epson.markdown
> +ha_release: "0.66"
This feature won't make it into 0.66 since it has been frozen already.
Maybe update it to 0.67?

2018-03-24 13:42 UTC, frenck commented on source/_components/media_player.epson.markdown
> +
One newline to many

2018-03-24 13:43 UTC, frenck commented
Thank you @pszafer for this PR! I've reviewed it and left you some comments.
Could you please take a look? 👍

2018-03-24 14:39 UTC, pszafer commented
@frenck thanks for help!
In configuration section is it possible to define boolean value?
I see in docs that there are only such values string, int, time, template or map

2018-03-27 16:36 UTC, dale3h commented
@pszafer Yes, you can define a `bool` or `boolean` value in the configuration section. You can use any value for the **type** key.

The reason this build is failing is because there is a `:` missing after `port` in the configuration section (on line 32).

2018-03-27 19:58 UTC, dthulke commented on source/_components/media_player.epson.markdown
> +- send next/previous track via HDMI CEC
Since there are projectors with internal media players or speakers the command may apply to the projector itself. Thus I would remove "via HDMI CEC".

2018-03-27 19:58 UTC, dthulke commented on source/_components/media_player.epson.markdown
> +To make this module work you need to connect your projector to WiFi. The best is to use iProjection app by Epson to test if it is working.
The component should also work via LAN. Thus, I suggest to replace WiFi by local network.

2018-04-02 15:17 UTC, frenck submitted a review, later dismissed

2018-04-02 15:18 UTC, frenck commented
Approved 🏅 

Can be merged as soon as the parent PR gets merged.

2018-04-06 16:59 UTC, frenck submitted a review, later dismissed

2018-06-13 05:37 UTC, MartinHjelmare commented on source/_components/media_player.epson.markdown
> +ha_release: 0.68
0.72

2018-06-13 05:37 UTC, MartinHjelmare commented on source/_components/media_player.epson.markdown
> +ha_iot_class: "Local Push"
Local Polling

2018-06-13 05:37 UTC, MartinHjelmare commented on source/_components/media_player.epson.markdown
> +name:
You can add a key for all the optional items named `default` that has the default value for the item as value.
```yaml
port:
 ...
  default: 80
```

2018-06-13 14:15 UTC, MartinHjelmare approved these changes
Great!

2018-06-13 14:15 UTC, merged