Add matrix documentation
home-assistant/home-assistant.github.io pull request #5019
Opened 2018-03-25 18:57 UTC by tinloaf

**Description:**

This adds documentation for the new Matrix component, which essentially adds Matrix chat bot capabilities.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13355

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-04-02 17:20 UTC, frenck requested changes

2018-04-02 17:20 UTC, frenck commented on source/_components/matrix.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-04-02 17:21 UTC, frenck commented
@tinloaf, I've reviewed it and left you a comment.

Also, this PR has a merge conflict. Please resolve that one as well.

2018-04-03 21:35 UTC, tinloaf commented
I've converted it to the new config tags and resolved the merge conflict. We should probably still figure out how to deal with lists-of-X as a config option types (e.g. list-of-map, which I use here for the `commands` option), but for now I guess this does the trick.

2018-04-04 18:29 UTC, frenck submitted a review, later dismissed

2018-04-04 18:30 UTC, frenck commented
Thank for your update @tinloaf. I've approved the PR.
Can be merged as soon as the parent PR gets merged.

2018-04-06 17:01 UTC, frenck submitted a review, later dismissed

2018-05-05 17:05 UTC, merged