Added documentation for gogogate2
home-assistant/home-assistant.github.io pull request #5023
Opened 2018-03-26 10:11 UTC by dlbroadfoot

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-04-02 17:14 UTC, frenck requested changes

2018-04-02 17:14 UTC, frenck commented on source/_components/cover.gogogate2.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-04-02 17:14 UTC, frenck commented on source/_components/cover.gogogate2.markdown
> +- **ip_address** (*Required*): IP address of your Gogogate2 device
The optional `api_key` configuration variable is missing in the docs but is present in the code.

2018-04-02 17:15 UTC, frenck commented
Thank you for this PR, @dlbroadfoot!

I've left you some comments to take a look at 👍

2018-04-03 07:46 UTC, frenck submitted a review, later dismissed

2018-04-03 07:46 UTC, frenck commented
Thanks, @dlbroadfoot for updating the PR! 🥇 

Looks good and can be merged as soon as the parent PR gets merged.

2018-04-06 12:21 UTC, fabaff submitted a review, later dismissed

2018-04-06 12:30 UTC, fabaff approved these changes

2018-04-06 13:53 UTC, merged