Update snips.markdown
home-assistant/home-assistant.github.io pull request #5133
Opened 2018-04-07 19:22 UTC by tschmidty69

**Description:**
 - Added probaility threshold and feedback sounds configuration
 - Added new services

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13746

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-04-14 09:19 UTC, frenck requested changes

2018-04-14 09:19 UTC, frenck commented on source/_components/snips.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-04-14 09:19 UTC, frenck commented on source/_components/snips.markdown
> +ha_release: 0.66
This should not be updated. Snips support was added in `0.48`.

2018-04-14 09:19 UTC, frenck commented
@tschmidty69 I've reviewed this PR and left you some comments.
Could you please take a look? 👍

2018-04-27 19:40 UTC, balloob commented
@tschmidty69 this PR did not make the 0.68 release but should have, as the support has gone out. Please fix it asap.

2018-05-06 13:49 UTC, tschmidty69 commented
This is outdated

2018-05-06 13:49 UTC, closed without merging