add switch.mqtt_template documentation
home-assistant/home-assistant.github.io pull request #5139
Opened 2018-04-08 21:36 UTC by natiz

**Description:**
See HA PR for details.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [V] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [V] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-04-14 08:12 UTC, frenck requested changes

2018-04-14 08:12 UTC, frenck commented on source/_components/switch.mqtt_template.markdown
> +    command_topic: "home/bedroom/switch1/set"
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-04-14 08:13 UTC, frenck commented
Thanks, @natiz. I've reviewed the PR and left you a comment. Could you please take a look? 👍

2018-04-14 18:02 UTC, natiz commented
Thanks @frenck. Waiting to see if my PR (home-assistant/home-assistant#13771) is gonna be accepted, will then look into that comment.

2018-05-12 17:51 UTC, DubhAd commented
I note that the linked PR was closed 10 days ago, closing this too

2018-05-12 17:51 UTC, closed without merging