Create sensor for Phicomm M1 air sensor
home-assistant/home-assistant.github.io pull request #5142
Opened 2018-04-09 13:04 UTC by Yonsm

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-04-14 08:24 UTC, frenck requested changes

2018-04-14 08:24 UTC, frenck commented on source/_components/sensor.phicomm.markdown
> +logo: https://cdn-mall.phicomm.com/themes/pc/feixun/images/logo.png
Please, do not use external image sources.
Add the logo to the repository and make a local reference.

2018-04-14 08:24 UTC, frenck commented on source/_components/sensor.phicomm.markdown
> +ha_release: 0.67
`0.67` is already shipped, maybe up it to `0.68`.

2018-04-14 08:24 UTC, frenck commented on source/_components/sensor.phicomm.markdown
> +Configuration options:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-04-14 08:24 UTC, frenck commented on source/_components/sensor.phicomm.markdown
> +    name: Phicomm
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-04-14 08:24 UTC, frenck commented on source/_components/sensor.phicomm.markdown
> +    devices: 1
Same as above, optional.

2018-04-14 08:24 UTC, frenck commented on source/_components/sensor.phicomm.markdown
> +    sensors: [pm25, hcho, temperature, humidity]
Same as above, optional.

2018-04-14 08:24 UTC, frenck commented on source/_components/sensor.phicomm.markdown
> +The `phicomm` sensor platform let you monitor data from an Phicomm M1 air sensor.
- `let` -> `lets`
- `an Phicomm` -> `a Phicomm`

2018-04-14 08:24 UTC, frenck commented
@Yonsm I've reviewed your PR and left you some comments.
Could you please take a look? 👍

2018-04-22 10:17 UTC, Yonsm commented on source/_components/sensor.phicomm.markdown
> +logo: https://cdn-mall.phicomm.com/themes/pc/feixun/images/logo.png
done

2018-04-22 10:17 UTC, Yonsm commented on source/_components/sensor.phicomm.markdown
> +ha_release: 0.67
done

2018-04-22 10:18 UTC, Yonsm commented on source/_components/sensor.phicomm.markdown
> +Configuration options:
Please have a look on it. Maybe done?

2018-04-22 10:19 UTC, Yonsm commented
@frenck I update the document. Please have a look, thank you.

2018-05-16 17:32 UTC, frenck approved these changes

2018-05-16 17:32 UTC, frenck commented
@Yonsm Sorry for the delay. I've done a minor tweak and approved it.
Can be merged as soon as the parent PR gets merged.

2018-07-08 09:07 UTC, frenck commented
Parent PR was closed. Closing this one as well.
Feel free to re-open when ready.

2018-07-08 09:07 UTC, closed without merging