Add max_volume option to Onkyo media player
home-assistant/home-assistant.github.io pull request #5153
Opened 2018-04-11 14:28 UTC by relvacode

**Description:**

Adds a new `max_volume` option to Onkyo media players

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [X] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-04-14 08:02 UTC, frenck requested changes

2018-04-14 08:02 UTC, frenck commented on source/_components/media_player.onkyo.markdown
> +    max_volume: 50
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-04-14 08:03 UTC, frenck commented
Thanks for the contribution @relvacode!
I've reviewed the PR and left you a comment, could you please take a look? 👍

2018-05-05 11:32 UTC, relvacode commented
@frenck Requested change made, I also updated the documentation for `max_volume` as per requested changes in the associated PR

2018-05-05 17:01 UTC, balloob submitted a review, later dismissed

2018-05-05 17:04 UTC, balloob approved these changes

2018-05-05 17:12 UTC, merged