Update switch.tplink.markdown
home-assistant/home-assistant.github.io pull request #5156
Opened 2018-04-11 16:56 UTC by eetree

**Description:**

added how to include multiple switches in the config 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-04-12 11:40 UTC, fabaff requested changes

2018-04-12 11:40 UTC, fabaff commented on source/_components/switch.tplink.markdown
> +    name: another switch
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-04-12 11:40 UTC, fabaff commented on source/_components/switch.tplink.markdown
> +    name: another switch
Also, it's already documented how to add additional devices.

2018-04-14 07:40 UTC, frenck commented
I agree with the comments by @fabaff, therefore closing this PR.

Thanks for the suggestion @eetree! 👍

2018-04-14 07:40 UTC, closed without merging