Describe the new services added
home-assistant/home-assistant.github.io pull request #5239
Opened 2018-04-24 03:44 UTC by teharris1

**Description:**
New services were added to support Insteon All-Linking. 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#14065

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-04-24 18:58 UTC, frenck requested changes
@teharris1, Thank you for your PR. I've reviewed it and left some comments. Could you please take a look? That would be awesome 😎

2018-04-24 18:58 UTC, frenck commented on source/_components/insteon_plm.markdown
> -description: "Instructions on how to setup an Insteon USB PLM locally within Home Assistant."
Incorrect, please leave it as it was.

2018-04-24 18:58 UTC, frenck commented on source/_components/insteon_plm.markdown
> -- **port** (*Required*): The port for your device, e.g., `/dev/ttyUSB0`
Please do not change this, the previous version was actually correct.

2018-04-24 18:58 UTC, frenck commented on source/_components/insteon_plm.markdown
> -only be shown by their INSTEON hex address (e.g., "1A.2B.3C") which can be a bit
Please leave this intact, since it was perfectly fine.

2018-04-24 18:58 UTC, frenck commented on source/_components/insteon_plm.markdown
> +linked. For an overview of device linking please read the Insteon page on
Missing comma: `linking please read` -> `linking, please read`

2018-04-24 18:58 UTC, frenck commented on source/_components/insteon_plm.markdown
> +- **insteon_plm.add_all_link**: Tells the Insteom Modem (IM) start All-Linking
`Insteom` -> `Insteon`

2018-04-24 18:58 UTC, frenck commented on source/_components/insteon_plm.markdown
> +device. WARNING - Loading a device All-LInk database is very time consuming
`All-LInk` -> `All-Link`

2018-04-24 18:58 UTC, frenck commented on source/_components/insteon_plm.markdown
> +and inconsistant. This may take a LONG time and may need to be repeated to
`inconsistant` -> `inconsistent`

2018-04-24 18:58 UTC, frenck commented on source/_components/insteon_plm.markdown
> +on most platforms. HouseLinc is no longer supported by SmartHome but it still
More active voice suggestion (and missing comma): 
`SmartHome no longer supports HouseLinc, but it still`

2018-05-01 23:48 UTC, teharris1 commented
@frenck Thanks for reviewing this PR. Hopefully my changes met your expectations. The associated code PR is still sitting out there after over a week. Any way you can help move the code review of the that PR forward? Thanks

2018-05-05 16:58 UTC, balloob submitted a review, later dismissed

2018-05-05 16:59 UTC, balloob commented
@teharris1 there has been a build error because you wrote invalid markdown on this PR as can be seen by the netlify build error.

2018-05-05 17:00 UTC, balloob commented
Please address asap so it can be part of the release.

2018-05-05 17:15 UTC, teharris1 commented
@balloob Working on it right now.

2018-05-05 18:54 UTC, balloob commented
Looks like editting it in the GitHub online editor converts it to UTF-8, let's see if that worked.

2018-05-05 19:08 UTC, merged

2018-05-05 19:08 UTC, balloob commented
Thanks! Cherry-picking this for RC branch.