Sisyphus component docs
home-assistant/home-assistant.github.io pull request #5369
Opened 2018-05-15 05:27 UTC by jkeljo

**Description:**
Adding documentation for the new Sisyphus component

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [X] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-06-28 21:46 UTC, frenck approved these changes

2018-06-28 21:46 UTC, frenck commented
Looks great @jkeljo! Thanks a lot 🏅 
Can be merged as soon as the parent PR gets merged.

2018-06-28 21:46 UTC, frenck submitted a review, later dismissed

2018-07-08 10:39 UTC, frenck submitted a review, later dismissed

2018-07-29 05:41 UTC, MartinHjelmare requested changes

2018-07-29 05:41 UTC, MartinHjelmare commented on source/_components/light.sisyphus.markdown
> +ha_release: 0.74
0.75

2018-07-29 05:41 UTC, MartinHjelmare commented on source/_components/media_player.sisyphus.markdown
> +ha_release: 0.74
0.75

2018-07-29 05:41 UTC, MartinHjelmare commented on source/_components/media_player.sisyphus.markdown
> +ha_category: Light
Media Player?

2018-07-29 05:41 UTC, MartinHjelmare commented on source/_components/sisyphus.markdown
> +ha_release: 0.74
0.75

2018-07-29 07:29 UTC, frenck approved these changes

2018-07-29 07:39 UTC, MartinHjelmare approved these changes

2018-07-29 07:40 UTC, merged