added documentation for KIWI.KI smartlock
home-assistant/home-assistant.github.io pull request #5381
Opened 2018-05-16 10:43 UTC by c7h

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-05-16 18:58 UTC, frenck requested changes
@c7h I left you some feedback, could you please take a look? 👍

2018-05-16 18:58 UTC, frenck commented on source/_components/lock.kiwi.markdown
> +ha_release: 0.69.1
Please update this to the next major release (0.70).
New features are never released in minor releases.

2018-05-16 18:58 UTC, frenck commented on source/_components/lock.kiwi.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-05-31 11:54 UTC, c7h commented on source/_components/lock.kiwi.markdown
> +Configuration variables:
done :) 👍

2018-06-01 14:41 UTC, c7h commented
@frenck The docs are updated now

2018-06-12 10:37 UTC, MartinHjelmare commented on source/_components/lock.kiwi.markdown
> +ha_release: 0.70
0.72

2018-06-12 10:37 UTC, MartinHjelmare commented on source/_components/lock.kiwi.markdown
> +
Remove this blank line.

2018-06-12 10:38 UTC, c7h commented on source/_components/lock.kiwi.markdown
> +ha_release: 0.70
👍

2018-06-12 11:17 UTC, MartinHjelmare approved these changes
Looks good!

2018-06-21 19:22 UTC, merged