Sensirion SHT31 Smart-Gadget component docs
home-assistant/home-assistant.github.io pull request #5386
Opened 2018-05-17 15:44 UTC by rhoriguchi

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-06-25 18:55 UTC, frenck approved these changes

2018-06-25 18:55 UTC, frenck requested changes

2018-06-25 18:55 UTC, frenck commented on source/_components/sensor.sensirion_sht31.markdown
> +      - battery
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-06-25 18:56 UTC, frenck commented
Hi there @rhoriguchi!
The PR looks great overall. Left you one small RFC.
Could you please take a look? 👍

2018-08-12 08:40 UTC, rhoriguchi commented
Update of hass broke the gattlib library since it uses an older version of request, so the requirements can't be met.

2018-08-12 08:40 UTC, closed without merging