Add Xiaomi Aqara Door Lock
home-assistant/home-assistant.github.io pull request #5387
Opened 2018-05-17 18:31 UTC by syssi

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#14419

2018-05-18 16:16 UTC, SchumyHao requested changes
Xiaomi Aqara Lock **CANNOT** unlock from Homeassistant, but we can use it's attribute to trigger automation.

`changed_by`: Show an unique ID number represent to last unlock method. 
`verified_wrong_times`: If someone tried to unlock this lock but failed more than 3 times, this attribute will record attempt times. This attribute will clear if unlock successfully.

2018-05-18 16:40 UTC, syssi commented
Thanks for your input. I will add it to the PR as soon as possible.

2018-05-22 07:52 UTC, MartinHjelmare commented on source/_components/lock.xiaomi_aqara.markdown
> +ha_release: "0.70"
0.71

2018-05-22 07:52 UTC, MartinHjelmare commented on source/_components/lock.xiaomi_aqara.markdown
> +If someone tried to unlock the device but failed more than 3 times the `verified_wrong_times` attribute will be incremented. The counter resets on a successful unlock.
If someone tries to unlock the device but fails more than 3 times...

2018-05-22 07:52 UTC, MartinHjelmare commented on source/_components/lock.xiaomi_aqara.markdown
> +The requirement is that you have setup [Xiaomi aqara](/components/xiaomi_aqara/).
The requirement to use this platform is that you have set up the Xiaomi Aqara component.

2018-05-22 08:18 UTC, MartinHjelmare approved these changes

2018-05-22 08:40 UTC, merged