Add documents for dyson climate device
home-assistant/home-assistant.github.io pull request #5420
Opened 2018-05-23 12:24 UTC by soraxas

**Description:**
Documentation for the now supported dyson climate platform.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#14598

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-06-28 21:54 UTC, frenck submitted a review, later dismissed

2018-06-28 21:54 UTC, frenck commented
Looks good to me @soraxas! Thanks a lot!

✅ Approved. Can be merged as soon as the parent PR gets merged.

2018-08-17 10:40 UTC, frenck submitted a review, later dismissed

2018-09-09 11:19 UTC, frenck commented
Merge conflicts have appeared!
Could you please take a look @soraxas

2018-09-21 10:29 UTC, frenck commented
Thanks for resolving the conflict @soraxas! 👍

2018-09-21 10:29 UTC, frenck submitted a review, later dismissed

2018-10-17 03:52 UTC, tjorim requested changes
Only some typo's.

⚠️ The ha_release will need an update before merging this one in.

2018-10-17 03:52 UTC, tjorim commented on source/_components/climate.dyson.markdown
> +You have first to set up the [Dyson component](/components/dyson/)
Please put a point at the end of a sentence.

2018-10-17 03:52 UTC, tjorim commented on source/_components/climate.dyson.markdown
> +This component support the following services (see [Climate](/components/climate/)):
This component support --> support _**s**_

2018-10-18 19:04 UTC, frenck requested changes
Merge conflict again 😢

2018-10-18 23:50 UTC, soraxas commented
Thanks @frenck :)

2018-10-21 09:32 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2018-10-21 15:37 UTC, MartinHjelmare commented on source/_components/climate.dyson.markdown
> +ha_release: 0.77
0.81

2018-10-21 15:37 UTC, MartinHjelmare commented on source/_components/climate.dyson.markdown
> +The `dyson` climate platform allows you to control your Dyson Pure Hot+Cool Fan thermal control. For controlling the fan functionality, see the [dyson fan](/components/fan.dyson/) component.
... see the dyson fan platform.

2018-10-21 16:32 UTC, frenck approved these changes

2018-10-21 17:52 UTC, MartinHjelmare approved these changes

2018-10-21 17:53 UTC, merged