Add dlna_dmr component
home-assistant/home-assistant.github.io pull request #5474
Opened 2018-06-01 20:50 UTC by StevenLooman

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-06-25 18:12 UTC, frenck requested changes
Looks good overall @StevenLooman!
Nevertheless, left you 2 comments, could you take a look? 👍

2018-06-25 18:12 UTC, frenck commented on source/_components/media_player.dlna_dmr.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-06-25 18:12 UTC, frenck commented on source/_components/media_player.dlna_dmr.markdown
> +    name: "TV living room"
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-06-25 18:40 UTC, StevenLooman commented
Thank you for the review, will fix it soon!

2018-07-08 10:21 UTC, frenck submitted a review, later dismissed

2018-07-08 10:23 UTC, frenck commented
Thanks for the updates @StevenLooman!
✅ Approved. Can be merged as soon as the parent PR gets merged.

2018-08-05 12:47 UTC, MartinHjelmare requested changes

2018-08-05 12:47 UTC, MartinHjelmare commented on source/_components/media_player.dlna_dmr.markdown
> +ha_release: 0.74
0.76

2018-08-05 12:47 UTC, MartinHjelmare commented on source/_components/media_player.dlna_dmr.markdown
> +## {% linkable_title Configuration %}
Move this above the paragraph where we talk about the example config.

2018-08-05 12:56 UTC, MartinHjelmare commented on source/_components/media_player.dlna_dmr.markdown
> +## {% linkable_title Configuration %}
I meant that this header should be moved above the example paragraph.

2018-08-05 15:33 UTC, MartinHjelmare approved these changes

2018-08-05 15:35 UTC, merged

2018-08-05 18:47 UTC, StevenLooman commented
Great, thanks! Please be sure to tag me in any future issues when any problems turn up.