Add Netgear LTE documentation
home-assistant/home-assistant.github.io pull request #5502
Opened 2018-06-06 20:29 UTC by amelchio

**Description:**

Initial documentation for a new integration.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#14687

## Checklist:

- [X] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-06-06 20:54 UTC, arsaboo commented on source/_components/netgear_lte.markdown
> +    description: The IP address where the modem web interface resides.
The IP address of the modem web interface.

2018-06-08 05:52 UTC, MartinHjelmare requested changes
Looks good. Just add the backtic.

2018-06-08 05:52 UTC, MartinHjelmare commented on source/_components/netgear_lte.markdown
> +``yaml
We're missing one backtic here.

2018-06-08 19:38 UTC, MartinHjelmare approved these changes

2018-06-08 19:39 UTC, merged