Add RitAssist support page
home-assistant/home-assistant.github.io pull request #5549
Opened 2018-06-15 20:32 UTC by depl0y

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#14976

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-06-16 15:20 UTC, arsaboo submitted a review, later dismissed
Looks good...can be merged when parent PR is merged

2018-06-24 11:18 UTC, frenck submitted a review, later dismissed

2018-06-24 11:18 UTC, frenck submitted a review, later dismissed

2018-07-08 10:37 UTC, frenck submitted a review, later dismissed

2018-08-02 05:06 UTC, MartinHjelmare requested changes

2018-08-02 05:06 UTC, MartinHjelmare commented on source/_components/device_tracker.ritassist.markdown
> +ha_release: 0.74
0.76

2018-08-02 05:06 UTC, MartinHjelmare commented on source/_components/device_tracker.ritassist.markdown
> +---
Please add the key `ha_iot_class` with the value `Cloud Polling`.

2018-08-02 07:44 UTC, MartinHjelmare approved these changes
Great!

2018-08-02 07:44 UTC, merged