Add documentation for pjlink media player component
home-assistant/home-assistant.github.io pull request #5585
Opened 2018-06-22 03:46 UTC by benoitlouy

**Description:**

Documentation for pjlink media player component which allows controlling projectors.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-06-25 11:09 UTC, frenck requested changes
Hi, @benoitlouy,

I've reviewed the documentation and it looks great!
Nevertheless, I've left some small requests for changes. Could you please take a look? 👍

2018-06-25 11:09 UTC, frenck commented on source/_components/media_player.pjlink.markdown
> +    port: 4352
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-06-25 11:09 UTC, frenck commented on source/_components/media_player.pjlink.markdown
> +ha_release: TBD
Please set this to the next major release, currently `0.73`.

2018-06-25 11:09 UTC, frenck commented on source/_components/media_player.pjlink.markdown
> +---
Maybe add the PJLink logo?
This would make the component more recognizable and just looks prettier.

2018-06-25 16:35 UTC, benoitlouy commented
@frenck all the requests for change have been addressed.

2018-06-25 16:43 UTC, frenck submitted a review, later dismissed

2018-06-25 16:45 UTC, frenck commented
Thank you for addressing these so quickly!
Awesome first-time contribution by the way! 🥇 

![bitmoji](https://render.bitstrips.com/v2/cpanel/8f03dc60-8d57-416f-b61b-461ec7ddc5c5-82100c49-8c0a-4ae4-9b04-3a6d3eac9cc2-v1.png?transparent=1&palette=1&width=246)

2018-08-09 18:01 UTC, MartinHjelmare submitted a review, later dismissed

2018-08-09 18:01 UTC, MartinHjelmare commented on source/_components/media_player.pjlink.markdown
> +ha_release: 0.73
0.76

2018-08-09 19:02 UTC, frenck approved these changes

2018-08-09 19:18 UTC, merged