Add docs for Turn Touch component.
home-assistant/home-assistant.github.io pull request #5591
Opened 2018-06-24 21:14 UTC by antsar

**Description:** Add documentation for the [Turn Touch](https://shop.turntouch.com/) component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#15126

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-06-25 10:25 UTC, frenck requested changes
Hi, @antsar,

I've reviewed the PR and they look pretty good, nevertheless, I've left some comments. Could you please take a look? 👍

2018-06-25 10:25 UTC, frenck commented on source/_components/turn_touch.markdown
> +Configuration variables for each device:
Please include these inside the configuration block you've defined above.

2018-06-25 10:25 UTC, frenck commented on source/_components/turn_touch.markdown
> +Turn Touch supports complex button presses (double-tap, hold, and multi-button). Complex button presses generate multiple events (eg. a double-tap generates two single-press events, followed by the d
`eg.` -> `e.g.,`

2018-06-25 10:25 UTC, frenck commented on source/_components/turn_touch.markdown
> +      debounce: false
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-06-25 13:13 UTC, antsar commented
Thanks for the quick review, @frenck! Changes made.

2018-06-25 15:16 UTC, frenck submitted a review, later dismissed

2018-06-25 15:17 UTC, frenck commented
No! Thank you for all this work! Awesome.
✅ Approved, can be merged as soon as the parent PR get merged.

![bitmoji](https://render.bitstrips.com/v2/cpanel/15f269e9-79ff-42f5-b6f8-df81e1cb3847-82100c49-8c0a-4ae4-9b04-3a6d3eac9cc2-v1.png?transparent=1&palette=1&width=246)

2018-08-17 10:40 UTC, frenck approved these changes

2018-09-21 14:36 UTC, frenck commented
Closing this PR since the parent PR has been closed as well.

2018-09-21 14:36 UTC, closed without merging