Fix incorrect path in Group Visibility example
home-assistant/home-assistant.github.io pull request #5602
Opened 2018-06-25 16:22 UTC by tfoxcroft

Hi there, just a minor but quite confusing typo.

The path for calling the occasion.py script referenced in the Group Visibility example when using docker should be /config/occasion.py and not /command/occasion.py

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-06-25 16:37 UTC, frenck approved these changes

2018-06-25 16:37 UTC, frenck requested changes
Needs to be rebased onto `current`.

2018-06-26 04:06 UTC, frenck approved these changes

2018-06-26 04:07 UTC, frenck commented
Rebased. Can be merged as soon as the build passes.

@tfoxcroft Thank you for this! Well spotted! 👍 
Please, next time, be sure the use the correct base & target branches. 😉

2018-06-26 04:17 UTC, merged

2018-06-26 13:09 UTC, tfoxcroft commented
No problem, thanks for fixing it up so quickly! Sorry about that, I only saw it was on the wrong branch afterward.

2018-06-26 14:54 UTC, frenck commented
No problem 😉