added Brunt cover docs
home-assistant/home-assistant.github.io pull request #5604
Opened 2018-06-26 12:31 UTC by eavanvalkenburg

**Description:**
Added docs for the Brunt cover component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-06-26 12:52 UTC, frenck requested changes
Hi, @eavanvalkenburg.
I've reviewed the documentation PR and left 2 comments.
Could you please take a look? 👍

2018-06-26 12:52 UTC, frenck commented on source/_components/cover.brunt.markdown
> +ha_release: 0.69
`0.69` has already shipped a while ago, please update this to the next major release; `0.73`

2018-06-26 12:52 UTC, frenck commented on source/_components/cover.brunt.markdown
> +logo: brunt.png
This logo does not exist in our repository.
Please add it to the PR.

2018-06-26 15:08 UTC, frenck submitted a review, later dismissed

2018-06-26 15:08 UTC, frenck commented
Thank you, @eavanvalkenburg, for updating the PR.
✅ Approved and can be merged as soon as the parent PR gets merged.

2018-06-26 15:09 UTC, eavanvalkenburg commented
Thanks for reviewing!

2018-07-09 07:35 UTC, frenck submitted a review, later dismissed

2018-07-25 10:20 UTC, MartinHjelmare commented on source/_components/cover.brunt.markdown
> +To enable this sensor, add the following lines to your `configuration.yaml`:
To enable this integration

2018-07-25 10:35 UTC, MartinHjelmare approved these changes

2018-07-25 10:36 UTC, MartinHjelmare commented
Can be merged when build passes.

2018-07-26 10:06 UTC, merged