Add documentation for new Enphase Envoy component
home-assistant/home-assistant.github.io pull request #5638
Opened 2018-06-30 18:19 UTC by jesserizzo

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15081

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-02 18:11 UTC, frenck submitted a review, later dismissed

2018-07-02 18:12 UTC, frenck commented
Looks great @jesserizzo!
I did remove the configuration header/title thingy, since that is already handled by our configuration tags.

✅ Approved.

Can be merged as soon as the parent PR gets merged.

2018-08-02 21:23 UTC, MartinHjelmare requested changes
The name of the markdown file is incorrect. It should be prefixed with `sensor.`.

2018-08-02 21:23 UTC, MartinHjelmare commented on source/_components/enphase_envoy.markdown
> +ha_release: 0.73
0.76

2018-08-02 21:23 UTC, MartinHjelmare commented on source/_components/enphase_envoy.markdown
> +  description: The list of conditions to display in the front end
This doesn't have anything to do with the frontend per se. This decides what entities will be created, ie what data to collect.

2018-08-02 21:23 UTC, MartinHjelmare commented on source/_components/enphase_envoy.markdown
> +logo: enphase.svg
The filename here doesn't match the included file.

2018-08-02 21:23 UTC, MartinHjelmare commented on source/_components/enphase_envoy.markdown
> +name:
This isn't included in the config schema of the platform.

2018-08-02 22:42 UTC, MartinHjelmare commented on source/_components/sensor.enphase_envoy.markdown
> +name:
Remove this key.

2018-08-02 23:43 UTC, MartinHjelmare approved these changes
Great!

2018-08-02 23:45 UTC, merged