Added venv installation steps for Windows
home-assistant/home-assistant.github.io pull request #5649
Opened 2018-07-02 16:40 UTC by ludeeus

**Description:**
Adds python virtual environment installation instruction for Windows

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [X] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-02 16:42 UTC, dshokouhi commented
Looks good to me, better direction for users to go with a virtual environment install.

2018-07-02 19:23 UTC, fabaff requested changes

2018-07-02 19:23 UTC, fabaff commented on source/_docs/installation/windows.markdown
> +
Please fix the typo and add a period to the end of the sentence. It's preferred to use a capital `P` for Python.

2018-07-02 19:23 UTC, fabaff commented on source/_docs/installation/windows.markdown
> +Open CMD.exe and paste the folowing commands (one at the time):
Please fix the typo. As a non-windows user I would guess that it's `cmd.exe`.

2018-07-02 19:23 UTC, fabaff commented on source/_docs/installation/windows.markdown
> +To update Home Assistant, stop it and then open CMD.exe and paste the folowing commands (one at the time):
Dito.

2018-07-02 19:23 UTC, fabaff commented on source/_docs/installation/windows.markdown
> +C:\...\> hass --open-ui
`--open-ui` is only useful if you want to browse the Home Assistant frontend the local machine. Should be removed here.

2018-07-03 10:35 UTC, fabaff submitted a review, later dismissed
:bird:

2018-07-03 10:36 UTC, fabaff approved these changes

2018-07-03 10:54 UTC, merged