Add convert_currency to alpha_vantage
home-assistant/home-assistant.github.io pull request #5657
Opened 2018-07-03 22:57 UTC by lausser

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15258

## Checklist:

- [X ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-04 10:26 UTC, frenck requested changes

2018-07-04 10:26 UTC, frenck commented on source/_components/sensor.alpha_vantage.markdown
> +    - symbol: RMBS
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-07-04 10:27 UTC, frenck commented
Thanks for the PR @lausser.
I've reviewed it and left you a comment, could you please take a look? 👍

2018-07-04 17:28 UTC, lausser commented on source/_components/sensor.alpha_vantage.markdown
> +    - symbol: RMBS
Please have a look, i moved the part with the new attribute to the examples section

2018-07-05 08:11 UTC, lausser reviewed
The example for the extra parameter is now in it's own section.

2018-07-08 10:43 UTC, frenck approved these changes

2018-07-08 10:44 UTC, frenck commented
Thanks for updating the PR @lausser!

✅ Approved. Can be merged as soon as the parent PR gets merged.

2018-09-09 14:44 UTC, frenck commented
Do not run stale stale[bot]. The parent PR is still open.

2018-09-21 13:26 UTC, closed without merging