Add pages for Environment Canada component and platforms
home-assistant/home-assistant.github.io pull request #5685
Opened 2018-07-08 03:41 UTC by michaeldavie

**Description:**
Adds pages for newly created Environment Canada component and platforms.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#TBD

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-08 11:07 UTC, frenck requested changes
@michaeldavie Thank you for your PR!
I've reviewed it and left you some comments. Could you please take a look? 👍

2018-07-08 11:07 UTC, frenck commented on source/_components/camera.environment_canada.markdown
> +  - Closest station to latitude / longitude from sensor configuration
- `Closest` -> `The closest`
- `latitude / longitude` -> `latitude/longitude`

2018-07-08 11:07 UTC, frenck commented on source/_components/camera.environment_canada.markdown
> +  - Closest station to latitude / longitude from Home Assistant core configuration
- `Closest` -> `The closest`
- `latitude / longitude` -> `latitude/longitude`

2018-07-08 11:07 UTC, frenck commented on source/_components/camera.environment_canada.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-07-08 11:07 UTC, frenck commented on source/_components/camera.environment_canada.markdown
> +    station: XFT
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-07-08 11:07 UTC, frenck commented on source/_components/environment_canada.markdown
> +To add Environment Canada platforms to your installation, add following to your `configuration.yaml` file:
`add following` -> `add the following`

2018-07-08 11:07 UTC, frenck commented on source/_components/environment_canada.markdown
> +Configuration variables:
Remove this section, or just create a single sentence about not having configuration variables.

2018-07-08 11:07 UTC, frenck commented on source/_components/camera.environment_canada.markdown
> +logo: environment_canada.jpg
The image does not exist. Please add it to the PR.

2018-07-08 11:07 UTC, frenck commented on source/_components/sensor.environment_canada.markdown
> +  - Closest station to latitude / longitude from sensor configuration
- `Closest` -> `The closest`
- `latitude / longitude` -> `latitude/longitude`

2018-07-08 11:07 UTC, frenck commented on source/_components/sensor.environment_canada.markdown
> +  - Closest station to latitude / longitude from Home Assistant core configuration
- `Closest` -> `The closest`
- `latitude / longitude` -> `latitude/longitude`

2018-07-08 11:07 UTC, frenck commented on source/_components/sensor.environment_canada.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-07-08 11:07 UTC, frenck commented on source/_components/weather.environment_canada.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-07-08 11:07 UTC, frenck commented on source/_components/weather.environment_canada.markdown
> +  - Closest station to latitude / longitude from sensor configuration
- `Closest` -> `The closest`
- `latitude / longitude` -> `latitude/longitude`

2018-07-08 11:07 UTC, frenck commented on source/_components/weather.environment_canada.markdown
> +  - Closest station to latitude / longitude from Home Assistant core configuration
- `Closest` -> `The closest`
- `latitude / longitude` -> `latitude/longitude`

2018-07-08 12:27 UTC, michaeldavie commented
Thanks, I've made the changes you pointed out. Please let me know if anything else needs to be adjusted.

2018-07-08 14:26 UTC, frenck commented
Thanks for updating the PR @michaeldavie!
Nevertheless, now the build fails.
Could you take a look? 👍

2018-07-08 15:03 UTC, michaeldavie commented
My bad; I broke one of the configuration variable descriptions over two lines. The error message was a bit cryptic (it was referring to `Line 12`, but it meant inside the variable block. Anyway, it's back on track.

2018-07-09 11:28 UTC, frenck approved these changes

2018-07-09 11:29 UTC, frenck commented
Nice @michaeldavie!

✅ Approved. Can be merged as soon as the parent PR gets merged in.

2018-07-26 10:19 UTC, frenck commented
Closing this PR, since the parent PR has been closed. Feel free to re-open when ready.

2018-07-26 10:19 UTC, closed without merging