add climate.broadlink doc
home-assistant/home-assistant.github.io pull request #5692
Opened 2018-07-08 17:06 UTC by clementTal

**Description:**
The broadlink_thermostat climate platform is a thermostat implemented in Home Assistant. It uses a sensor and a switch connected to a heater or air conditioning under the hood. When in heater mode, if the measured temperature is cooler then the target temperature, the heater will be turned on and turned off when the required temperature is reached. When in air conditioning mode, if the measured temperature is hotter then the target temperature, the air conditioning will be turned on and turned off when required temperature is reached.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15363

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-09 10:25 UTC, frenck requested changes
@clementTal Thank for this PR!
I've reviewed and left some comments. Could you please take a look? 👍

2018-07-09 10:25 UTC, frenck commented on source/_components/climate.broadlink.markdown
> +ha_release: 0.73
`0.73` has already been shipped. Please use the next major version (`0.74` atm)

2018-07-09 10:25 UTC, frenck commented on source/_components/climate.broadlink.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-07-09 10:25 UTC, frenck commented on source/_components/climate.broadlink.markdown
> +logo: heat-control.png
Please use the brand logo: `broadlink.png`

2018-07-09 10:25 UTC, frenck commented on source/_components/climate.broadlink.markdown
> +The `broadlink_thermostat` climate platform is a thermostat implemented in Home Assistant. It uses a sensor and a switch connected to a heater or air conditioning under the hood. When in heater mode,
- `temperature is cooler` -> ` temperature is colder`
- `then the target temperature` -> `than the target temperature`
- `when required temperature` -> `when the required temperature`

2018-07-09 17:56 UTC, frenck commented
@clementTal Thanks for the update, nevertheless, now the build fails.

Also, please remove the `Configuration variables:` header as well, since that one is also generated by the configuration tags.

2018-09-21 11:40 UTC, frenck commented
Closing this PR, since parent PR has been closed as well. Feel free to re-open when ready.

2018-09-21 11:40 UTC, closed without merging

2018-10-06 04:34 UTC, thundergreen commented
Would be a pity if this pull request wouldn't be merged but maybe there could be also parameters in config to turn on the heating if a temperature falls to a certain value?