Create mitsubishicontroller.markdown
home-assistant/home-assistant.github.io pull request #5720
Opened 2018-07-09 12:04 UTC by adgelbfish

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15299

## Checklist:

- [X] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-09 12:24 UTC, frenck requested changes
@adgelbfish Thank you!
Looks great in general, just left a single note.
Could you please take a look?  👍

2018-07-09 12:24 UTC, frenck commented on source/_components/mitsubishicontroller.markdown
> +logo: daikin.png
This logo is incorrect, right?

2018-07-09 13:50 UTC, adgelbfish commented
@frenck thanks! It should be fixed now.

2018-07-09 17:50 UTC, frenck approved these changes

2018-07-09 17:51 UTC, frenck commented
Looks good @adgelbfish! Thank you for updating.

✅ Approved. Can be merged as soon as the parent PR gets merged in.

2018-08-09 14:45 UTC, frenck commented
Closing this PR, since the parent PR has been closed as well.
Feel free to re-open when ready.

2018-08-09 14:45 UTC, closed without merging