added letter support
home-assistant/home-assistant.github.io pull request #5731
Opened 2018-07-09 19:36 UTC by scheric

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15389

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

- [ ]  Approved by myself

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-10 09:44 UTC, hmmbob commented
typo in multiple locations: packege --> package

2018-07-12 04:16 UTC, iMicknl requested changes
Typo's

2018-07-12 04:16 UTC, iMicknl commented on source/_components/sensor.postnl.markdown
> +The letters sensor value shows the number of letters to be deliverd.
deliverd -> delivered

2018-07-12 04:16 UTC, iMicknl commented on source/_components/sensor.postnl.markdown
> +  If you want to receve data from the letter sensor you need to enable it in the PostNL-app for Android ore IOS.
receve -> receive
ore -> or
IOS -> iOS

2018-07-12 04:16 UTC, iMicknl commented on source/_components/sensor.postnl.markdown
> +  See [this](https://www.postnl.nl/campagnes/mijn-post-in-de-app/) for more detaild instructions.
detaild -> detailed

2018-07-12 04:27 UTC, iMicknl commented on source/_components/sensor.postnl.markdown
> +  description: Enable ore disable letters
ore -> or

2018-07-29 09:32 UTC, frenck approved these changes

2018-07-29 09:32 UTC, frenck commented
Looks good to me! Thanks, @scheric!
Can be merged as soon as the parent PR gets merged.

2018-08-09 14:50 UTC, frenck commented
Closing this PR, since the parent PR has been closed as well.
Feel free to re-open when ready.

2018-08-09 14:50 UTC, closed without merging