Add Tuya component and platform document
home-assistant/home-assistant.github.io pull request #5739
Opened 2018-07-10 03:48 UTC by huangyupeng

**Description:**
This PR add documentation for tuya component and cover.tuya, climate.tuya, fan.tuya, light.tuya, scene.tuya, switch.tuya platform. 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-12 08:42 UTC, MartinHjelmare requested changes
Please update the documentation to the changed parent PR and remove all platforms except switch.

2018-07-12 08:42 UTC, MartinHjelmare commented on source/_components/tuya.markdown
> +Devices state data and new devices will refresh automatically. If you want to refresh all devices information or get new devices related to your account manually, you can call the `force_update` or `
Missing period at the end of the sentence.

2018-07-12 09:22 UTC, MartinHjelmare submitted a review, later dismissed
Looks good!

2018-07-13 12:30 UTC, frenck approved these changes

2018-07-13 12:31 UTC, merged