Enable missing octopress-filters gem
home-assistant/home-assistant.github.io pull request #5857
Opened 2018-07-23 07:17 UTC by grischard

**Description:**

Fixes #5856 maybe?

The atom.xml template uses the `full_urls` filter which is part of the `octopress-filters` gem, which is missing from the Gemfile.

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-23 07:21 UTC, grischard commented
I'm not sure why the CI doesn't find the gem on rubygems, [it's right there](https://rubygems.org/gems/octopress-filters)...

2018-08-13 23:17 UTC, frenck commented
Sorry for the long wait.

The issue is that you've simply added it to the Gemfile (guess by the branch name, using the GitHub editor).

This, however, does not update the lock file. Run `bundle install` to update it and add the lock file.

2018-08-13 23:17 UTC, frenck requested changes
Please update the lock file.

2018-08-30 13:02 UTC, grischard commented
I've updated the lock file.

2018-08-30 13:18 UTC, grischard commented
And now it's failing and I have no idea why - I couldn't really find something with `empty` or `nil:NilClass` so I imagine it's something like a missing argument?

2018-09-19 22:10 UTC, grischard commented
@frenck Help! Any ideas?

2018-09-21 14:46 UTC, frenck commented
Assigned myself an reminder to take a look.

2018-10-03 18:42 UTC, frenck commented
Looking into this one right now. I wonder if the gem is needed to achieve this. Will test this locally.

2018-10-03 20:11 UTC, frenck commented
@grischard I've been able to reproduce the issue locally.
It seems to be related to a plugin this website uses:

https://github.com/home-assistant/home-assistant.io/blob/fef1e594d5d2089f1987cc48f0fce08da8edb2cd/plugins/category_generator.rb#L98

Nevertheless, I was unable to get the wished output with your offered solution.

2018-10-06 19:38 UTC, frenck commented
Closing this issue because of the above reasons.
Feel free to open a PR with another solution.

2018-10-06 19:38 UTC, closed without merging