WIP: Update Configuration Variables section
home-assistant/home-assistant.github.io pull request #5887
Opened 2018-07-25 15:48 UTC by tjorim

**Description:**
Updates the Configuration Variables section of several components I use according to the docs: https://developers.home-assistant.io/docs/en/documentation_create_page.html

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-28 14:47 UTC, tjorim commented
Would like to know the answer to https://github.com/home-assistant/home-assistant/pull/15143#issuecomment-408599718, to reflect correct options in the documentation.

2018-07-28 15:36 UTC, dale3h requested changes
- Please change all `default: True` to `default: true` (preferred for YAML)
- Please change all `default: False` to `default: false` (preferred for YAML)
- Please reduce all lines to 80 characters or less where possible. To reduce lines with URLs, it is preferred to use reference links in the entire document.

This is just a preliminary review. Another review will be conducted after these changes have been addressed.

2018-07-28 15:36 UTC, dale3h commented on source/_components/binary_sensor.ihc.markdown
> +      default: False
Please change to all lowercase (`default: false`).

2018-07-28 15:36 UTC, dale3h commented on source/_components/cover.template.markdown
> +        default: False
Please change to all lowercase (`default: false`).

2018-07-28 15:36 UTC, dale3h commented on source/_components/cover.template.markdown
> +        default: False
Please change to all lowercase (`default: false`).

2018-07-28 15:36 UTC, dale3h commented on source/_components/cover.template.markdown
> +If you are using the state of a platform that takes extra time to load, the Template Cover may get an `unknown` state during startup. This results in error messages in your log file until that platfo
Please revert back to <=80 characters per line.

2018-07-28 15:36 UTC, dale3h commented on source/_components/cover.template.markdown
> +with this equivalent that returns `true`/`false` and never gives an unknown result:
Please revert back to <=80 characters per line.

2018-07-28 15:36 UTC, dale3h commented on source/_components/cover.template.markdown
> +In optimistic mode, the cover position state is maintained internally. This mode is automatically enabled if neither [`value_template`](#value_template) or [`position_template`](#position_template) a
Please revert back to <=80 characters per line.

2018-07-28 15:36 UTC, dale3h commented on source/_components/cover.template.markdown
> +This example converts a garage door with a controllable switch and position sensor into a cover.
Please revert back to <=80 characters per line.

2018-07-29 10:21 UTC, frenck commented
@tjorim, I really like the effort you are putting off here.
Nevertheless, the PR becomes really big. Almost too big to handle.

Please use smaller PR's., those are easier to move forward.

2018-07-29 10:39 UTC, tjorim commented
@frenck You're probably right, I'm sorry. Is it ok if I stop now?

2018-07-30 18:42 UTC, tjorim commented
New PR: https://github.com/home-assistant/home-assistant.io/pull/5929

2018-07-30 18:42 UTC, closed without merging