Add documentation and logo for Aladdin Connect cover
home-assistant/home-assistant.github.io pull request #5903
Opened 2018-07-27 03:47 UTC by shoejosh

**Description:**
Documentation for Aladdin Connect Cover

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15699

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-29 10:11 UTC, frenck submitted a review, later dismissed

2018-07-29 10:12 UTC, frenck commented
Thank you, @shoejosh! Those are some pretty nice additions to the project 👍 
✅ Approved. Can be merged as soon as the parent PR get merged.

2018-07-30 05:24 UTC, MartinHjelmare requested changes

2018-07-30 05:24 UTC, MartinHjelmare commented on source/_components/cover.aladdin_connect.markdown
> +---
Please add `ha_iot_class` to the front matter. I assume the value should be `Cloud Polling`.

2018-07-30 05:52 UTC, frenck commented on source/_components/cover.aladdin_connect.markdown
> +---
Well spotted @MartinHjelmare!

2018-07-30 05:53 UTC, frenck commented
@shoejosh, can you take a look? 👍

2018-07-31 02:59 UTC, MartinHjelmare approved these changes
Great!

2018-07-31 03:01 UTC, merged