Update MVG documentation for changes in 15454
home-assistant/home-assistant.github.io pull request #5908
Opened 2018-07-28 08:46 UTC by mountainsandcode

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15454

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-07-29 08:41 UTC, frenck approved these changes

2018-07-29 08:42 UTC, frenck commented
Looks good, can be merged as soon as the parent PR gets merged.
Thank @mountainsandcode! 👍

2018-07-29 08:42 UTC, frenck submitted a review, later dismissed

2018-07-30 07:05 UTC, DavidMStraub commented
Perfect, thanks!

2018-07-30 08:36 UTC, MartinHjelmare requested changes

2018-07-30 08:36 UTC, MartinHjelmare commented on source/_components/sensor.mvglive.markdown
> +The second sensor returns U2 and U8 departures from Sendlinger Tor and stores a total of 5 departures in attributes. To retrieve the time until the second departure, you would use states.sensor.entiy
states.sensor.ENTITY_NAME.attributes.departures[1].time.

2018-07-30 09:05 UTC, frenck approved these changes

2018-07-30 09:07 UTC, MartinHjelmare approved these changes
Great!

2018-07-30 09:18 UTC, merged