Update Roomba to reflect the new state of things
home-assistant/home-assistant.github.io pull request #5939
Opened 2018-08-01 12:57 UTC by arbreng

**Description:**
Updated to reflect that the platform is no longer a toggle and therefor won't support turn_on and turn_off.

Pull request in home-assistant (if applicable): https://github.com/home-assistant/home-assistant/pull/15779

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-08-01 13:00 UTC, arbreng commented
Part of: https://github.com/home-assistant/architecture/issues/29

2018-08-18 14:01 UTC, DubhAd approved these changes
👍

2018-10-29 07:55 UTC, frenck commented
Parent is still open, reopening PR.

2018-10-29 07:56 UTC, frenck requested changes
@arbreng Merge conflicts have occurred!
Could you please take a look and resolve them? 👍

2018-12-24 20:16 UTC, frenck commented
Closing this PR, since the parent PR has been closed as well.

2018-12-24 20:16 UTC, closed without merging