specify security concerns and actions to mitigate them.
home-assistant/home-assistant.github.io pull request #5944
Opened 2018-08-03 19:14 UTC by finity69x2

With the focus on security concerns in the forums recently I think it would benefit users to be more aggressive in recommending actions to take to secure home assistant when exposing it to the internet. Vague warnings don't always catch the eye of the casual user. I was one of those users and the forum threads on security caused me to examine my own security and I then realized how potentially lacking that it was.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-08-04 20:26 UTC, frenck requested changes
We should not shout in our docs...

EVER 😉 

So I'm not approving this in the current state.

2018-08-04 20:26 UTC, frenck commented on source/_docs/configuration/securing.markdown
> +If you want to allow remote access, consider taking the additional steps as listed below. They are listed from the most secure to the least secure. IT IS HIGHLY RECOMMENDED THAT IF YOU ARE GOING TO B
We don't have to shout.
Secondly, VPN is not the golden ticket, there are more possibilities.

2018-08-04 21:50 UTC, finity69x2 commented
Of course. I always forget the "all caps is shouting" standard. I've corrected it with bolding. I hope that's acceptable.

As for the VPN recommendation - I realize there may be other more secure routes to take (which is why I made it #3 on the list) but it should be the minimum to feel fairly secure. And if there are other better options not on the list they should probably be added. I don't have the experience to know what they are or I would add them here with my edit.

2018-08-11 09:23 UTC, DubhAd commented on source/_docs/configuration/securing.markdown
> +If you want to allow remote access, consider taking the additional steps as listed below. They are listed from the most secure to the least secure. <b>It is highly recommended that if you are going t
Hmmm, I'm having difficulty with the "Tor is more secure than a VPN or an SSH tunnel" statement. If we're going to have statements like that lets have some evidence ;)

2018-08-11 18:23 UTC, finity69x2 commented on source/_docs/configuration/securing.markdown
> +If you want to allow remote access, consider taking the additional steps as listed below. They are listed from the most secure to the least secure. <b>It is highly recommended that if you are going t
I'm no internet security expert but in my investigating the different options it just seemed as the Tor option was a little more secure. I may be (and probably am...) wrong. 

I was just simply trying to impress upon new users the importance of securing their installation with something more substantial than a simple password if they want to access it from the outside world . And imparting the understanding that using Letsencrypt or a reverse proxy isn't much better since they are, ultimately, still just protected by a simple password.

If you have a recommendation on how to get that point across for new people who aren't internet security experts who want to be able to safely access their HA from the outside (and I think most people actually want to do that since that's the impression given from looking at the very first page on the HA website...), please feel free to share.

I'm pretty confident in saying that Tor, SSH tunnel or a VPN are all likely way more secure than a password, letsencrypt or a simple reverse proxy. We can quibble about the details but in the end  letting people know of more safe options is what's important.

2018-08-11 20:45 UTC, DubhAd commented on source/_docs/configuration/securing.markdown
> +If you want to allow remote access, consider taking the additional steps as listed below. They are listed from the most secure to the least secure. <b>It is highly recommended that if you are going t
I'd agree that Tor/SSH/VPN are likely more secure, but ranking those...

Maybe more a *we would suggest that if you don't need remote access to the API (for example, for a device tracker) you should use one of the first three options*

2018-08-13 08:35 UTC, finity69x2 commented
@DubhAd 

I made a change as recommended. Hopefully it works for you.

2018-08-13 18:02 UTC, DubhAd approved these changes
Thanks

2018-10-06 13:09 UTC, frenck commented
The documentation has been revamped. This PR is now a use merge conflict.
Some elements of this PR are integrated as well.

Closing this one.

2018-10-06 13:09 UTC, closed without merging