Adding enigma2 docs
home-assistant/home-assistant.github.io pull request #5984
Opened 2018-08-09 12:39 UTC by fbradyirl

**Description:**
Adding enigma2 docs

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15799

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-08-09 19:09 UTC, frenck requested changes

2018-08-09 19:09 UTC, frenck commented on source/_components/media_player.enigma2.markdown
> +    name: Vu Duo2
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-08-09 22:45 UTC, fbradyirl reviewed
@frenck agree with your comments. I’ve removed the optional config from sample.

2018-10-04 19:22 UTC, frenck approved these changes

2018-10-17 02:44 UTC, tjorim requested changes
@fbradyirl, only one question for you sir.


⚠️ The `ha_release` will need an update before merging this one in.

2018-10-17 02:44 UTC, tjorim commented on source/_components/media_player.enigma2.markdown
> +{% configuration %}
According to the code the network port can be configured as well.
If that is correct, add it to this section and mention the default (80).

2018-10-18 19:10 UTC, frenck requested changes
You are right, @tjorim!
@fbradyirl, could you add the missing option? 👍

2018-11-03 00:45 UTC, cgarwood commented
Parent PR went stale and was closed, closing this one.

2018-11-03 00:45 UTC, closed without merging