Update bmw_connected_drive.markdown
home-assistant/home-assistant.github.io pull request #6024
Opened 2018-08-15 20:27 UTC by Alexxander0

**Description:**
Update of documentation of the BMW connected drive platform

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-08-15 21:22 UTC, frenck commented
Hi there @Alexxander0!

Thank you for this PR! Unfortunately, it is targeted against the wrong base. Since this is a new feature (implemented in your parent PR), it will be part of a next release, so it should go into the `next` branch.

Please update the target branch and rebase if needed.

2018-08-16 20:27 UTC, tjorim requested changes

2018-08-16 20:27 UTC, tjorim commented on source/_components/bmw_connected_drive.markdown
> +      description: Enables or disables the services of the vehicles including the lock. Default false (Services enabled)
Please use the `default:` key to clarify what the default is -> [documentation](https://developers.home-assistant.io/docs/en/documentation_create_page.html).

2018-08-17 09:52 UTC, frenck approved these changes

2018-08-17 09:52 UTC, frenck commented
Thanks, @Alexxander0! 🏅

2018-08-17 09:52 UTC, merged