Smarty component
home-assistant/home-assistant.github.io pull request #6086
Opened 2018-08-26 18:40 UTC by z0mbieprocess

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [X] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-06 13:27 UTC, DubhAd requested changes

2018-10-06 13:27 UTC, DubhAd commented on source/_components/fan.smarty.markdown
> +ha_release: "0.77"
No longer 0.77

2018-10-06 13:27 UTC, DubhAd commented on source/_components/sensor.smarty.markdown
> +ha_release: "0.77"
No longer 0.77

2018-10-06 13:27 UTC, DubhAd commented on source/_components/smarty.markdown
> +ha_release: "0.77"
No longer 0.77

2018-10-06 13:27 UTC, DubhAd commented on source/_components/smarty.markdown
> +- **name** (*Optional*): The name of this device as you want to see it in Home Assistant.
Please use a configuration block, as [in the doc standards](https://developers.home-assistant.io/docs/en/documentation_standards.html#component-and-platform-pages).

2018-10-08 10:14 UTC, DubhAd submitted a review, later dismissed

2018-10-17 02:01 UTC, tjorim commented on source/_components/smarty.markdown
> +  default: smarty
Default is Smarty with a capital letter according to the code.

2018-10-17 02:05 UTC, tjorim requested changes
@z0mbieprocess, thanks for your first documentation PR!
I requested some small changes, good luck.

⚠️ The `ha_release` will need an update before merging this one in.

2018-10-17 02:05 UTC, tjorim commented on source/_components/smarty.markdown
> +  default: smarty
Default is Smarty with a capital letter according to the code.

2018-10-17 02:05 UTC, tjorim commented on source/_components/smarty.markdown
> +Configuration variables:
This line is not needed, the `{% configuration %}` will put it in here.
(when removing this remember to delete one empty line as well)

2018-10-18 18:56 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2018-12-25 19:33 UTC, frenck commented
Re-opening PR, since the parent PR is still open.

2018-12-25 21:57 UTC, frenck approved these changes

2019-02-06 01:12 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2019-02-06 01:12 UTC, closed without merging