Update rflink.markdown
home-assistant/home-assistant.github.io pull request #6101
Opened 2018-08-28 12:34 UTC by samuelsson86

**Description: RFLink Switches cannot be added automatically. This is wrong in the documentation**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant.io/source/_components/rflink.markdown)

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

This is my first pull request. Tell me if I did anything wrong. Thank you!

2018-09-09 11:44 UTC, frenck commented
Changes to the current documentation need to go into the `current` branch.
Please change the target to `current` and rebase.

2018-09-09 11:44 UTC, frenck requested changes
Please rebase

2018-09-11 11:01 UTC, frenck commented
@samuelsson86 As you can see in the PR right now, there are many commits in here that are not yours. You've merged in `current` into your branch... instead of rebasing.

Could you take a look at fixing this?

2018-09-11 12:09 UTC, samuelsson86 commented
@frenck as you may have noticed, I have zero experience with Github and coding in general. 

I thought it would be a lot easier to change wrong information in the home assistant documentation. Can you point me in the right direction in how I fix this issue? I completely understand if you don't have the time and would it then work to just delete the pull request? I really hope I haven't changed something yet. 

I'm so sorry. I'll make sure to read up on how github works before I change something else.

2018-09-21 10:03 UTC, frenck commented
Assigned myself as a reminder to pick this one up.

2018-10-04 19:32 UTC, frenck approved these changes

2018-10-04 19:33 UTC, frenck commented
Sorry for the long wait @samuelsson86! But I've fixed it 🎉 

✅ Approved. Thank you very much for this valuable addition to our documentation 🥇 

../Frenck

2018-10-04 19:33 UTC, merged