Update fail2ban.markdown
home-assistant/home-assistant.github.io pull request #6104
Opened 2018-08-29 05:32 UTC by mplinuxgeek

Updated using more consistent paths for the filter and jail configuration.
Added additional checks to help confirm everything working as expected.
Added steps to unblock an IP address.
Updated jail conf file includes email alerts.
Removed the syslog section, this step is not required for fail2ban thus optional and only required if you want HA logs to be sent to syslog, should be covered by another page.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-08-29 18:22 UTC, fabaff commented on source/_cookbook/fail2ban.markdown
> +```sudo fail2ban-client status
Dito

2018-08-29 18:22 UTC, fabaff commented on source/_cookbook/fail2ban.markdown
> +```logger:
This needs be reverted. `yaml` is for the syntax highlighting.

2018-08-29 18:22 UTC, fabaff commented on source/_cookbook/fail2ban.markdown
> +```sudo yum install epel-release
`epel-release` is not needed for Fedora.

2018-08-29 18:24 UTC, fabaff requested changes
The file needs to follow the markdown standards.

2018-08-29 22:42 UTC, mplinuxgeek commented on source/_cookbook/fail2ban.markdown
> +```sudo yum install epel-release
Fixed

2018-08-29 22:42 UTC, mplinuxgeek commented on source/_cookbook/fail2ban.markdown
> +```logger:
Fixed

2018-08-29 22:42 UTC, mplinuxgeek commented on source/_cookbook/fail2ban.markdown
> +```sudo fail2ban-client status
Fixed

2018-08-30 07:03 UTC, fabaff approved these changes
Thanks :bird:

2018-08-30 07:03 UTC, merged