Add shelly documentation
home-assistant/home-assistant.github.io pull request #6110
Opened 2018-08-29 15:10 UTC by ispiropoulos

**Description:**
Documentation for the shelly switch component

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#16268

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-09-29 12:15 UTC, DubhAd submitted a review, later dismissed
👍

2018-09-30 13:26 UTC, frenck requested changes

2018-09-30 13:26 UTC, frenck commented on source/_components/switch.shelly.markdown
> +ha_release: 0.76
0.76 has been ship a while back already, please update the version number to the next major release.

2018-09-30 13:26 UTC, frenck commented on source/_components/switch.shelly.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-09-30 13:27 UTC, frenck commented
@ispiropoulos I've reviewed your PR and left you some comments. Could you please take a look? 👍

2018-10-20 00:56 UTC, zsarnett commented
@ispiropoulos

2018-10-21 09:53 UTC, frenck commented on source/_components/switch.shelly.markdown
> +Configuration variables:
@ispiropoulos Not sure why you've marked this comment as "Resolved", while it is not.
Please convert the configuration variables section as per link listed above.

2018-12-24 20:21 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2018-12-24 20:21 UTC, closed without merging