GreenEye Monitor component docs
home-assistant/home-assistant.github.io pull request #6177
Opened 2018-09-03 03:28 UTC by jkeljo

**Description:**
Adding documentation for the new GreenEye Monitor component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#16378

## Checklist:

- [X] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-09-29 12:19 UTC, DubhAd submitted a review, later dismissed
👍

2018-10-25 19:57 UTC, frenck requested changes

2018-10-25 19:57 UTC, frenck commented on source/_components/greeneye_monitor.markdown
> +          type: positive_int
`postive_int` is not a valid documentation type.

```suggestion
          type: integer
```

2018-10-25 19:57 UTC, frenck commented on source/_components/greeneye_monitor.markdown
> +      type: positive_int
`postive_int` is not a valid documentation type.
```suggestion
      type: integer
```

2018-10-25 19:57 UTC, frenck commented on source/_components/greeneye_monitor.markdown
> +          type: temperature_unit
`temperature_unit` is not a valid documentation type.

```suggestion
          type: string
```

2018-10-25 19:57 UTC, frenck commented on source/_components/greeneye_monitor.markdown
> +              type: positive_int
`postive_int` is not a valid documentation type.
```suggestion
              type: integer
```

2018-10-25 19:57 UTC, frenck commented on source/_components/greeneye_monitor.markdown
> +          type: positive_int
`postive_int` is not a valid documentation type.
```suggestion
          type: integer
```

2018-10-25 19:57 UTC, frenck commented on source/_components/greeneye_monitor.markdown
> +          type: s, min, h
`s, min, h` is not a valid documentation type.

```suggestion
          type: string
```

2018-10-25 19:57 UTC, frenck commented on source/_components/greeneye_monitor.markdown
> +ha_release: 0.75
`0.75` has been shipped already, please update to `0.82` (nice starting point)

2018-10-25 19:57 UTC, frenck commented on source/_components/sensor.greeneye_monitor.markdown
> +ha_release: 0.75
`0.75` has been shipped already, please update to `0.82` (nice starting point)

2018-10-25 19:57 UTC, frenck commented on source/_components/greeneye_monitor.markdown
> +          description: The unit being counted by this pulse counter (e.g. gal, L)
```suggestion
          description: The unit being counted by this pulse counter (e.g., gal, L)
```

2018-10-25 19:57 UTC, frenck commented
Thanks for the PR @jkeljo, I've reviewed it, and left some comments.
Could you please take a look? 👍

2018-11-01 09:53 UTC, MartinHjelmare commented on source/_components/greeneye_monitor.markdown
> +featured: false
This is the default.

2018-11-01 11:18 UTC, frenck approved these changes

2018-11-01 11:39 UTC, merged