Add docs for new EDP re:dy component
home-assistant/home-assistant.github.io pull request #6200
Opened 2018-09-04 22:49 UTC by abmantis

**Description:**
Docs for a new integration of the EDP re:dy platform.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-09-09 14:20 UTC, tjorim requested changes

2018-09-09 14:20 UTC, tjorim commented on source/_components/edp_redy.markdown
> +{% configuration %}
Please fix the indentation, remove 2 leading spaces from each line.
https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration

2018-09-15 23:24 UTC, MartinHjelmare commented on source/_components/edp_redy.markdown
> +ha_release: "0.78"
0.79

2018-09-15 23:24 UTC, MartinHjelmare commented on source/_components/sensor.edp_redy.markdown
> +ha_release: "0.78"
0.79

2018-09-15 23:24 UTC, MartinHjelmare commented on source/_components/sensor.edp_redy.markdown
> +ha_category: Hub
Sensor

2018-09-15 23:24 UTC, MartinHjelmare commented on source/_components/switch.edp_redy.markdown
> +ha_category: Hub
Switch

2018-09-15 23:24 UTC, MartinHjelmare commented on source/_components/switch.edp_redy.markdown
> +ha_release: "0.78"
0.79

2018-09-16 08:15 UTC, MartinHjelmare approved these changes

2018-09-16 08:17 UTC, merged