Add page for KNX fan component
home-assistant/home-assistant.github.io pull request #6202
Opened 2018-09-05 11:54 UTC by itineric

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#16434

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-09-09 14:18 UTC, tjorim requested changes

2018-09-09 14:18 UTC, tjorim commented on source/_components/fan.knx.markdown
> +Configuration variables:
Replace this section according to the docs: https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration

2018-10-02 16:54 UTC, frenck commented
@itineric, @tjorim is correct. Could you please update the PR? 👍

2018-10-03 09:33 UTC, frenck requested changes

2018-10-03 09:33 UTC, frenck commented on source/_components/fan.knx.markdown
> +Configuration variables:
You need to remove this header as well, this is added automatically by the configuration tags.

2018-10-17 03:16 UTC, tjorim requested changes
Some minor things @itineric, take a look at them.
Please fix the merge conflict as well!

⚠️ The `ha_release` will need an update before merging this one in.

2018-10-17 03:16 UTC, tjorim commented on source/_components/fan.knx.markdown
> +
Remove one of these empty lines

2018-10-17 03:16 UTC, tjorim commented on source/_components/fan.knx.markdown
> +name:
Name has a default value `default: KNX Fan`

2018-10-17 03:16 UTC, tjorim commented on source/_components/fan.knx.markdown
> +    name: living-room-fan
The example may only contain the required variables to make it work, so remove `name` and `speed_state_address`

2018-12-23 06:00 UTC, closed without merging