Document the addition of ssl to alarmdecoder
home-assistant/home-assistant.github.io pull request #6222
Opened 2018-09-08 00:50 UTC by jonathanjsimon

**Description:**
This documents the changes to the alarmdecoder component to support the changes added to the underlying alarmdecoder library to add ssl functionality to that software.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-09-29 12:29 UTC, DubhAd approved these changes
👍

2018-10-17 03:33 UTC, tjorim commented
Hi @jonathanjsimon, I assume you're awaiting a new release for alarmdecoder now your PR's have been accepted?
Anyway, you may always update the  Configuration variables section to use the new tags, here is [the documentation](https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration)

2018-12-09 13:16 UTC, jonathanjsimon commented
@tjorim Not sure how I missed your comment. Yes, I'm waiting for a new release of alarmdecoder. It looks like I have some conflicts to resolve now. I'll have to take care of both of these.

2019-01-01 15:19 UTC, frenck requested changes
Please resolve merge conflicts.

2019-02-06 01:11 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2019-02-06 01:11 UTC, closed without merging