Multiple octoprint servers
home-assistant/home-assistant.github.io pull request #6278
Opened 2018-09-14 08:08 UTC by AmiSMB

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#16613

## Checklist:

- [*] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [*] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-09-29 12:54 UTC, DubhAd submitted a review, later dismissed
👍

2018-09-30 12:04 UTC, frenck requested changes

2018-09-30 12:04 UTC, frenck commented on source/_components/binary_sensor.octoprint.markdown
> +Configuration variables:
This is now duplicate? Since you've already created a new list just above this, using the new formatting.

2018-09-30 12:04 UTC, frenck commented on source/_components/octoprint.markdown
> +Configuration variables:
This is now duplicate? Since you've already created a new list just above this, using the new formatting.

2018-09-30 12:04 UTC, frenck commented on source/_components/sensor.octoprint.markdown
> +- **name** (*Required*): The name of the sensor. This needs to match a name under the Octoprint platform configuration.
This is now duplicate? Since you've already created a new list just above this, using the new formatting.

2018-09-30 12:06 UTC, frenck commented
I've reviewed your PR @AmiSMB and found that the configuration variables are now in there twice? Once with the old style, once new style.

Please complete the conversion to the new configuration tag style and remove the old style listing.

2018-10-02 08:46 UTC, frenck commented
Thanks for updating @AmiSMB 👍

2018-10-12 12:54 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2018-10-12 14:44 UTC, closed without merging