Z-Wave indicator services and bitwise filters to support Cooper Scene Controllers
home-assistant/home-assistant.github.io pull request #6288
Opened 2018-09-15 15:38 UTC by blakeblackshear

**Description:**
Added documentation for using Cooper 5-button Scene Control Keypads and the services used to enable it be integrated.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-09-29 12:47 UTC, DubhAd requested changes
Can u

2018-09-29 12:47 UTC, DubhAd commented on source/_docs/z-wave/device-specific.markdown
> +          value_id: "{{ states.sensor.scene_contrl_indicator.attributes.value_id }}"
These should technically be `"{{ state_attr('sensor.scene_contrl_indicator', 'value_id') }}"`

2018-09-29 12:47 UTC, DubhAd commented on source/_docs/z-wave/device-specific.markdown
> +            value_id: "{{ states.sensor.scene_contrl_indicator.attributes.value_id }}"
And here

2018-09-29 12:47 UTC, DubhAd commented on source/_docs/z-wave/device-specific.markdown
> +            value_id: "{{ states.sensor.scene_contrl_indicator.attributes.value_id }}"
And here

2018-09-29 12:47 UTC, DubhAd commented on source/_docs/z-wave/device-specific.markdown
> +            value_id: "{{ states.sensor.scene_contrl_indicator.attributes.value_id }}"
And here

2018-09-29 12:47 UTC, DubhAd commented on source/_docs/z-wave/device-specific.markdown
> +            value_id: "{{ states.sensor.scene_contrl_indicator.attributes.value_id }}"
And here

2018-09-29 12:47 UTC, DubhAd commented on source/_docs/z-wave/device-specific.markdown
> +            value_id: "{{ states.sensor.scene_contrl_indicator.attributes.value_id }}"
And here

2018-09-29 12:47 UTC, DubhAd commented on source/_docs/z-wave/device-specific.markdown
> +            value_id: "{{ states.sensor.scene_contrl_indicator.attributes.value_id }}"
And here

2018-09-29 12:47 UTC, DubhAd commented on source/_docs/z-wave/device-specific.markdown
> +            value_id: "{{ states.sensor.scene_contrl_indicator.attributes.value_id }}"
And here

2018-09-29 12:47 UTC, DubhAd commented on source/_docs/z-wave/device-specific.markdown
> +            value_id: "{{ states.sensor.scene_contrl_indicator.attributes.value_id }}"
And here

2018-09-29 12:47 UTC, DubhAd commented on source/_docs/z-wave/device-specific.markdown
> +            value_id: "{{ states.sensor.scene_contrl_indicator.attributes.value_id }}"
And here

2018-09-29 12:47 UTC, DubhAd commented on source/_docs/z-wave/device-specific.markdown
> +            value_id: "{{ states.sensor.scene_contrl_indicator.attributes.value_id }}"
And finally, here

2018-09-30 14:08 UTC, frenck commented
@blakeblackshear Since the parent has been merged already, this gains a little priority. Could you take a look at the comments @DubhAd left? Thanks!

2018-09-30 16:55 UTC, blakeblackshear commented
@frenck and @DubhAd updated.

2018-09-30 19:13 UTC, DubhAd approved these changes
👍

2018-09-30 19:14 UTC, merged