SMHI weather service
home-assistant/home-assistant.github.io pull request #6375
Opened 2018-09-29 05:49 UTC by helto4real

Docs for new Swedish weather service component

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** https://github.com/home-assistant/home-assistant/pull/16717

## Checklist:

- [x ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-09-30 07:07 UTC, frenck submitted a review, later dismissed

2018-09-30 07:08 UTC, frenck commented
Took the liberty to fix some minor grammar & spelling errors.
Overall the docs look great, thanks!

✅ Approved. Can be merged as soon as the parent PR get merged in.

2018-09-30 07:56 UTC, helto4real commented
Thabks @frenck for that, English is not my first language.

2018-09-30 11:19 UTC, frenck commented
@helto4real That is ok! We are here to help 😄

2018-10-08 22:00 UTC, MartinHjelmare requested changes

2018-10-08 22:00 UTC, MartinHjelmare commented on source/_components/smhi.markdown
> +ha_release: 0.80
0.81

2018-10-08 22:00 UTC, MartinHjelmare commented on source/_components/smhi.markdown
> +Only location close to sweden can be added. See [SMHI.se area](http://opendata.smhi.se/apidocs/metfcst/geographic_area.html) for more details what locations are supported.
"Only locations close to Sweden can be added."

2018-10-08 22:00 UTC, MartinHjelmare commented on source/_components/weather.smhi.markdown
> +ha_release: 0.80
0.81

2018-10-08 22:00 UTC, MartinHjelmare commented on source/_components/weather.smhi.markdown
> +## {% linkable_title Configuration %}
Don't duplicate this information. Just refer the user to the component page.

2018-10-09 05:41 UTC, MartinHjelmare approved these changes

2018-10-09 05:43 UTC, merged