Homeatic signalgen
home-assistant/home-assistant.github.io pull request #6379
Opened 2018-09-29 20:44 UTC by siom79

**Description:**

Describes the new component ``notify.homematic_signalgen`` for the homematic signal generator.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#16973

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-09-30 06:54 UTC, frenck submitted a review, later dismissed

2018-09-30 06:55 UTC, frenck commented
Docs look great! Thanks! 👍 

✅ Approved. Can be merged as soon as the parent PR gets merged.

2018-10-17 01:21 UTC, tjorim requested changes
What is that `csv.markdown` doing in this PR?

2018-10-17 01:25 UTC, tjorim requested changes

2018-10-17 01:25 UTC, tjorim commented on source/_components/notify.homematic.markdown
> +{% endconfiguration %}
In the component code is also an optional `ATTR_INTERFACE`, is it missing here?

2018-10-17 18:07 UTC, siom79 commented on source/_components/notify.homematic.markdown
> +{% endconfiguration %}
@tjorim Yes, you are right. The ``interface`` parameter was missing. I have added it now and removed the ``csv.markdown``.

2018-10-18 18:23 UTC, frenck approved these changes

2018-10-18 18:48 UTC, frenck commented
Thanks, @siom79!

2018-10-18 18:48 UTC, merged