ebusd sensor component documentation
home-assistant/home-assistant.github.io pull request #6412
Opened 2018-10-01 13:51 UTC by CrazYoshi

Integration between ebusd (https://github.com/john30/ebusd), daemon for communication with eBUS heating systems, and homeassistant using sensor component.

2018-10-01 14:12 UTC, CrazYoshi commented
I don't understand why I get this error during deploy validation `failed during stage 'deploying site': Invalid filename 'getting-started/basic/#remote-access.html'. Deployed filenames cannot contain # or ? characters`

2018-10-01 14:39 UTC, WofWca commented on source/_components/sensor.ebusd.markdown
> +Integration between ebusd (https://github.com/john30/ebusd), daemon for communication with eBUS heating systems, and homeassistant using sensor component.
What about `[ebusd](https://github.com/john30/ebusd)`?

2018-10-01 14:43 UTC, WofWca commented on source/_components/sensor.ebusd.markdown
> +title: "eBusd"
Do you think this is written in the right case? It's "ebusd" nearly everywhere.

2018-10-02 08:42 UTC, frenck requested changes
- Please restore the PR template in the opening post.
- Link this issue to the parent PR in the main repo.
- Rebase this PR onto `origin/next` to resolve the build issues.

2018-10-02 09:14 UTC, closed without merging

2018-10-02 17:08 UTC, frenck commented
Not sure why you closed this PR @CrazYoshi?

2018-10-02 17:11 UTC, WofWca commented
@frenck He replaced it with #6433.

2018-10-02 17:23 UTC, frenck commented
Thx @WofWca