add host, port, discovery and configuration options to Konnected component
home-assistant/home-assistant.github.io pull request #6493
Opened 2018-10-04 02:00 UTC by heythisisnate

**Description:**
Document the new config options in the latest Konnected component iteration.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

2018-10-04 07:28 UTC, frenck submitted a review, later dismissed

2018-10-04 07:29 UTC, frenck commented
Thanks, @heythisisnate!

✅ Approved. Can be merged as soon as the parent PR gets merged.

2018-10-17 02:54 UTC, tjorim requested changes
The parent PR has been merged!

Please reverse the order of `type`, `required` and `description` to be in line with the other documentation. Other than that, only some small changes needs to be done here.

2018-10-17 02:54 UTC, tjorim commented on source/_components/konnected.markdown
> +    discovery:
Add the default values to this section.
For discovery `default: true`

2018-10-17 02:54 UTC, tjorim commented on source/_components/konnected.markdown
> +      description: Enable or disable discovery for this device. When true, the device will respond to discovery requests on your network. When false, the device will not respond to discovery requests
Use code quotes (that backwards single quote thing) when talking about boolean values in the description:

- true  --> \`true\`
- false --> \`false\`

2018-10-17 02:54 UTC, tjorim commented on source/_components/konnected.markdown
> +    blink:
`default: true` as well

2018-10-18 19:33 UTC, frenck approved these changes
Updated the PR. Thanks for the review @tjorim. Please note, there is no standard on the order of the configuration fields.

Can be merged as soon as the build passes.

2018-10-18 19:43 UTC, merged