Documentation for home-assistant/home-assistant-polymer#1732
home-assistant/home-assistant.github.io pull request #6506
Opened 2018-10-04 11:39 UTC by thomasloven

**Description:**
Adds new `theming` option to documentation of lovelace glance card.

**Pull request in [home-assistant-polymer](https://github.com/home-assistant/home-assistant-polymer) (if applicable):** home-assistant/home-assistant-polymer#1732

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-04 18:03 UTC, frenck requested changes
@thomasloven Thanks! I've reviewed it and left a question, could you take a look? 👍

2018-10-04 18:03 UTC, frenck commented on source/_lovelace/glance.markdown
> +  default: "default"
Judging by the code, there is no default explicitly set.
So I guess this line should be left out?

2018-10-04 19:24 UTC, thomasloven commented on source/_lovelace/glance.markdown
> +  default: "default"
Correct. I forgot to fix that after the latest revision of the code.

2018-10-05 08:27 UTC, balloob approved these changes

2018-10-05 08:27 UTC, merged