Add device registry for MQTT sensors
home-assistant/home-assistant.github.io pull request #6513
Opened 2018-10-04 18:22 UTC by OttoWinter

**Description:**

Add device registry integration to MQTT sensors. The plan is to expand it to other platforms too.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#16943

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-06 13:40 UTC, DubhAd submitted a review, later dismissed
👍

2018-10-08 18:58 UTC, frenck requested changes
@OttoWinter Left you some comments, could you please take a look?

2018-10-08 18:58 UTC, frenck commented on source/_components/sensor.mqtt.markdown
> +  description: 'Information about the device this sensor is a part of to tie it into the [device registry](https://developers.home-assistant.io/docs/en/device_registry_index.html). Only works through
Some commas would make it more readable (just like the other PRs).

2018-10-08 18:58 UTC, frenck commented on source/_components/sensor.mqtt.markdown
> +      type: list, tuple
`tuple` is not a valid documentation configuration type.

2018-10-11 20:25 UTC, frenck approved these changes

2018-10-11 20:25 UTC, merged