Update sensors.mitemp_bt configuration variables
home-assistant/home-assistant.github.io pull request #6531
Opened 2018-10-05 11:27 UTC by Mryck

**Description:**

Update sensors.mitemp_bt configuration variables #6385

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-05 13:18 UTC, frenck requested changes

2018-10-05 13:18 UTC, frenck commented on source/_components/sensor.mitemp_bt.markdown
> +  type: list
Please define the `keys` section.

2018-10-05 13:19 UTC, frenck commented
Overall it looks good @Mryck, just one small adjustment. Could you take a look? 👍

2018-10-05 14:18 UTC, Mryck commented
Thanks @frenck it should be fine now.

2018-10-06 12:48 UTC, frenck approved these changes

2018-10-06 12:49 UTC, frenck commented
Thanks for the update @Mryck!

Happy Hacktoberfest 🎉 

../Frenck

2018-10-06 12:49 UTC, merged