Adds documentation for Lupusec alarm control panel
home-assistant/home-assistant.github.io pull request #6601
Opened 2018-10-08 08:39 UTC by majuss

**Description:**
This PR add support for the alarm control panel from Lupus Electronics. For now the panel and sensors are supported and tested.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-08 08:51 UTC, klaasnicolaas requested changes

2018-10-08 08:51 UTC, klaasnicolaas commented on source/_components/alarm_control_panel.lupusec.markdown
> +Configuration variables:
Use the new configuration variable syntax: [more info](https://developers.home-assistant.io/docs/en/documentation_create_page.html)

2018-10-08 18:18 UTC, frenck requested changes
Hi there @majuss, thank you for this PR.

I and @klaasnicolaas left you some comments. Could you please take a look? 👍

2018-10-08 18:18 UTC, frenck commented on source/_components/alarm_control_panel.lupusec.markdown
> +      scan_interval: 2
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-10-08 18:18 UTC, frenck commented on source/_components/alarm_control_panel.lupusec.markdown
> +      username: user
Please use all CAPS constant like placeholders. For example, `YOUR_USERNAME`.

2018-10-08 18:18 UTC, frenck commented on source/_components/alarm_control_panel.lupusec.markdown
> +      password: 'greatpassword'
Please use all CAPS constant like placeholders. For example, `YOUR_PASSWORD`.

2018-10-08 18:18 UTC, frenck commented on source/_components/alarm_control_panel.lupusec.markdown
> +ha_release: 0.79
`0.79` has been shipped already some time ago. The next possible release would be `0.81`.

2018-10-08 18:18 UTC, frenck commented on source/_components/binary_sensor.lupusec.markdown
> +ha_release: 0.79
`0.79` has been shipped already some time ago. The next possible release would be `0.81`.

2018-10-08 18:18 UTC, frenck commented on source/_components/lupusec.markdown
> +ha_release: 0.79
`0.79` has been shipped already some time ago. The next possible release would be `0.81`.

2018-10-08 18:18 UTC, frenck commented on source/_components/switch.lupusec.markdown
> +ha_release: 0.79
`0.79` has been shipped already some time ago. The next possible release would be `0.81`.

2018-10-08 18:31 UTC, majuss commented
@frenck @klaasnicolaas Thanks for the comments! I will work them off.

2018-10-09 10:43 UTC, frenck submitted a review, later dismissed

2018-10-09 10:43 UTC, frenck commented
Thanks, @majuss.

Can be merged as soon as the parent PR gets merged.

2018-10-09 10:44 UTC, majuss commented
Thank you for the fine tuning!

2018-10-09 10:46 UTC, frenck commented
@majuss Your welcome sir! 👍

2018-10-17 01:45 UTC, tjorim reviewed
Good luck with your first PR, @majuss!
I left some feedback on the documentation.

2018-10-17 01:45 UTC, tjorim commented on source/_components/lupusec.markdown
> +  description: The login username of your lupusec alarm panel.
Please write Lupusec with a capital letter here,

2018-10-17 01:45 UTC, tjorim commented on source/_components/lupusec.markdown
> +  description: The login password of your lupusec alarm panel.
here,

2018-10-17 01:45 UTC, tjorim commented on source/_components/lupusec.markdown
> +  description: The IP-address of your lupusec alarm panel.
and here as well.

2018-10-17 01:45 UTC, tjorim commented on source/_components/lupusec.markdown
> +  default: 2
Isn't the default value 5 seconds? https://github.com/home-assistant/home-assistant/pull/17237/files#diff-e34648182c47cb2ba95be679ce4023b1R23
(I do see that in other places it's 2 so I'm not sure)

2018-10-17 01:45 UTC, tjorim commented on source/_components/lupusec.markdown
> +  description: Scanning interval in seconds. Lower that value to get faster responses from your alarm panel but raise the temperatures and ressource usage.
Typo: ressource --> resource (and sentence seems a bit off)

2018-10-17 01:45 UTC, tjorim commented on source/_components/lupusec.markdown
> +
Remove this empty line

2018-10-17 01:51 UTC, tjorim reviewed
Is "Cloud Push" the correct IoT class? Not Local?

2018-10-17 11:17 UTC, majuss commented
@tjorim I think I got everything.

2018-10-18 18:46 UTC, frenck submitted a review, later dismissed

2018-10-18 18:46 UTC, frenck commented
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2018-11-07 11:59 UTC, MartinHjelmare requested changes

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/alarm_control_panel.lupusec.markdown
> +ha_release: 0.81
0.83

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/alarm_control_panel.lupusec.markdown
> +ha_iot_class: "Local Push"
This is a polling integration.

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/binary_sensor.lupusec.markdown
> +ha_release: 0.81
0.83

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/binary_sensor.lupusec.markdown
> +ha_iot_class: "Local Push"
See above.

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/binary_sensor.lupusec.markdown
> +For the switches to work you have to setup your [Lupusec component](/components/lupusec/).
It's confusing to call them switches. Switches in home assistant are actuator devices. The page is for binary sensors.

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/lupusec.markdown
> +ha_release: 0.81
0.83

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/lupusec.markdown
> +ha_iot_class: "Local Push"
See above.

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/lupusec.markdown
> +The `Lupusec` component allow the user to integrate their Lupusec alarm control panel and ultimately all connected sensors and other devices. For more information about the LUPUS-Electronics security
... allows the user...

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/lupusec.markdown
> +- [Switch](/components/switch.lupusec/): Reports on `Camera` devices and will download and show the latest captured still image.
There's no downloading or showing the latest image in home assistant?

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/lupusec.markdown
> +      username: YOUR_USERNAME
Use two space indentation.

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/lupusec.markdown
> +scan_interval:
This isn't configurable.

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/switch.lupusec.markdown
> +ha_release: 0.81
0.83

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/switch.lupusec.markdown
> +ha_iot_class: "Local Push"
See above.

2018-11-07 11:59 UTC, MartinHjelmare commented on source/_components/lupusec.markdown
> +scan_interval:
`name` config option is missing.

2018-11-07 18:28 UTC, majuss commented
I will work on it asap :) Thanks again @MartinHjelmare for the very helpful comments!

2018-11-08 09:23 UTC, MartinHjelmare approved these changes
Looks good! Can be merged when build passes.

2018-11-11 13:14 UTC, merged