Update Modbus component configuration variable
home-assistant/home-assistant.github.io pull request #6603
Opened 2018-10-08 11:02 UTC by klaasnicolaas

Update style of Modbus component (all the 4 files) documentation to follow new configuration variables description.
Related to #6385.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-08 11:33 UTC, klaasnicolaas commented
Error: Liquid Exception: (<unknown>): mapping values are not allowed in this context at line 3 column 69 in /opt/build/repo/source/_components/modbus.markdown

2018-10-08 17:10 UTC, WofWca commented on source/_components/binary_sensor.modbus.markdown
> +  type: map
List maybe? Or [map, list]? Idk.

2018-10-08 17:10 UTC, WofWca commented on source/_components/modbus.markdown
> +  description: Type of the connection to Modbus. Possible values are:
`:`

2018-10-10 16:17 UTC, WofWca commented on source/_components/sensor.modbus.markdown
> +      description: If data_type is custom specify here a double quoted python struct format string to unpack the value. See python documentation for details. Ex: ">i".
Here

2018-10-10 16:17 UTC, WofWca commented on source/_components/switch.modbus.markdown
> +      description: Modbus register type: holding or input.
And here.

2018-10-10 22:53 UTC, klaasnicolaas commented
if it is good, it can now be merged

2018-10-11 19:15 UTC, frenck requested changes
@klaasnicolaas Found 1 little thing. Could you take a look? 👍

2018-10-11 19:15 UTC, frenck commented on source/_components/modbus.markdown
> +  type: map
This is not a map or list. This is a string.

2018-10-11 19:38 UTC, frenck approved these changes

2018-10-11 19:39 UTC, frenck commented
Thanks, @klaasnicolaas!

Happy Hacktoberfest 🎉 

../Frenck

2018-10-11 19:39 UTC, merged