Add device registry to MQTT switch
home-assistant/home-assistant.github.io pull request #6607
Opened 2018-10-08 11:27 UTC by OttoWinter

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17244

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-08 16:37 UTC, DubhAd submitted a review, later dismissed

2018-10-08 16:37 UTC, DubhAd commented on source/_components/switch.mqtt.markdown
> +      description: 'A list of connections of the device to the outside world as a list of tuples `[connection_type, connection_identifier]`. For example the MAC address of a network interface: `[["ma
Can you make the same clarity update here please.

2018-10-08 18:55 UTC, frenck requested changes
@OttoWinter Left you some comments, could you take a look? 👍

2018-10-08 18:55 UTC, frenck commented on source/_components/switch.mqtt.markdown
> +      type: list, tuple
Same as the other PR, `tuple` is not a valid type for the documentation.

2018-10-08 18:55 UTC, frenck commented on source/_components/switch.mqtt.markdown
> +  description: 'Information about the device this switch is a part of to tie it into the [device registry](https://developers.home-assistant.io/docs/en/device_registry_index.html). Only works through
`Information about the device this switch` sounds/reads weird.
Adding comma's would probably help.

2018-10-10 18:22 UTC, frenck approved these changes

2018-10-10 18:22 UTC, merged