Update all device tracker configuration variables
home-assistant/home-assistant.github.io pull request #6635
Opened 2018-10-09 11:56 UTC by Mryck

**Description:**

Update of 25 device tracker configuration variables to follow the new standards  #6385

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-09 12:11 UTC, klaasnicolaas commented on source/_components/device_tracker.ubus.markdown
> +  default: `dnsmasq`
Leave the `` away or put it between "" like: "`dnsmasq`"

2018-10-09 12:11 UTC, klaasnicolaas commented on source/_components/device_tracker.upc_connect.markdown
> +  default: `192.168.0.1`
Same

2018-10-09 12:11 UTC, klaasnicolaas commented on source/_components/device_tracker.swisscom.markdown
> +  default: `192.168.1.1`
Same

2018-10-09 12:11 UTC, klaasnicolaas commented on source/_components/device_tracker.sky_hub.markdown
> +  default: `192.168.1.254`
Same

2018-10-09 12:11 UTC, klaasnicolaas commented on source/_components/device_tracker.owntracks.markdown
> +  default: `owntracks/#`
Same

2018-10-09 12:41 UTC, Mryck commented
Thanks @klaasnicolaas it should be fine now ! 👍

2018-10-09 18:07 UTC, frenck requested changes
Nice @Mryck!
I've found 2 little things, could you please take a look? 👍 

You really did a fine job btw. I love the way you even updated small details (Like `eg.` -> `e.g.,` and many others).

One other note though, this PR is kinda hitting the size limit 😉 
A couple of smaller PR's is usually easier to review/merge/process and reduces the risk of merge conflicts.

2018-10-09 18:07 UTC, frenck commented on source/_components/device_tracker.automatic.markdown
> +  type: boolean
Type `boolean` is missing `default`.

2018-10-09 18:07 UTC, frenck commented on source/_components/device_tracker.netgear.markdown
> +port:
Not really clear by the older docs and code, but the default here is actually `5000`.
Please add the `default` key.

2018-10-09 19:26 UTC, Mryck commented
Thanks @frenck for the review,  I agree about the size of the PR I will be carful, I made the change that you've requested 👍

2018-10-10 07:49 UTC, frenck approved these changes

2018-10-10 07:49 UTC, frenck commented
Thanks for updating @Mryck! 👍 

Happy Hacktoberfest 🎉 

../Frenck

2018-10-10 07:50 UTC, merged