Update OpenTherm Gateway docs to reflect the rewrite to a component.
home-assistant/home-assistant.github.io pull request #6637
Opened 2018-10-09 13:05 UTC by mvn23

**Description:**
OpenTherm Gateway has been rewritten to a component. This PR updates the docs accordingly

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17133

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-09 17:53 UTC, frenck requested changes
@mvn23 Thanks for the PR!
I've reviewed it and left you some comments. Could you please take a look? 👍

2018-10-09 17:53 UTC, frenck commented on source/_components/climate.opentherm_gw.markdown
> +date: 2018-10-09 11:23
Please do not update these dates.
The date indicates the initial introduction of the file.

2018-10-09 17:53 UTC, frenck commented on source/_components/opentherm_gw.markdown
> +ha_release: "0.80"
This is going to be `0.81`.

2018-10-09 17:53 UTC, frenck commented on source/_components/opentherm_gw.markdown
> +      type: boolean
Type `boolean` should have a default.

2018-10-09 17:53 UTC, frenck commented on source/_components/opentherm_gw.markdown
> +      description: "Some thermostats round all temperatures down to the lower value according to their precision. Default behaviour for Home Assistant is to round temperatures to the nearest value. S
Our docs are American English:
- `behaviour` -> `behavior`

2018-10-09 23:35 UTC, mvn23 commented
Thanks for the review, all requested changes have been made and your comments have been noted.

2018-10-10 10:18 UTC, frenck approved these changes

2018-10-10 10:18 UTC, frenck commented
Thanks for processing those @mvn23! 👍 

Happy Hacktoberfest 🎉 

../Frenck

2018-10-10 10:19 UTC, merged