Add csv.markdown
home-assistant/home-assistant.github.io pull request #6649
Opened 2018-10-09 20:05 UTC by siom79

**Description:**
Documentation for pull request [17296](https://github.com/home-assistant/home-assistant/pull/17296).

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17296

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-10 10:28 UTC, frenck requested changes
@siom79 Thanks for the PR!
I've reviewed it and left some comments. Could you please take a look? 👍

2018-10-10 10:28 UTC, frenck commented on source/_components/csv.markdown
> +  separator: ','
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-10-10 10:28 UTC, frenck commented on source/_components/csv.markdown
> +ha_release: 0.80
`0.80` has already been cut off, so this should be `0.81`.

2018-10-10 10:28 UTC, frenck commented on source/_components/csv.markdown
> +  type: boolean
A boolean always should have a `default: ` key.

2018-10-10 10:28 UTC, frenck commented on source/_components/csv.markdown
> +  description: Sets the number of old files to keep. Older files are removed. Default value is 10.
Default should be listed in a separate `default: ` key.

2018-10-10 10:28 UTC, frenck commented on source/_components/csv.markdown
> +  description: The separator between the values inside the CSV file. Default value is ','.
Default should be listed in a separate `default: ` key.

2018-10-12 12:43 UTC, siom79 commented
Closed because the parent PR has been closed.

2018-10-12 12:43 UTC, closed without merging