Added water heater doc and moved econet to water heater
home-assistant/home-assistant.github.io pull request #6676
Opened 2018-10-11 01:33 UTC by w1ll1am23

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-11 08:13 UTC, flowolf requested changes
rest LGTM. thanks!

2018-10-11 08:13 UTC, flowolf commented on source/_components/water_heater.econet.markdown
>  ---
this needs a redirect header. see docs: [Renaming Pages](https://developers.home-assistant.io/docs/en/documentation_standards.html#renaming-pages)

2018-10-11 19:56 UTC, frenck requested changes

2018-10-11 19:56 UTC, frenck commented on source/_components/water_heater.markdown
> +---
missing logo, release, category...
see other components for examples.

2018-10-11 19:56 UTC, frenck commented on source/_components/water_heater.markdown
> +Available services: `climate.set_temperature`, `climate.set_away_mode`, `climate.set_operation_mode`
These services changed, right? (`climate`)

2018-10-11 20:20 UTC, w1ll1am23 commented on source/_components/water_heater.markdown
> +---
You are looking at the base compoent, the econet water heater was copied from the econet climate. If you look at water_heater.econet.markdown it has the release, logo, and category.

2018-10-11 20:21 UTC, w1ll1am23 commented on source/_components/water_heater.markdown
> +Available services: `climate.set_temperature`, `climate.set_away_mode`, `climate.set_operation_mode`
correct, i'll fix that. Forgot to update those.

2018-10-11 20:22 UTC, w1ll1am23 commented on source/_components/water_heater.econet.markdown
>  ---
Thanks, I'll add that.

2018-10-11 20:37 UTC, frenck commented on source/_components/water_heater.markdown
> +---
👍

2018-10-11 20:37 UTC, frenck submitted a review, later dismissed

2018-10-13 21:37 UTC, fabaff approved these changes
Thanks :bird:

2018-10-13 21:37 UTC, merged