Added more details to introduction of component
home-assistant/home-assistant.github.io pull request #6678
Opened 2018-10-11 05:18 UTC by fortepc

Added more details specifically for the context of a user who may have never heard of Zillow or Zestimates to better understand what this sensor does.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-11 05:20 UTC, fortepc reviewed
Updated something I forgot to finishing updating.

2018-10-11 05:22 UTC, fortepc commented
Also, the image embedded is linked to an imgur link, not sure how to get that image hosted inside of github for proper embedding, or if I even have the necessary permissions to do so.

2018-10-11 13:28 UTC, fabaff commented
Images can't be uploaded with the GitHub editor.

2018-10-11 18:22 UTC, fortepc commented
So is having them posted on imager temporarily the right thing to do then?

2018-10-11 18:27 UTC, frenck commented
@fortepc No, you should add them to this PR.

2018-10-12 02:34 UTC, fortepc commented
I don't know how to do that...

2018-10-13 15:22 UTC, frenck commented
@fortepc Browse to:

https://github.com/fortepc/home-assistant.github.io/tree/patch-5

Browse to the location where you want to upload a file and hit the "Upload files" button.
![image](https://user-images.githubusercontent.com/195327/46907022-8dc73500-cf0c-11e8-96f5-3a58420990f3.png)

2018-10-16 21:06 UTC, fortepc commented
Okay... I think I got it @frenck

2018-10-18 19:18 UTC, frenck requested changes

2018-10-18 19:18 UTC, frenck commented on source/_components/sensor.zestimate.markdown
> +![image](home-assistant.github.io/source/images/components/zestimate/zestimateexample.png)
The image inclusion is still invalid. See:

<https://deploy-preview-6678--home-assistant-docs.netlify.com/components/sensor.zestimate/>

An example from the docs on how:
<https://raw.githubusercontent.com/home-assistant/home-assistant.io/next/source/_docs/installation.markdown>

2018-10-19 16:37 UTC, fortepc reviewed
Okay.. so used the html instead of markdown img embed, and also switched to relative paths instead of direct link to match the example provided above.

2018-10-21 09:48 UTC, frenck approved these changes

2018-10-21 09:49 UTC, frenck commented
Thanks for all the effort @fortepc!

✅ Approved 🎉 

Happy Hacktoberfest 🎉

2018-10-21 09:59 UTC, merged