Update configuration description for binary_sensor.tcp
home-assistant/home-assistant.github.io pull request #6704
Opened 2018-10-11 23:25 UTC by tmcarr

**Description:**

Updating configs for binary_sensor.tcp based on https://github.com/home-assistant/home-assistant.io/issues/6385

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-12 08:17 UTC, ludeeus requested changes

2018-10-12 08:17 UTC, ludeeus commented on source/_components/binary_sensor.tcp.markdown
> +    required: true
This is not a required option.

2018-10-12 08:17 UTC, ludeeus commented on source/_components/binary_sensor.tcp.markdown
> +    required: true
This is not a required option.

2018-10-12 08:17 UTC, ludeeus commented on source/_components/binary_sensor.tcp.markdown
> +    required: true
This is not a required option.

2018-10-12 18:31 UTC, tmcarr commented
@ludeeus Sorry about that, fixed.

2018-10-13 11:08 UTC, frenck approved these changes

2018-10-13 11:09 UTC, frenck commented
Thanks @tmcarr 👍 

Happy Hacktoberfest 🎉 

../Frenck

2018-10-13 11:09 UTC, merged