Add documentation for new zwave_lock configuration option
home-assistant/home-assistant.github.io pull request #6736
Opened 2018-10-13 01:55 UTC by mtreinish

**Description:**
This commit adds documentation around setting the new
use_notification_state configuration option being added to
home-assistant in home-assistant/home-assistant#17386

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17386
## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-17 01:10 UTC, tjorim commented on source/_components/lock.zwave.markdown
> +{% configuration %}
This doesn't look like a [configuration variable section](https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration).

I think you wanted to use
 ```yaml
zwave:
  device_config:
    lock.my_lock:
      use_notification_state: true
 ```

2018-10-18 19:12 UTC, frenck requested changes
Hi there, @mtreinish! Thank you for the PR.
I and @tjorim left some comments. Could you please take a look? 👍

2018-10-18 19:12 UTC, frenck commented on source/_components/lock.zwave.markdown
> +If your lock does not update the status properly for all events but the notification gets updated to show the state change you may need to set the
```suggestion
If your lock does not update the status properly for all events, but the notification gets updated to show the state change you may need to set the
```

2018-10-19 15:43 UTC, mtreinish commented
@frenck I've updated the PR per the suggestions. Sorry for the delay

2018-10-21 09:44 UTC, frenck approved these changes

2018-10-21 09:45 UTC, frenck commented
✅ Approved. Can be merged as soon as the parent PR gets merged.

2018-11-04 13:33 UTC, mtreinish commented
No longer using a config option in the parent PR, so the documentation doesn't need to be updated anymore.

2018-11-04 13:33 UTC, closed without merging