Update sensor.imap.markdown
home-assistant/home-assistant.github.io pull request #6775
Opened 2018-10-13 22:40 UTC by noxhirsch

Update IMAP Sensor configuration variable

2018-10-13 22:47 UTC, klaasnicolaas requested changes

2018-10-13 22:47 UTC, klaasnicolaas commented on source/_components/sensor.imap.markdown
> +port:
It has a default port: 993

2018-10-13 22:47 UTC, klaasnicolaas commented on source/_components/sensor.imap.markdown
> +folder:
default: inbox

2018-10-13 22:53 UTC, klaasnicolaas approved these changes

2018-10-13 22:53 UTC, noxhirsch commented on source/_components/sensor.imap.markdown
> +port:
Thank you! Added 👍

2018-10-13 22:53 UTC, noxhirsch commented on source/_components/sensor.imap.markdown
> +folder:
Thank you! Added 👍

2018-10-14 07:11 UTC, frenck approved these changes

2018-10-14 07:12 UTC, frenck commented
Thanks, @noxhirsch!

Happy Hacktoberfest 🎉 

../Frenck

2018-10-14 07:12 UTC, merged