Update IMAP Email Content Sensor configuration variable
home-assistant/home-assistant.github.io pull request #6777
Opened 2018-10-13 22:50 UTC by noxhirsch

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-13 22:54 UTC, klaasnicolaas approved these changes

2018-10-13 23:59 UTC, klaasnicolaas requested changes

2018-10-13 23:59 UTC, klaasnicolaas commented on source/_components/sensor.imap_email_content.markdown
> +  description: If specified this template will be used to render the state of the sensor. If a template is not supplied the message subject will be used for the sensor value. The following attributes
Put this between ""

2018-10-14 07:24 UTC, frenck approved these changes

2018-10-14 07:25 UTC, frenck commented
Thanks, @noxhirsch!

Happy Hacktoberfest 🎉 

../Frenck

2018-10-14 07:25 UTC, merged