Create sensor.rtorrent.markdown
home-assistant/home-assistant.github.io pull request #6780
Opened 2018-10-14 04:20 UTC by terorie

**Description:**
Description for my new rtorrent sensor

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#17421

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-14 07:21 UTC, frenck requested changes
Thanks for you PR @terorie!
I've reviewed it and left you some comments. Could you please take a look? 👍

2018-10-14 07:21 UTC, frenck commented on source/_components/sensor.rtorrent.markdown
> +---
`logo` is missing.

2018-10-14 07:21 UTC, frenck commented on source/_components/sensor.rtorrent.markdown
> +
Remove additional empty line.

2018-10-14 07:21 UTC, frenck commented on source/_components/sensor.rtorrent.markdown
> +
Remove additional empty line.

2018-10-14 07:21 UTC, frenck commented on source/_components/sensor.rtorrent.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-10-14 13:08 UTC, terorie commented
@frenck Just added the configuration tags and updated the description a bit.
I also set `ha_release` to `0.80`. I hope this is correct.

Thanks for taking a look 👍

2018-10-14 16:33 UTC, frenck submitted a review, later dismissed

2018-10-14 16:35 UTC, frenck commented
Thanks, @terorie!
0.80 is not correct since it has been shipped already.
Nevertheless, even when updating to 0.81, the question remains if it ships in that version (it might as well be the version after that.).

✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2018-10-17 01:00 UTC, tjorim requested changes
Thanks for your first-time PR here!
Maybe I'm just nitpicking but please put the `description` above `required` in the configuration-section.

2018-10-18 19:03 UTC, terorie commented
@tjorim Okay, I did so. Btw, I was using https://github.com/home-assistant/home-assistant.io/blob/next/source/_components/sensor.deluge.markdown as guidance, so maybe it should be updated there too then?

2018-10-18 19:13 UTC, frenck commented
@terorie All documentation is currently updated to the new format. Since we have a couple of pages, this takes some time.

2018-10-18 19:14 UTC, frenck submitted a review, later dismissed

2018-10-21 18:24 UTC, MartinHjelmare commented on source/_components/sensor.rtorrent.markdown
> +ha_release: 0.80
0.81

2018-10-21 18:24 UTC, MartinHjelmare commented on source/_components/sensor.rtorrent.markdown
> +The `rtorrent` platform allows you to monitor your downloads with [rtorrent](https://rakshasa.github.io/rtorrent/) from within Home Assistant and setup automation based on the information.
... and set up automations based on the information.

2018-10-21 18:24 UTC, MartinHjelmare commented on source/_components/sensor.rtorrent.markdown
> +Alternatively, the [arch-rtorrentvpn](https://github.com/binhex/arch-rtorrentvpn) container can be used with `url ` set to `http://admin:rutorrent@127.0.0.1:9080/RPC2`.
`url ` -> `url`

2018-10-21 18:24 UTC, MartinHjelmare commented on source/_components/sensor.rtorrent.markdown
> +  description: The name to user when displaying this rtorrent instance.
The name to use...

2018-10-21 18:24 UTC, MartinHjelmare commented on source/_components/sensor.rtorrent.markdown
> +  description: Conditions to display in the frontend.
These doesn't have anything to do with the frontend per se. These decide what conditions should be tracked as entity states.

2018-10-23 17:15 UTC, frenck approved these changes

2018-10-23 17:16 UTC, merged