Added documentation for MelCloud components.
home-assistant/home-assistant.github.io pull request #6798
Opened 2018-10-14 13:09 UTC by o0Zz

**Description:**
Add documentation for melcloud component

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant/pull/17338):** https://github.com/home-assistant/home-assistant/pull/17338

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-14 16:32 UTC, frenck requested changes

2018-10-14 16:32 UTC, frenck commented on source/_components/climate.melcloud.markdown
> +	password: yourpassword
- There is a <TAB> character in here.
- Please use `YOUR_PASSWORD` as per documentation standards.

2018-10-14 16:32 UTC, frenck commented on source/_components/climate.melcloud.markdown
> +
Remove extra empty line.

2018-10-14 18:21 UTC, o0Zz commented
@Frenck, everthing should be resolved.

2018-10-14 19:05 UTC, Danielhiversen requested changes

2018-10-14 19:05 UTC, Danielhiversen commented on source/_components/climate.melcloud.markdown
> +login:
This called email in the code

2018-10-14 19:05 UTC, Danielhiversen commented on source/_components/climate.melcloud.markdown
> +
`language` and `lease_time` are missing

2018-10-14 19:05 UTC, Danielhiversen commented on source/_components/climate.melcloud.markdown
> +    login: YOUR@EMAIL.COM
This called email in the code

2018-10-14 19:13 UTC, Danielhiversen commented on source/_components/climate.melcloud.markdown
> +ha_iot_class: "Local Polling"
Is this not cloud polling?

2018-10-14 21:31 UTC, o0Zz commented on source/_components/climate.melcloud.markdown
> +
Language as been remove from code

2018-10-17 00:49 UTC, tjorim requested changes
Thanks for this docs PR! I left some small notes.

2018-10-17 00:49 UTC, tjorim commented on source/_components/climate.melcloud.markdown
> +  description: How long time the melcloud cache stay valid in seconds (Default: 60)
Add `default: 60` to `lease_time` [per the docs](https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration), the default value should not be put in the description.

2018-10-17 00:49 UTC, tjorim commented on source/_components/climate.melcloud.markdown
> +    lease_time: 60
Please omit this line. The example entry should only contain required values (and 60 is the default anyway).

2018-10-17 00:52 UTC, tjorim commented on source/_components/climate.melcloud.markdown
> +  description: How long time the melcloud cache stay valid in seconds (Default: 60)
Apparently this also made the deploy preview fail because of the space behind the colon.

2018-10-21 09:15 UTC, frenck commented
Parent PR has been closed, closing this PR as well.

2018-10-21 09:15 UTC, closed without merging