Added description for minimum/maximum
home-assistant/home-assistant.github.io pull request #6802
Opened 2018-10-14 16:03 UTC by spacemanspiff2007

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17440

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-14 16:28 UTC, frenck requested changes

2018-10-14 16:28 UTC, frenck commented on source/_components/counter.markdown
> +      default: None
If it has no default, please leave it out.

2018-10-14 16:28 UTC, frenck commented on source/_components/counter.markdown
> +      default: None
If it has no default, please leave it out.

2018-10-14 17:56 UTC, spacemanspiff2007 reviewed
removed default: None

2018-10-16 18:30 UTC, frenck submitted a review, later dismissed

2018-10-16 18:31 UTC, frenck commented
Thanks for updating the PR @spacemanspiff2007! 👍 

✅ Approved. Can be merged as soon as the parent PR gets merged.

2018-10-18 07:04 UTC, spacemanspiff2007 commented
Added a service which can change minimum, maximum and step

2018-10-18 17:44 UTC, frenck approved these changes

2018-12-24 22:16 UTC, closed without merging