Add message template support for alert component
home-assistant/home-assistant.github.io pull request #6859
Opened 2018-10-16 12:13 UTC by thoscut

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17516

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2018-10-28 08:54 UTC, DubhAd requested changes

2018-10-28 08:54 UTC, DubhAd commented on source/_components/alert.markdown
> +	message_template: "Plant {{ states.plant.plant_office }} needs help ({{ state_attr('plant.plant_office', 'problem') }})"
There's a tab here, please correct

2018-10-31 19:50 UTC, thoscut commented
@DubhAd I updated the commit, also made some more changes as I updated the component code as well.

2018-11-01 08:49 UTC, balloob approved these changes

2018-11-01 08:49 UTC, merged

2018-11-07 02:26 UTC, tjorim commented on source/_components/alert.markdown
> +    message: "Plant {{ states.plant.plant_office }} needs help ({{ state_attr('plant.plant_office', 'problem') }})"
Is this example missing the `{% raw %}` tags?