Update Envisalink component configuration
home-assistant/home-assistant.github.io pull request #6935
Opened 2018-10-18 19:00 UTC by klaasnicolaas

**Description:**
Update style of Envisalink component documentation to follow new configuration variables description.
Related to #6385.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-10-18 19:33 UTC, klaasnicolaas commented
Please help, do not see where the problem may be.

2018-10-18 20:00 UTC, DubhAd requested changes

2018-10-18 20:00 UTC, DubhAd commented on source/_components/envisalink.markdown
> +  description: "Both DSC and Honeywell boards support a "panic" alarm. This is used when the alarm_trigger service is called in Home Assistant. This determines which type of panic alarm to raise. Val
Remove the `:` after `are` (and dump the quotes here and elsewhere)

2018-10-18 20:26 UTC, DubhAd approved these changes

2018-10-18 20:28 UTC, DubhAd requested changes

2018-10-18 20:28 UTC, DubhAd commented on source/_components/envisalink.markdown
> +  description: This is an interval (measured in seconds) where the evl will dump out all zone statuses. This is required for Honeywell systems, which do not properly send zone closure events. DSC boa
Please exapand *evl*

2018-10-19 13:21 UTC, DubhAd approved these changes

2018-10-19 18:04 UTC, fabaff approved these changes
Thanks :bird:

2018-10-19 18:04 UTC, merged