Documentation for Météo France sensor
home-assistant/home-assistant.github.io pull request #6938
Opened 2018-10-18 20:02 UTC by victorcerutti

**Description:**
Météo France provides a convenient rain forecast that is pretty accurate.
This sensor gives the time to next rain forecasted.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-10-21 09:26 UTC, frenck requested changes
@victorcerutti Thanks for the PR! I've reviewed it and left you some comments.
Could you please take a look? 👍

2018-10-21 09:26 UTC, frenck commented on source/_components/sensor.meteofrance.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-10-21 09:26 UTC, frenck commented on source/_components/sensor.meteofrance.markdown
> +    name: Paris 1er
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-10-21 09:26 UTC, frenck commented on source/_components/sensor.meteofrance.markdown
> +If no rain is forecasted for the nex hour, value will be "No rain".
```suggestion
If no rain is forecasted for the next hour, the value will be "No rain".
```

2018-10-21 09:26 UTC, frenck commented on source/_components/sensor.meteofrance.markdown
> +Attributes also gives the forecast for the next hour in 5min intervals.
```suggestion
Attributes also give the forecast for the next hour in 5min intervals.
```

2018-10-23 18:34 UTC, victorcerutti commented
Thank you for the review.
I have work to do on the sensor and I might change some of the doc.
I take account of the changes requested and will update as soon as the work is done.

2018-10-25 20:20 UTC, frenck submitted a review, later dismissed

2018-10-25 20:21 UTC, frenck commented
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2018-10-29 22:26 UTC, fabaff approved these changes
Thanks :bird:

2018-11-01 08:11 UTC, merged