Homekit troubleshooting section
home-assistant/home-assistant.github.io pull request #6950
Opened 2018-10-19 00:02 UTC by cdce8p

**Description:**
Due to many new issues being opened about problems with the `HomeKit` component, I've added a `troubleshooting` section to the documentation.

I've included some small improvement to the `setup` section as well.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-10-19 17:16 UTC, DubhAd requested changes

2018-10-19 17:16 UTC, DubhAd commented on source/_components/homekit.markdown
> +**PIN doesn't appear as persistent status**<br>
Should be linkeable title

2018-10-19 17:16 UTC, DubhAd commented on source/_components/homekit.markdown
> +**`Home Assistant Bridge` doesn't appear in the Home App (for pairing)**<br>
Should be linkeable title

2018-10-19 17:16 UTC, DubhAd commented on source/_components/homekit.markdown
> +**Pairing hangs - zeroconf error**<br>
Should be linkeable title

2018-10-19 17:16 UTC, DubhAd commented on source/_components/homekit.markdown
> +**Pairing hangs - no error**<br>
Should be linkeable title

2018-10-19 17:16 UTC, DubhAd commented on source/_components/homekit.markdown
> +**Duplicate AID found when attempting to add accessory**<br>
Should be linkeable title

2018-10-19 17:16 UTC, DubhAd commented on source/_components/homekit.markdown
> +**Some of my devices don't show up - Z-Wave / Discovery**<br>
Should be linkeable title

2018-10-19 17:16 UTC, DubhAd commented on source/_components/homekit.markdown
> +**Accessory not responding - after restart or update**<br>
Should be linkeable title

2018-10-19 17:16 UTC, DubhAd commented on source/_components/homekit.markdown
> +**Accessory not responding - randomly**<br>
Should be linkeable title

2018-10-19 17:16 UTC, DubhAd commented on source/_components/homekit.markdown
> +**Accessories not responding / behaving unusual - Upgrade from `0.65.x`**<br>
Should be linkeable title

2018-10-19 18:54 UTC, cdce8p commented
@DubhAd Personally I think that it looked better inline (with strong and line break), then as a title, due to the bottom padding. However I agree that it might make sense to link to one specifically.

2018-10-20 09:25 UTC, DubhAd commented
It makes a huge difference when you're directing people to the relevant troubleshooting section, rather than just a header and then trying to describe which section to use.

2018-10-20 09:27 UTC, DubhAd approved these changes

2018-10-20 09:27 UTC, merged