Update Documentation for 'Volumio' Media Player Component Configuration
home-assistant/home-assistant.github.io pull request #7030
Opened 2018-10-23 07:43 UTC by vaidyasm

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-10-23 08:01 UTC, tjorim requested changes
Thanks for helping us out with this PR! I left some feedback.

2018-10-23 08:01 UTC, tjorim commented on source/_components/media_player.volumio.markdown
> +  description: IP address or hostname of the device
The IP [...].

2018-10-23 08:01 UTC, tjorim commented on source/_components/media_player.volumio.markdown
> +  description: Port number of Volumio service
The .

2018-10-23 08:01 UTC, tjorim commented on source/_components/media_player.volumio.markdown
> +  description: Name of the device
The name of the device.

2018-10-23 08:01 UTC, tjorim commented on source/_components/media_player.volumio.markdown
> +host:
Try to cross-check the documentation with the actual code.
In this case you can find the default values here: https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/media_player/volumio.py#L49
`default: Volumio`

2018-10-23 08:01 UTC, tjorim commented on source/_components/media_player.volumio.markdown
> +port:
Default value for host is localhost (https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/media_player/volumio.py#L32)

2018-10-23 08:01 UTC, tjorim commented on source/_components/media_player.volumio.markdown
> +{% endconfiguration %}
Same for port

2018-10-23 08:36 UTC, vaidyasm commented
@tjorim Thanks for your feedbacks. They have been incorporated. It helps to know source where the defaults were defined.

2018-10-23 11:37 UTC, frenck commented
Rebased this PR onto `current`.

2018-10-25 19:22 UTC, frenck approved these changes

2018-10-25 19:22 UTC, frenck commented
Thank you for this PR, @vaidyasm! 👍 

Happy Hacktoberfest 🎉

2018-10-25 19:22 UTC, merged