Add documentation for updated Fire TV component
home-assistant/home-assistant.github.io pull request #7062
Opened 2018-10-24 16:34 UTC by JeffLIrion

**Description:** Add documentation for native support + ADB authentication for Fire TV

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17767

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-10-24 18:22 UTC, rytilahti commented on source/_components/media_player.firetv.markdown
> +Once you've successfully connected to your Fire TV via the command `adb connect <ipaddress>`, the files `adbkey` and `adbkey.pub` will be created on your computer.  Copy these to your Home Assistant
The location of the adb keyfiles should be pointed out. In linux they are stored under `~/.android/` (at least in my case).

2018-10-25 20:05 UTC, frenck requested changes
@JeffLIrion Thanks for the PR, I've reviewed it and left some comments. 
Could you please take a look? 👍

2018-10-25 20:05 UTC, frenck commented on source/_components/media_player.firetv.markdown
> +Configuration variables:
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-10-25 20:05 UTC, frenck commented on source/_components/media_player.firetv.markdown
> +If you get a "Device authentication required, no keys available" error when trying to setup Fire TV, then you'll need to create an adbkey and add its path to your configuration.  Follow the instructi
```suggestion
If you get a "Device authentication required, no keys available" error when trying to set up Fire TV, then you'll need to create an adbkey and add its path to your configuration.  Follow the instructions on this page to connect to your Fire TV from your computer: [Connecting to Fire TV Through adb](https://developer.amazon.com/zh/docs/fire-tv/connecting-adb-to-device.html).  
```

2018-10-25 20:05 UTC, frenck commented on source/_components/media_player.firetv.markdown
> +If you receive the error message `Issue: Error while setting up platform firetv` in your log when trying to setup a Fire TV device with an ADB key, then there is probably an issue with your ADB key.
```suggestion
If you receive the error message `Issue: Error while setting up platform firetv` in your log when trying to set up a Fire TV device with an ADB key, then there is probably an issue with your ADB key.  Here are some possible causes.
```

2018-10-29 08:21 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2018-11-19 06:26 UTC, JeffLIrion commented
https://github.com/home-assistant/home-assistant/pull/17767 has been merged!

2018-11-19 11:45 UTC, frenck commented
Thanks, @JeffLIrion for letting us know!
Congrats on getting this merged. Great job btw! 🥇

2018-11-19 11:45 UTC, merged