Add 'run_test' configs to skip ffmpeg input test on startup
home-assistant/home-assistant.github.io pull request #7064
Opened 2018-10-24 18:33 UTC by jjlawren

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-10-25 20:01 UTC, frenck requested changes

2018-10-25 20:01 UTC, frenck commented on source/_components/binary_sensor.ffmpeg_motion.markdown
> +  default: True
```suggestion
  default: true
```

2018-10-25 20:01 UTC, frenck commented on source/_components/binary_sensor.ffmpeg_noise.markdown
> +  default: True
```suggestion
  default: true
```

2018-10-25 20:01 UTC, frenck commented on source/_components/camera.ffmpeg.markdown
> +  default: True
```suggestion
  default: true
```

2018-10-25 20:02 UTC, frenck commented
Really small change needed there @jjlawren!
Could you take a look? 👍

2018-10-25 20:45 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2018-10-30 02:38 UTC, jjlawren commented
Changed some functionality in the parent PR to address design concerns, updated docs to match.

2018-11-03 12:49 UTC, jjlawren commented
Closing in favor of #7342.

2018-11-03 12:49 UTC, closed without merging