Update rest_command.markdown configuration
home-assistant/home-assistant.github.io pull request #7122
Opened 2018-10-26 11:06 UTC by hmmbob

**Description:**
Update style of REST Command documentation to follow new configuration variables description.
Related to #6385

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** n/a

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-10-27 21:00 UTC, frenck requested changes
Thanks for the PR @hmmbob! I've left some comments, could you please take a look? 👍

2018-10-27 21:00 UTC, frenck commented on source/_components/rest_command.markdown
>  Configuration variables:
This header should be removed.

2018-10-27 21:00 UTC, frenck commented on source/_components/rest_command.markdown
> +name:
The properties below are maps of the device...

2018-10-27 21:12 UTC, hmmbob commented
Done.

2018-10-29 11:05 UTC, frenck approved these changes

2018-10-29 11:06 UTC, frenck commented
Thanks, @hmmbob!

Happy Hacktoberfest 🎉

2018-10-29 11:06 UTC, merged