W800rf32
home-assistant/home-assistant.github.io pull request #7187
Opened 2018-10-28 01:26 UTC by horga83

**Description:**
Initial add of documentation for w800rf32 component and binary_sensor and switch platform.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17897

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-10-28 13:33 UTC, klaasnicolaas requested changes

2018-10-28 13:33 UTC, klaasnicolaas commented on source/_components/binary_sensor.w800rf32.markdown
> +Configuration variables:
Please use the new format: [read more](https://developers.home-assistant.io/docs/en/documentation_create_page.html)

2018-10-28 13:33 UTC, klaasnicolaas commented on source/_components/w800rf32.markdown
> +Configuration variables:
Same

2018-10-28 13:33 UTC, klaasnicolaas commented on source/_components/binary_sensor.w800rf32.markdown
> +---
missing `ha_release` and `ha_iot_class`

2018-10-28 13:33 UTC, klaasnicolaas commented on source/_components/switch.w800rf32.markdown
> +---
Same

2018-10-28 13:33 UTC, klaasnicolaas commented on source/_components/w800rf32.markdown
> +---
Same

2018-10-29 12:01 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2018-10-29 12:01 UTC, closed without merging