documentation for the Minut Point
home-assistant/home-assistant.github.io pull request #7269
Opened 2018-10-30 13:18 UTC by fredrike

**Description:**

Added documentation for the Minut Point integration.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#17466

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-10-30 15:41 UTC, ludeeus reviewed
Added some suggestions for correcting some typos :)

2018-10-30 15:41 UTC, ludeeus commented on source/_components/point.markdown
> +The Point is just active occasionaly so the sensors are only updated every hour or so.
```suggestion
The Point is just active occasionally so the sensors are only updated every hour or so.
```

2018-10-30 15:41 UTC, ludeeus commented on source/_components/point.markdown
> +Just follow the integration dialogs and make sure that your Home Assistant instance is accessable from the web (to be able to recieve webhooks).
```suggestion
Just follow the integration dialogs and make sure that your Home Assistant instance is accessible from the web (to be able to receive webhooks).
```

2018-10-30 15:41 UTC, ludeeus commented on source/_components/binary_sensor.point.markdown
> +description: "Access your Minut Point Events as binary senros."
```suggestion
description: "Access your Minut Point Events as binary sensors."
```

2018-10-30 15:41 UTC, ludeeus commented on source/_components/binary_sensor.point.markdown
> +Each Point exposes the following Sensors:
```suggestion
Each Point exposes the following binary sensors:
```
Unsure about this one(?)

2018-10-30 15:41 UTC, ludeeus commented on source/_components/binary_sensor.point.markdown
> +ha_category: BinarySensor
```suggestion
ha_category: Binary Sensor
```

2018-10-30 15:41 UTC, ludeeus commented on source/_components/sensor.point.markdown
> +The Point is just active occasionaly so the sensors are only updated every hour or so.
```suggestion
The Point is just active occasionally so the sensors are only updated every hour or so.
```

2018-10-30 15:41 UTC, ludeeus commented on source/_components/sensor.point.markdown
> +Each Point exposes the following Sensors:
```suggestion
Each Point exposes the following sensors:
```
Unsure about this one(?)

2018-11-19 11:53 UTC, balloob commented
This PR needs to include on every page the release it was included.

2018-11-19 12:10 UTC, fredrike commented
> This PR needs to include on every page the release it was included.

What do you mean @balloob ?

2018-11-19 12:16 UTC, frenck requested changes
@fredrike I've left you a review as comments on the places where the release information was missing, as stated by balloob.

2018-11-19 12:16 UTC, frenck commented on source/_components/binary_sensor.point.markdown
> +ha_iot_class: "Cloud Push"
`ha_release` is missing.

2018-11-19 12:16 UTC, frenck commented on source/_components/point.markdown
> +---
`ha_release` is missing.

2018-11-19 12:16 UTC, frenck commented on source/_components/sensor.point.markdown
> +---
`ha_release` is missing.

2018-11-19 13:02 UTC, balloob commented
It's `ha_release`

2018-11-19 13:15 UTC, frenck requested changes
@fredrike Thank you for adding the `ha_release` tags 👍 

I've now done a general review and left you some comments. Could you please take a look?
Thanks already! 👍

2018-11-19 13:15 UTC, frenck commented on source/_components/point.markdown
> +Once Home Assistant is started, a configurator will pop up asking you to Authenticate your Point account via a link when you follow the link and have clicked on **Accept** you will be redirected to t
```suggestion
Once Home Assistant is started, a configurator will pop up asking you to Authenticate your Point account via a link when you follow the link and have clicked on **Accept** you will be redirected to the `callback url` and the Point integration will be automatically configured and you can go back to the original dialog and press **Submit**.
```

2018-11-19 13:15 UTC, frenck commented on source/_components/point.markdown
> +
Configuration options list is missing.

Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2018-11-19 19:39 UTC, fredrike commented
@frenck Thank you for your comments, I've updated accordingly.

2018-11-20 00:16 UTC, frenck approved these changes

2018-11-20 00:16 UTC, frenck commented
Thanks for updating @fredrike! 👍 

I'll go ahead and merge it in.

2018-11-20 00:16 UTC, merged