Adding Asuswrt component and sensor to Asuswrt
home-assistant/home-assistant.github.io pull request #7324
Opened 2018-11-01 21:49 UTC by kennedyshead

**Description:**
This is the documentation for the new Asuswrt component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17757

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-11-07 17:38 UTC, MartinHjelmare commented on source/_components/asuswrt.markdown
> +featured: false
This is the default.

2018-11-07 17:38 UTC, MartinHjelmare commented on source/_components/asuswrt.markdown
> +ha_release: 0.82
0.83

2018-11-07 17:38 UTC, MartinHjelmare commented on source/_components/asuswrt.markdown
> +  description: "The username of an user with administrative privileges, usually `admin`."
```suggestion
  description: "The username of a user with administrative privileges, usually `admin`."
```

2018-11-07 17:38 UTC, MartinHjelmare commented on source/_components/sensor.asuswrt.markdown
> +ha_release: 0.82
0.83

2018-11-07 17:38 UTC, MartinHjelmare commented on source/_components/sensor.asuswrt.markdown
> +The `melissa` platform allows you to get data from your [ASUSWRT](http://event.asus.com/2013/nw/ASUSWRT/) sensors from within Home Assistant.
This is not the melissa platform. :wink:

2018-11-07 17:52 UTC, MartinHjelmare commented on source/_components/sensor.melissa.markdown
> +layout: **page**
Probably revert this.

2018-11-07 17:55 UTC, kennedyshead commented on source/_components/sensor.melissa.markdown
> +layout: **page**
hmm i did not do this ://

2018-11-07 17:59 UTC, MartinHjelmare approved these changes
Looks good!

2018-11-07 18:02 UTC, MartinHjelmare commented on source/_components/sensor.asuswrt.markdown
> +ha_category: Environment
Is this correct or is it a leftover from the Melissa page?

2018-11-07 18:05 UTC, MartinHjelmare requested changes
Fix the category of the sensor and rename the title in the front matter of the device tracker page similar as the sensor page.

2018-11-08 18:50 UTC, MartinHjelmare commented on source/_components/device_tracker.asuswrt.markdown
>  title: "ASUSWRT"
Change the title to eg "Asuswrt Device Tracker".

2018-11-09 07:21 UTC, MartinHjelmare approved these changes

2018-11-09 07:22 UTC, merged