Update device_tracker.aruba.markdown
home-assistant/home-assistant.github.io pull request #7510
Opened 2018-11-15 02:08 UTC by JDW2018

**Description:**

This is an update to the Aruba device tracker to allow it to connect and interface with both IAP's and AP's. This allows devices to be tracked around the home depending on which access point they are connected

In the configuration the type option is optional to make sure this is not a breaking change. by selection AP it changes from the current IAP mode to AP mode

Home assistant PR Number #18475

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-01-21 20:47 UTC, frenck commented
Not stale, parent PR is still open.

2019-02-02 10:20 UTC, DubhAd requested changes

2019-02-02 10:20 UTC, DubhAd commented on source/_components/device_tracker.aruba.markdown
> +  description: type of device that you want to connect to.
_The type of device that you want to connect to_

However, what are the options? From the example above we can guess that `AP` is one

2019-02-08 11:32 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2019-02-08 11:32 UTC, closed without merging