added google home alarm documentation
home-assistant/home-assistant.github.io pull request #7590
Opened 2018-11-20 09:49 UTC by eliseomartelli

**Description:**
Added the Google Home Alarms sensor documentation.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#18586

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-11-20 15:16 UTC, dshokouhi commented
Asides from the minor issue, this looks good to me.

2018-11-20 15:18 UTC, dshokouhi requested changes
The description should be updated for the integration.

2018-11-20 15:18 UTC, dshokouhi commented on source/_components/sensor.google_home_alarm.markdown
> +description: "Instructions on how to integrate a BH1750 light sensor into Home Assistant."
May want to update the description as this is not a light sensor :)

2018-11-20 15:27 UTC, eliseomartelli commented on source/_components/sensor.google_home_alarm.markdown
> +description: "Instructions on how to integrate a BH1750 light sensor into Home Assistant."
took care of that 😎

2018-11-20 16:23 UTC, eliseomartelli commented on source/_components/sensor.google_home_alarm.markdown
> +description: "Instructions on how to integrate a BH1750 light sensor into Home Assistant."
Netlify preview ready :)

2018-11-21 11:33 UTC, frenck requested changes
Thanks for the PR @eliseomartelli!

I've reviewed it, and left some comments. Could you please take a look? 👍

2018-11-21 11:33 UTC, frenck commented on source/_components/sensor.google_home_alarm.markdown
> +    monitored_conditions:
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-11-21 11:33 UTC, frenck commented on source/_components/sensor.google_home_alarm.markdown
> +  type: map
```suggestion
  type: list
```

2018-11-21 11:50 UTC, eliseomartelli commented
@frenck I've fixed the configuration to reflect the code review from the component's pull request.

2018-11-21 18:31 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-01-21 19:31 UTC, frenck commented
Not stale, parent PR is still open.

2019-01-29 12:07 UTC, frenck commented
Re-open, parent PR is still there.

2019-01-31 23:02 UTC, eliseomartelli commented
Waiting https://github.com/home-assistant/home-assistant.io/pull/8346 to update accordingly.

2019-02-03 09:24 UTC, closed without merging