added qbittorrent sensor documentation
home-assistant/home-assistant.github.io pull request #7597
Opened 2018-11-21 18:53 UTC by eliseomartelli

**Description:**
Added the documentation of the qbittorrent sensor.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#18618

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-11-21 19:07 UTC, frenck requested changes
Thanks for creating a documentation PR @eliseomartelli!

I've reviewed it and left 2 suggestions.
Furthermore, for a nice presentation on our documentation website, it would be awesome if you'd include a logo for qBittorrent.

Could you take a look? 👍

2018-11-21 19:07 UTC, frenck commented on source/_components/sensor.qbittorrent.markdown
> +    username: "<your username>"
```suggestion
    username: YOUR_USERNAME
```

2018-11-21 19:07 UTC, frenck commented on source/_components/sensor.qbittorrent.markdown
> +    password: "<your password>"
```suggestion
    password: YOUR_PASSWORD
```

2018-11-21 20:58 UTC, eliseomartelli commented
Applied your suggestion and added the logo @frenck 👍

2018-11-24 12:25 UTC, frenck submitted a review, later dismissed

2018-11-24 12:25 UTC, frenck commented
Thanks for addressing that @eliseomartelli 👍 
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2018-11-29 18:22 UTC, fabaff approved these changes
Thanks :bird:

2018-11-29 19:39 UTC, merged