Add LG Netcast remote doc
home-assistant/home-assistant.github.io pull request #7646
Opened 2018-11-26 10:27 UTC by doudz

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#19889

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-12-26 14:47 UTC, frenck requested changes
Thanks, @doudz! I've reviewed your PR and left some comments. Could you please take a look? 👍

2018-12-26 14:47 UTC, frenck commented on source/_components/remote.lg_netcast.markdown
> +    name: tv_room
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-12-26 14:47 UTC, frenck commented on source/_components/remote.lg_netcast.markdown
> +  description: The IP address of the LG Smart TV, e.g., 192.168.0.20.
```suggestion
  description: The IP address of the LG Smart TV, e.g., `192.168.0.20`.
```

2018-12-26 14:47 UTC, frenck commented on source/_components/remote.lg_netcast.markdown
> +To get the access token for your TV configure the `lg_netcast` platform in Home Assistant without the `access_token`.
```suggestion
To get the access token for your TV, configure the `lg_netcast` platform in Home Assistant without the `access_token`.
```

2018-12-26 14:47 UTC, frenck commented on source/_components/remote.lg_netcast.markdown
> +After starting Home Assistant the TV will display the access token on screen.
```suggestion
After starting Home Assistant, the TV will display the access token on screen.
```

2018-12-26 14:47 UTC, frenck commented on source/_components/remote.lg_netcast.markdown
> +Turn off device.
```suggestion
Turn off the device.
```

2018-12-26 14:47 UTC, frenck commented on source/_components/remote.lg_netcast.markdown
> +
Extra unneeded empty line.
```suggestion
```

2018-12-26 14:47 UTC, frenck commented on source/_components/remote.lg_netcast.markdown
> +ha_release: "0.82.0"
```suggestion
ha_release: 0.85
```

2018-12-26 14:47 UTC, frenck commented on source/_components/remote.lg_netcast.markdown
> +date: 2016-11-05 17:00
Please update this date to the creation date.

2018-12-28 09:12 UTC, doudz commented
I think everything's ok now ?

2019-01-01 17:05 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-02-25 09:33 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2019-02-25 09:33 UTC, closed without merging