Added documentation for ROVA sensor
home-assistant/home-assistant.github.io pull request #7780
Opened 2018-12-08 21:10 UTC by GidoHakvoort

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#18868

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-12-08 22:31 UTC, gerard33 commented on source/_components/sensor.rova.markdown
> +  - platform: solaredge
```suggestion
  - platform: rova
```

2018-12-09 06:58 UTC, GidoHakvoort commented on source/_components/sensor.rova.markdown
> +  - platform: solaredge
Thanks, missed this during copy/paste from another pull request.

2018-12-30 13:28 UTC, frenck requested changes
Thanks for the PR @GidoHakvoort! I've reviewed it, and left you some comments.

2018-12-30 13:28 UTC, frenck commented on source/_components/sensor.rova.markdown
> +{% raw %}
There is no need for the raw escape here?

2018-12-30 13:28 UTC, frenck commented on source/_components/sensor.rova.markdown
> +    monitored_conditions:
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-12-30 13:28 UTC, frenck commented on source/_components/sensor.rova.markdown
> +{% raw %}
No need to raw escape here.

2018-12-30 13:28 UTC, frenck commented on source/_components/sensor.rova.markdown
> +[ROVA](https://rova.nl) is a waste collection company that operates in the center and east of the Netherlands. The `rova` platform uses an unofficial [ROVA](https://rova.nl) API to allow you to get y
```suggestion
[ROVA](https://rova.nl) is a waste collection company that operates in the center and east of the Netherlands. The `rova` platform uses an unofficial [ROVA](https://rova.nl) API to allow you to get your waste collection schedule and integrate this in your Home Assistant installation.
```

2018-12-30 13:28 UTC, frenck commented on source/_components/sensor.rova.markdown
> +ha_release:
Please provide a release number. Next release is recommended. 0.85 at the moment of writing this.

2018-12-30 18:20 UTC, GidoHakvoort commented
@frenck Nice, thanks for the reviews frenck (both doc and platform). I've updated the doc to resolve the issues.

2019-01-21 22:29 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-01-31 02:45 UTC, klaasnicolaas commented
I see that the parent PR has been merged. So time to do that with this PR also 😄 Thnx for the PR @GidoHakvoort 👍

2019-01-31 02:46 UTC, klaasnicolaas approved these changes

2019-01-31 02:48 UTC, merged