Initial documentation for twinkly platform and XLED discovery
home-assistant/home-assistant.github.io pull request #7789
Opened 2018-12-10 01:58 UTC by scrool

**Description:**
Provides initial documentation for twinkly platform and XLED discovery.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#19158

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-12-10 09:55 UTC, klaasnicolaas requested changes

2018-12-10 09:55 UTC, klaasnicolaas commented on source/_components/light.twinkly.markdown
> +
You missing this line

```suggestion
{% endconfiguration %}
```

2019-01-01 15:17 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-03-01 15:44 UTC, Golab commented
How is it going white the addon?

2019-04-30 21:25 UTC, closed without merging