Add additional documentation for new Jewish Calendar sensors
home-assistant/home-assistant.github.io pull request #7838
Opened 2018-12-14 05:13 UTC by arigilder

**Description:**
Add additional documentation for new Jewish Calendar sensors.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#19278

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-12-14 05:14 UTC, arigilder commented
@tsvi Here's the documentation PR accompanying the code.

2018-12-14 06:40 UTC, tsvi submitted a review, later dismissed

2018-12-19 06:57 UTC, tsvi submitted a review, later dismissed

2019-01-21 18:24 UTC, rohankapoorcom requested changes
A couple of changes here (details in the specific comments).

2019-01-21 18:24 UTC, rohankapoorcom commented on source/_components/sensor.jewish_calendar.markdown
> +  platform: jewish_calendar
Please put this back. Since it's likely that users have multiple `sensors` defined, the convention of each platform page is that it is formatted as a list.

2019-01-21 18:24 UTC, rohankapoorcom commented on source/_components/sensor.jewish_calendar.markdown
> +    issur_melacha_is_in_effect:
This is inconsistently named with the code: https://github.com/home-assistant/home-assistant/pull/19278/files#diff-dd470e9104d306598757e35e0e219137R40

2019-01-21 18:24 UTC, rohankapoorcom commented on source/_components/sensor.jewish_calendar.markdown
> +      description: A boolean sensor indicating if melacha is currently not permitted. The value is true when it is currently Shabbat or Yom Tov and false otherwise.
Boolean sensors should be part of the `binary_sensor` component not the `sensor` component.

2019-01-22 01:21 UTC, arigilder commented on source/_components/sensor.jewish_calendar.markdown
> +      description: A boolean sensor indicating if melacha is currently not permitted. The value is true when it is currently Shabbat or Yom Tov and false otherwise.
I can open an issue for this to figure out a refactor, but I'd like to at least get this in as is for now.

2019-01-22 02:31 UTC, rohankapoorcom approved these changes
Great, thanks!

2019-01-23 06:14 UTC, merged