add documentation for zengge-wifi
home-assistant/home-assistant.github.io pull request #7947
Opened 2018-12-25 16:34 UTC by autinerd

**Description:**
Add documentation for new platform 'zengge-wifi'

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-12-25 22:02 UTC, frenck requested changes
@autinerd Thanks for the PR. Left you 2 small comments. Could you take a look? 👍

2018-12-25 22:02 UTC, frenck commented on source/_components/light.zengge-wifi.markdown
> +        name: Living Room
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2018-12-25 22:02 UTC, frenck commented on source/_components/light.zengge-wifi.markdown
> +date: 2017-01-14 08:00
This date seems off...?

2018-12-26 15:39 UTC, autinerd commented
I have now changed the configuration scheme, so it's simpler. The date is also corrected.

2018-12-31 07:00 UTC, autinerd commented
In home-assistant/home-assistant#19568 it was found out that this platform already exists, so this can be closed as well.

2018-12-31 07:00 UTC, closed without merging