added documenation changes for alarm_control_panel.homekit_controller
home-assistant/home-assistant.github.io pull request #7965
Opened 2018-12-28 03:56 UTC by adrum

**Description:**

This adds the necessary documentation stating support for HomeKit security systems being exposed as alarm control panels through Home Assistant.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#19612

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-12-30 09:17 UTC, frenck submitted a review, later dismissed

2018-12-30 09:17 UTC, frenck commented
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-01-04 20:05 UTC, MartinHjelmare commented on source/_components/homekit_controller.markdown
> +- [Alarm Control Panel](/components/alarm_control_panel.homekit_controller/)
🔡

2019-01-04 20:33 UTC, MartinHjelmare approved these changes
Nice!

2019-01-04 20:35 UTC, MartinHjelmare requested changes
Sorry, I missed that we just cut the beta.

2019-01-04 20:35 UTC, MartinHjelmare commented on source/_components/alarm_control_panel.homekit_controller.markdown
> +ha_release: 0.85
We just cut 0.85 beta before the parent PR was merged, so this will go out in 0.86.

2019-01-04 20:38 UTC, MartinHjelmare approved these changes
Thanks!

2019-01-22 11:18 UTC, merged