Add press hold for send command
home-assistant/home-assistant.github.io pull request #7985
Opened 2018-12-29 23:07 UTC by ehendrix23

**Description:**

Documentation with example for the new hold_secs parameter within the send_command.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#19650

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-02-02 11:05 UTC, DubhAd submitted a review, later dismissed

2019-02-02 11:05 UTC, DubhAd commented on source/_components/remote.harmony.markdown
> +This file will be overwritten whenever the Harmony HUB has a new configuration, there is no need to restart HASS.
HASS -> Home Assistant

2019-02-02 11:05 UTC, DubhAd commented on source/_components/remote.harmony.markdown
> +
Stray blank line

2019-02-02 11:05 UTC, DubhAd commented on source/_components/remote.harmony.markdown
> +| `entity_id`            |      yes | Only act on a specific remote, else target all.
Not a doc point, but I believe Home Assistant is moving away from that, and requiring that `all` be used as the entity ID to target all devices.

2019-03-06 20:03 UTC, frenck requested changes
@ehendrix23 There are some review changes requested and there appears to be a merge conflict. Could you please take a look? 👍

2019-03-06 21:36 UTC, ehendrix23 commented
Updates done :-)

2019-03-11 18:52 UTC, frenck commented
Thanks, @ehendrix23 👍

2019-03-11 18:52 UTC, frenck approved these changes

2019-03-11 18:52 UTC, merged