Update light.mqtt.markdown
home-assistant/home-assistant.github.io pull request #8000
Opened 2018-12-31 02:07 UTC by dchesterton

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#19675

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2018-12-31 03:23 UTC, emontnemery commented on source/_components/light.mqtt.markdown
> +  description: "Defines a [template](/docs/configuration/templating/#processing-incoming-data) to compose message which will be sent to `color_temp_command_topic`. Available variables: `value`."
It's confusing to link to /docs/configuration/templating/#processing-incoming-data here, better just link to /docs/configuration/templating/
This should be fixed also for `rgb_command_template`
On the other hand, from color_temp_value_template, link to /docs/configuration/templating/#processing-incoming-data

2018-12-31 13:32 UTC, dchesterton commented on source/_components/light.mqtt.markdown
> +  description: "Defines a [template](/docs/configuration/templating/#processing-incoming-data) to compose message which will be sent to `color_temp_command_topic`. Available variables: `value`."
Thanks, I've updated the links

2018-12-31 13:51 UTC, emontnemery commented on source/_components/light.mqtt.markdown
> +  description: "Defines a [template](/docs/configuration/templating/#processing-incoming-data) to compose message which will be sent to `color_temp_command_topic`. Available variables: `value`."
I think you modified the link from rgb_value_templare, instead of rgb_command_template?

2018-12-31 14:02 UTC, frenck commented
@dchesterton, thank you for this PR!
The PR is against the wrong target base. It currently is targeted and based of the `current` branch. Since this PR has a code change pending, the documentation must go into the `next` branch, since it is depended on a future release of Home Assistant.

Please change the target branch to `next` and rebase the PR.

2018-12-31 14:02 UTC, frenck requested changes
Please rebase onto `next`.

2019-01-01 14:46 UTC, emontnemery submitted a review, later dismissed

2019-01-01 14:46 UTC, emontnemery commented on source/_components/light.mqtt.markdown
> +  description: "Defines a [template](/docs/configuration/templating/) to extract the RGB value."
This should still link to /docs/configuration/templating/#processing-incoming-data, change the link from `rgb_command_template instead`.

2019-01-01 21:03 UTC, dchesterton commented
Thanks for the feedback. I've fixed the links and rebased onto `next`.

2019-01-15 20:57 UTC, frenck approved these changes

2019-01-15 20:58 UTC, frenck commented
Thanks, @dchesterton!
👍

2019-01-15 20:58 UTC, merged