support of telnet communication with NAD receivers
home-assistant/home-assistant.github.io pull request #8010
Opened 2019-01-01 22:28 UTC by rymsha

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#19704
## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-01-02 09:36 UTC, frenck requested changes
Thanks for the PR @rymsha!
I've reviewed it and provided some suggestions. Could you please take a look? Thanks! 👍

2019-01-02 09:36 UTC, frenck commented on source/_components/media_player.nad.markdown
> +  required: false
```suggestion
  required: exclusive
```

2019-01-02 09:36 UTC, frenck commented on source/_components/media_player.nad.markdown
> +  required: false
```suggestion
  required: exclusive
```

2019-01-02 09:36 UTC, frenck commented on source/_components/media_player.nad.markdown
> +Either serial_port or host must be provided. If serial_port is provided RS-232 connection is established. If host is provided Telnet communication is established.
```suggestion
Either `serial_port` or `host` must be provided. If a `serial_port` is provided, an RS-232 connection is established. If a `host` is provided, Telnet communication is established.
```

2019-01-02 17:43 UTC, rymsha commented
Looks better. Thanks.

2019-01-11 01:23 UTC, balloob approved these changes

2019-01-11 01:23 UTC, merged