Co2Signal platform
home-assistant/home-assistant.github.io pull request #8037
Opened 2019-01-03 23:24 UTC by danielsjf

**Description:**
This is the documentation for the CO2Signal platform

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#19204

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-01-14 23:44 UTC, frenck requested changes
Thanks for the PR @danielsjf! I've left you some comments, could you please take a look? Thanks! 👍

2019-01-14 23:44 UTC, frenck commented on source/_components/sensor.co2signal.markdown
> +    latitude: YOUR_LATITUDE
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2019-01-14 23:44 UTC, frenck commented on source/_components/sensor.co2signal.markdown
> +A similar result can be achieved by using the country code. In that case, use the following lines in your `configuration.yaml` file:
Move additional example below the configuration variables table.

2019-01-14 23:44 UTC, frenck commented on source/_components/sensor.co2signal.markdown
> +    country_code: YOUR_COUNTRY_CODE
Move additional example below the configuration variables table.

2019-01-17 17:34 UTC, danielsjf commented
@frenck Thanks for reviewing. I have made the requested modifications. Could you check if they suit your requests?

2019-01-22 11:08 UTC, frenck submitted a review, later dismissed
Thanks for updating the PR @danielsjf! 👍 

✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-01-26 18:06 UTC, MartinHjelmare commented on source/_components/sensor.co2signal.markdown
> +ha_release: 0.85
0.87

2019-01-26 18:06 UTC, MartinHjelmare commented on source/_components/sensor.co2signal.markdown
> +  required: optional
false

2019-01-26 18:06 UTC, MartinHjelmare commented on source/_components/sensor.co2signal.markdown
> +  required: required
true

2019-01-26 18:06 UTC, MartinHjelmare commented on source/_components/sensor.co2signal.markdown
> +  required: optional
false

2019-01-26 18:06 UTC, MartinHjelmare commented on source/_components/sensor.co2signal.markdown
> +  required: optional
false

2019-01-26 18:06 UTC, MartinHjelmare commented on source/_components/sensor.co2signal.markdown
> +ha_category: Health
Is this health related? I thought it was more environmental.

2019-01-26 18:17 UTC, klaasnicolaas commented
If the suggestions are processed from @MartinHjelmare, then this PR can be merged.

2019-01-26 19:58 UTC, danielsjf commented
@MartinHjelmare @klaasnicolaas The final edits have been made

2019-01-26 20:42 UTC, klaasnicolaas approved these changes

2019-01-26 20:42 UTC, klaasnicolaas commented
@danielsjf Great work! Thnx for the PR! 🎉 👍

2019-01-26 20:43 UTC, MartinHjelmare approved these changes
Great!

2019-01-26 20:43 UTC, merged