Add support for fan speed to HomeKit
home-assistant/home-assistant.github.io pull request #8044
Opened 2019-01-04 14:22 UTC by nd-net

**Description:**
Adds support to `speed` in HomeKit fans via value mapping.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#19767

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-01-21 09:43 UTC, cdce8p requested changes
It seems that the rebase went wrong here.

2019-01-21 09:43 UTC, cdce8p commented on source/_components/homekit.markdown
> +| fan | Fan | All fans that support `speed` and `speed_list` through value mapping. (first entry of `speed_list` -> `0`; last entry of `speed_list` -> `100`; entry in between -> patching percentage)
`matching percentage`? Can you add a line, that the values need to be in ascending order?

2019-01-21 19:31 UTC, frenck commented
@nd-net Please rebase this PR onto the `next` branch.

2019-02-08 23:45 UTC, cdce8p commented
@nd-net Any update on this?

2019-02-08 23:46 UTC, klaasnicolaas commented
We can't merge this PR with all the unrelated commits.

2019-02-09 12:37 UTC, nd-net commented
Sorry, I was sick this week.

PR is now based on the next branch; the mapping between `speed_list` and HomeKit fan speed is more verbose and contains examples.

2019-02-09 18:11 UTC, cdce8p commented
@nd-net Hope you're feeling better now. FYI: When we do rebases, we usually do force pushes so that the git log stays clean.

2019-02-09 18:11 UTC, cdce8p approved these changes

2019-02-09 18:12 UTC, merged