Small changes to help fill a couple of small gaps.
home-assistant/home-assistant.github.io pull request #8111
Opened 2019-01-09 18:02 UTC by Bodge-IT

Stopped short of offering a full example such as Harmony Remote config.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-01-09 21:25 UTC, tjorim requested changes
Fix the typo (inclduing -> including) and remove the double whitespace (just put it on another line), you can simply apply the 'Suggested Changes'.

2019-01-09 21:25 UTC, tjorim commented on source/_docs/configuration/packages.markdown
> +See the documentation about [splitting the configuration](/docs/configuration/splitting_configuration/) for more information about `!include_dir_named` and other include statements that might be help
```suggestion
See the documentation about [splitting the configuration](/docs/configuration/splitting_configuration/) for more information about `!include_dir_named` and other include statements that might be helpful.
The benefit of this approach is to pull all configurations required to integrate a system, into one file, rather than across several.
```

2019-01-09 21:25 UTC, tjorim commented on source/_docs/configuration/packages.markdown
> +The package configuration can include: `switch`, `light`, `automation`, `groups`, or most other Home Assistant components inclduing hardware platforms.
```suggestion
The package configuration can include: `switch`, `light`, `automation`, `groups`, or most other Home Assistant components including hardware platforms.
```

2019-01-13 10:47 UTC, fabaff approved these changes
Thanks :bird:

2019-01-13 10:47 UTC, merged