Create binary_sensor.tod.markdown
home-assistant/home-assistant.github.io pull request #8172
Opened 2019-01-14 22:27 UTC by kstaniek

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#20068

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-01-14 22:49 UTC, frenck requested changes
Thanks for the PR @kstaniek, please take a look at other piece of documentation on how to build the documentation page.

2019-01-14 22:49 UTC, frenck commented on source/_components/binary_sensor.tod.markdown
> +The `tod` platform supports binary sensors which get their values by checking
Our whole documentation header is missing here, please be sure to check out developers documentation on how to add a new page (or simply look at some other example in this repository).

2019-01-14 22:49 UTC, frenck commented on source/_components/binary_sensor.tod.markdown
> +The time ranges can be provided as absolute local time, or
```suggestion
The time ranges can be provided as absolute local time or
```

2019-01-14 22:49 UTC, frenck commented on source/_components/binary_sensor.tod.markdown
> +using the `sunrise` or `sunset` keyword calcuated based on the sun position
```suggestion
using the `sunrise` or `sunset` keyword calculated based on the sun position
```

2019-01-14 22:49 UTC, frenck commented on source/_components/binary_sensor.tod.markdown
> +The major purpose of this sensor is to use simple time range definition instead of creating a complex
```suggestion
The primary purpose of this sensor is to use a simple time range definition instead of creating a complex
```

2019-01-14 22:49 UTC, frenck commented on source/_components/binary_sensor.tod.markdown
> +templates with references to `sun.sun` component attributes.
```suggestion
template with references to `sun.sun` component attributes.
```

2019-01-14 22:49 UTC, frenck commented on source/_components/binary_sensor.tod.markdown
> +  - plartform: tod
```suggestion
  - platform: tod
```

2019-01-14 22:49 UTC, frenck commented on source/_components/binary_sensor.tod.markdown
> +In above example the next day `sunrise` is calculated as a time range end.
```suggestion
In the above example, the next day `sunrise` is calculated as a time range end.
```

2019-01-14 22:49 UTC, frenck commented on source/_components/binary_sensor.tod.markdown
> +
```suggestion
```

2019-01-14 22:49 UTC, frenck commented on source/_components/binary_sensor.tod.markdown
> +
```suggestion
```

2019-01-14 22:49 UTC, frenck commented on source/_components/binary_sensor.tod.markdown
> +The `tod` platform supports binary sensors which get their values by checking
Nevermind, fixed already.

2019-01-14 22:50 UTC, frenck commented
Please use the configuration tags, for more information please see:
https://home-assistant.io/developers/documentation/create_page/#configuration

2019-01-14 22:54 UTC, kstaniek commented
@frenck Franck, I have already added the tags. I missed that point.

2019-01-14 23:03 UTC, frenck commented
Thanks, @kstaniek! 
That happened during my review, we crossed streams 😉

2019-01-22 11:26 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-02-15 11:40 UTC, fabaff approved these changes

2019-02-15 13:00 UTC, merged