Add documentation for Danfoss Air HRV.
home-assistant/home-assistant.github.io pull request #8180
Opened 2019-01-15 20:40 UTC by JonasPed

**Description:**
Add documentation for Danfoss Air HRV component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#20138

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-01-17 05:26 UTC, rohankapoorcom requested changes
Please also add pages for the platforms included with this component.

2019-01-17 05:26 UTC, rohankapoorcom commented on source/_components/danfoss_air.markdown
> +footer: true
Please add a logo. You can add it to `source/images/supported_brands`

2019-01-17 05:26 UTC, rohankapoorcom commented on source/_components/danfoss_air.markdown
> +ha_category: Hub
This category doesn't seem right. I think this would be better to be a in `climate` or `fan`.

2019-01-20 23:46 UTC, rohankapoorcom commented
Looking like this is almost set - just needs pages for the platforms that are created as well.

2019-01-21 21:03 UTC, JonasPed commented
I was actually a bit unsure if documentation was needed for the individual platform as no configuration for these is possible. I have updated PR with documentation for sensor and binary sensor platform.

2019-01-21 21:44 UTC, rohankapoorcom commented
I think the new platforms documentation should indicate what things it provides sensors for.

2019-01-22 05:51 UTC, JonasPed commented
I think making a list with the sensors will make sense. Should this go in to the platform pages or the component page? Looks like it is a bit of a mix in the existing documentation?

2019-01-22 06:25 UTC, rohankapoorcom commented
Platform pages makes more sense since there each platform exposes different sensors.

2019-01-22 19:32 UTC, JonasPed commented
Updated the platform pages with a short description of each sensor.

2019-01-22 20:54 UTC, rohankapoorcom approved these changes
This looks good to me. Thanks for working through it.

2019-01-23 16:58 UTC, merged

2019-01-23 17:00 UTC, rohankapoorcom commented
@cgarwood I think this needs a version change to 0.87

2019-01-23 19:04 UTC, cgarwood commented
Good catch. New PR to update version: #8249