Update config options for sensor.discogs
home-assistant/home-assistant.github.io pull request #8214
Opened 2019-01-19 10:41 UTC by thibmaek

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#19443

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-01-21 20:41 UTC, frenck requested changes

2019-01-21 20:41 UTC, frenck commented on source/_components/sensor.discogs.markdown
> +    monitored_conditions:
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2019-01-24 20:10 UTC, thibmaek commented
Just corrected the final change request.

2019-01-25 11:09 UTC, frenck approved these changes

2019-01-25 11:10 UTC, frenck commented
✅ Approved. Can be merged as soon as the parent PR gets merged.

2019-02-23 22:15 UTC, fabaff approved these changes

2019-02-23 22:15 UTC, merged