Owlet Component Documentation
home-assistant/home-assistant.github.io pull request #8217
Opened 2019-01-20 04:03 UTC by oblogic7

**Description:**
Add documentation for Owlet component

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#20258

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-01-21 00:00 UTC, rohankapoorcom commented on source/_components/binary_sensor.owlet.markdown
> +title: "Owlet"
Title should be different for each platform and the component.

2019-01-21 00:01 UTC, rohankapoorcom commented on source/_components/owlet.markdown
> +The Point component is the main component to integrate the [Minut Point](https://minut.se/). To connect Point, you will have to [sign up for a developer account](https://minut.com/community/developer
This and the next paragraph seem leftover from a copy/paste.

2019-01-21 15:54 UTC, rohankapoorcom reviewed
The logo is not working. See: https://deploy-preview-8217--home-assistant-docs.netlify.com/components/owlet/


I think you have to use a png, not an svg.

2019-01-21 16:01 UTC, oblogic7 commented
Looks like I didn't get the file into the supported_brands folder when I dropped it onto the project.  I've updated the file location.  I think SVG will work as there are others in the supported_brands folder.

2019-01-21 16:11 UTC, rohankapoorcom submitted a review, later dismissed
Looks good!

2019-01-21 19:25 UTC, frenck requested changes
Thanks for the PR @oblogic7, I've left some comments, could you please take a look? 👍

2019-01-21 19:25 UTC, frenck commented on source/_components/binary_sensor.owlet.markdown
> +replace the Owlet app nor should it be used for for life critical notifications.
```suggestion
replace the Owlet app nor should it be used for life-critical notifications.
```

2019-01-21 19:25 UTC, frenck commented on source/_components/binary_sensor.owlet.markdown
> +ha_qa_scale:
Please remove this, since there is no ha_qa_scale.

2019-01-21 19:25 UTC, frenck commented on source/_components/owlet.markdown
> +  name: CUSTOM_NAME
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2019-01-21 19:25 UTC, frenck commented on source/_components/owlet.markdown
> +ha_qa_scale:
Please remove the ha_qa_scale.

2019-01-21 19:25 UTC, frenck commented on source/_components/owlet.markdown
> +replace the Owlet app nor should it be used for for life critical notifications.
```suggestion
replace the Owlet app nor should it be used for life-critical notifications.
```

2019-01-21 19:25 UTC, frenck commented on source/_components/sensor.owlet.markdown
> +ha_qa_scale:
Please remove the ha_qa_scale

2019-01-21 19:25 UTC, frenck commented on source/_components/sensor.owlet.markdown
> +replace the Owlet app nor should it be used for for life critical notifications.
```suggestion
replace the Owlet app nor should it be used for life-critical notifications.
```

2019-01-21 19:35 UTC, oblogic7 commented
@frenck Requested changes are complete.

2019-01-22 11:03 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-02-16 09:17 UTC, MartinHjelmare commented on source/_components/binary_sensor.owlet.markdown
> +## {% linkable_title Configuration %}
Remove this section. It's not correct. The platform is only loaded via discovery from the component.

2019-02-16 09:17 UTC, MartinHjelmare commented on source/_components/binary_sensor.owlet.markdown
> +---
We can merge this page with the component page as platforms don't require any configuration.

2019-02-16 09:17 UTC, MartinHjelmare commented on source/_components/owlet.markdown
> +ha_release: "0.87"
0.89

2019-02-16 09:17 UTC, MartinHjelmare commented on source/_components/owlet.markdown
> +featured: true
Remove this.

2019-02-16 09:17 UTC, MartinHjelmare commented on source/_components/sensor.owlet.markdown
> +---
We can remove this page and merge content with component page.

2019-02-16 17:30 UTC, oblogic7 commented
@MartinHjelmare Something blew up this branch during rebase too.  I'm thinking something is wonky with my PyCharm git integration.  Created a new PR (#8608) from clean working branch.

2019-02-16 17:30 UTC, closed without merging