html5 notification VAPID support
home-assistant/home-assistant.github.io pull request #8279
Opened 2019-01-25 13:39 UTC by quazzie

**Description:**
Add info about VAPID.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#20415

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-01-27 20:10 UTC, frenck requested changes

2019-01-27 20:10 UTC, frenck commented on source/_components/notify.html5.markdown
> +    vapid_pub_key: YOUR_PUBLIC_KEY
Maybe we should provide an additional example?
We like to keep example cut & pasteable....

2019-01-28 08:49 UTC, quazzie commented
Maybe we should remove GCM as it deprecated and will stop working in april ?

2019-02-10 16:43 UTC, klaasnicolaas commented
Time to merge this PR?

2019-02-11 12:32 UTC, frenck approved these changes

2019-02-11 12:32 UTC, merged