Deprecate travel_mode option
home-assistant/home-assistant.github.io pull request #8320
Opened 2019-01-27 20:23 UTC by jarmovanlenthe

The logs state that travel_mode is deprecated and mode should be used.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-01-27 20:27 UTC, klaasnicolaas requested changes

2019-01-27 20:27 UTC, klaasnicolaas commented on source/_components/sensor.google_travel_time.markdown
> +  description: "You can choose between: `driving`, `walking`, `bicycling` or `transit`." This method is now deprecated, use `mode` under `options`.
```suggestion
  description: "You can choose between: `driving`, `walking`, `bicycling` or `transit`. This method is now deprecated, use `mode` under `options`."
```

Will fix the build error

2019-01-27 20:45 UTC, klaasnicolaas commented on source/_components/sensor.google_travel_time.markdown
> +  description: "You can choose between: `driving`, `walking`, `bicycling` or `transit`. This method is now deprecated, use `mode` under `options`."
Are you sure that it is deprecated? In [the code](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sensor/google_travel_time.py#L55) is see that it is still an optional variable

2019-01-27 20:48 UTC, jarmovanlenthe commented
I know, but the logs of home-assistant say that it is the case.

On Sun, 27 Jan 2019, 21:45 Klaas Schoute, <notifications@github.com> wrote:

> *@klaasnicolaas* commented on this pull request.
> ------------------------------
>
> In source/_components/sensor.google_travel_time.markdown
> <https://github.com/home-assistant/home-assistant.io/pull/8320#discussion_r251254443>
> :
>
> > @@ -54,7 +54,7 @@ name:
>    required: false
>    type: string
>  travel_mode:
> -  description: "You can choose between: `driving`, `walking`, `bicycling` or `transit`."
> +  description: "You can choose between: `driving`, `walking`, `bicycling` or `transit`. This method is now deprecated, use `mode` under `options`."
>
> Are you sure that it is deprecated? In the code
> <https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sensor/google_travel_time.py#L55>
> is see that it is still an optional variable
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/home-assistant/home-assistant.io/pull/8320#pullrequestreview-196844685>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAQnRbRLtx2eOIWSc_-MTrUWEXhw4RVsks5vHg_jgaJpZM4aU6xc>
> .
>

2019-01-31 12:52 UTC, klaasnicolaas approved these changes

2019-01-31 12:53 UTC, merged

2019-01-31 12:53 UTC, klaasnicolaas commented
Will merge it, thnx for the PR 👍