Clarify MDI version currently used by HA
home-assistant/home-assistant.github.io pull request #8415
Opened 2019-02-05 18:16 UTC by akasma74

HA is currently using [mdi 3.0.39](https://cdn.materialdesignicons.com/3.0.39/), which is not the current one.
As per https://github.com/home-assistant/home-assistant-polymer/issues/2684

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-02-05 19:30 UTC, klaasnicolaas commented
Tomorrow it will be upgraded to 3.3.92 😉 
https://rc--home-assistant-docs.netlify.com/blog/2019/01/30/release-87/

2019-02-06 15:10 UTC, fabaff requested changes
We shouldn't add releases numbers because this increases the amount of maintenance of the page significantly.

2019-02-06 15:16 UTC, fabaff commented
Link to https://github.com/home-assistant/home-assistant-polymer/blob/dev/package.json#L20 could be an option.

2019-02-06 15:17 UTC, akasma74 commented
> We shouldn't add releases numbers because this increases the amount of maintenance of the page significantly.

Then you need to come up with an alternative to it, otherwise a lot of people will spend hours trying to find out why that particular icon does not show up.

2019-02-07 09:36 UTC, akasma74 commented
> Link to https://github.com/home-assistant/home-assistant-polymer/blob/dev/package.json#L20 could be an option.

I can see only "@mdi/svg": "^3.0.39".
The problem is it does not reflect the current release state - for example, HA 0.87.0 uses a different version of MDI.
So the issue stands - we need a way to know the MDI version supported.
Any thoughts?

2019-02-13 16:40 UTC, frenck commented
@akasma74 Use the master branch instead of dev?
<https://github.com/home-assistant/home-assistant-polymer/blob/master/package.json#L20>

2019-02-13 18:09 UTC, akasma74 commented
I can see the same "@mdi/svg": "^3.0.39" when follow your link

2019-02-13 19:50 UTC, frenck commented
@akasma74 Yep, but at least it is not the dev branch, so more accurate...

2019-04-14 21:12 UTC, akasma74 commented
I still don't know the right link to use.
HA devs, any ideas?

2019-06-13 21:54 UTC, akasma74 commented
bump

2019-06-18 19:19 UTC, frenck commented
@akasma74 There is no way to link the code base (truth) to the documentation right now.
So whatever we list in here, will be outdated, probably, every release.

We could, however, say something like: `Please note, that new icons might not be available in Home Assistant yet.`

IMHO it is simple, honest and explanatory.

2019-06-18 20:54 UTC, frenck commented
Superseded by #9416.
Closing this PR.

2019-06-18 20:54 UTC, closed without merging

2019-06-19 10:16 UTC, akasma74 commented
> @akasma74 There is no way to link the code base (truth) to the documentation right now.

got it

> We could, however, say something like: `Please note, that new icons might not be available in Home Assistant yet.`

that will do to start with.
but I'm curious how exactly does the process of adding a new MDI icon to HA look?
what is involved?

maybe by thinking about it I can come up with more detailed sentence as there is no such thing as too much details, is it? ;)

2019-06-19 10:33 UTC, frenck commented
Well, for starters, yes, there is a thing called too much detail. There is a big difference between user and developer documentation.

The file linked before shows the version scope the MDI icon package is in at the Home Assistant repo right now. On release, the build script will fetch the latest version matching those version requirements. Sometimes the version is pinned, sometimes it isn't.