Adding Teletask Hub, Light and Switch
home-assistant/home-assistant.github.io pull request #8426
Opened 2019-02-06 19:51 UTC by Tiemooowh

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-02-06 20:12 UTC, klaasnicolaas requested changes
Could you include the switch and light page in your component page? We now work with a new format so that we do not create extra pages for the light, switch, sensor etc.

2019-02-06 20:12 UTC, klaasnicolaas commented on source/_components/teletask.markdown
> +ha_category: Hub
```suggestion
ha_category:
  - Hub
  - Light
  - Switch
```

2019-02-06 20:22 UTC, Tiemooowh commented on source/_components/teletask.markdown
> +ha_category: Hub
merged the pages into one single page

2019-02-06 20:28 UTC, Tiemooowh commented
Hi Klaas,

Adjusted the code as per your remarks 👍 

Br
T

2019-04-03 21:34 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2019-04-03 21:34 UTC, closed without merging