Remove config.yaml part
home-assistant/home-assistant.github.io pull request #8442
Opened 2019-02-07 23:52 UTC by gerard33

**Description:**
As part of PR home-assistant/home-assistant#20631 an entry in configuration.yaml is no longer necessary.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#20631

cc: @rohankapoorcom

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-02-08 06:01 UTC, rohankapoorcom requested changes

2019-02-08 06:01 UTC, rohankapoorcom commented on source/_components/geofency.md
> -mobile_beacons:
This optional part is still needed. We have no way to add mobile_beacons from the UI.

2019-02-13 15:52 UTC, frenck commented
Because it is no longer necessary, doesn't mean it is no longer working?
One could still use this.

2019-02-14 21:26 UTC, gerard33 commented
@frenck, I have made this PR based on this description by balloob in PR home-assistant/home-assistant#20631

> With a config entry, there can be no entry in configuration.yaml.

I will change the PR so the `mobile_beacons` part stays in.

2019-02-15 05:38 UTC, rohankapoorcom approved these changes

2019-02-15 05:39 UTC, merged

2019-02-15 05:39 UTC, rohankapoorcom commented
Thanks! :)

2019-02-15 08:51 UTC, frenck commented
👍 @gerard33