Adding docs for new component GOCR
home-assistant/home-assistant.github.io pull request #8450
Opened 2019-02-08 15:52 UTC by grea09

**Description:**

Documentation for a new component for GOCR. It allows user to extract text simply from an image and even use reinforcement learning to fit their needs and improve accuracy.

I don't know how to add the logo:

![logo](https://upload.wikimedia.org/wikipedia/fr/e/e5/Logo_Gocr.jpg)

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-02-08 20:14 UTC, klaasnicolaas requested changes

2019-02-08 20:14 UTC, klaasnicolaas commented on source/_components/image_processing.gocr.markdown
> +  description: Other arguments to use. Like `-m 2`, `-p database`, etc. See [`manpage`](https://linux.die.net/man/1/gocr).
```suggestion
  description: "Other arguments to use. Like `-m 2`, `-p database`, etc. See [`manpage`](https://linux.die.net/man/1/gocr)."
```

2019-02-08 20:14 UTC, klaasnicolaas commented on source/_components/image_processing.gocr.markdown
> +  description: `True` if you want the image to be inverted before recognition. The process works better if the text is black on white.
```suggestion
  description: "`True` if you want the image to be inverted before recognition. The process works better if the text is black on white."
```

2019-02-08 20:14 UTC, klaasnicolaas commented on source/_components/image_processing.gocr.markdown
> +  default: '_'
```suggestion
  default: "'_'"
```

2019-04-15 10:59 UTC, klaasnicolaas commented
Parent PR still open

2019-06-07 10:07 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2019-06-07 10:07 UTC, closed without merging