Change type of offset in utility_meter
home-assistant/home-assistant.github.io pull request #8459
Opened 2019-02-10 01:17 UTC by dgomes

**Description:**

Updates the type of **offset** from integer to **time** and provides an example of how to define a Time period (copy&paste from sensor.darksky)

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#20926

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-02-10 12:38 UTC, klaasnicolaas requested changes

2019-02-10 12:38 UTC, klaasnicolaas commented on source/_components/utility_meter.markdown
> +  description: Cycle reset occur at the beginning of the period (0 minutes, 0h00 hours, Monday, day 1, January). This option enables the offsetting of these beginnings. Supported formats: `offset: 'H
```suggestion
  description: "Cycle reset occur at the beginning of the period (0 minutes, 0h00 hours, Monday, day 1, January). This option enables the offsetting of these beginnings. Supported formats: `offset: 'HH:MM:SS'`, `offset: 'HH:MM'` and Time period dictionary (see example below)."
```

2019-02-10 14:10 UTC, dgomes commented
@klaasnicolaas tks!

2019-02-11 14:47 UTC, klaasnicolaas submitted a review, later dismissed

2019-02-28 14:36 UTC, cgarwood commented
@dgomes looks like there's a merge conflict with the file now, otherwise I think the backend and this PR are ready to merge. Guessing it will land in 0.90?

2019-02-28 14:52 UTC, dgomes commented
@cgarwood thanks for the heads up

Beta was already cut, don't think it qualifies as a bug fix to be fit in 0.89

2019-03-06 12:54 UTC, cgarwood approved these changes

2019-03-06 12:54 UTC, merged