Add documentation for Point alarm_control_panel
home-assistant/home-assistant.github.io pull request #8477
Opened 2019-02-11 09:47 UTC by fredrike

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#20972

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-02-11 13:56 UTC, klaasnicolaas requested changes

2019-02-11 13:56 UTC, klaasnicolaas commented on source/_components/point.markdown
>  ha_category: Hub
```suggestion
ha_category: 
  - Hub
  - Alarm
  - Binary Sensor
  - Sensor
```

You can merge all information from the `Alarm`, `Binary Sensor` and `Sensor` page and put it on the `Hub` page and then delete the pages.

2019-02-11 13:56 UTC, klaasnicolaas commented on source/_components/point.markdown
>  ---
```suggestion
redirect_from:
  - /components/binary_sensor.point/
  - /components/sensor.point/
---
```

2019-02-11 13:56 UTC, klaasnicolaas commented on source/_components/point.markdown
>  ---
Add also on this page then:
```suggestion
There is currently support for the following device types within Home Assistant:
  - Alarm
  - Binary Sensor
  - Sensor
```

2019-02-12 07:07 UTC, fredrike commented on source/_components/point.markdown
>  ---
Where should I place this text?

2019-02-12 12:16 UTC, klaasnicolaas requested changes

2019-02-12 12:16 UTC, klaasnicolaas commented on source/_components/point.markdown
> -date: 2018-11-19
Please revert this to: `2018-11-19`

2019-02-12 12:20 UTC, fredrike commented on source/_components/point.markdown
> +date: 2019-02-12
```suggestion
date: 2018-11-19
```

2019-02-12 12:23 UTC, klaasnicolaas submitted a review, later dismissed

2019-02-15 12:17 UTC, fredrike commented
@klaasnicolaas, the home-assistant/home-assistant#20972 have been merged now..

2019-02-15 13:41 UTC, klaasnicolaas approved these changes

2019-02-15 13:42 UTC, klaasnicolaas commented
✅ We can merge this PR, will be released in the 0.89 release.

2019-02-15 15:40 UTC, merged