Teleinfo doc
home-assistant/home-assistant.github.io pull request #8517
Opened 2019-02-12 19:02 UTC by guiguid

**Description:**
Signed-off-by: Nicolas Lamirault [nicolas.lamirault@gmail.com](mailto:nicolas.lamirault@gmail.com)
    * home-assistant/home-assistant.io#4382

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** [home-assistant/home-assistant#20936](https://github.com/home-assistant/home-assistant/pull/20936)

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-02-12 19:31 UTC, klaasnicolaas requested changes

2019-02-12 19:31 UTC, klaasnicolaas commented on source/_components/sensor.teleinfo.markdown
> +  name: "edf"
```suggestion
  name: "edf"
```
This is a optional variable, and in the first example config we want only required items.

2019-04-15 00:01 UTC, klaasnicolaas commented
Parent PR is still open

2019-05-06 20:01 UTC, frenck commented
Parent PR has been closed, closing this one as well.

2019-05-06 20:01 UTC, closed without merging