Add SmartHab documentation page
home-assistant/home-assistant.github.io pull request #8647
Opened 2019-02-19 20:37 UTC by outadoc

**Description:**
This PR adds documentation for the SmartHab integration support in Home Assistant.

SmartHab is a French company that provides a proprietary app-based home automation platform in some new buildings, including mine. You can learn a bit more on their website: http://smarthab.fr 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#21225

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-02-20 10:14 UTC, klaasnicolaas requested changes

2019-02-20 10:14 UTC, klaasnicolaas commented on source/_components/smarthab.markdown
> +  password: '123456'
```suggestion
  password: PASSWORD
```

2019-02-20 10:14 UTC, klaasnicolaas commented on source/_components/smarthab.markdown
> +  email: john.doe@example.com
```suggestion
  email: EMAIL_ADDRESS
```

2019-04-15 15:12 UTC, outadoc commented
Hi @klaasnicolaas, could you maybe take another look at the PRs? They should be complete now. Thanks :)

2019-04-15 16:13 UTC, klaasnicolaas requested changes

2019-04-15 16:13 UTC, klaasnicolaas commented on source/_components/smarthab.markdown
> +redirect_from:
Please remove this

2019-04-15 16:13 UTC, klaasnicolaas commented on source/_components/smarthab.markdown
> +ha_iot_class: "Cloud Polling"
```suggestion
ha_iot_class: Cloud Polling
```

2019-04-15 16:13 UTC, klaasnicolaas commented on source/_components/smarthab.markdown
> +ha_release: 0.89
```suggestion
ha_release: 0.92
```

2019-04-16 20:03 UTC, outadoc commented
@klaasnicolaas Thanks. Should be good now.

2019-04-16 20:31 UTC, klaasnicolaas submitted a review, later dismissed

2019-04-16 20:32 UTC, klaasnicolaas commented
Yep it is now waiting on the parent PR 😉

2019-05-14 21:01 UTC, klaasnicolaas approved these changes

2019-05-14 21:07 UTC, merged