Adding enigma2 docs
home-assistant/home-assistant.github.io pull request #8669
Opened 2019-02-21 17:01 UTC by fbradyirl

**Description:**
Adding enigma2 docs. (this is based on comments from a stale review here: #5984 ).

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#21271

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

2019-02-21 18:36 UTC, klaasnicolaas requested changes

2019-02-21 18:36 UTC, klaasnicolaas commented on source/_components/media_player.enigma2.markdown
> +    host: 192.168.1.12
```suggestion
    host: IP_ADDRESS
```

2019-02-27 21:56 UTC, fbradyirl commented
@klaasnicolaas are you happy with this PR?

2019-02-27 22:59 UTC, klaasnicolaas commented
I'm missing the `name` and `port` variable 😉

2019-02-28 10:27 UTC, closed without merging