Create sensor.tof
home-assistant/home-assistant.github.io pull request #8672
Opened 2019-02-21 20:19 UTC by josemotta

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-02-21 23:39 UTC, klaasnicolaas requested changes

2019-02-21 23:39 UTC, klaasnicolaas commented on source/_components/sensor.tof.markdown
> +ha_category: DIY
```suggestion
ha_category: 
  - DIY
  - Sensor
```

2019-02-22 06:52 UTC, klaasnicolaas submitted a review, later dismissed

2019-02-22 06:52 UTC, klaasnicolaas commented on source/_components/sensor.tof.markdown
> +ha_release: 0.87.1
```suggestion
ha_release: 0.89
```

2019-02-22 12:13 UTC, josemotta commented
Having some issues also at pull request at home assistant. Any help?

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant/pull/21230):** [home-assistant/home-assistant#21230](https://github.com/home-assistant/home-assistant/pull/21230)

2019-02-22 12:22 UTC, klaasnicolaas commented
Why closing this PR?

2019-02-22 12:24 UTC, josemotta commented
Sorry, wrong action. Please keep it! It´s my first time here I was trying to ask for help at code PR

2019-02-22 12:24 UTC, josemotta commented
reopening

2019-02-26 20:26 UTC, josemotta commented
There is a broken link at:

Source: tof/sensor.py

Actually is should be `sensor/tof.py`, isn´t? How to fix this?

2019-02-27 11:11 UTC, frenck commented
This is known and has to do with "[The Great Migration](https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html)".

The documentation code currently only looks at the "new" situation.

From the documentation perspective, there is currently nothing you can do about that.

2019-03-08 07:26 UTC, MartinHjelmare requested changes

2019-03-08 07:26 UTC, MartinHjelmare commented on source/_components/sensor.tof.markdown
> +ha_release: 0.89
"0.90"

Keep the quotes to keep the trailing zero.

2019-03-08 07:26 UTC, MartinHjelmare commented on source/_components/sensor.tof.markdown
> +ha_iot_class: "Local Push"
Local Polling

2019-03-08 12:47 UTC, MartinHjelmare submitted a review, later dismissed

2019-03-11 20:48 UTC, frenck submitted a review, later dismissed

2019-03-11 21:35 UTC, frenck approved these changes

2019-03-11 21:35 UTC, frenck commented
Thanks, @josemotta! 👍

2019-03-11 21:35 UTC, merged