Added documentation for the ELV PCA 301 smart emeter switch
home-assistant/home-assistant.github.io pull request #8717
Opened 2019-02-24 16:28 UTC by majuss

**Description:**
Adds the documentation for the ELV PCA 301 smart emeter switch running at 868 MHz.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-02-25 11:54 UTC, klaasnicolaas requested changes

2019-02-25 11:55 UTC, klaasnicolaas commented on source/_components/switch.pca.markdown
> +  description: The path to you serial tty. Get it via: `ls /dev/tty*`.
```suggestion
  description: "The path to you serial tty. Get it via: `ls /dev/tty*`."
```

2019-03-24 17:07 UTC, majuss commented
Had in typo in there, now it should work.

2019-03-24 17:28 UTC, klaasnicolaas requested changes

2019-03-24 17:28 UTC, klaasnicolaas commented on source/_components/switch.pca.markdown
> +ha_iot_class: "Local Polling"
```suggestion
ha_iot_class: Local Polling
```

2019-03-24 17:28 UTC, klaasnicolaas commented on source/_components/switch.pca.markdown
> +ha_release: "0.90"
```suggestion
ha_release: 0.91
```

2019-03-25 00:33 UTC, klaasnicolaas requested changes
After this changes, we can approve it 🎉

2019-03-25 00:33 UTC, klaasnicolaas commented on source/_components/switch.pca.markdown
> +{% configuration %}
I see that there is a config variable for `name`, you can add this here.

2019-03-25 00:33 UTC, klaasnicolaas commented on source/_components/switch.pca.markdown
> +
One whitespace to much 😉

2019-03-25 12:02 UTC, klaasnicolaas submitted a review, later dismissed
✅ Can be merged after parent PR got merged 👍

2019-06-20 11:55 UTC, frenck approved these changes

2019-06-20 12:42 UTC, merged

2019-06-20 12:42 UTC, frenck commented
Thanks, @majuss! 👍

2019-06-20 13:58 UTC, majuss commented
It's always a pleasure to work with you guys and to expand the supported platforms! :)

2019-06-28 07:58 UTC, majuss commented
Hm something is off, maybe some pca/elv mixup, I can't reach the documentation.

2019-06-28 08:03 UTC, klaasnicolaas commented
https://www.home-assistant.io/components/switch.pca/