Added conditional element documentation
home-assistant/home-assistant.github.io pull request #8795
Opened 2019-03-01 20:24 UTC by yosilevy

Will add an example later on.

PR:
https://github.com/home-assistant/home-assistant-polymer/pull/2865

2019-03-03 19:37 UTC, balloob commented on source/_lovelace/picture-elements.markdown
> +  required: false
Should be required ?

2019-03-04 03:19 UTC, yosilevy commented on source/_lovelace/picture-elements.markdown
> +  required: false
Yes. Bad copy/paste. Fixed

2019-03-04 10:22 UTC, frenck requested changes
This PR has a parent PR in our codebase, and therefore, has a dependency on the next release of Home Assistant. Please change the target branch of this PR to `next` and rebase the PR if needed.

Thanks 👍

2019-03-04 12:44 UTC, yosilevy commented
I'm really not sure how to do this. I committed these changes via the git GUI since they're minor. Is it possible to do what you asked via the GUI or should I pull the PR and do it again on the next branch?

2019-03-04 13:16 UTC, frenck commented
Rebased.

2019-03-04 17:00 UTC, merged