Add ClickSend "caller" option
home-assistant/home-assistant.github.io pull request #8831
Opened 2019-03-05 14:28 UTC by fabtesta

**Description:**
Added optional "caller" parameter to let ClickSend API call be more compliant with some cellular networks that do not allow incoming calls from the same recipient number.
If "caller" is not defined, then the recipient parameter value is used.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#20780

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-03-05 19:30 UTC, klaasnicolaas requested changes

2019-03-05 19:30 UTC, klaasnicolaas commented on source/_components/notify.clicksend_tts.markdown
> +    caller: PHONE_NO
You can remove this line, also the name variable. 
Only required items in the first example.

2019-03-25 01:42 UTC, klaasnicolaas approved these changes
✅ Can be merged when deploy is ready

2019-03-25 19:47 UTC, frenck approved these changes
Thanks, @fabtesta! 👍

2019-03-25 19:47 UTC, merged