Add documentation for stream component
home-assistant/home-assistant.github.io pull request #8838
Opened 2019-03-06 03:55 UTC by hunterjm

**Description:**
Documents the stream component and the new camera service.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#21473

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-03-11 02:09 UTC, klaasnicolaas submitted a review, later dismissed

2019-03-12 16:13 UTC, dshokouhi commented
@hunterjm I had just started testing this, currently looking to see if I have a supported camera.  

On my dev instance of HA I have things running on a raspberry pi. When attempting to start HA with `stream:` in my configuration I got the following error:

```
2019-03-12 08:49:59 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package av==6.1.2: Command "/home/pi/home-assistant/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-udfl2b3t/av/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ftn5zmh2/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/home-assistant/include/site/python3.6/av" failed with error code 1 in /tmp/pip-install-udfl2b3t/av/
2019-03-12 08:49:59 ERROR (MainThread) [homeassistant.requirements] Not initializing stream because could not install requirement av==6.1.2
2019-03-12 08:49:59 ERROR (MainThread) [homeassistant.setup] Setup failed for stream: Could not install all requirements.
```

After a little bit of googling the following commands allowed me to get past this error, so I think a note for manual install users would be helpful here:

```
sudo apt-get install -y python-dev pkg-config

sudo apt-get install -y libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
```

If you think its out of scope for this PR I will submit a change but I think it may be helpful to some users to get in the first release :)

2019-03-12 16:37 UTC, hunterjm commented
@dshokouhi - The pyAV package is also available pre-built on https://www.piwheels.org/, which Hassbian has as a default package source, I believe.  Maybe we can add a note to add that?  Can you try removing those packages and installing from piwheels?

2019-03-12 16:50 UTC, dshokouhi commented
@hunterjm it looks like wheels is not supported on python 3.6?  I have Python 3.6.7 on my raspberry pi.  I already had the default package source setup on my pi as I had just checked it from the link but it did not grab the packages.

```
Wheels provided support all Raspberry Pi models (Pi 3, Pi 2, Pi 1 and Pi Zero). Wheels are provided for Python 3.4 and 3.5. We plan to add support for Python 3.6, 3.7 and 2.7.
```

When I attempt remove the installed packages and try again I get the same error about it being unable to find the packages.  Below is part of the error when I try to manually install pyAV, when I grab the packages I linked above the install works fine.

```
    Could not find libavformat with pkg-config.
    Could not find libavcodec with pkg-config.
    Could not find libavdevice with pkg-config.
    Could not find libavutil with pkg-config.
    Could not find libavfilter with pkg-config.
    Could not find libswscale with pkg-config.
    Could not find libswresample with pkg-config.
```

I can provide the full error but don't want to spam this PR.

2019-03-12 16:54 UTC, hunterjm commented
Ok. Good to know that piwheels doesn’t support 3.6 and 3.7.

I think we can add a warning message in the docs, but upon release it should work out of the box in new hassbian installs, HASS.io, and the official docker image.

2019-03-12 16:59 UTC, dshokouhi commented
ok I will just add the note for manual installers who run into the error on how to fix it once this PR gets merged :)

2019-03-12 18:29 UTC, frenck requested changes

2019-03-12 18:29 UTC, frenck commented on source/_components/stream.markdown
> +ha_release: 0.90
```suggestion
ha_release: "0.90"
```

2019-03-12 18:29 UTC, frenck commented on source/_components/stream.markdown
> +ha_category: "Other"
```suggestion
ha_category: 
  - Other
```

2019-03-12 18:29 UTC, frenck commented on source/_components/stream.markdown
> +---
```suggestion
ha_iot_class: Local Push
ha_qa_scale: internal
---
```

2019-03-12 18:29 UTC, frenck commented on source/_components/camera.markdown
> +{% raw %}
Raw should not be needed here.
```suggestion
```

2019-03-12 18:29 UTC, frenck commented on source/_components/camera.markdown
> +{% endraw %}
```suggestion
```

2019-03-12 18:29 UTC, frenck commented on source/_components/camera.markdown
> +Play a live stream from a camera to selected media player(s).  Requires `stream` component to be set up.
Additional space.
```suggestion
Play a live stream from a camera to selected media player(s). Requires `stream` component to be set up.
```

2019-03-12 18:29 UTC, frenck commented on source/_components/stream.markdown
> +The Stream component provides a way to proxy live streams through Home Assistant.  The component currently only supports the HLS format.
A space to many...
```suggestion
The Stream component provides a way to proxy live streams through Home Assistant. The component currently only supports the HLS format.
```

2019-03-12 19:03 UTC, frenck submitted a review, later dismissed

2019-03-12 19:50 UTC, fabaff approved these changes

2019-03-12 19:57 UTC, dshokouhi reviewed
probably want to update this part

2019-03-12 19:57 UTC, dshokouhi commented on source/_components/stream.markdown
> +To enable the random binary sensor, add the following lines to your `configuration.yaml` file:
we have a random binary sensor here? :)

2019-03-12 19:58 UTC, merged

2019-03-12 19:58 UTC, fabaff commented on source/_components/stream.markdown
> +To enable the random binary sensor, add the following lines to your `configuration.yaml` file:
Thanks