Add Nordpool Sensor documentation
home-assistant/home-assistant.github.io pull request #8840
Opened 2019-03-06 08:11 UTC by MTrab

**Description:**
The Nordpool Elspot market is the market for electrical power in the Scandinavian and Baltic countries.
This sensor fetches the current price for electrical power and put it into a sensor.

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-03-06 08:12 UTC, MTrab commented
Erhm?! Why is my Repetier pull mixed in with this?
It's a completely different branch?!

2019-03-06 08:25 UTC, klaasnicolaas requested changes

2019-03-06 08:25 UTC, klaasnicolaas commented on source/_components/sensor.nordpool.markdown
> +ha_release: 0.88
```suggestion
ha_release: 0.90
```

2019-03-06 08:25 UTC, klaasnicolaas commented on source/_components/sensor.nordpool.markdown
> +      description: Your preferred currency. Valid currencies are: DKK, NOK, SEK, EUR (case-sensitive)
```suggestion
      description: "Your preferred currency. Valid currencies are: DKK, NOK, SEK, EUR (case-sensitive)"
```

2019-04-09 09:17 UTC, MTrab commented
Closing this - unfortunately Nordpool are requiring a 1900EUR yearly license pr. user for this, and are not willing to negotiate.

2019-04-09 09:17 UTC, closed without merging