Update homematicip_cloud.markdown
home-assistant/home-assistant.github.io pull request #8864
Opened 2019-03-08 12:45 UTC by saepfle

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-03-08 12:46 UTC, saepfle commented
Update of current documentation - please set status for "current"

2019-03-09 09:44 UTC, steckenpferd commented
There mods aproved from my site please continue

2019-03-09 21:21 UTC, steckenpferd submitted a review, later dismissed
Approved

2019-03-11 11:19 UTC, klaasnicolaas requested changes

2019-03-11 11:19 UTC, klaasnicolaas commented on source/_components/homematicip_cloud.markdown
> +* Shutter
```suggestion
* Cover
```

2019-03-17 10:54 UTC, klaasnicolaas submitted a review, later dismissed

2019-03-19 10:36 UTC, steckenpferd commented
When will it be live?

2019-03-20 23:40 UTC, klaasnicolaas commented
Only after the conflict has been resolved @steckenpferd

2019-03-24 04:43 UTC, saepfle commented
Not sure who can resolve the "conflict" - and don't see any - descriptions were corrected by me accoring this homepage: https://github.com/coreGreenberet/homematicip-rest-api

2019-03-24 05:02 UTC, saepfle commented
Sorry did not see the to does in the conflict - hopefully its ok now and documentation can finally be updated

2019-03-24 13:03 UTC, klaasnicolaas commented
After the deploy is ready, we can merge this 😉

2019-03-24 15:08 UTC, klaasnicolaas approved these changes

2019-03-24 15:08 UTC, klaasnicolaas commented
Thnx for the PR! 👍

2019-03-24 15:08 UTC, merged