added docs for reddit sort_by config
home-assistant/home-assistant.github.io pull request #8952
Opened 2019-03-15 16:49 UTC by ljmerza

**Description:**
Add docs for sort_by config on reddit sensor

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-03-16 14:15 UTC, klaasnicolaas submitted a review, later dismissed

2019-03-16 14:15 UTC, klaasnicolaas commented on source/_components/sensor.reddit.markdown
> +  sort_by: new
You can remove this line, only variables that are required in the **first** example config

2019-03-17 08:44 UTC, fabaff requested changes

2019-03-17 08:44 UTC, fabaff commented on source/_components/sensor.reddit.markdown
> +  type: string
`default: hot` is missing. It should not be part of the description.

2019-03-22 20:05 UTC, fabaff approved these changes

2019-03-22 20:06 UTC, merged