Proxmox VE integration docs
home-assistant/home-assistant.github.io pull request #8973
Opened 2019-03-18 12:37 UTC by erangaj

This is the documentation for the Proxmox VE component.

2019-03-20 10:24 UTC, klaasnicolaas requested changes
There are a lot of changes for you in the `example config` section. Only required variables in the first example, you can add a more advanced example with optional variables.

2019-03-20 10:24 UTC, klaasnicolaas commented on source/_components/proxmox.markdown
> +   host: 192.168.1.100
```suggestion
   host: IP_ADDRESS
```

2019-03-20 10:24 UTC, klaasnicolaas commented on source/_components/proxmox.markdown
> +   port: 8006
Please remove `line 38`

2019-03-20 10:24 UTC, klaasnicolaas commented on source/_components/proxmox.markdown
> +   verify_ssl: False
Please remove `line 39`

2019-03-20 10:24 UTC, klaasnicolaas commented on source/_components/proxmox.markdown
> +   username: user
```suggestion
   username: USERNAME
```

2019-03-20 10:24 UTC, klaasnicolaas commented on source/_components/proxmox.markdown
> +   password: mysupersecretpassword
```suggestion
   password: PASSWORD
```

2019-03-20 10:24 UTC, klaasnicolaas commented on source/_components/proxmox.markdown
> +   realm: pam
Please remove `line 42`

2019-03-20 10:24 UTC, klaasnicolaas commented on source/_components/proxmox.markdown
> +   nodes:
Please remove `line 43 - 45`

2019-03-20 10:24 UTC, klaasnicolaas commented on source/_components/proxmox.markdown
> +   vms:
Please remove `line 46 - 49`

2019-03-20 10:24 UTC, klaasnicolaas commented on source/_components/proxmox.markdown
> +   start_stop_all_vms: False
Please remove `line 50`

2019-03-20 10:24 UTC, klaasnicolaas commented on source/_components/proxmox.markdown
> +   start_stop_vms:
Please remove `line 51 - 53`

2019-03-20 20:46 UTC, erangaj commented on source/_components/proxmox.markdown
> +   port: 8006
Done. All the optional configs removed.

2019-03-20 20:46 UTC, erangaj commented on source/_components/proxmox.markdown
> +   verify_ssl: False
Done. All the optional configs removed.

2019-03-20 20:46 UTC, erangaj commented on source/_components/proxmox.markdown
> +   realm: pam
Done. All the optional configs removed.

2019-03-20 20:46 UTC, erangaj commented on source/_components/proxmox.markdown
> +   nodes:
Done. All the optional configs removed.

2019-03-20 20:46 UTC, erangaj commented on source/_components/proxmox.markdown
> +   vms:
Done. All the optional configs removed.

2019-03-20 20:47 UTC, erangaj commented on source/_components/proxmox.markdown
> +   start_stop_all_vms: False
Done. All the optional configs removed.

2019-03-20 20:47 UTC, erangaj commented on source/_components/proxmox.markdown
> +   start_stop_vms:
Done. All the optional configs removed.

2019-03-20 20:52 UTC, erangaj commented
Thank you. I have removed all the optional elements from the configuration.

2019-05-27 17:58 UTC, klaasnicolaas commented
Parent PR still open?

2019-07-04 11:49 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2019-07-04 11:49 UTC, closed without merging