Added documentation for Sector Alarm component
home-assistant/home-assistant.github.io pull request #9022
Opened 2019-03-24 20:42 UTC by peroyvind

**Description:**
Documentation for the new Sector Alarm component

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-03-25 00:22 UTC, klaasnicolaas requested changes

2019-03-25 00:22 UTC, klaasnicolaas commented on source/_components/sectoralarm.markdown
> +redirect_from:
You can remove line 15 - 17

2019-03-25 00:22 UTC, klaasnicolaas commented on source/_components/sectoralarm.markdown
> +{% configuration %}
Please remove the whitespaces between the variables.

2019-03-25 00:22 UTC, klaasnicolaas commented on source/_components/sectoralarm.markdown
> +  email: your@email.com
```suggestion
  email: EMAIL_ADDRESS
```

2019-03-25 00:22 UTC, klaasnicolaas commented on source/_components/sectoralarm.markdown
> +  password: Password
```suggestion
  password: PASSWORD
```

2019-03-25 00:22 UTC, klaasnicolaas commented on source/_components/sectoralarm.markdown
> +  code: 1234
```suggestion
  code: ALARM_CODE
```

2019-03-25 00:22 UTC, klaasnicolaas commented on source/_components/sectoralarm.markdown
> +  alarm_id: 012345678
```suggestion
  alarm_id: ALARM_ID
```

2019-03-25 15:32 UTC, klaasnicolaas approved these changes
✅ Can be merged after merging the parent PR 👍

2019-05-24 16:13 UTC, klaasnicolaas commented
Parent PR still open

2019-06-18 08:18 UTC, frenck commented
Closing PR, since the parent PR has been closed.

2019-06-18 08:18 UTC, closed without merging