Add AirBase zone switches
home-assistant/home-assistant.github.io pull request #9040
Opened 2019-03-26 14:19 UTC by fredrike

**Description:**

Add documentation for AirBase zone switches

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22417

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-03-26 18:25 UTC, klaasnicolaas requested changes

2019-03-26 18:25 UTC, klaasnicolaas commented on source/_components/daikin.markdown
> +  - /components/switch.daikin/
You can remove line 21

2019-03-26 18:50 UTC, fredrike commented on source/_components/daikin.markdown
> +  - /components/switch.daikin/
```suggestion
```

2019-03-26 18:54 UTC, klaasnicolaas approved these changes

2019-03-30 08:31 UTC, frenck commented
Thanks, @fredrike 👍

2019-03-30 08:31 UTC, merged