Create fortios.markdown
home-assistant/home-assistant.github.io pull request #9044
Opened 2019-03-26 17:55 UTC by kimfrellsen

this is documentation for the initial version of a new device_tracker component named Fortios from Fortinet.

**Description:**
the fortios device_tracker.py pull request is not created yet. But I'll make a PR during this week and documentation should be ready when the code is committed :)

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-06-18 19:45 UTC, frenck requested changes
@kimfrellsen I've reviewed your PR and left some comments. Could you please take a look? Thanks! 👍

2019-06-18 19:45 UTC, frenck commented on source/_components/device_tracker.fortios.markdown
> +
The documentation header is missing, please add it.

2019-06-18 19:45 UTC, frenck commented on source/_components/device_tracker.fortios.markdown
> +The component rely on fortiosapi: https://pypi.org/project/fortiosapi/
```suggestion
The component relies on the [fortiosapi](https://pypi.org/project/fortiosapi/).
```

2019-06-18 19:45 UTC, frenck commented on source/_components/device_tracker.fortios.markdown
> +All devices with a MAC address identified by FortiGate would be tracked, this covers both Ethernet and WiFi devices, incl. devices detected by LLDP.
```suggestion
All devices with a MAC address identified by FortiGate would be tracked, this covers both Ethernet and WiFi devices, including devices detected by LLDP.
```

2019-06-18 19:45 UTC, frenck commented on source/_components/device_tracker.fortios.markdown
> +    description: Hostname or IP address of the FortiGate
```suggestion
    description: Hostname or IP address of the FortiGate.
```

2019-06-18 19:45 UTC, frenck commented on source/_components/device_tracker.fortios.markdown
> +    host: 192.168.0.1
```suggestion
    host: YOUR_HOST
```

2019-06-18 19:45 UTC, frenck commented on source/_components/device_tracker.fortios.markdown
> +    verify_ssl: False
We try to keep all configuration samples minimal. Thus, no optional requirement in the default sample. This helps a user to get started quickly by copy-&-paste the sample without worrying about optional parameters which they most likely not need. If required, insert a full configuration sample later that covers special setups or alike.

2019-06-18 19:45 UTC, frenck commented on source/_components/device_tracker.fortios.markdown
> +    description: if the SSL certificate should be verified. In most home cases users do not have a verified certificate. Default=False.
```suggestion
    description: if the SSL certificate should be verified. In most home cases users do not have a verified certificate.
```

The default should not be in the description but added to the configuration list. Please add it.

2019-06-18 19:45 UTC, frenck commented on source/_components/device_tracker.fortios.markdown
> +    description: See [Fortinet Devloper Network](https://fndn.fortinet.com) for how to create a API token. Remember this component only needs read access to a FortiGate, so configure the API user to
```suggestion
    description: See [Fortinet Developer Network](https://fndn.fortinet.com) for how to create an API token. Remember this component only needs read access to a FortiGate, so configure the API user to only to have limited and read-only access.
```

2019-06-18 19:45 UTC, frenck commented on source/_components/device_tracker.fortios.markdown
> +{% endconfiguration %}
```suggestion
{% endconfiguration %}

```

2019-06-30 18:33 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-07-18 22:48 UTC, frenck submitted a review, later dismissed

2019-07-21 12:01 UTC, klaasnicolaas commented
Please rename the file from `device_tracker.fortios.markdown` to `fortios.markdown`

2019-07-21 19:56 UTC, frenck submitted a review, later dismissed

2019-07-23 23:21 UTC, MartinHjelmare commented on source/_components/fortios.markdown
> +ha_release: 0.96
0.97

2019-07-23 23:21 UTC, MartinHjelmare commented on source/_components/fortios.markdown
> +---
Please add `ha_iot_class`.

2019-07-23 23:41 UTC, frenck commented on source/_components/fortios.markdown
> +ha_release: 0.96
Done

2019-07-23 23:41 UTC, frenck commented on source/_components/fortios.markdown
> +---
Done

2019-07-23 23:42 UTC, frenck submitted a review, later dismissed

2019-07-23 23:43 UTC, MartinHjelmare submitted a review, later dismissed

2019-07-23 23:45 UTC, MartinHjelmare commented
Sorry for messing up the project status. 🙈

2019-07-23 23:45 UTC, frenck commented
@MartinHjelmare Don't worry about that! You doing great

2019-07-24 00:02 UTC, frenck approved these changes

2019-07-24 00:02 UTC, merged