Add docs for LCN climate platform
home-assistant/home-assistant.github.io pull request #9073
Opened 2019-03-29 18:53 UTC by alengwenus

**Description:**
Documentation is added for the LCN climate platform.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22542

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-03-29 19:09 UTC, klaasnicolaas requested changes

2019-03-29 19:09 UTC, klaasnicolaas commented on source/_components/lcn.markdown
> +      description: "Setpoint for target temperature ([VARIABLE](/components/lcn#variables-and-units), [SETPOINT](/components/lcn#variables-and-units))."
```suggestion
      description: "Setpoint for target temperature ([VARIABLE](#variables-and-units), [SETPOINT](#variables-and-units))."
```

2019-03-29 19:09 UTC, klaasnicolaas commented on source/_components/lcn.markdown
> +      description: "Measurement unit ([VAR_UNIT](/components/lcn#variables-and-units))."
```suggestion
      description: "Measurement unit ([VAR_UNIT](#variables-and-units))."
```

2019-03-29 19:09 UTC, klaasnicolaas commented on source/_components/lcn.markdown
> +      description: "Current temperature source ([VARIABLE](/components/lcn#variables-and-units))."
```suggestion
      description: "Current temperature source ([VARIABLE](#variables-and-units))."
```

2019-03-29 19:09 UTC, klaasnicolaas commented on source/_components/lcn.markdown
> +      description: "[Address](/components/lcn#lcn-addresses) of the module/group."
```suggestion
      description: "[Address](#lcn-addresses) of the module/group."
```

2019-03-29 19:09 UTC, klaasnicolaas commented on source/_components/lcn.markdown
> +If you intend to leave the regulation to home assistant, you should consider using the [Generic Thermostat](/components/climate.generic_thermostat) in conjuction with [LCN Sensor](/components/sensor.
```suggestion
If you intend to leave the regulation to home assistant, you should consider using the [Generic Thermostat](/components/climate.generic_thermostat) in conjuction with [LCN Sensor](#sensor) and [LCN Switch](#switch).
```

2019-05-11 08:28 UTC, MartinHjelmare approved these changes

2019-05-11 09:00 UTC, klaasnicolaas approved these changes

2019-05-14 19:10 UTC, merged