Create sensor.solax
home-assistant/home-assistant.github.io pull request #9082
Opened 2019-03-31 04:28 UTC by CountParadox

**Description:**

Initial adding of docs

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22579

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-03-31 07:43 UTC, frenck requested changes
Looks good @CountParadox! Some minor tweaks and the docs are done!

One additional note: Please rename the file from `sensor.solax.markdown` to `solax.markdown`.

👍

2019-03-31 07:43 UTC, frenck commented on source/_components/sensor.solax.markdown
> +The `solax` component connects home-assistant to Solax solar power inverters. Solax inverters may be connected to a home Wi-Fi network and expose a REST api. This component retrieves information such
```suggestion
The `solax` component connects home-assistant to Solax solar power inverters. Solax inverters may be connected to a home Wi-Fi network and expose a REST API. This component retrieves information such as photovoltaic power production, battery levels and power, and how much power is being fed back into the grid.
```

2019-03-31 07:43 UTC, frenck commented on source/_components/sensor.solax.markdown
> +{% raw %}
No need for raw here
```suggestion
```

2019-03-31 07:43 UTC, frenck commented on source/_components/sensor.solax.markdown
> +{% endraw %}
```suggestion

```

2019-03-31 07:43 UTC, frenck commented on source/_components/sensor.solax.markdown
> +
Unneeded empty line
```suggestion
```

2019-03-31 07:43 UTC, frenck commented on source/_components/sensor.solax.markdown
> +{% raw %}
```suggestion
```

2019-03-31 07:43 UTC, frenck commented on source/_components/sensor.solax.markdown
> +{% endraw %}
```suggestion
```

2019-03-31 07:57 UTC, CountParadox commented
Done!

2019-03-31 08:11 UTC, frenck commented
Thanks for handling those change so fast @CountParadox! 👍 

✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-03-31 08:12 UTC, frenck submitted a review, later dismissed

2019-05-26 09:08 UTC, squishykid commented
@frenck parent has been merged

2019-05-26 18:08 UTC, klaasnicolaas requested changes

2019-05-26 18:08 UTC, klaasnicolaas commented on source/_components/solax.markdown
> +ha_release: 0.91
```suggestion
ha_release: 0.94
```

2019-05-26 18:08 UTC, klaasnicolaas commented on source/_components/solax.markdown
> +sensor:
I think that we can remove this one, it's almost the same as above.

2019-05-29 21:48 UTC, klaasnicolaas approved these changes

2019-05-29 21:48 UTC, merged