Updated documentation for template binary_sensor
home-assistant/home-assistant.github.io pull request #9106
Opened 2019-04-02 20:07 UTC by gadgetchnnel

**Description:**
Added documentation for the new attribute_templates option for the template binary sensor.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22664

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-02 20:50 UTC, klaasnicolaas submitted a review, later dismissed

2019-06-01 21:13 UTC, klaasnicolaas commented
Parent PR still open ⚠️ We have a merge conflict

2019-06-18 19:58 UTC, frenck requested changes
Hey, @gadgetchnnel, a wild merge conflict appeared 😢 

Could you please take a look and resolve it? Thanks already! 👍

2019-06-18 20:22 UTC, frenck submitted a review, later dismissed

2019-06-18 20:23 UTC, frenck commented
Thanks for resolving the merge conflict so quickly @gadgetchnnel!
Awaiting parent PR now.

2019-07-18 22:49 UTC, frenck commented
A wild merge conflict appeared again. @gadgetchnnel could you take a look? Thanks 👍

2019-07-21 11:56 UTC, klaasnicolaas commented on source/_components/binary_sensor.template.markdown
> +### {% linkable_title Device Tracker sensor with Latitude and Longitude Attributes %}
```suggestion
### Device Tracker sensor with Latitude and Longitude Attributes
```

2019-07-21 14:25 UTC, gadgetchnnel commented on source/_components/binary_sensor.template.markdown
> +### {% linkable_title Device Tracker sensor with Latitude and Longitude Attributes %}
Just made that change

2019-08-13 08:08 UTC, frenck approved these changes

2019-08-21 21:41 UTC, frenck commented
Parent PR got merged! 🎉 
Thanks for this @gadgetchnnel! 👍

2019-08-21 21:41 UTC, merged