Create epsonprinter.markdown
home-assistant/home-assistant.github.io pull request #9200
Opened 2019-04-11 16:54 UTC by ThaStealth

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#23000

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-12 09:39 UTC, klaasnicolaas requested changes

2019-04-12 09:39 UTC, klaasnicolaas commented on source/_components/epsonworkforceprinter.markdown
> +redirect_from:
only for existing pages

2019-04-12 09:39 UTC, klaasnicolaas commented on source/_components/epsonworkforceprinter.markdown
> +  description: The cartridge colours to monitor. Valid values are: black,yellow,magenta,cyan and clean. Clean is the cleaning cartridge
```suggestion
  description: "The cartridge colours to monitor. Valid values are: `black`, `yellow`, `magenta`, `cyan` and `clean`. Clean is the cleaning cartridge."
```

2019-04-12 09:39 UTC, klaasnicolaas commented on source/_components/epsonworkforceprinter.markdown
> +     host: 192.168.0.123
```suggestion
     host: IP_ADDRESS
```

2019-04-12 10:03 UTC, ThaStealth commented on source/_components/epsonworkforceprinter.markdown
> +redirect_from:
Removed it

2019-04-17 13:19 UTC, closed without merging

2019-04-24 18:41 UTC, balloob commented
@ThaStealth you have closed this PR for the docs but the integration was merged. Please open a PR asap to fix this.

2019-04-25 07:50 UTC, ThaStealth commented
Very strange, I do not know how I caused this.
Anyway, created a new PR at https://github.com/home-assistant/home-assistant.io/pull/9294

2019-04-25 20:05 UTC, balloob commented
Thanks!