Add Honeywell Lyric Component Docs
home-assistant/home-assistant.github.io pull request #9201
Opened 2019-04-11 19:53 UTC by timmo001

**Description:**

Adds docs for new compoenent

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#23015

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-11 20:19 UTC, timmo001 commented
Not sure why netlify didn't generate a page at:

https://deploy-preview-9201--home-assistant-docs.netlify.com/components/lyric/

Did something change, did I miss something or is this a bug I've hit?

2019-04-12 00:38 UTC, klaasnicolaas commented
That happens when you use the `redirect_from` for the same page 😆

2019-04-12 02:07 UTC, timmo001 commented
Ah. Thanks!

2019-04-12 09:35 UTC, klaasnicolaas commented on source/_components/lyric.markdown
> +  client_id: !secret lyric_client_key
At the moment we have not a kind of policy, that you must use `!secret` (ofcourse it's better 😉 ). But the examples are for simple copy/paste work.

2019-04-25 13:41 UTC, klaasnicolaas submitted a review, later dismissed

2019-05-06 00:10 UTC, klaasnicolaas commented
Is there some progress?

2019-06-23 11:08 UTC, klaasnicolaas requested changes

2019-06-23 11:08 UTC, klaasnicolaas commented on source/_components/lyric.markdown
> +ha_release: 0.95
```suggestion
ha_release: 0.96
```

2019-07-18 22:52 UTC, frenck submitted a review, later dismissed

2019-12-02 19:22 UTC, closed without merging