Update Météo France component documentation
home-assistant/home-assistant.github.io pull request #9239
Opened 2019-04-17 18:27 UTC by oncleben31

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#23128

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-17 20:14 UTC, klaasnicolaas requested changes

2019-04-17 20:14 UTC, klaasnicolaas commented on source/_components/meteo_france.markdown
> +  The weather alert is available for the metropolitan France.<br/>
```suggestion
  The weather alert is available for the metropolitan France.
```

2019-04-17 20:14 UTC, klaasnicolaas commented on source/_components/meteo_france.markdown
> +The sensor attributes  give access to each type of alerts and date of the bulletin emitted by Météo-France.
```suggestion
The sensor attributes give access to each type of alerts and date of the bulletin emitted by Météo-France.
```

2019-04-17 21:24 UTC, oncleben31 commented
Thanks for the quick review.

2019-04-19 08:36 UTC, oncleben31 reviewed
OK taken into account.

2019-04-19 08:40 UTC, oncleben31 commented
@klaasnicolaas I'm not sure what I have to do for resolving the red "Changes requested" action in the checks?
I've add a commit with your suggestion. Do I need to do something else?

2019-04-19 11:56 UTC, klaasnicolaas commented
@oncleben31 You don't have to do anything, it is waiting for the parent PR to merge.

2019-04-19 11:58 UTC, klaasnicolaas submitted a review, later dismissed

2019-05-17 16:08 UTC, oncleben31 commented
Hey @klaasnicolaas. It seems no one is available to review my parent PR. Perhaps it's now too low in the PR list to catch attention. Do you have any means to poke some other dev to see if they can invest some time on it ?

2019-05-18 11:00 UTC, klaasnicolaas commented
You just have to wait, reviewers work the list in their own way.

2019-05-18 20:06 UTC, oncleben31 commented
Thanks for taking the time to answer me. I'm new in this PR game.
I've other ideas of improvement for this integration. Do you think I can continue to add features or I should try to keep my PR not too complex

2019-05-18 20:11 UTC, klaasnicolaas commented
Depends on what you are planning, but we prefer that PRs do not become too large and complex. So maybe you can do it better in a new PR.

2019-06-20 13:07 UTC, frenck approved these changes

2019-06-20 13:10 UTC, merged