Update documentation for #23162
home-assistant/home-assistant.github.io pull request #9254
Opened 2019-04-19 12:05 UTC by Devqon

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-19 12:21 UTC, klaasnicolaas requested changes

2019-04-19 12:21 UTC, klaasnicolaas commented on source/_components/harman_kardon_avr.markdown
>  media_player:
Only required variables in the first example

2019-04-19 12:21 UTC, klaasnicolaas commented on source/_components/harman_kardon_avr.markdown
> +ha_release: 0.85.0
Please undo this

2019-04-19 12:21 UTC, klaasnicolaas commented on source/_components/harman_kardon_avr.markdown
> +redirect_from:
Please undo this

2019-06-20 10:22 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2019-06-20 10:22 UTC, closed without merging