Added bizkaibus.makdown
home-assistant/home-assistant.github.io pull request #9280
Opened 2019-04-22 12:58 UTC by UgaitzEtxebarria

**Description:**
Added the web page for the bizkaibus component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant/pull/22934

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-22 20:46 UTC, klaasnicolaas requested changes

2019-04-22 20:46 UTC, klaasnicolaas commented on source/_components/bizkaibus.markdown
> +redirect_from:
Not necessary because this is not an existing page.

2019-04-22 20:46 UTC, klaasnicolaas commented on source/_components/bizkaibus.markdown
> +ha_category: Transport
```suggestion
ha_category: 
  - Transport
  - Sensor
```

2019-04-22 20:46 UTC, klaasnicolaas commented on source/_components/bizkaibus.markdown
> +http://apli.bizkaia.net/APPS/DANOK/TQ/DATOS_PARADAS/DATOS_Paradas.xml (PR_CODRED is the STOP_ID)
Maybe make this link clickable?

2019-05-06 19:22 UTC, UgaitzEtxebarria commented
I forgot to add the logo inte source/images and I have included (I hope it is not too late)

2019-05-06 19:46 UTC, klaasnicolaas approved these changes

2019-05-06 19:46 UTC, merged