Update mqtt configuration example to use external broker
home-assistant/home-assistant.github.io pull request #9316
Opened 2019-04-26 05:48 UTC by emontnemery

**Description:**
The internal MQTT broker has been marked as deprecated. Update the documention to reflect this.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22753

## Checklist:

- [x] Branch: Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-26 12:36 UTC, klaasnicolaas submitted a review, later dismissed

2019-04-26 12:36 UTC, klaasnicolaas commented on source/_docs/mqtt.markdown
> +  broker: 192.168.1.100
```suggestion
  broker: IP_ADDRESS
```

2019-04-28 16:42 UTC, fabaff requested changes
The component documentation needs to be updated to.

2019-04-28 17:25 UTC, emontnemery commented
@fabaff done here #9317

2019-04-28 17:33 UTC, emontnemery commented on source/_docs/mqtt.markdown
> +  broker: 192.168.1.100
Fixed!

2019-05-02 18:55 UTC, emontnemery commented
@klaasnicolaas, @fabaff I think I've addressed your concerns, can you check again?

2019-05-10 20:44 UTC, fabaff approved these changes

2019-05-10 20:44 UTC, merged