Added documentation for IPP printer component
home-assistant/home-assistant.github.io pull request #9343
Opened 2019-04-28 18:52 UTC by Matte23

**Description:** Documentation for the new component IPP Printer

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-28 19:51 UTC, klaasnicolaas requested changes

2019-04-28 19:51 UTC, klaasnicolaas commented on source/_components/ipp_printer.markdown
> +ha_category: System Monitor
```suggestion
ha_category:
  - System Monitor
  - Sensor
```

2019-04-28 19:51 UTC, klaasnicolaas commented on source/_components/ipp_printer.markdown
> +redirect_from:
This is only for existing pages

2019-04-28 21:11 UTC, klaasnicolaas commented
Pherhaps you could use this logo for the componen? https://www.pwg.org/ipp/everywhere.html

2019-04-29 13:44 UTC, Matte23 commented
> Pherhaps you could use this logo for the component? https://www.pwg.org/ipp/everywhere.html

It's a good idea, but I'm not sure if non PWG members are allowed to use this logo.

2019-06-19 21:38 UTC, closed without merging