Add Essent
home-assistant/home-assistant.github.io pull request #9351
Opened 2019-04-29 18:29 UTC by TheLastProject

**Description:**
Allows retrieving your meter information from Essent.

Note: I have not been able to test how it renders because I'm having issues with my Ruby installation.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#23513

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-29 18:50 UTC, TheLastProject commented
Hmm, the page doesn't show up in the preview and I don't know why :(

2019-04-29 18:57 UTC, klaasnicolaas requested changes

2019-04-29 18:57 UTC, klaasnicolaas commented on source/_components/essent.markdown
> +redirect_from:
Please remove this -> `redirect_from`

2019-04-29 19:40 UTC, klaasnicolaas commented
If all goes well you can now see the page in netlify

2019-04-29 20:07 UTC, TheLastProject commented
Yup I can see it, and it looks fine to me. Please tell me if you want me to change anything :)

2019-04-29 20:10 UTC, klaasnicolaas approved these changes

2019-05-01 05:26 UTC, TheLastProject commented
Parent has been merged :)

2019-05-01 09:18 UTC, merged

2019-05-01 09:19 UTC, klaasnicolaas commented
Well then it's time to merge 😉 Always nice some new Dutch integrations 🎉