Updating sesame component docs
home-assistant/home-assistant.github.io pull request #9355
Opened 2019-04-30 08:50 UTC by zanglang

**Description:**

Updating the sesame component's documentation with the api_key config needed for V3 API.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-30 09:55 UTC, klaasnicolaas requested changes

2019-04-30 09:55 UTC, klaasnicolaas commented on source/_components/sesame.markdown
> +date: 2019-04-30 12:00
Please do not change this

2019-04-30 10:08 UTC, zanglang commented on source/_components/sesame.markdown
> +date: 2019-04-30 12:00
My bad, thanks!

2019-05-17 07:02 UTC, zanglang commented
Hi, any chance we could get this merged? This PR adds a URL for sesame users to generate an API key, which is a breaking change just released in home-assistant.

2019-05-17 07:06 UTC, robbiet480 approved these changes

2019-05-17 07:08 UTC, merged

2019-05-17 07:08 UTC, robbiet480 commented
@zanglang ask and ye shall receive