Update volvooncall.markdown
home-assistant/home-assistant.github.io pull request #9356
Opened 2019-04-30 12:35 UTC by silfa718

**Description:**

Just trying to make the instructions and example clearer to understand.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-30 14:02 UTC, klaasnicolaas requested changes

2019-04-30 14:02 UTC, klaasnicolaas commented on source/_components/volvooncall.markdown
> +  description: Make it possible to provide a name for the vehicles. Note: Use all lower case letters when inputing your VIN number.
```suggestion
  description: "Make it possible to provide a name for the vehicles. Note: Use all lower case letters when inputing your VIN number."
```

2019-04-30 14:32 UTC, silfa718 commented
That's better.

2019-05-08 12:34 UTC, klaasnicolaas approved these changes

2019-05-08 12:35 UTC, merged