Added documentation for new strava component
home-assistant/home-assistant.github.io pull request #9358
Opened 2019-04-30 20:30 UTC by stv0g

**Description:**

Adds documentation for new `strava` component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#22151

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-04-30 21:24 UTC, klaasnicolaas requested changes

2019-04-30 21:24 UTC, klaasnicolaas commented on source/_components/strava.markdown
> +redirect_from:
Please remove this

2019-04-30 21:24 UTC, klaasnicolaas commented on source/_components/strava.markdown
> +ha_release: 0.93.0
```suggestion
ha_release: 0.93
```

2019-04-30 21:24 UTC, klaasnicolaas commented on source/_components/strava.markdown
> +ha_category:
Add also: `Health`

2019-04-30 22:38 UTC, stv0g commented on source/_components/strava.markdown
> +ha_release: 0.93.0
Done

2019-04-30 22:39 UTC, stv0g commented on source/_components/strava.markdown
> +redirect_from:
Done

2019-05-06 08:00 UTC, stv0g commented
@klaasnicolaas Hi, I addressed the requested changes :) Can we merge this PR? The component is also ready to be merged in the HA repo.

2019-05-06 09:11 UTC, klaasnicolaas commented
The parent pr must be merged first, only then we merge this PR 😉

2019-08-08 10:45 UTC, frenck commented
Closing PR, since the parent PR has been closed

2019-08-08 10:45 UTC, closed without merging