Added information for the MeteoAlarm Sensor
home-assistant/home-assistant.github.io pull request #9375
Opened 2019-05-03 17:38 UTC by rolfberkenbosch

**Description:**
Documentation about a new sensor meteoalarm to get weather alerts in Europe.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-05-03 17:42 UTC, klaasnicolaas requested changes

2019-05-03 17:42 UTC, klaasnicolaas commented on source/_components/meteoalarm.markdown
> +redirect_from:
Please remove this

2019-05-03 17:42 UTC, klaasnicolaas commented on source/_components/meteoalarm.markdown
> +    language: 'ne-NL' (use your language)
Only required variables

2019-05-03 17:42 UTC, klaasnicolaas commented on source/_components/meteoalarm.markdown
> +    country: 'NL' (use your own country digits)
```suggestion
    country: 'NL'
```

2019-05-03 17:42 UTC, klaasnicolaas commented on source/_components/meteoalarm.markdown
> +    province: 'Groningen' (use your own province name)
```suggestion
    province: 'Groningen'
```

2019-05-03 17:42 UTC, klaasnicolaas commented on source/_components/meteoalarm.markdown
> +    language: 'ne-NL' (use your language)
```suggestion
    language: 'ne-NL'
```

2019-05-03 17:47 UTC, klaasnicolaas requested changes

2019-05-03 17:47 UTC, klaasnicolaas commented on source/_components/meteoalarm.markdown
> +  default: "meteoalarm"
```suggestion
  default: meteoalarm
```

2019-05-03 17:47 UTC, klaasnicolaas commented on source/_components/meteoalarm.markdown
> +  description: The 4 digits our your language, please be aware that this is only possible in the current country. So 'ne' is only possible in Netherlands. Possible options is: bu, bs, ce, da, de, ee,
```suggestion
  description: "The 4 digits our your language, please be aware that this is only possible in the current country. So 'ne' is only possible in Netherlands. Possible options is: bu, bs, ce, da, de, ee, en, es, ga, ca, su, fr, gr, he, hr, ma, is, it, li, la, sr, mk, ma, ne, no, po, ro, cp, sv, sl, eu."
```

Perhaps better to place all possible options in a list elsewhere on the page

2019-05-03 17:47 UTC, klaasnicolaas commented on source/_components/meteoalarm.markdown
> +  default: 'en'.
```suggestion
  default: 'en'
```

2019-05-04 00:10 UTC, rolfberkenbosch commented
I'm sorry guys that i have added so much pull requests. I made a few mistakes, the last one should no be good.

2019-05-04 14:40 UTC, fabaff commented
> I'm sorry guys that i have added so much pull requests.

Don't worry, we will squash the commits when we are merging.

2019-05-07 05:28 UTC, rolfberkenbosch commented
@klaasnicolaas can you approve my last commit, because the binary sensor has been approved.

2019-05-07 11:35 UTC, klaasnicolaas approved these changes

2019-05-08 00:50 UTC, merged