Initial documentation for the Rotel Media Player platform
home-assistant/home-assistant.github.io pull request #9387
Opened 2019-05-05 12:49 UTC by pp81381

**Description:**

Initial documentation for the Rotel Media Player platform

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-05-05 17:56 UTC, klaasnicolaas requested changes

2019-05-05 17:56 UTC, klaasnicolaas commented on source/_components/rotel.markdown
> +ha_release: 0.93.0
```suggestion
ha_release: 0.93
```

2019-05-05 17:56 UTC, klaasnicolaas commented on source/_components/rotel.markdown
> +description: "Rotel Media Player platform implementation.   Currently only supports the Rotel RSP-1570 Processor."
```suggestion
description: "Rotel Media Player platform implementation."
```

2019-06-18 20:48 UTC, frenck requested changes
Hi there @pp81381, I've reviewed your PR and left some comments. Nothing big, don't worry!
Could you please take a look? Thanks already! 👍

2019-06-18 20:48 UTC, frenck commented on source/_components/rotel.markdown
> +At the moment the platform only supports the Rotel RSP-1570 processor but the underlying third party library could be adapted to support other devices of the same vintage.
```suggestion
At the moment the platform only supports the Rotel RSP-1570 processor but the underlying third-party library could be adapted to support other devices of the same vintage.
```

2019-06-18 20:48 UTC, frenck commented on source/_components/rotel.markdown
> +  type: dict
`dict` is not a valid type for our documentation. Please see:

<https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration>

2019-06-18 20:48 UTC, frenck commented on source/_components/rotel.markdown
> +The media player component offers the followiing services:
```suggestion
The media player component offers the following services:
```

2019-06-18 20:48 UTC, frenck commented on source/_components/rotel.markdown
> +The `entity_id` parameter can be a single entity id, a comma separated list or the word `all`.
```suggestion
The `entity_id` parameter can be a single entity id, a comma-separated list or the word `all`.
```

2019-07-14 20:16 UTC, frenck commented
Closing this PR, since the parent PR has been closed.

2019-07-14 20:16 UTC, closed without merging