added page and logo for warmup4IE thermostat
home-assistant/home-assistant.github.io pull request #9396
Opened 2019-05-06 18:42 UTC by alex-0103

**Description:**
new documentation page for warmup4IE thermostat, see PR link below.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#21144

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-05-10 09:21 UTC, klaasnicolaas requested changes

2019-05-10 09:21 UTC, klaasnicolaas commented on source/_components/climate.warmup.markdown
> +ha_release: 0.93
```suggestion
ha_release: 0.94
```

2019-06-18 20:57 UTC, frenck requested changes
Hi there @alex-0103. I've reviewed your PR and left some tiny comments. Could you please take a look? Thanks! 👍

2019-06-18 20:57 UTC, frenck commented on source/_components/climate.warmup.markdown
> +ha_qa_scale:
If there is no scale, this should be removed.

2019-06-18 20:57 UTC, frenck commented on source/_components/climate.warmup.markdown
> +The `warmup` climate platform let you control Warmup 4IE thermostats from Home Assistant.
```suggestion
The `warmup` climate platform lets you control Warmup 4IE thermostats from Home Assistant.
```

2019-06-18 20:57 UTC, frenck commented on source/_components/climate.warmup.markdown
> +To use this component, you have to setup an account at the warmup web site first and register your thermostat appropriately. See <https://my.warmup.com/login>.
```suggestion
To use this component, you have to set up an account at the warmup web site first and register your thermostat appropriately. See <https://my.warmup.com/login>.
```

2019-06-18 20:57 UTC, frenck commented on source/_components/climate.warmup.markdown
> +  description: Name of thermostat.
```suggestion
  description: Name of the thermostat.
```

2019-06-18 20:57 UTC, frenck commented on source/_components/climate.warmup.markdown
> +{% endconfiguration %}
```suggestion
{% endconfiguration %}

```

2019-08-21 17:27 UTC, closed without merging