Adds documentation for Plaato Airlock
home-assistant/home-assistant.github.io pull request #9398
Opened 2019-05-06 23:37 UTC by JohNan

**Description:**
Adds a new integration for the Plaato Airlock. Plaato Airlock is a tool for beer brewers that wants a unique insight in the fermentation process. It will create sensors for the data that is pushed to a webhook from the airlock.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#23727

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-05-07 10:24 UTC, JohNan commented
I just got a green light from Plaato to use their logo in the documentation. Please wait with merge until I have updated the PR

2019-05-07 11:45 UTC, klaasnicolaas requested changes

2019-05-07 11:45 UTC, klaasnicolaas commented on source/_components/plaato.markdown
> +ha_iot_class: "Cloud Push"
```suggestion
ha_iot_class: Cloud Push
```

2019-05-07 11:45 UTC, klaasnicolaas commented on source/_components/plaato.markdown
> +ha_release: "0.93"
```suggestion
ha_release: 0.93
```

2019-05-07 12:59 UTC, JohNan commented
@klaasnicolaas The example at https://developers.home-assistant.io/docs/en/documentation_create_page.html says those values should use quotes. Maybe the docs need to be updated?

Pushed the changes you suggested.

2019-05-07 13:07 UTC, klaasnicolaas commented
In the case of the release version, it should only be for versions that end with a 0, such as 0.30, 0.40, 0.50 etc. For the iot class it is wrong in the example.

2019-05-07 13:43 UTC, JohNan commented
@klaasnicolaas I understand. Is the changes fine no then?

2019-05-07 14:43 UTC, klaasnicolaas submitted a review, later dismissed

2019-06-18 10:14 UTC, frenck approved these changes
Thanks, @JohNan! 👍

2019-06-18 10:17 UTC, merged