Initial commit - markdown & image
home-assistant/home-assistant.github.io pull request #9401
Opened 2019-05-07 09:24 UTC by zxdavb

**Description:**
Adds the Intergas InComfort (known as InTouch in UK) Lan2RF gateway.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#23736

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-05-07 17:06 UTC, klaasnicolaas requested changes

2019-05-07 17:06 UTC, klaasnicolaas commented on source/_components/incomfort.markdown
> +  type: integer
Are you sure this must be an integer?

2019-05-07 17:10 UTC, zxdavb commented on source/_components/incomfort.markdown
> +  type: integer
no - have pushed a fix

2019-05-07 21:57 UTC, MartinHjelmare commented on source/_components/incomfort.markdown
> +ha_release: 0.94
This should make it into 0.93.

2019-05-07 21:57 UTC, MartinHjelmare commented on source/_components/incomfort.markdown
> +In future, other entities will be added to this integration (e.g. a **Sensor** for CV pressure, and a **Climate** device for room temperature).
```suggestion
In the future, other entities will be added to this integration (e.g. a **Sensor** for CV pressure, and a **Climate** device for room temperature).
```

2019-05-08 12:25 UTC, klaasnicolaas approved these changes

2019-05-08 12:25 UTC, merged