Add water_heater to geniushub integration
home-assistant/home-assistant.github.io pull request #9402
Opened 2019-05-07 13:47 UTC by zxdavb

**Description:**
Adds a water_heater to the Genius Hub integration. Also updates client library to latest version.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#23384

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-05-07 14:43 UTC, klaasnicolaas requested changes

2019-05-07 14:43 UTC, klaasnicolaas commented on source/_components/geniushub.markdown
> +date: 2019-05-07 16:00
Please do not change

2019-05-07 16:26 UTC, zxdavb commented on source/_components/geniushub.markdown
> +date: 2019-05-07 16:00
un-changed

2019-05-07 17:29 UTC, klaasnicolaas submitted a review, later dismissed

2019-05-08 00:42 UTC, klaasnicolaas approved these changes

2019-05-08 00:42 UTC, merged