Add Linky sensors : yesterday + months + years
home-assistant/home-assistant.github.io pull request #9422
Opened 2019-05-08 20:38 UTC by Quentame

**Description:**
Documentation for home-assistant/home-assistant#23726

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#23726

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-05-21 12:15 UTC, Quentame commented
Any news about this and home-assistant/home-assistant#23726 @klaasnicolaas ?

2019-05-21 12:41 UTC, klaasnicolaas commented
Well there is a merge conflict that you need to solve first 😉

2019-05-21 12:45 UTC, Quentame commented
Ok, haven't seen it, solving tonight.

It seems I haven't been notify of that :thinking:

2019-06-05 15:41 UTC, Quentame commented
Both of my PRs were rebased and tested :wink: 
@klaasnicolaas

2019-06-05 18:10 UTC, klaasnicolaas commented
Great but we still have to wait on the parent pr 😜

2019-06-12 07:33 UTC, Quentame commented
Parent PR merged

2019-06-18 09:07 UTC, frenck requested changes
@Quentame Could you please adjust the documentation with the last changes made in the parent PR? Thanks! 👍

2019-06-18 09:07 UTC, frenck commented on source/_components/linky.markdown
> +monitored_conditions:
This has been removed in the parent PR.

2019-06-18 21:01 UTC, frenck commented
PR adjusted. Removed the "tip" as well. While good at heart, when we started adding it everywhere in the docs, it might become annoying. Therefore, removed it.

2019-06-18 21:05 UTC, klaasnicolaas submitted a review, later dismissed

2019-06-18 21:06 UTC, frenck submitted a review, later dismissed

2019-06-18 21:15 UTC, frenck approved these changes

2019-06-18 21:15 UTC, merged