WIP: Update documentation related to sun triggers and sun conditions.
home-assistant/home-assistant.github.io pull request #9423
Opened 2019-05-09 14:47 UTC by emontnemery

**Description:**
This PR intends to improve the documentation related to the sun.

The sun conditions are not useful in locations with polar night/day, or in locations with very skewed time zones. Also, using sun conditions or triggers with a time offset should be disencouraged as the duration of twilight varies throughout the year.

More discussion here: home-assistant/architecture#225

## Checklist:

- [x] Branch: Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-05-10 09:28 UTC, klaasnicolaas requested changes

2019-05-10 09:28 UTC, klaasnicolaas commented on source/_docs/scripts/conditions.markdown
> +#### Sun state condition
please make it clickable

2019-05-10 09:28 UTC, klaasnicolaas commented on source/_docs/automation/trigger.markdown
> +#### Sunset / Sunrise trigger
Here

2019-05-10 09:28 UTC, klaasnicolaas commented on source/_docs/automation/trigger.markdown
> +#### Sun elevation trigger
Here

2019-05-10 09:28 UTC, klaasnicolaas commented on source/_docs/scripts/conditions.markdown
> +#### Sun elevation condition
Here

2019-05-10 09:28 UTC, klaasnicolaas commented on source/_docs/scripts/conditions.markdown
> +#### Sunset/sunrise condition
Here

2019-05-10 13:14 UTC, emontnemery commented
@klaasnicolaas Thanks for reviewing, fixed now!

2019-05-29 22:17 UTC, klaasnicolaas approved these changes

2019-05-29 22:17 UTC, merged