Added npi_gpio component section
home-assistant/home-assistant.github.io pull request #9509
Opened 2019-05-24 00:05 UTC by Tungsteno74

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-05-24 06:33 UTC, klaasnicolaas requested changes

2019-05-24 06:33 UTC, klaasnicolaas commented on source/_components/npi_gpio.markdown
> +ha_release: pre 0.93.2
```suggestion
ha_release: 0.94
```

2019-05-24 06:33 UTC, klaasnicolaas commented on source/_components/npi_gpio.markdown
> +redirect_from:
This is only for existing pages

2019-05-24 17:23 UTC, Tungsteno74 commented
@klaasnicolaas thanks for your review

2019-05-24 19:42 UTC, klaasnicolaas commented
Well @Tungsteno74 it's my duty 😜

2019-07-02 23:09 UTC, klaasnicolaas requested changes

2019-07-02 23:09 UTC, klaasnicolaas commented on source/_components/npi_gpio.markdown
> +ha_release: 0.94
```suggestion
ha_release: 0.96
```

2019-07-10 21:00 UTC, frenck commented
Closing PR, since the parent PR has been closed.

2019-07-10 21:00 UTC, closed without merging