Add docs for PR #24103
home-assistant/home-assistant.github.io pull request #9518
Opened 2019-05-25 16:31 UTC by perosb

**Description:**
Update docs for change in https://github.com/home-assistant/home-assistant/pull/24103

Also includes doc updates done in https://github.com/home-assistant/home-assistant.io/pull/9226

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-07-02 22:48 UTC, klaasnicolaas submitted a review, later dismissed

2019-07-02 22:48 UTC, klaasnicolaas commented on source/_components/prometheus.markdown
>  prometheus:
Only required items in the first example

2019-08-10 12:38 UTC, MartinHjelmare requested changes

2019-08-10 12:38 UTC, MartinHjelmare commented on source/_components/prometheus.markdown
> +prometheus:
We don't include the top level component domain name in the config spec.

2019-08-10 12:56 UTC, MartinHjelmare commented on source/_components/prometheus.markdown
> +keys:
The above items should also be removed.

2019-08-10 13:00 UTC, perosb commented on source/_components/prometheus.markdown
> +keys:
You're a fast reviewer ;)

2019-08-10 13:03 UTC, MartinHjelmare approved these changes

2019-08-10 20:15 UTC, frenck approved these changes
Thanks, @perosb! 👍

2019-08-10 20:15 UTC, merged