General Linux deps are wrong
home-assistant/home-assistant.github.io pull request #9520
Opened 2019-05-26 00:21 UTC by gerdesj

See https://github.com/home-assistant/home-assistant/issues/24095

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-05-26 09:22 UTC, fabaff commented on source/_docs/z-wave/installation.markdown
> -On Debian Linux platforms there two dependencies you will need to have installed ahead of time (included in `systemd-devel` on Fedora/RHEL systems):
According to the [spec file](https://src.fedoraproject.org/rpms/systemd/blob/master/f/systemd.spec) is `libudev-dev` still handled by `systemd-devel`.

2019-06-04 19:32 UTC, frenck approved these changes
Thanks, @gerdesj! 👍

2019-06-04 19:33 UTC, frenck requested changes
Aah missed the RH part that fabaff points out...

2019-06-18 21:35 UTC, frenck commented
A small and friendly notification @gerdesj 

Are you planning on moving forward on this PR? 
I didn't see any activity recently, while there are still things to do. I hope you consider picking it up soon! 👍

2019-06-18 21:58 UTC, gerdesj commented
I misread @fabaff's comment and they are correct.  I over edited.  I deleted the phrase _"(included in `systemd-devel` on Fedora/RHEL systems)"_ in error.

I've poked at Github a bit but I'm not sure how to change my commit and resubmit.  Please either drop my commit or if you have a black belt in git please fix it - the rest is correct. I don't need attribution.

Sorry for being a pain.

2019-07-31 08:40 UTC, closed without merging