Life360 integration
home-assistant/home-assistant.github.io pull request #9539
Opened 2019-05-31 17:56 UTC by pnbruckner

**Description:**
Add Life360 integration.

> Note: This is "take 2." The original proposal can be found in #9302.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-05-31 21:17 UTC, klaasnicolaas requested changes

2019-05-31 21:17 UTC, klaasnicolaas commented on source/_components/life360.markdown
> +ha_release: 0.94
```suggestion
ha_release: 0.95
```

2019-05-31 21:17 UTC, klaasnicolaas commented on source/_components/life360.markdown
> +ha_category: Presence Detection
```suggestion
ha_category:
  - Presence Detection
```

2019-05-31 21:51 UTC, klaasnicolaas submitted a review, later dismissed

2019-06-18 10:08 UTC, frenck approved these changes
Thanks, @pnbruckner!

2019-06-18 10:14 UTC, merged