Add documentation for JLR InControl component
home-assistant/home-assistant.github.io pull request #9551
Opened 2019-06-02 07:31 UTC by rb28z2

**Description:**
Add document for the Jaguar/Land Rover InControl component

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#24211

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-06-02 09:55 UTC, HarryJHolmes reviewed
So is ‘name’ required it suggests here, it is  not?

2019-06-02 10:52 UTC, HarryJHolmes submitted a review, later dismissed

2019-06-02 11:36 UTC, klaasnicolaas requested changes

2019-06-02 11:36 UTC, klaasnicolaas commented on source/_components/jlrincontrol.markdown
> +ha_iot_class: Polling
```suggestion
ha_iot_class: Cloud Polling
```

2019-06-02 11:36 UTC, klaasnicolaas commented on source/_components/jlrincontrol.markdown
> +ha_release: 0.94
```suggestion
ha_release: 0.95
```

2019-06-02 11:36 UTC, klaasnicolaas commented on source/_components/jlrincontrol.markdown
> +redirect_from:
Please remove the `redirect_from` section

2019-06-02 11:36 UTC, klaasnicolaas commented on source/_components/jlrincontrol.markdown
> +jlrincontrol:
Only required items in the first example

2019-06-02 11:36 UTC, klaasnicolaas commented on source/_components/jlrincontrol.markdown
> +  password: 'password'
```suggestion
  password: 'PASSWORD'
```

2019-06-02 11:36 UTC, klaasnicolaas commented on source/_components/jlrincontrol.markdown
> +  username: 'email@domain.com'
```suggestion
  username: 'EMAIL_ADDRESS'
```

2019-06-02 11:37 UTC, klaasnicolaas requested changes

2019-06-02 11:37 UTC, klaasnicolaas commented on source/_components/jlrincontrol.markdown
> +ha_category:
```suggestion
ha_category:
  - Car
  - Binary Sensor
  - Sensor
```

2019-06-02 16:04 UTC, rb28z2 commented
> So is ‘name’ required it suggests here, it is not?

Correct, `name` is required.

2019-06-24 22:19 UTC, Harryjholmes commented
Are the changes requested preventing merge? @rb28z2

2019-06-24 22:42 UTC, rb28z2 commented
I believe I addressed those. Just needs a re-review :)

2019-06-30 09:44 UTC, klaasnicolaas requested changes

2019-06-30 09:44 UTC, klaasnicolaas commented on source/_components/jlrincontrol.markdown
> +ha_release: 0.95
```suggestion
ha_release: 0.96
```

2019-07-02 16:25 UTC, Harryjholmes commented
@rb28z2

2019-07-02 16:51 UTC, rb28z2 commented
@klaasnicolaas I've bumped the released version - hopefully its good now.

2019-07-03 11:54 UTC, klaasnicolaas requested changes

2019-07-03 11:54 UTC, klaasnicolaas commented on source/_components/jlrincontrol.markdown
> +  required: false
```suggestion
  required: true
```

name was required right?

2019-07-03 13:53 UTC, rb28z2 commented
I addressed the name field issue. Slip on my part 😅

2019-07-03 16:44 UTC, klaasnicolaas approved these changes

2019-07-03 16:44 UTC, klaasnicolaas commented
✅ Can be merged after merging the parent PR 👍

2019-09-03 00:33 UTC, closed without merging