vlc-telnet component documentation added
home-assistant/home-assistant.github.io pull request #9558
Opened 2019-06-03 03:33 UTC by rodripf

**Description:**
Documentation added for the new component vlc-telnet. I am opening the PR right now.

## Checklist:

- [X ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-06-09 17:17 UTC, klaasnicolaas requested changes

2019-06-09 17:17 UTC, klaasnicolaas commented on source/_components/vlc-telnet.markdown
> +ha_release: 0.35
```suggestion
ha_release: 0.95
```

2019-06-09 17:17 UTC, klaasnicolaas commented on source/_components/vlc-telnet.markdown
> +redirect_from:
Please remove the `redirect_from`

2019-06-09 17:17 UTC, klaasnicolaas commented on source/_components/vlc-telnet.markdown
> +    host: "127.0.0.1"
```suggestion
    host: IP_ADDRESS
```

2019-06-09 17:17 UTC, klaasnicolaas commented on source/_components/vlc-telnet.markdown
> +    password: "test"
```suggestion
    password: PASSWORD
```

2019-06-09 17:17 UTC, klaasnicolaas commented on source/_components/vlc-telnet.markdown
> +name:
```suggestion
name:
  default: VLC-TELNET
```

There is a default config variable

2019-06-09 17:17 UTC, klaasnicolaas commented on source/_components/vlc-telnet.markdown
> +  description: The port number where the VLC Player is running. The default value is *4212*
same

2019-06-10 12:30 UTC, klaasnicolaas commented on source/_components/vlc-telnet.markdown
> +media_player:
Here you could do the config without the placeholders 😉

2019-06-26 04:15 UTC, balloob approved these changes

2019-06-26 04:16 UTC, merged