Update totalconnect.markdown
home-assistant/home-assistant.github.io pull request #9589
Opened 2019-06-08 23:46 UTC by austinmroczek

**Description:**
Update docs to show new configuration entry requirement.  

Also adds suggestion to use a separate, non administrative account Total Connect account with HA.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** https://github.com/home-assistant/home-assistant/pull/24427

## Checklist:

- [next] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-06-10 12:39 UTC, klaasnicolaas commented
Please rebase to the `next` branch

2019-06-18 21:47 UTC, frenck requested changes
@austinmroczek this PR targets the wrong branch. It currently targets `current`, but it should target the `next` branch. Please change the target and rebase if needed.

2019-06-19 03:40 UTC, austinmroczek commented
Sorry I’ve been out of town. Hope to get to it this weekend

2019-06-29 16:50 UTC, austinmroczek commented
Changed to Next.  Thanks

2019-06-30 09:04 UTC, frenck requested changes

2019-06-30 09:04 UTC, frenck commented on source/_components/totalconnect.markdown
> +Starting in Home Assistant version 0.95, add the following lines to your `configuration.yaml`:
```suggestion
Add the following lines to your `configuration.yaml`:

```

2019-06-30 09:04 UTC, frenck commented on source/_components/totalconnect.markdown
>      password: YOUR_PASSWORD
Please remove the previous instructions, they are no longer valid.

2019-06-30 09:04 UTC, frenck commented on source/_components/totalconnect.markdown
> +You are highly encouraged to create a Total Connect user account specifically for Home Assistant.  It should not have full administrative privileges.
```suggestion
You are highly encouraged to create a Total Connect user account specifically for Home Assistant. It should not have full administrative privileges.
```

2019-06-30 23:14 UTC, austinmroczek commented
Made updates per recommendations.  Thanks

2019-07-01 06:46 UTC, frenck submitted a review, later dismissed
Thanks for the adjustments @austinmroczek! 👍 

✅ Approved. Can be merged as soon as the parent PR gets merged.

2019-07-09 23:20 UTC, klaasnicolaas commented
⚠️ We have I merge conflict

2019-07-18 23:14 UTC, frenck approved these changes

2019-07-18 23:14 UTC, merged