add surepetcare doc
home-assistant/home-assistant.github.io pull request #9590
Opened 2019-06-09 04:26 UTC by benleb

**Description:** Component for smart pet/cat flaps from Sure Petcare

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#24426

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-06-10 12:37 UTC, klaasnicolaas requested changes

2019-06-10 12:37 UTC, klaasnicolaas commented on source/_components/surepetcare.markdown
> +    required: true
```suggestion
    required: false
```

2019-06-10 12:37 UTC, klaasnicolaas commented on source/_components/surepetcare.markdown
> +      id:
add also `type: integer`

2019-06-10 12:37 UTC, klaasnicolaas commented on source/_components/surepetcare.markdown
> +      name:
Add also `type: string`

2019-06-10 12:37 UTC, klaasnicolaas commented on source/_components/surepetcare.markdown
> +      id:
Same

2019-06-10 12:37 UTC, klaasnicolaas commented on source/_components/surepetcare.markdown
> +      name:
Same

2019-06-10 12:37 UTC, klaasnicolaas commented on source/_components/surepetcare.markdown
> +    required: true
```suggestion
    required: false
```

2019-06-10 12:37 UTC, klaasnicolaas commented on source/_components/surepetcare.markdown
> +{% configuration %}
missing `device_class`, `icon` and `scan_interval`?

2020-01-07 14:25 UTC, frenck commented
Because of age, I've rebased the PR.

2020-01-07 14:26 UTC, frenck approved these changes

2020-01-07 14:50 UTC, merged