Add docs for Notion
home-assistant/home-assistant.github.io pull request #9665
Opened 2019-06-20 02:57 UTC by bachya

**Description:**

This PR adds docs for the forthcoming `notion` component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** https://github.com/home-assistant/home-assistant/pull/24634

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-06-20 10:51 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-07-09 08:30 UTC, MartinHjelmare commented on source/_components/notion.markdown
> +ha_release: 0.95
0.96

2019-07-09 08:32 UTC, MartinHjelmare commented on source/_components/notion.markdown
> +  - Sensor
There's a binary sensor platform too right?

2019-07-09 09:35 UTC, klaasnicolaas requested changes

2019-07-09 09:35 UTC, klaasnicolaas commented on source/_components/notion.markdown
> +## {% linkable_title Configuration %}
```suggestion
## Configuration
```

2019-07-09 17:43 UTC, MartinHjelmare approved these changes

2019-07-09 18:13 UTC, klaasnicolaas approved these changes

2019-07-09 18:14 UTC, klaasnicolaas commented
Time to merge it. Thnx for the PR! 👍

2019-07-09 18:15 UTC, merged