Updating tplink docs to include missing dimmer option.
home-assistant/home-assistant.github.io pull request #9689
Opened 2019-06-25 13:58 UTC by vangorra

**Description:**
Updating documentation to include dimmer config option.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-06-25 21:56 UTC, klaasnicolaas submitted a review, later dismissed

2019-06-25 21:56 UTC, klaasnicolaas commented on source/_components/tplink.markdown
> +- **Dimmer**
Dimmer isn't a device type / (old) platform

2019-06-27 18:08 UTC, rytilahti commented
LGTM, approval from @klaasnicolaas is still required.

2019-06-27 21:25 UTC, klaasnicolaas commented
This PR will be closed because the parent PR is closed 😉 Feel free to reopen it when there is new progress on the main repo.

2019-06-28 01:19 UTC, rytilahti commented
The parent PR was merged some time ago (and the linked PR is about the missing documentation for `dimmers`) which is to be corrected with this PR, so I'm reopening it.

2019-06-28 07:34 UTC, klaasnicolaas commented
Is this the right parent PR? https://github.com/home-assistant/home-assistant/pull/23668 
if yes, then this PR must get a rebase to the `Current` branch

2019-06-28 11:43 UTC, vangorra commented
home-assistant/home-assistant#23668 is the correct PR. Looks like I merged incorrectly as my PR now includes commits from other people. Weird.

2019-06-28 12:28 UTC, klaasnicolaas commented
It would have been better if you hadn't done that push because I could adjust the target branch. Now you will first have to remove the unrelated commits, you can do this by having your own branch perform a recent pull and push again to his PR.

2019-06-28 19:01 UTC, frenck requested changes
Hi there @vangorra!

This did not go totally according to plan I guess 😄 

Could you please rebase the PR and your commits onto the latest `current` branch to get rid of those unreleased commits? Thanks already! 👍

2019-06-29 14:16 UTC, vangorra commented
There we go, fixed it.

2019-06-29 15:09 UTC, frenck approved these changes
Thanks for updating @vangorra! 👍

2019-06-29 15:10 UTC, merged