added Testing section
home-assistant/home-assistant.github.io pull request #9767
Opened 2019-07-03 10:20 UTC by akasma74

I saw no such thing in docs and it constantly causes topics like this - https://community.home-assistant.io/t/condition-problems/124222.
Hope this addition is useful.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-07-03 12:10 UTC, klaasnicolaas requested changes

2019-07-03 12:10 UTC, klaasnicolaas commented on source/_docs/automation.markdown
> +If your automation uses templates in any part, you can do the following to make sure it works as expected:
Put the steps in a list with numbers?

2019-07-03 12:12 UTC, klaasnicolaas commented
![image](https://user-images.githubusercontent.com/20448157/60590483-623af200-9d9c-11e9-8d9d-88e15ecf4cf0.png)

Maybe you should make the text more readable and to the point. Describe how you can test your automations in different ways in a step by step guide?

2019-07-03 12:49 UTC, akasma74 reviewed
I hope this is more readable than it was

2019-07-13 15:00 UTC, klaasnicolaas commented
I have thought again about this PR and we think it is better to put your additions on this page: https://www.home-assistant.io/docs/automation/troubleshooting/

2019-07-13 19:50 UTC, akasma74 commented
I'm happy if the info is somewhere in docs so if you think it's better to be there, that's fine with me.
Probably add link to that page as well?

2019-08-18 02:47 UTC, klaasnicolaas commented
Are you still moving the text to the page we sugested?

2019-08-18 10:34 UTC, akasma74 commented
I've just done that, you can review.

2019-08-18 12:26 UTC, klaasnicolaas commented
I have made some changes to the text, find it quite *long-winded* to read and a reader must know what is meant at the end.

I also see that the troubleshooting page is not listed as an item in the docs menu, so we have to solve that.

2019-08-18 14:38 UTC, akasma74 commented
Couldn't see anything special so happy with your changes.

2019-08-21 21:16 UTC, frenck approved these changes

2019-08-21 21:19 UTC, klaasnicolaas approved these changes

2019-08-21 21:19 UTC, merged

2019-08-24 15:32 UTC, akasma74 reviewed
good catch ;)