Update VeSync Integration page
home-assistant/home-assistant.github.io pull request #9779
Opened 2019-07-04 22:13 UTC by webdjoe

**Description:**
Update the documentation for the functionality of the VeSync Integration

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** https://github.com/home-assistant/home-assistant/pull/24953

## Checklist:

- [X ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-07-05 21:48 UTC, klaasnicolaas submitted a review, later dismissed

2019-07-05 21:48 UTC, klaasnicolaas commented on source/_components/vesync.markdown
> + - /components/fan.vesync/
Please remove line 17

2019-07-05 22:30 UTC, webdjoe commented on source/_components/vesync.markdown
> + - /components/fan.vesync/
Line removed, thanks for the catch

2019-07-05 22:56 UTC, frenck requested changes

2019-07-05 22:56 UTC, frenck commented on source/_components/vesync.markdown
> +## {% linkable_title Supported Devices %}
```suggestion
## Supported Devices
```

Please remove all `linkable_title`'s

2019-07-06 23:20 UTC, webdjoe commented
Can you hold off on the approval, I'm working on the tests for the integration and adding another supported device?

2019-07-07 20:46 UTC, klaasnicolaas commented
Added WIP to the PR name and you have to resolve a merge conflict 😉

2019-07-23 21:44 UTC, MartinHjelmare commented on source/_components/vesync.markdown
> +time_zone:
This option was removed, right?

2019-07-24 00:25 UTC, webdjoe commented on source/_components/vesync.markdown
> +time_zone:
Forgot to push, all good to go

2019-07-24 21:56 UTC, frenck approved these changes
Thanks, @webdjoe! 👍

2019-07-24 22:01 UTC, merged