Update lutron_caseta.markdown
home-assistant/home-assistant.github.io pull request #9780
Opened 2019-07-04 23:07 UTC by djj211

Updated for new config point to work with my new pylutron_caseta mods and also support for the new caseta fan.

https://github.com/home-assistant/home-assistant/pull/24770
https://github.com/gurumitts/pylutron-caseta/pull/34

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-07-05 21:52 UTC, klaasnicolaas requested changes

2019-07-05 21:52 UTC, klaasnicolaas commented on source/_components/lutron_caseta.markdown
> +  - /components/fan.lutron_caseta/
Please remove line 25

2019-07-09 01:05 UTC, klaasnicolaas submitted a review, later dismissed

2019-07-09 01:05 UTC, klaasnicolaas commented on source/_components/lutron_caseta.markdown
> +## {% linkable_title Fan %}
```suggestion
## Fan
```

2019-10-02 16:56 UTC, frenck commented
Closing PR, since the parent PR has been closed.

2019-11-28 01:47 UTC, MartinHjelmare commented
Please rebase on latest next branch.

2019-11-28 07:52 UTC, frenck approved these changes
Rebased the PR and updated it during rebase to match the latest standards.

Thanks for the PR! 👍

2019-11-28 07:54 UTC, merged