Added SMSAPI documentation (new integration)
home-assistant/home-assistant.github.io pull request #9848
Opened 2019-07-13 21:42 UTC by zen

**Description:**

Added support for new notification component using polish SMSAPI service

**Pull request in [home-asistant](https://github.com/home-assistant/home-assistant) (if applicable):** WIll follow once it's ready (kind of chicken and egg problem)

## Checklist:

- [/ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [/ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-07-14 00:35 UTC, klaasnicolaas requested changes

2019-07-14 00:35 UTC, klaasnicolaas commented on source/_components/smsapi.markdown
> +ha_release: 0.96
```suggestion
ha_release: 0.97
```

2019-07-14 12:22 UTC, frenck commented on source/_components/smsapi.markdown
> +ha_release: 0.96
Done

2019-07-14 12:22 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-11-19 18:27 UTC, frenck commented
Closing PR, since the parent PR has been closed.

2019-11-19 18:27 UTC, closed without merging