Add IntesisHome climate platform documentation
home-assistant/home-assistant.github.io pull request #9935
Opened 2019-07-21 08:07 UTC by jnimmo

**Description:**
Add documentation for IntesisHome climate platform

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#25364

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-07-21 08:14 UTC, frenck requested changes
Thanks for the PR @jnimmo, a couple of small changes and we are good to go! 👍

2019-07-21 08:14 UTC, frenck commented on source/_components/climate.intesishome.markdown
> +### {% linkable_title Supported services %}
```suggestion
### Supported services
```

2019-07-21 08:14 UTC, frenck commented on source/_components/climate.intesishome.markdown
> +
```suggestion

## Configuration

```

2019-07-21 08:14 UTC, frenck commented on source/_components/climate.intesishome.markdown
> +If internet connectivity is lost the device will be marked as unavailable after 5 minutes.
```suggestion
If internet connectivity is lost, the device will be marked as unavailable after 5 minutes.
```

2019-07-21 08:14 UTC, frenck commented on source/_components/climate.intesishome.markdown
> +By default the component will be named using the friendly device name from the IntesisHome website or application.
```suggestion
By default, the component will be named using the friendly device name from the IntesisHome website or application.
```

2019-07-21 09:11 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-07-21 09:37 UTC, frenck requested changes
Sorry, @klaasnicolaas Just pointed me to another issue.
The filename is:
`source/_components/climate.intesishome.markdown`

This should be:
`source/_components/intesishome.markdown`

Could you please adjust that?

2019-07-21 09:46 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

2019-07-21 11:50 UTC, klaasnicolaas commented on source/_components/intesishome.markdown
> +Available services:
What you could do is a small description of what each service does, but that is extra and not something we demand 😄

2019-12-08 16:49 UTC, frenck commented
Rebased PR onto the latest `next` branch and moved the page to the new location in our documentation repository (`_integrations` folder).

2019-12-09 21:36 UTC, frenck approved these changes

2019-12-09 21:36 UTC, merged