Added velbus config flow documentation
home-assistant/home-assistant.github.io pull request #9955
Opened 2019-07-23 08:54 UTC by Cereal2nd

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#25308

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-07-23 10:13 UTC, frenck requested changes
Thanks for the PR @Cereal2nd! I've reviewed it and left some comments. Could you please take a look? Thanks 👍

2019-07-23 10:13 UTC, frenck commented on source/_components/velbus.markdown
> +layout: page
We don't use this anymore, please remove this line.

2019-07-23 10:13 UTC, frenck commented on source/_components/velbus.markdown
> +date: 2017-06-17 16.58
We don't use this anymore, please remove this line.

2019-07-23 10:13 UTC, frenck commented on source/_components/velbus.markdown
> +sidebar: true
We don't use this anymore, please remove this line.

2019-07-23 10:13 UTC, frenck commented on source/_components/velbus.markdown
> +comments: false
We don't use this anymore, please remove this line.

2019-07-23 10:13 UTC, frenck commented on source/_components/velbus.markdown
> +sharing: true
We don't use this anymore, please remove this line.

2019-07-23 10:13 UTC, frenck commented on source/_components/velbus.markdown
> +footer: true
We don't use this anymore, please remove this line.

2019-07-23 10:13 UTC, frenck commented on source/_components/velbus.markdown
> +There are 2 options in configuring the velbus component:
```suggestion
There are 2 options in configuring the Velbus integration:
```

2019-07-23 10:13 UTC, frenck commented on source/_components/velbus.markdown
> +- Via the Home Assistant user interface where it will let you enter the portstring to connect to the velbus bus.
```suggestion
- Via the Home Assistant user interface where it will let you enter the port string to connect to the Velbus bus.
```

2019-07-23 10:13 UTC, frenck commented on source/_components/velbus.markdown
> +  port: '<portstring>'
```suggestion
  port: 'PORT_STRING'
```

2019-07-23 10:13 UTC, frenck commented on source/_components/velbus.markdown
> +The portstring used in the user interface or the configuration file can have 2 formats:
```suggestion
The port string used in the user interface or the configuration file can have 2 formats:
```

2019-07-23 10:13 UTC, frenck commented on source/_components/velbus.markdown
> +## Port String
```suggestion
## Port string
```

2019-07-23 11:09 UTC, frenck commented
Thanks for the quick update @Cereal2nd! 👍 
Still, 2 left...

2019-07-23 11:13 UTC, Cereal2nd commented
Crap missed those ....

2019-07-23 11:29 UTC, frenck submitted a review, later dismissed
✅ Approved. Can be merged as soon as the parent PR gets merged.

2019-07-29 07:22 UTC, MartinHjelmare commented on source/_components/velbus.markdown
> +The porti string used in the user interface or the configuration file can have 2 formats:
The port string

2019-07-29 07:44 UTC, frenck commented on source/_components/velbus.markdown
> +The porti string used in the user interface or the configuration file can have 2 formats:
Addressed

2019-07-29 07:44 UTC, frenck approved these changes

2019-07-29 07:46 UTC, merged