Update installation.markdown
home-assistant/home-assistant.github.io pull request #9972
Opened 2019-07-25 08:55 UTC by Kanga-Who

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-07-25 09:20 UTC, frenck requested changes

2019-07-25 09:20 UTC, frenck commented on source/hassio/installation.markdown
> +The below script works for generic installs on x86/x64 machines, running an OS such as Ubuntu.
I think the original one was better, especially this is not true. 
Hass.io is not limited to x86/x64 machines. Please restore the original line.

2019-07-25 09:20 UTC, frenck commented on source/hassio/installation.markdown
> +Some installation types require flags to identify the computer type, for example, when using a Raspberry Pi 3, the flag `-- -m raspberrypi3` is required. The install script would then look like this.
Very useful section, maybe extend this a bit with the possible machine types?

2019-07-25 12:30 UTC, Kanga-Who commented
Thanks, @frenck.

I have made some changes and welcome your feedback.

2019-07-26 11:58 UTC, frenck approved these changes
Thanks, @Kanga-Who! 👍

2019-07-26 11:58 UTC, merged

2019-07-26 12:24 UTC, Kanga-Who commented
Great! Thanks @frenck.